ddtrace/api.py, ddtrace/encoding.py, setup.py, tests/test_integration.py, tox.ini
Adds support to the ``trace-agent`` API version ``0.3``. This new API uses msgpack as a new communication format by default. The API also support JSON encoding if users want to send their traces manually.
If a ``404`` is hit, it means that the API is not available and so we have to downgrade the API to a stable version (``JSONEncoder`` with the ``v0.2`` API at the time of writing).
The flow is:
* use ``MsgpackEncoder`` if the CPP implementation is available, otherwise fallback to ``JSONEncoder``
* at the first call (services or traces are the same), read the status code
* if the response is a ``404``, downgrade and re-try the call with the stable version
* in any other cases, keep the current encoder and API version (a ``5xx`` or ``4xx`` doesn't mean we should change the encoder because …
=> [core] provide support for trace-agent API v0.3

ddtrace/contrib/django/middleware.py
Checking for `django.contrib.auth` as an installed app is unnecessary
here since `_set_auth_tags` is graceful in itself by feature detecting
for `request.user`.
Refs: GH-134
=> django: Fix <1.7 compatibility in middleware

ddtrace/contrib/elasticsearch/patch.py, ddtrace/contrib/elasticsearch/transport.py, tests/contrib/elasticsearch/test.py
This makes it so queries with dates, decimals and UUIDs work.
https://github.com/elastic/elasticsearch-py/blob/d4efb81b0695f3d9f64784a35891b732823a9c32/elasticsearch/serializer.py#L24-L50
Right now any query with the above types will throw an exception:
```
File "/tmp/example/env/lib/python2.7/site-packages/elasticsearch_dsl/search.py", line 593, in execute
**self._params
File "/tmp/example/env/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
return func(*args, params=params, **kwargs)
File "/tmp/example/env/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 531, in search
doc_type, '_search'), params=params, body=body)
File "/tmp/example/env/lib/python2.7/site-packages/ddtrace/contrib/elasticsearch/patch.py", line 73, in _perform_request …
```
=> Use elasticsearch serializer

ddtrace/contrib/django/conf.py
Django can recast strings as unicode strings, which invalidate the input
for `getaddrinfo()`.
Massive help from @brettlangdon on this!!
Regular Python shell:
```python
>>> from ddtrace import tracer
>>> tracer.writer.api.port
7777
```
Django 1.9.4 shell on Python 2.7.12:
```python
>>> from ddtrace import tracer
>>> tracer.writer.api.port
u'7777'
>>> from socket import *
>>> getaddrinfo(tracer.writer.api.hostname, tracer.writer.api.port, 0,
SOCK_STREAM)
File "<console>", line 1, in <module>
error: getaddrinfo() argument 2 must be integer or string
>>> tracer.writer.api.port = 7777
>>> getaddrinfo(tracer.writer.api.hostname, tracer.writer.api.port, 0,
SOCK_STREAM)
[(2, 1, 6, '172.17.0.1', ('172.17.0.1', 7777))]
```
Signed-off-by: Mike Fiedler …
=> django: Fix configuration casting

ddtrace/contrib/dbapi/__init__.py, ddtrace/contrib/django/middleware.py, ddtrace/contrib/flask_cache/tracers.py, ddtrace/contrib/pylibmc/client.py, ddtrace/contrib/requests/patch.py, ddtrace/pin.py, ddtrace/span.py, ddtrace/tracer.py
so they don't flood by default.
=> log: downgrade high throughput log messages to debug

ddtrace/contrib/flask/middleware.py, tests/contrib/flask/test_flask.py
If a traced application returns a ``404``, the ``resource`` value that defaults to ``endpoint`` is ``None`` and so the trace is dropped by the ``dd-trace-agent``.
Documentation [here][1] (targets the latest version).
[1]: http://flask.pocoo.org/docs/0.12/api/#flask.Request.endpoint
=> [flask] fixed 404 pages

ddtrace/span.py, ddtrace/tracer.py, tests/test_tracer.py
It's technically possible to create a span without a service, and this is valid, it should inherit the service from its parent in that case. However root spans have no parent so it's impossible to infer/guess a valid name. This patch provides a default value (`python`) in that case.
=> [span] adding a default 'python' service is none is given

ddtrace/provider.py, tests/contrib/aiohttp/app/web.py, tests/contrib/aiohttp/test_request_safety.py, tests/contrib/asyncio/test_tracer.py, tests/contrib/asyncio/test_tracer_safety.py
Cover different test cases when concurrent calls are executed in asynchronous instrumentation.
=> [asyncio] safety tests when the default context_provider is wrongly used in async code

ddtrace/context.py, ddtrace/contrib/aiohttp/middlewares.py, ddtrace/span.py, ddtrace/tracer.py, tests/test_context.py, tests/test_span.py, tests/test_tracer.py
Major change that updates the ``Tracer`` API to provide:
* ``start_span(name, **kwargs)`` to create root spans
* ``start_child_span(name, parent, **kwargs)`` to create a child span from the given ``parent``
* ``start_child_from_context(name, context, **kwargs)`` to create a new span for the given ``context``; this span could be the root span or the child span of the ``context.current_span()``
* ``trace(name)`` that automatically handles everything, using the [ContextProvider][1] to retrieve the current ``Context`` and parent ``Span``
* not sure that we really need a ``start_child_from_context()``
* the ``start_child_span()`` may handle also the ``Context`` like it does in the [reference implementation of OT][2]
* the ``context`` kwarg can become a required argument as defined in [the OT …
=> updating the Tracer API

Rakefile, ddtrace/contrib/pyramid/trace.py, ddtrace/span.py, tests/contrib/pyramid/test_pyramid.py, tests/test_span.py
fixes a msgpack encoding issue when the error flag is set to true (as well as handling this case in general)
=> Pyramid errs

ddtrace/contrib/django/apps.py, ddtrace/contrib/django/conf.py, tests/contrib/django/app/settings.py, tests/contrib/django/test_cache_backends.py, tests/contrib/django/test_cache_client.py, tests/contrib/django/test_cache_views.py, tests/contrib/django/test_instrumentation.py
This PR will allow specifying global tracer tags in your django `DATADOG_TRACE` config object. We'd like to use this to pass the appropriate `env` tag to the tracer from our django configuration. Alternately, we could import the tracer and call `set_tags` somewhere during the django boot process, but it would be easier to able to specify it directly in the configuration.
Thanks!
=> Set global tracer tags from django DATADOG_TRACE

tests/test_integration.py
Because we have two different workers we don't know which one is the first to make the call, making our ``Workers`` tests flaky. This will retrieve the right call, using the ``endpoint`` as a matching string.
=> [core] fix workers threading tests

ddtrace/contrib/celery/__init__.py, ddtrace/contrib/celery/app.py, ddtrace/contrib/celery/patch.py, ddtrace/contrib/celery/task.py, ddtrace/contrib/celery/util.py, ddtrace/ext/__init__.py, tests/contrib/celery/test_app.py, tests/contrib/celery/test_task.py, tox.ini
Fixes #87 
This PR adds the contrib module for [celery](celeryproject.org) and the ability to patch the `celery` module to trace task execution.
Example:
```python
from ddtrace.contrib.celery import patch
patch()
import celery
app = celery.Celery()
@app.task
def my_task():
pass
my_task.delay()
```
I also have some example screenshots of how these traces look.
**Task being executed by a worker**
**Task execution started by a Flask request**
This one is more for fun, since it requires using redis with `celery` and having the redis library patching enabled.
**Redis calls to schedule celery task**
=> celery: add celery app and task patching

ddtrace/contrib/bottle/trace.py
When I attempt to install the tracer plugin in bottle, I get the following exception
'''
AttributeError: 'NoneType' object has no attribute 'set_service_info'
'''
This appears to be linked to the included change. In the scope provided, tracer would reference the __init__ argument. Instead, we want to tracer selected as a result of the previous line.
=> tracer should reference the result of the previous line

ddtrace/bootstrap/sitecustomize.py, ddtrace/commands/ddtrace_run.py, ddtrace/monkey.py, setup.py, tests/commands/ddtrace_run_debug.py, tests/commands/ddtrace_run_disabled.py, tests/commands/ddtrace_run_enabled.py, tests/commands/ddtrace_run_env.py, tests/commands/ddtrace_run_integration.py, tests/commands/ddtrace_run_no_debug.py, tests/commands/ddtrace_run_patched_modules.py, tests/commands/ddtrace_run_service.py, tests/commands/ddtrace_run_service_default.py, tests/commands/test_runner.py, tox.ini
Adds a command-line entrypoint that can run an arbitrary Python program with autopatching enabled:
1. `ddtrace-run python my_program.py` 
2. `ddtrace-run python manage.py runserver`
3. `ddtrace-run gunicorn myapp.wsgi:application`
will run `patch_all()` transparently without the need to change existing application code.
This works by adding a module to PYTHONPATH with a specialized `sitecustomize.py` file. This file executes patching code as early as possible in a module's lifetime.
Patchers for pylons, django and flask are linked below as cases in point where autopatching might be preferable to modifying app code
TODO:
=> scripts: add a command-line entrypoint for bootstrapping and patching

ddtrace/compat.py, ddtrace/compat_async.py, ddtrace/tracer.py, tests/contrib/aiohttp/app/web.py, tests/contrib/aiohttp/test_middleware.py, tests/contrib/asyncio/test_tracer.py
Allows the use of ``tracer.wrap()`` also for coroutines. In that way:
```python
@tracer.wrap()
async def coroutine():
return 'executed'
@tracer.wrap()
@asyncio.coroutine
def coroutine():
return 'executed'
```
If python 2 is used, that part of the code is never executed. The evaluation is done only once when the method `tracer.wrap()` is invoked.
We have to use a separated file to store the `yield from` call otherwise we got a Syntax Error in Python 2.
=> [asyncio] make the tracer.wrap() works with coroutines

ddtrace/contrib/aiohttp/__init__.py, ddtrace/contrib/aiohttp/middlewares.py, ddtrace/contrib/aiohttp/template.py, ddtrace/monkey.py, tests/contrib/aiohttp/app/web.py, tests/contrib/aiohttp/test_middleware.py, tests/contrib/aiohttp/test_request.py, tests/contrib/aiohttp/test_request_safety.py, tests/contrib/aiohttp/test_templates.py, tests/contrib/aiohttp/utils.py, tox.ini
Makes the ``aiohttp`` auto instrumentation more clear, providing:
* ``trace_middleware`` used to start recording the request span
* ``on_prepare`` signal to stop recording the request span
* ``trace_app(app, tracer, service='')`` function that automatically instrument the given app
* test matrix to support latest releases
Auto instrumentation becomes more readable:
```python
from aiohttp import web
from ddtrace.contrib.aiohttp import trace_app
app = web.Application(
middlewares=[
custom_middleware,
another_middleware,
]
)
app.router.add_get('/', home_handler)
trace_app(app, tracer, service='async-api')
web.run_app(app, port=8000)
```
When the request span is created, the ``Context`` for this logical execution is attached to the ``aiohttp`` request so that it can …
=> [aiohttp] convert stateful TraceMiddleware in a trace_middleware

ddtrace/context.py, tests/test_context.py, tests/test_span.py
When the root span of a trace is closed, it prints the number and the details of unfinished spans. This functionality is activated only if the ``tracer.debug_logging`` is set to `True`.
Actually the ``pprint()`` function is used so we have the full details of each unfinished spans.
=> [core] print the list of unfinished spans if the debug_logging is activated

ddtrace/contrib/django/__init__.py, ddtrace/contrib/django/conf.py, ddtrace/tracer.py, ddtrace/writer.py, docker-compose.yml, tests/contrib/django/test_instrumentation.py, tests/test_integration.py
**Breaking change**
The tracing client uses the port ``8126``. Using a Trace Agent older than version `5.11.0` will **not** work with the current version of the client.
=> [core] drop legacy port 7777 in favor of 8126

ddtrace/bootstrap/sitecustomize.py, ddtrace/contrib/pyramid/__init__.py, ddtrace/contrib/pyramid/patch.py, ddtrace/monkey.py, tests/contrib/pyramid/test_pyramid_autopatch.py, tox.ini
Adds pyramid autopatching - disabled in `patch_all()` by default, but enabled under `ddtrace-run`
the existing pyramid test suite has been replicated to run without explicit patching.
instead it runs under `ddtrace-run nosetests ...` and behaves identically
=> pyramid: add autopatching

ddtrace/bootstrap/sitecustomize.py, ddtrace/contrib/falcon/__init__.py, ddtrace/contrib/falcon/middleware.py, ddtrace/contrib/falcon/patch.py, ddtrace/monkey.py, tests/contrib/falcon/test_autopatch.py, tox.ini
Add an autopatcher into the falcon integration. The autopatcher will
_not_ run by default under `patch_all()` but will run by default under
`ddtrace-run`
Also replicates the existing falcon test case to run without explicit
patching, instead under `ddtrace-run`
=> falcon: add autopatching

ddtrace/bootstrap/sitecustomize.py, tests/commands/ddtrace_run_disabled.py, tests/commands/ddtrace_run_hostname.py, tests/commands/test_runner.py
this allows overriding the point of submission of the default tracer
when using `ddtrace-run <my_script>`
=> respect DATADOG_TRACE_AGENT_HOSTNAME and DATADOG_TRACE_AGENT_PORT in ddtrace-run

ddtrace/contrib/pyramid/patch.py, tests/contrib/pyramid/test_pyramid_autopatch.py
pyramid's name_resolver relies on the Configurator not fudging
it's import path, since this is consulted to retrieve models, views etc.
this change uses `wrapt.wrap_function_wrapper` to ensure
pyramid.config.Configurator remains introspectable
=> pyramid: use a function wrapper to maintain introspection abilities

ddtrace/contrib/pyramid/trace.py, tests/contrib/pyramid/test_pyramid.py
This PR sets the following tags for the pyramid.request span:
1. http.METHOD
2. pyramid.route.name
=> Set pyramid request span tags for HTTP method and route name

circle.yml
When a branch is pushed, CircleCI builds and releases:
* `develop`: the latest package and dev docs `/trace-dev/docs`
* `master`: the latest package
* `vX.X.X`: the latest official docs (official package releases are separated from CircleCI)
=> [ci] master merge doesn't build the development docs

tox.ini
The CI tests `mysql-connector<2.2` because the latest version requires a full `protobuf` configuration. This fixes our CI `contrib` tests.
=> [mysql] CI tests only versions < 2.2

ddtrace/contrib/django/apps.py
Provide a unique app label for our tracing Django app: `datadog_django`
=> [django] provide a unique datadog_django app label

ddtrace/tracer.py, tests/test_tracer.py
Adds a `wrap_executor` callback to the `Tracer.configure()` method, so that a contrib module can change the behavior of `Tracer.wrap()`. This is required because in some frameworks (i.e. Tornado), the `Tracer.wrap()` must handle "coroutine" executions that returns immediately a `Future` instance. On the other hand, we can't pollute the `Tracer.wrap()` with `contrib` code and PR goals are:
* if a `wrap_executor` is not defined, the `Tracer.wrap()` behaves as usual for regular functions or `asyncio` coroutines
* if a `wrap_executor` is defined, decorated functions are handled using this callable
```python
def wrap_executor(tracer, fn, args, kwargs, span_name, service, resource, span_type):
with tracer.trace(span_name, service=service, resource=resource, …
```
=> [core] provide a wrap_executor

ddtrace/contrib/boto/__init__.py, ddtrace/contrib/botocore/__init__.py, docs/index.rst
- added descriptions in __init__
- compatible versions
- automodule
=> Adding doc in pypi for boto/botocore

ddtrace/contrib/boto/patch.py
Using `inspect.py`'s `getouterframes()` function can have a performance cost; in the attached flamegraph, it looks like it spends as much time in there as it does fetching.
Luckily, it looks like we only need the name of the frame above, which does not require a full call to `getouterframes()`. This PR asks for the parent of the parent's name, and uses that.
=> [boto] Use frames directly without calling getouterframes()

docs/index.rst
I wrote some examples for a cross service tracing, if as this example, passed as a string, tracer-agent will got some error:
```
2017-03-30 10:04:52 ERROR (receiver_logger.go:21) - cannot decode v0.3 traces payload: json: cannot unmarshal string into Go value of type uint64
```
It's a type mismatch.
=> fix sample code issue

ddtrace/contrib/elasticsearch/__init__.py
Pin is now set on the Transport object found on Elasticsearch.transport, updating doc
=> changing doc after pin change

ddtrace/contrib/aiohttp/patch.py, ddtrace/contrib/elasticsearch/patch.py, ddtrace/contrib/redis/patch.py
All contribs  needing an `_unwrap` method had it written in there patch.py.
For boto/botocore I had already set them to call `unwrap` from ddtrace.util, quick fix so that the other contribs (aiohttp/elasticsearch/redis) are also refactored. The others don't use this function
=> code factorising _unwrap

ddtrace/api.py, tests/test_integration.py
Pre-sampling on the agent side requires this header to be here,
to know how many traces are in the payload without decoding the
payload for real.
=> [presampler] Adding X-Datadog-Trace-Count header

ddtrace/contrib/mysql/__init__.py
The current `mysql` integration supports only `mysql-connector` package. Other libraries such as `MySQL-Python`, must be handled differently. However, the current integration loader ( available in the `monkey` module) doesn't give the right feedback to developers, and indeed the error output is misleading.
```
import logging
logger = logging.getLogger()
logger.setLevel(logging.DEBUG)
from ddtrace import patch, patch_all
patch_all()
```
The library `MySQL-Python` is installed in the environment so `patch_all()` should not find this integration.
**Before the patch**
```
DEBUG:root:failed to patch mysql: module not installed
```
It seems that `mysql` is not installed while it is.
**After the patch**
```
DEBUG:root:failed to patch mysql: integration not available
```
The integration `mysql` …
=> [mysql] distinguish mysql-python instrumentation

ddtrace/contrib/mysql/__init__.py
Uses a `logging.debug` instead of the loader exception handler. This allows to have both mysql connectors in the Python environment. Only `mysql-connector` will be used.
Having `mysql-python` and `mysql-connector` installed in the same environment:
**Before the patch**
```
DEBUG:root:failed to patch mysql: integration not available
INFO:root:patched 1/11 modules (sqlite3)
```
**After the patch**
```
DEBUG:root:failed to patch mysql-python: integration not available
INFO:root:patched 2/11 modules (mysql,sqlite3)
```
Having only `mysql-python` installed in the environment:
**Before the patch**
```
DEBUG:root:failed to patch mysql: integration not available
INFO:root:patched 1/11 modules (sqlite3)
```
**After the patch**
```
DEBUG:root:failed to patch mysql-python: integration not available …
```
=> [mysql] use a logging message instead of an ImportError

ddtrace/contrib/pylons/middleware.py
This happens if the request triggers a timeout for example. In that case, no `http_status` tag is set on the span.
=> pylons: catch BaseException since a SystemExit might've been raised.

ddtrace/contrib/pyramid/trace.py
This happens if the request triggers a timeout for example. In that case, no `http_status` tag is set on the span.
=> pyramid: catch BaseException since a SystemExit might've been raised.

ddtrace/contrib/pylons/middleware.py
9569c72 fixes the issue with missing hHTTP status code, but `getattr(e, 'code', 500))` returns 1 on SystemExit exceptions. This commit makes sure it is set to 500.
=> pylons: in case of SystemExit, set HTTP status code to 500.

tox.ini
`moto` version 1.0.0+ introduces a breaking change so that all moto decorator stops working. This patch pin the library to the latest working version.
=> [ci] pin moto library version

Rakefile, ddtrace/contrib/pylons/__init__.py, ddtrace/monkey.py, ddtrace/tracer.py, docs/index.rst, tox.ini
* fixes `pylons` documentation because it's not built in the current master. `pylons` was imported when building the doc from the docstring:
```
/home/ubuntu/dd-trace-py/docs/index.rst:138: WARNING: autodoc: failed to import module u'ddtrace.contrib.pylons'; the following exception was raised:
File "/home/ubuntu/virtualenvs/venv-system/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
__import__(self.modname)
File "/home/ubuntu/dd-trace-py/ddtrace/contrib/pylons/__init__.py", line 19, in <module>
from .patch import patch
File "/home/ubuntu/dd-trace-py/ddtrace/contrib/pylons/patch.py", line 9, in <module>
import pylons.wsgiapp
ImportError: No module named pylons.wsgiapp
```
* fixes also minor warnings and errors when building …
=> [docs] fix Pylons and monkey.py docstrings

ddtrace/contrib/flask/middleware.py, ddtrace/contrib/flask/patch.py, tests/contrib/flask/test_signals.py
When connecting to a signal, Blinker stores by default a weak reference that may be removed when it goes out of scope or it is garbage collected.
In many Flask application it's reasonable that the `traced_app` shown in our examples, is not stored somewhere and so the object will be lost (and so our signals) during a garbage collection. If that happens, Blinker signals are automatically disconnected and Flask will not be instrumented.
This PR avoids using weak references through the `weak=False` kwarg.
=> [flask] avoid using weak references when instrumented via Blinker

ddtrace/contrib/flask/middleware.py, tests/contrib/flask/test_flask.py
Flask integration doesn't add the http.method (GET, POST, etc...) in the flask.request span.
This PR adds the http method to flask spans.
=> Add http method to flask

ddtrace/contrib/mysql/__init__.py, ddtrace/monkey.py
Closes #280 
Uses `logging.getLogger(__name__)` everywhere instead of using the root logger.
**Testing code**
```python
import logging
logging.basicConfig(level=logging.DEBUG)
from ddtrace import patch, patch_all
patch_all(fake_integration=True)
```
**Output**
```
DEBUG:ddtrace.encoding:using Msgpack encoder
DEBUG:ddtrace.writer:resetting queues. pids(old:None new:42)
DEBUG:ddtrace.writer:starting flush thread
DEBUG:ddtrace.monkey:failed to patch fake_integration: integration not available
DEBUG:ddtrace.monkey:failed to patch mongoengine: module not installed
INFO:ddtrace.monkey:patched 10/12 modules (aiohttp,cassandra,celery,elasticsearch,mysql,psycopg,pylibmc,pymongo,redis,sqlite3)
```
=> [logging] use specific logger instead of the root one

ddtrace/contrib/httplib/__init__.py, ddtrace/contrib/httplib/patch.py, ddtrace/monkey.py, tests/contrib/httplib/test_httplib.py, tests/contrib/httplib/utils.py, tox.ini
This PR adds in tracing support for the base `httplib.HTTPConnection` (Py2) and `http.lib.HTTPConnection` (Py3) classes.
Patching these classes allows us expand our support for tracing external HTTP requests.
This tracing is setup similar to the tracing for `requests`. There is no service being set, and we are capturing the basic tags of `http.method`, `http.status_code`, and `http.url`.
```python
from ddtrace.contrib.httplib import patch
patch()
import urllib
resp = urllib.urlopen('http://www.datadog.com/')
import urllib2
resp = urllib2.urlopen('http://www.datadog.com/')
import urllib.request
resp = urllib.request.urlopen('http://www.datadog.com/')
import urllib.request
resp = urllib.request.urlopen('http://www.datadog.com/')
```
=> httplib: add patching for httplib and http.lib

ddtrace/contrib/gevent/greenlet.py, tests/contrib/gevent/test_tracer.py
Creates a new `Context` instance when a `Greenlet` is created so that the current active span (and the sampling) is propagated, while the hierarchy will be different for each one.
* In the previous approach, each `Greenlet` propagates the same `Context`, but this causes new greenlets to have the previous greenlets `Span` as a parent, instead of the common one.
* tests have been changed to represent the new state, so if we create 3 greenlets, 3 different traces will be generated
=> [gevent] create a new Context when a new Greenlet is created

ddtrace/contrib/util.py, tests/contrib/django/app/views.py, tests/contrib/django/test_middleware.py, tests/contrib/test_utils.py
In some cases, getting the module of a callable item does not make sense, and this breaks our instrumentation as we used this to set up the resource request (from the view `__module__.__name__`). This patch tries to provide reasonable defaults when `__module__` is not here. Additionally, has a tests for the `lambda` case, this one was not reported, but technically, it could expose the problem too.
=> [contrib:django] fixing django request resource when view is partial

README.rst, ddtrace/ext/system.py, ddtrace/tracer.py, tests/benchmark.py, tests/contrib/celery/test_task.py, tests/contrib/django/test_cache_backends.py, tests/contrib/django/test_cache_client.py, tests/contrib/flask_cache/test.py, tests/contrib/httplib/test_httplib.py, tests/contrib/mysql/test_mysql.py, tests/test_tracer.py, tests/util.py
This will make it possible to associate traces with running processes on the host.
=> Add process id in root spans metadata

ddtrace/contrib/django/__init__.py, ddtrace/contrib/django/conf.py, ddtrace/contrib/django/db.py, tests/contrib/django/test_connection.py, tests/contrib/django/utils.py
When I have many django projects with one database, all data goes to `defaultdb` service.
=> create settings to append database prefix name

ddtrace/context.py, ddtrace/contrib/asyncio/helpers.py, ddtrace/contrib/asyncio/patch.py, tests/contrib/asyncio/test_helpers.py, tests/contrib/asyncio/test_tracer.py
* minor refactoring for in-process context propagation for `asyncio`
* refactoring unittests
* `patch()` and `unpatch()` methods don't use any kwarg
=> [asyncio] improved context propagation

docs/index.rst
Updates docs about used headers for experimental distributed tracing. It changes the header so that they're compliant with:
* [aiohttp headers](https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/aiohttp/middlewares.py#L12-L13)
* [grpc (go client)](https://github.com/DataDog/dd-trace-go/blob/master/tracer/contrib/tracegrpc/grpc.go#L15-L19)
=> [docs] correction for distributed tracing headers

ddtrace/api.py, ddtrace/contrib/flask/middleware.py, tests/contrib/flask/test_flask.py
Based on tests, `span.set_traceback()` works perfectly, I kept the former way in case my test coverage wasn't enough. I could also drop it.
=> Attach stack trace to Flask errors

docs/index.rst
Lists the auto instrumented library because not all modules are patched when using `patch_all()`.
=> [docs] add the list of auto-instrumented modules

ddtrace/contrib/aiobotocore/patch.py, tests/contrib/aiobotocore/test_35.py, tox.ini
When using `async with`, the proxy object isn't returned so the client is not traced. Example:
```python
client = aiobotocore.get_session().create_client('s3')
response = await client.get_object(Bucket='something')
async with response['Body'] as stream:
await stream.read()
```
=> [aiobotocore] update async with context manager

ddtrace/contrib/elasticsearch/__init__.py
Since https://github.com/DataDog/dd-trace-py/pull/238
We can use a more common way of importing ES. So updating the doc (the tests already do it) to suggest this syntax instead.
=> Use from elasticsearch import ... syntax in doc

circle.yml
CircleCI has only some Python versions and `3.6.0` was removed. We will update all language versions and dependencies later in another PR, since this is only a quick-fix.
=> [ci] update Python version

tests/contrib/aiobotocore/utils.py
Mostly related to CircleCI builds, this "fix" is required to let `aiobotocore` tests pass.
=> [ci] use localhost for aiobotocore calls

tests/contrib/aiobotocore/utils.py
Uses hard-coded testing credentials so that no `.aws/credentials` is required when launching tests (both locally or via CI).
=> [ci] add AWS credential so that they are not required in forks

docs/index.rst
Make it a bit clearer that the environment variables are specific to the ddtrace-run command line utility. 
Also adds a section about how to change the hostname/port of where to send Traces using the Tracer object.
=> Adds section about updating the hostname/port

ddtrace/contrib/django/apps.py, tests/contrib/django/test_tracing_disabled.py
This fix #304 
I have tested locally that it fixes the bug, but I haven't added a unit test since I haven't found a simple way to do it. It requires running the unit tests with a different config at startup and I'm not convinced it's worth adding new test envs only to check on this.
=> Fix initialization order in Django app

ddtrace/contrib/mysql/__init__.py
=> [mysql] remove docs typo

tests/contrib/httplib/test_httplib.py, tests/contrib/requests/test_requests.py
Switch to http://httpbin.org/ for our httplib and requests tests there is a regression on http://httpstat.us/.
=> Switch to httpbin for tests

ddtrace/contrib/pylons/middleware.py, tests/contrib/pylons/test_pylons.py
In Python, there is a subtle but important distinction between `raise e` and `raise`: the former has a traceback originating with the current location, whereas the latter uses the original traceback from before the exception was caught. In this case, I think it makes significantly more sense to preserve the original traceback.
=> Reraise exception with original traceback

ddtrace/contrib/pyramid/__init__.py, ddtrace/contrib/pyramid/patch.py, ddtrace/contrib/pyramid/trace.py, tests/contrib/pyramid/__init__.py, tests/contrib/pyramid/test_pyramid.py, tests/contrib/pyramid/test_pyramid_autopatch.py, tox.ini
Forcing autocommit to `True` changes the behavior of the `Configurator`and a previously working application might break when we patch it since it becomes sensitive to the order of the configuration methods calls. (we had a bug report on this)
AFAIK autocommit was needed to avoid conflicts when the tween was added several time. (for instance this happens when using `include`since it calls `Configurator.__init__' another time.) Adding our tween in an `include` changes the conflict resolution rules used by pyramid and avoid that problem.
=> Disable autocommit in pyramid patching

ddtrace/contrib/flask/middleware.py, tests/contrib/flask/test_flask.py, tests/contrib/flask/test_templates/render_err.html
The flask instrumentation was not closing spans if an exception
happened during the rendering of a template for flask > 0.10
To fix the issue I chose to always use `_patch_render` because the `template_rendered` signal is not called if an exception occurs during the rendering. Another possibility would be to check if a we have a span for template rendering when we get the `got_request_exception`. It has the advantage of leveraging signals instead of wrapping a private method when we can but I don't like how it spreads the logic between two seemingly unrelated signal handlers, IMO it makes the code more complicated.
=> Fix flask instrumentation not closing spans

tox.ini
This is minor but since the Cassandra tests are the flakiest this should help make the CI great again :)
=> Exclude cassandra from generic contrib tests

ddtrace/contrib/django/__init__.py
Based on #314, we don't need to add the Django Datadog middleware because it's done automatically. We updated the docs, but forget to clean the first sentences.
=> [django] update docs: adding the middleware is not required

ddtrace/contrib/psycopg/connection.py, ddtrace/contrib/pylons/middleware.py
To have better sampling ratio, the information about the service should be send to the trace constructor. This patches fixes for pylons and psycopg.
=> [distributed sampling] setting service as early as possible

ddtrace/contrib/asyncio/helpers.py, ddtrace/contrib/asyncio/provider.py, ddtrace/contrib/gevent/greenlet.py, ddtrace/contrib/gevent/provider.py, ddtrace/contrib/tornado/__init__.py, ddtrace/contrib/tornado/application.py, ddtrace/contrib/tornado/patch.py, ddtrace/contrib/tornado/stack_context.py, ddtrace/provider.py, ddtrace/tracer.py, tests/contrib/asyncio/test_tracer.py, tests/contrib/gevent/test_tracer.py, tests/contrib/tornado/test_stack_context.py, tests/test_tracer.py
Changes the way our `ContextProvider`s work. Before the change, the context provider was a callable that returns the current active `Context`. After the change, we have a manager that can get/set the current context. This allows an API similar to:
```python
trace_id, span_id, sampling_priority = get_params_somehow()
ctx = Context(trace_id=trace_id, span_id=span_id, sampling_priority=sampling_priority)
tracer.context_provider.activate(ctx)
with tracer.trace('web.request') as span:
assert span.trace_id == trace_id
```
This work must extend the API to all current Providers:
* DefaultContextProvider
* AsyncioContextProvider
* GeventContextProvider
* TornadoContextProvider
`__call__` method become a proxy to `context_provider.active()` that returns the current active `Context`. This has been …
=> [core] update the context propagation API

ddtrace/bootstrap/sitecustomize.py, ddtrace/contrib/pyramid/__init__.py, ddtrace/contrib/pyramid/constants.py, ddtrace/contrib/pyramid/patch.py, ddtrace/contrib/pyramid/trace.py, tests/contrib/pyramid/test_pyramid.py, tests/contrib/pyramid/test_pyramid_autopatch.py
This addresses #313 
There are two ways to add tweens to a pyramid app, either through the `config.add_tween` method, or by passing a 'pyramid.tweens' setting. In case the 'pyramid.tweens' setting is used, all calls to `config.add_tween` are ignored. This is what happened here.
To fix the issue I've chosen to automatically add our tween to the 'pyramid.tweens' setting when the app is automatically instrumented with ddtrace-run, and for user that instrument manually their application I've updated the doc to clarify that if the tweens are set with the 'pyramid.tweens' setting, our tween must be added there too. (that behavior is consistent with what is done for the native exception view: https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/hooks.html#explicit-tween-ordering)
I …
=> Fix bug in pyramid, the application was not traced when the tween list was explicitely specified

ddtrace/contrib/django/conf.py, tests/contrib/django/test_instrumentation.py, tests/util.py
Enable to override agent hostname and port via `DATADOG_TRACE_AGENT_HOSTNAME` and `DATADOG_TRACE_AGENT_PORT` .
To make dd-trace-py for Django work as expected.
Currently, dd-trace-py for Django ignores those environment variables in spite of [the document](http://pypi.datadoghq.com/trace/docs/#get-started) says it can be override via those environment variables.
This PR fixes https://github.com/DataDog/dd-trace-py/issues/332
=> Respect env agent host and port in Django apps

ddtrace/constants.py, ddtrace/context.py, ddtrace/sampler.py, ddtrace/span.py, ddtrace/tracer.py, docs/index.rst, tests/contrib/aiohttp/test_middleware.py, tests/test_context.py, tests/test_sampler.py, tests/test_span.py
Move the `sampling_priority` fully to the `Context` object and document its usage.
- Remove priority from the span, moving it fully to the Context.
- Now the `SAMPLING_PRIORITY_KEY` metric is set when we flush the context.
- Provide a setter to allow changing the Context priority.
- Document how the priority sampling work and how to manually update the priority
- Update the tests accordingly
=> Move sampling priority fully to the context

tox.ini
Avoid https://github.com/psycopg/psycopg2/issues/594
A move to CircleCI 2 would potentially fix it. Until then, disable these.
=> Disable old psycopg2 tests until CircleCI is fixed

ddtrace/contrib/django/__init__.py, ddtrace/contrib/django/conf.py, ddtrace/contrib/django/middleware.py, ddtrace/propagation/http.py, docs/index.rst, tests/contrib/django/test_middleware.py
- Add support for distributed tracing to Django, reading incoming HTTP headers
- Under the `DISTRIBUTED_TRACING` option, True by default
- Add test to ensure it works well when turned off and on.
=> Add distributed sampling support to Django

ddtrace/contrib/flask/__init__.py, ddtrace/contrib/flask/middleware.py, docs/index.rst, tests/contrib/flask/test_flask.py
Extend work from https://github.com/DataDog/dd-trace-py/pull/331 and https://github.com/DataDog/dd-trace-py/pull/355 to bring distributed tracing to Flask.
- Use the HTTPPropagator
- Add test
- Disable it by default
To be discussed: what do we think of this `use_distributed_tracing` API?
=> Bring distributed tracing to Flask

ddtrace/contrib/tornado/__init__.py, ddtrace/contrib/tornado/application.py, ddtrace/contrib/tornado/handlers.py, docs/index.rst, tests/contrib/tornado/test_tornado_web.py
- Use HTTPPropagator to propagate header in tornado web
- Add tests
- Have it off by default
- Document it + improve overall HTTP distributed tracing documentation
=> Implement distributed tracing for Tornado web

ddtrace/propagation/http.py
- Don't serialize `None` priority when not defined
- Catch `extract` exceptions and log them
=> Make HTTPPropagator safe

ddtrace/writer.py
It is sometimes interesting to know what endpoint the library is actually hitting. A typical use case is a Docker or Kubernetes environment, where the client gets its parameters through environment variables. It's then convenient to have a clear log of where the data is sent to.
=> [tracer:writer] slightly more explicit log on 'cannot send' error

tests/wait-for-services.py
This fixes the error reported and ignored by CircleCI:
```
WARNING:command failed but result from testenv is ignored
cmd: InvocationError: '/root/project/.tox/wait/bin/python tests/wait-for-services.py mysql'
```
in mysqlconnector test. It cause test failure sometimes.
Thanks.
=> Wait service correctly on CircleCI

ddtrace/contrib/bottle/__init__.py, ddtrace/contrib/bottle/trace.py, tests/contrib/bottle/test_distributed.py
Read the HTTP headers to propagate context and build proper distributed traces when using Bottle.
=> [contrib:bottle] get distributed tracing context

ddtrace/contrib/requests/__init__.py, ddtrace/contrib/requests/patch.py, ddtrace/ext/http.py, docs/index.rst, tests/contrib/requests/test_requests_distributed.py, tox.ini
This is a rework on top of https://github.com/DataDog/dd-trace-py/pull/356
It adds:
* recent context/propagator support
* forwards the sampling prority
* by default, this is disabled, needs to be activated by setting a session attribute (`distributed_tracing_enabled`)
* a small bug-fix in common code, `None` type would be converted in `'Node'` string when not defined
=> [contrib:requests] propagate distributed sampling context

docs/index.rst
We wrote a wrong kwarg in the documentation, it is `priority_sampling`.
=> [docs] fixed priority_sampling kwarg in the configure method

ddtrace/tracer.py, tests/test_integration.py
When custom hostname and port is required (typically, running the app in a container) calling configure() without specifying explicitly hostname and port actually sets it back to the default `localhost:8126` value. Which is usually not what you want when it was set up explicitly before, the
named parameter interface suggest you can, indeed, omit parameters.
=> [tracer] keep hostname and port when calling configure()

ddtrace/contrib/httplib/patch.py, tests/contrib/httplib/test_httplib.py
Fix https://github.com/DataDog/dd-trace-py/issues/323
=> contrib.httplib.patch: Don't overwrite return value

ddtrace/ext/priority.py, ddtrace/tracer.py, docs/index.rst, tests/test_context.py, tests/test_span.py
Allow usage of `-1` as a priority sampling value. Here there's no real impact, it's mostly about writing tests ensuring this works and updating the docs.
=> [dual sampling] support -1 as a priority sampling value

setup.py
The classifiers are not only useful for indicating the supported Python versions for a human, but they are also consumed by tools such as `caniusepython3` for indicating if a project supports Python 3 or not.
=> Add missing trove classifiers for Pypi

ddtrace/contrib/psycopg/patch.py, tests/contrib/psycopg/test_psycopg.py, tox.ini
`register_type` was patched in #96, though only in `psycopg.extensions`.
The function is defined in `psycopg2._psycopg` and imported in `psycopg2._json`
neither of them are patched and if used cause a `TypeError`.
=> psycopg2: Patch all imports of register_type

.circleci/config.yml, tox.ini
Some versions of `aiohttp` may use `yarl>=1.0` that drops some methods. In that case it's not possible to run tests for `aiohttp` because of:
```
File "/root/project/.tox/py34-aiohttp12-aiohttp_jinja012/lib/python3.4/site-packages/aiohttp/web_urldispatcher.py", line 14, in <module>
from yarl import URL, quote, unquote
ImportError: cannot import name 'quote'
```
Pinning `yarl` to version 0.18 fixes the problem.
=> [ci] force downgrade of yarl for aiohttp tests

.circleci/config.yml, ddtrace/contrib/pyramid/trace.py, tests/contrib/pyramid/app/__init__.py, tests/contrib/pyramid/app/web.py, tests/contrib/pyramid/test_pyramid.py, tests/contrib/pyramid/test_pyramid_autopatch.py, tox.ini
As defined in [pyramid docs](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/httpexceptions.html), each `HTTPException` class is also a `Response` object.
It also adds Pylons 1.9 to the test matrix.
Original PR #386: @TylerLubeck
=> Use pyramid HTTPExceptions as valid response types

ddtrace/contrib/pyramid/__init__.py, ddtrace/contrib/pyramid/constants.py, ddtrace/contrib/pyramid/trace.py, tests/contrib/pyramid/test_pyramid.py, tests/contrib/pyramid/test_pyramid_autopatch.py
Introduces distributed tracing for `pyramid`. To activate, add the following to your pyramid settings:
```python
from pyramid.config import Configurator
from ddtrace.contrib.pyramid import trace_pyramid
settings = {
'datadog_trace_service' : 'my-web-app-name',
'datadog_distributed_tracing' : True,
}
config = Configurator(settings=settings)
trace_pyramid(config)
```
=> [pyramid] add distributed tracing

ddtrace/contrib/requests/__init__.py, ddtrace/contrib/requests/patch.py, tests/contrib/requests/test_requests.py, tests/contrib/requests/test_requests_distributed.py
* Adds protection to avoid double `patch()`
* Adds `unpatch()` to remove tracing
* Patches `__init__` so that we can set later (another PR) settings from env vars
=> [requests] add unpatch and double-patch protection

ddtrace/contrib/pyramid/patch.py, ddtrace/util.py, tests/contrib/pyramid/test_pyramid_autopatch.py, tests/contrib/test_utils.py, tests/test_utils.py, tox.ini
Adds `DATADOG_PYRAMID_DISTRIBUTED_TRACING` environment variable to activate `pyramid` distributed tracing. This functionality is experimental because we should provide it consistently across all integrations, that's why it has not been documented.
The long-term plan is to provide a `Configuration` object that is initialized based on env variables / hard-coded settings.
=> [pyramid] add DATADOG_PYRAMID_DISTRIBUTED_TRACING env var

ddtrace/contrib/requests/patch.py
Adds `DATADOG_REQUESTS_DISTRIBUTED_TRACING` env variable to activate distributed tracing for `requests`. The module still requires the use of `DATADOG_PATCH_MODULES=requests:true` since it's not instrumented by default.
This env variable is flagged as experimental, so it could change in the future.
=> [requests] add DATADOG_REQUESTS_DISTRIBUTED_TRACING 

ddtrace/context.py, ddtrace/contrib/tornado/__init__.py, ddtrace/contrib/tornado/application.py, ddtrace/contrib/tornado/compat.py, ddtrace/contrib/tornado/futures.py, ddtrace/contrib/tornado/patch.py, ddtrace/contrib/tornado/stack_context.py, tests/contrib/tornado/test_executor_decorator.py, tests/contrib/tornado/test_safety.py, tests/contrib/tornado/utils.py, tests/contrib/tornado/web/app.py
In general, a new Thread is created every time synchronous work must be done. To achieve that, a common approach is to use `concurrent.futures.ThreadPoolExecutor` so that a specific `Executor` implementation handles the thread pool. This results in:
```python
class MyHandler(TornadoHandler):
executor = ThreadPoolExecutor(NUM_THREADS)
def query(self):
@gen.coroutine
def get(self, endpoint):
response = yield self.executor.submit(query)
return response
```
Unfortunately, if the `ThreadPoolExecutor` is used directly without the `tornado.concurrent.run_on_executor` decorator, we miss instrumentation to propagate the `Context` from the `MainThread` to the new thread.
This implementation ensures that the `Context` is properly propagated.
It works for the current test suite, though the test is …
=> [tornado] patch concurrent.futures if available

ddtrace/contrib/flask/middleware.py, tests/contrib/flask/test_flask.py
This is a refactoring of how we handle flask requests. We don't use
signals to teardown requests and instead use the `teardown_request`
handler. This always runs so it's a more reliable way of closing the
request. Signals are only used to annotate spans that received an error
(which a user may handler), and not to finish requests that may have been
successful.
This also reduces the difference between signal enabled and disabled
mode which is nice.
This should fix #390.
=> flask: don't override code of already handled errors

ddtrace/encoding.py, tests/test_integration.py
`msgpack-python` dependency has been renamed in `msgpack`. We have already a contribution PR (https://github.com/DataDog/dd-trace-py/pull/413) that updates our dependency but it could lead to some unexpected behaviors as defined here: https://github.com/DataDog/dd-trace-py/pull/413#discussion_r168746581
This PR makes the implementation safer in a specific edge case (only found via tests, it's not happening in real), and we're disabling two tests that are failing because the C implementation seems not available in the latest `msgpack-python` versions (0.5.x). This work is temporarily and we'll provide a future-proof solution as a next iteration.
=> [core] disable msgpack tests after the package split

.circleci/config.yml, ddtrace/contrib/mysql/__init__.py, ddtrace/contrib/mysqldb/__init__.py, ddtrace/contrib/mysqldb/patch.py, ddtrace/monkey.py, docs/index.rst, tests/contrib/mysqldb/test_mysql.py, tox.ini
This PR adds MySQLdb integration. MySQLdb is widely used db connector implementation:
* https://pypi.python.org/pypi/MySQL-python/1.2.5
* https://pypi.python.org/pypi/mysqlclient (fork of MySQL-python with Python3 support)
Difference from existing mysql (mysql-connector) integration:
* Did not port ddtrace.contrib.mysql.tracers since it is marked as deprecated.
* The factory function is Connect. Its aliases are connect and Connection.
* Genarate tags from arguments (positional arguments and keyword arguments), since connection parameters aren't stored as attributes of connection except port.
Modify test to work with MySQLdb:
* Keyword arguments are slightly different (password -> passwd, database -> db).
* cursor.callproc() doesn't return output value (same as PyMySQL, its integration …
=> Add MySQLdb integration

ddtrace/contrib/dbapi/__init__.py, tests/contrib/mysql/test_mysql.py, tests/contrib/mysqldb/test_mysql.py, tests/contrib/psycopg/test_psycopg.py, tests/contrib/sqlite3/test_sqlite3.py
This patch removes the `sql.query` tag otherwise it's not properly obfuscated in the Trace Agent (reference: https://github.com/DataDog/datadog-trace-agent/blob/0067fb9a869a949e018e15befadb56338c5fa798/quantizer/sql.go#L228-L236). This issue impacts only MySQL integrations and NOT `psycopg2` or `sqlalchemy` with Postgres driver.
=> [dbapi] remove `sql.query` tag so that the content is obfuscated in the Agent

.circleci/config.yml, ddtrace/contrib/django/compat.py, ddtrace/contrib/django/middleware.py, tests/contrib/django/app/settings.py, tests/contrib/django/compat.py, tests/contrib/django/test_cache_views.py, tests/contrib/django/test_middleware.py, tests/contrib/djangorestframework/app/settings.py, tox.ini
Fixes #397 - tracing with Django 2.0 seems to work fine with this small change.
=> Django 2.0 compatibility: User.is_authenticated is now a property

ddtrace/contrib/pylons/__init__.py, ddtrace/contrib/pylons/middleware.py, ddtrace/contrib/pylons/patch.py, tests/contrib/pylons/test_pylons.py
Adds Distributed Tracing for `pylons` web framework. It could be activated using the `PylonsTraceMiddleware` with the following kwarg:
```python
traced_app = PylonsTraceMiddleware(app, tracer, service='my-pylons-app', distributed_tracing=True)
```
If `ddtrace-run` script is used, you can enable Distributed Tracing using the `DATADOG_PYLONS_DISTRIBUTED_TRACING=True` environment variable.
=> [pylons] add distributed tracing via kwarg and environment variable

ddtrace/bootstrap/sitecustomize.py, docs/index.rst, tests/commands/ddtrace_run_priority_sampling.py, tests/commands/test_runner.py
When `ddtrace-run` script is used, it's not possible to configure Distributed Sampling. With this patch you can enable it using `DATADOG_PRIORITY_SAMPLING=True`.
=> [ddtrace-run] enable Distributed Sampling via environment variable

ddtrace/contrib/tornado/compat.py, ddtrace/contrib/tornado/patch.py, tests/contrib/tornado/test_executor_decorator.py
`tornado` was wrapping directly the unbound method `submit`, avoiding the safe-guard we have when using `wrapt`. With this new approach we use directly the `patch()` and `unpatch()` functions from the `futures` integration, so that we don't need to think what needs to be patched. Furthermore, avoids double wrapping the same unbound method.
=> [tornado] better compatibility with `futures` instrumentation

ddtrace/contrib/falcon/__init__.py, ddtrace/contrib/falcon/middleware.py, ddtrace/contrib/falcon/patch.py, tests/contrib/falcon/app/app.py, tests/contrib/falcon/test_distributed_tracing.py, tests/contrib/falcon/test_suite.py, tox.ini
This adds distributed tracing to falcon. 
It's not enabled by default, but can be set with an argument to the middleware or by setting an environment variable when using autopatching.
It just works by looking for the HTTP headers using HTTPPropagator.
=> [falcon] Add distributed tracing

ddtrace/contrib/django/db.py, tests/contrib/django/test_middleware.py, tests/contrib/django/utils.py
When running django via gunicorn and using gevent workers new connections are created after a greenlet fork, and they are unpatched. That results in still seeing django traces but losing DB traces.
This simply makes connection patching slightly more robust, by patching the ConnectionHandler object. The patched ConnectionHandler makes sure that every connection it handles is patched.
=> [django] Fix gunicorn gevent worker causing database connection unpatch

tests/contrib/django/app/settings.py, tests/contrib/django/test_autopatching.py, tests/contrib/djangorestframework/app/settings.py
We just had our test/sample project set up incorrectly to have both a redundant MIDDLEWARE_CLASSES as well as a MIDDLEWARE when django >= (1,10). The warning wasn't present in 2.0 but was shown for earlier new-middlware versions.
I just made it only use MIDDLEWARE_CLASSES for supported versions.
=> [django] Remove MIDDLEWARE_CLASSES deprecation warning from tests

ddtrace/contrib/django/middleware.py
I do this by ensuring that only _one_ of MIDDLEWARE and MIDDLEWARE_CLASSES gets patched.
Downside: I still don't completely understand why it would flake, I know there is some kind of race in the tests happening where the insert_trace_middleware function gets called multiple times but I couldn't figure out what it is. I was starting to spend a little too much time on this, so I figured you'd at least enjoy a solution.
I just made sure that insert_trace_middleware is idempotent now.
=> [django] Fix django test flake

ddtrace/util.py, tests/test_utils.py
Depending on the integration, there isn't a clear consistency in environment variables nomenclature. With this patch we:
* expose an API to retrieve a setting from an environment variable (`get_env`)
* get the value from `DD_` prefix, with highest priority
* if `DD_` is not found, look for `DATADOG_` prefix (backward compatibility)
* if no environment variables are found, return a default
```python
config._add('requests',{
'service_name': get_env('requests', 'service_name', DEFAULT_SERVICE),
'distributed_tracing': asbool(get_env('requests', 'distributed_tracing', False)),
})
```
=> [core] provide an environment getter utility to ensure consistency between env vars

ddtrace/__init__.py, ddtrace/configuration.py, tests/test_configuration.py
Some integrations (i.e. `requests`) may need global settings to avoid polluting modules namespaces. With this patch, a global `Config` object is provided so that users can change integrations behavior, with one and only one simple API. Example:
```python
config.requests['distributed_tracing'] = True
```
The patch provides only the API and doesn't migrate any integration to this new API.
Integrations must register themselves to the global configuration object. A simple (private) API is available:
```python
def patch():
config._add('requests', { 'distributed_tracing': False })
```
=> [core] add a global configuration system

docs/index.rst
Just fixing an hyperlink cross reference bug in the docs.
=> Fixing typo in the doc

ddtrace/utils/formats.py
In the previous implementation we raised a deprecation warning despite `DATADOG_` prefix was used or not.
=> [core] fix deprecation warning on `get_env()`

ddtrace/contrib/requests/__init__.py, ddtrace/contrib/requests/connection.py, ddtrace/contrib/requests/constants.py, ddtrace/contrib/requests/legacy.py, ddtrace/contrib/requests/patch.py, ddtrace/contrib/requests/session.py, tests/contrib/requests/test_requests.py, tests/contrib/requests/test_requests_distributed.py
The current implementation doesn't provide any service name for the `requests` span. It means that all traces produced by `requests` as a root span will be dropped. With this patch we mainly:
* provide a default service name (that is `requests`), so that everytime it's a root span, the trace can be sent correctly
* allow users to change the service name for each client via:
```python
cfg = config.get_from(session)
cfg['service_name'] = 'client'
```
* the default service name can be changed also via environment variable `DD_REQUESTS_SERVICE_NAME` (or the legacy`DATADOG_REQUESTS_SERVICE_NAME`)
* if a parent is available and the service name has not been set by the user, use the parent service
During the process, minor refactoring has been done to split better the integration modules.
The …
=> [requests] provide a service name for the request Span

ddtrace/bootstrap/sitecustomize.py, tests/commands/bootstrap/sitecustomize.py, tests/commands/ddtrace_run_sitecustomize.py, tests/commands/test_runner.py, tests/util.py
Our current `ddtrace-run` implementation doesn't support users' `sitecustomize.py`. This module is auto-loaded when the interpreter starts, and with the current implementation this is what is happening:
* when you run `ddtrace-run`, users `sitecustomize.py` is executed
* then we spawn a new interpreter via `execl` running users' app for real
* at this point `sitecustomize.py` is executed again, but it's ours because we're first in the `PYTHONPATH`.
* if users change something globally (i.e. UTF encoding instead of ASCII), that change is discarded because the `sitecustomize.py` should be called twice.
With this patch, we exclude our `boostrap/sitecustomize.py` from the path, so that the original one can be loaded again.
=> [core] ensure users sitecustomize.py is called

ddtrace/context.py, ddtrace/contrib/gevent/greenlet.py, tests/contrib/gevent/test_tracer.py, tests/test_context.py
Otherwise it seems we might be losing traces.
While playing around with gevent and the tracing library, I noticed that we were losing some traces at the gevent new context creation for no obvious reason. Passing the sampling_priority seems to have fixed it.
It's not a really scientific approach, i.e. I'm not sure what this change does, but it seems to be working... Do you think it could explain some missing spans in a trace?
Happy to add a test if you can point me in the right direction. 😃 (and if this PR makes sense)
=> [contrib/gevent] pass sampling_priority

docs/index.rst
@palazzem 
As per title, add the missing reference to tornado integration.
=> [docs] add missing tornado support

tox.ini
The `aiobotocore` test suite did not pass because of a dependencies issue. It seems that the library doesn't pin the version of their dependencies, creating errors on the test suite.
As a reference, see [this build failing](https://circleci.com/gh/DataDog/dd-trace-py/16095).
This PR forces the use of the `typing` module when missing.
=> [aiobotocore] Fixing tests dependencies

ddtrace/contrib/dbapi/__init__.py, ddtrace/contrib/mysql/patch.py, ddtrace/contrib/mysqldb/patch.py, ddtrace/contrib/pymysql/patch.py
The way the `MySQLdb` library is patched uses `dbapi`. Then when initializing a `TracedConnection` object, a new Pin was created that did not have `type`, that where the error came from.
This PR solves this issue and prevents from getting 2 services reported for the `MySQLdb` integration. If passing the pin parameter when initializing, it will not create a new one.
=> [mysqlb] Fixing missing db type

ddtrace/bootstrap/sitecustomize.py, tests/commands/ddtrace_run_argv.py, tests/commands/ddtrace_run_patched_modules.py, tests/commands/test_runner.py, tox.ini
This PR solves [this issue](https://github.com/DataDog/dd-trace-py/issues/423) : when patching celery with the `ddtrace-run` command, the import fails silently and Celery is not patched. The exception raised is `'module' object has no attribute 'argv'`, stemming from the way our tracer patches libraries: `argv` is not passed, and causes the fail celery import as the library needs it.
The PR replaces argv when it is required.
I have tested this change with a Celery app and a `pymysql` app, it seems to work fine.
=> [celery] fixing ddtrace-run broke celery support

ddtrace/contrib/requests/patch.py
The `requests` library did not set up `app_type` and `app`, resulting in errors on the agent when reporting services:
`ERROR:failed_to_send services to Agent: HTTP error status 400, reason Bad Request, message Content-Type: text/plain; charset=utf-8`
This PR just adds these attributes to the `Pin`.
I have checked all other integrations and it seems `requests` was the last one with these attributes missing, so this bug should not happen again with other integrations.
=> [requests] adding missing app_type and app name to pin

ddtrace/compat.py, ddtrace/contrib/pylons/middleware.py, ddtrace/utils/reraise.py, tests/test_compat.py
Closes #472 
Pylons is not Python 3 compatible, but our code must be. In that case, any import will generate a `SyntaxError`. With this approach, the `raise` keyword is replaced with a "six-like" approach that is Python 2 and Python 3 compatible.
Because the number of compatibility functions is increasing, we may decide to move to `six` library. It will add a new dependency, but the compatibility code across python versions will be handled by the community. For the scope of this PR, migrating to `six` is not an option and a small change (that needs clean-up) fits better.
=> [pylons] ensure the middleware code is Python 3 compatible

ddtrace/contrib/celery/patch.py, ddtrace/contrib/celery/registry.py, tox.ini
After solving #465 #469 to fix #423, we discovered that `ddtrace-run` wasn't instrumenting old-style tasks. The issue was related to the fact that `celery.task.Task` (`Task` base class) wasn't instrumented by our system; unfortunately, it wasn't possible to instrument it directly because of how the base class is used by Celery. Indeed, a direct instrumentation of `celery.task.Task` ended with the following exception:
```
[2018-06-11 12:37:50,595: ERROR/MainProcess] Received unregistered task of type u'_get_exec_options'.
The message has been ignored and discarded.
Did you remember to import the module containing this task?
Or maybe you're using relative imports?
Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.
The full contents of the message body …
```
=> [celery] patch TaskRegistry to support old-style task with `ddtrace-run`

ddtrace/contrib/django/conf.py
Closes #435.
Our legacy test suite used the `setting_changed()` signal to connect our reloading function when settings are updated via `django.test.TestCase.settings()` context manager or `@django.test.override_settings` decorator ([reference](https://docs.djangoproject.com/en/2.0/ref/signals/#setting-changed)). This signal is not required in order to run our tests (see the CI result).
The main issue is related to the testing code that is imported in our `conf.py` module, resulting in side effects when the `ddtrace-run` script is used. In this specific case, the `DatabaseWrapper` object was owned by the main thread, but the preloading process that happens in `gunicorn` or `uwsgi` assigned (correctly) the object to another thread (Django has a …
=> [django] remove setting_changed signal from the DatadogSettings

docs/index.rst
Adds information to the debugging process for new users. 
Clarifies running your application in debug mode disables traces as [suggested by ndkv](https://github.com/DataDog/documentation/issues/2105).
Also gives an example command to see if your traces are being shipped or not in a Kubernetes environment. I'm open to suggestions here if someone knows a better / quicker way.
=> [docs] Notes about debug mode, and debugging in Kubernetes

ddtrace/contrib/psycopg/patch.py, tests/contrib/psycopg/test_psycopg.py
Closes #474 and closes #383 
Related to #96.
Use the method introduced in #96 to manually patch the `psycopg2.extensions.quote_ident` method if it exists on the version of `psycopg2` used.
This PR also introduces a test that replicates the bug.
=> [psycopg2] fix for quote_ident typing bug

ddtrace/contrib/celery/patch.py, ddtrace/contrib/celery/task.py, tests/contrib/celery/test_task.py
Closes #451 
When Django+Celery are used, Django users rely on the `@shared_task` decorator. This allows re-usable Django apps, while not depending on which Celery `app` is used. With this patch we're sure Celery tasks are properly instrumented, because Django doesn't rely on Celery registry when adding a new task. Because of that, our previous patch for `TaskRegistry.register` wasn't enough.
When testing this PR, bear in mind that our tracing system is disabled if Django is in debug mode (`DEBUG = True`).
=> [django/celery] add `shared_task` decorator wrapper

ddtrace/helpers.py, tests/test_helpers.py
If for some reasons at any time we need to retrieve the current correlation identifiers (`trace_id` and `span_id` at the time of writing), users need to:
* import the current active `Tracer`
* retrieve the current active `Span` or `Scope` depending on the implementation (OpenTracing compatible or not)
* find the `trace_id` and `span_id`
* add a safety check in case a `Trace` is not active
* return these values
This `helpers` module can be imported to provide a high-level API that abstracts all the steps above, providing a reasonable shortcut.
```python
from ddtrace import helpers
trace_id, span_id = helpers.get_correlation_ids()
```
=> [core] add a shortcut to retrieve Trace correlation identifiers

ddtrace/opentracer/span.py, ddtrace/opentracer/tracer.py, tests/opentracer/test_tracer.py, tests/opentracer/test_tracer_asyncio.py, tests/opentracer/test_tracer_gevent.py, tox.ini
This PR adds the remaining opentracing tracer functionality along with more extensive test coverage.
Particularly:
- `start_active_span`
- support for references
- tests for the above
- tests for:
- asyncio
- gevent
- threading
=> [opentracer] Remaining tracer pieces

ddtrace/opentracer/span.py, tests/opentracer/test_span.py
`get_tag` is not in the OpenTracing spec.
=> [opentracer] Span: make get_tag private

ddtrace/opentracer/tracer.py, tests/opentracer/test_tracer.py
`start_span` should not activate a span. This PR fixes this and adjusts the tests to use `start_active_span` instead.
=> [opentracer] Tracer: start_span fixes

ddtrace/contrib/aiopg/connection.py
Closes #492 
When a `AIOTracedConnection` object is initialized, a new `Pin` is created without the `app_type`. That field is required for the `services` endpoint in the Agent
The `services` endpoint is deprecated and will be removed in version 1.0. This issue doesn't impact the way traces are sent.
=> [aiopg] send app_type value

ddtrace/contrib/tornado/__init__.py, ddtrace/contrib/tornado/application.py, tests/contrib/tornado/test_config.py
Closes #499
Filter doesn't work with tornado trace configuration since it doesn't have access to the settings object during configuration. https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/tracer.py#L108
```python
settings['datadog_trace'] = {
'FILTERS': [FilterRequestsOnUrl([r'.*/test'])]
}
```
=> tracer needs the settings object to get filter configurations

ddtrace/opentracer/span.py, ddtrace/opentracer/span_context.py, ddtrace/opentracer/tags.py, ddtrace/opentracer/tracer.py, tests/opentracer/test_span.py, tests/opentracer/test_span_context.py, tests/opentracer/test_tracer.py
This PR aims to connect the added opentracing logic to our Datadog tracing so that the traces collected by the opentracer are successfully sent and displayed in the Datadog platform.
A dependent PR in the trace-examples repo will contain a few more concrete opentracing usage examples: https://github.com/DataDog/trace-examples/pull/33.
This PR makes the following changes:
- a service name is set which allows traces to be accepted by the trace agent
- make span context usage immutable
- set the tags related to baggage in the datadog span
- fixes to scope manager usage
- tests for all the above
=> [opentracer] Compatibility with Datadog

ddtrace/bootstrap/sitecustomize.py, tests/commands/ddtrace_minimal.py, tests/commands/test_runner.py
Module `ddtrace.bootstrap.sitecustomize` expect that the python application is started using the `ddtrace-run` command or that the bootstrap_dir is in `sys.path` see  https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/bootstrap/sitecustomize.py#L93
This PR prevent failed tracing initialization by checking presence of bootstrap dir in path.
How to reproduce:
minimal.py
```
#!/bin/env python
import ddtrace.bootstrap.sitecustomize
```
```
» python minimal.py
WARNING:ddtrace.bootstrap.sitecustomize:error configuring Datadog tracing
File "/home/mkuffa/src/dd-trace-py/ddtrace/bootstrap/sitecustomize.py", line 93, in <module>
path.remove(bootstrap_dir)
ValueError: list.remove(x): x not in list
```
While `ddtrace-run minimal.py` works fine.
=> Check if bootstrap dir is in path before removal

ddtrace/contrib/celery/app.py, ddtrace/contrib/celery/patch.py, ddtrace/contrib/celery/task.py, tests/contrib/celery/base.py, tests/contrib/celery/test_app.py, tests/contrib/celery/test_integration.py, tests/contrib/celery/test_old_style_task.py, tests/contrib/celery/test_task.py, tests/contrib/celery/utils.py
This PR changes how we execute our tests. It ensures `patch()` and `unpatch()` are used in tests, so we can double check if the integration works.
It introduces also a change that was needed to make the `patch()` work. It's a bug in the underlying instrumentation that wasn't reported before.
This PR is the first of a series of PRs to address all problems related to our Celery integrations.
=> [celery] refactor tests execution; change the patched Task() method

ddtrace/tracer.py, tests/test_tracer.py
This allows reusing the `DATADOG_TRACE_AGENT_HOSTNAME` environmental variable from `ddtrace-run` as the default hostname for Tracer.
We ran into the same problem as OP from #509 and this should fix #509.
=> core: default hostname to `DATADOG_TRACE_AGENT_HOSTNAME` if available

ddtrace/propagation/http.py, ddtrace/propagation/utils.py, tests/propagation/test_http.py, tests/propagation/test_utils.py
WSGI specification states for variable HTTP headers to be in a particular format stated [here](https://www.python.org/dev/peps/pep-3333/#environ-variables).
This PR adds support to the HTTP Propagator to support if and when the Datadog headers are converted to this format.
This should fix #456.
=> [core] Add WSGI http header support to HTTP propagator

ddtrace/contrib/boto/patch.py, ddtrace/ext/aws.py
Fixes #525, also applies formatting.
=> [boto] Default to None if no region 

ddtrace/__init__.py
Add configuration of the root logger so that error messages are not displayed in cases like #513.
=> [core] Configure the root logger

ddtrace/contrib/pymongo/client.py, tests/contrib/pymongo/test.py
This PR adds a fix for the bug demonstrated in #369.
Due to supporting deprecated code, a hack existed that used the first argument passed to the `TracedMongoClient`. The first argument passed to `MongoClient` was `host`. This bug would occur when host was provided explicitly as a kwarg.
=> [pymongo] Fix multiple host kwarg

tests/contrib/pylons/app/middleware.py, tests/contrib/pylons/test_pylons.py
#463 raised concerns about properly handled exceptions causing spans to be incorrectly tagged with error information. While the issue could not be replicated, a bunch of tests were written to assert the logic of exception handling in middleware.
This PR adds these regression tests.
=> [pylons] Add middleware exception/error handling tests

ddtrace/bootstrap/sitecustomize.py, ddtrace/monkey.py, tests/commands/ddtrace_run_patched_modules.py, tests/contrib/celery/autopatch.py, tests/contrib/celery/test_autopatch.py, tests/contrib/celery/test_patch.py, tox.ini
Patching `celery` our usual way does not work for `celery` as `celery` [contains a reference to `sys.argv`](https://github.com/celery/celery/blob/8d2f93d303dee9b8620933b89dd38704aa697a8b/celery/__init__.py#L121). This is problematic as [`sys.argv` is not defined in `sitecustomize.py`](https://bugs.python.org/issue2972). 
This PR introduces a fix for this by taking a completely different approach to patching by using post-import hooks as defined here: https://www.python.org/dev/peps/pep-0369.
For simplicity and proof of concept this approach is meant only to patch `celery` via post-import hooks. It is a bit hacky in that we check explicitly for `celery` and add in the normal patching side-effects.
It turns out that patching this way is extremely easy. We should strongly consider moving to …
=> [celery] Patch via post-import hooks

ddtrace/contrib/flask/middleware.py, tests/contrib/flask/test_flask.py, tests/contrib/flask/web.py
In some cases it's possible to instrument the framework twice. For instance, using `ddtrace-run` and the `TraceMiddleware` together will produce unexpected behavior. Using both is not the right behavior and it's possible to hit this code-path, causing traces to not be sent.
This safe-guard ensures that signals and callbacks are attached to the Flask application only once, making the instrumentation idempotent and safe.
I've refactored also the test suite, to make these tests possible. The main change is explained here: https://github.com/DataDog/dd-trace-py/commit/23287fea06961faf06c8a695fabe01b83e56b68e
=> [flask] avoid double instrumentation when TraceMiddleware is used

ddtrace/contrib/celery/__init__.py, ddtrace/contrib/celery/app.py, ddtrace/contrib/celery/constants.py, ddtrace/contrib/celery/patch.py, ddtrace/contrib/celery/signals.py, tests/contrib/celery/base.py, tests/contrib/celery/test_integration.py
Fixes #510
Adds the `Config` API to Celery integration so that service names can be set globally per application as follows:
```python
config.celery['producer_service_name'] = 'task-queue'
config.celery['worker_service_name'] = 'worker-notify'
```
or via the following environment variables:
```
DD_CELERY_PRODUCER_SERVICE_NAME=task-queue
DD_CELERY_WORKER_SERVICE_NAME=worker-notify
```
=> [celery] add Config object to change Worker/Producer service names

ddtrace/contrib/pymemcache/__init__.py
When building docs, `pymemcache` library was imported, crashing the build for this module. Using our `require_modules` helper solves the problem. It doesn't impact the way `pymemcache` works.
=> [docs] fix pymemcache documentation build

Rakefile, docs/conf.py
With Sphinx > 1.7.5 the table of content is not built. Because we're moving to ReadTheDocs to keep our API documentation, we just downgrade the package to make it work again.
=> [docs] downgrade Sphinx to 1.7.5

ddtrace/contrib/celery/__init__.py
- Rewording
- Fix the configuration example
=> [celery] Documentation Fixes

ddtrace/opentracer/span.py, ddtrace/opentracer/tracer.py, ddtrace/opentracer/utils.py, tests/opentracer/test_dd_compatibility.py, tests/opentracer/test_tracer.py, tests/opentracer/test_tracer_asyncio.py, tests/opentracer/test_tracer_gevent.py, tests/opentracer/test_tracer_tornado.py, tests/opentracer/test_utils.py, tests/opentracer/utils.py, tox.ini
This PR aims to add support so that the opentracer can be used in tandem with the Datadog tracer. Traces started with an opentracer should be continued seamlessly with the Datadog tracer, and the other way around as well.
This should enable us to verify in subsequent PRs that the opentracer will work with each of our supported integrations.
=> [opentracer] Integration with Datadog tracer

tests/contrib/aiobotocore/test.py, tests/opentracer/utils.py
This PR adds testing support for the `aiobotocore` integration when used with the opentracer. This PR serves as a basis to then go through and confirm OpenTracing support for the rest of our integrations.
=> [opentracer] aiobotocore tests

ddtrace/__init__.py
Configuring Python logging from a library/module (rather than the application) will cause a lot of problems. As mentioned in this [comment](https://github.com/DataDog/dd-trace-py/pull/536/files#r213843347), we must not do that.
This reverts PR #536.
=> [core] remove the root logger configuration within the library

.circleci/config.yml, Rakefile, docs/conf.py
The documentation deploy was broken due to this change: https://github.com/DataDog/dd-trace-py/commit/2071be204e21d7725399c62d420b8ff27633278d#diff-85987f48f1258d9ee486e3191495582dL20
This PR re-adds this logic and also installs `wrapt` before building the docs as it seems to be required as well.
=> [docs] Fix docs deploy

ddtrace/opentracer/tracer.py, tests/opentracer/test_dd_compatibility.py
- default to using global ddtrace.tracer instance
- allow user to specify their own
- if all else fails create a new datadog tracer instance
=> [opentracer] Configuration for underlying Datadog tracer

tests/contrib/elasticsearch/test.py
Add elasticsearch OpenTracing test
=> [opentracer] Add elasticsearch test

.circleci/config.yml, tox.ini
For python 1.x we tested a few versions that are no longer supported based on https://www.djangoproject.com/download/#supported-versions
With this PR, we keep the oldest version that we were already testing among the not supported just to be aware of potential breaking changes we are introducing for older versions and remove all the others.
We keep the oldest version that we were already testing and the latest two stable releases, 3.7 and 3.8.
=> [ci] Reduce django and djangorestframework test matrix

docker-compose.yml
Elastic search doker image version 2.3-alpine disappeared from the docker hub and it is no longer available for download.
We should update the image to version 2.4-alpine
=> Update elasticsearch docker image from 2.3 to 2.4

ddtrace/opentracer/propagation/http.py, tests/opentracer/test_tracer.py
Our OpenTracing span context propagation does not take into consideration that the Datadog propagator will return a `Context` when it fails to extract: https://github.com/DataDog/dd-trace-py/blob/61000958a7354d92ce4a4d6319d81545c55989cb/ddtrace/propagation/http.py#L123-L135
This PR introduces a check
```python
if not ddspan_ctx.trace_id:
raise SpanContextCorruptedException('failed to extract span context')
```
to ensure that we detect when the propagation has failed and then raise the appropriate OpenTracing exception.
=> [opentracer] Properly handle corrupted span context propagation

.circleci/config.yml, .circleci/images/runner/Dockerfile, tests/contrib/cassandra/test.py, tox.ini
1) Avoid dist->install->test at each run.
Our previous workflow was to make a "dist" and an "install" of ddtrace at each environment even if it was cached. This had the benefit of testing a real dist package, but was also extremely time consumig.
This change switch to using the source code during testing instead of the actual dist. Which is much more fast (~50%).
At the same time, when we test the ddtestrun command, we want to use the real distribution, so that we do not lose testing the actual build of our library.
2) Requests tests had 2 problems, thay failed often because of 503 and were slow. In order to fix both the issues, this commit uses a local docker container running the httpbin image provided by http://httpbin.org
3) Avoid cassandra failures due to auto_snapshot functionality …
=> Improve performance of tests execution

.circleci/config.yml, tests/contrib/elasticsearch/test.py, tests/contrib/falcon/test_autopatch.py, tox.ini
A few notes follow for specific libraries besides updates you can see in the code itself
```
*tornado*
- not possible to udate to 5.x, postponing
*elasticsearch*
- added 6.3
- a test had to be updated because `doc_type` arg was optional before, it is not anymore.
*falcon*
- added 1.3, 1.4
- a small change to a test class was necessaries because of a new expected property that must exists in the TestCase class.
*flask*
- added version 1.0
- our integration flask_cache does not support flask 1.
*pymongo/mongoengine*
- mongoengine: updated to latest
- pymongo: added 3.6. Latest stable is 3.7, but our integration fails to trace at least inserts.
Example:
1) ['count here.are.songs', 'count here.are.songs', 'count here.are.songs', 'count here.are.songs', 'delete here.are.songs {"artist": "?"}', …
```
=> [tests] Update the integrations libraries versions to the latest possible.

ddtrace/contrib/django/__init__.py, docs/advanced_usage.rst
We had a line in our documentation with regard to the tracer being disabled in "`DEBUG`" mode. However this only applies to the Django integration.
=> [docs] Clarify debug mode

setup.py
As mentioned in #611:
```sh
> pip install 'ddtrace[opentracing] == 0.14.0'
Collecting ddtrace[opentracing]==0.14.0
ddtrace 0.14.0 does not provide the extra 'opentracing'
Collecting msgpack-python (from ddtrace[opentracing]==0.14.0)
Collecting wrapt (from ddtrace[opentracing]==0.14.0)
Installing collected packages: msgpack-python, wrapt, ddtrace
Successfully installed ddtrace-0.14.0 msgpack-python-0.5.6 wrapt-1.10.11
```
notably:
```
ddtrace 0.14.0 does not provide the extra 'opentracing'
```
This was due to a typo in setup.py.
This PR also explicitly defines the supported `opentracing` version.
Should fix #611.
=> Fix "does not provide the extra opentracing"

.circleci/config.yml, tox.ini
- We defined specific commands depending on the real command and not on
the dependency graph
- We removed django testenv special configurations that were no longer
used after we added redis{210} in place of redis to the dependency list
- We sorted alphabetically the various envs
- We do not rely anymore on checksum of tox.ini to invalidate cache
=> [tests] Refactor tox.ini file

.circleci/config.yml
Problems we had:
- the only way we had to release docs was to push a branch with a release tag
- when we wanted to release docs we had to re-run all tests, which was
not desired.
What this PR changes:
- Now docs doesn't require tests to be run
- Now docs do not require a release, can be published at any time
- In order to publish docs just add a tag 'docs' and push it
- Docs for release tags 'vx.x.x' are still built and deployed
- A browsable preview of the docs is available in the build step's artifacts
- The preview can be inspected before manually approving the deploy to S3.
=> [circleci] Improve python docs deployment strategy

ddtrace/commands/ddtrace_run.py
This fixes the discrepancy between: 
https://github.com/DataDog/dd-trace-py/blob/57e99540f3b330dd0fd5bbfdb0269c740fa75e26/ddtrace/commands/ddtrace_run.py#L16-L32
and
https://github.com/DataDog/dd-trace-py/blame/master/docs/advanced_usage.rst#L374-L395
We should consider a better way of ensuring these stay synchronized (or if we even need to keep them separated).
=> [docs] Add priority sampling to ddtrace-run usage

ddtrace/contrib/django/compat.py
We are running on Django 1.11 and we see a lots of deprecation warning although there is no reason for that, as it's been a property since [Django 1.10](https://docs.djangoproject.com/en/1.10/ref/contrib/auth/#django.contrib.auth.models.User.is_authenticated).
The amount of warnings coming from dd-trace is making it difficult for us to see the other actual warnings, so it would be great if they could be silenced, that would help us tackle the Django upgrade more easily.
=> Fix minimum Django version for user.is_authenticated property

ddtrace/contrib/django/__init__.py, ddtrace/contrib/django/cache.py, ddtrace/contrib/django/conf.py, tests/contrib/django/test_cache_client.py
DEFAULT_CACHE_SERVICE is introduced to override the service name used for the span dedicated to the cache.
If the value is set, the django.cache span will appear as a different service. If not set, the current
behavior is kept.
Fix #528
=> Allow django cache to be seen as a different service.

ddtrace/context.py, ddtrace/tracer.py, tests/test_context.py, tests/test_tracer.py
This new tracer API method provides access to the root span in a given context. This is useful for setting tags on the root span which provide general information about the trace instead of having to attach tags on each child span.
```python
root_span = tracer.current_root_span()
root_span.set_tag('host', '127.0.0.1')
```
=> [core] add Tracer API to retrieve the root Span

.circleci/config.yml, ddtrace/monkey.py, tests/contrib/requests_gevent/test_regression.py, tests/contrib/requests_gevent/test_requests_gevent.py, tox.ini
This PR adds `requests` and `gevent` to the list of modules that we will patch on first import instead of explicitly importing/patching for the user.
We have refactored code in `monkey.py` for how we define which modules support patching on import.
We also added in a check to see if the module is already imported, in which case we will patch immediately rather that adding a hook for it.
This PR also resolves https://github.com/DataDog/dd-trace-py/issues/506
The problem we were seeing in that issue is when using `ddtrace-run` we were importing and patching `requests` (which imports and uses `urllib3`) before the user could import `gevent` and call `gevent.monkey.patch_all()`.
This resolves that issue by only patching `requests` when the user first imports it into their code.
We have added …
=> [requests] [gevent] Patch modules on first import

.circleci/config.yml, tests/wait-for-services.py, tox.ini
The `rediscluster` tests were flaky due to the instances not being ready before the tests started running causing the first few tests to fail. 
This PR adds a connection and query check to `wait-for-services.py` which will allow the test to proceed once the connection and query are successfully made.
=> [rediscluster] Add wait for services to start

tests/test_api.py
#542 helped to fix an issue where we were leaking some `HTTPConnection`s.
This PR adds in two basic test cases to ensure that we are always calling `HTTPConnection.close()` on `API._put`.
Also added in checking to ensure we do not raise any `Warning`s
=> [tests] Add test cases for API._put

ddtrace/contrib/gevent/greenlet.py, ddtrace/contrib/gevent/patch.py, tests/contrib/gevent/test_tracer.py
=> Add support for gevent.pool.Pool and gevent.pool.Group

tests/test_integration.py
This test is non-deterministic and will fail for no reason and so should be skipped.
The problem we are having is that this test relies on us being able to correctly time the flush intervals from the writer, which we are unable to do at this time.
If we can tweak the writer internals in a way where we can make it deterministic then we should revive this test case.
=> [tests] Skip flaky TestWorkers.test_worker_multiple_traces test case

ddtrace/contrib/mysqldb/patch.py
This PR fixed patching `MySQLdb.Connect` function.
It's reasonable to assume that those functions(`connect`, `Connect`, `Connection`) are identical. However, It's very dangerous if each implementation is different. I think wrapping all of the connect functions are more reliable and also, will prevent generating critical bugs from customizing `connect` function
=> Fix mysqldb monkey patch

ddtrace/settings.py, ddtrace/utils/merge.py, tests/test_global_config.py
Previously if we tried to set a config setting before the contrib module was imported
we would receive an error that the integration key did not exist.
With this new approach we are allowing any integration setting to be configured by
the user, whenever they want and then when we call `config._add()` in the contrib
module, we will merge the settings with any existing settings, keeping those that
already exist.
We have also added a `Config.__repr__`
=> [core] Update config to allow configuration before patching 

.circleci/config.yml, tests/ddtrace_run.py, tox.ini
Currently, for a number of integrations, we test the integration itself in two scenarios: in "manual" patch mode and in "auto" patch mode.
We optimized the "manual" patch mode (avoiding the dist -> install) of the ddtrace package and forcing tox to use the source code. Now it is time to make "auto" patch mode quicker.
Right now we do `TOX_SKIP_DIST=False` for auto patch tests because we need the cli executable `ddtrace-run` in path. The idea is to avoid it.
**What does this PR add?**
1- We create files `tests/ddtrace_run.py` that loads the bootstrap module and run the tests commands
2- We execute autopatch tests using, again, source code instead of the installed bin
3- We add one job `ddtracerun_dist_install_execute` because we still want to make sure that in a clean environment we are …
=> Make CI faster by disabling dist and install in autopatching tests

ddtrace/contrib/django/compat.py, ddtrace/contrib/django/middleware.py, tests/contrib/django/test_middleware.py
Django has a set of internal error view handlers that it will fallback to if the user does not define one.
This is most clear with requests to unknown urls (404).
The problem we have when one of these view handlers is used is Django is not calling the `process_view` method from our middleware so we are unable to determine and set a proper view resource name for the request.
In this PR we are adding in a little logic to infer a resource name if we both have a span resource name of `unknown` (`process_view` was not called) and the response status code is for a known internal error handler.
=> [django] Infer span resource name when internal error handler is used

ddtrace/contrib/elasticsearch/patch.py, ddtrace/contrib/elasticsearch/quantize.py, ddtrace/contrib/elasticsearch/transport.py, ddtrace/ext/elasticsearch.py, tests/contrib/elasticsearch/test.py
The PR adjusts the elasticsearch integration to use constants defined in `ext/elasticsearch.py`. It also changes over the tests to use string literals instead of the constants.
=> [elasticsearch] Make constant organization consistent with other integrations

ddtrace/contrib/pyramid/patch.py, ddtrace/monkey.py, tests/contrib/pyramid/app/web.py, tests/contrib/pyramid/test_pyramid.py, tests/contrib/pyramid/test_pyramid_autopatch.py
This PR continues on from #658, enabling the pyramid integration by default.
In order to properly test the change a test was added to test the idempotence of patching pyramid. To clean up the test an `unpatch` method was added. Tests are added for both `patch` and `unpatch`.
=> [pyramid] Enabled by default

ddtrace/monkey.py, tests/contrib/httplib/test_httplib.py
This PR continues on from #658, enabling the httplib integration by default.
Good coverage was provided for patch/unpatch, two more tests added to assert idempotency.
=> [httplib] Enabled by default

.circleci/config.yml
In this PR:
- Run `deploy_experimental` on all `*-dev` branches
-  This will deploy to the wheelhouse when we merge into branches like `0.16-dev` so we don't need to merge into `master` in order to deploy to staging
- Reorganize list of jobs to be in alphabetical order
- Make test suites dependent on `flake8` task
- This means CI will fail fast if linting fails. Bit of a pain to manage the `requires: flake8` for each and every job, but will be nice to not destroy our parallelism if linting fails
=> [ci] reorganize CircleCI workflows

ddtrace/contrib/requests/connection.py, ddtrace/contrib/requests/patch.py, ddtrace/contrib/requests/session.py, tests/contrib/requests/test_requests.py
This PR changes our `requests` instrumentation to patch `requests.Session.send` instead of `requests.Session.request`.
The problem we have is if someone is using `.send()` directly then we do not end up tracing their calls.
This change is safe to make since `.request()` calls `.send()`, and this is a change compatible with `>=2.0.0`.
If we wanted to support `<2.0.0` in the future we can add tracing back in `requests.Session.request`.
=> [requests] patch Session.send instead of Session.request

ddtrace/bootstrap/sitecustomize.py, ddtrace/contrib/django/conf.py, ddtrace/tracer.py, tests/commands/ddtrace_run_hostname.py, tests/commands/test_runner.py
To help support desired containerization onboarding improvements we need to support `DD_AGENT_HOST` and `DD_TRACE_AGENT_PORT` environment variables for configuration.
These changes are the minimal viable changes needed to support these variables. It isn't the most clean, using something like `get_env()` would be better, but we decided to get this out the door since @Kyle-Verhoog has a task to work on standardizing our `DD_*` variables.
=> [core] Allow DD_AGENT_HOST and DD_TRACE_AGENT_PORT env variables

tests/commands/ddtrace_run_integration.py
This PR fixes a fix pushed for `redis==3.0.1`, they were computing whether a flush was async or not improperly.
=> [tests] fix broken redis check

tox.ini
It seems `tox -e wait <service>` has been failing because `redis-py-cluster` does not support `redis>3.0.0` yet.
Previous versions used to install `redis`, `1.3.6` now pins `redis` to a specific version.
=> [tests] pin version of redis-py-cluster for 'tox -e wait'

.circleci/config.yml, tox.ini
New major releases are killing us this month...
=> [tests] Pin pytest to 3.x.x and redis to 2.10.x for rediscluster

ddtrace/contrib/flask/__init__.py
We are missing this in our documentation right now.
=> [docs] add Flask configuration documentation

ddtrace/contrib/dbapi/__init__.py
This change shouldn't make much of a difference since it seems `commit()` and `rollback()` typically just return `None`, but we want to make this change just in case one of our integrations (or one in the future) does not break if they would have returned something other than `None`
=> [dbapi] return values for commit/rollback

ddtrace/contrib/cassandra/session.py, ddtrace/contrib/grpc/client_interceptor.py, ddtrace/contrib/pylons/middleware.py, tox.ini
We cannot upgrade to `3.6.0` since there is a bug that alerts on invalid escape sequences in docstrings.
For us this causes an issue with sphinx docstring `:param \**kwargs:`
=> [tests] upgrade flake8 to 3.5.0

ddtrace/contrib/psycopg/patch.py
We changed linting rules in `0.17.1-dev`, this fixes issues caught by those changes.
=> [psycopg2] fix linting issues

ddtrace/contrib/aiohttp/middlewares.py, tests/contrib/aiohttp/test_middleware.py, tests/contrib/aiohttp/test_request.py, tests/contrib/aiohttp/test_request_safety.py
At PeopleDoc we are using Datadog to monitor REST APIs written with Aiohttp. With APIs, you often have the same URL (eg: `/documents`) used for different views according to the HTTP method (eg: `GET /documents` vs `POST /documents`). But In Datadog's APM those views will share the same dashboard, making it impossible to get sensitive information about the behavior of a specific view.
Unfortunately I've found no easy way to change the `resource` attribute of a span in our apps, because the attribute is overwritten right before the span is sent [in ddtrace-py](https://github.com/k4nar/dd-trace-py/blob/1a5f79bca1ae81f691e214e9db53865e4f4610e3/ddtrace/contrib/aiohttp/middlewares.py#L89-L93).
My contribution could have gone two ways:
1. Don't overwrite the `resource` of a span if it has …
=> [aiohttp] Add HTTP method to the root span resource

ddtrace/contrib/cassandra/session.py, tests/contrib/cassandra/test.py
Reverts DataDog/dd-trace-py#714.
We ran into an issue when testing on our staging environment described in the comment below.
=> Revert "[cassandra] Fix batched query leak"

ddtrace/tracer.py, docs/advanced_usage.rst, tests/contrib/grpc/test_grpc.py, tests/contrib/pylons/test_pylons.py, tests/test_integration.py, tests/test_sampler.py, tests/utils/tracer.py
We want to enable priority sampling by default now.
=> Enable priority sampling by default

ddtrace/contrib/dbapi/__init__.py, ddtrace/contrib/psycopg/patch.py, tests/contrib/dbapi/test_unit.py, tests/contrib/django/test_cache_views.py, tests/contrib/django/test_connection.py, tests/contrib/django/test_middleware.py, tests/contrib/django/utils.py, tests/contrib/mysql/test_mysql.py, tests/contrib/mysqldb/test_mysql.py, tests/contrib/psycopg/test_psycopg.py, tests/contrib/pymysql/test_pymysql.py, tests/contrib/sqlite3/test_sqlite3.py, tests/utils/span.py
In a release `0.17.0` we added instrumentation for `dbapi2` `fetchone`, `fetchmany`, and `fetchall` methods.
While we want to provide instrumentation for these methods tracing them by default has caused issues. The reason being that most database libraries will use `fetchone()` when iterating over a cursor. This will cause your application to create an unnecessarily large number of spans when returning back a large number of rows from the database.
With this change we are disabling this tracing by default but provide a configuration option for enabling:
```python
config.dbapi2.trace_fetch_methods = True
```
It can also be enabled with the environment variable `DD_DBAPI2_TRACE_FETCH_METHODS=true`
=> [dbapi2] disable fetchone/fetchmany/fetchall tracing by default

.circleci/config.yml
This PR adds a CircleCI step to test running `python setup.py sdist` and `twine check` on our package.
This job is fast and should pass about 99.9% of the time, but acts as a quick/easy way for us to know if either our deploy script could fail to build the package distribution or if there is an issue with rendering our `setup.py` `long_description`.
=> [tests] test python setup.py sdist and twine check on build

tox.ini
`grpcio==1.18.0` was released recently and it changed how it raises exceptions so it is causing a test case to fail.
We should address the change, but this PR updates the tox version to be `>=0.8.0,<1.18.0` for now to ensure our tests pass.
=> [tests] limit grpcio version to >=1.8.0,<1.18.0

ddtrace/api.py, ddtrace/writer.py, tests/test_api.py, tests/test_integration.py, tox.ini
When working on another feature I noticed that we kept getting errors saying we cannot parse JSON response from trace agent showing it as an empty string.
After diving further I noticed that the response showed a length, and a quick wiresharking showed a valid JSON response, but still the body was always none.
If you call `HTTPConnection.close()` before calling `HTTPResponse.read()` the result will always be `b''`.
This means we have not been parsing/updating the rate by service sample rates.
=> [core] Call HTTPResponse.read() before HTTPConnection.close()

Rakefile, ddtrace/__init__.py, ddtrace/api.py, ddtrace/writer.py, tests/test_api.py, tests/test_integration.py, tox.ini
No changes are needed to upgrade to `0.20.2`.
This big fix release includes changes to ensure we properly read the HTTP response body from the trace agent before we close the HTTP connection.
- [core] Call HTTPResponse.read() before HTTPConnection.close() (#800)
- [tests] limit grpcio version to >=1.8.0,<1.18.0 (#802)
- [tools] Add confirmation to 'rake pypi:release' task (#791 )
Read the [full changeset](https://github.com/DataDog/dd-trace-py/compare/v0.20.1...v0.20.2) and the [release milestone](https://github.com/DataDog/dd-trace-py/milestone/36?closed=1).
=> Release 0.20.2

ddtrace/context.py, ddtrace/contrib/asyncio/provider.py, ddtrace/contrib/futures/threading.py, ddtrace/contrib/gevent/provider.py, ddtrace/contrib/tornado/stack_context.py, ddtrace/provider.py, tests/base/__init__.py, tests/contrib/futures/test_propagation.py, tests/contrib/tornado/test_executor_decorator.py
This PR addresses an issue we had when using `gunicorn` sync workers with endpoints that use `futures`.
The bug is caused by the fact that when submitting a new future, if a context does not already exist in the current thread then we will create and propagate that context through to the future.
This is usually not a big deal, but with `gunicorn` it means the main `gunicorn` thread will have a single context created for it and then propagated to all requests that are handled via futures from that thread.
This is issue is very evident when calling creating nested futures.
The following basic example reproduces the issue:
```python
import concurrent.futures
import time
import random
@tracer.wrap(service='task')
def task(w, i):
time.sleep(random.random()) …
```
=> [core] Allow futures to skip creating new context if one doesn't exist

ddtrace/__init__.py, ddtrace/context.py, ddtrace/contrib/asyncio/provider.py, ddtrace/contrib/futures/threading.py, ddtrace/contrib/gevent/provider.py, ddtrace/contrib/tornado/stack_context.py, ddtrace/provider.py, tests/base/__init__.py, tests/contrib/futures/test_propagation.py, tests/contrib/tornado/test_executor_decorator.py
This is a bug fix release that requires no changes.
This release includes a fix for context propagation with `futures`. Under the right conditions we could incorrectly share a trace context between multiple `futures` threads which result in multiple traces being joined together in one.
* [core] Allow futures to skip creating new context if one doesn't exist (#806)
Read the [full changeset](https://github.com/DataDog/dd-trace-py/compare/v0.20.2...v0.20.3) and the [release milestone](https://github.com/DataDog/dd-trace-py/milestone/37?closed=1).
=> Release 0.20.3

.circleci/config.yml
Removing `TOX_SKIP_DIST=False` and moving all the test suites into a single `tox` command reduced the overall runtime by 60 seconds.
_Note:_ We cannot use `detox` here because we tests rely on a single Elasticsearch index/specific documents, so the test suites collide with each other.
=> [tests] Simplify elasticsearch CI test commands

tests/base/__init__.py, tests/contrib/celery/base.py, tests/contrib/celery/test_integration.py, tests/contrib/django/test_instrumentation.py, tests/contrib/falcon/test_suite.py, tests/contrib/flask/test_request.py, tests/contrib/httplib/test_httplib.py, tests/contrib/molten/test_molten.py, tests/contrib/requests/test_requests.py, tests/contrib/requests/test_requests_distributed.py, tests/util.py
This PR ensures consistent use of our base `override_config` and `override_env` helpers from the `tests.base.BaseTestCase`
=> [testing] Ensure consistent use of override_config and override_env

ddtrace/utils/attrdict.py, tests/test_instance_config.py
This PR fixes a `__setattr__` priority issue we found for `IntegrationConfig`.
The problem was:
```python
config._add('flask', dict(distributed_tracing_enabled=False))
config.flask.distributed_tracing_enabled = True
assert config.flask.distributed_tracing_enabled is True
assert config.flask['distributed_tracing_enabled'] is True
```
The reason this is an issue is because initial we set a config key which gets is accessible as an item and an attribute. When we go to update as an attribute we see that an attribute already exists so we use `object.__setattr__(self, key, value)` to update it instead of `self[key] = value` like we should.
The change here ensures we always consider items first when calling `__setattr__`.
=> [bug] Integration config keys not being updated

ddtrace/__init__.py, ddtrace/utils/attrdict.py, tests/test_instance_config.py
This is a bug fix release, no code changes are required.
In this release we have fixed a bug that caused some configuration values to not get updated when set.
* [bug] Integration config keys not being updated (#816)
Read the [full changeset](https://github.com/DataDog/dd-trace-py/compare/v0.20.3...v0.20.4) and the [release milestone](https://github.com/DataDog/dd-trace-py/milestone/37?closed=1).
=> Release 0.20.4

ddtrace/__init__.py, ddtrace/bootstrap/sitecustomize.py, ddtrace/contrib/dbapi/__init__.py, ddtrace/contrib/sqlite3/patch.py, ddtrace/propagation/http.py, tests/contrib/dbapi/test_unit.py, tests/contrib/mysqldb/test_mysql.py, tests/contrib/psycopg/test_psycopg.py, tests/contrib/pymysql/test_pymysql.py, tests/contrib/sqlite3/test_sqlite3.py
This is a bug fix release that requires no changes to your code.
Included in this release is a fix for some database cursors where we would force `Cursor.execute` and `Cursor.executemany` to return a cursor instead of the originally intended output. This caused an issue specifically with MySQL libraries which tried to return the row count and we were returning a cursor instead.
* [core] Patch logging earlier for ddtrace-run (#832)
* [dbapi2] Fix dbapi2 execute/executemany return value (#830 )
* [core] Use case-insensitive comparison of header names during extract (#826 -- thanks @defanator)
=> Release 0.21.1

.circleci/config.yml, Rakefile, scripts/mkwheelhouse
Now that we are including C code in our package `python setup.py bdist_wheel` will try to build a platform specific wheel which causes issues when deploying a pre-release build to from our wheelhouse.
This change includes:
- Custom `scripts/mkwheelhouse` script that does what `mkwheelhouse` does, but runs `python setup.py sdist` instead
- Remove unused tasks from `Rakefile`
- Adds `python setup.py bdist_wheel` to the `test_build` CircleCI job
=> [dev/tooling] Use custom mkwheelhouse script to build/upload sdist packages

.circleci/config.yml, tests/contrib/requests_gevent/test_requests_gevent.py
We were getting connection issues with `https://icanhazip.com/` moved to `https://httpbin.org/get`
Also had to remove the `httpbin_local` container since we would try to hit that instead of the real server, and we need https for the tests to work.
=> [tests] Fix requests gevent tests

.circleci/config.yml, docker-compose.yml
The spotify cassandra image boots much faster than the official cassandra image.
Hoping this helps reduce the flakiness of this test (usually fails due to memory issues).
=> [tests] Use spotify cassandra image for tests

.circleci/config.yml, Rakefile, scripts/build-dist, scripts/mkwheelhouse
This PR:
- Adds a custom script `scripts/build-dist` to build wheels and source distribution for our package
- This also generates manylinux wheels as well
- Modifies our custom `mkwheelhouse` to upload the output wheels/sdist from `scripts/build-dist`
Example result from `scripts/build-dist`:
```
$ ls -1 dist
ddtrace-0.24.0-cp27-cp27m-linux_i686.whl
ddtrace-0.24.0-cp27-cp27m-linux_x86_64.whl
ddtrace-0.24.0-cp27-cp27m-manylinux1_i686.whl
ddtrace-0.24.0-cp27-cp27m-manylinux1_x86_64.whl
ddtrace-0.24.0-cp27-cp27mu-linux_i686.whl
ddtrace-0.24.0-cp27-cp27mu-linux_x86_64.whl
ddtrace-0.24.0-cp27-cp27mu-manylinux1_i686.whl
ddtrace-0.24.0-cp27-cp27mu-manylinux1_x86_64.whl
ddtrace-0.24.0-cp34-cp34m-linux_i686.whl
ddtrace-0.24.0-cp34-cp34m-linux_x86_64.whl …
```
=> Add script to build wheels

tests/commands/ddtrace_run_sitecustomize.py, tests/commands/test_runner.py
The current negative test is broken and is actually testing the same case
without `-S`.
That's because the condition `sys.argv[1] is '-S'` is always `False`; strings
must be compared with `==`, not `is`.
=> [tests] Fix ddtrace sitecustomize negative test

.circleci/config.yml, tox.ini
The package has been removed from PyPI entirely.
=> Remove mysql-connector 2.1 support

ddtrace/bootstrap/sitecustomize.py
If DATADOG_PATCH_MODULES is unset, the default value was '' which when used
with .split(',') does not return 2 items, logging that the patch instruction is
malformed.
This patch fixes that by checking that the value is set and non empty before
trying to patch anything.
=> [core] Fix logging with unset DATADOG_PATCH_MODULES

.circleci/config.yml, tox.ini
This is a prerequisite for Python 3.7 support.
=> Add testing for Celery 4.3

ddtrace/commands/ddtrace_run.py, setup.py, tests/commands/ddtrace_minimal.py, tests/commands/ddtrace_run_app_name.py, tests/commands/ddtrace_run_argv.py, tests/commands/ddtrace_run_debug.py, tests/commands/ddtrace_run_disabled.py, tests/commands/ddtrace_run_enabled.py, tests/commands/ddtrace_run_env.py, tests/commands/ddtrace_run_hostname.py, tests/commands/ddtrace_run_integration.py, tests/commands/ddtrace_run_logs_injection.py, tests/commands/ddtrace_run_no_debug.py, tests/commands/ddtrace_run_patched_modules.py, tests/commands/ddtrace_run_priority_sampling.py, tests/commands/ddtrace_run_service.py, tests/commands/ddtrace_run_sitecustomize.py, tests/contrib/celery/autopatch.py
The future is now! print as a function is available in Python >= 2.7.
=> Remove useless __future__ imports

ddtrace/sampler.py
In reference to [this issue](https://github.com/DataDog/dd-trace-py/issues/860).
This way these logs can be seen when debugging is turned on, but otherwise left out.
=> Use DEBUG log level for RateSampler initialization

README.md
The current instructions are confusing as they start with talking about
docker-compose, and then talk about not using it !?.
It seems that it's barely possible to run most of the tests without
docker-compose anyway, so let's keep things simple and remove those
instructions entirely.
=> Remove confusing testing instructions from README

tests/contrib/aiohttp/test_request_safety.py
The current code only yield once the thread have started, though there's a
little chance that one of the thread did not had time to actually sent its
request yet. That means that the requests will never be served and the thread
will fail.
This patch fixes this by making sure to do pass the execution to the asyncio
loop between each join, just in case a request needs to be handled.
Fixes #876
=> [aiohttp] Fix race condition in testing

.circleci/config.yml, README.md, docker-compose.yml, scripts/run-tox-scenario
This allows to group the running of tox environment list by pattern rather than
having to type and maintain the entire list of environment both in `tox.ini`
and `.circleci/config`.
=> [tests] Leverage tox environment listing to simplify CircleCI tox target list

ddtrace/writer.py, tests/test_integration.py, tests/test_writer.py
This new implementation based on the standard Python Queue class makes it possible to have blocking waits. This replaces
the `sleep` calls that were prone to race conditions by proper blocking `wait` calls.
=> [writer] Enhance Q implementation with a wait based one

ddtrace/writer.py, tests/test_writer.py
In this new episode of "Multithreading is Hard", let's a fix a rare race
condition that could occur if a thread emptied the queue just before another
thread tries to replace a random item (because the queue is full).
In order to avoid that, we check the size of the queue, and simply retry to put
the item if the queue has been emptied in the meantime.
This also adds a tiny test for the `get` method.
=> writer: fix a possible race condition in put() if queue is full

tests/contrib/tornado/test_safety.py, tests/contrib/tornado/web/compat.py
This tries to enhance test_concurrent_requests by waiting until all responses
have completed. There's still a default timeout set by tornado testing
framework (5 seconds) that can be exceeded, but that should be more solid in
practice than the previous 0.5 seconds delay that was used.
We also make sure threads worked fine by joining them rather than setting them
as daemons.
This also makes sure we use `tornado.gen.sleep` function when available.
Fixes #914
=> tests/tornado: enhance `test_concurrent_requests`

tests/opentracer/test_tracer.py
This mocks time.time to be sure of the result.
Fixes #900
=> [opentracer] Fix flaky test based on sleep

ddtrace/constants.py, ddtrace/span.py
We want to provide users with constants they can import and use instead of knowing the tag key.
```python
from ddtrace.constants import MANUAL_DROP_KEY, MANUAL_KEEP_KEY
@tracer.wrap()
def handler():
span = tracer.current_span()
if is_healthcheck():
span.set_tag(MANUAL_DROP_KEY)
elif is_error():
span.set_tag(MANUAL_KEEP_KEY)
```
=> [core] Use constants for manual.keep and manual.drop

ddtrace/contrib/django/middleware.py, tests/contrib/django/test_middleware.py
There was no test checking that the http.url tag would not contain query
string. This adds the test and fix the issue with Django.
=> django: remove query string from http.url tag

ddtrace/contrib/bottle/trace.py, tests/contrib/bottle/test.py
There was no test checking that the query string was not part of the URL and it
was actually added. Fix that and add proper testing.
=> bottle: fix query string embedded in URL

ddtrace/contrib/tornado/handlers.py, tests/contrib/tornado/test_safety.py, tests/contrib/tornado/test_tornado_web.py
The query string used to be included in http.url tag for Tornado. Let's match
the behavior of other frameworks and remove it.
=> tornado: do not include query string in the http.url tag

.circleci/config.yml, tox.ini
This should make installation faster and development easier.
=> tests: always skip sdist, use develop mode

ddtrace/constants.py, ddtrace/context.py, ddtrace/internal/hostname.py, ddtrace/settings/config.py, tests/base/__init__.py, tests/internal/test_hostname.py, tests/test_context.py
This PR adds the ability to tag trace root spans with the system hostname.
=> [core] Add config to set hostname tag on trace root span

ddtrace/_worker.py, ddtrace/internal/runtime/runtime_metrics.py, ddtrace/writer.py, tests/test_worker.py
There is at least 2 places (writer and runtime metric collectors) where the
code needs to start worker threads doing regular tasks.
This patch merge the existing code in a simple PeriodicWorker base class that
can be enhanced with custom code. It has the upside of using a
`threading.Event` rather than a sleep timer, making the exit code running as
soon as `stop()` is called.
=> Add a PeriodicWorker base class for periodic tasks

ddtrace/span.py
The currently used random generator is not re-seeded on `os.fork` calls, making
span id collision a sure thing.
This is only a problem on Python 2 — Python 3 does not show this issue.
This patches changes the random number generator to use the system ones based
on urandom. This avoids the issue altogether.
=> span: use system random source to generate span id

tests/opentracer/test_tracer.py
The `opentracer` tests failed in CI on a test where spans written by two threads were expected to be in a specific order, but this was not stable. This PR adds thread synchronization to ensure the order for spans is as expected.
Fixes #893
=> [tests] fix threading synchronization to opentracer test

ddtrace/writer.py
There's no way to know that the queue is getting full and that some traces are
dropped. At least write a log message so the user knows something's wrong.
=> writer: log a message when a trace is dropped

tests/opentracer/test_tracer.py
The addition of event synchronization for threads in #924 still left the possibility for the second thread to start writing spans before the first. This PR ensures that the second waits for the first to start a span context.
```
=================================== FAILURES ===================================
_________________ TestTracer.test_start_span_multi_intertwined _________________
self = <tests.opentracer.test_tracer.TestTracer object at 0x7f168001ae48>
ot_tracer = <ddtrace.opentracer.tracer.Tracer object at 0x7f168001a208>
writer = <tests.utils.tracer.DummyWriter object at 0x7f16800845c0>
def test_start_span_multi_intertwined(self, ot_tracer, writer):
"""Start multiple spans at the top level intertwined.
Alternate calling between two traces.
"""
import threading
event = …
```
=> [tests] Fix thread synchronization

tests/test_sampler.py
The `RateSamplerTest.test_sample_rate_deviation` was failing for `sample_rate = 0.1`. The actual deviation was 0.0216 though the manual threshold is set to 0.02. While we could increase the number of iterations or do more convergence testing, we are increasing the deviation threshold to 0.05 to keep a reasonable upper bound in place while making the test less brittle.
```
__________________ RateSamplerTest.test_sample_rate_deviation __________________
self = <tests.test_sampler.RateSamplerTest testMethod=test_sample_rate_deviation>
def test_sample_rate_deviation(self):
for sample_rate in [0.1, 0.25, 0.5, 1]:
tracer = get_dummy_tracer()
writer = tracer.writer
tracer.sampler = RateSampler(sample_rate)
random.seed(1234)
iterations = int(1e4 / sample_rate)
for i in range(iterations):
span = …
```
=> [tests] fix brittle deviation test for tracer

ddtrace/contrib/bottle/trace.py, tests/contrib/bottle/test.py
Datadog isn't recording the correct HTTP status code when using `abort(status_code, 'message)`.
This PR fix this issue.
Thanks.
=> Record HTTP status code correctly when using abort() with Bottle

ddtrace/contrib/grpc/patch.py, tests/contrib/grpc/test_grpc.py
The `target` for a GRPC channel can be specified with a keyword argument instead of a positional argument in both the function `grpc.insecure_channel` and `grpc.secure_channel`. See, for example, this [usage](https://github.com/googleapis/google-cloud-python/blob/4166ddbf1f8b07c2a5e2db8f7955457b5cedd82d/pubsub/google/cloud/pubsub_v1/publisher/client.py#L70-L72) in the official google pubsub client.
Currently, the datadog patch only uses the positional argument to get the `target` parameter, which throws the following exception if the keyword argument is used by a client:
```
>       target = args[0]
E       IndexError: tuple index out of range
```
For a simple example of client code that reproduces this error, see this [gist](https://gist.github.com/asnr/8f4fdffef9bccb7d4632ae2a4968ee0b). …
=> Support keyword 'target' parameter when wrapping GRPC channels

setup.py
PSUtilRuntimeMetricCollector uses `.oneshot` which only comes with version 5 or higher.
=> make psutil requirement more accurate

ddtrace/tracer.py
the function may return `None`. guard against that in the example
=> fix documentation for current_root_span

tox.ini
tests/integration does not exists; the file tests/test_integration.py is more
likely what we want to ignore.
=> tox: fix ignore path for integrations

ddtrace/api.py
The length is always provided and should be included in every request, so make
it mandatory.
Move the header name variable to the local API class, making it overridable by
a subclass — you never know!
=> api: simplify _put codepath

ddtrace/bootstrap/sitecustomize.py, ddtrace/commands/ddtrace_run.py, ddtrace/contrib/aiobotocore/patch.py, ddtrace/contrib/aiohttp/middlewares.py, ddtrace/contrib/aiopg/connection.py, ddtrace/contrib/aiopg/patch.py, ddtrace/contrib/asyncio/helpers.py, tests/contrib/aiobotocore/py35/test.py, tests/contrib/aiobotocore/test.py, tests/contrib/aiohttp/app/web.py, tests/contrib/aiohttp/test_middleware.py, tests/contrib/aiohttp/test_request.py, tests/contrib/aiohttp/test_request_safety.py, tests/contrib/aiohttp/test_templates.py, tests/contrib/aiopg/py35/test.py, tests/contrib/aiopg/test.py, tests/contrib/asyncio/test_helpers.py, tests/contrib/asyncio/test_tracer.py, tests/contrib/asyncio/test_tracer_safety.py, tests/contrib/flask/test_middleware.py, tests/contrib/molten/test_molten.py, tests/contrib/molten/test_molten_di.py, tests/contrib/test_utils.py, tests/contrib/tornado/test_executor_decorator.py, tests/contrib/tornado/utils.py, tests/contrib/tornado/web/compat.py, tests/opentracer/test_tracer_asyncio.py, tests/test_compat.py, tox.ini
This allows to remove a few noqa flag from files using `yield from` and fixing
various errors.
The compat tests have been merged to a single scenario that works for both
Python version in order to make flake8 happier.
Some wild noqa tag have been replaced by specific flake8 error code ignore tag
so avoid skipping non-wanted mistakes.
=> Run flake8 with Python 3

.circleci/config.yml, README.md, tests/benchmark.py, tox.ini
This PR adopts `pytest-benchmarks` for writing benchmarks, adds new benchmarks for the tracer, and includes reporting benchmarks results in the CI.
=> [tests] Add benchmarks

ddtrace/internal/runtime/runtime_metrics.py, ddtrace/tracer.py, tests/internal/runtime/test_runtime_metrics.py
- Fixes shutdown of runtime workers and add test
- Avoid unnecessary setting services
=> Fix runtime workers not flushing to Dogstatsd

ddtrace/__init__.py
This release introduces some important core improvements and continues addressing pain points in our tooling and testing. 
* Add a PeriodicWorker base class for periodic tasks (#934)
* Fix runtime workers not flushing to Dogstatsd (#939)
* api: simplify _put codepath (#956)
* make psutil requirement more accurate (#949 -- thanks @chrono)
* writer: log a message when a trace is dropped (#942)
* span: use system random source to generate span id (#940)
* [core] Add config to set hostname tag on trace root span (#938)
* Support keyword 'target' parameter when wrapping GRPC channels (#946 -- thanks @asnr)
* Record HTTP status code correctly when using abort() with Bottle (#943 -- thanks @equake)
* boto: add support for Python 3.5+ (#930)
* fix documentation for current_root_span (#950 -- …
=> Update ddtrace version for 0.26

ddtrace/sampler.py, tests/test_sampler.py
The current implementation it overly complicated and needs to use a Lock to be
thread safe. This new one does not.
Fixes #935
=> sampler: rewrite RateByServiceSampler without using Lock

ddtrace/api.py, ddtrace/payload.py, ddtrace/writer.py, tests/test_integration.py, tests/test_payload.py
Rather than trying to guess if we're going to hit the maximum size, actually
raise a PayloadFull exception when the payload is full and let the caller
handle the problem. This should divide the number of API call by 2 when a lot
of traces are being sent at once.
This patch also fixes the hypothetical case where a trace wouldn't fit in a
single Payload.
This also makes sure we don't re-build the payload when we need to downgrade
the API by splitting out the _flush method out of the `send_traces` method.
=> payload: raise PayloadFull on full payload

ddtrace/contrib/pymongo/parse.py
opcode `1000` was deprecated awhile ago, `2013` is now used for `msg`.
This PR updates our parser to know about `2013`.
=> pymongo: Add missing 2013 opcode

ddtrace/context.py, ddtrace/span.py, tests/test_context.py
Rather than using a clumsy way of counting finished spans, actually checks
the traces attached to the context. This simplify the logic.
We also make sure that the context.close_span() method is always called when
finishing a span, whether a tracer is present or not.
=> context: don't count finished spans

ddtrace/context.py, ddtrace/opentracer/span_context.py, tests/opentracer/test_span.py, tests/opentracer/test_tracer.py, tests/test_context.py
Rather than carrying a dedicated flag on the Context object, sample the spans
if any of them is sampled.
=> context: determine if context is sampled based on traces

ddtrace/contrib/sqlalchemy/engine.py, ddtrace/settings/integration.py, tests/contrib/sqlalchemy/test_patch.py
We were always attempting to set the sample rate for `sqlalchemy`, the default value is `None` which causes `span.set_tag(ANALYTICS_SAMPLE_RATE, None)` to log an error (debug).
=> [sqlalchemy] Only set sample rate if configured

ddtrace/api.py, ddtrace/writer.py, tests/test_api.py
This should makes it easier to have a string representation of the API endpoint
when needed.
=> api: implement __str__

ddtrace/contrib/aiopg/connection.py, ddtrace/contrib/aiopg/patch.py, ddtrace/contrib/psycopg/patch.py
Not sure if I need to add much more information, it's just a typo fix.
=> Fix a typo in AIOTracedCursor docstring

ddtrace/contrib/aiopg/connection.py, tests/contrib/aiopg/py37/test.py
Closes #983
I don't know if there was a way to implement the test with a little less boilerplate copy-paste, but it works now.
I've done it in 2 commits, feel free to check that the first one showcases the error.
=> Refs #983 - Make AIOTracedCursor an async generator 

ddtrace/contrib/pymongo/parse.py, tox.ini
Newer versions of Mongo support sending a generic `OP_MSG` request instead of `OP_QUERY`, we should support these versions.
=> [pymongo] Support newer msg requests

Rakefile
This leverages scripts/build-dist to build the wheel and upload them to PyPI
when it's time to release.
=> Upload wheels on release

ddtrace/api.py, ddtrace/bootstrap/sitecustomize.py, ddtrace/contrib/flask/middleware.py, ddtrace/internal/runtime/collector.py, ddtrace/internal/runtime/runtime_metrics.py, ddtrace/utils/hook.py, ddtrace/writer.py, tests/internal/runtime/test_metrics.py, tests/test_hook.py
I have 100's of deprecation warnings in my tests because `log.warn` is deprecated.
Example of warning:
```
/usr/local/lib/python3.6/site-packages/ddtrace/writer.py:163: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
This PR simple use log.warning - nothing impressive :)
=> writer: fix deprecated log.warn use

.circleci/config.yml, ddtrace/__init__.py, scripts/build-dist, setup.py
This leverages setuptools_scm to generate version number for the libary rather
than updating manually. It will leverages git tags to produce adequate numbers.
For dev version, it'll generate version numbers such as
`0.27.1.dev7+gdeb1fb54.d20190723` which are pretty explicity about where the
version is at.
Since we now produce and distribute wheels, setuptools-scm is only a
requirement if someone installs from source — which should not be the case for
anyone using pip.
This should simplify maintenance and distribution overall.
=> Use setuptools_scm to handle version numbers

docker-compose.yml
I was trying to decide between this and the env variable `setuptools_scm` allows for overriding the version, but decided to use `.git` since that is a behavior we want to test to ensure it always works.
=> [dev] Map .git into ddtest for setuptools_scm

ddtrace/contrib/django/middleware.py, ddtrace/contrib/django/utils.py
There is a chance that building the original url from the Django request using `request.build_absolute_uri` could raise an exception and cause us to fail to trace the request all together.
This PR adds in a new helper which does (almost) what `build_absolute_uri` does but ensures that we guard against potential failures and ensures the url is formatted as we format them for other frameworks (without query string/fragments/etc).
=> [django] Update how we get the http.url

tox.ini
Some generic test utilities that are either nice to have or plan to use in the future. Adding now to make it easier to run/test locally.
`pdbpp` - a better `pdb`... because... it's better.
`pytest-cov` - we want to add coverage testing and reporting across everything at some point, but for now I find it is sometimes helpful to have and use `pytest-cov` locally when building something new to ensure I didn't miss a branch of code in my tests.
=> [tests] Adding in helpful default packages

ddtrace/contrib/pylibmc/client.py, tests/contrib/pylibmc/test.py
Fixes #831
@yevhen-m found where the issue was coming from, so this PR is a patch to the problem.
The issue is that if the tracer was disabled then the `self._span()` call would return `None`, which is does not have a `__exit__`/`__enter__` methods so calling `with self._span() as span:` would fail.
=> [pylibmc] Fix client when tracer is disabled

ddtrace/contrib/django/middleware.py, tests/contrib/django/test_middleware.py
Only try to set the analytics sample rate if a sample rate is available.
This saves us from potentially having `span.set_tag(ANALYTICS_SAMPLE_RATE_KEY, None)`
=> [django] Only set sample rate if rate is set

ddtrace/api.py, ddtrace/internal/runtime/container.py, tests/internal/runtime/test_container.py, tests/internal/runtime/utils.py, tests/test_api.py, tests/test_integration.py
In this PR we are adding in a utility for parsing the current container id from `/proc/self/cgroup` and sending it as a header to the trace agent.
=> [core] Parse and send container id with payloads to the agent

ddtrace/contrib/pymongo/client.py, tox.ini
PyMongo 3.9 changed a traced function `send_message_with_response` to `run_operation_with_response`.
This PR updates our patching and test suite.
=> [pymongo] Add support for PyMongo 3.9

ddtrace/contrib/tornado/__init__.py
We were missing documentation that explained the tornado integration requires subclasses of `RequestHandler` to call patched methods that are overridden.
=> [tornado] document overriding on_finish and log_exception

ddtrace/contrib/django/apps.py, ddtrace/contrib/django/patch.py, tests/contrib/django/test_connection.py
Fixes #1014
Management commands don't call `connections.all()` anywhere by default and as a result, are excluded from being patched unless a user manually makes that call. This will instead call this inside the AppConfig for the Django app so that all processes benefit from tracing by default.
This also moves the code into a function outside the ready which solves 2 things:
1. It's easier to test.
1. It means we can reuse this code in our django 1.6 app rather than copying it in.
=> Patch DBs in django app config

ddtrace/contrib/tornado/__init__.py, ddtrace/contrib/tornado/decorators.py, ddtrace/contrib/tornado/stack_context.py, tests/contrib/tornado/test_stack_context.py, tests/contrib/tornado/test_tornado_web.py, tox.ini
This PR adds support for Tornado 5 and 6 for Python 3.7 since #990 makes `ddtrace.contrib.tornado.stack_context` unnecessary for handling contexts cleanly between asynchronous tasks.
=> [tornado] Add support for Tornado 5 and 6 with Python 3.7

ddtrace/internal/rate_limiter.py, ddtrace/sampler.py, tests/internal/test_rate_limiter.py, tests/test_sampler.py
**Note this PR is merging into `brettlangdon/datadog.sampler` not `master`**
This PR adds in `RateLimiter.effective_rate` to return the effective sample rate at that time based on the total number of traces seen vs the number of sampled traces in any given 1s rolling window.
TODO:
=> [internal] Add rate limit effective sample rate

ddtrace/contrib/grpc/client_interceptor.py, ddtrace/contrib/grpc/patch.py, tests/contrib/grpc/test_grpc.py
Resolves:
* GRPC patching incorrectly handles arbitrary exceptions #1039
* Missing gRPC status code #1018
* Interceptor ordering with `grpc.intercept_channel`
=> [grpc] Fix channel interceptors

.circleci/config.yml, ddtrace/contrib/consul/__init__.py, ddtrace/contrib/consul/patch.py, ddtrace/monkey.py, docker-compose.yml, docs/db_integrations.rst, docs/index.rst, tests/contrib/config.py, tests/contrib/consul/test.py, tox.ini
Automatically instruments consul connections to trace KV calls. Only works for sync client.
=> [consul] Add instrumentation for consul

ddtrace/context.py, ddtrace/opentracer/span.py, ddtrace/span.py, tests/opentracer/test_span.py, tests/opentracer/test_tracer.py, tests/opentracer/test_tracer_gevent.py, tests/test_context.py
There is currently no way to know if a span is finished or not. There's no
reason to keep this attribute private.
=> span: expose finished attribute

ddtrace/bootstrap/sitecustomize.py, ddtrace/commands/ddtrace_run.py, ddtrace/context.py, ddtrace/tracer.py, tests/commands/ddtrace_run_debug.py, tests/commands/ddtrace_run_no_debug.py, tests/commands/test_runner.py, tests/contrib/flask/test_middleware.py, tests/memory.py, tests/test_api.py, tests/test_context.py
This removes the debug_logging option. This should not be necessary as
configuring the logging level for the tracer ought to be enough to control what
is logged or not.
That simplifies the logging logic by avoiding two knobs to control one thing.
=> tracer: remove debug_logging option

tests/internal/runtime/test_metric_collectors.py
The current test checks the value returned by the gc, but it regularly fails:
>       self.assertLess(collected_after[0][1], collected[0][1])
E       AssertionError: 9 not less than 8
The computing method is not 100% reproducible and depends on the GC state.
Since we're not really interested in testing the GC anyway, let's simplify the
test and check what's important for us.
=> runtime metrics: fix gc0 test

ddtrace/internal/writer.py, tests/internal/test_writer.py
This adds some stats to our Q to know how many objects we enqueue/drop and the
cumulative size of those objects.
=> writer: add statistics to Q

ddtrace/tracer.py, tests/internal/runtime/test_runtime_metrics.py, tests/utils/tracer.py
- The current code does not allow to disable collect_metrics by passing `False`
to it.
- The recent change from 2c41f15838d1baa96ef3fda2e37e5bc182c9f774 made the hack
in test_runtime_metrics to change the FLUSH_INTERVAL a noop, making the test
taking 20 seconds to complete.
This patch fixes both issues by allowing the `collect_metrics` arguments to be
a boolean or a float representing the interval in seconds to use to collect the
runtime metrics. This makes sure users can disabled runtime metrics at any
time, and fixes the test for running in a less than a second.
=> tracer: fix configure(collect_metrics) argument

ddtrace/contrib/cassandra/session.py, tests/contrib/cassandra/test.py
When a bound statement is batched, the query string it uses is it's
query_id which is bytestring (and not an encoded one, just a raw bytes
sequence) so when it is attempted to be joined using a unicode string
(in python3) it raises an exception due to mixed types during query
sanitization.  If the prepared flag is set to `True` on the statements
list, don't include the query_id.
With the added test (but before the change to `session.py`):
```
elif t == 'BatchStatement':
resource = 'BatchStatement'
>           q = '; '.join(q[1] for q in query._statements_and_parameters[:2])
E           TypeError: sequence item 0: expected str instance, bytes found
ddtrace/contrib/cassandra/session.py:264: TypeError
```
=> [contrib/cassandra] Handle batched bound statements in python3

ddtrace/sampler.py, tests/test_sampler.py
If a string is passed in then we get the following error:
```python
>>> '1' * (2 ** 64)
File "<stdin>", line 1, in <module>
OverflowError: cannot fit 'int' into an index-sized integer
```
Explicitly cast sample rate to a `float` to at least raise a `TypeError` if it isn't "floatable"
=> [core] Ensure we cast sample rate to a float

ddtrace/internal/writer.py, ddtrace/utils/sizeof.py, tests/internal/test_writer.py, tests/test_utils.py
This adds memory statistics to the Q object used by the internal writer.
This also renamed 'enqueued' to 'accepted' to make it easier to understand.
=> writer: add memory size statistics to the queue

ddtrace/api.py, ddtrace/internal/writer.py, ddtrace/tracer.py, tests/internal/test_writer.py
This adds dogstatsd support to the AgentWriter thread. When flushing traces,
the writer will flush various statistics to the local dogstatsd agent.
=> Flush writer stats to dogstatsd

ddtrace/api.py, ddtrace/internal/writer.py, ddtrace/opentracer/settings.py, ddtrace/opentracer/tracer.py, ddtrace/tracer.py, docs/advanced_usage.rst, tests/test_api.py, tests/test_integration.py
We have collectors deployed behind an AWS NLB that does TLS termination so we'd like HTTPS support.
This will have conflicts with #1054.
=> [core] Add HTTPS support

ddtrace/monkey.py
Make expected behavior follow https://github.com/datadog/dd-trace-py/blob/majorgreys%2Fenable-rediscluster-by-default/docs/index.rst#L109 and the `rediscluster` integration be enabled by default.
=> [internal] enable rediscluster by default

ddtrace/span.py, ddtrace/utils/sizeof.py, tests/test_utils.py
This should make computing the size of e.g. Spans faster, as the code currently
tries to compute also the size of the Tracer and attached Context.
=> utils/sizeof: allow to ignore certain field when computing object size

ddtrace/tracer.py, docs/installation_quickstart.rst, tests/test_tracer.py
This makes possible to use an URL to configure the Tracer rather than different
variables.
This also starts a process where Tracer.configure is not going to be the right
way to set the tracer up, but the parameter are used on Tracer initialization.
Fixes #1052
=> tracer: allow to override agent URL with a env var

ddtrace/internal/writer.py, tests/internal/test_writer.py
The current rate of sending metrics every 1 second is too heavy and impacts the
performance. Let's do this only every 10 seconds by default, so we're sure our
perf impact is quite small.
=> writer: send statistics less often and disable by default

ddtrace/opentracer/tracer.py, tests/opentracer/test_tracer.py
When creating a new opentracing span via the tracer, it must set the tags on the
opentracing span, and not directly on the underlying ddspan in order to ensure
that the special compatibility tags (resource name, sampling priority, etc) are
processed correctly.
=> Fix for opentracing compatibility tags not being set correctly when creating a new span.

ddtrace/compat.py, ddtrace/span.py, tests/opentracer/test_tracer.py
This improves span precision. Note that time_ns is only available on Python 3.
=> span: use ns time directly rather than converting

ddtrace/tracer.py
For the code example for get_call_context under the Tracer API, instead of
```
from ddtrace import import tracer
async def web_handler(request):
```
the import should look like this:
```
async def web_handler(request):
```
This is to address this doc example: http://pypi.datadoghq.com/trace/docs/advanced_usage.html?highlight=tags#ddtrace.Tracer.get_call_context .
=> Remove extra import from tracer get_call_context code snippet

ddtrace/api.py, ddtrace/internal/writer.py, ddtrace/utils/time.py, tests/test_integration.py, tests/unit/utils/test_time.py
`time.time` might jump around as the clock changes (NTP, leap seconds, etc).
It's safer to use monotonic.monotonic to get elapsed time ranges.
=> Replace time.time by monotonic clock

ddtrace/span.py, tests/test_span.py
duration_ns should always be an integer, though the current code would return a
float if finish_time is passed as a float.
=> span: fix {duration,start}_ns being float if {start,finish} is passed as float

ddtrace/contrib/grpc/client_interceptor.py, tests/contrib/grpc/test_grpc.py
Make sure to set `span.error` properly when exception is handled. This was not covered by tests so update those as well.
=> grpc: set error attribute on client span for exceptions

ddtrace/internal/logger.py, tests/internal/test_logger.py
Fixes #1115.
This avoids message duplication in Sentry.
=> internal: use args for LogRecord when logging

ddtrace/vendor/__init__.py, ddtrace/vendor/dogstatsd/base.py, tests/vendor/test_dogstatsd.py
If we are unable to connect to a dogstatsd server then the log messages could get noisy if we have health metrics enabled by default
=> internal: Update dogstatsd to use ddtrace.internal.logger.get_logger

ddtrace/internal/writer.py
This PR removes the sampling logic and goes back to sending stats on every flush.
Since we removed the heavier `sizeof` metrics we should be able to do this no problem.
If we find that we do need to limit the frequency again we need to figure out how to still collect all the metrics between each flush (e.g. total traces flushed between each stats flush) and then ensure we flush them in a way that works for sending once per X seconds.
=> internal: send health metrics on every flush

ddtrace/internal/writer.py, tests/internal/test_writer.py
**Depends on #1129**
The way we have the current stats sending structured we will only send stats if the queue is not empty, but we want to send stats on every iteration of the writer to ensure consistent metrics are available, even if the numbers are 0. Otherwise it'll look like writers are coming and going a lot.
This PR does a few things:
- Restructure `run_periodic` and `on_shutdown` to ensure some metrics are always sent
- Add `datadog.tracer.heartbeat` metric
- Add `datadog.tracer.shutdown` metric
- Turn some existing metrics into `histogram`s and rename a few
- This will allow us to find outliers on a "per-flush" basis, e.g. `min/median/avg/max/p95` traces flushed per iteration of the writer
=> internal: restructure stats sending

ddtrace/internal/writer.py, tests/internal/test_writer.py
We currently report CPU time as an ever increasing number, instead we want to report it as the difference between the previous CPU time and now in seconds.
=> internal: report cpu time as histogram diff of last time

ddtrace/internal/writer.py, tests/internal/test_writer.py
Sending as a histogram is great to get per-flush aggregation metrics, but we need to send as a counter as well to get the total number.
Histograms do support `.sum` aggregations but they must be enabled in the agent and are disabled by default.
=> internal: use histogram and counters for metrics

ddtrace/internal/writer.py, ddtrace/settings/config.py, tests/base/__init__.py, tests/internal/test_writer.py
Move away from a private property to control whether health metrics are enabled and move to config API.
```python
config.health_metrics_enabled = True
```
It is disabled by default for now.
=> internal: move health metrics enabled to config

.circleci/config.yml, docker-compose.yml, pyproject.toml, tox.ini
This PR adds a `black` step to the CI but it ignores every file by default.
In the future we can slowly start to remove files/directories from the blacklist and roll `black` formatting out everywhere.
=> ci: add black step to ci

tox.ini
Version 8.0.18 is causing segfaults in sqlalchemy tests.
Signed-off-by: Alex Boten <aboten@lightstep.com>
=> Fixing sqlalchemy test failures

ddtrace/tracer.py, ddtrace/vendor/__init__.py, ddtrace/vendor/debtcollector/__init__.py, ddtrace/vendor/debtcollector/_utils.py, ddtrace/vendor/debtcollector/moves.py, ddtrace/vendor/debtcollector/removals.py, ddtrace/vendor/debtcollector/renames.py, ddtrace/vendor/debtcollector/updating.py, tests/test_tracer.py
Vendor [debtcollector](https://github.com/openstack/debtcollector) and use it to deprecate keyword arguments instead of existing approach where a warning is generated within code.
=> internal: use debtcollector for keyword argument warnings

tox.ini
The new version of multidict released yesterday (4.6.0) causes failures in aiobotocore2 tests. Pinning version as a workaround. Note: I ran into this problem only once the build cache had been invalidated.
Signed-off-by: Alex Boten <aboten@lightstep.com>
=> Pin multidict dependency for aiobotocore02 tests

ddtrace/vendor/debtcollector/_utils.py, ddtrace/vendor/debtcollector/moves.py, ddtrace/vendor/debtcollector/removals.py, ddtrace/vendor/debtcollector/renames.py, ddtrace/vendor/debtcollector/updating.py
This adjustment had already been applied elsewhere in the vendored code but I had missed `ddtrace/vendor/debtcollector/_utils.py`. When I attempted to run it locally I got:
```
ModuleNotFoundError: No module named 'six'
```
I am not sure why this did not cause problems in CircleCI.
=> vendor: fix debtcollector imports

.circleci/config.yml, ddtrace/contrib/dogpile_cache/__init__.py, ddtrace/contrib/dogpile_cache/lock.py, ddtrace/contrib/dogpile_cache/patch.py, ddtrace/contrib/dogpile_cache/region.py, docs/db_integrations.rst, tests/contrib/dogpile_cache/test_tracing.py, tox.ini
[dogpile.cache](https://dogpilecache.sqlalchemy.org/en/latest/) is a library that provides a distributed locking mechanism to avoid the ['dogpile' problem](https://en.wikipedia.org/wiki/Cache_stampede) and provides an abstraction that simplifies the integration of multiple caching systems into an application.
Adding tracing to dogpile may sound redundant, but it turns out just tracing a caching system (eg. memcache) isn't that helpful _if_ you're using something like consistent hashing, which requires the cache keys be hashed so they can be evenly distributed across a cache cluster. So adding tracing at dogpile's layer can give us insight into the actual raw keys that were requested in a function call in addition to more information about the caching setup (eg. what caching system was …
=> Add support for dogpile.cache

ddtrace/sampler.py, ddtrace/tracer.py, tests/test_sampler.py
Right now the defaults are:
1) Fallback to the "rate by service" sampler whenever no matching rule is found
2) 100 traces sampled per second max
With these defaults:
1) 100% of all traces
2) No rate limit
=> core: change DatadogSampler defaults

ddtrace/contrib/bottle/trace.py, tests/contrib/bottle/test.py
This PR is a fix for #1156. 
The integration currently does not support handle when a `HTTPResponse` is raised, whereas we only had handled `HTTPError` exceptions.
While fixing exception handling, I also found that the handling of the response in the wrapping function was not pulling out the correct status code for the response being returned. The code had been using the current value of `bottle.response` but this had not yet been bound to the response from the callback. We should use the return value of the callback to set the span tag for HTTP status. When a route function returns a `str`, we continue using the default response status.
=> bottle: fix status code for responses

ddtrace/ext/__init__.py, ddtrace/ext/consul.py, ddtrace/ext/sql.py, ddtrace/utils/__init__.py
When upgrading `ddtrace` internally I noticed that an import of `ddtrace.ext.AppTypes` was failing because it was removed.
Instead we should add a deprecation warning so that we do not break anyone's applications.
=> core: Deprecate ddtrace.ext.AppTypes

ddtrace/contrib/elasticsearch/patch.py, ddtrace/ext/cassandra.py, ddtrace/ext/elasticsearch.py, ddtrace/ext/http.py, ddtrace/ext/kombu.py, ddtrace/ext/memcached.py, ddtrace/ext/mongo.py, ddtrace/ext/redis.py, ddtrace/ext/sql.py
#1144 and #1150 removed `app_type` and reworked how span types were organized. While #1162 added back `ddtrace.ext.AppTypes` with deprecation warnings, several of the `ddtrace.ext.*` modules also contained `APP_TYPE` or `TYPE` attributes that need to also be restored and flagged for deprecation as to avoid breaking existing code.
=> core: safely deprecate ext type constants

ddtrace/sampler.py, tests/base/__init__.py, tests/test_sampler.py, tests/utils/__init__.py
We want to ensure we have a sane default rate limit for the sampler.
As well, we want to allow people to use `DD_TRACE_SAMPLE_RATE` and `DD_TRACE_RATE_LIMIT` to configure these default values for the new sampler.
=> core: fix new sampler defaults and add env variables to configure

setup.py
This is breaking my build right now when I try to upgrade versions.
This could be because I'm using poetry which expects it to be encoded rather than an `if` condition. Not sure. But this seems to be how lots of packages do this specification in setup.py
=> encode python in the install_requires string

setup.py
Small modification to avoid install `enum34` backport for Python 3.4 after move to environment markers with #1174.
=> not install enum34 for Python 3.4

setup.py
Since 0.32.0, the vendored `debtcollector` depends on `funcsigs` before Python 3.3 but this had not been specified for installation at setup, causing an `ImportError` exception when importing `ddtrace` or running `ddtrace-run` on Python 2.7 if `funcsigs` had not been installed as a dependency of another library.
=> add funcsigs backport to install

tox.ini
PyYAML 5.3 dropped support for Python 3.4, we need 5.2 or lower
=> tests: Fix botocore py34 tests

ddtrace/internal/writer.py, ddtrace/sampler.py, ddtrace/tracer.py, tests/test_sampler.py
We have made a change to ensure that, if no explicitly defined rules match and no global sample rate is defined, we continue to use a `RateByServiceSampler`.
I tried to unify the logic here a bit more to make it easier to drop in a `DatadogSampler` as the default without needing to rely on configuring/passing priority samplers around, hopefully it makes it more clear.
How people can utilize this new sampler:
1) Set `DD_TRACE_SAMPLE_RATE=` env variable to set a global rate limit
a) this will by-pass the `RateByServiceSampler`
2) Configure and pass in the sampler manually:
```python
from ddtrace.sampler import DatadogSampler
tracer.configure(sampler=DatadogSampler(sample_rate=1.0, rules=[ ... ], rate_limit=100))
```
=> core: Update default sampler to new DatadogSampler

ddtrace/span.py
This is a follow-up to a change originally made in https://github.com/DataDog/dd-trace-py/pull/940.
In #940, we started using a urandom-based implementation of `getrandbits` to work around a problem in Python 2. The downside of this plan is that the urandom implementation is around 15x-20x slower than the default implementation at `random.getrandbits`.
Instead of changing to the urandom implementation in all cases, this PR changes it so that we only fall back to the slower urandom implementation if we are actually in Python 2. Python 3 and above can continue using the fast version.
```
Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.10.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import random …
```
=> Prefer random.getrandbits on Python 3+, fall back to urandom implementation on 2

tox.ini
`jsonpatch==1.25` removed support for Python 3.4.
=> tests: fix botocore tests on py3.4

ddtrace/contrib/django/middleware.py, ddtrace/contrib/grpc/client_interceptor.py, ddtrace/contrib/requests/connection.py, pyproject.toml, tests/contrib/dogpile_cache/test_tracing.py, tests/contrib/pyramid/utils.py, tests/internal/test_writer.py, tests/opentracer/test_tracer.py, tests/propagation/test_http.py, tox.ini
black does not respect those error codes and therefore they should be ignored.
It does support W503 so that one should be included.
This patch therefore black-ifies the files that do not respect W503.
=> chord(flake8,black): ignore W504 and E231 not respected by black

.circleci/config.yml
This should help with concurrency in CircleCI and help speed up the slow Django builds
=> tests: Run django_contrib and django_drf_contrib tests separately

tox.ini
The API changed in Werkzeug >= 1 and is not compatible with older Flask
version. Capping Werkzeug makes tests work again.
=> fix(ci): limit Werkzeug to <1 for old Flask version

tox.ini
This makes running flake8 in tox faster.
=> fix(tox): flake8 does not need to install ddtrace

tox.ini
This is a follow-up of #1200, doing the same thing for black.
=> ci(tox): do not install ddtrace for running black

tox.ini
We don't use ddtrace at all, we just run a Python script.
=> ci(wait): do not install ddtrace in the wait target

.circleci/config.yml
This currently fails since the docs are not built by rake anymore (I presume).
- Remove unneeded `sudo` usage in docs target
- Upgrade deploy_dev to Python 3.8
=> ci(docs): fix deploy_dev target for releasing docs

.circleci/config.yml
There's no need to pull our custom images there.
=> ci(update): use standard Python images for black and flake8 jobs

tox.ini
https://tox.readthedocs.io/en/latest/example/general.html#basepython-defaults-overriding
```
basepython defaults, overriding
For any pyXY test environment name the underlying pythonX.Y executable will be searched in your system PATH.
```
=> ci(tox): remove useless basepython specifiers

pyproject.toml, tests/test_integration.py
This has been removed in msgpack 1.0.0.
Just use the decoder decode method.
=> Support msgpack 1.0.0

ddtrace/encoding.py
msgpack 1.0.0 has a different default behaviour which returns string rather
than bytes. Keep it to bytes by default for all versions.
Note that this is only used in testing anyway.
=> fix(encoding): always return bytes when decoding

tests/test_encoders.py
Extend #1220 to remaining tests calling `unpackb` directly.
=> fix(tests): use encoder decode in tests

ddtrace/contrib/django/__init__.py, docs/installation_quickstart.rst, tox.ini
We need the package installed for `sphinx.ext.autodoc` to work. This PR also raises any warnings from sphinx as errors.
=> fix(tox): do not skip install for docs

.circleci/config.yml, tox.ini
There's a regression in virtualenv >= 20 that makes one of the ddtrace-run +
Celery test to fails.
virtualenv now adds a site.py which modifies sys.path and breaks the PYTHONPATH
that is set by ddtrace-run.
=> ci: requires virtualenv < 20

ddtrace/contrib/rediscluster/patch.py, tests/contrib/rediscluster/test.py, tox.ini
Fixes #1224
Version `2.0.0` dropped `Strict` from the name of properties.
This PR ensures we use the correct class names, and updates CI to test with latest version.
=> rediscluster: Add support for v2.0.0

tests/test_api.py
This is not portable, errno values might be different on other platforms.
=> fix(tests): do not use numeric value for errno

.circleci/config.yml
Latest build on `master` has failed at `deploy_dev` because `cython` wasn't installed.
=> ci: make sure we install cython for deploy_dev

.circleci/config.yml, setup.py, tox.ini
Adds Python 3.8 support to `tox.ini` and `.circleci/config.yml`.
Also changes the docker image to use the one published to https://github.com/DataDog/dd-trace-ci.
=> Add Python 3.8 support

ddtrace/contrib/django/patch.py, ddtrace/contrib/django/utils.py, tests/contrib/django/test_django.py
Fixes #1231 
The new Django integration in `0.34.0` began using Django request's own methods to build the value for `http.url`. Unfortunately calling method threw an internal Django exception inside our patching code when a request host is not found in the `ALLOWED_HOSTS` setting.
This PR re-introduces `utils.get_request_uri()`  from `<0.34.0` and modifies it given the approach take in `0.34.0` but avoids throwing the exception by calling a different internal method for getting the request host. This latter modification only applies to `django>=1.19`.
=> fix(django): handle disallowed hosts

tox.ini
We specify Python 3.7 as a base in tox whereas the target runs on Python 3.8 in
the CI. Use the CI Python version rather than the one specified here.
=> chore(ci): use system Python version for flake8 and black target

ddtrace/compat.py, ddtrace/contrib/django/patch.py, tests/contrib/django/django1_app/urls.py, tests/contrib/django/django_app/urls.py, tests/contrib/django/test_django.py, tests/contrib/django/views.py
Fixes #1234 
We added instrumentation to trace Django class-based views in 0.34.0. Unfortunately the way we were patching the view methods did not work when a method was specified as a static method.
This is due to how the `wrapt` library we vendor [resolves](https://github.com/GrahamDumpleton/wrapt/blob/8f2c9c3427047dc642be62797fd8a95005e87958/src/wrapt/wrappers.py#L742) attributes to be wrapped using `getattr`. The solution here is a workaround for how we are using `wrapt`. I opened https://github.com/GrahamDumpleton/wrapt/issues/153 to confirm this actual behavior is unexpected and that our workaround is correct.
=> fix(django): patch staticmethods in views

docker-compose.yml
Running `scripts/ddtest tox -e docs` locally fails due to read only access to mounted volume.
=> fix: local docs

scripts/build-dist
uuidgen is not available on the CI image, use (g)mktemp instead.
=> ci: replace uuidgen by mktemp

ddtrace/bootstrap/sitecustomize.py, ddtrace/monkey.py, ddtrace/settings/config.py, tests/unit/test_settings.py
This PR pulls out the logs injection setting stuff introduced coincidentally with #1211 and adds a simple test case.
=> core: Add logs injection setting to Config

ddtrace/contrib/tornado/__init__.py, ddtrace/contrib/tornado/application.py
allow user to set tornado's trace app name via the `DATADOG_SERVICE_NAME` environment variable. flask integration supports this behavior, doc language has been copied from flask to tornado.
this is a huge help so that a simple tornado integration doesn't require any changes to the tornado application setup.
=> Use DATADOG_SERVICE_NAME as default tornado name

.circleci/config.yml
- Use more recent `ubuntu-1604:201903-01` machine image
- Use Python 3.6.5 already installed with `pyenv` on image
- `BOTO_CONFIG` to avoid using `/etc/boto.cfg` on image
=> fix(ci): use machine executor for deploy jobs

ddtrace/contrib/botocore/patch.py
ran into an issue with the botocore patching due to a missing `RetryAttempts` key in the aws response metadata.
will be running this through some tests tomorrow but since it's a sensible change thought i'd put it up as a PR now.
also seems like guarding against unset metadata was already thumbs up'd in the original PR, just missed these two - https://github.com/DataDog/dd-trace-py/pull/1248#discussion_r389036357.
can update here once we've run this on our end!
=> guard against missing botocore response metadata

.circleci/config.yml
We don't use Docker so a simple Python image should be fine.
Partial revert of 5e8b3c419994c183677073d1075f2966b25684b1
=> fix(ci): do not use the machine executor for deploy_docs

ddtrace/contrib/aiobotocore/patch.py, tox.ini
Fixes #1247 
https://github.com/aio-libs/aiobotocore/pull/744 moved `ClientResponseContentProxy` from `aiobotocore.endpoint` to `aiobotocore._endpoint_helpers`
=> fix(aiobotocore): add support for aiobotocore>=0.11.0

.circleci/config.yml, tests/internal/runtime/utils.py, tox.ini
* fix(ci): pin pytest to avoid test failures
* chore: fix new flake8 warning about id
* fix(ci): pin readme_renderer since 25.0 dropped py34 support
=> chore(ci): fix flake8 and pin pytest and readme_renderer

.circleci/config.yml, docs/index.rst, pyproject.toml, setup.py, tox.ini
Python 3.4 has reached end of life is not supported anymore.
=> Remove support for Python 3.4

tests/profile/simple_program_fork.py
This test can be false in Python 2.7 (at least) since it's possible that we
catch the profiler background thread using a lock — the Python 2 threading
module uses one.
Only do a check based on the lock name, that ought to be enough.
=> fix(tests,profile): do not test the number of locking events

ddtrace/commands/ddtrace_run.py, ddtrace/constants.py, ddtrace/contrib/bottle/patch.py, ddtrace/contrib/celery/constants.py, ddtrace/contrib/django/patch.py, ddtrace/contrib/falcon/patch.py, ddtrace/contrib/flask/__init__.py, ddtrace/contrib/flask/patch.py, ddtrace/contrib/grpc/patch.py, ddtrace/contrib/pylons/patch.py, ddtrace/contrib/pyramid/patch.py, ddtrace/contrib/tornado/__init__.py, ddtrace/contrib/tornado/application.py, ddtrace/settings/config.py, ddtrace/span.py, ddtrace/tracer.py, ddtrace/utils/deprecation.py, docs/advanced_usage.rst, tests/base/__init__.py, tests/commands/ddtrace_run_service.py, tests/commands/test_runner.py, tests/subprocesstest.py, tests/test_tracer.py, tests/unit/test_settings.py
This PR introduces support for `DD_SERVICE` environment variable and `ddtrace.config.server`. It also adds support for OpenCensus service name configuration via `span.set_tag('service.name', 'mysvc')`.
Tests are added to confirm precedence in service name configuration.
`{DD,DATADOG}_SERVICE_NAME` support is left in-place for the integrations that used it (django, flask, falcon, tornado, celery, pylons, pyramid, grpc). A helper deprecation function `get_service_legacy` is added to deal with deprecating the old variables.
In order to create robust tests for environment configuration, an addition was added to `run_in_subprocess` to support passing custom environment variables to the subprocess.
=> core: Add support for DD_SERVICE

.circleci/config.yml, scripts/build-dist
Testing scripts/build-dist should make sure we don't break it when it's running
on post-commit.
=> fix: do not build wheels on Python 3.4 + run test buildin wheels in the CI

ddtrace/profile/profiler.py, tests/profile/test_accuracy.py
If no exporters are configured, there is no need to create any scheduler to
export data.
This allows to keep the event in memory without having the scheduler resetting
the recorder every N seconds.
This adds a pretty simple accuracy test for the stack collector. It checks that
the wall and CPU time metering is actually correct.
=> Check profiler accuracy

ddtrace/contrib/django/__init__.py
Fixed a couple of typos in the “Migration from ddtrace<=0.33.0” section
=> Fixed typos in ddtrace.contrib.django docs

tests/profile/collector/test_stack.py
The number frames can actually be 1. In rare circumstances, the first event we
get can be e.g. catching the bootstrap of a thread which is only a frame like:
[('/root/.pyenv/versions/2.7.17/lib/python2.7/threading.py', 774, '__bootstrap')]
In that case, the test was a little bit too strict.
=> fix(tests,profiling): correct number of frames handling

tests/opentracer/test_tracer.py
Fixes a [flaky test](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/418/workflows/4fb0f2f2-2699-41e6-8dba-0fe2480f3411/jobs/215297) that has been bugging us for a while :smile:
=> fix(tests, opentracer): opentracing threading test

ddtrace/contrib/grpc/patch.py, tests/base/__init__.py, tests/contrib/aiopg/test.py, tests/contrib/cassandra/test.py, tests/contrib/elasticsearch/test.py, tests/contrib/grpc/test_grpc.py, tests/contrib/mongoengine/test.py, tests/contrib/mysql/test_mysql.py, tests/contrib/mysqldb/test_mysql.py, tests/contrib/psycopg/test_psycopg.py, tests/contrib/pylibmc/test.py, tests/contrib/pymemcache/test_client.py, tests/contrib/pymongo/test.py, tests/contrib/redis/test.py, tests/contrib/rediscluster/test.py, tests/contrib/sqlite3/test_sqlite3.py, tests/contrib/vertica/test_vertica.py, tests/subprocesstest.py, tests/test_tracer.py
This PR is part 1 of 2 where we confirm the behaviour of service names: we want only non-external integrations to use `DD_SERVICE` (or `config.service`).
The second PR will add assertions that non-external integrations all use DD_SERVICE if it is specified by the user.
=> Ensure DD_SERVICE is not used for external integrations

ddtrace/contrib/aiobotocore/patch.py, tests/contrib/aiobotocore/test.py
The service precedence for `aiobotocore` is now: `DD_SERVICE`/`config.service` with a fallback to the original service name logic (`"aws.{endpoint}"`).
I also black'd the tests for aiobotocore.
=> aiobotocore: prioritize DD_SERVICE

ddtrace/contrib/aiohttp/middlewares.py, ddtrace/contrib/aiohttp/patch.py, tests/contrib/aiohttp/test_middleware.py, tests/contrib/aiohttp/test_request.py, tests/contrib/aiohttp/test_request_safety.py, tests/contrib/aiohttp/test_templates.py, tests/contrib/aiohttp/utils.py
The service precedence for `aiohttp` is now: `DD_SERVICE`/`config.service` with a fallback to the original service (`"aiohttp-web"`).
I also black'd the tests for aiohttp.
=> aiohttp: prioritize DD_SERVICE

ddtrace/contrib/algoliasearch/patch.py, tests/contrib/algoliasearch/test.py
The service precedence for `algoliasearch` is now: `DD_SERVICE`/`config.service` with a fallback to the original service name logic (`"algoliasearch"`).
I also black'd the tests.
=> algoliasearch: prioritize DD_SERVICE

ddtrace/profiling/collector/threading.py, tests/profiling/collector/test_threading.py
Storing the wrapped locked using wrapt in a class attribute would trigger the
descriptor protocol and fail with an error:
AttributeError: 'builtin_function_or_method' object has no attribute '__get__'
This overrides the standard wrapt wrapper to handle this special case.
=> fix(profiling): fix Lock issue when stored in a class attribute

ddtrace/contrib/grpc/client_interceptor.py, ddtrace/contrib/httplib/patch.py, tests/base/__init__.py, tests/contrib/grpc/test_grpc.py, tests/contrib/httplib/test_httplib.py, tests/utils/__init__.py
For some of our integrations, which represent external service calls, applying the `_dd.measured` tag does not make sense by default. This PR removes those instances.
=> Update _dd.measured support

ddtrace/__init__.py, ddtrace/tracer.py, tests/test_tracer.py
This deprecates and remove the code of the global excepthook.
We don't expect anyone to use it as it was never enabled by default.
Let's keep the API just in case anyhow — it just default to noop.
=> feat(tracer): deprecate global excepthook

ddtrace/commands/ddtrace_run.py, ddtrace/contrib/aiobotocore/patch.py, ddtrace/contrib/aiohttp/middlewares.py, ddtrace/contrib/aiohttp/patch.py, ddtrace/contrib/algoliasearch/patch.py, ddtrace/contrib/bottle/patch.py, ddtrace/contrib/bottle/trace.py, ddtrace/contrib/celery/constants.py, ddtrace/contrib/django/patch.py, ddtrace/contrib/falcon/patch.py, ddtrace/contrib/flask/patch.py, ddtrace/contrib/flask_cache/tracers.py, ddtrace/contrib/grpc/patch.py, ddtrace/contrib/kombu/patch.py, ddtrace/contrib/mako/patch.py, ddtrace/contrib/molten/patch.py, ddtrace/contrib/pylons/patch.py, ddtrace/contrib/pyramid/patch.py, ddtrace/contrib/requests/patch.py, ddtrace/contrib/tornado/application.py, ddtrace/settings/config.py, ddtrace/utils/deprecation.py, tests/contrib/bottle/test.py, tests/contrib/flask_cache/test.py, tests/contrib/jinja2/test_jinja2.py, tests/contrib/kombu/test.py, tests/contrib/mako/test_mako.py, tests/contrib/molten/test_molten.py, tests/contrib/requests/test_requests.py, tests/test_tracer.py
This PR makes the following changes:
1. When `DD_SERVICE`/`config.service` is provided it is the default service name used by non-external-calling integrations. The expected behaviour when not using `DD_SERVICE`/`config.service` should remain as before.
2. Integrations that never used `{DD,DATADOG}_SERVICE_NAME` should use `config.service` instead of `config.get_service` since using the latter would introduce new functionality for integrations to use the old `{DD,DATADOG}_SERVICE_NAME`.
3. `config.get_service` refactored to `config._get_service`. This should be a private api used only in integrations which use `{DD,DATADOG}_SERVICE_NAME` in order to deprecate the usage.
=> integrations: DD_SERVICE

tox.ini
The `grpc` CI job is especially long running. This PR addresses this by only testing versions of the `grpcio` package available as `bdist_wheels`. 
Most importantly, we avoid testing versions that lack wheels for Python 3.8:
```
$ curl https://pypi.org/pypi/grpcio/json | jq ".releases[][] | select(.packagetype == \"bdist_wheel\" and .python_version == \"cp38\") | .filename | sub(\"grpcio-(?<version>.*)-cp38-cp38.*\"; \"\(.version)\")" | uniq
"1.24.3"
"1.25.0"
"1.25.0rc1"
"1.26.0"
"1.26.0rc1"
"1.27.0rc1"
"1.27.0rc2"
"1.27.1"
"1.27.2"
"1.28.0.dev0"
"1.28.0rc1"
"1.28.0rc2"
"1.28.0rc3"
```
=> chore(ci): test only with grpcio wheels

ddtrace/profiling/exporter/__init__.py, ddtrace/profiling/exporter/file.py, ddtrace/profiling/exporter/http.py, ddtrace/profiling/exporter/pprof.py, ddtrace/profiling/scheduler.py, tests/profiling/exporter/test_file.py, tests/profiling/exporter/test_http.py, tests/profiling/exporter/test_pprof.py
Currently, the Exporters have to guess what the time range is for the provided
events.
This is not optimal in cases where we don't have any events — even if it
_should_ not happen in practice.
By forcing the caller of the exporter to provide the collection time range, we
can generate data that are actually more precise.
=> fix(profiling/pprof): provide timestamp to export()

ddtrace/contrib/logging/patch.py, tests/contrib/logging/test_logging.py
We wants logs into include only the globally configured values for `env`, `service` and `version`.
=> logging: only use global setting for env, service and version

ddtrace/commands/ddtrace_run.py, docs/advanced_usage.rst, docs/configuration.rst
This PR consolidates where we specify environment variables for `ddtrace-run` and updates documentation for deprecated environment variables.
=> chore(docs): consolidate environment variable configuration

ddtrace/profiling/_periodic.py
On interpreter shutdown, we can see this kind of errors:
File "ddtrace/profiling/_periodic.py", line 104, in run
del threading._active[self._tident]
TypeError: 'NoneType' object does not support item deletion
This changes the code to use the same try/except mechanism in the above block
to avoid logging those errors on shutdown.
=> fix(profiling): ignore failure on shutdown

tox.ini
[aiobotocore went 1.0](https://github.com/aio-libs/aiobotocore/releases/tag/1.0.0) with some breaking changes. We don't yet support this functionality (or at least our tests don't). Pin it for now.
=> aiobotocore: pin to <1.0

ddtrace/contrib/sqlalchemy/engine.py
Resolves issue #841 (SQLAlchemy: ConnectionEvents.dbapi_error() event is deprecated)
**Background**
The `ddtrace` library's sqlalchemy engine currently listens for the `dbapi_error` event. This throws a deprecation warning within sqlalchemy, as mentioned in the above issue.
**Solution**
This PR changes the name of the event being listened for from `dbapi_error` to `handle_error`.
Reference to the new `handle_error` event within SQLAlchemy: https://docs.sqlalchemy.org/en/13/core/events.html#sqlalchemy.events.ConnectionEvents.handle_error
=> Update error event handler name within SQLAlchemy engine

ddtrace/profiling/exporter/http.py, tests/profiling/exporter/test_http.py
Using default=os.getenv in attr attributes will make the default unchangeable
after the library is loaded.
Most options already leverage ddtrace.profiling._attr.from_env to avoid
this, but not the HTTP exporter.
=> fix(profiling): allow to override options after load

ddtrace/profiling/__init__.py
If an incompatible ABI is detected, users are usually lost and don't know what
to do.
Indicate the command to use to install and compile this module.
=> feat(profiling): add the pip install when recompilation is needed

ddtrace/tracer.py, tests/test_tracer.py
This PR introduces support for continuing a trace from a parent process into a forked process.
I had thought that we already supported this. We do currently (as of before this PR) handle forked processes as we recreate the writer thread. However, as demonstrated in #1184, when a parent trace is started the child process never sends spans. Note that tracing still worked if there was no parent span at the time of fork.
The reason why we didn't support tracing _across_ processes is that the `Context` object that is copied, by means of `fork`, into the child process, containing the trace so far. The child process will never finish the copied spans in the trace which are sitting in its context. This causes the context to never be recorded because of [this …
=> tracer: support tracing across `fork()`

ddtrace/constants.py, ddtrace/context.py, ddtrace/contrib/logging/patch.py, ddtrace/internal/logger.py, tests/contrib/logging/test_logging.py
resolves #1337. could also avoid adding the extra attribute to the record and say `if record.name.startswith("ddtrace")` in `_w_makeRecord` but that could miss some cases and hit a lot of false positives.
if folks are 👍 on this approach i can make `__from_DDLogger` a constant, look at tests, etc. haven't checked performance impact and am guessing there may be an easier way to do this
=> fix: avoid context deadlock with logs injection enabled

ddtrace/profiling/collector/memory.py, ddtrace/profiling/collector/stack.pyx
Using the `bool` primitive will only work with 0 or 1, whereas we want to
support true/false strings.
=> fix(profiling): use formats.asbool to convert bool from env

ddtrace/span.py, tests/test_span.py
As I found out the hard way: setting a non-string key tag (eg: `span.set_tag(1, "value")`) will result in the span being dropped at the agent:
```bash
2020-04-07 21:26:21 UTC | TRACE | ERROR | (pkg/trace/api/api.go:379 in handleTraces) | Cannot decode v0.4 traces payload: msgp: attempted to decode type "int" with method for "str"
```
This PR adds the functionality of logging a warning and aborting the operation when this occurs.
=> span: handle non-string tag keys

ddtrace/profiling/_periodic.py, ddtrace/profiling/_service.py, ddtrace/profiling/collector/__init__.py, ddtrace/profiling/collector/memory.py, ddtrace/profiling/collector/stack.pyx, ddtrace/profiling/profiler.py, ddtrace/profiling/scheduler.py, tests/profiling/collector/test_collector.py, tests/profiling/collector/test_memory.py, tests/profiling/collector/test_service.py, tests/profiling/collector/test_stack.py, tests/profiling/collector/test_threading.py, tests/profiling/compat_program.py, tests/profiling/simple_program.py, tests/profiling/test_accuracy.py, tests/profiling/test_periodic.py, tests/profiling/test_scheduler.py
This should make the Profiler slightly faster to stop.
This introduces a new class Service that describes a Service that can be
started, stopped and joined.
The Service tracks its own status in order to avoid starting twice the same
service.
The collectors are now inheriting from this common class as they all provide a
startable/stoppable service.
This changes the Scheduler class to leverage the PeriodicService class.
It also makes sure the Scheduler always flush on exit.
The Profiler is now responsible for joining or not the Scheduler if it wants to
block on the last upload before returning from its `stop` method.
=> Allow Profiler to finish upload data in the background when stopped

ddtrace/tracer.py, tests/test_tracer.py
~Creating this as a draft for now as I'm not yet 100% of the implications this might have.~ It seems like (thankfully) we don't reuse or copy writers anywhere so I think this change isn't breaking.
I think this might be part (and only part) of the reason for cases like #1155. For this to be a solution for #1155 would mean that somehow the abandoned writer thread was somehow still having traces sent to it.
=> tracer: stop previous writer if a new one is created

docs/configuration.rst
This updates the configuration docs, calling out that the DD_SERVICE, DD_ENV, and DD_VERSION env vars were added in v0.36.0
I spent more time than I'd care to say debugging why traces weren't falling into the correct environment in the UI, only later to realize I was using v0.33.0 and while I added the new env vars, that version wasn't using them.
My goal in calling out when these env vars were added to ddtrace is to remind those using the library to check their versions and not waste time like I did.
=> Updates configuration docs

ddtrace/contrib/django/__init__.py, ddtrace/contrib/django/patch.py, tests/contrib/django/django_app/urls.py, tests/contrib/django/test_django.py
The default behaviour of the Django contrib package is to add a `django.user.name` tag with the username to the root span of the Django request.
This is a concern as the user's name is personally identifiable data and should not be leaving the system.
This PR adds a `user_name_enabled` config to the Django contrib package which defaults to `True`, but when set to `False` would mean that the Django user's username is omitted from the root request span tags.
=> Add config to omit `django.user.name` tag from request root span

tests/profiling/test_periodic.py
This test would fail occasionally if a thread from another test is still
running, depending on the order the tests are run.
This replaces check with a more accurate one.
=> test(profiling): check for thread presence rather than number of threads

.circleci/config.yml, docs/installation_quickstart.rst, setup.py
If no C compiler is available, the installation do not fail and only a warning
is being print. This is wrong as the profiler won't work — at all.
Since we need a C compiler to build the profiler extensions that are part of
the wheel anyway,  let's not make wrapt or psutil optional.
Fixes #1328
=> fix: make C extensions mandatory

ddtrace/internal/writer.py, tests/test_tracer.py
This PR adds the ability to configure the maximum number of traces the writer can hold via an  environment variable `DD_TRACE_MAX_TRACES`.
Instead of trying to design and support a new public API around setting the queue max size as discussed in #1363 we'd rather provide a quick and dirty solution to allow users to set their own max traces limit.
This will be succeeded by either a public API if our current system is deemed adequate; or by changes we make to the underlying queuing and writing system we have.
=> writer: allow configuration of queue maxsize via env var

ddtrace/tracer.py, tests/contrib/asyncio/test_tracer.py
That does not seem to be really useful.
=> refactor(tracer): remove @property for Tracer.context_provider

ddtrace/profiling/exporter/http.py, tests/profiling/exporter/test_http.py
The timeout defined in the HTTP exporter was never used and system default was
used instead.
=> fix(profiling): use timeout attribute

ddtrace/contrib/celery/signals.py, docs/advanced_usage.rst, tests/contrib/celery/test_integration.py
This PR addresses [Open Issue 1217](https://github.com/DataDog/dd-trace-py/issues/1217), by adding app analytics support for celery worker and producer spans. Previously it was not possible to enable spans created by Celery instrumentation as analyzed spans for use in app analytics. The only workaround was relying on the [datadog-agent configuration setting](https://docs.datadoghq.com/tracing/guide/app_analytics_agent_configuration/?tab=agent630#pagetitle) which is brittle and decoupled from application settings, making it difficult to maintain. This PR exposes an environment variable `DD_CELERY_ANALYTICS_ENABLED` at the application level to enable analyzed spans for celery.
```
DD_CELERY_ANALYTICS_ENABLED=true ddtrace-run python app.py
```
- long time listener first time caller. Tried to …
=> Add analyzed span configuration option for Celery

ddtrace/settings/integration.py, tests/unit/test_settings.py
`IntegrationConfig` has a broken implementation of `deepcopy` and a non-existent/broken implementation for `copy` since it falls back to using `dict.copy`.
This PR fixes the bug in the `deepcopy` implementation and adds an implementation for `copy` as well as some basic tests.
=> fix(integration config): copy and deepcopy implementations

.circleci/config.yml, ddtrace/profiling/collector/stack.pyx, docs/installation_quickstart.rst
This hides the pthread_t type usage and force the cast to unsigned long thread
no matter what.
This is fine with glibc and musl libc at least.
Fixes #1388
=> fix(profiling): allow to build on Alpine Linux

ddtrace/profiling/scheduler.py
The current Scheduler always sleeps `interval` (default 60s) between two
exports.
If the export takes more than 0s (hehe), then the exporter might end up
exporting more than one minute of data during the next flush.
This makes sure we compensate the sleeping interval for that and makes sure the
profiler do export one minute of data every minute.
=> fix(profiling): correct the scheduler sleep time based on exporter time

ddtrace/contrib/django/__init__.py, ddtrace/contrib/django/patch.py
Resolves #1349
With middleware enabled (default behavior):
With middleware disabled (`DD_DJANGO_INSTRUMENT_MIDDLEWARE=false`):
=> feat(django): add config for instrumenting middleware

ddtrace/settings/hooks.py, ddtrace/settings/integration.py
There's a potential bug here as the `memodict` is not passed to call from the
__deepcopy__ special method. That means the module might copy too much data,
especially data that can be shared.
=> fix(settings): pass the `memodict` argument to subcall to deepcopy

ddtrace/internal/runtime/__init__.py, ddtrace/profiling/exporter/http.py, ddtrace/tracer.py, tests/contrib/flask/test_flask_helpers.py, tests/contrib/flask/test_signals.py, tests/contrib/flask/test_template.py, tests/internal/runtime/test_runtime_id.py, tests/test_integration.py, tests/test_tracer.py
This adds support for a runtime id, a unique identifier that can identifies a
running process during his lifecycle.
This actually fixes the collision that occurred when a process was forking and
its runtime id was the same.
This adds a tag named `runtime-id` to the root span that matches the generated
runtime id.
As profiles are also tagged with that same runtime-id, it makes it easy to link
traces and profiles.
=> Add runtime id tag support for traces & profiles

ddtrace/monkey.py, pyproject.toml
This PR adds the path and module to exceptions generated when errors occur with those values. Before, a generic message was raised which was not at all useful for debugging.
Also formats monkey.py.
These changes are split into two separate commits for ease in reviewing 🙂
=> monkey: add better error messages

ddtrace/_hooks.py, ddtrace/contrib/falcon/middleware.py, ddtrace/settings/__init__.py, ddtrace/settings/integration.py, pyproject.toml, tests/test_global_config.py, tests/test_hooks.py
This move the hooks class away of settings so it can be used by non-settings
code without import statement looking weird.
It also hides the module as being private.
The only user of this API seems to always send a span and nothing breaks while
removing this check.
That makes sure we are able to deregister a hook for a particular event.
=> Make hooks settings generic

tox.ini
should be the last one until we fix the libraries for which we don't support the latest versions 😄
=> bottle: update tests to latest

ddtrace/_hooks.py
Using debug makes it impossible for a user of this hook to get feedback on a
possible failure.
=> fix(hooks): use log.error to log hook exceptions

ddtrace/internal/writer.py
fix: raise RuntimeError("threads can only be started once").
This occurs due to a race condition on `AgentWriter._started` when multiple threads start simultaneously and a writer has not yet been created.
=> fix: raise RuntimeError("threads can only be started once")

ddtrace/profiling/collector/stack.pyx, ddtrace/profiling/profiler.py, ddtrace/settings/__init__.py, ddtrace/settings/config.py, ddtrace/settings/exceptions.py, ddtrace/settings/http.py, ddtrace/settings/integration.py, ddtrace/tracer.py, pyproject.toml, tests/profiling/collector/test_stack.py, tests/test_tracer.py
This allows to register a function to be called when a new span is being
started by a Tracer.
=> Store span ids in profiling events

ddtrace/api.py
Essentially the issue is that we don't accept logs bigger than 256kb: "Any log exceeding 256KB is accepted and truncated by server" and when we log that a trace payload is too large, we print the whole trace, causing a log larger than the acceptable size: https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/api.py#L229
This causes many error level logs to be generated
Which is causing the customer's monitor for error level logs on this application to alert.
=> internal: Change trace too large message to debug

ddtrace/internal/writer.py
Clarify the logic on when we drop a trace.
Note: This should effectively not be changing anything, but will clarify the legibility of the code.
=> internal: Ensure queue is at or over max size before dropping

ddtrace/opentracer/tracer.py, tests/opentracer/test_tracer.py
This PR implements `active_span` on the opentracing tracer. This now will allow opentracing library users to obtain the active span when using datadog instrumentation.
Should fix #1153.
=> feat(opentracer): implement active_span

ddtrace/profiling/_periodic.py
This does not change the functionality but should be slightly cleaner.
=> fix(profiling): use gevent.monkey rather than private _threading module

ddtrace/profiling/_periodic.py, ddtrace/profiling/collector/stack.pyx, ddtrace/profiling/exporter/pprof.py, tests/profiling/exporter/test-pprof-exporter.txt, tests/profiling/exporter/test-pprof-exporter_tracemalloc+stack-exceptions.txt, tests/profiling/exporter/test-pprof-exporter_tracemalloc.txt, tests/profiling/exporter/test_pprof.py, tests/profiling/test_periodic.py
Python ≥ 3.8 supports native OS thread id. Assign it to gevent custom thread
too.
The current code uses the pthread_t id to cache CPU time between two polling.
This is very optimistic as the pthread_t id can be reused, and it seems Linux
does that quite often. When a program is heavily loaded, it will reuse the
pthread_t faster than the stack profiler can notice, meaning that the CPU time
might end up being negative:
1. cached previous thread with same pthread_t id cpu time = 1000
2. new thread with same pthread_t id cpu time = 500
3. cpu time = 500 - 1000 = -500 🤦
To fix that, we now also uses the native thread id to identify thread. This
should be unique and the couple (pthread_t, native id) has a really small
chance of collision only using hash instead of native id (for old Python …
=> fix(profiling): fix negative CPU time

tox.ini
We can at least run with 1.1.0 on Python 2.7.
=> ci: make sure we test a low enough gevent version

ddtrace/profiling/collector/stack.pyx, tests/profiling/collector/test_stack.py
When gevent is running and monkey-patches the threading module, the stack
collector struggles to identify the MainThread. This is due to gevent replacing
the native thread with greenlet based ones.
This patch leverages the original threading.get_ident() function to store the
main thread id and stores it for future reference, even if the application has
been monkey-patched.
=> fix(profiling): identify Python main thread properly with gevent

ddtrace/ext/aws.py, ddtrace/utils/formats.py, pyproject.toml, tests/test_utils.py, tests/unit/test_ext.py
This function is only used there so there's no need to carry it around.
Also make it private since it shouldn't be part of the exposed API.
Finally, this black some more files that are touched by this patch.
=> refactor: move flatten_dict to ext.aws

ddtrace/profiling/exporter/http.py, tests/profiling/exporter/test_http.py
Rather than emitting on each upload try at runtime, directly raise an error on
exporter creation.
=> feat(profiling): raise an error on start if endpoint is empty

ddtrace/profiling/__init__.py, docs/installation_quickstart.rst, setup.py
We want users to be able to deploy and start profiling their applications right
away with this Python package, without having to pick a flavor.
=> feat(profiling): install the profiling extra by default

ddtrace/span.py
The newly introduced span/trace id generation did not take into consideration forking processes. For which, the seed would be shared among the processes and would result in id collisions for spans and traces.
=> revert span/trace id generation

ddtrace/profiling/exporter/http.py, ddtrace/profiling/profiler.py, tests/profiling/exporter/test_http.py, tests/profiling/test_profiler.py
This allows to pass the env to the Profiler object when uploading profiles.
=> feat(profiling): allow to pass env to Profiler

tests/test_api.py
There's a race between starting a UDS server and using it: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/1257/workflows/23c32c73-3dfb-48f9-832c-0f6db3e728b7/jobs/261005
This PR adds a delay to work around this. A better solution would be to synchronize the threads but would be a quite a bit more involved.
Fixes #1215
=> tests: wait for uds server to start before using it

ddtrace/profiling/collector/stack.pyx, ddtrace/profiling/profiler.py, tests/profiling/test_profiler.py
This disables the tracer usage by default in the profiler.
=> feat(profiling): disable trace tracking in tracer by default

tox.ini
Once in a while, a test hangs in the CI and it's impossible to see which one
and why. This should gives more insight about what's happening.
=> test(profiling): enable verbose + no capture

tests/profiling/test_accuracy.py
CircleCI sometimes goes up to 2.5% non-accuracy which breaks the test.
=> test(profiling): increase error tolerance

ddtrace/profiling/_periodic.py, tests/profiling/test_periodic.py
A seemingly [flaky test](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/1092/workflows/116cd465-3bd5-42fa-b277-632322e333c8/jobs/251605/steps) brought to my attention a race condition in `PeriodicThread` (described below).
~It also seems that `PERIODIC_THREAD_IDS` should be protected by a mutex since there could be multiple periodic threads (at least 1 in the profiler and 1 in the tracer). So I added a lock around the set. Although it'd be extremely rare for a collision to occur given our usage of `PeriodicThread`.~
=> fix(profiling/periodic): PERIODIC_THREAD_IDS race condition

ddtrace/profiling/profiler.py, ddtrace/profiling/recorder.py, docs/configuration.rst, tests/profiling/collector/test_memory.py, tests/profiling/collector/test_stack.py, tests/profiling/collector/test_threading.py, tests/profiling/test_recorder.py
This introduces a per-event-type maximum number of event limit.
So far, the event was global per event type. However, not all event type are
equal and some are bigger than others.
This reduces the default maximum number of events for an event type to 32768
and remove it as a publicly documented interface via the environment variable.
It sets default value for MemorySampleEvent which can be quite big, and
slightly increase the number of StackBasedEvent that can be stored by default
(from 49152 to 60000).
Related to #1481
=> refactor(profiling): enhance event type limit

ddtrace/contrib/django/patch.py, tests/contrib/django/django1_app/urls.py, tests/contrib/django/django_app/urls.py, tests/contrib/django/templates/basic.html, tests/contrib/django/test_django.py, tests/contrib/django/views.py
This is just #1441 brought up to date with master since it had some conflicts and we didn't have permissions to update the remote branch. Thanks @sibsibsib for the contribution!
closes #1441.
=> fix(django): handle all template name types

tests/profiling/collector/test_stack.py
The main thread is not always the first and only thread.
=> test(profiling): fix test_truncate random failure

tests/profiling/collector/test_stack.py
The stress test run the collect function while the collector thread is running;
however, the collector is not thread-safe itself and not designed to be run on
2 threads at the same time, triggering race conditions. For example:
ddtrace/profiling/collector/stack.pyx:480: in ddtrace.profiling.collector.stack.StackCollector.collect
all_events = stack_collect(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
>   cpu_time_ns=cpu_time[tid],
E   KeyError: 140707993589504
=> test(profiling): fix stress test

tox.ini
This should make it easier to understand why the CI is slow as we'll be able to
identify the slowest tests — and then improve some tests to make them faster.
=> test: show 10 slowest tests

.circleci/config.yml, Dockerfile
It is automatically pulled by CircleCI job.
=> ci: do not install tox in the base image

.circleci/config.yml
This makes the CI use this CI image which is automatically built by Docker Hub.
=> ci: switch to this own repo Docker image

Dockerfile
The current pyenv global sets Python 2.7, and the rest of the command line is
ignored since it does not make any sense to have several Python as globals.
=> ci: use Python 3.8 by default

Dockerfile
This reverts commit 94e6a849ff14a03b1227b2d9e9f629c429afee57.
=> ci: fix available Python versions

ddtrace/profiling/exporter/http.py, ddtrace/profiling/profiler.py, tests/profiling/exporter/test_http.py, tests/profiling/test_accuracy.py, tests/profiling/test_profiler.py
The upcoming Datadog agent release will support uploading profiles. This
enables its usage by default when configuration the profiler with no DD_API_KEY
set in the env.
=> feat(profiling): enable agent upload by default

tox.ini
There is a typo in the psycopg env name which makes it use the default Python
version rather than Python 3.7.
=> ci: fix psycopg on Python 3.7

ddtrace/contrib/redis/__init__.py, ddtrace/contrib/redis/patch.py, ddtrace/contrib/redis/tracers.py, ddtrace/contrib/redis/util.py, ddtrace/ext/redis.py, ddtrace/utils/__init__.py, pyproject.toml, tests/commands/ddtrace_run_integration.py, tests/contrib/redis/test.py
This patch adds global configuration functionality for setting the service in the redis integration.
A helper `utils.external_service` is added to be used in all external integrations to aid in setting the service name
=> feat(redis): add global service configuration

ddtrace/contrib/redis/patch.py, ddtrace/pin.py, ddtrace/utils/__init__.py
The Pin is no longer the primary source of configuring the service name. As
such, it doesn't make sense to enforce that the service name be required since
it may be provided by a global configuration option instead.
=> pin: make service optional

ddtrace/profiling/exporter/http.py, ddtrace/profiling/profiler.py, tests/profiling/exporter/test_http.py, tests/profiling/test_accuracy.py, tests/profiling/test_profiler.py
The upcoming Datadog agent release will support uploading profiles. This
enables its usage by default when configuration the profiler with no DD_API_KEY
set in the env.
=> feat(profiling): enable agent upload by default (#1494)

ddtrace/profiling/profiler.py
It's very unlikely anybody wants to provide their scheduler list, so hide it
from the API so it appears a little bit simpler.
=> refactor(profiling): hide Profiler._schedulers

.circleci/config.yml
Do not install virtualenv, we don't use it (directly).
=> ci: fix install -U for tox

ddtrace/profiling/collector/stack.pyx, tests/profiling/collector/test_stack.py
This is a follow-up to 5cff1aad64ed31e950f045c1e695a1e8339a0091 which did not
fix all the tests.
=> test(profiling): fix stress tests

ddtrace/profiling/collector/stack.pyx, setup.py
This feature relies on POSIX features, it won't work on Windows.
Fixes #1487
=> fix(profiling): disable exception profiling on Windows

.circleci/config.yml, .circleci/scripts/test_build.sh
Adds CircleCI jobs to tests Windows builds for Python 3.5, 3.6, 3.7, and 3.8. Python 2.7 has not been added since it's not published on nuget, which we are using for installing versions under Windows. The test build commands that had been defined in the CircleCi config are now pulled out into a separate script and used across Linux and Windows jobs.
=> ci: Add tests for Windows builds

ddtrace/api.py, tests/test_integration.py
This fixes the lack of a log warning for sending a single trace to the agent that is larger than the max payload size. At the moment there is a log warning when a trace is larger than the max payload size is sent but only when alongside other traces.
=> fix: log warnings for full payload

ddtrace/profiling/exporter/http.py, tests/profiling/exporter/test_http.py
This is an alternative to #1459
Fixes #1452
=> feat(profiling/http): emit log message when server returns 400

.gitignore, ddtrace/internal/_queue.pyx, ddtrace/internal/writer.py, setup.py, tests/benchmark.py, tests/internal/test_writer.py, tests/test_queue.py, tests/test_tracer.py
The queue implementation subclassed the stdlib Queue while using none of its
features besides the built-in lock. The notifying capabilities are not used.
It was also noticed that the queue put operation was strangely more expensive
than simply adding an item to a mutex protected list, possibly due to the
additional notifying capabilities which there is no need of.
[In microbenchmarks](https://gist.github.com/Kyle-Verhoog/376d399f5217664ebb0fb561040676a9):
- **1.1-1.3x** speed-up in **trace creation** (creating, finishing and adding spans to the queue)
- **4-6x** speed-up in primitive operation usage over the previous queue
=> core: rewrite queue

ddtrace/bootstrap/sitecustomize.py, docs/configuration.rst, pyproject.toml, tests/commands/ddtrace_minimal.py, tests/commands/ddtrace_run_app_name.py, tests/commands/ddtrace_run_argv.py, tests/commands/ddtrace_run_debug.py, tests/commands/ddtrace_run_disabled.py, tests/commands/ddtrace_run_dogstatsd.py, tests/commands/ddtrace_run_enabled.py, tests/commands/ddtrace_run_env.py, tests/commands/ddtrace_run_global_tags.py, tests/commands/ddtrace_run_hostname.py, tests/commands/ddtrace_run_integration.py, tests/commands/ddtrace_run_logs_injection.py, tests/commands/ddtrace_run_no_debug.py, tests/commands/ddtrace_run_patched_modules.py, tests/commands/ddtrace_run_priority_sampling.py, tests/commands/ddtrace_run_profiling.py, tests/commands/ddtrace_run_sitecustomize.py, tests/commands/test_runner.py
This adds an environment variable DD_PROFILING_ENABLED (default to false). If
set to `true`, this will make the profiler run in the wrapped program.
=> feat(ddtrace-run): allow to enable profiling

ddtrace/profiling/collector/stack.pyx, tests/profiling/collector/test_stack.py
The current C code inside the stack collector function is not going to release
the GIL per itself, however the Python code inside might release the GIL, which
can other threads to finish and a following call to pthread_getcpuclockid() to
crash the program on Linux: calling pthread_*() function on an invalid
thread_id makes the application crash (thank you, glibc).
This patches splits the code and disable thread switching function where we
don't want to switch to another thread by doing only C.
This will also improve the wall time usage measurement for the dynamic
interval; currently if the stack collecting thread is interrupted by another
thread, its wall time will be increased by mistake and its run frequency
subsequently reduced by mistake.
This can still happens, but a little less. If …
=> fix(profiling/stack): fix GIL switching

ddtrace/contrib/grpc/__init__.py, ddtrace/contrib/grpc/client_interceptor.py, ddtrace/contrib/grpc/patch.py, ddtrace/contrib/grpc/server_interceptor.py, ddtrace/utils/__init__.py, docs/advanced_usage.rst, tests/contrib/grpc/test_grpc.py
The service name can be changed post-patch-time. This patch adds the
functionality to look-up the service name dynamically to achieve the correct
service name behaviour.
=> fix(grpc): compute service name dynamically

ddtrace/settings/config.py, ddtrace/tracer.py, tests/contrib/logging/test_logging.py, tests/test_tracer.py
We want to allow `service`, `env` and `version` to be set-able via the `DD_TAGS` environment variable.
=> core: set tags from DD_TAGS

tests/profiling/exporter/test_http.py, tests/profiling/test_compat.py, tests/profiling/test_main.py, tests/profiling/test_profiler.py
This changes a few settings to make sure test run as fast a possible. This
reduces timeout, and disable flush on exit in certain cases to avoid retrying
for several seconds on shutdown if the agent is down.
This brings down the execution time of while test suite from 4 minutes to
1 minute.
=> tests(profiling): optimize test execution for speed

tests/profiling/simple_program_gevent.py, tests/profiling/test_main.py
This rewrite the test to exit faster and cut down the timeout for flushing
profiles.
This brings the speed from 45 to 1.3 second.
=> test(profiling): speed up gevent script test

ddtrace/profiling/_nogevent.py, ddtrace/profiling/_periodic.py, ddtrace/profiling/_service.py, ddtrace/profiling/collector/stack.pyx, ddtrace/profiling/recorder.py, tests/profiling/collector/test_stack.py
This should make it easier to access non-gevent function under gevent.
The lock-free approach does not work as the following scenario might happen:
- Recorder.push_events() is called from a Collector
- The collector gets a reference to the event queue and is interrupted
- The Scheduler calls Recorder.reset() and passes the old events queue to the
Exporter
- The Exporter starts to export and iterate over the list of events
- The Exporter gets interrupted and the Collector resumes
- The Collectors finally pushes its events and go back to sleep
- The Exporter resumes and the iteration breaks because the event queue changed
This can be seen in the wild with the following backtrace:
File "/lib/python2.7/site-packages/ddtrace/profiling/scheduler.py", line 44, …
=> fix(profiling): lock Recorder on reset

ddtrace/profiling/collector/stack.pyx
Cython increases itself the reference to the dict returned by
_PyThread_CurrentFrames whereas there is already one ref being counted.
This makes sure the refcount goes to 0 before the function exit, releasing the
dict.
=> fix(profiling): fix memory leak in Python 2 stack collector

ddtrace/__init__.py, tests/internal/import_hooks/test_integration.py
The import hooks have been causing a few issues. #1553 is one example of which (I'm going to try to dig up other instances but memory serves that it's come up before). We don't use the import hooking mechanism anywhere within the project, we just install the patches which is causing issues.
So the patching can be safely disabled until a find a root cause for #1553 is found and more time is allocated for testing the hooks more thoroughly.
Fixes #1553.
=> core: disable import hooks

tox.ini
Dogpile 1.0 was [released](https://github.com/sqlalchemy/dogpile.cache/releases/tag/rel_1_0_1) which drops support for Python < 3.6. This broke our tests as we were testing with the latest version across all python versions.
=> tests: fix test for dogpile.cache 1.0

ddtrace/bootstrap/sitecustomize.py, ddtrace/contrib/django/__init__.py, ddtrace/contrib/flask/__init__.py, ddtrace/contrib/molten/__init__.py, ddtrace/contrib/pyramid/patch.py, ddtrace/monkey.py, ddtrace/settings/integration.py, ddtrace/tracer.py, docs/advanced_usage.rst, docs/configuration.rst, tests/commands/test_runner.py, tests/integration/test_integration.py, tests/test_monkey.py, tests/test_tracer.py, tests/unit/test_settings.py
Add support for the following variables
- `DD_TRACE_ENABLED`: used to disable the sending of spans to the agent, spans are still produced. The variable was previously used only in `ddtrace-run` where it also disabled patching. This functionality is maintained for backwards compatibility while the new functionality is added to the core library.
- `DD_TRACE_DEBUG`: used to enable debug logging at the DEBUG level. This previously existed only in `ddtrace-run`. The functionality is now included in the core library.
- `DD_TRACE_<INTEGRATION>_ENABLED`: enables and disables integrations from being installed. This overlaps with the existing `DATADOG_PATCH_MODULES`, which will have lower precedence.
- `DD_TRACE_<INTEGRATION>_ANALYTICS_*`: These were previously `DD_<INTEGRATION>_ANALYTICS_*` and …
=> Make environment variables consistent with other languages

ddtrace/profiling/_periodic.py, ddtrace/profiling/collector/stack.pyx, tests/profiling/test_periodic.py
The lock used in the threading is a gevent coroutine-lock which break if locked
from different threads:
File "/root/project/ddtrace/profiling/_periodic.py", line 104, in run
with threading._active_limbo_lock:
File "src/gevent/_semaphore.py", line 191, in gevent._gevent_c_semaphore.Semaphore.__enter__
File "src/gevent/_semaphore.py", line 192, in gevent._gevent_c_semaphore.Semaphore.__enter__
File "src/gevent/_semaphore.py", line 143, in gevent._gevent_c_semaphore.Semaphore.acquire
File "/root/project/.tox/py27-profile-gevent/lib/python2.7/site-packages/gevent/thread.py", line 118, in acquire
acquired = BoundedSemaphore.acquire(self, blocking, timeout)
File "src/gevent/_semaphore.py", line 143, in gevent._gevent_c_semaphore.Semaphore.acquire
File …
=> fix(profiling,gevent): fix race condition with periodic thread

ddtrace/profiling/collector/stack.pyx, tests/profiling/exporter/test_pprof.py, tox.ini
https://github.com/python/cpython/pull/16347 made the symbols hidden so we
can't use private functions anymore.
=> ci: test profiler on Python 3.9

ddtrace/contrib/grpc/patch.py
It is currently impossible to set Pin on multiple grpc channels. The grpc implementation creates a pin on the `grpc.Channel` class. However a `shallow clone` does not take place when using Pin.get_from(class), a shallow clone will take place for the Pin when using Pin.get_from(instance.)
https://github.com/DataDog/dd-trace-py/blob/e9d0ab3f6a24d034b327363919fb28998192146d/ddtrace/pin.py#L100-L102
Fixes #1576.
=> Fix: GRPC Channel Pin

ddtrace/profiling/collector/__init__.py, docs/configuration.rst, tests/profiling/collector/test_memory.py, tests/profiling/collector/test_threading.py
This should lower the default amount of memory overhead for the memory
tracer.
=> feat(profiling): reduce the default amount of sampling for memory/lock to 2%

tox.ini
This appears to be the cause for the recent flakiness in CI (no idea why):
- https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/1986/workflows/b397a441-bf0f-42b1-9f28-0b863fdc15ef/jobs/298112
- https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/1989/workflows/df14ba71-ed2a-452b-9fe6-99d84c011450/jobs/298278
- https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/1958/workflows/d5b505e0-ea16-41cd-93cb-a3d1f892f117/jobs/297207
- https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/1985/workflows/195359db-46e9-4f07-9f70-09d16d3aee44/jobs/298030
=> tests: skip grpc 1.16

tox.ini
Django 3.1 (latest as of now) breaks djangorestframework 3.10.
=> ci: fix djangorestframework scenario

ddtrace/contrib/asgi/middleware.py, tests/contrib/asgi/test_asgi.py
This surfaced with a recent update to `httpx` (which the asgi tests use for multiple async requests) which treats url ports optional: https://github.com/encode/httpx/pull/1080
=> fix(asgi): handle when server port is not set

pyproject.toml, setup.py
That makes sure that when the last tag on `master` is 0.39, then the next
version for master is 0.40(.devN).
On the other hand, when on a branch named 0.39, the next version will be
0.39.1(.devN).
=> build: use release-branch-semver versioning in setuptool-scm

tests/__init__.py, tests/contrib/asgi/test_asgi.py, tests/contrib/django/test_django.py, tests/contrib/django/test_django_migration.py, tests/tracer/test_tracer.py
Move helper functions for overriding the tracer configuration for a test out of the `BaseTestCase` class into a module.
=> chore: move override functions to tests.utils

ddtrace/contrib/aiohttp/middlewares.py, ddtrace/settings/config.py, ddtrace/settings/integration.py, tests/tracer/test_settings.py
This setting is referenced in documentation as being public on the global
config but it never actually was.
Fixes #1573.
=> fix(core): expose http setting on global config

tox.ini
The latest black version seems to ignore our ignore list: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/2382/workflows/a434fb5a-ecf1-4ef7-a19e-fb807ce6230e/jobs/320709
Let's pin it for now.
=> fix(ci): pin black version

ddtrace/contrib/gevent/__init__.py, ddtrace/monkey.py, tests/contrib/gevent/monkeypatch.py, tests/contrib/gevent/test_tracer.py, tox.ini
As described in #662, modules that result in the ssl module being imported cause gevent monkey patching to potentially crash. When ddtrace-run is used this could not be avoided since it attempts to import and patch most modules.
This PR makes these modules be patched on import instead which should address the issue.
Fixes #662, #1624, #506, #1090
=> gevent: patch ssl modules on import

ddtrace/contrib/logging/patch.py, tests/contrib/logging/test_logging.py
If you are using a json logger the record value will be interpreted as a number which will result in values being rounded in the log pipeline.
=> Cast span_id and trace_id as string when adding to the record.

.readthedocs.yml, docs/conf.py, docs/requirements.txt
As tested in https://github.com/Kyle-Verhoog/dd-trace-py-test/commit/ab9d0f056ae25d4160979b715847fd56d7421cc9 (results [here](https://dd-trace-py-test.readthedocs.io/en/latest/web_integrations.html)) this is what is required in order for us to deploy our docs to readthedocs.
This will give us a good way to finally do versioned docs!
=> docs: add readthedocs config

ddtrace/contrib/algoliasearch/patch.py, ddtrace/contrib/django/patch.py, ddtrace/contrib/flask/helpers.py, ddtrace/contrib/flask/patch.py, ddtrace/contrib/flask/wrappers.py, ddtrace/contrib/grpc/__init__.py, ddtrace/contrib/grpc/client_interceptor.py, ddtrace/contrib/grpc/patch.py, ddtrace/contrib/grpc/server_interceptor.py, ddtrace/contrib/molten/__init__.py, ddtrace/contrib/molten/patch.py, ddtrace/contrib/molten/wrappers.py, ddtrace/contrib/redis/patch.py, ddtrace/contrib/requests/connection.py, ddtrace/contrib/requests/patch.py, ddtrace/contrib/sanic/patch.py, ddtrace/contrib/trace_utils.py, ddtrace/contrib/vertica/patch.py, ddtrace/settings/integration.py, ddtrace/utils/__init__.py, tests/contrib/algoliasearch/test.py, tests/contrib/flask/test_blueprint.py, tests/contrib/grpc/test_grpc.py, tests/contrib/sanic/test_sanic.py, tests/tracer/test_settings.py, tests/tracer/test_trace_utils.py
This patch adds service as a field to the IntegrationConfig class. This
will enable all integrations to have a service name that will be
automatically read from the environment. Follow-up patches will be
required to make use of this functionality.
Based off of (and is dependent on) #1611.
=> core: add DD_<INTEGRATION>_SERVICE to integration config

ddtrace/internal/runtime/container.py, ddtrace/monkey.py
The debug logs of the tracer have some noisy, not very helpful logs which can be cleaned up.
```
DEBUG:ddtrace.sampler:initialized RateSampler, sample 100% of traces
DEBUG:ddtrace.tracer:Connecting to DogStatsd(udp://localhost:8125)
DEBUG:ddtrace.internal.runtime.container:Failed to parse cgroup file for pid 'self'
File "/Users/kyle.verhoog/dev/dd-trace-py/ddtrace/internal/runtime/container.py", line 97, in get_container_info
with open(cgroup_file, mode="r") as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/proc/self/cgroup'
DEBUG:ddtrace.monkey:failed to patch boto
File "/Users/kyle.verhoog/dev/dd-trace-py/ddtrace/monkey.py", line 198, in _patch_module
imported_module.patch()
AttributeError: module …
```
=> core: clean-up some debug logs

ddtrace/span.py, tests/tracer/test_encoders.py
Formerly if the span_type field was assigned to a Span object as a `SpanType` then it would fail to encode since the encoding does not handle the enum. This patch fixes this by making `span_type` a property and storing the enum value on the span.
```python
with tracer.trace("op", span_type=SpanTypes.WEB):
pass
```
```python
with tracer.trace("op") as span:
span.span_type = SpanTypes.WEB
```
thanks to @thehesiod for discovering this one!
=> fix(core): always store span_type as str on span

ddtrace/contrib/falcon/middleware.py, tests/contrib/falcon/test_suite.py
- Check that span error is set to 1 for 5xx errors and all others are set to 0
- Modified Falcon tests to test above
=> fix(falcon): set span error for 5xx responses

ddtrace/contrib/dbapi/__init__.py, ddtrace/contrib/django/patch.py, ddtrace/contrib/mysql/__init__.py, ddtrace/contrib/mysql/patch.py, ddtrace/contrib/mysqldb/__init__.py, ddtrace/contrib/mysqldb/patch.py, ddtrace/contrib/psycopg/__init__.py, ddtrace/contrib/psycopg/connection.py, ddtrace/contrib/psycopg/patch.py, ddtrace/contrib/pymysql/__init__.py, ddtrace/contrib/pymysql/patch.py, ddtrace/contrib/sqlite3/__init__.py, ddtrace/contrib/sqlite3/patch.py, tests/contrib/dbapi/test_dbapi.py, tests/contrib/mysql/test_mysql.py, tests/contrib/mysqldb/test_mysqldb.py, tests/contrib/psycopg/test_psycopg.py, tests/contrib/pymysql/test_pymysql.py, tests/contrib/sqlite3/test_sqlite3.py
Add the global service name configuration for all dbapi based integrations. This will allow the configuration of the service name for:
- psycopg
- mysql
- mysqldb
- sqlite
- pymysql
=> feat: add global service name configuration for dbapi integrations

ddtrace/contrib/django/__init__.py, ddtrace/contrib/django/patch.py, tests/contrib/django/test_django.py
This allows the configuration of the service name directly in addition to providing a prefix.
=> feat(django): add database_service_name config option

tests/contrib/botocore/test.py, tox.ini
We were specifying celery==4.3 and `kombu==4.4` to run our test cases against.
celery==4.3 has the [dependencies](https://github.com/celery/celery/blob/v4.3.0/requirements/default.txt):
- pytz>dev
- billiard>=3.6.0,<4.0
- kombu>=4.4.0,<5.0
- vine>=1.3.0
Celery is installed first which installs `vine==5.0.0`, the latest version.
`kombu==4.4` has the [dependencies](https://github.com/celery/kombu/blob/v4.4.0/requirements/default.txt)
- amqp>=2.4.0,<3.0
Which installs `amqp==2.6.1` which has the [dependency](https://github.com/celery/py-amqp/blob/v2.6.1/requirements/default.txt)
- vine>=1.1.3, <5.0.0a1
which conflicts with the `vine==5.0.0` installed above 😕 🤦 
This is solved by explicitly stating vine==1.3 as a dependency of celery
The botocore tests had an issue where for some reason the …
=> fix: celery and botocore tests

.github/PULL_REQUEST_TEMPLATE.md
PR templates were introduced in #1590 but they aren't used by default. `.github/PULL_REQUEST_TEMPLATE.md` is the template that is used by default.
=> docs: add generic, default PR template

CHANGELOG.md, ddtrace/contrib/flask/middleware.py
#1651 exposed a bug in the flask instrumentation where patching template rendering was not idempotent. This wasn't caught in the tests because each time it was patched, it was patched with a different tracer instance. So when the spans were collected only the spans from the tracer instance specific to the test case were collected. [CI run](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/2519/workflows/04cb8a6d-9944-4f9c-a0ea-9ceaafc882b8/jobs/328555).
=> fix(flask): make template rendering idempotent

ddtrace/profiling/collector/stack.pyx, tests/profiling/collector/test_stack.py
Rather than hardcoding the default 100 Hz the stack collector is using to poll
data, let's use a default that is based on the Python threading interval
switch.
This gives the same result by default, but if anyone changes the switch
interval to something higher or lower, that'll make sure the profiler scales
accordingly.
=> feat(profiling): use sys.getswitchinterval() to determine stack collector freq

ddtrace/profiling/profiler.py, tests/profiling/compat_program.py, tests/profiling/simple_program.py, tests/profiling/test_accuracy.py, tests/profiling/test_profiler.py
This simplifies the Profiler object to only have one scheduler and hide everything from the user.
=> refactor(profiling): hide collector and scheduler

tests/contrib/flask/test_request.py
The comparison was not correct see the example below:
```python
>>> (0, 12) >= (0, 12, 0)
False
```
The flask version used here would be `(0, 12)` so the above check wasn't working properly.
=> fix(flask/tests): correct comparison

docs/_templates/navigation.html, docs/conf.py
Limits the depth in the sidebar to 2 so that the listing doesn't get too big.
=> docs: limit depth of headings in sidebar

tests/profiling/simple_program_fork.py, tests/profiling/test_main.py
This removes the memory testing with is not fork-dependent and make sure the
program exits as fast as possible.
=> test: improve fork test speed

tests/profiling/test_main.py
If stdout is not read, the process is blocked and never exits, making the test
hang forever.
=> test(profiling): fix process waiting

tox.ini
Old gevent version wheels segfaults with some version of Python.
It's likely an ABI changed somewhere and breaks everything.
=> ci: disable wheels for gevent

CHANGELOG.md, ddtrace/contrib/rediscluster/patch.py, tox.ini
Starting with `rediscluster==2.0.0` these classes were renamed, however our integration patched them in the top-level namespace rather than the module namespace. This PR changes this for 2.0.0 so that it works with 2.1.0 where the top-level imports were removed.
=> fix(rediscluster): support rediscluster==2.1.0

tox.ini
The recently released `greenlet==0.4.17` causing a segfault in `py39-profile-minreqs-gevent` with:
```
<frozen importlib._bootstrap>:228: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
ERROR: InvocationError for command /root/project/.tox/py39-profile-minreqs-gevent/bin/python -m tests.profiling.run pytest --capture=no --verbose --benchmark-disable tests/profiling (exited with code -11 (SIGSEGV)) (exited with code -11)
``` 
We can pin `greenlet==0.4.16` for the `gevent==20.6.0` installed for this tox env.
=> ci: pin greenlet for py39

CHANGELOG.md, ddtrace/internal/logger.py, tests/tracer/test_logger.py
When debug logging is enabled in the tracer, do not rate limit _any_ log lines.
Run the tracer with debug logging and expect that no log lines are limited (e.g. end with `, skipped X additional messages`)
`DD_TRACE_DEBUG=true python script.py`
=> Do not rate limit logs when in debug mode

CHANGELOG.md, ddtrace/profiling/_periodic.py, ddtrace/profiling/profiler.py, ddtrace/profiling/recorder.py, tests/profiling/collector/test_memalloc.py, tests/profiling/test_main.py
#1693 + #1695
The scenario ignore_profiler=False randomly fails because there is no memory
allocation samples from the profiler. Indeed, when allocating 1k objects,
there's a chance they take all the places in the buffer and exclude the ones
from the profiler itself.
Reduce the allocation to 1 object so we're sure there are at least one sample
from the profiler itself in the sample list.
When a process fork, its threading.Lock (and anything based on it) must be
considered unusable since there's no way to know in which state they are.
The workflow after fork()ing is to stop the old-parent-profiler, and start a
new one in the child.
The problem is that stopping the old profiler in the child would use at least
two locks:
1. one from the Event in the Scheduler that is used to stop the thread. …
=> Profiling CI fixes

tests/profiling/collector/test_stack.py
They're not useful and slow down the tests.
=> test(profiling): disable tracer startup logs

.circleci/config.yml, Dockerfile, ddtrace/profiling/collector/_memalloc.c, setup.py
Use the latest stable version rather than an old snapshot.
This adds more C checks to the C-written module that we own such as the
profiling memalloc collector.
It leverages GCC 10 static analyzer and enable a bunch of warning-as-errors.
This also upgrade to a more recent version of clang-format.
=> ci: more C checks

docs/requirements.txt
The docs build is failing with
```
File "/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
mod = __import__(extname, None, None, ['setup'])
ModuleNotFoundError: No module named 'reno'
During handling of the above exception, another exception occurred:
File "/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
args.tags, args.verbosity, args.jobs, args.keep_going)
File "/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 228, in __init__ …
```
=> docs: add reno to requirements

docs/requirements.txt
The docs build is failing with
```
File "/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
mod = __import__(extname, None, None, ['setup'])
ModuleNotFoundError: No module named 'sphinxcontrib.spelling'
During handling of the above exception, another exception occurred:
File "/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
args.tags, args.verbosity, args.jobs, args.keep_going)
File "/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 228, in __init__ …
```
=> docs: add spelling dependencies

pyproject.toml
Some of our Cython files are actually Python files compiled down to C.
This makes black format them by default, adding to the ignore list only the few
ones we know contains Cython-specific language.
=> chore(black): black pyx files too

ddtrace/monkey.py, releasenotes/notes/gevent-pynamodb-fix-72ac7017e51fd4f9.yaml, tests/contrib/gevent/test_tracer.py, tox.ini
As described in #1721.
Add pynamodb to patch on import modules.
Fixes #1721
=> fix(gevent/pynamodb): patch pynamodb on import

tox.ini
For some reason the pytest-django plugin is failing for the python 35/36 django
1.8 tests.
- https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/3059/workflows/d4cb4f16-aeaa-4c53-add2-3fc9892652cf/jobs/358261
- https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/3064/workflows/cfe60445-67b9-4b7a-a567-a8b7f0a0b3ae/jobs/358550
Let's pin pytest-django until this can be resolved.
=> tests: pin pytest-django

ddtrace/contrib/tornado/handlers.py, releasenotes/notes/tornado-none-bug-85faed75c859f5e5.yaml
It is possible that the current span in the log_exception function can be None.
This was formerly not handled and would cause an error.
Handle the case when the current span does not exist.
=> fix(tornado): handle current span being None

.circleci/config.yml
This was included since the docker image is be built after merging. It is no
longer required.
=> ci: remove install steps

ddtrace/internal/writer.py, ddtrace/tracer.py, tests/__init__.py, tests/contrib/tornado/test_config.py, tests/integration/test_integration.py, tests/tracer/test_tracer.py, tests/tracer/test_writer.py
This cleans up the design and prevents potentially filtered traces from
being counted towards the trace queue limit.
Filtering being done in the writers was probably done as an attempt at
optimization given that they'd run in the thread (presumably in parallel
to the main application code) however due to the GIL python code is only
ever run once.
=> core: move filters from writers to tracer

.github/workflows/changelog.yml, scripts/check-releasenotes
The changelog validation workflow we introduced didn't actually block PRs that didn't have a changelog entry aded.
This is because we were checking against `git diff origin/master... releasenotes/notes`, but if you didn't add anything the command would still succeed.
The main change here is moving to `git diff --name-only --diff-filter=A origin/master... | grep releasenotes/notes` which will succeed if there was a new filed _added_ in `releasenotes/notes`, but fail if not.
We also moved this check to it's own script to help readability and to add some logging output to help analyze success/failures.
=> Move changelog check to its own script

ddtrace/internal/writer.py, ddtrace/tracer.py, tests/tracer/test_writer.py
These are not being used and are a hindrance to refactoring the agent
writer. Something like #1143 should provide a cleaner solution to
collecting metrics like these.
=> core: remove health metrics

.circleci/config.yml
The job fails because the required library for building the docs is not
installed in the machine executor:
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/3046/workflows/012e69de-b4e2-470a-8762-98d32fbe4804/jobs/357586
Use the dev executor which has it installed.
=> ci: fix deploy_master and deploy_staging jobs

docs/conf.py, docs/ext/filters.py
Versions with "rc" in them seem to register as spelling mistakes.
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/3057/workflows/ab9bf51f-d338-4bff-8549-08e02d4cbcf1/jobs/358186
@majorgreys introduced this fix to solve the issue in #1714.
=> ci: fix spelling

.circleci/config.yml
Forgot to `sudo`. Tested it out this time:
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/3130/workflows/20ef583e-b828-4b4d-9cb5-b3bb4dae8042
=> ci: fix deploy_master

tests/tracer/test_logger.py
`warn` is deprecated and generates a ton of noise in our CI:
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/3123/workflows/da4f5a5f-e4bd-4555-8977-28b607448b70/jobs/361625
And we're sufficiently covered by testing all the other possible log methods.
=> tests(logging): don't test warn

tests/__init__.py
In using `snapshot` decorator with pytest tests with fixtures, a `TypeError` error is raised. This is due to a known limitation of `functools.wraps` with Python 2.7 and pytest: https://github.com/pytest-dev/pytest/issues/2782. This fix uses `wrapt.decorator` instead.
=> fix: snapshot decorator for pytest fixtures

tests/__init__.py, tests/contrib/django/test_django_snapshots.py
The motivation for this PR is to simplify the way snapshot tests are written for different runs. The use case here is for when a test run produces a different trace depending on the version of a library being used. We currently have to use cumbersome `skipif` clauses alongside multiple versions of the same test function.
=> chore: add variants for snapshot tests

tests/__init__.py
If flushing the queue fails then the closing request to the test agent will not
be sent which leaves the test token active in the test agent.
This makes sure that the test agent always gets the final request.
=> tests: handle failing trace flushes

ddtrace/contrib/dogpile_cache/lock.py
`tracer.current_span()` can potentially return None. This adds a check to make
sure that we won't get a NoneType error.
=> dogpile: safe-guard current_span

.readthedocs.yml
Note that the failing doc build should be resolved as of October 31:
https://github.com/readthedocs/readthedocs.org/issues/7605#issuecomment-717900199
=> readthedocs: update python version, don't fail on warning

.circleci/config.yml, scripts/run-tox-scenario
Use CircleCI job parallelism to run celery tox envs in parallel. The speed up with 4 executors brings down total runtime from ~45min to ~15min, as to be expected.
**Before** from master:
```
celery_contrib-py27-celery31-redis210: commands succeeded
celery_contrib-py35-celery31-redis210: commands succeeded
celery_contrib-py36-celery31-redis210: commands succeeded
celery_contrib-py27-celery40-redis210-kombu43: commands succeeded
celery_contrib-py27-celery40-redis32-kombu44: commands succeeded
celery_contrib-py27-celery41-redis210-kombu43: commands succeeded
celery_contrib-py27-celery41-redis32-kombu44: commands succeeded
celery_contrib-py35-celery40-redis210-kombu43: commands succeeded
celery_contrib-py35-celery40-redis32-kombu44: commands succeeded …
```
=> ci: parallelism for celery

.circleci/config.yml
This cuts down the time to build the bases from [~4 minutes](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/3473/workflows/fb677bdd-59a6-4505-9d21-6b1862c58668/jobs/379958) -> [~1 minute](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/3505/workflows/6e7ceef4-3100-466b-9897-50c9581527ca/jobs/381409)
=> ci: build base venvs in parallel

.circleci/config.yml
If changes are merged to these branches then we want them deployed whether or
not the tests pass.
=> ci: don't require passing tests for dev deploys

.circleci/config.yml
this gets the CI time to under 10 minutes (from about 20)
=> ci: bump profiling parallelism to 6

tests/__init__.py
Since the tests are run in parallel now parallel mode should be used for snapshot tests.
The test agent supports receiving trace payloads in two modes, synchronous and parallel. In synchronous (which we were using) the trace payloads are attributed to the active test token. The active test token is set with the `/start` endpoint. The parallel mode associates payloads with a test token which is included as an http header on the request.
=> tests: run snapshots in parallel mode

.circleci/config.yml, docker-compose.yml, riotfile.py, tests/contrib/django/test_django_snapshots.py, tox.ini
Replaces tox with riot for django tests.
Also re-enables migration tests which were mistakenly missed with changes in #1744 with filter on `^django_contrib-` rather than `^django_contrib` which would capture `django_contrib_migration`. 
Total duration of the django CI job goes down from 26 minutes to 11 minutes (before parallelism) and 10 mins to 5 mins (after parallelism).
List of tox envs (=69):
```
$ tox -l | grep django
django_contrib-py27-django18-djangopylibmc06-djangoredis45-pylibmc-redis210-memcached-test_django
django_contrib-py27-django111-djangopylibmc06-djangoredis45-pylibmc-redis210-memcached-test_django
django_contrib-py35-django18-djangopylibmc06-djangoredis45-pylibmc-redis210-memcached-test_django
django_contrib-py35-django111-djangopylibmc06-djangoredis45-pylibmc-redis210- …
```
=> chore: use riot for django tests

.circleci/config.yml, riotfile.py, tox.ini
```
Python 2.7 'pynamodb>=4.0,<4.1' 'moto>=1.0,<2.0'
Python 2.7 'pynamodb>=4.1,<4.2' 'moto>=1.0,<2.0'
Python 2.7 'pynamodb>=4.2,<4.3' 'moto>=1.0,<2.0'
Python 2.7 'pynamodb>=4.3,<4.4' 'moto>=1.0,<2.0'
Python 2.7 'pynamodb' 'moto>=1.0,<2.0'
Python 3.5 'pynamodb>=4.0,<4.1' 'moto>=1.0,<2.0'
Python 3.5 'pynamodb>=4.1,<4.2' 'moto>=1.0,<2.0'
Python 3.5 'pynamodb>=4.2,<4.3' 'moto>=1.0,<2.0'
Python 3.5 'pynamodb>=4.3,<4.4' 'moto>=1.0,<2.0'
Python 3.5 'pynamodb' 'moto>=1.0,<2.0'
Python 3.6 'pynamodb>=4.0,<4.1' 'moto>=1.0,<2.0'
Python 3.6 'pynamodb>=4.1,<4.2' 'moto>=1.0,<2.0'
Python 3.6 'pynamodb>=4.2,<4.3' 'moto>=1.0,<2.0'
Python 3.6 'pynamodb>=4.3,<4.4' 'moto>=1.0,<2.0'
Python 3.6 'pynamodb' 'moto>=1.0,<2.0'
Python 3.7 'pynamodb>=4.0,<4.1' 'moto>=1.0,<2.0'
Python 3.7 'pynamodb>=4.1,<4.2' …
```
=> use riot to test pynamodb

ddtrace/contrib/django/utils.py, releasenotes/notes/django-request-uri-safe-guards-fdd8bd664374ded1.yaml, tests/contrib/django/test_django.py
This fix addresses a problem that arises if a request is handled that is missing a url scheme. An example of this case is seen in [saleor's wsgi code](https://github.com/mirumee/saleor/blob/a82166ce550eb4baefbc7ffb1c1514d710500f60/saleor/wsgi/__init__.py#L33-L45) where a warmup request is made when the wsgi application is started:
```
application(
{
"REQUEST_METHOD": "GET",
"SERVER_NAME": SimpleLazyObject(get_allowed_host_lazy),
"REMOTE_ADDR": "127.0.0.1",
"SERVER_PORT": 80,
"PATH_INFO": "/graphql/",
"wsgi.input": b"",
"wsgi.multiprocess": True,
},
lambda x, y: None,
)
```
Additionally, this fix addresses the use of a `SimpleLazyObject` for a request attribute.
I have added this to the [majorgreys/django-tutorial-uwsgi-warmup](https://github.com/DataDog/trace-examples/tree/majorgreys/djang …
=> fix(django): add safe guards in get_request_uri

.circleci/config.yml
The actual test running was being skipped if parameters.wait was not defined
=> ci: fix riot tests

.circleci/config.yml
Celery is the slowest job so let's speed it up a bit.
=> ci: bump celery parallelism

tests/__init__.py, tests/integration/test_integration.py
This allows a new tracer instance to be used and configured for snapshot test cases.
=> add include_tracer option to snapshot

.github/workflows/build_deploy.yml, releasenotes/notes/build-deploy-py39-wheels-6524f77277e3c788.yaml
Update `cibuildwheel` to latest release (1.6.4) to add building and deploying wheels for Python 3.9, support for which was added in #1750.
=> ci: update cibuildwheel to deploy 3.9 wheels

ddtrace/context.py, ddtrace/span.py, ddtrace/tracer.py
span.set_tag() does a lot of checking which is not required when we know the values we're setting.
It's nearly 8x faster to bypass all these checks and set the value directly.
```
---------------------------------------------------------------------------------------------- benchmark: 2 tests ----------------------------------------------------------------------------------------------
Name (time in ns)                  Min                    Max                  Mean              StdDev                Median                IQR            Outliers  OPS (Kops/s)            Rounds  Iterations
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
=> core: set tags directly with str values

ddtrace/profiling/exporter/http.py, ddtrace/profiling/profiler.py, releasenotes/notes/profiling-fix-uds-ebf0ea0587c8a23c.yaml, tests/profiling/test_profiler.py
This fixes the UDS class creation which was wrongly using the hostname as path.
This also simplify the profiler/http code to hardcode the endpoint since it's
not possible to pass it via UDS anyway (and has no interest).
=> fix(profiling): use correct path for UDS support

.circleci/config.yml
#1826 was missing pin for riot in `run_test` job.
=> fix(ci): pin riot

ddtrace/profiling/exporter/http.py, ddtrace/profiling/profiler.py, releasenotes/notes/profiling-use-tracer-config-83aa0ae0c2c53086.yaml, setup.py, tests/profiling/test_profiler.py
If the user does not pass any configuration to the Profiler object, it will by
default copy the configuration from the provided Tracer.
This makes sure that users only configuring the Tracer will see the Profiler
work the same way by default.
=> feat(profiling): profiler uses tracer configuration if no configuration given

ddtrace/compat.py, ddtrace/profiling/_nogevent.py, ddtrace/profiling/collector/_threading.pyx, ddtrace/profiling/collector/stack.pyx, ddtrace/profiling/event.py, ddtrace/profiling/exporter/pprof.pyx, releasenotes/notes/profiler-stack-greenlet-tracer-6f960c1557fd39c4.yaml, tests/profiling/collector/test_stack.py
This makes the export more flexible: by setting the thread_name to None in the
event, any exporter can implement its own logic for anonymous thread name.
This leverages the gevent GreenletTracer to keep track of the greenlet running
in the main thread.
This allows us to add information in stack events about the currently running
gevent thread, and store its name if it has one.
=> feat(profiling): track gevent greenlets

ddtrace/profiling/collector/_memalloc.c, tests/profiling/collector/test_memalloc.py
This ought to be enough as in practice we use something like 32 or 64. The goal
being to buffer data in C before exporting to Python regularly, there's no need
to store gigabytes of stack trace in C anyway.
=> refactor(profiling/memalloc): reduce max number of events in memory to 65535

ddtrace/profiling/collector/_memalloc.c, ddtrace/profiling/collector/_memalloc_tb.c, ddtrace/profiling/collector/_memalloc_tb.h, ddtrace/profiling/collector/_pymacro.h, setup.py
This splits the memory allocation profiler in 2 different files. The new file
contains everything related to traceback management.
This should make it easier to comprehend and hack on the memalloc profiler in
the future.
=> refactor(profiling): split memalloc in 2 parts

ddtrace/compat.py, tests/integration/test_integration.py
Instantiating a `_MainThread` is causing Python 2 applications to spawn another thread instance which conflicts with the actual MainThread that is already running causing Python 2 applications to output
```
Exception RuntimeError: RuntimeError('cannot join current thread',)
```
=> fix: don't spawn a _MainThread if in main thread

ddtrace/span.py, tests/tracer/test_span.py
Currently there is no way to ignore exceptions raised when a span is being used as a context manger however there are times when exceptions are used non-erroneously as in the case of [Http404 exceptions in Django](https://github.com/DataDog/dd-trace-py/pull/1834).
=> span: add ignored exceptions

ddtrace/profiling/collector/_memalloc.c, ddtrace/profiling/collector/_memalloc_tb.c, ddtrace/profiling/collector/_memalloc_tb.h
This stores the allocated ptr address into the traceback_t struct.
=> refactor(profiling/memalloc): track allocated ptr

tests/tracer/test_ext.py
=> tests: force env values in CI tests

riotfile.py
Adds a helper to our `riotfile.py` to make selecting python versions for `Venv` easier.
We define an exhaustive list of all Python versions we support, and then we use this helper to select what versions to test each `Venv` with based on a min and max requirement.
```python
Venv(pys=select_pys())  # all of them
Venv(pys=select_pys(max_version=3.6))  # [2.7, 3.5, 3.6]
Venv(pys=select_pys(min_version=3.6))  # [3.6, 3.7, 3.8, 3.9]
```
This helps since as we add or remove support for Python versions, then all `Venv`s will get updated as well.
- ~[ ] Entry added to release notes using [reno](https://docs.openstack.org/reno/latest/user/usage.html)~
- ~[ ] Tests provided; and/or~
- ~[ ] Description of manual testing performed and explanation is included in the code and/or PR.~
- ~[ ] Library …
=> ci: add helper to select venv 'pys'

Dockerfile
In light of issues with maintaining the ci image we use for running tests in a Docker container, this PR removes riot and tox from our Dockerfile. This avoids the problem of pinning or upgrading these packages as they are updated. Also, if we down the line want to pin, we pin them in the setup ci jobs rather than having to first push a change with the updated pinned version in the Dockerfile. The `scripts/ddtest` has already been updated in #1828 to silently install these packages before executing a command.
=> ci: remove tox/riot from docker image

.circleci/config.yml, riotfile.py, tox.ini
Two reasons:
1) The 0.22 release of mongoengine introduced syntax [that breaks Python 3.5](https://github.com/MongoEngine/mongoengine/pull/2448). So we need to work around this
2) It appears as though tox is broken for our mongoengine tests. It pulls in the latest version of pymongo for each of the tests as seen here: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/4286/workflows/6a8db7e2-36fc-4679-8e65-8a87896bf46b/jobs/427577
=> Use riot for mongoengine tests

docs/installation_quickstart.rst, releasenotes/notes/current-span-reset-a860bbbad3acda5c.yaml, releasenotes/notes/django-request-uri-safe-guards-fdd8bd664374ded1.yaml, releasenotes/notes/django-view-mro-check-782374fb9c427305.yaml, releasenotes/notes/fix-aiobotocore-9eeac808a3bf0f63.yaml, releasenotes/notes/fix-elasticsearch-a3f89a915ccc36c4.yaml, releasenotes/notes/fix-span-type-web-20122b5c57c50341.yaml
=> v0.45 documentation fixes

ddtrace/ext/ci.py, tests/tracer/fixtures/ci/jenkins.json
Removes invalid Jenkins URL from CI env detection.
=> ext: remove invalid Jenkins job URL

tox.ini
pytest-cov should be sufficient.
=> Remove coverage as a dependency

.coveragerc
https://coverage.readthedocs.io/en/coverage-5.3/cmd.html#warnings
```
Coverage.py warning: Couldn't parse Python file '/root/project/tests/contrib/molten/test_molten.py' (couldnt-parse)
Coverage.py warning: Couldn't parse Python file '/root/project/tests/contrib/sanic/test_sanic.py' (couldnt-parse)
Coverage.py warning: Couldn't parse Python file '/root/project/tests/contrib/sanic/test_sanic_server.py' (couldnt-parse)
```
=> Coverage ignore couldnt-parse errors

ddtrace/profiling/_periodic.py, ddtrace/profiling/collector/_threading.pyx, ddtrace/profiling/collector/stack.pyx, tests/profiling/test_periodic.py
This list was used to track the periodic thread running on behalf of the
profiler, to ignore them when collecting data.
This mechanism is quite fragile and actually breaks on a fork: the threads are
dead and won't never be removed from the list.
In order to avoid that, we now use the list of active thread maintained by
Python in `threading._active` instead, and add a `_ddtrace_profiling_ignore`
flag to our `threading.Thread` class to indicate it should be ignored.
This has the perk of allowing anyone to write threads ignore by the profiler —
for better or for worse.
=> refactor(profiling): remove global periodic thread list

tests/profiling/collector/test_stack.py
The number of frames in the events is only > than the number of max frames if
the captured thread runs code that needs truncation.
With gevent, it happens that the MainThread runs the gevent main loop function
which is only 1 stack trace long, so no truncation happens.
=> test(profiling): fix potential failure in test_collect_truncate with gevent

tests/profiling/collector/test_stack.py
This test might fail if another gevent thread runs and is captured by the
profiler. Make sure it ignore those.
This also improve the test duration from 60 seconds to 5 seconds.
=> test(profiling): increase accuracy of test_collect_thread

conftest.py, tox.ini
Noticed an issue in CircleCI where we do not get all of the test results in the junit.xml file. This is because pytest doesn't append, it'll overwrite. This has issues when we run multiple test scenarios in one container in CircleCI.
This PR adds a configuration hook to `conftest.py` to dynamically set the JUnit `xmlpath` to include the pid in the filename.
In order for this to work properly we also have to pass through the `CI_*` and `CIRCLE_*` env variables (well, I am only using `CI=true`, but figured doesn't hurt to pass the others through, probably useful for tools like Codecov/etc if we ever run them in tox env).
Results end up looking like this: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/4520/workflows/6cf32f06-dd5c-4d22-833f-0790fa9b9008/jobs/442582/artifacts
=> Dynamically set JUnit XML results filename

ddtrace/profiling/_service.py, ddtrace/profiling/collector/stack.pyx, ddtrace/profiling/exporter/http.py, ddtrace/profiling/recorder.py, ddtrace/profiling/scheduler.py, tests/profiling/test_profiler.py
This also makes sure that copy() works fine without checking all attributes
individually, just in case we'd forget some.
=> refactor(profiling): allow to compare Profiler objects

tests/profiling/collector/test_memalloc.py
The thread_id might not be the main thread is there's another thread for
another test laying around.
Move the assert in a piece of code where we are sure what the thread_id is.
=> test(profiling): fix possible race condition in thread_id test

ddtrace/profiling/profiler.py, ddtrace/profiling/scheduler.py, tests/commands/test_runner.py, tests/profiling/simple_program_fork.py, tests/profiling/test_profiler.py
This argument controlled only the exit time, but not the fact that it exported
or no a last profile.
This makes sure the scheduler is fully stopped before stopping collector, and
then flush or not a last profile.
This fixes an issue where on fork() a profile could be still sent when the
parent profiler would be stopped.
=> refactor(profiling): fix stop() flush argument

ddtrace/profiling/_periodic.py, releasenotes/notes/profiling-fix-deadlock-gevent-1e6192828238def3.yaml, tests/profiling/gevent_fork.py, tests/profiling/test_main.py, tests/profiling/test_periodic.py
In gevent when profile_childre is True, the child process will try to stop the
parent profiler. This can hang forever since the thread is not running: it will
never set the `quit` value to True.
To avoid this, we use `self.is_alive` to check if the thread is alive; on fork,
the thread is marked as dead by Python via the _reset_internal_locks() method.
This is a fix similar to 6836e1f05d58649b16e8e5a668bce85cfd1238a5
In order to `is_alive` to work, the thread now set the Thread._started event
correctly. It's set in __bootstrap normally, but this uses Locks in Python 3
which are now gevent-Lock, so we can't use this method. We use our own variable
and a busy loop to make sure the thread booted.
This can avoid a race condition when the process fork just after the thread
starts and where it'd …
=> fix(profiling): fix thread join() hang after fork() with gevent

tox.ini
B902 was added in https://github.com/elijahandrews/flake8-blind-except/releases/tag/v0.2.0 but we can safely ignore it for now.
=> fix(ci): flake8 ignore B902

ddtrace/profiling/collector/__init__.py, ddtrace/profiling/profiler.py, ddtrace/profiling/scheduler.py, tests/profiling/test_profiler.py
This new snapshot() method allows collectors to implement a method to be
executed just before the scheduler is about to export data.
This allows to export data, e.g., every minute only.
=> refactor(profiling): allow Collectors to run a function before flushing

ddtrace/ext/ci.py, ddtrace/ext/git.py, tests/tracer/fixtures/ci/appveyor.json, tests/tracer/fixtures/ci/azurepipelines.json, tests/tracer/fixtures/ci/bitbucket.json, tests/tracer/fixtures/ci/bitrise.json, tests/tracer/fixtures/ci/buildkite.json, tests/tracer/fixtures/ci/circleci.json, tests/tracer/fixtures/ci/github.json, tests/tracer/fixtures/ci/gitlab.json, tests/tracer/fixtures/ci/jenkins.json, tests/tracer/fixtures/ci/travisci.json
Update the CI specs removing deprecated CI tags based on DataDog/datadog-ci-spec#38
=> ext: update ci specs

ddtrace/ext/ci.py, tests/tracer/fixtures/ci/gitlab.json
Update the CI specs adding new CI tags for GitLab
=> ext: update ci specs - GitLab

docs/configuration.rst
Update configuration documentation to clarify that `DD_VERSION` is set along with `DD_SERVICE` as part of [unified service tagging](https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=kubernetes).
=> docs: update DD_VERSION configuration

.github/PULL_REQUEST_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE/bugfix.md, .github/PULL_REQUEST_TEMPLATE/feature.md, .github/PULL_REQUEST_TEMPLATE/integration.md
changelog management is now done through CI so we don't need it in the checklist; along with a few other touch-ups
=> PR template fix-ups

ddtrace/contrib/requests/session.py, releasenotes/notes/traced-session-1f2134ac99449b91.yaml, tests/contrib/requests/test_requests.py
`TracedSession` is broken unless patching is done.
Fixes #778
=> requests: fix TracedSession usage when not patching 

ddtrace/internal/writer.py, tests/integration/test_integration.py
Looks like there was a typo/oversight with the error handling for encoding in which we'd continue to try to send the trace after encoding failed.
=> fix(core): handle failed encoding

tox.ini
Seems like Python 2.7 and grpc 1.14, 1.18 results in deadlocks in the tests:
- https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/4758/workflows/b7bd6cb9-a2ec-49c7-a4e6-9c24d9766c4b/jobs/457578
- https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/4758/workflows/afff6b43-5296-4372-b120-3e72a5f1aa0b/jobs/457579
- https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/4758/workflows/6f8551e3-a8ee-4250-a13c-bcc146c03c36/jobs/457502
=> tests: exclude py27 grpc 1.14, 1.18

releasenotes/config.yaml
This exclude rc releases which is not a good thing to have a proper release
notes generated on every branch.
=> docs: fix release notes release_tag_re

ddtrace/sampler.py, tests/integration/test_integration.py, tests/snapshots/tests.integration.test_integration.test_sampling.snap, tests/tracer/test_sampler.py
The sampling tests previously depended on the implementation of `Context`. This patch removes the dependence by depending the resulting traces rather than the intermediate state of spans and context. A snapshot test for a variety of sampling scenarios is also added.
This will unblock #1936
=> refactor sampling tests to be context independent

tests/contrib/grpc/test_grpc.py
#1949 attempted to address flaky grpc tests but this issue remains https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/4835/workflows/c27376c4-9d7b-458c-a0b3-c290bfcad48f/jobs/462372.
Follow same approach in grpcio tests for shutting down thread pool executor created when starting server:
https://github.com/grpc/grpc/blob/94c653aaf5d8094204de79e2a67070c2825b7d9b/src/python/grpcio_tests/tests/unit/_interceptor_test.py#L369
If this resolves the problem, we can revert the previous attempt.
=> ci: fix flaky grpc tests

tox.ini
Reverts DataDog/dd-trace-py#1949 since #1961 should have addressed the root cause.
=> Revert "tests: exclude py27 grpc 1.14, 1.18"

.mergify.yml
Mergify is a little bit too aggressive on updating the PR and trying to merge.
This copies the content of branch protection settings so it does not try to
merge before at least the CI and an approval are there.
=> ci(mergify): add more conditions before trying to merge

tests/contrib/grpc/test_grpc.py
Followup on #1961 to further reduce the number of threads in the server pool as another attempt to avoid the deadlocks that are causing the grpc job to hang in CI.
=> ci: lower max pool of workers for grpc server

.github/workflows/build_deploy.yml
Just testing out https://github.com/joerick/cibuildwheel/pull/482 to see if I can get it working.
They mentioned this feature should be released this week.
=> Use cibuildwheel to build aarch64 wheels

ddtrace/contrib/flask/helpers.py, ddtrace/contrib/flask/patch.py
This helper was needlessly dependent on the context implementation
and could be simplified to using the tracer API.
=> flask: remove get_current_span helper

ddtrace/contrib/django/patch.py, releasenotes/notes/django-key-error-be8812133f0ef920.yaml
In some edge cases (preview mode in wagtail CMS for instance) the request meta object does not contain a query string attribute, so access it safely with a dictionary get rather than killing the request
=> Resolve keyerror in Django traced_get_response

ddtrace/context.py, tests/contrib/logging/test_logging.py, tests/tracer/test_context.py
This is a valid use-case in async and I don't think we've ever used
this log message for debugging.
=> logging: remove logging for parent closing before child

ddtrace/context.py, ddtrace/tracer.py, tests/tracer/test_context.py, tests/tracer/test_tracer.py
This gets it out of the context which will help with refactoring.
=> tracer: move hostname tagging to start_span

tests/contrib/futures/test_propagation.py, tests/tracer/test_propagation.py
These tests depended on implementation details of the context which are
not described in our public API. In my opinion it's safe to remove
the dependence so long as the functionality is still asserted.
=> tests: make context independent

tests/contrib/gevent/test_tracer.py
These tests depended on the implementation details of the context
management for gevent. There exist very similar tests that assert the
correct context management behaviour which are less brittle.
=> gevent: remove implementation dependent tests

.mergify.yml
I find it handy to be able to notice at a glance PR that are in conflict with a
label, so we know there's, e.g., no point in reviewing them now.
This also notifies the author they need to update the PR to get it working.
=> chore(mergify): warn on PR conflict

ddtrace/context.py, ddtrace/propagation/http.py, tests/tracer/test_context.py, tests/tracer/test_propagation.py, tests/tracer/test_tracer.py
Really no reason for it to be "private" since it's in the initializer. Also noticed that it's not thread-safe, not sure it's worth doing anything about it now.
=> context: _dd_origin -> dd_origin

ddtrace/contrib/httplib/__init__.py, ddtrace/contrib/httplib/patch.py, releasenotes/notes/httplib-3b8917c90d162170.yaml
Since the integration is disabled by default, it makes sense that if a
user opts into using it that distributed tracing should be enabled out
of the box.
Also updates the docs to match our new format.
=> httplib: enable distributed tracing by default

ddtrace/internal/uwsgi.py, ddtrace/profiling/profiler.py, docs/spelling_wordlist.txt, releasenotes/notes/profiling-uwsgi-faaeb38f11bd287b.yaml, tests/profiling/conftest.py, tests/profiling/test_uwsgi.py, tests/profiling/uwsgi-app.py, tox.ini
Profiling tests use subprocesses in several cases which might mess with
coverage. Let's disable coverage in Python subprocesses.
This adds support for many of the uWSGI configuration mode (master, lazy-apps,
multi process, etc) by introspecting uWSGI options and leveraging its hooks.
=> feat(profiling): support most uwsgi modes

.circleci/config.yml, Dockerfile
To help address timeout errors with CircleCI: https://support.circleci.com/hc/en-us/articles/360045268074-Build-Fails-with-Too-long-with-no-output-exceeded-10m0s-context-deadline-exceeded-
=> ci: disable output buffering

ddtrace/contrib/django/patch.py, releasenotes/notes/django-2ebd5565ee27d4d1.yaml, tests/snapshots/tests.contrib.django.test_django_snapshots.test_404_exceptions.snap, tests/snapshots/tests.contrib.django.test_django_snapshots.test_404_exceptions_111x.snap, tests/snapshots/tests.contrib.django.test_django_snapshots.test_404_exceptions_18x.snap, tests/snapshots/tests.contrib.django.test_django_snapshots.test_404_exceptions_21x.snap, tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_callable_view.snap, tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_callable_view_111x.snap, tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_callable_view_18x.snap, tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_callable_view_21x.snap, tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_partial_based_view.snap, tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_partial_based_view_111x.snap, tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_partial_based_view_18x.snap, tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_partial_based_view_21x.snap, tests/snapshots/tests.contrib.django.test_django_snapshots.test_safe_string_encoding.snap, tests/snapshots/tests.contrib.django.test_django_snapshots.test_safe_string_encoding_111x.snap, tests/snapshots/tests.contrib.django.test_django_snapshots.test_safe_string_encoding_18x.snap, tests/snapshots/tests.contrib.django.test_django_snapshots.test_safe_string_encoding_21x.snap, tests/snapshots/tests.contrib.django.test_django_snapshots.test_urlpatterns_include.snap, tests/snapshots/tests.contrib.django.test_django_snapshots.test_urlpatterns_include_21x.snap
This in general is fine but if there is a parent span of the same
service (eg. WSGI) then metrics won't be calculated for django spans.
With this change metrics will be generated regardless.
=> django: add measured tag to root span

.circleci/scripts/test_build.sh
3.4 dropped support for Python 2 and introduced Rust for build time dependency
https://cryptography.io/en/3.4/changelog.html#v3-4
https://github.com/pyca/cryptography/issues/5771
Our only dependency which needs cryptography is `twine`, which is only used here as part of the CircleCI job to test building.
=> Pin cryptography package to <3.4

.circleci/config.yml, riotfile.py, tox.ini
Use `riot` to run grpc test suite.
Number of tests running increased because of adding 3.9 testing.
```
grpc  Interpreter(_hint='2.7') 'mock' 'pytest' 'coverage' 'pytest-cov' 'opentracing' 'googleapis-common-protos' 'grpcio~=1.12.0'
grpc  Interpreter(_hint='2.7') 'mock' 'pytest' 'coverage' 'pytest-cov' 'opentracing' 'googleapis-common-protos' 'grpcio~=1.14.0'
grpc  Interpreter(_hint='2.7') 'mock' 'pytest' 'coverage' 'pytest-cov' 'opentracing' 'googleapis-common-protos' 'grpcio~=1.18.0'
grpc  Interpreter(_hint='2.7') 'mock' 'pytest' 'coverage' 'pytest-cov' 'opentracing' 'googleapis-common-protos' 'grpcio~=1.20.0'
grpc  Interpreter(_hint='2.7') 'mock' 'pytest' 'coverage' 'pytest-cov' 'opentracing' 'googleapis-common-protos' 'grpcio~=1.21.0'
grpc  Interpreter(_hint='2.7') 'mock' 'pytest' …
```
=> ci: move grpc to riot

tests/profiling/collector/test_stack.py
The current code is subject to a race condition as the data is flushed out via
the scheduler before the assertion is run.
This fixes the test 🤞 by making it clear that the flush must not occur and by
getting the events out before we stop the profiler anyway by using the `reset`
method.
=> test(profiling): make test_not_ignore_profiler_gevent_task more robust

.circleci/config.yml, riotfile.py, tox.ini
Moving from tox to riot cuts runtime down from 20+ minutes to <10 mins.
```
elasticsearch_contrib-py27-elasticsearch16
elasticsearch_contrib-py27-elasticsearch17
elasticsearch_contrib-py27-elasticsearch18
elasticsearch_contrib-py27-elasticsearch23
elasticsearch_contrib-py27-elasticsearch24
elasticsearch_contrib-py27-elasticsearch51
elasticsearch_contrib-py27-elasticsearch52
elasticsearch_contrib-py27-elasticsearch53
elasticsearch_contrib-py27-elasticsearch54
elasticsearch_contrib-py27-elasticsearch63
elasticsearch_contrib-py27-elasticsearch64
elasticsearch_contrib-py27-elasticsearch68
elasticsearch_contrib-py27-elasticsearch70
elasticsearch_contrib-py27-elasticsearch71
elasticsearch_contrib-py27-elasticsearch75
elasticsearch_contrib-py27-elasticsearch76 …
```
=> Migrate elasticsearch from tox to riot

ddtrace/profiling/collector/_memalloc.c, ddtrace/profiling/collector/_memalloc_heap.c, ddtrace/profiling/collector/_memalloc_heap.h, ddtrace/profiling/collector/_memalloc_tb.c, ddtrace/profiling/collector/_memalloc_tb.h, ddtrace/profiling/collector/_utils.h, ddtrace/profiling/collector/memalloc.py, ddtrace/profiling/profiler.py, tests/profiling/collector/test_memalloc.py
Adds a _memalloc.heap() method that returns a list of traceback using memory
right now with their allocated size.
=> feat(profiling): allow to export memory heap to Python

.circleci/config.yml, riotfile.py, tests/contrib/cherrypy/test_middleware.py, tests/snapshots/tests.contrib.cherrypy.test_middleware.test_child.snap, tests/snapshots/tests.contrib.cherrypy.test_middleware.test_error.snap, tests/snapshots/tests.contrib.cherrypy.test_middleware.test_fatal.snap, tests/snapshots/tests.contrib.cherrypy.test_middleware.test_success.snap, tox.ini
The cherrypy test cases were a little flaky due to the test server configuration that the cherrypy test case uses. 
This PR increases the wait time, removes the time assertions and introduces snapshot testing and ports the tests from tox to riot.
=> ci: fix flaky cherrypy tests, use riot, snapshots

ddtrace/contrib/flask/middleware.py, releasenotes/notes/flask-241a6dd8c17e2c12.yaml
By shortcutting when the span isn't sampled, the span will not be
finished. By not finishing the span, the trace will never finish which
will keep it in memory indefinitely.
=> flask: don't shortcut on sampling decision

.circleci/config.yml, riotfile.py, tox.ini
Use riot for psycopg (adding the 6 tests for latest to the test matrix) and sqlalchemy
```
$ tox -l | grep psycopg_contrib
psycopg_contrib-py27-psycopg224
psycopg_contrib-py27-psycopg225
psycopg_contrib-py27-psycopg226
psycopg_contrib-py27-psycopg227
psycopg_contrib-py27-psycopg228
psycopg_contrib-py35-psycopg224
psycopg_contrib-py35-psycopg225
psycopg_contrib-py35-psycopg226
psycopg_contrib-py35-psycopg227
psycopg_contrib-py35-psycopg228
psycopg_contrib-py36-psycopg224
psycopg_contrib-py36-psycopg225
psycopg_contrib-py36-psycopg226
psycopg_contrib-py36-psycopg227
psycopg_contrib-py36-psycopg228
psycopg_contrib-py37-psycopg227
psycopg_contrib-py37-psycopg228
psycopg_contrib-py38-psycopg228
psycopg_contrib-py39-psycopg228
$ tox -l | grep psycopg_contrib | wc -l
19
$ tox -l | grep …
```
=> ci: use riot for psycopg and sqlalchemy

tox.ini
This prevents the job to be run twice as cython is not installed in the venv
otherwise.
=> docs: fix missing cython dependencies

tests/profiling/test_accuracy.py
The test failed in the ci with 3.3% drift:
E       AssertionError: assert False
E        +  where False = almost_equal(2067426803, 2000000000.0)
E        +    where 2067426803 = total_time(defaultdict(<function test_accuracy.<locals>.<lambda> at 0x7f04011c5c80>, {0: defaultdict(<function test_accuracy.<loc...acy.<locals>.<lambda>.<locals>.<lambda> at 0x7f03fbabc510>, {'spend_1': 0, 'spend_3': 0, 'monotonic_ns': 1614057035})}), 'spend_1')
Increase the value to 4% to be safe.
=> test(profiling): increase tolerance for accuracy testing

tests/profiling/simple_program_fork.py
The current test can fail with the following error:
File "/root/project/tests/profiling/simple_program_fork.py", line 47, in <module>
assert test_lock_name in set(e.lock_name for e in recorder.events[cthreading.LockReleaseEvent])
File "/root/project/tests/profiling/simple_program_fork.py", line 47, in <genexpr>
assert test_lock_name in set(e.lock_name for e in recorder.events[cthreading.LockReleaseEvent])
RuntimeError: deque mutated during iteration
The event list should not be used while the profiler runs. The program now
calls `reset` instead to make sure we can iterate on the event list and the
profiler can keep running and storing new events while the test asserts.
=> test(profiling): fix test_fork failure

tests/profiling/collector/test_stack.py
The test can fail with the following error:
.0 = <deque_iterator object at 0x7f0a80ce3b30>
>   assert collector_thread_ids.isdisjoint({e.task_id for e in events})
E   RuntimeError: deque mutated during iteration
Which makes sense since the event deque is not frozen and still used by the
profiler object. Calling the `reset` method makes sure we get the current
event list and can assert on it without having it being modified.
=> test(profiling): fix flaky test_ignore_profiler_gevent_task

tests/profiling/collector/test_stack.py
Gevent scheduling is not reliable, so there's always a chance than in 3 seconds
the event we want to see is not seen.
This changes the sleeping time into a `while True` loop that waits until we
validate the test.
=> test(profiling): make sure to wait for all valid events to be seen

ddtrace/contrib/cherrypy/middleware.py
By shortcutting when the span isn't sampled, the span will not be
finished. By not finishing the span, the trace will never finish which
will keep it in memory indefinitely.
=> cherrypy: don't shortcut on sampling decision

riotfile.py
This enables the pass-through of additional command line flags and
arguments to pytest.
=> riot: specify cmdargs for all pytest commands

tox.ini
We can't test Sanic on Python 3.6 as uvloop is pulled and requires
Python  >= 3.7.
=> ci: remove Sanic support for Python 3.6

ddtrace/contrib/django/__init__.py
`DD_SERVICE_NAME` was deprecated in #1320, but it still appears in the Django integration docs. This PR replaces it with `DD_SERVICE`.
=> chore(docs): Update deprecated env variable name

pyproject.toml, riotfile.py
The exclude rule was omitting `riotfile.py` which needed to be formatted.
=> fix black formatting on riotfile.py

riotfile.py
The `rsa` package dropped support for Python 2.7 starting with version 4.7.1.
=> fix(ci): pin rsa for python 2.7

ddtrace/internal/logger.py, releasenotes/notes/fix-logger-standard-logging-rate-envvar-155e113deea71e85.yaml, tests/tracer/test_logger.py
Deprecate the `(DD/DATADOG)_LOGGING_RATE_LIMIT` variable in favour of the standard `DD_TRACE_LOGGING_RATE` for configuring the logging rate limit (see DataDog/architecture#833)
=> fix(logger): Use standard DD_TRACE_LOGGING_RATE variable

tests/contrib/uwsgi/__init__.py, tests/profiling/test_uwsgi.py
Refactor the running of uwsgi to make it useful for other components, like the tracer in #1992, as suggested here https://github.com/DataDog/dd-trace-py/pull/1992#discussion_r574647006.
I left the fixtures as specific to each use case and factored out the subprocess code for running uwsgi.
=> refactor(profiling/uwsgi): reusable run uwsgi for tests

docs/integrations.rst
Since WSGI was merged a checklist item was added to the integration checklist (https://github.com/DataDog/dd-trace-py/pull/1979) to make sure this doesn't happen again.
=> Add WSGI to integration docs

ddtrace/internal/writer.py
There is no need to have this defined twice.
=> refactor(writer): use the PeriodicWorkerThread started attribute

ddtrace/internal/agent.py, ddtrace/tracer.py, releasenotes/notes/tracer-200a66ebb04f6cb0.yaml, tests/profiling/test_profiler.py, tests/tracer/test_agent.py
This centralizes the agent configuration into a single module which can
be shared across the library. It also changes the environment variable
look ups to be done at runtime as opposed to import-time.
(Changes ported from #1848 and #2041)
=> refactor: move agent variables to separate module

ddtrace/internal/dogstatsd.py, ddtrace/internal/runtime/runtime_metrics.py, ddtrace/tracer.py, tests/__init__.py, tests/commands/ddtrace_run_dogstatsd.py, tests/tracer/runtime/test_runtime_metrics.py, tests/tracer/test_tracer.py
The tracer initializes a single dogstatsd client and shares it between the two worker threads. This would better be handled separately. The flush interval for the runtime metrics worker is also decoupled from the tracer and exposed as an environment variable.
=> refactor(tracer): separate dogstatsd for AgentWriter and RuntimeWorker

ddtrace/contrib/django/conf.py, tests/contrib/django/test_django_migration.py
Pulled out of #1848 since these attributes are being removed.
=> django: use configure for agent settings

ddtrace/internal/writer.py
This check is done in tracer.write() already so it's redundant to do it here again.
=> writer: remove falsy spans check

ddtrace/internal/writer.py, tests/integration/test_integration.py, tests/tracer/test_writer.py
Previously the metric was emitted as both a count and a distribution
metric as described in #2018.
Based off of and follows #2049.
=> fix(writer): remove duplicate http.requests metric

ddtrace/internal/writer.py, tests/integration/test_integration.py, tests/tracer/test_writer.py
This will allow easier testing as well as better reuse as debug logging
can now use the AgentWriter to perform and introspect requests to the
Agent.
Based off of and follows #2050.
=> writer: enable flush_queue to raise

ddtrace/contrib/django/patch.py
Following #2058,  the django integration was refactored to use trace_utils' helper function which extracts and activates a distributed header's context (if enabled).
=> refactor: use trace_utils distributed header extraction in django

ddtrace/contrib/httplib/patch.py
Also add a duck type check in case the writer doesn't have an agent_url
(like when using the LogWriter).
=> httplib: use agent_url instead of internal attributes

ddtrace/profiling/profiler.py, tests/profiling/test_profiler.py
The profiler checks if collectors fail, but ignores the error and continues. In the case of `_memalloc.MemoryCollector`, the [`_memalloc` module could fail to load](https://github.com/DataDog/dd-trace-py/blob/e1ad1731be0bef70b29339a652ad5e1437c02a94/ddtrace/profiling/collector/memalloc.py#L4-L7). Since the [`RuntimeError`](https://github.com/DataDog/dd-trace-py/blob/e1ad1731be0bef70b29339a652ad5e1437c02a94/ddtrace/profiling/collector/memalloc.py#L64-L65) is [ignored](https://github.com/DataDog/dd-trace-py/blob/e1ad1731be0bef70b29339a652ad5e1437c02a94/ddtrace/profiling/profiler.py#L306-L310) the `snapshot` method can be called and [will fail](https://github.com/DataDog/dd-trace-py/blob/e1ad1731be0bef70b29339a652ad5e1437c02a94/ddtrace/profiling/collector/memalloc.py#L89) repeatedly since …
=> fix(profiling): handle failed collectors

ddtrace/internal/writer.py, tests/__init__.py, tests/integration/test_integration.py
The logging was moved around in a previous patch. Also add a regression
test for the logging.
=> fix(writer): logging request timing

tox.ini
Looks like the latest pytest-sanic release 1.7.0 broke our tests: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/5517/workflows/42be3e31-9c4c-4792-814b-1d90d1ba2a1a/jobs/509128/steps
=> tests(sanic): pin pytest-sanic version

ddtrace/tracer.py, releasenotes/notes/configure-a39313ef4fed9028.yaml, tests/tracer/test_tracer.py
Using tracer.configure() is broken when a dogstatsd configuration is given as the existing writer is not updated unless an agent configuration setting (eg. hostname, port, url) is given (which creates a new AgentWriter).
Handle the case of when a writer exists and the dogstatsd url is updated.
=> configure: fix dogstatsd configuration for existing writers

ddtrace/propagation/http.py
Precompute normalised header names to avoid repeated calls to `str.lower` in a loop.
=> perf(http): Further header extraction improvements

tests/__init__.py, tests/opentracer/conftest.py, tests/opentracer/core/test_dd_compatibility.py, tests/opentracer/core/test_span.py, tests/opentracer/core/test_tracer.py, tests/opentracer/test_tracer_asyncio.py, tests/opentracer/test_tracer_gevent.py, tests/opentracer/test_tracer_tornado.py
As per title.
Cleans up #2071 slightly
=> tests: remove explicit writer usage from opentracing tests

ddtrace/contrib/botocore/patch.py, releasenotes/notes/fix-botocore-missing-response-meta-e80c1cfb34ec0881.yaml, tests/contrib/botocore/test.py
Fixes #2116
When using `botocore.stub.Stubber` if no `ResponseMetadata` is provided in the response then our instrumentation raises a `KeyError`.
While this is not likely to happen from calling a non-stubbed version of `botocore` we should still be defensive in our instrumentation code to ensure if our expectations from `botocore` ever change we will continue to work.
- ~[ ] Library documentation is updated.~
- ~[ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).~
=> fix(botocore) Ensure the presence of ResponseMetadata key in the result

ddtrace/contrib/flask/patch.py, releasenotes/notes/flask-codes-f0841d78ec847807.yaml, tests/contrib/flask/test_request.py
This was supposed to be removed in 0.47
=> flask: remove extra_error_codes

.mergify.yml
As every PR is now labeled `automerge`, and people are now forgetting to add
the automerge label, let's change the merge rule to always automerge except
said otherwise.
=> ci(mergify): change label merge condition

ddtrace/internal/runtime/runtime_metrics.py, ddtrace/tracer.py
The tracer shouldn't have to do that itself.
=> refactor(runtime_metrics): update the tags on init

tests/tracer/test_writer.py
This covers the following lines in the writer:
https://github.com/DataDog/dd-trace-py/blob/716b2a6e90d44a42969a7697e9ead74fbd0e84c5/ddtrace/internal/writer.py#L350-L353
=> tests: add racing start test for writer

.circleci/config.yml, riotfile.py, tox.ini
This change also drops testing Flask 0.9 since that version is from 2012.
=> Move Flask and Flask-Cache tests to riot

riotfile.py
As per https://github.com/encode/databases/issues/298, sqlalchemy 1.4 removed `RowProxy` which causes `databases` to fail.
Pin sqlalchemy to 1.3.x for until the issue is resolved upstream.
=> Fix starlette tests

ddtrace/contrib/trace_utils.py, tests/tracer/test_trace_utils.py
The log is `debug`-level since `set_http_meta` will run on possibly many requests that may be impacted by this issue if it does occur. I could see an argument be made about warning/error level as well if we think that it's more likely that this would be really rare and the user should be alerted to the issue.
=> trace_utils: handle non-integer error codes

ddtrace/span.py, tests/tracer/test_span.py
As per [APMPY-511](https://datadoghq.atlassian.net/jira/software/projects/APMPY/boards/136?selectedIssue=APMPY-511), the setter for `span.duration()` was found to implicitly convert the value `duration_ns` into a float when multiplying by `1e9` to get the value in nanoseconds. Since the duration value must be an int when sending traces to the agent, this was explicitly cast.
=> Fix: Explicitly cast span.duration_ns as int when setting

ddtrace/internal/service.py, ddtrace/profiling/_periodic.py, ddtrace/profiling/profiler.py, tests/profiling/test_periodic.py
While unlikely, there's a possible race condition when starting a service
multiple times with multiple parallel threads.
=> fix(profiling): use service lock to avoid race condition on start

ddtrace/commands/ddtrace_run.py, docs/advanced_usage.rst, docs/spelling_wordlist.txt, releasenotes/notes/uwsgi-workaround-6fbfde6c19691d8b.yaml
The `ddtrace-run` script does not correctly support tracer initialization in uWSGI workers. Instead, users of the library can use a uWSGI configuration option to ensure the tracer is initialized in the uWSGI worker processes. There is upcoming work that will allow uWSGI users to use `ddtrace-run` but given the limitations of the library a workaround is being provided in the documentation.
=> docs(uwsgi): workaround for uwgi worker initialization

ddtrace/span.py, tests/tracer/test_span.py
From #2180, the mypy check to `span.py` found a missing return in the case that a duration was not set yet to a span. Although trivial, it is good practice to have explicit returns. A test case was added to ensure the `span.duration` property is None by default.
=> Added explicit NoneType return for mypy in span.duration

ddtrace/sampler.py
From #2187, it was found that the default `sample_rate` for the RateSampler and RateByServiceSampler constructors were ints while they should be a float between 0 and 1.
=> Fixed default sample_rates to be floats rather than int

ddtrace/compat.py
From #2163,  the return type for `compat.get_connection_response()` was added after it was found that `typing.TYPE_CHECK` can be used to bypass circular imports for mypy. It should be noted though that the input type for `compat.get_connection_response()` is `six.moves.http_client.HTTPConnection`, which is currently not able to be properly type hinted via mypy due to the `six` library being vendored in the tracing library.
=> Added return type hint to compat.get_connection_response()

ddtrace/span.py, releasenotes/notes/span-22c2917b9580c0e6.yaml, tests/tracer/test_span.py
With these callbacks we could eventually remove the need to specify a
tracer or context instance to ``Span``.
=> Add span on finish callbacks

ddtrace/internal/writer.py, tests/integration/test_integration.py
When reading the debug logs it wasn't clear where the traces were being sent to.
=> Add agent url to writer logs

ddtrace/utils/formats.py, docs/configuration.rst, releasenotes/notes/ddtags-space-82407d0d3f0426cd.yaml, tests/tracer/test_utils.py
=> feat: support space separated DD_TAGS value

.github/workflows/django.yml
Django's test runner doesn't offer a way to skip a specific test case. We can exclude tags, but there isn't a way to use that to disable only that one known test case.
This isn't a lovely approach, but it works. Using `sed` to add a `@skipUnless(False, "")` before the test case (We are using `skipUnless` because it is already imported in the test file).
=> Disable known failing Django tests

ddtrace/span.py
The current type annotation for `meta` is too permissive.
We can't use `Dict[typing.AnyStr, Text]` for `meta` (see https://mypy.readthedocs.io/en/stable/generics.html#type-variables-with-value-restriction).
=> chore: correct typing hints for span.meta

ddtrace/span.py, tests/tracer/test_span.py
Among all the arguments of the Span constructor, the ones bearing IDs are the most important type-wise. This change adds checks to ensure that `span_id`, `trace_id` and `parent_id` all have the expected type.
The rationale for adding the check at construction time is so that this error could be caught as soon as possible, rather than defer it to later processing stages, thus avoiding invalid entries in the processing queue.
=> fix(span): ensure ID args have the correct type

.gitlab-ci.yml
Instead of S3, this PR makes use of a multiproject pipeline to deploy to the reliability env. This should provide faster and more stable deploys.
Manually tested through gitlab
=> Use multiproject pipeline to deploy to reliability env

ddtrace/internal/dogstatsd.py
In order to make adding mypy type checking/hinting easier for `dogstatsd.py`, this unnecessary NoneType check can be removed in `parse_dogstatsd_url` since the `url` is already processed through a Nonetype/empty string check in `get_dogstatsd_client`, which is the only function calling `parse_dogstatsd_url`.
=> Refactor unnecessary NoneType check in parse_dogstatsd_url

ddtrace/opentracer/tracer.py, ddtrace/utils/__init__.py, releasenotes/notes/utils-remove-merge-dicts-9252805c864677f8.yaml
This is only used once and is really not needed.
=> refactor(utils): remove merge_dicts

tox.ini
Version 5 dropped support for Python 2.
=> ci(pylons,dogpile): limit to decorator<5

ddtrace/internal/debug.py, tests/integration/test_debug.py
Handle the following:
- tracer.writer can no longer be None
- custom trace writers
- the existing usage of AgentWriter was incorrect
=> Fix debug usage of TraceWriters

Dockerfile
Updating all versions to the latest
Making 3.9 the default Python version
Adding 3.10-dev
=> Update datadog/dd-trace-py python versions

.circleci/config.yml, riotfile.py
With 3.10 up coming we cannot use floats anymore to refer to python versions, we need to use strings.
=> Use strings for python versions in riotfile

.circleci/config.yml, tests/utils.py
riot 0.5 fixed environment variables which actually exposed a
misconfiguration we had.
The `DD_TRACE_AGENT_URL` env var needs to be passed through for tests to use the test agent
=> fix(ci): pass environment through riot

ddtrace/contrib/grpc/client_interceptor.py, releasenotes/notes/grpc-future-callback-a3cc27b11df34eef.yaml, tests/contrib/grpc/test_grpc.py
Fixes issue of unfinished spans when response is not a `grpc.Future` but has the same interface, as is the case with the base future class in google-api-core.
We should use duck-typing to support the case of `google.api_core.operation.Operation` which inherits from an internal [base class](https://github.com/googleapis/python-api-core/blob/49c6755a21215bbb457b60db91bab098185b77da/google/api_core/future/base.py#L23) rather `grpc.Future`.
=> fix(grpc): support future-like responses

ddtrace/internal/dogstatsd.py
This function actually loses typing information by returning things like port
(int) in Dict[str, str] which does not make sense.
This typing error is not typed because typing information for urlparse does not
work (yet) until we unvendor six.
=> refactor(dogstatsd): remove parse_dogstatsd_url

.circleci/config.yml, riotfile.py, scripts/build-docs, tox.ini
Migrate `tox -e docs` to `riot run docs`.
~Blocker for now is being able to do extra installs with `riot`. https://github.com/DataDog/riot/issues/104~
This isn't actually blocked because we globally install `opentracing` for all envs.
=> Move tox -e docs to riot run docs

ddtrace/profiling/profiler.py, releasenotes/notes/profiling-fix-uwsgi-empty-profiles-7dbd5fdd93dea47f.yaml, tests/profiling/exporter/test_file.py, tests/profiling/test_main.py, tests/profiling/test_uwsgi.py, tests/profiling/utils.py
In uWSGI, the current code starts in the forked process the ProfilerInstance
that has been created in the master process. That actually works fine, except
all Events are discarded by the Recorder because its `pid` attribute is not
updated: it is still the pid of the master process.
Using the `_restart_on_fork` method makes sure that the `ProfilerInstance` gets
a new `Recorder` object with the correct PID.
The test is updated to not test only for file presence, but making sure that
there is at least one sample included.
=> fix(profiling): restart the profiler on uwsgi fork

.circleci/config.yml, docker-compose.yml
The version being used as well as a bunch of others have been removed
from dockerhub for some reason: https://github.com/Grokzen/docker-redis-cluster#redis-major-version-support-and-dockerhub-availability
=> ci: bump rediscluster docker images to 6.2

Dockerfile
This PR adds Valgrind and [sirun](https://github.com/DataDog/sirun) to the dev image which we can use both for benchmarks.
=> Add valgrind and sirun to dev docker image

releasenotes/notes/depends-on-six-e9b79edbf0d169a2.yaml, setup.py
The `ensure_text` function was added in 1.12.0
=> fix(six): use first version that has ensure_text

tests/contrib/starlette/test_starlette.py
The starlette tests were not overriding the tracer instance used by
sqlalchemy for Python versions >= 3.7. This was probably done because
the sqlalchemy integration generates spans when the sqlalchemy engine is
initialized which get collected with the test helpers.
=> Use span filtering helpers for starlette tests

ddtrace/contrib/grpc/client_interceptor.py, releasenotes/notes/grpc-client-measured-span-aa043d35bfe71238.yaml, tests/contrib/grpc/test_grpc.py
Add `SPAN_MEASURED_KEY` tag to gRPC client spans.
It was present on the server span but missing on the client.
=> Add SPAN_MEASURED_KEY tag to grpc client

tests/tracer/test_context.py, tests/tracer/test_tracer.py
This helps clean up #2038. The trace building is moving out of the
context so these tests can be made into integration tests (they arguably
were already).
=> Port context trace tests

riotfile.py, tox.ini
The latest release of mysql-connector-python seems to introduce a
regression on Python 2.7 so we temporarily prevent tox from installing
it.
=> fix: avoid latest release of mysql-connector-python

ddtrace/internal/runtime/container.py, docs/spelling_wordlist.txt, releasenotes/notes/fix-container-id-cgroup-parsing-28790e02a2ac0adc.yaml, tests/tracer/runtime/test_container.py
From [issue #2314 ](https://github.com/DataDog/dd-trace-py/issues/2314), it was reported that containerIDs with preceding characters with k8 information don't get parsed correctly, i.e. in the following format:
ex: `docker-7b8952daecf4c0e44bbcefe1b5c5ebc7b4839d4eefeccefe694709d3809b6199.scope`
The reason for this was that the previous parsing rule for containerIDs relied on matching the beginning and end of the string, which would inevitably fail if there were preceding characters before the containerID itself.
To fix this, the current container regex parsing rule was changed to add a non-capture 
group for any character preceding a 64 hex-digit character sequence for task/container ID.
Note: this fix ended up breaking a pre-existing test case for invalid containerIDs with one extra …
=> Fix: container id (with preceding characters) not reporting properly

Dockerfile
The current `Dockerfile` is failing to build Python 3.10-dev due to an issue with openssl library.
Updating to `buster` (something we probably should have done awhile ago anyways) and using `libssl-dev` instead of `libssl1.0-dev` fixes the issue.
=> Fix Dockerfile install of python 3.10-dev

Dockerfile
`3.10-dev` stopped working on `debian:stretch-slim` because of libssl dependency version. Upgrading to `buster-slim` fixed installation of `3.10-dev`, but broke `psycopg2` and `mysql` due to incompatible dev versions of libmysql and libpq.
The `libpq-dev` issue is only a problem on older versions of `psycopg2` when `libpq` versioning was `X.Y.Z`, but it is now `X.Y`.
=> Fix Dockerfile, remove 3.10-dev and back to debian:stretch-slim

docs/installation_quickstart.rst
I am apparently bad at RST code blocks.
I never noticed how this was rendered locally to see that it was wrong.
The current rendering before this change: https://ddtrace.readthedocs.io/en/latest/installation_quickstart.html
=> docs: Fix code blocks

riotfile.py
mysql-connector-python has dropped support for Python 2 since 8.0.24. As
an initial measure, the dependency on this package for SQLAlchemy was
restricted for all Python versions. This change re-enables testing against
the latest release on Python 3.
=> ci(sqlalchemy): re-enable latest mysqlconnector on Python 3

ddtrace/profiling/exporter/http.py, releasenotes/notes/profiling-timeout-10s-a2468ce1444887b5.yaml
As the agent does no buffering, 2 seconds is too little for the profiling
backend.
=> fix(profiling): set back the default timeout to 10 seconds

ddtrace/contrib/celery/signals.py, ddtrace/contrib/kombu/patch.py, ddtrace/contrib/wsgi/wsgi.py
Replaced usages of HTTPPropagator in kombu, celery, wsgi with trace_utils helper for distributed tracing.
=> refactor: kombu, celery, wsgi distributed tracing to use helper

ddtrace/settings/integration.py, tests/tracer/test_settings.py
With #2358 there is no longer the need to copy integration configurations and therefore this code can be removed. This PR also supersedes #2085.
=> chore(settings): remove unused copy methods

.circleci/config.yml
This should help reduce CI runtime when there are failures. If here is an error that will cause all scenarios/Venvs from completing successfully then better to fail fast after the first one.
Note this applies to one entire Venv run, not individual test cases. So one whole Python version/dependency group will execute until the end, if there were any failures it'll stop all future runs.
=> Use riot run --exitfirst to stop a job after the first failed scenario

ddtrace/contrib/futures/__init__.py, ddtrace/monkey.py, releasenotes/notes/futures-f485da98a50c9d50.yaml
I don't see a reason for why it should not be enabled by default.
=> Enable futures integration by default

.circleci/config.yml, riotfile.py, tests/profiling/conftest.py, tox.ini
Coverage is being disabled to allow the CI to finish test runs. At the moment of making this change, the coverage tool tries to analyse .so files from the library and fails with an encoding error.
=> ci(coverage): disable coverage

ddtrace/monkey.py, releasenotes/notes/fix-monkey-patch-on-import-7bbf81bcd2a86f11.yaml
The fix affects elasticsearch in particular. The wrong integration name was being used when patching-on-import a module that was already loaded. Fixes #2272.
=> fix(monkey): use correct integration name when patching-on-import a module that is already loaded

ddtrace/contrib/mysql/patch.py, ddtrace/contrib/mysqldb/patch.py, ddtrace/contrib/psycopg/patch.py, ddtrace/contrib/pymysql/patch.py, ddtrace/contrib/pyodbc/patch.py, ddtrace/contrib/sqlite3/patch.py, ddtrace/settings/integration.py, releasenotes/notes/dbapi2-deprecate-analytics-config-ececae6e9274f852.yaml, tests/tracer/test_settings.py
As part of the effort of deprecating the `dbapi2` configuration, this change deprecates configuring analytics via the `dbapi2` generic configuration.
=> chore(dbapi2): deprecate analytics

riotfile.py, tox.ini
Temporary skip Flask >=2.0.0 and Jinja2 >= 3.0.0 until our integrations are compatible.
=> Skip testing Flask >=2.0.0 and Jinja2 >=3.0.0

ddtrace/tracer.py, tests/integration/test_debug.py, tests/tracer/test_tracer.py
This is done in `tracer.write()` but we should also do it here since `tracer.write()` is going to be deprecated and removed soon.
=> Add span debug logging to _on_span_finish

ddtrace/contrib/grpc/client_interceptor.py, ddtrace/contrib/grpc/utils.py, releasenotes/notes/fix-grpc-client-meta-1145db1fec07255f.yaml, tests/contrib/grpc/test_grpc_utils.py
Since #1938 we had exposed how we were not checking values before setting tags, causing `TypeError`s to be raised if the value was being set to `None`. This PR adds checks around those cases where the value can be `None`.
=> fix(grpc): handle None values for tags

.dd-ci/README.md, .dd-ci/ci-app-spec.json
The CI App uses the `ci-app-spec.json` file to generate a dynamic HTML page with tags supported by each tracer in the context of the CI App. As the Python tracer is currently updating the pytest plugin to add more tags in an ongoing effort to reach feature parity with the other tracers, this will help visualize the progress of the ongoing work.
=> Pytest: Enable CI App feature tracking

releasenotes/notes/remove-apptypes-76c78d46c1792863.yaml
Having it be `other` makes it less visible and could go unnoticed since
it should be an upgrade note.
=> Change AppTypes removal releasenote type to upgrade

.github/workflows/build_deploy.yml
When Github actions is unavailable or delayed then we may opt to upload
some wheels manually. When this is the case we probably won't build all
the wheels manually and will still rely on the action.
Setting `skip_existing` will prevent the deploy from erring out early
due to a duplicate wheel being present which will ensure that the rest
of the wheels will be uploaded.
=> ci: add skip_existing option

setup.py
Since cythonize is called explicitly where we want, there's no need to do it
magically with Cython `build_ext` function.
The latter might break other extension types.
=> chore(setup): remove Cython build_ext usage

ddtrace/context.py, tests/integration/test_integration.py
The lock in the context object was not reentrant. There was a regression in #2038
where a debug log line was added to `close_span`. If logs injection was enabled
then it was possible to deadlock when parent spans closed before child spans.
The fix is to make the context lock reentrant.
=> Fix context reentry deadlock

.github/workflows/flask.yml
This PR bumps flask to 1.1.4 on the Flask test suite. The CI job was failing because tests are broken upstream for Flask 1.1.2.
=> fix(ci): bump Flask test suite to 1.1.4

ddtrace/internal/writer.py, releasenotes/notes/tracer-upload-retry-d60310aa6c91059d.yaml, tests/tracer/test_writer.py
This change introduces a Fibonacci retry policy (with jitter) to the agent writer to mitigate networking issues (e.g. timeouts, broken pipes, ...), similar to what the profiler does already.
Memory usage might increase up to an extra payload buffer size, meaning that occasionally the tracer would require about 8MB more memory for processing. That is because the buffer will start filling up again while the writer retries flushing the previous payload.
Resolves #1413.
=> feat(writer): add retry logic

ddtrace/internal/periodic.py, ddtrace/internal/runtime/runtime_metrics.py, ddtrace/internal/service.py, ddtrace/internal/writer.py, ddtrace/profiling/collector/memalloc.py, ddtrace/profiling/collector/stack.pyx, ddtrace/profiling/collector/threading.py, ddtrace/profiling/profiler.py, ddtrace/profiling/scheduler.py, ddtrace/tracer.py, tests/profiling/test_profiler.py, tests/tracer/test_periodic.py, tests/tracer/test_service.py, tests/tracer/test_writer.py
This makes the base Service class entirely thread safe for starting and
stopping services.
Service must now implement a _{start,stop}_service method which does the heavy
work and is guaranteed to run only once in a thread-safe manner.
=> refactor(service): make Service class thread-safe
