ddtrace/contrib/cassandra/session.py, tests/contrib/cassandra/test.py
cassandra backwards compatibility test.
=> cassandra: add backwards compatibility test

circle.yml
=> [ci] enabling Agent integration tests

ddtrace/contrib/elasticsearch/patch.py
Changed the non deprecated code
=> Elasticsearch to the non deprecated code

ddtrace/monkey.py
autopatch mysql.
was an ommision.
=> mysql: autopatch mysql

tests/test_integration.py
Integration tests related to: https://github.com/DataDog/dd-trace-py/pull/176
=> [core] add test integration for boolean error value

ddtrace/contrib/celery/__init__.py, ddtrace/contrib/celery/app.py, ddtrace/contrib/celery/patch.py, ddtrace/contrib/celery/task.py, ddtrace/contrib/celery/util.py, ddtrace/monkey.py, docs/index.rst, tests/contrib/celery/test_app.py, tests/contrib/celery/test_integration.py, tests/contrib/celery/test_task.py, tests/contrib/celery/test_utils.py, tests/contrib/celery/utils.py, tests/test_tracer.py
Related to #135. It's only a minor set of changes related to documentation and how the application is instrumented. Adds some tests using functions with arguments so that we're sure arguments are properly passed.
=> [celery] minor changes

tests/contrib/bottle/test.py
Follow-up for #199 that adds a regression test.
=> [bottle] refactoring tests to prevent tracer regression

ddtrace/span.py, ddtrace/tracer.py, docs/index.rst
* Docs for ``start_span`` method
* Overall improvements
* API section moved at the bottom of the doc
* Created the *Advanced usage* section
=> Improving current documentation

ddtrace/compat.py, ddtrace/compat_async.py, ddtrace/contrib/asyncio/__init__.py, ddtrace/contrib/asyncio/helpers.py, ddtrace/tracer.py, tests/contrib/aiohttp/app/web.py, tests/contrib/aiohttp/test_middleware.py, tests/contrib/asyncio/test_helpers.py, tests/contrib/asyncio/test_tracer.py, tests/contrib/asyncio/test_tracer_safety.py, tests/contrib/asyncio/utils.py, tox.ini
Changes to the ``asyncio`` contrib module, to make it slightly better. Also:
* add support for Python 3.4
=> [asyncio] improving asynchronous support for the stdlib module

docker-compose.yml, tests/contrib/cassandra/test.py, tox.ini
* update all tested libraries
* add to the test matrix python 3.5 and 3.6 (according to library support)
=> upgrade all tested libraries

ddtrace/contrib/django/__init__.py
Docs for Django `TAGS` setting. Related to #159
=> [django] documentation for Django TAGS setting

ddtrace/contrib/pyramid/trace.py, tests/contrib/pyramid/test_pyramid.py, tests/contrib/pyramid/test_pyramid_autopatch.py
This PR adds the HTTP request method to the resource name of Pyramid trace span.
=> Add request method to Pyramid trace span resource name.

ddtrace/monkey.py
To distinguish if a module is not loaded or if the integration is not available, the `monkey` module uses a `PatchException`. In that way developers have better details especially when using the `DEBUG` level.
Any other exception raised from the module `patch()`, is handled as before.
```python
import logging
logger = logging.getLogger()
logger.setLevel(logging.DEBUG)
from ddtrace import patch, patch_all
patch_all(fake_integration=True)
```
**Before the patch**
```
DEBUG:root:failed to patch mysql: 'module' object has no attribute 'patch'
DEBUG:root:failed to patch fake_integration: No module named fake_integration
DEBUG:root:failed to patch cassandra: 'module' object has no attribute 'patch'
DEBUG:root:failed to patch redis: 'module' object has no attribute 'patch'
DEBUG:root:failed to …
```
=> [core] patch loader raises PatchException

ddtrace/contrib/pylons/middleware.py, tests/contrib/pylons/test_pylons.py
=> Fix pylons bug when getting wrong formatted https status code

ddtrace/contrib/aiobotocore/__init__.py, ddtrace/contrib/aiohttp/__init__.py, ddtrace/contrib/aiopg/__init__.py, ddtrace/contrib/asyncio/__init__.py, ddtrace/contrib/asyncio/helpers.py, ddtrace/contrib/django/__init__.py
Updates documentation for some modules after community contributions!
=> [docs] update documentation after latest changes

ddtrace/contrib/asyncio/__init__.py, ddtrace/contrib/django/__init__.py, ddtrace/contrib/gevent/__init__.py, ddtrace/contrib/sqlalchemy/__init__.py, ddtrace/contrib/tornado/__init__.py, ddtrace/span.py, docs/index.rst
Updates docs and docstrings to be more clear.
=> [docs] be more explicit in docs

ddtrace/contrib/aiobotocore/patch.py, ddtrace/contrib/boto/patch.py, ddtrace/contrib/botocore/patch.py
Small fix on the name of the app
=> Change ServiceMetadata app for AWS

ddtrace/contrib/pyramid/patch.py, tests/contrib/pyramid/test_pyramid_autopatch.py
This fix the bug reported in #311
=> Fix relative imports in pyramid

tests/contrib/cassandra/test.py
Truncate is a very expensive operation.
This reduced the runtime of each cassandra test environment from ~40seconds to ~15seconds on my machine.
=> [Cassandra] Do not Truncate table after each test

ddtrace/contrib/celery/util.py
Signed-off-by: Mike Fiedler <miketheman@gmail.com>
=> [celery] Enable setting service name from env

ddtrace/api.py, ddtrace/constants.py, ddtrace/context.py, ddtrace/contrib/aiohttp/middlewares.py, ddtrace/contrib/asyncio/helpers.py, ddtrace/contrib/asyncio/provider.py, ddtrace/ext/distributed.py, ddtrace/sampler.py, ddtrace/span.py, ddtrace/tracer.py, ddtrace/writer.py, tests/contrib/aiohttp/app/web.py, tests/contrib/aiohttp/test_middleware.py, tests/contrib/celery/test_task.py, tests/test_api.py, tests/test_context.py, tests/test_encoders.py, tests/test_integration.py, tests/test_sampler.py, tests/test_span.py
Follow-up to #325 which isolates the generic, core features, from contrib specific enhancements which may make sense without priority sampling.
=> [distributed sampling] introduce new priority sampler for distributed sampling

ddtrace/contrib/pyramid/trace.py, tests/contrib/pyramid/test_pyramid.py, tests/contrib/pyramid/test_pyramid_autopatch.py
=> Keep request as part of pyramid render kwargs

.circleci/config.yml
=> [ci] update CircleCI config

ddtrace/contrib/flask/middleware.py, tests/contrib/flask/test_flask.py
If a custom resource is set in middleware, respect that and don't override it. Should fix #353
=> flask: allow custom resource names

.circleci/config.yml
=> [ci] update how docs are built

ddtrace/contrib/pyramid/__init__.py, docs/index.rst
This patch updates some docs styles for better formatting.
=> [docs] update docs syntax

.gitignore, tests/contrib/pylons/app/controllers/root.py, tests/contrib/pylons/app/lib/base.py, tests/contrib/pylons/app/lib/helpers.py, tests/contrib/pylons/app/router.py, tests/contrib/pylons/app/web.py, tests/contrib/pylons/test.ini, tests/contrib/pylons/test_pylons.py
With the previous test suite, a fake WSGI app was created. Even if tests were correctly executed, they didn't match real Pylons versions. After this change, a real Pylons app is created, and if a breaking change is present between Pylons versions, our test suite will fail.
=> [pylons] rewrite Pylons test suite

ddtrace/monkey.py
We've been using both libraries on prod for about 5 months without any problem. I believe it's time to automatically patch them
=> Botocore, boto default True

ddtrace/contrib/falcon/__init__.py, ddtrace/contrib/pyramid/__init__.py
=> [docs] minor fixes for Falcon and Pyramid

.circleci/config.yml, ddtrace/opentracer/span.py, ddtrace/opentracer/tracer.py, tests/contrib/httplib/test_httplib.py, tests/opentracer/test_tracer_asyncio.py, tests/opentracer/test_tracer_gevent.py, tests/opentracer/test_tracer_tornado.py, tox.ini
This PR introduces fixes to the opentracer tests that were broken with the compatibility PR (#497).
=> [opentracer] Fix opentracer tests

ddtrace/contrib/celery/__init__.py
Depends on #530, it updates the documentation for the new instrumentation.
=> [celery] update Celery documentation based on the new instrumentation

Rakefile
cc @palazzem our docs fail to deploy when triggered through the CI...
=> [docs] Fix docs deploy

.circleci/config.yml
The docker images used in our circle ci environment have been updated.
The following process has been adopted to decide whether to advance or not a version:
- if a newer version exists that does not introduce breaking changes based on online info and change log, then advance.
- if an official '-alpine' version exists, then use it.
=> [ci] Optimize circleci docker images

tests/contrib/boto/test.py
=> [opentracer] Add boto tests

tests/contrib/botocore/test.py
Add botocore OpenTracing test.
=> [opentracer] Add botocore test

tests/contrib/celery/test_task.py
=> [opentracer] Add celery test

tests/contrib/django/test_middleware.py
=> [opentracer] Add django test

tests/contrib/flask/test_flask.py
=> [opentracer] Add flask test

tests/contrib/flask_cache/test.py
Add flask_cache OpenTracing test.
=> [opentracer] Add flask_cache test

docs/advanced_usage.rst
This PR fixes a spelling mistake in the docs.
=> [docs] Doc improvement

tests/contrib/asyncio/test_tracer.py
=> [opentracer] Add asyncio tests

tests/contrib/aiopg/test_aiopg.py
=> [opentracer] Add aiopg tests

tests/contrib/gevent/test_tracer.py
=> [opentracer] Add gevent tests

tests/contrib/aiohttp/test_middleware.py
=> [opentracer] Add aiohttp tests

tests/contrib/cassandra/test.py
Add cassandra OpenTracing test.
=> [opentracer] Add cassandra tests

tests/contrib/futures/test_propagation.py
=> [opentracer] Add futures test

tests/contrib/bottle/test.py
=> [opentracer] Add bottle tests

tests/contrib/falcon/test_suite.py
=> [opentracer] Add falcon test

tests/contrib/httplib/test_httplib.py
=> [opentracer] Add httplib test

tests/contrib/mysqldb/test_mysql.py
=>  [opentracer] Add mysqldb test

tests/contrib/psycopg/test_psycopg.py
=> [opentracer] Add psycopg test

tests/contrib/pylibmc/test.py
=> [opentracer] Add pylibmc test

tests/contrib/pylons/test_pylons.py
=> [opentracer] Add pylons test

tests/contrib/pymongo/test.py
=> [opentracer] Add pymongo test

tests/contrib/sqlalchemy/mixins.py
Add sqlalchemy OpenTracing test.
=> [opentracer] Add sqlalchemy test

tests/contrib/sqlite3/test_sqlite3.py
=> [opentracer] Add sqlite3 test

tests/contrib/tornado/test_tornado_web.py
=> [opentracer] Add tornado test

.circleci/config.yml, tests/contrib/mongoengine/test.py, tox.ini
Add mongoengine OpenTracing test. Also adds the missing CI job for mongoengine.
=> [opentracer] Add mongoengine test

tests/contrib/aiobotocore/test.py, tests/contrib/boto/test.py, tests/contrib/botocore/test.py, tests/contrib/django/test_middleware.py, tests/contrib/falcon/test_suite.py, tests/contrib/pylons/test_pylons.py
Span.span_type is set in the code but not checked in tests. This PR adds tests for some untested contribs
=> Add Span.span_type tests

.circleci/config.yml
This PR condenses the test commands used by autopatch tests.
=> [ci] Reorganize autopatch test calls

.circleci/config.yml, tests/contrib/__init__.py, tests/contrib/gevent/test_patch.py, tests/contrib/requests/test_patch.py, tests/contrib/test_patch_runner.py, tox.ini
This branch was separated out in case it ended up growing to be too unrelated to #681. However after discussions with @brettlangdon and @majorgreys we concluded that it makes sense to include this logic in #681.
=> [tests] Add rough patch test runner

.circleci/config.yml
A couple resource_class declarations were missed with #710.
=> [circleci] add missing resource class declarations

ddtrace/contrib/elasticsearch/patch.py
This PR fixes an issue we saw in staging.
=> [elasticsearch] add alias for default _perform_request

ddtrace/bootstrap/sitecustomize.py
Fixes minor issue with logging errors when executing `ddtrace-run` with debug mode.
=> Patch logging earlier for ddtrace-run

ddtrace/helpers.py, ddtrace/tracer.py, tests/test_helpers.py, tests/test_tracer.py
=> [core] Guard against when there is no current call context

.circleci/config.yml
This is a first step toward making more generic the CircleCI scenario running.
The ultimate goal being to be able to simplify tox and CircleCI scenario
listing and running.
=> [tests] Use a macro to persist result to workspace in CircleCI

tox.ini
The API changed and we don't support it yet.
=> Cap algoliasearch to <2

tests/opentracer/test_tracer.py
A large number of tests is import time and using it whereas it's not needed.
This refactor `time` usage, leaving only the `time.sleep` calls that are
actually needed.
=> [opentracer] Refactor time usage

tests/test_sampler.py
This PR applies #945 to `RateByServiceSamplerTest`.
=> [tests] increase deviation for sampler by service test

tests/contrib/aiohttp/test_request_safety.py
The current code might fail because the loop is only executed once; if one of the thread is late, its request won't be processed.
The call to `t.join()` has a timeout and has basically no effect here. It's now moved at the end of the waiting loop to be sure all threads are completed.
Since pytest would not catch an assertion failure in a thread, the assertion check for replies is moved to the main thread.
=> tests/aiohttp: yield back to the loop until complete

ddtrace/api.py, tests/test_api.py
This include one commit of top https://github.com/DataDog/dd-trace-py/pull/941 which should be merged first.
=> Handle HTTP timeout in API writer

tests/commands/test_runner.py, tests/util.py
This removes unused code and move inject_sitecustomize to where it is actually
used.
=> tests/util: remove unused code

ddtrace/tracer.py
This should make the code a bit clearer
=> tracer: use constant rather than its value

.circleci/config.yml
Looking for other suggestions on how to handle this better, but this seemed like a quick fix.
=> Use Python 3 for test_build job

ddtrace/context.py
=> context: avoid iterating over span list

ddtrace/context.py
context: count the number of closed spans
context: only try to find unfinished_spans if we're debugging
=> Pull request for 0.27-perf-fix

ddtrace/contrib/django/__init__.py
Fix capitalization of `DEBUG` and clarify it's the Django setting.
=> Improve Django docs

ddtrace/internal/rate_limiter.py, tests/internal/test_rate_limiter.py
This is the rate limiter from #1020, no reason it has to be tied to that PR and it can possibly be used in other places as well (not specific to the sampler).
=> [internal] Add generic rate limiter

ddtrace/context.py, ddtrace/contrib/pyramid/trace.py, ddtrace/sampler.py, ddtrace/span.py, ddtrace/tracer.py, tests/contrib/aiohttp/app/web.py, tests/test_tracer.py
This attribute is actually public, don't lie about it.
=> span: remove tracer property function

ddtrace/contrib/httplib/__init__.py
=> [httplib] make docs consistent with implementation

ddtrace/utils/sizeof.py, tests/test_utils.py
=> utils/sizeof: fix iteration on slot class if attribute is unset

ddtrace/contrib/elasticsearch/__init__.py, ddtrace/contrib/elasticsearch/elasticsearch.py, ddtrace/contrib/elasticsearch/patch.py, ddtrace/contrib/elasticsearch/transport.py, tox.ini
Add testing for `elasticsearch6` module.
=> [elasticsearch] Add support for elasticsearch6 module

ddtrace/internal/writer.py, tests/internal/test_writer.py
The current rate of sending metrics every 1 second is too heavy and impacts the
performance. Let's do this only every 10 seconds by default, so we're sure our
perf impact is quite small.
=> writer: send statistics less often, disable by default

ddtrace/span.py, tests/test_span.py
We need to make sure this is an integer, not a float.
=> span: fix start time setter

ddtrace/contrib/grpc/client_interceptor.py, tests/contrib/grpc/test_grpc.py
The integration currently causes `grpc.FutureCancelledError` to be raised if the grpc error being handled is due to a cancelled future.
=> grpc: handle cancelled futures

conftest.py, docker-compose.yml, docs/conf.py, pyproject.toml, setup.py
`setup.py`, `conftest.py`, and `docs/conf.py`.
=> Start black formatting some files

ddtrace/_worker.py, ddtrace/internal/writer.py, tests/test_tracer.py, tests/test_worker.py
=> fix(writer): start thread as late as possible

.circleci/config.yml
Update to config version `2.1`, add custom `commands`, and `executors` and try to refactor the jobs a bit to make them easier to maintain.
Also added all docker images as aliases to the top of the file to make them easier to find and update. The same for docker images, storing common definitions in aliases.
=> ci: rework .circleci/config.yml

ddtrace/contrib/django/__init__.py
Fix for migrate doc from ddtrace<=0.33.0
=> fix doc for migrate from ddtrace<=0.33.0

.circleci/config.yml
=> Build and publish wheels for the staging branch

scripts/build-dist, scripts/mkwheelhouse
This build not only the sdist but also the wheels when calling mkwheelhouse.
=> ci: build and push wheels when releasing

.circleci/config.yml
This seems to help speed things up a bit.
=> ci: use medium resource class

ddtrace/encoding.py, ddtrace/internal/writer.py, ddtrace/tracer.py, tests/internal/test_writer.py, tests/test_encoders.py
Adds LogWriter support to the the tracer.
Will change default writer when it detects a lambda environment. For the moment, LogWriter doesn't support dogstats, (this might not be possible, since we don't have an agent).
=> Log exporter support

docs/basic_usage.rst
=> docs: fix profiler example and more details about API usage

scripts/build-dist
=> build: use latest manylinux images

scripts/build-dist
manylinux1 is old, deprecated and now unsupported security-wise.
Bump our build env to manylinux2010.
=> feat(wheels): update to manylinux2010

ddtrace/commands/ddtrace_run.py, ddtrace/contrib/logging/__init__.py
Update the logging integration docs for the new required attributes `dd.service` and `dd.env`, `dd.version`
=> logging: update documentation

ddtrace/profiling/exporter/http.py, tests/profiling/exporter/test_http.py
This is slightly higher level than http_client and supports features such as
the `HTTP_PROXY` environment variable.
=> feat(profiling): replace http_client by urllib for uploading

ddtrace/profiling/collector/stack.pyx
=> profiler: remove unused imports

ddtrace/profiling/exporter/http.py, tests/profiling/exporter/test_http.py
=> fix(profiling/http): make sure tags are UTF-8 encoded

ddtrace/contrib/aiohttp/__init__.py, ddtrace/contrib/django/__init__.py, ddtrace/contrib/falcon/__init__.py, ddtrace/contrib/flask/__init__.py, ddtrace/contrib/molten/__init__.py, ddtrace/contrib/pyramid/__init__.py, ddtrace/contrib/tornado/__init__.py, docs/advanced_usage.rst
Changed instances of `Trace Search & Analytics` to `App Analytics` per request on the docs JIRA board.
=> Updated to pypi advance usage docs

ddtrace/__init__.py, ddtrace/compat.py, ddtrace/opentracer/tracer.py, ddtrace/span.py, pyproject.toml, tests/contrib/asyncio/test_tracer.py, tox.ini
=> Upgrade flake8 to 3.8 + black ddtrace{,.span}

.circleci/config.yml
not sure why this was added in the first place 🤔
=> circleci: remove unused busybox

Dockerfile
We don't support nor use Python 3.4 anymore, remove it.
=> ci: update Python versions

ddtrace/contrib/elasticsearch/__init__.py, ddtrace/contrib/elasticsearch/elasticsearch.py, ddtrace/contrib/elasticsearch/patch.py, ddtrace/contrib/elasticsearch/quantize.py, ddtrace/contrib/elasticsearch/transport.py, pyproject.toml, tests/contrib/elasticsearch/test.py
=> fix(elasticsearch): ensure params is a dict before urlencoding

ddtrace/contrib/grpc/server_interceptor.py, tests/contrib/grpc/hello_pb2_grpc.py, tests/contrib/grpc/test_grpc.py
=> fix(grpc): RpcMethodHandler can be None

.circleci/config.yml, ddtrace/opentracer/tracer.py, ddtrace/opentracer/utils.py, tests/opentracer/test_tracer.py
As per #838, adds support for interleaving the opentracing tracer and datadog tracer.
Thanks @JackWink!
=> feat(opentracing): support for tracer interleaving

ddtrace/profiling/collector/stack.pyx
WeakSet are actually not thread safe since copy-ing them iterate over their
internal set. We need to lock those to make sure they are not mutated during
our iteration, otherwise you'd get RuntimeError:
Exception in thread ddtrace.profiling.collector.stack:StackCollector:
File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/path/to/virtualenv/src/ddtrace/ddtrace/profiling/_periodic.py", line 48, in run
self._target()
File "/path/to/virtualenv/src/ddtrace/ddtrace/profiling/collector/__init__.py", line 21, in periodic
for events in self.collect():
File "ddtrace/profiling/collector/stack.pyx", line 408, in ddtrace.profiling.collector.stack.StackCollector.collect
File "ddtrace/profiling/collector/stack.pyx", line 276, in …
=> fix(profiling/stack): lock _WeakSet in ThreadSpanLinks

ddtrace/contrib/httplib/__init__.py, ddtrace/contrib/httplib/patch.py, tests/contrib/httplib/test_httplib.py, tests/contrib/httplib/test_httplib_distributed.py
Adds support for distributed tracing in httplib.
=> feat(httplib): support distributed tracing

ddtrace/profiling/collector/memory.py, tests/profiling/collector/test_memory.py
This rewrite the memory filtering function to filter traces faster. It also
fixes the test so it's way faster to have it passing.
=> fix(profiling): enhance memory filtering

tox.ini
This should speed things up a bit.
=> tests: don't install unnecessary deps

ddtrace/contrib/django/patch.py, tests/contrib/django/django1_app/urls.py, tests/contrib/django/django_app/urls.py, tests/contrib/django/templates/custom_dispatch.html, tests/contrib/django/test_django.py, tests/contrib/django/views.py, tests/contrib/djangorestframework/test_djangorestframework.py
Reverts DataDog/dd-trace-py#1615
=> Revert "fix(django): trace entire mro chain for django view classes"

docs/conf.py, docs/index.rst
=> docs: refer to the library as APM client

CHANGELOG.md
We really need to start using reno soon...
=> chore: update changelog with patch releases

CHANGELOG.md
Add the 0.42 changelog entries
=> chore: add 0.42 changelog entries

docs/advanced_usage.rst
Minor doc fix for code snippets.
=> docs: fix code snippet formatting for opentracing and celery

Dockerfile
=> chore: update python 3.8 and 3.7 in ddtrace/dd-trace-py

Dockerfile
Fixes the versions that were updated in #1681.
=> fix(ci): use correct Python versions

ddtrace/contrib/asgi/__init__.py
Fix docs for asgi middleware config
=> docs: fix asgi distribute tracing config

Dockerfile
Let's switch to the final Python 3.9 🎉
=> ci: upgrade Python versions

ddtrace/profiling/collector/threading.py, ddtrace/profiling/exporter/pprof.pyx, ddtrace/profiling/profiler.py, releasenotes/notes/profiling-threading-tracing-6877348333bbaa80.yaml, tests/profiling/collector/conftest.py, tests/profiling/collector/test_stack.py, tests/profiling/collector/test_threading.py, tests/profiling/exporter/test-pprof-exporter-py2.txt, tests/profiling/exporter/test-pprof-exporter.txt, tests/profiling/exporter/test_pprof.py
=> Add traces support for lock profiling

releasenotes/notes/tornado-none-bug-85faed75c859f5e5.yaml
=> chore: fix tornado release note

ddtrace/api.py, ddtrace/internal/uds.py, ddtrace/profiling/exporter/http.py, ddtrace/profiling/scheduler.py, releasenotes/notes/profiler-uds-108b876bdab8a151.yaml, tests/profiling/exporter/test_http.py, tests/tracer/test_api.py
=> feat(profiler): support UDS

.circleci/config.yml
We do this already in github actions.
=> ci: remove build wheels job from circleci

ddtrace/profiling/exporter/pprof.pyx, releasenotes/notes/fix-trace_id_lock-profiling-585779e8713144f3.yaml, tests/profiling/exporter/test-pprof-exporter-py2.txt, tests/profiling/exporter/test-pprof-exporter.txt
Backport of https://github.com/DataDog/dd-trace-py/pull/1805
=> fix(profiling): thread name and trace id were inverted in pprof exports

ddtrace/contrib/starlette/__init__.py, releasenotes/notes/fix-docs-starlette-env-var-9901a95294b40a84.yaml
Fixes 2 env vars in the documentation.
=> [Misc] Documentation fix: env var starlette distributed tracing

ddtrace/_worker.py, ddtrace/api.py, ddtrace/constants.py, ddtrace/context.py, ddtrace/encoding.py, ddtrace/filters.py, ddtrace/payload.py, ddtrace/pin.py, ddtrace/provider.py, ddtrace/sampler.py, ddtrace/tracer.py, ddtrace/util.py, pyproject.toml
It's getting way too annoying having flake8 complain about formatting on
these files which we can't autoformat.
=> format ddtrace module

ddtrace/internal/writer.py, ddtrace/tracer.py, tests/__init__.py, tests/integration/test_integration.py, tests/tracer/test_writer.py
This should conclude the writer refactor!
=> Add health metrics back

ddtrace/contrib/aiohttp/__init__.py, ddtrace/contrib/aiohttp/middlewares.py, ddtrace/contrib/aiohttp/patch.py, ddtrace/contrib/aiohttp/template.py, pyproject.toml, tests/contrib/aiohttp/app/web.py
reformat aiohttp & its tests with black
=> fix(aiohttp): format aiohttp & tests with black

ddtrace/contrib/bottle/__init__.py, ddtrace/contrib/bottle/patch.py, ddtrace/contrib/bottle/trace.py, pyproject.toml, tests/contrib/bottle/test.py, tests/contrib/bottle/test_autopatch.py, tests/contrib/bottle/test_distributed.py
reformat bottle & tests with black
=> fix(bottle): reformat bottle & tests with black

ddtrace/contrib/falcon/__init__.py, ddtrace/contrib/falcon/middleware.py, ddtrace/contrib/falcon/patch.py, pyproject.toml, tests/contrib/falcon/app/app.py, tests/contrib/falcon/app/resources.py, tests/contrib/falcon/test_autopatch.py, tests/contrib/falcon/test_distributed_tracing.py, tests/contrib/falcon/test_middleware.py, tests/contrib/falcon/test_suite.py
reformat falcon & tests with black
=> fix(falcon): reformat falcon & tests with black

ddtrace/contrib/flask/__init__.py, ddtrace/contrib/flask/helpers.py, ddtrace/contrib/flask/middleware.py, ddtrace/contrib/flask/patch.py, ddtrace/contrib/flask/wrappers.py, pyproject.toml, tests/contrib/flask/test_blueprint.py, tests/contrib/flask/test_errorhandler.py, tests/contrib/flask/test_flask_helpers.py, tests/contrib/flask/test_hooks.py, tests/contrib/flask/test_idempotency.py, tests/contrib/flask/test_middleware.py, tests/contrib/flask/test_request.py, tests/contrib/flask/test_signals.py, tests/contrib/flask/test_static.py, tests/contrib/flask/test_template.py, tests/contrib/flask/test_views.py, tests/contrib/flask/web.py
reformat flask & tests using black
=> fix(flask): reformat flask & tests using black

ddtrace/contrib/httplib/__init__.py, ddtrace/contrib/httplib/patch.py, pyproject.toml, tests/contrib/httplib/test_httplib.py, tests/contrib/httplib/test_httplib_distributed.py
reformat httplib & tests with black
=> fix(httplib): reformat httplib & tests with black

ddtrace/contrib/molten/wrappers.py, pyproject.toml, tests/contrib/molten/test_molten.py, tests/contrib/molten/test_molten_di.py
reformat molten & tests with black
=> fix(molten): reformat molten & tests with black

pyproject.toml, tests/contrib/pyramid/__init__.py, tests/contrib/pyramid/app/web.py, tests/contrib/pyramid/test_pyramid.py, tests/contrib/pyramid/test_pyramid_autopatch.py
reformat pyramid tests with black (pyramid already formatted with black)
=> fix(pyramid): reformat pyramid tests with black (pyramid already formatted with black)

ddtrace/contrib/requests/__init__.py, ddtrace/contrib/requests/constants.py, ddtrace/contrib/requests/legacy.py, ddtrace/contrib/requests/patch.py, ddtrace/contrib/requests/session.py, pyproject.toml, tests/contrib/requests/test_requests.py, tests/contrib/requests/test_requests_distributed.py
reformat requests & tests with black
=> fix(requests): reformat requests & tests with black

.circleci/config.yml, docker-compose.yml, tests/integration/test_debug.py, tests/integration/test_integration.py, tox.ini
- Agent v5 is still supported
- Introduce the test agent for future snapshotting tests
- Add latest agent version
Pulls the changes out of #1781
=> ci: test with multiple agents

tox.ini
Looks like our CI is now using the new pip resolver which is exposing several issues with our test dependencies
=> Fix dependency issues

ddtrace/contrib/aiohttp/middlewares.py, ddtrace/contrib/trace_utils.py, releasenotes/notes/feature-aiohttp-23084fcf8e34ad0a.yaml, tests/contrib/aiohttp/app/web.py, tests/contrib/aiohttp/test_request.py
Store request and response headers in the aiohttp integration using the new http helper function.
=> feat(aiohttp): store request and response headers

ddtrace/contrib/molten/patch.py, ddtrace/contrib/trace_utils.py, releasenotes/notes/feature-molten-041abc52f37eed37.yaml, tests/contrib/molten/test_molten.py
Store request headers in the molten integration using the new http helper function.
=> feat(molten): store request headers

ddtrace/contrib/pyramid/trace.py, ddtrace/contrib/trace_utils.py, releasenotes/notes/feature-pyramid-aa3d4c3361861753.yaml, tests/contrib/pyramid/app/web.py, tests/contrib/pyramid/test_pyramid.py
Store request and response headers in the pyramid integration using the new http helper function.
=> feat(pyramid): store request and response headers

docs/installation_quickstart.rst, releasenotes/notes/current-span-reset-a860bbbad3acda5c.yaml, releasenotes/notes/django-request-uri-safe-guards-fdd8bd664374ded1.yaml, releasenotes/notes/django-view-mro-check-782374fb9c427305.yaml, releasenotes/notes/fix-aiobotocore-9eeac808a3bf0f63.yaml, releasenotes/notes/fix-elasticsearch-a3f89a915ccc36c4.yaml, releasenotes/notes/fix-span-type-web-20122b5c57c50341.yaml
Found a few things when skimming the documentation and release notes before the release.
=> v0.45 documentation fixes

ddtrace/profiling/collector/_memalloc.c, ddtrace/profiling/collector/_memalloc_tb.c
This never fails, but who knows.
=> fix(profiling/memalloc): check memalloc_tb_init return code

docker-compose.yml
Skip mounting individual files in docker-compose
=> Skip mounting individual files in docker-compose

.circleci/config.yml, .gitignore, scripts/run-tox-scenario, tox.ini
Store JUnit XML test results from pytest
https://circleci.com/docs/2.0/collect-test-data/
=> Store JUnit XML test results from pytest

ddtrace/internal/runtime/container.py, pyproject.toml, tests/tracer/runtime/test_container.py
This has the upside of supporting e.g. __eq__ for free.
=> refactor(runtime): rewrite container with attrs

.circleci/config.yml, riotfile.py, tests/benchmarks/test_encoding.py, tests/benchmarks/test_span_id.py, tests/benchmarks/test_tracer.py, tests/profiling/collector/test_stack.py, tox.ini
I also shifted a few of the files around, since by default we weren't running all of the benchmarks.
=> Use Riot to run benchmarks

ddtrace/profiling/exporter/http.py, ddtrace/profiling/profiler.py, releasenotes/notes/profiling-tags-api-f4d732d3c31ee2cf.yaml, tests/profiling/exporter/test_http.py, tests/profiling/test_profiler.py
=> feat(profiling): allow to pass tags

ddtrace/profiling/collector/_memalloc.c, ddtrace/profiling/collector/_memalloc_tb.c, ddtrace/profiling/collector/_memalloc_tb.h, ddtrace/profiling/collector/_utils.h
This refactors the current traceback list into array where utility functions
are automatically generated from macros.
=> refactor(profiling/memalloc): add array handling macros

.github/PULL_REQUEST_TEMPLATE/integration.md
Clarify a few sections and update with trace utils that have been added.
=> Integration PR template updates

tests/tracer/test_tracer.py
Pulled out of #1936. Make sure all started spans are finished.
=> Add and fix-up a few tracer tests

tests/contrib/requests/test_requests_distributed.py
=> requests: remove context dependence from tests

tests/contrib/aiohttp/test_request_safety.py
=> aiohttp: remove context dependence in tests

ddtrace/contrib/tornado/__init__.py, ddtrace/contrib/tornado/application.py, ddtrace/contrib/tornado/compat.py, ddtrace/contrib/tornado/constants.py, ddtrace/contrib/tornado/decorators.py, ddtrace/contrib/tornado/handlers.py, ddtrace/contrib/tornado/patch.py, ddtrace/contrib/tornado/stack_context.py, ddtrace/contrib/tornado/template.py, pyproject.toml, tests/contrib/tornado/test_config.py, tests/contrib/tornado/test_executor_decorator.py, tests/contrib/tornado/test_safety.py, tests/contrib/tornado/test_stack_context.py, tests/contrib/tornado/test_tornado_template.py, tests/contrib/tornado/test_tornado_web.py, tests/contrib/tornado/test_wrap_decorator.py, tests/contrib/tornado/utils.py, tests/contrib/tornado/web/app.py, tests/contrib/tornado/web/compat.py, tests/contrib/tornado/web/uimodules.py
Going to be touching these files with some of the context changes so
it's a good time to format them first.
=> chore: format tornado

.circleci/config.yml, tests/contrib/psycopg/test_psycopg.py, tests/snapshots/tests.contrib.psycopg.test_psycopg.test_composed_query_encoding.snap
Added snapshot test for psycopg for encoding tests.
=> tests(psycopg2): add encoding test

tests/profiling/collector/test_stack.py
This test can fail from time to time since there's a race condition. This makes
sure we wait enough time, whatever that is, to have the event waited for.
=> test(profiling): fix flakyness for test_ignore_profiler_gevent_task

ddtrace/internal/writer.py, tests/tracer/test_writer.py
This ports the existing test from test_api to the new writer code to make sure
we handle those cases correctly.
This only test the lower layer for now; more test to see if errors are
correctly caught and handled cannot be done easily as the datadog logger has a
rate limit that can't be easily disabled.
=> test(writer): test writer against real API endpoint

ddtrace/contrib/django/patch.py
Not really a big deal as unpatching is an internal API.
=> django: fix unpatching

tests/tracer/test_tracer.py
This is helpful with #1848 to ensure functionality doesn't change
=> tests: add partial configure test case

ddtrace/ext/cassandra.py, ddtrace/ext/db.py, ddtrace/ext/elasticsearch.py, ddtrace/ext/errors.py, ddtrace/ext/http.py, ddtrace/ext/kombu.py, ddtrace/ext/memcached.py, ddtrace/ext/mongo.py, ddtrace/ext/net.py, ddtrace/ext/sql.py, ddtrace/ext/system.py, pyproject.toml
=> chore: format ext module

ddtrace/contrib/flask_cache/__init__.py, ddtrace/contrib/flask_cache/tracers.py, ddtrace/contrib/flask_cache/utils.py, pyproject.toml, tests/contrib/flask_autopatch/test_flask_autopatch.py, tests/contrib/flask_cache/test.py, tests/contrib/flask_cache/test_utils.py, tests/contrib/flask_cache/test_wrapper_safety.py
=> chore: format flask-cache and tests

ddtrace/internal/writer.py, tests/__init__.py, tests/contrib/aiopg/test.py, tests/contrib/bottle/test.py, tests/contrib/bottle/test_autopatch.py, tests/contrib/flask/test_middleware.py, tests/contrib/psycopg/test_psycopg.py, tests/contrib/pymongo/test.py, tests/contrib/pyramid/utils.py, tests/contrib/sqlalchemy/mixins.py, tests/contrib/sqlite3/test_sqlite3.py
Once upon a time services had to be sent individually to the Agent.
=> chore: remove writer services

ddtrace/internal/writer.py
This was introduced in https://github.com/DataDog/dd-trace-py/pull/2051
=> refactor(writer): remove unneeded reraise usage

ddtrace/profiling/collector/_memalloc.c, ddtrace/profiling/collector/_memalloc_heap.c, ddtrace/profiling/collector/_utils.h, tests/profiling/collector/test_memalloc.py
This changes the fixed heap sample size to use a geometric distribution rather
than a fixed sample size. That gives some jitter to the heap profiler and a
long term better accuracy of the generated sample.
=> feat(profiling/memalloc): use a geometric distribution to randomize heap samples

ddtrace/filters.py, docs/advanced_usage.rst, tests/tracer/test_filters.py
=> Add TraceFilter abstract base class

ddtrace/contrib/botocore/__init__.py, ddtrace/contrib/botocore/patch.py, pyproject.toml, tests/contrib/botocore/test.py
=> chore(botocore): Format botocore

tests/__init__.py, tests/conftest.py, tests/tracer/test_sampler.py, tests/tracer/test_trace_utils.py, tests/tracer/test_tracer.py
Pulls the main test util changes from #2071
=> refactor(tests): testing utils

docs/basic_usage.rst
"catching" didn't read quite right... "capturing" is probably more appropriate.
=> Tweak wording

ddtrace/internal/writer.py, ddtrace/tracer.py, tests/tracer/test_tracer.py, tests/tracer/test_writer.py
Also implement the methods on LogWriter.
=> Add TraceWriter abstract base class

.github/PULL_REQUEST_TEMPLATE/integration.md
=> docs: add test helpers to integration checklist

tests/profiling/collector/test_memalloc.py
This test barely fails, but it did a couple of times.
=> test(profiling): reduce sample size for test_heap_collector

ddtrace/monkey.py
The flask tests were failing in #2142 and #2139...
=> Fix flask patch on import string

ddtrace/contrib/django/patch.py, ddtrace/contrib/django/utils.py
This should give a slight perf boost by avoiding the expensive set_tag
method.
=> django: use _set_str_tag where possible

tests/contrib/tornado/test_config.py
The current test uses a DummyTracer/DummyWriter which strays from real world usage
=> tests(tornado): use real tracer for configuration tests

.circleci/config.yml, ddtrace/contrib/mako/__init__.py, ddtrace/contrib/mako/constants.py, ddtrace/contrib/mako/patch.py, pyproject.toml, riotfile.py, tests/contrib/mako/test_mako.py, tox.ini
Black format Mako integration and tests.
Move Mako from Tox to Riot.
=> Black and Riot mako

docs/installation_quickstart.rst
=> docs: add note about pip version requirement

tests/contrib/botocore/test.py
This change adds a test case for #2204 to ensure that the `params.Records` argument is excluded from the span tags.
=> test(botocore): add test case for firehose args

ddtrace/internal/writer.py
This is a breaking change which we're going to make at a later date.
=> Revert writer.write argument change

ddtrace/tracer.py
This isn't something we want to make public yet.
=> Make processor private on Tracer

ddtrace/contrib/pymongo/__init__.py, ddtrace/contrib/pymongo/client.py, ddtrace/contrib/pymongo/parse.py, ddtrace/contrib/pymongo/patch.py, pyproject.toml, tests/contrib/pymongo/test.py, tests/contrib/pymongo/test_spec.py
=> style(pymongo): format pymongo

ddtrace/internal/dogstatsd.py, ddtrace/internal/writer.py, ddtrace/tracer.py
- type the writer initializers
- type the dogstatsd module
=> Add type hints for internal.writer and internal.dogstatsd

.circleci/config.yml
https://about.codecov.io/security-update/
=> Use the codecov python package instead of bash uploader

.github/workflows/build_deploy.yml
Add the ability to manually dispatch a build and deploy.
=> Allow manual dispatch of deploy job

ddtrace/contrib/django/utils.py
The utility in the parse module are generic and generally expensive to
call. Its use in the Django integration has been removed in favour of
cheaper string concatenations.
=> perf(django): avoid use of parse for URL parsing

docs/installation_quickstart.rst
Add a note about necessary build dependencies for installing on Alpine.
Helps (but does not resolve) #2247 and #2262
=> Add installation note for Alpine

ddtrace/contrib/psycopg/__init__.py, ddtrace/contrib/psycopg/connection.py, ddtrace/contrib/psycopg/patch.py, pyproject.toml, tests/contrib/psycopg/test_psycopg.py
=> style(psycopg): format with black

tests/contrib/asyncio/test_helpers.py, tests/contrib/asyncio/test_propagation.py, tests/contrib/asyncio/test_tracer.py, tests/contrib/asyncio/test_tracer_safety.py, tox.ini
This introduces usage of pytest-asyncio to run the async test functions.
=> test(asyncio): replace asyncio.coroutine with async def

ddtrace/internal/runtime/runtime_metrics.py
- Class name was hardcoded rather than using the @classmethod decorator.
- Leverage `factory` instead of post init method.
- Fix/add some typing.
=> chore(runtime_metrics): fix some methods signatures

ddtrace/contrib/wsgi/__init__.py
=> Fix wsgi middleware docs

tests/utils.py
This allows to use get `get_root_span` with pytest tests.
=> test(utils): refactor get_root_span out of unittest classes

.circleci/config.yml, riotfile.py, tests/contrib/celery/test_old_style_task.py, tox.ini
=> Migrate celery tests to riot

tests/contrib/grpc/test_grpc.py
#2399 changed how spans for streaming responses were finished which requires tests to ensure the registered callback has been called. Use the same synchronization before checking written spans.
=> fix(grpc): ensure callbacks in streaming tests

ddtrace/contrib/gevent/__init__.py, ddtrace/profiling/profiler.py, ddtrace_gevent_check.py, releasenotes/notes/gevent-warning-f91ed0e6cac71a21.yaml, setup.py, tests/contrib/gevent/test_monkeypatch.py, tests/contrib/gevent/wrong_program_gevent.py, tests/profiling/test_profiler.py
This moves the profiler-only check to be for the whole ddtrace module.
=> feat(gevent): warn when ddtrace is imported before monkey patching is done

tests/contrib/celery/test_integration.py
Somehow none of our celery tests actually tested creating a trace from
within a task which is a very common use-case when using celery.
=> celery: add trace test case

tests/tracer/test_sampler.py
Adding some additional test cases to help validate some use cases.
The coding is working as expected, but wanted to add the new
test cases anyways.
=> Add additional DatadogSampler test cases

.circleci/config.yml
This reverts commit 26b3c81088c461b1f02cdf0271f60eb62fb84db3.
=> Revert "ci: add manual build workflow (#2321)"

ddtrace/internal/writer.py
Looks to have been missed in #2228
=> chore(internal): remove unused lock in writer

.github/workflows/codespell.yml, CHANGELOG.md, ddtrace/contrib/boto/patch.py, ddtrace/contrib/cassandra/session.py, ddtrace/contrib/dbapi/__init__.py, ddtrace/contrib/grpc/utils.py, ddtrace/contrib/molten/wrappers.py, ddtrace/contrib/pymongo/client.py, ddtrace/contrib/pymongo/parse.py, ddtrace/contrib/pyramid/patch.py, ddtrace/contrib/tornado/stack_context.py, ddtrace/ext/git.py, ddtrace/profiling/exporter/pprof.proto, ddtrace/utils/formats.py, docs/contributing.rst, setup.py, tests/contrib/boto/test.py, tests/contrib/jinja2/test_jinja2.py, tests/contrib/molten/test_molten.py, tests/contrib/pylons/app/lib/helpers.py, tests/contrib/pylons/app/middleware.py, tests/contrib/pymongo/test.py, tests/contrib/pynamodb/test_pynamodb.py, tests/opentracer/core/test_tracer.py, tests/profiling/simple_program_fork.py
Fix typos discovered by https://github.com/codespell-project/codespell
Test output: https://github.com/cclauss/dd-trace-py/actions
=> Fix typos discovered by codespell

ddtrace/contrib/requests/connection.py, tests/contrib/requests/test_requests.py
Call `set_http_meta` once and with all the available data. Also avoid `urlparse` and use simpler parsing instead for better performance.
=> fix(requests): ensure http metadata

ddtrace/contrib/pynamodb/__init__.py
Fix for formatting of Python directive in https://ddtrace.readthedocs.io/en/v0.49.3/integrations.html#id65
=> chore(docs): fix formatting in pynamodb docs

ddtrace/contrib/django/patch.py, ddtrace/contrib/django/utils.py, tests/contrib/django/test_django.py
This is a refactor to help preprare for the incoming ASGI support to
Django which will utilize the same helpers.
=> refactor(django): pull request/response tagging into helpers

.github/workflows/mako.yml
This change leverages the mako test suite to test whether ddtrace instrumentation alters the functionality of the Mako framework in unexpected ways.
=> Mako ci integration test

ddtrace/profiling/exporter/pprof.pyx, releasenotes/notes/profiling-task-pprof-3afb83e36a63aeaf.yaml, tests/profiling/exporter/test-pprof-exporter-py2.txt, tests/profiling/exporter/test-pprof-exporter.txt, tests/profiling/exporter/test_pprof.py
This makes sure the task id and name that are gathered by the stack collector
is exported as label in the final pprof file.
=> feat(profiling): export task name and ids from StackEvent to pprof

.github/workflows/django.yml
This should allow to run and test the profiler while running django tests.
=> ci(django): enable profiling

.gitignore
=> chore: add riot to gitignore

releasenotes/notes/fix-sanic-non-str-args-4d1b0f506bee3436.yaml
=> fix: fix latest sanic release note

.circleci/config.yml, riotfile.py, scripts/ddtest
Remove the pin on riot to allow using the latest release.
=> ci: unpin riot

setup.py
Added `py.typed` file to publish mypy type hinting for ddtrace.
Resolves #951
=> Added py.typed for ddtrace

ddtrace/contrib/asgi/__init__.py, ddtrace/contrib/asgi/middleware.py, releasenotes/notes/asgi-span-19e772cb2f09ef4d.yaml
https://github.com/DataDog/dd-trace-py/pull/2725#discussion_r680035274
=> Use dictionary for ASGI scope storage

ddtrace/appsec/internal/rules.yaml, ddtrace/appsec/internal/utils.py
update the converter and the rules for the recent change in the rule format (removing the `$` from the addresses)
=> Eslam.salem/update the addresses format

ddtrace/internal/runtime/runtime_metrics.py, releasenotes/notes/feat-runtime-distribution-e27687432f7ee4a5.yaml
Submit runtime metrics as distributions for improved aggregation.
=> feat: submit runtime metrics as distributions

benchmarks/README.rst, benchmarks/bm/__init__.py, benchmarks/bm/_scenario.py, benchmarks/django_simple/scenario.py, benchmarks/encoder/scenario.py, benchmarks/flask_simple/scenario.py, benchmarks/span/scenario.py, benchmarks/tracer/scenario.py
Auto-register every subclass of `bm.Scenario` so you don't need to sub-class _and_ decorate with `@bm.register`.
=> perf: Auto-register bm.Scenario sub-classes

ddtrace/pin.py
=> perf(pin): avoid cloning newly created Pin object

releasenotes/notes/fix-forksafe-after-in-child-f13fb133563c7b53.yaml
Update previous release note for #2821
=> Update release note

ddtrace/contrib/pytest/__init__.py
{{title}}
If a customer uses the `--ddtrace-patch-all` option without `--ddtrace`, they are effectively not enabling the CI Visibility integration. This PR adds text to clarify that both options should be used.
=> Minor documentation clarification in pytest module

ddtrace/internal/_encoding.pyx, releasenotes/notes/fix-encoder-thread-safe-5c6924013c51d4f6.yaml, tests/tracer/test_encoders.py
=> fix(internal): add locks for thread-safety of trace encoder

riotfile.py
=> tests(django): Pin django_hosts and djangorestframework test suites

ddtrace/tracer.py
=> Fix new mypy error from 0.920

releasenotes/notes/deprecate_external_ddtrace.propagation.utils-e5106df5b4723310.yaml
=> fix deprecation release note

ddtrace/sampler.py, tests/tracer/test_sampler.py
From working on #3082 realized there are implementation details of these two samplers which need to be shared having DatadogSampler subclass from RateByServiceSampler simplifies the coordination.
{{title}}
=> internal: refactor DatadogSampler, subclass from RateByServiceSampler

ddtrace/profiling/collector/stack.pyx
=> refactor(profiling): use a set rather than a tuple

ddtrace/contrib/grpc/patch.py, releasenotes/notes/fix-grpc-intercept-channel-not-unpatched-5a4252256801ad09.yaml
=> fix(grpc): ensure grpc.intercept_channel is unpatched properly

docs/spelling_wordlist.txt
=> internal: add unpatched to spelling wordlist

Dockerfile.buster
{{title}}
https://github.com/DataDog/dd-trace-py/pull/3095#discussion_r782640891
=> dev: update Python versions in dev docker image

ddtrace/contrib/botocore/patch.py
Inject trace context for SNS.
TODO: tests - will be done in the `hsg/managed-services-trace-context` branch.
=> [SLS-1824] Inject trace context for SNS

ddtrace/_monkey.py, releasenotes/notes/fix-gevent-autopatching-7d77beebd4698da2.yaml, tests/contrib/gevent/test_monkeypatch.py
`gevent` was in `_PATCH_ON_IMPORT` but not `PATCH_MODULES` so was not getting picked up for patching.
=> fix(gevent): ensure gevent is patched automatically

ddtrace/profiling/exporter/pprof.pyx
=> fix(types): remove unused type ignore in pprof.pyx

ddtrace/constants.py, ddtrace/contrib/logging/patch.py, ddtrace/opentracer/tracer.py, ddtrace/span.py, ddtrace/tracer.py, releasenotes/notes/deprecate-constants-e6ea6706d38b186f.yaml, tests/tracer/test_constants.py
Deprecate constants that are intended for internal usage only.
=> chore: deprecate constants

ddtrace/__init__.py, releasenotes/notes/remove-ddtrace-install-excepthooks-8107b679a9f51ef3.yaml
=> chore(tracing)!: Remove deprecated install excepthook

ddtrace/contrib/celery/app.py, ddtrace/contrib/celery/constants.py, ddtrace/contrib/flask/patch.py, ddtrace/contrib/molten/patch.py, ddtrace/pin.py, releasenotes/notes/remove-pin-app-apptype-8d0addd243deb7f9.yaml, tests/contrib/requests/test_requests.py, tests/tracer/test_pin.py
Remove deprecated `Pin.app` and `Pin.app_type`.
=> chore!: remove Pin.app and Pin.app_type

.circleci/config.yml, .github/workflows/changelog.yml, .github/workflows/codeql-analysis.yml, .github/workflows/django-overhead-profile.yml, .github/workflows/encoders-profile.yml, .github/workflows/system-tests.yml, .github/workflows/test_frameworks.yml, benchmarks/README.rst, scripts/check-releasenotes
=> chore: update build scripts for new default branch

ddtrace/tracer.py
With stats computation incoming (#2915) there will be multiple writers
that depend on an agent url. Currently this state is maintained on the
writer but now it seems to make more sense to live on the tracer
instance.
=> refactor(tracer): maintain agent url state

releasenotes/notes/aiopg-0160-67bac7e073e4bbf9.yaml
=> fix: update aiopg-0160-67bac7e073e4bbf9.yaml

.circleci/config.yml, tests/contrib/aiohttp/test_templates.py, tests/snapshots/tests.contrib.aiohttp.test_templates.test_template_rendering_snapshot.json, tests/snapshots/tests.contrib.aiohttp.test_templates.test_template_rendering_snapshot[pyloop].json
Add a snapshot test case for aiohttp_jinja2 to ensure no inadvertent
changes are made to trace data.
=> chore(aiohttp): add snapshot test

ddtrace/tracer.py, tests/appsec/test_processor.py
This refactor makes it clear what is required to create the standard
list of span processors that are used by `Tracer`. It also hopefully
makes `configure` more clear as well and also makes it such that the
processors won't be recreated with every call to `configure`.
=> refactor(tracer): use span processor factory

docs/spelling_wordlist.txt, releasenotes/notes/fix-psutil-macos-0cd7d0f93b34e3e4.yaml
=> fix(docs): add release note missing from #3382

ddtrace/internal/telemetry/writer.py, tests/tracer/telemetry/test_writer.py
This field is a boolean and not a string.
=> fix(telemetry): update compatible field in telemetry payload

Dockerfile.buster
https://github.com/pyenv/pyenv/releases/tag/v2.2.5
=> chore: bump python versions to 3.10.3 3.9.11 3.8.13 3.7.13

ddtrace/internal/telemetry/writer.py, tests/tracer/telemetry/test_writer.py
=> feat(telemetry): add integrations to app-started payload

.circleci/config.yml, ddtrace/internal/logger.py, ddtrace/sampler.py, hooks/pre-commit/run-slotscheck.sh, hooks/scripts/run-slotscheck.sh, pyproject.toml, riotfile.py
=> chore: fix __slots__ inheritance

ddtrace/appsec/CMakeLists.txt, ddtrace/appsec/_ddwaf.pyx, ddtrace/appsec/_libddwaf.pxd, ddtrace/appsec/rules.json, docs/spelling_wordlist.txt, releasenotes/notes/appsec-and-libddwaf-c2a7054f3df35f31.yaml
This updates libddwaf and recommended rules to their latest available versions.
=> feat: update libddwaf and rules

docs/advanced_usage.rst, docs/release_notes.rst, docs/versioning.rst, releasenotes/notes/release-1.0-758fc917e40d7eb3.yaml, releasenotes/notes/remove-deprecated-tracer-attributes-4bb24b794a1aacb9.yaml
[Preview of revised 1.0 release notes](https://output.circle-artifacts.com/output/job/afd17c78-0275-4ff8-bde2-f6609875763c/artifacts/0/tmp/docs/_release_notes_all.html)
[Preview of 1.0 release notes without duplicate reno notes](https://output.circle-artifacts.com/output/job/83600983-7be0-4614-b521-4ee2cbb94589/artifacts/0/tmp/docs/release_notes.html)
=> docs: revise 1.0 release notes

docs/advanced_usage.rst, docs/index.rst, docs/release_notes.rst, docs/upgrading.rst, docs/versioning.rst, releasenotes/notes/add-warning-after-shutdown-tracer-dd8799467c4d29c8.yaml, releasenotes/notes/ddtrace-1.0-disable-basic-config-call-by-default-b677844e4a13a794.yaml, releasenotes/notes/release-1.0-758fc917e40d7eb3.yaml, releasenotes/notes/span-types-enum-5ca7cb35031a199e.yaml, releasenotes/notes/update-deprecated-contrib-removal-version-ca920d9e1d91b6e0.yaml
Aside from some minor edits, the preface has been redone to separate out different types of changes and actions that a library user needs to take when migrating.
📝 [Preview](https://output.circle-artifacts.com/output/job/dc29a8ee-5d02-41e0-b9a4-44dc6d00744d/artifacts/0/tmp/docs/_release_notes_all.html)
=> docs: release notes for 1.0 revisions

setup.cfg, tox.ini
tox.ini is an odd place for it
=> chore(pytest): move config to setup.cfg

.circleci/config.yml
These jobs can also benefit from more parallelization
=> chore(grpc,gevent): more parallelization

ddtrace/contrib/botocore/patch.py
Fixing type error. https://github.com/DataDog/dd-trace-py/issues/3640
=> fix(typing): botocore.get_kinesis_data_object

releasenotes/notes/asm_fix_headers-9bd1585200be8a2a.yaml
=> docs(asm): add release note for header fix

.circleci/config.yml, tests/contrib/aiomysql/test_aiomysql.py, tests/snapshots/tests.contrib.aiomysql.test_aiomysql.test_pin_override[True].json, tests/snapshots/tests.contrib.aiomysql.test_aiomysql.test_queries.json, tests/snapshots/tests.contrib.aiomysql.test_aiomysql.test_user_specified_service.json
As per title.
Also add snapshot tests to replace hand rolled assertions.
=> chore(aiomysql): use async/await for tests

.circleci/config.yml, scripts/ddtest
CircleCI has provided updates to the `ubuntu-2004` image to address some networking issues.
=> chore(ci): update machine executor image

docs/spelling_wordlist.txt, releasenotes/notes/pin-protobuf-v4-357193706afd46e6.yaml
We missed added a release note to #3766, this note relates to that PR.
=> chore(docs): add release note for #3766

ddtrace/profiling/profiler.py, mypy.ini, riotfile.py
No longer pin `mypy` to `<0.960`, ignore mypy checking on all generated protobuf files, and remove unused ignore comments.
=> chore(ci): update mypy to latest version

ddtrace/filters.py
=> fix(docs): update doc link to python 3

ddtrace/debugging/_metrics.py
This change adds dogstatsd metrics declarations for the debugger.
=> chore(debugging): add metrics declarations

ddtrace/debugging/_expressions.py, tests/debugging/test_expressions.py
This change adds support for the custom debugging expression language.
=> chore(debugging): add expression language support

ddtrace/commands/ddtrace_run.py
The current code calls `distutils.spawn.find_executable` on the passed
argument. This is fine on non-Windows platform, but it fails easily on Windows
platform.
`find_executable` has a subtle bug reported as
https://github.com/python/cpython/issues/94338 which prevents files with a
`.EXE` extension (uppercase) to be found.
As `distutils` is deprecated, replace it with shutil which is not and has a
`which` function which does the same thing.
=> fix(ddtrace-run): drop distutils in favor of shutil

releasenotes/notes/add-datadog-trace-tag-propagation-f69736976107f1c2.yaml
Update release note included in #3625 to indicate this was internal and not part of our public api.
=> docs: update release note for trace tag propagation

ddtrace/bootstrap/sitecustomize.py, docs/configuration.rst, releasenotes/notes/enable-telemetry-by-default-ae39651a478f8e61.yaml
Enables telemetry collection when an application is run with `ddtrace-run`.
Collect tracer configurations.
Starts a telemetry writer which sends a payload of tracer configuration to the datadog agent. As of now one event is sent on application startup and another is sent when an application terminates.
Ensure telemetry test suite passes in ci.
=> feat(telemetry): enable telemetry by default

tests/profiling/collector/test_stack.py
This waits for events to happen, which should limit the possibility for a test
failure as we've seen from time to time in the CI.
```
@pytest.mark.skipif(not stack.FEATURES["stack-exceptions"], reason="Stack exceptions not supported")
def test_exception_collection_trace(tracer):
r = recorder.Recorder()
c = stack.StackCollector(r, tracer=tracer)
with c:
with tracer.trace("test123") as span:
try:
raise ValueError("hello")
except Exception:
nogevent.sleep(1)
exception_events = r.events[stack_event.StackExceptionSampleEvent]
>       assert len(exception_events) >= 1
E       assert 0 >= 1
E        +  where 0 = len(deque([]))
```
=> test(profiling): reduce flaky tests probability

.circleci/config.yml, riotfile.py, tests/contrib/flask/app.py, tests/contrib/flask/test_flask_snapshot.py, tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_200.json, tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_stream.json
Flask does not have any snapshots tests so let's add some so that we can
be more confident in making changes like #3826.
Some of the logic from #3705 are used here.
=> chore(flask/tests): add snapshot tests

ddtrace/bootstrap/sitecustomize.py, docs/configuration.rst, releasenotes/notes/enable-telemetry-by-default-ae39651a478f8e61.yaml
Reverts DataDog/dd-trace-py#3925
=> chore(telemetry): revert enable telemetry by default

ddtrace/debugging/_debugger.py, ddtrace/debugging/_function/store.py, ddtrace/debugging/_probe/registry.py, ddtrace/debugging/_uploader.py, ddtrace/internal/module.py, tests/debugging/.coveragerc, tests/debugging/mocking.py, tests/debugging/test_debugger.py, tests/debugging/test_uploader.py
This change introduces the main debugger service class.
=> chore(debugging): add the debugger class

docs/troubleshooting.rst, releasenotes/notes/troubleshooting-root-errors-cfe9af0c0083e03f.yaml
=> docs: add troubleshooting for root span error details

ddtrace/contrib/wsgi/wsgi.py
=> chore(wsgi): remove redundant error handling

tests/conftest.py
Occasionally some subprocess test cases could leave pytest in a weird state that causes it to complain about previous items not being torn down properly. This change should fix these issues with test runs.
=> test: implement full runtest protocol for subprocess tests

ddtrace/contrib/pylons/middleware.py, docs/spelling_wordlist.txt, releasenotes/notes/asm-pylons-report-http-raw-uri-6a5f2c2351aaab6d.yaml, tests/contrib/pylons/test_pylons.py
Add support for reporting http raw uri for pylons under appsec.
Unit tests in this PR, system tests are being prepared separately.
=> feat(asm/pylons): appsec http raw uri support

ddtrace/appsec/processor.py, ddtrace/contrib/django/utils.py, ddtrace/contrib/trace_utils.py, releasenotes/notes/asm-detect-attack-on-body-3fe45bc066dcc680.yaml, releasenotes/notes/feat:-detect-attack-on-body-3fe45bc066dcc680.yaml, tests/appsec/test_processor.py, tests/contrib/django/test_django_appsec.py, tests/contrib/djangorestframework/test_djangorestframework.py, tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
Detect attacks on Django and Django Rest Framework body.
=> feat(asm): detect attack on django body

releasenotes/notes/fix-attribute-error-in-flask-2.2.0-94524c33b005d48a.yaml
Improve release note for flask fix
=> chore(flask): update fix release note

setup.py
Add [PEP-0345 project URL](https://peps.python.org/pep-0345/#project-url-multiple-use) in setup.py.
**Side Effect:** Pypi will show more links in left side bar under "Project links" (e.g: https://pypi.org/project/gevent/)
=> chore(setup/pypi): update pypi.org Project links

.mergify.yml
Configure Mergify so that approved PRs are automatically updated
=> chore(mergify): auto-update approved PRs

ddtrace/internal/telemetry/data.py, tests/telemetry/test_data.py
When appsec is enabled we should add it to the application object in a telemetry request.
=> feat(telemetry/appsec): add appsec to telemetry payload

ddtrace/contrib/django/utils.py, ddtrace/contrib/flask/patch.py, ddtrace/contrib/pylons/middleware.py, releasenotes/notes/feat-detect-attack-on-xml-body-878215f0d3d1a64d.yaml, setup.py, tests/contrib/django/test_django_appsec.py, tests/contrib/flask/test_flask_appsec.py, tests/contrib/pylons/test_pylons.py
=> feat(asm/python): support xml content in body detection

ddtrace/contrib/django/utils.py, ddtrace/contrib/flask/patch.py, ddtrace/contrib/pylons/middleware.py, releasenotes/notes/asm-avoid-json-decode-error-31479891110bcb55.yaml, tests/contrib/django/test_django_appsec.py, tests/contrib/flask/test_flask_appsec.py, tests/contrib/pylons/test_pylons.py
For Flask, Django and Pylons, with appsec enabled, a json decode error can occur while parsing the request body, but it should be captured.
No issue exists yet.
Unit testing.
=> fix(asm): avoid json decode error in request body

ddtrace/constants.py, ddtrace/context.py, ddtrace/contrib/trace_utils.py, releasenotes/notes/asm-propagate-user-id-1b1f596f7442fd34.yaml, tests/tracer/test_tracer.py
=> feat(asm/python): propagate user ID

ddtrace/internal/telemetry/writer.py, tests/telemetry/test_telemetry.py
Currently the telemetry writer sends a heartbeat event every 60 seconds. The information sent in a heartbeat event is also included in all other telemetry events. With this optimization heartbeat events will only be queued if the telemetry events queued is empty when `TelemetryWriter.periodic()` is called.
=> feat(telemetry): heartbeat optimization

ddtrace/internal/_context.py, ddtrace/span.py
Improve performance `set_http_meta`. Update `context.set_items`
=> chore(refactor): improve performance set_http_meta

.github/workflows/system-tests.yml
https://github.com/DataDog/system-tests/pull/453 has been merged.
=> chore: update lib injection system-tests branch

releasenotes/notes/enable-telemetry-by-default-ae39651a478f8e61.yaml, releasenotes/notes/telemetry-release-note-1-5-2376710f62cba11b.yaml
Releasenote in https://github.com/DataDog/dd-trace-py/pull/3925 was not included in v1.5.0rc1. 
This occurred because the release note in the PRs below have the same file name:
1. [enable telemetry in v1.4](https://github.com/DataDog/dd-trace-py/commit/649d7848cf048f4890001a7679cab50601a448ee)
2. [revert enable telemetry in v1.4](https://github.com/DataDog/dd-trace-py/commit/ff53d16436fdab11689e929e6551a73f0ec5b23b)
3. [enable telemetry in v1.5](https://github.com/DataDog/dd-trace-py/pull/4003)
We will need to fix this issue in reno.
=> chore(telemetry): add telemetry release note

ddtrace/contrib/flask/patch.py, releasenotes/notes/flask-support-response-streamig-d3aafc8fa1e3605d.yaml, tests/contrib/flask/test_errorhandler.py, tests/contrib/flask/test_flask_appsec.py, tests/contrib/flask/test_hooks.py, tests/contrib/flask/test_request.py, tests/contrib/flask/test_static.py, tests/contrib/flask/test_views.py, tests/contrib/flask_autopatch/test_flask_autopatch.py, tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_200.json, tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_200_220.json, tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_get_user.json, tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_get_user_220.json, tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_stream.json, tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_stream_220.json
Revert #3826 as an immediate mitigation for #4215
=> fix(flask): revert trace streamed responses

releasenotes/notes/mitigate-1-5-gevent-regression-c505053014036c6a.yaml
Adds release note for the following change: https://github.com/DataDog/dd-trace-py/pull/4252
=> chore(gevent): add release note for gevent mitigation

docs/spelling_wordlist.txt
With package updates it seems that backported was being caught by sphinx-build -W -b spelling docs docs/_build/html.
=> chore(spelling): add backported to spelling_wordlist

.circleci/config.yml, scripts/tested_pythons
This change updates how our circleci configuration manages python interpreters for riot test suite runs. Currently, any `run_test` step statically creates parallel jobs for each python interpreter based on our riotfile's `select_pys()`, which can cause issues in CI if any python versions are excluded (ex. [failing CI run here](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/21836/workflows/8b846d34-399f-4787-b764-06f84fd654c1/jobs/1485004/parallel-runs/2?filterBy=FAILED))
This changes the `run_test` step such that the circleci runner checks the python interpreters of the test suite being run in each job, instead of blindly creating all python interpreters as specified in `select_pys()`.
=> chore(ci): dynamic listing of python interpreters for riot test suites in circleci

.github/workflows/test_frameworks.yml, riotfile.py, tox.ini
PasteDeploy, which is a dependency of pylons, released a new version 3.0 which includes an f-string and is therefore not Python 2 compatible (see relevant [issue](https://github.com/Pylons/pastedeploy/issues/38)). This is unfortunately breaking our CI so we will pin PasteDeploy to <3.0 for our pylons tests for now.
I've pinned PasteDeploy in our pylons tests and framework tests, as well as pyramid tests (which indirectly rely on PasteDeploy as well).
=> chore(ci): pin PasteDeploy for pylons, pyramid tests

ddtrace/context.py, ddtrace/settings/database_monitoring.py, tests/internal/test_database_monitoring.py, tests/tracer/test_context.py
Adds utils for generating DBM comments
=> chore(dbm): generate sql comments for DBM

ddtrace/contrib/trace_utils.py, docs/spelling_wordlist.txt, releasenotes/notes/asm-ipaddress-consider-appsec-value-9a0948896645a4b1.yaml, tests/contrib/django/test_django_appsec.py, tests/contrib/flask/test_flask_appsec.py
Enable IP collection if `DD_TRACE_CLIENT_IP_HEADER_DISABLED` is not set but appsec is enabled as per https://datadoghq.atlassian.net/wiki/spaces/APS/pages/2118779066/Client+IP+addresses+resolution#Activation
=> chore(asm): enable ip collection if not disabled and appsec is enabled

releasenotes/notes/asm-1-click-activation-with-RCM-6a2431949768b73b.yaml, releasenotes/notes/asm-add-http-route-for-flask-8b13c721e2f7543b.yaml, releasenotes/notes/asm-fix-ipaddress-backport-lib-4684ce71e63459e7.yaml, releasenotes/notes/asm-tag-http-query-string-c7faba44b1402215.yaml, releasenotes/notes/feat-dynamic-instrumentation-4c46bb86482438c1.yaml, releasenotes/notes/iast-weak-hash-2fe50c2c7da2289d.yaml, releasenotes/notes/ipaddress-dep-3.7-b2bf42719e5f99ec.yaml, releasenotes/notes/wsgi-span-parenting-fix-22908787ac7ee6a6.yaml
We found several changelog entries for 1.6.0 that were unclear or for not-yet public facing changes. This PR addresses those concerns.
PR #4400 also makes a fix to set `DD_REMOTE_CONFIGURATION_ENABLED` to false by default, this PR makes the relevant changelog fix here.
=> chore(releasenotes): fix release note entries for 1.6.0

ddtrace/contrib/dbapi/__init__.py, ddtrace/settings/_database_monitoring.py, tests/contrib/dbapi/test_dbapi.py, tests/internal/test_database_monitoring.py
This PR adds support for DBM comment injection in all ddtrace integrations.
`dbapi.TracedCursor._trace_method` was updated to add DBM comments to sql queries executed in `[integration_name].query` spans. This adds DBM to the following integrations: `pyodbc`, `psycopg2`, `snowflake.connector`, `sqllite3`, `mariadb`, `mysql.connector`, `MySQLdb`, `pymysql`.
The following integrations do not use `dbapi.TracedCursor._trace_method` to trace database queries: `aiomysql`,`aiopg`, and `asyncpg`. They will be supported in a future PR
=> chore(dbm): add dbm comment to database queries

releasenotes/notes/python311-tracer-a7077c0e461622d2.yaml
The note about lack of compatibility should be highlighted.
**Current**
**Preview**
=> fix(releasenotes): highlight note regarding 3.11 support

tests/profiling/test_uwsgi.py
This test does not work anymore with greenlet 2.
=> test(profiling): disable uwsgi master+lazy app scenario on gevent

docker/Dockerfile.buster
v2.3.6 contains Python 3.11.
https://github.com/pyenv/pyenv/releases/tag/v2.3.6
=> fix(ci): update dev image pyenv to v2.3.6

ddtrace/settings/_database_monitoring.py, tests/contrib/dbapi/test_dbapi.py, tests/internal/test_database_monitoring.py
The term `propagation` better describes how we plan to update database queries to correlate DBM profiles to APM traces. With this in mind `DD_TRACE_SQL_COMMENT_INJECTION_MODE` configuration was updated to `DD_DBM_PROPAGATION_MODE`.
=> chore(dbm): use DD_DBM_PROPAGATION_MODE

tests/contrib/redis/test_redis_asyncio.py
=> fix(ci): add wait for traces for rest of redis tests

.circleci/config.yml, ddtrace/vendor/wrapt/wrappers.py, releasenotes/notes/fix-patching-error-asynctest-9b430f410cd9dfeb.yaml, riotfile.py, tests/contrib/asynctest/test_asynctest.py, tests/contrib/django/views.py, tests/contrib/pytest/test_pytest.py
Fix error in patching functions. `forbiddenfruit` package has conflicts with some libraries such as `asynctest`. This conflict raises `AttributeError` exception. 
See issue #4484.
=> fix(wrapt): fix error in patching functions

.circleci/config.yml
Circleci pipelines: Enable asynctest
Thanks @Kyle-Verhoog ! https://github.com/DataDog/dd-trace-py/pull/4514#discussion_r1019511523
=> fix(circleci): enable asynctest

.circleci/config.yml
[27m45s](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/23931/workflows/da46d188-8b20-4765-8912-40035b77710f/jobs/1625550/parallel-runs/0?filterBy=ALL) -> [12m13s](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/23936/workflows/da820b94-3ca3-43f9-9a74-670946616554/jobs/1625757/parallel-runs/6?filterBy=ALL).
=> chore(ci/profiling): bump number of runners

.circleci/config.yml, riotfile.py, tox.ini
[12m 3s](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/24026/workflows/afe0ab90-8eb7-4d79-823d-6e1a93715c92/jobs/1631678) -> [2m 14s](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/24050/workflows/8f1fe6b6-6595-41ce-b717-4b5e157e952b/jobs/1633274/parallel-runs/1?filterBy=ALL)
=> chore(ci/consul): move to riot

tests/contrib/psycopg/test_psycopg_snapshot.py
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/24048/workflows/07d39bba-30fd-49d5-a5e8-ec85f58ad8c5/jobs/1633184
=> chore(ci/psycopg): wait for traces in snapshot tests

tests/profiling/collector/test_stack.py
I broke this in #4563 and didn't notice it as the Windows profiling tests passed.
=> chore(ci/profiling): update line number

ddtrace/contrib/django/utils.py, ddtrace/contrib/flask/patch.py, ddtrace/contrib/pylons/middleware.py, releasenotes/notes/capture-xml-parsing-errors-e6c8c761ed026ce3.yaml, tests/contrib/django/test_django_appsec.py, tests/contrib/flask/test_flask_appsec.py
xmltodict could raise some exceptions that we weren't catching on XML body parsing.
=> fix(asm): capture XML parsing errors on body parse

.circleci/config.yml, riotfile.py, tox.ini
[5m 8s](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/24062/workflows/fc236ff5-e41a-43a3-8934-c51df5130497/jobs/1634042) -> [1m 54s](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/24068/workflows/320b950f-d00f-4461-9195-872327dff816/jobs/1634438)
=> chore(ci/pyodbc): move to riot

.circleci/config.yml, riotfile.py, tox.ini
=> chore(ci/pylibmc): move to riot

docs/index.rst
an extra space prevents the hyperlink from rendering correctly
n/a
Use rich preview in GitHub UI to confirm that the change renders correctly.
=> docs: remove space to create url

ddtrace/contrib/sqlalchemy/engine.py
Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in the sqlalchemy integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().
=> chore(sqlalchemy): replace set_tag usages with set_tag_str

ddtrace/contrib/pyramid/trace.py
Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in the pyramid integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().
=> chore(pyramid): replace set_tag usage with set_tag_str

ddtrace/contrib/pylibmc/client.py
Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in the pylibmc integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().
=> chore(pylibmc): replace set_tag usage with set_tag_str

.circleci/config.yml
=> ci(tox): avoid running ddtrace with tox v4.0 (#4751) [backport to 1.6]

.circleci/config.yml
Backport https://github.com/DataDog/dd-trace-py/pull/4751
=> ci(tox): avoid running ddtrace with tox v4.0 [backport #4751 0.61]

scripts/profiles/encoders/setup.sh
Backport: https://github.com/DataDog/dd-trace-py/pull/4750
=> chore(encoders): update package tool before installing packages [backport #4750 to 1.5]

.github/workflows/upstream-issues.yml
The upstream-issue-notifier v0.1.1 is currently re-creating notification issues after they are closed and the reference to the closed upstream issue is still kept. Version 0.1.2 should make it no longer create new duplicate notification issues if a previous notification issue for a closed upstream issue has been closed.
=> chore(upstream issues): upgrade upstream notifier version to keep closed issues closed

.github/workflows/upstream-issues.yml
#4775 upgraded the upstream issue notifier to 0.1.2, but this still did not resolve the issue of the notifier creating duplicate issues from already closed issues.
Version 0.1.3 now takes all github issues on the host repository (including closed and open issues) so this problem should be fixed after upgrading. See https://github.com/Kyle-Verhoog/upstream-issue-notifier/pull/22 for more context.
=> chore(upstream issue notifier): upgrade upstream issue notifier to 0.1.3

.github/workflows/test_frameworks.yml
The starlette framework tests currently pin sqlalchemy to 1.4.41 due to an upstream issue which has now closed:
https://github.com/encode/databases/issues/512. It looks like we can unpin this dependency.
Note: this also indirectly fixes the failing starlette framework tests due to this now closed upstream issue:
https://github.com/encode/databases/pull/513, where sqlalchemy==1.4.42 added a new private field in the SQLAlchemy cursor class. While this job uses the latest databases package that has accounted for this field, this was causing attribute errors since we were using a previous version of sqlalchemy that did not yet have that private field added.
=> fix(starlette framework tests): unpin sqlalchemy [backport #4801 to 1.6]

riotfile.py, tests/integration/test_integration.py
`attrs==22.2.0` removed support for Python 3.5 and made Python 3.6 support deprecated.
This causes deprecation warnings to be logged and causes our integration tests to fail.
This change makes sure we install a version of `attrs<22.2.0` only for these failing integration tests.
https://www.attrs.org/en/22.2.0/changelog.html#id1
Co-authored-by: Yun Kim <35776586+Yun-Kim@users.noreply.github.com>
Co-authored-by: Yun Kim <yun.kim@datadoghq.com>
=> fix(tests): pin attrs<22.2.0 for Python 3.6 in integration tests [backport #4816 to 1.7]

riotfile.py, tests/integration/test_integration.py
`attrs==22.2.0` removed support for Python 3.5 and made Python 3.6 support deprecated.
This causes deprecation warnings to be logged and causes our integration tests to fail.
This change makes sure we install a version of `attrs<22.2.0` only for these failing integration tests.
https://www.attrs.org/en/22.2.0/changelog.html#id1
Co-authored-by: Yun Kim <35776586+Yun-Kim@users.noreply.github.com>
Co-authored-by: Yun Kim <yun.kim@datadoghq.com>
=> fix(tests): pin attrs<22.2.0 for Python 3.6 in integration tests [backport #4816 to 1.6]

ddtrace/debugging/_config.py, releasenotes/notes/fix-dynamic-instrumentation-logging-aef13f091e5feed5.yaml
=> chore(dynamic_instrumentation): remove unnecessary log line

ddtrace/debugging/_config.py, releasenotes/notes/fix-dynamic-instrumentation-logging-aef13f091e5feed5.yaml
=> chore(dynamic instrumentation): remove unnecessary log line from application start up

ddtrace/debugging/_config.py, releasenotes/notes/fix-dynamic-instrumentation-logging-aef13f091e5feed5.yaml
=> chore(dynamic_instrumentation): remove unnecessary log line (backport to 1.7)

riotfile.py
The 39 release of cryptography causes the snowflake test suite to fail with Python < 3.7. Therefore we pin it to allow the CI jobs to pass for now.
=> ci(snowflake): pin cryptography [backport #4857 to 1.7]

riotfile.py
The 39 release of cryptography causes the snowflake test suite to fail with Python < 3.7. Therefore we pin it to allow the CI jobs to pass for now.
=> ci(snowflake): pin cryptography [backport #4857 to 1.6]

ddtrace/internal/module.py
Taken from: https://github.com/P403n1x87/dd-trace-py/commit/ed5b716526d9a657e474a8db162b257c37e9222e This is required to reduce flakiness in one of the debugger tests: test_debugger_probe_new_delete[probe0-<lambda>] Example failure: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/23627/workflows/79199172-b4ef-43b3-a69e-371660cb1b68/jobs/1604074
=> chore(debugger): reduce debugger test flakiness [backport #4528 to 1.6]

.github/workflows/test_frameworks.yml, ddtrace/internal/module.py, ddtrace/internal/utils/version.py, riotfile.py, tests/integration/test_integration.py, tests/profiling/test_uwsgi.py
This PR includes 5 backport PRs to 0.61 to fix broken test suites:
- chore(packaging): support version parsing in packaging v22 #4752
- test(profiling): disable uwsgi master+lazy app scenario on gevent #4457
- fix(tests): pin attrs<22.2.0 for Python 3.6 in integration tests #4816 (cannot cherry-pick directly, as `integration-v5` was removed from 1.x)
- ci(snowflake): pin cryptography [backport #4857 to 0.61]
- chore(debugger): reduce debugger test flakiness #4528 (cannot directly cherry-pick as 
This PR also includes 4 backport PRs and 1 new commit to fix broken framework test suites:
- chore(framework tests): pin django framework test ubuntu to 20.04 #4636
- ci: pin pygments to fix mako framework test #3718
- test: pin MarkupSafe dependency #3478
- ci(starlette/fastapi): pin SQLAlchemy …
=> chore(ci): backport CI fixes to 0.61

ddtrace/appsec/constants.py
Add a specific constant file to AppSec
To avoid mixing specific AppSec features with APM, a constant file is added specific to ASM.
To avoid a large number of `import from`, constants are grouped into constant classes with additional features:
- assignment protection, to avoid changing the value of a constant
- access using field name or key
- possibility to iterate on all constants of a class
=> chore(asm): add specific constant file to AppSec

ddtrace/profiling/profiler.py, docs/configuration.rst, releasenotes/notes/profiler-code-provenance-issue-a912ea575a43ed07.yaml, releasenotes/notes/profiling-enable-code-provenance-3d9663e0cd742fcd.yaml
Backports #4878 to 1.7.
Reverts #4519 as this was causing a performance regression. Added release note acknowledging known performance regression. Note that code provenance is still disabled by default.
=> fix(profiler): revert code provenance enabled by default [backport #4876 to 1.7]

ddtrace/appsec/constants.py, ddtrace/contrib/trace_utils.py, releasenotes/notes/asm-event-tracking-sdk-d7e8516511c73589.yaml, tests/tracer/test_trace_utils.py
Implement the event tracking SDK, currently composed of two functions to track user logins and custom events.
=> feat(asm): add application security events tracking SDK functions

ddtrace/internal/remoteconfig/client.py
The fix for ensuring RCM used a SemVer compliant version string only took into account ddtrace versions that match `x.y.zrc2` or `x.y.zrc2.dev3+gf344hg`, but not `x.y.z.dev3+gf344hg`.
This fix ensures that if we have a `.dev` without `rc` that we properly convert `.dev` -> `-dev` which will make it SemVer compliant.
Since the tests rely heavily on the version of `ddtrace.__version__` writing a test is challenging. We should revisit this in the future so we can mock the version and parametrize the test to ensure all variations are tested.
=> fix(internal): properly convert PEP 440 version to SemVer for RCM client

ddtrace/contrib/trace_utils.py, releasenotes/notes/fix-http-url-200fca099f41ce49.yaml, tests/contrib/aiohttp/test_aiohttp_client.py, tests/contrib/requests/test_requests.py, tests/snapshots/tests.contrib.aiohttp.test_aiohttp_client.test_auth_200_request.json, tests/tracer/test_trace_utils.py
This fix removes unintended url parts in the `http.url` tag.
=> fix: remove url parts from http.url tag [backport #4904 to 1.7]

releasenotes/notes/fix-verify-url-7d0dd6b0ab53306f.yaml, tests/tracer/test_trace_utils.py
Add missing release notes for https://github.com/DataDog/dd-trace-py/pull/4914
=> chore(releasenotes): add missing release notes for #4914

ddtrace/contrib/sqlalchemy/__init__.py
Solves #4933.
Adds clear language to the purpose of enabling SQLAlchemy as an integration, whereas before its value was unclear vis a vis other database engines.
Clarity!
N/A
- fixes #4933 
N/A
=> docs: disambiguate SQLAlchemy's integration purpose

releasenotes/notes/asm-event-tracking-sdk-d7e8516511c73589.yaml
Make release note more clear as per @juanjux 's work. Original PR: https://github.com/DataDog/dd-trace-py/pull/4913
=> chore(asm): update release note for New Application Security Events Tracking API

ddtrace/profiling/collector/stack.pyx, releasenotes/notes/fix-profiler-3-11-memory-leak-stack-collector-9131642011ee5ce8.yaml, tests/profiling/collector/test_stack.py
Backports for #4901 and #4937 to 1.7.
=> fix(profiler): decrement refcount given strong reference of frame object in python 3.11 [backport]

tests/contrib/aiobotocore/test.py
This PR removes a 5-year old unexplained comment which appears irrelevant.
Closes #4676
=> chore(aiobotocore): remove unnecessary comment

riotfile.py
=> chore(starlette): unpin sqlalchemy

ddtrace/contrib/aiobotocore/__init__.py, ddtrace/contrib/aiobotocore/patch.py, ddtrace/contrib/boto/__init__.py, ddtrace/contrib/boto/patch.py, ddtrace/contrib/botocore/__init__.py, ddtrace/contrib/botocore/patch.py, ddtrace/ext/aws.py, docs/spelling_wordlist.txt, releasenotes/notes/fix-aws-tag-params-0e1488513a0ae5c7.yaml, tests/contrib/aiobotocore/test.py, tests/contrib/boto/test.py, tests/contrib/botocore/test.py
=> fix(aws): limit api params as span tags [backport #4781 to 0.61]

ddtrace/contrib/trace_utils.py, ddtrace/settings/config.py, releasenotes/notes/asm-dd-client-enabled-env-var-0d418972a04728f2.yaml, tests/tracer/test_trace_utils.py, tests/utils.py
Backport of #4949 to 1.8
+tests.
=> feat(asm): add the DD_TRACE_CLIENT_IP_ENABLED env var to fetch request IPs with ASM disabled

ddtrace/internal/remoteconfig/client.py, releasenotes/notes/rcm-validations-162716c50ea90f1b.yaml, tests/internal/remoteconfig/test_remoteconfig_client.py
Update flaky test, fix release note type
=> fix: update flaky test, fix release note type

releasenotes/notes/rcm-validations-162716c50ea90f1b.yaml
Update Remote Config release note
=> fix: update Remote Config release note

.gitlab-ci.yml
The change allows running a pipeline of the DI backend repository for internal dogfooding changes committed to a feature branch.
=> ci: allow running pipeline in DI backend

ddtrace/debugging/_debugger.py, ddtrace/debugging/_encoding.py, ddtrace/debugging/_expressions.py, ddtrace/debugging/_probe/model.py, ddtrace/debugging/_probe/registry.py, ddtrace/debugging/_probe/remoteconfig.py, ddtrace/debugging/_probe/status.py, ddtrace/debugging/_snapshot/collector.py, ddtrace/debugging/_snapshot/model.py, ddtrace/debugging/_snapshot/utils.py, ddtrace/debugging/safety.py, tests/debugging/exploration/_coverage.py, tests/debugging/exploration/_profiler.py, tests/debugging/exploration/debugger.py, tests/debugging/exploration/test_bootstrap.py, tests/debugging/probe/test_registry.py, tests/debugging/probe/test_remoteconfig.py, tests/debugging/probe/test_status.py, tests/debugging/snapshot/test_collector.py, tests/debugging/test_debugger.py, tests/debugging/test_encoding.py, tests/debugging/test_safety.py, tests/debugging/utils.py
Refactor probe model to better support multiple type of probes on multiple locations.
Now only metadata fields are defined on Probe and any additional data is defined using Mixin:
1. ProbeConditionMixin - add condition functionally to the probe.
2. ProbeLocationMixin - add location information such as LineLocationMixin or FunctionLocationMixin
3. SnapshotProbeMixin - add information regarding capture snapshot
4. MetricProbeMixin - add information regarding metric generation
This PR is ground work for adding log probes and span probes
There is no functionally change, ensure all previous tests pass
=> chore(debugger): refactor probe model

.circleci/config.yml, hooks/scripts/run-slotscheck.sh
#4989 reverted a previous change of using staged files only for the slotscheck job, and made it so that the slotscheck job runs on the entire repository. However, that change left code that checks for staged files in the precommit hook, which is now unnecessary as the slotscheck job now runs on the entire repository.
This PR also adds back the `-s: skip install` option to the riot command `riot -v run slotscheck` which was inadvertently removed in #4989.
=> chore(slotscheck): make slotscheck run on entire repository on precommit hook

ddtrace/internal/remoteconfig/client.py, releasenotes/notes/rcm-validations-162716c50ea90f1b.yaml
This PR contains two changes to the #4970 PR:
- Update the release note to clarify the scope + bug being fixed
- Rollback incorrect validation based on feedback from https://github.com/DataDog/dd-trace-py/pull/4974#discussion_r1089321493
=> fix(rcm): fix release note and validation logic from #4970

tests/profiling/_test_multiprocessing.py, tests/profiling/collector/test_stack.py, tests/profiling/simple_program_gevent.py
This change refactors some of the profiler tests to avoid incurring in potentially infinite loops that would cause the CI runs to stall indefinitely.
=> test(profiling): refactor to avoid infinite loops

.github/workflows/lib-injection.yml
This changed in https://github.com/DataDog/system-tests/pull/812.
=> fix: add required parameter for lib injection tests

.github/workflows/lib-injection.yml
This changed in https://github.com/DataDog/system-tests/pull/812.
=> fix: add required parameter for lib injection tests [backport #5009 to 1.7]

ddtrace/internal/writer.py
=> chore: fix writer log typo

ddtrace/appsec/_remoteconfiguration.py, ddtrace/appsec/ddwaf/__init__.py
=> fix(rcm): fix RCM tests

merge.json
This is A side of the conflict.
This PR should be added to the queue first.
Expectations:
* build should be uninterrupted
* CircleCI checks should be uninterrupted by the addition of B side to the queue
* PR should merge on its own
=> feat(ci): test merge queues: conflict, A side

merge.json
This is A side of the multiple non-conflicting PR test.
Expectations:
* PR should build
* PR should merge
=> feat(ci): test merge queues: move non-conflicting data around

merge.json
This is B side of the multiple non-conflicting PR test.
Expectations:
* PR should build
* PR should merge
=> feat(ci): test merge queues: change some data around

.gitlab-ci.yml
This PR introduces automatic deployment for the dynamic instrumentation demo services on every commit to the default branch.
=> ci(debugger): automatic demo service deployment

ddtrace/appsec/rules.json, tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json, tests/snapshots/tests.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json, tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot.json, tests/snapshots/tests.contrib.django.test_django_snapshots.test_appsec_enabled.json, tests/snapshots/tests.contrib.django.test_django_snapshots.test_appsec_enabled_attack.json
Update Datadog WAF rules to version 1.5.1
=> chore(asm): rules update 1.5.1

.github/workflows/test_frameworks.yml
Ubuntu 18.04 is being phased out so we need to update to a newer version.
https://github.com/actions/runner-images/issues/6002
=> chore(ci): update uwsgi framework test from ubuntu-18.04 to ubuntu-latest

ddtrace/contrib/django/patch.py
fix (small revert) for django-poc system test that was introduced a moment before in [PR 5152](https://github.com/DataDog/dd-trace-py/pull/5152)
=> ci(asm): fix failing django system test

tests/appsec/test_remoteconfiguration.py
=> fix(rcm): fix flaky rcm test

ddtrace/appsec/_remoteconfiguration.py
Update Remote Config log messages. Related to this comment: https://github.com/DataDog/dd-trace-py/pull/5184#discussion_r1120713520
=> chore(asm): update rcm log messages

.github/CODEOWNERS
This change puts more sources under the remit of the debugger-python team.
- ~~Testing strategy is described if automated tests are not included in the PR.~~
- ~~Risk is outlined (performance impact, potential for breakage, maintainability, etc).~~
- ~~Change is maintainable (easy to change, telemetry, documentation).~~
- ~~[Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines) are followed.~~
- ~~Documentation is included (in-code, generated user docs, [public corp docs]~~(https://github.com/DataDog/documentation/)).
- ~~Author is aware of the performance implications of this PR as reported in the benchmarks PR comment.~~
=> chore: improve debugging CODEOWNERS section

ddtrace/contrib/pylons/middleware.py, releasenotes/notes/fix-unicode-decode-errors-pylons-52d28b22f82e184a.yaml, tests/contrib/pylons/test_pylons.py
=> fix(asm): fix unicode decode errors in pylons [backport #5029 to 1.6]

ddtrace/appsec/ddwaf/__init__.py
Ensure that the WAF mockup (used in case the dynamic library for the WAF has not been loaded properly) has the same signature as the regular WAF.
=> chore(asm): add missing methods to WAF mockup

ddtrace/appsec/ddwaf/__init__.py
To avoid memory leak, destroy previous handle after a new handle is created by an update from remote config.
=> chore(asm): free old waf handle after remote config update

ddtrace/appsec/_remoteconfiguration.py, ddtrace/internal/remoteconfig/client.py, releasenotes/notes/rcm-fix-product-callback-d4d33b56ed8e17b4.yaml, tests/appsec/test_remoteconfiguration.py
Backport to 1.9 of: https://github.com/DataDog/dd-trace-py/pull/5249
=> fix(rcm): check if the product callback exists  [backport to 1.9]

ddtrace/appsec/rules.json, tests/appsec/rules-good.json, tests/appsec/test_processor.py, tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json, tests/snapshots/tests.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json, tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Update Datadog rule file for the WAF to 1.5.2.
Update file version of rules-good test file.
=> chore(asm): update dd appsec rules to 1.5.2

ddtrace/internal/remoteconfig/__init__.py
https://github.com/DataDog/dd-trace-py/pull/5223
=> chore(rcm): update warning message (backport #5223 to 1.9)

.circleci/config.yml, ddtrace/contrib/redis/patch.py, ddtrace/contrib/redis/util.py, releasenotes/notes/add-support-for-redis-py-cluster-265c66546f843efa.yaml, riotfile.py, tests/contrib/redis/test_redis_cluster.py, tests/contrib/rediscluster/test.py
Resolves: https://github.com/DataDog/dd-trace-py/issues/5157
=> feat(redis): add support for redis cluster

ddtrace/internal/remoteconfig/client.py
=> chore(rcm): improve logs message

.circleci/config.yml, scripts/ddtest, tests/contrib/starlette/test_starlette.py
backports: https://github.com/DataDog/dd-trace-py/pull/5304
=> ci: pin riot and fix starlette tests [backport #5304 to 1.9]

releasenotes/notes/fix-asm-taint-tracking-compilation-8c740752bd9df137.yaml, setup.py
backport:  https://github.com/DataDog/dd-trace-py/pull/5289
=> fix(asm): ensure platform can compile taint tracking sources [backport #5289 to 1.9]

.circleci/config.yml, scripts/ddtest, tests/contrib/starlette/test_starlette.py
backports: https://github.com/DataDog/dd-trace-py/pull/5304
=> ci: pin riot and fix starlette tests [backport #5304 to 1.8]

releasenotes/notes/fix-asm-taint-tracking-compilation-8c740752bd9df137.yaml, setup.py
backport: https://github.com/DataDog/dd-trace-py/pull/5289
---------
=> fix(asm): ensure platform can compile taint tracking sources [backport #5289 to 1.10]

ddtrace/contrib/botocore/patch.py, releasenotes/notes/fix-botocore-newline-str-issues-fab81e395207b0ed.yaml, tests/contrib/botocore/test.py
Backports: https://github.com/DataDog/dd-trace-py/pull/5317
=> fix(botocore): fix kinesis typeerror [backports #5317 to 1.10]

ddtrace/contrib/botocore/patch.py, releasenotes/notes/fix-botocore-newline-str-issues-fab81e395207b0ed.yaml, tests/contrib/botocore/test.py
Backports: https://github.com/DataDog/dd-trace-py/pull/5317
=> fix(botocore): fix kinesis typeerror [backports #5317 to 1.8]

scripts/backport
This change makes the automatic remote detection in scripts/backport more robust, and will ensure it falls back to a sane default of 'origin' if anything fails.
=> chore(ci): improve remote detection for scripts/backport

.circleci/config.yml
Backports: https://github.com/DataDog/dd-trace-py/pull/5349
=> ci(aws_lambda): run aws lambda tests in circleci [backport #5349 to 1.10]

.github/workflows/lib-injection.yml
Currently there are integration tests for the library injection image. These do a good job of ensuring the injection mechanism is working end to end in a real Kubernetes instance with the tradeoff of being quite complex and flaky.
The integration testing framework is overkill for testing the mechanism itself. Kubernetes is not required to validate different scenarios.
Instead, the injection mechanism can be tested more directly by running the test Docker application images with the environment variables and volume mount that the Kubernetes injection logic installs. This enables us to write more test cases and not have to depend on the complexity and flakiness of having to build images, run Kubernetes, etc.
=> chore(lib-injection): add unit tests

ddtrace/contrib/aws_lambda/patch.py, releasenotes/notes/fix-aws-lambda-infinite-recursion-crash-2cba8a190411cc7e.yaml, tests/contrib/aws_lambda/test_aws_lambda.py
Backports: https://github.com/DataDog/dd-trace-py/pull/5314
=> fix(aws_lambda): fix infinite recursion when wrapping signals [backport #5314 to 1.10]

ddtrace/debugging/_debugger.py, ddtrace/internal/remoteconfig/__init__.py, releasenotes/notes/rcm-fix-disable-f45787a4e6576f53.yaml, tests/contrib/gunicorn/test_gunicorn.py, tests/internal/remoteconfig/test_remoteconfig.py
Backports: https://github.com/DataDog/dd-trace-py/pull/5241/files
Resolves: https://github.com/DataDog/dd-trace-py/issues/5343
=> fix(rcm): validate remote config is enabled [backport #5241 to 1.9]

.circleci/config.yml, tests/contrib/aws_lambda/test_aws_lambda.py
Backports: https://github.com/DataDog/dd-trace-py/pull/5349
=> ci(aws_lambda): run aws lambda tests in circleci [backport #5349 to 1.9]

.github/workflows/system-tests.yml
This PR installs python 3.9 for system tests jobs.
System test executor will run on the host rather than inside a container (see https://github.com/DataDog/system-tests/pull/958). It will allow users to do step-by-step debugging, and will allow to unify architecture with parametric tests.
As now, the change will do nothing but installing python 3.9 on system tests job. Once the PR on system repo will be merge, it'll work silently (and we'll be able to remove the installation of docker compose, not required anymore).
=> fix(system-tests): setup python 3.9 for system tests

ddtrace/appsec/ddwaf/__init__.py, ddtrace/appsec/ddwaf/ddwaf_types.py
Change log level to debug to avoid filling up customers' logs
Fixes #5415
=> chore(asm): change waf log level to debug

ddtrace/appsec/iast/reporter.py, ddtrace/appsec/iast/taint_sinks/_base.py, tests/appsec/iast/test_reporter.py
IAST: According to RFC's span id is sent as a location attribute, not as a vulnerability one.
=> chore(asm): move span id from vulnerability to location

ddtrace/appsec/iast/reporter.py, ddtrace/appsec/iast/taint_sinks/_base.py, tests/appsec/iast/test_reporter.py, tests/appsec/iast/test_weak_hash.py
IAST: Adjust payload to current schema by removing evidence type
=> chore(asm): iast remove evidence type from json

ddtrace/contrib/dbapi/__init__.py, docs/spelling_wordlist.txt, releasenotes/notes/dbm-support-sql-queries-with-the-type-bytes-30fb4b75ea2f8cf8.yaml, tests/contrib/dbapi/test_dbapi.py, tests/contrib/psycopg/test_psycopg.py, tests/snapshots/tests.contrib.psycopg.test_psycopg.test_postgres_dbm_propagation_tag.json
Backports: https://github.com/DataDog/dd-trace-py/pull/5188
=> fix(dbm): support byte string queries [backports #5188 to 1.8]

ddtrace/internal/wrapping.py, tests/internal/py36/test_wrapping.py, tests/internal/py37/test_wrapping.py
This change simplifies the handling of the stop iteration exception in the bytecode wrapping of generators. In doing so we also gain support for async context managers.
=> chore: better stop iteration handling in wrapping

ddtrace/debugging/_capture/metric_sample.py, ddtrace/debugging/_capture/model.py, ddtrace/debugging/_capture/snapshot.py, ddtrace/debugging/_capture/tracing.py, ddtrace/debugging/_debugger.py, tests/debugging/capture/test_collector.py, tests/debugging/test_debugger.py
This change simplifies the internal API of the line capture events by removing unnecessary arguments. These can be worked out internally by each event subclass, and in tests one can simply create the required data by defining auxiliary functions.
=> refactor(debugging): simplify line capture event API

.circleci/config.yml, .riot/requirements/11304ce.txt, .riot/requirements/145d12f.txt, .riot/requirements/15eed6c.txt, .riot/requirements/1666b9d.txt, .riot/requirements/168056a.txt, .riot/requirements/16d9484.txt, .riot/requirements/1747910.txt, .riot/requirements/1bf9ccc.txt, .riot/requirements/1e3fff3.txt, .riot/requirements/1ed0e35.txt, .riot/requirements/1f61f0f.txt, .riot/requirements/1f99b32.txt, .riot/requirements/227eb61.txt, .riot/requirements/a178330.txt, .riot/requirements/aeb635b.txt, .riot/requirements/b335fe2.txt, .riot/requirements/bd1ac0d.txt, .riot/requirements/bdbe5d0.txt, .riot/requirements/c7f001b.txt, .riot/requirements/cc92558.txt, .riot/requirements/db2eaee.txt, .riot/requirements/f433975.txt, docker-compose.yml
Django 4.2 does not support PostgreSQL<=11. [Error](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/32189/workflows/4cd07666-057d-4959-9063-cb4aef3be273/jobs/2183711/parallel-runs/0/steps/0-108):
```
self = <DatabaseWrapper vendor='postgresql' alias='__no_db__'>
def check_database_version_supported(self):
"""
Raise an error if the database version isn't supported by this
version of Django.
"""
if (
self.features.minimum_database_version is not None
and self.get_database_version() < self.features.minimum_database_version
):
db_version = ".".join(map(str, self.get_database_version()))
min_db_version = ".".join(map(str, self.features.minimum_database_version))
>           raise NotSupportedError(
f"{self.display_name} {min_db_version} or later is required "
f"(found …
```
=> ci(django): ensure tests are compatible with django 4.2

riotfile.py
Backports: https://github.com/DataDog/dd-trace-py/pull/5484
=> ci(sanic): pin websockets in sanic tests [backports #5484 to 1.10]

.circleci/config.yml, docker-compose.yml
Backports: https://github.com/DataDog/dd-trace-py/pull/5505
=> ci(django): ensure tests are compatible with django 4.2 [backport #5505 to 1.10]

.circleci/config.yml, docker-compose.yml
Backports: https://github.com/DataDog/dd-trace-py/pull/5505
=> ci(django): ensure tests are compatible with django 4.2 [backport #5505 to 1.9]

ddtrace/appsec/_remoteconfiguration.py, setup.py, tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json, tests/snapshots/tests.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json, tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot.json, tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
- update libddwaf to 1.9.0
- remove some useless fields at definition of waf ruleset
=> chore(asm): update libddwaf to 1.9.0

ddtrace/appsec/iast/reporter.py, tests/appsec/iast/test_weak_hash.py
IAST: Change the vulnerability hash field to use a simpler algorithm that will return the same result among different executions.
=> chore(asm): iast fix vulnerability report hash

tests/conftest.py
This option is useful if a developer would like to switch between querying a real agent (end-to-end testing) and integration testing with the test agent.
=> chore(ci): add DD_SNAPSHOT_ENABLED to skip snapshots

.gitlab/benchmarks.yml, benchmarks/tracer/scenario.py
Fix Benchmark CI:
- Tracer scenario error: https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-py/-/jobs/256011926
```
File "/app/candidate/benchmarks/scenario.py", line 3, in <module>
from ..bm import utils
ImportError: attempted relative import with no known parent package
File "/app/candidate/benchmarks/scenario.py", line 3, in <module>
from ..bm import utils
ImportError: attempted relative import with no known parent package
```
- Add Otel_span scenario to `.gitlab/benchmarks.yml` list:
=> fix(benchmark): tracer error, add otel_span to scenarios list

ddtrace/appsec/_asm_request_context.py, tests/appsec/test_asm_request_context.py
Activate asm context only if asm is activated
=> chore(asm): activate asm context only in asm

ddtrace/internal/ci_visibility/encoder.py, ddtrace/internal/ci_visibility/writer.py, ddtrace/internal/writer/writer.py, tests/contrib/pytest/test_pytest.py, tests/tracer/test_encoders.py, tests/tracer/test_writer.py
* Updates test event version to match reality
* Ensures that ID fields are integers >= 1, required by the intake
* Sets the Content-Type header on agentless requests
* Adds debug logging showing payloads and responses
* Adds a test check for the repository url span tag
=> chore(pytest): civisibility adjustments from integration testing

scripts/release.py
=> chore(release_script): fix patch version

ddtrace/opentelemetry/__init__.py, releasenotes/notes/fix-otel-docs-formatting-1-5e555fa29a0c4ba4.yaml
Current formatting:
link: https://ddtrace.readthedocs.io/en/v1.12.1/api.html#opentelemetry-api
Fix:
link: https://output.circle-artifacts.com/output/job/5f8dc586-b7e0-4fa4-8721-502a13fb2980/artifacts/0/tmp/docs/api.html
=> docs(otel): fix formatting

releasenotes/notes/fix-redis-cross-import-40590b3d41f96dcc.yaml
This PR adds a release note corresponding to the fix from #5608 that was not marked as a fix.
=> fix(redis): add release note for redis cross import fix

releasenotes/notes/fix-asm-request-context-partial-flushing-7c45aaf55e836261.yaml
=> fix(appsec): add release note for 5822

ddtrace/contrib/asgi/middleware.py, releasenotes/notes/fastapi-set-error-tags-before-finishing-span-8fc48f94909251c1.yaml, tests/contrib/asgi/test_asgi.py, tests/contrib/fastapi/test_fastapi.py, tests/contrib/starlette/test_starlette.py, tests/snapshots/tests.contrib.fastapi.test_fastapi.test_500_error_raised.json
Backports: https://github.com/DataDog/dd-trace-py/pull/5818
=> fix(asgi): ensure error tags are set on request spans (backports #5818 to 1.10)

ddtrace/contrib/asgi/middleware.py, releasenotes/notes/fastapi-set-error-tags-before-finishing-span-8fc48f94909251c1.yaml, tests/contrib/asgi/test_asgi.py, tests/contrib/fastapi/test_fastapi.py, tests/contrib/starlette/test_starlette.py, tests/snapshots/tests.contrib.fastapi.test_fastapi.test_500_error_raised.json
Backports: https://github.com/DataDog/dd-trace-py/pull/5818
=> fix(asgi): ensure error tags are set on request spans [backports #5818 to 1.12]

ddtrace/contrib/asgi/middleware.py, releasenotes/notes/fastapi-set-error-tags-before-finishing-span-8fc48f94909251c1.yaml, tests/contrib/asgi/test_asgi.py, tests/contrib/fastapi/test_fastapi.py, tests/contrib/starlette/test_starlette.py, tests/snapshots/tests.contrib.fastapi.test_fastapi.test_500_error_raised.json
Backports: https://github.com/DataDog/dd-trace-py/pull/5818
=> fix(asgi): ensure error tags are set on request spans (backport #5818 to 1.13)

ddtrace/contrib/asgi/middleware.py, tests/contrib/asgi/test_asgi.py, tests/contrib/fastapi/test_fastapi.py, tests/contrib/starlette/test_starlette.py
Backports: https://github.com/DataDog/dd-trace-py/pull/5849
=> chore(asgi): revert regression that removed support for background tasks (backport #5849 to 1.12)

ddtrace/contrib/asgi/middleware.py, tests/contrib/asgi/test_asgi.py, tests/contrib/fastapi/test_fastapi.py, tests/contrib/starlette/test_starlette.py
Backports: https://github.com/DataDog/dd-trace-py/pull/5849
=> chore(asgi): revert regression that removed support for background tasks (backport #5849 to 1.10)

ddtrace/appsec/_constants.py, ddtrace/contrib/django/patch.py, tests/contrib/django/django_app/appsec_urls.py, tests/contrib/django/test_django_appsec.py
IAST: Taint Django path with the proper source origin information
=> chore(asm): iast taint django path

ddtrace/_monkey.py, ddtrace/bootstrap/sitecustomize.py, releasenotes/notes/ensure-ddtracerun-respects-disabled-integrations-ea1952a79a353bf0.yaml, tests/commands/ddtrace_run_patched_modules_overrides.py, tests/commands/test_runner.py
Resolves: https://github.com/DataDog/dd-trace-py/issues/5458
=> fix(tracing): ensure integrations can be disabled (backport #5856 to 1.13)

ddtrace/internal/wrapping.py
Tidy up the compatibility support for the different versions of the supported CPython bytecode versions in the wrapping submodule to make it more easily maintainable as new versions of CPython are released that introduce bytecode breaking changes.
=> refactor(internal): tidy up versioning in wrapping submodule

ddtrace/contrib/django/utils.py, releasenotes/notes/django-fix-view-names-55a357e1ac903ea5.yaml, tests/contrib/django/test_django.py, tests/contrib/django/test_django_snapshots.py, tests/snapshots/tests.contrib.django.test_django_snapshots.test_django_resource_handler.json
Resolves: https://github.com/DataDog/dd-trace-py/issues/5711
=> fix(django): include the view class name in resource names (backport #5891 to 1.12)

ddtrace/profiling/_threading.pyx
=> chore(profiling): use new module watchdog decorator

ddtrace/ext/sql.py, docs/spelling_wordlist.txt, releasenotes/notes/fix-tracer-parse-pg-dsn-take2-7ef89362545b2721.yaml, tests/contrib/psycopg/test_psycopg.py, tests/contrib/psycopg2/test_psycopg.py
=> fix(sql): use psycopg's parse_dsn when available (backport #5927 to 1.14)

ddtrace/contrib/pyramid/trace.py, releasenotes/notes/add-http-route-to-pyramid-23eab91880ac8e0e.yaml, tests/contrib/pyramid/app/web.py, tests/contrib/pyramid/test_pyramid.py, tests/snapshots/tests.contrib.pyramid.test_pyramid.test_simple_pyramid_app_endpoint.json, tests/snapshots/tests.contrib.pyramid.test_pyramid.test_simple_pyramid_app_endpoint[ddtrace-run_pserve_tests_contrib_pyramid_pserve_app_development.ini].json, tests/snapshots/tests.contrib.pyramid.test_pyramid.test_simple_pyramid_app_endpoint[ddtrace-run_python_tests_contrib_pyramid_app_app.py].json
Added support for the http.route tag in pyramid.
=> feat(pyramid): added http.route support for spans in pyramid

.github/workflows/build_deploy.yml
Backport of #5908 to 1.14
The resulting file name is something like `ddtrace-1.14.0rc1-all.tar.gz`
Failed job: https://github.com/DataDog/dd-trace-py/actions/runs/5015773964/jobs/8996024129
> Uploaded /home/runner/work/dd-trace-py/dd-trace-py/ddtrace-1.14.0rc1-all.tar.gz (100.0%) bytes 218103808:218366029
> stat *.all.tar.gz: no such file or directory
=> ci(build-deploy): fix incorrect glob for uploading artifact.. [backport #5908 to 1.14]

tests/appsec/test_remoteconfiguration_e2e.py
update `tests/appsec/test_remoteconfiguration_e2e.py` to remove some flakyness due to time.sleep
=> chore(asm): remove some flakyness in appsec tests

.github/workflows/system-tests.yml
##
Following DataDog/system-tests/pull/1117, APPSEC_IP_BLOCKING and APPSEC_IP_BLOCKING_MAXED scenarios has been merged and renamed in APPSEC_BLOCKING_FULL_DENYLIST
=> chore(test): rename system-tests scenario

ddtrace/contrib/openai/patch.py, releasenotes/notes/fix-openai-embeddings-pc-sample-rate-52a8433eb22833e1.yaml, tests/contrib/openai/test_openai.py
(cherry picked from commit 93d700ea02319617593992b273141134f12b0d24)
=> fix(openai): ensure embeddings input gets pc sampled correctly [backport to 1.13]

releasenotes/notes/fix-pytest-skip-fail-information-if-testcase-used-f8ccd7bf90615d78.yaml
=> ci: fix failing spellcheck in release note

ddtrace/contrib/langchain/patch.py, tests/contrib/langchain/test_langchain.py
This PR does not require a release note as the LangChain PR has not been released yet.
This PR fixes the scenario where creating logs raises an `UnboundLocalError: local variable XYZ referenced before assignment` because we reference data returned by the response when creating the log. This would only happen when errors happen before the response is returned in the middle of our tracing. Now, we will log an empty output attribute on the log instead of referencing a value that may not exist.
Regression tests were added to ensure logs are sent properly even if the response is not set/returned.
=> chore(langchain): ensure error logs are sent when responses not completed

.github/workflows/system-tests.yml
=> ci: run system tests when necessary on PRs

ddtrace/appsec/iast/reporter.py, tests/appsec/iast/fixtures/weak_algorithms.py, tests/appsec/iast/iast_utils.py, tests/appsec/iast/test_weak_cipher.py, tests/appsec/iast/test_weak_hash.py, tests/contrib/django/test_django_appsec_iast.py
=> chore(iast): update iast hash report

tests/contrib/subprocess/test_subprocess.py
=> chore(asm): fix unused var

scripts/needs_testrun.py
When we cannot query the GitHub API for the changed files within a PR, we rely on the local git information to determine the merge base for a more accurate result.
=> ci: diff against merge base

.github/workflows/django-overhead-profile.yml, .github/workflows/encoders-profile.yml, .github/workflows/flask-overhead-profile.yml
=> ci: run profile jobs when needed

scripts/gen_circleci_config.py
=> ci: validate suitespec JSON

.github/workflows/system-tests.yml
CI: Makes system-tests steps conditional in order to make the job pass if they are not run
=> ci: system-tests steps conditional so the job can be required and skipped

scripts/gen_circleci_config.py
The snapshot formatting check should not validate a diff including all dd-trace-py files.
Attempts to address the following test failure: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/42731/workflows/b09dd58f-8f85-4fa6-bddc-f85970b4c6db/jobs/2843113.
=> ci(pre-check): fix failing hatch check

ddtrace/appsec/iast/_taint_tracking/aspects.py
=> chore(iast): bytes and bytearray propagation

tests/appsec/iast/test_iast_mem_check.py, tests/appsec/iast/test_iast_propagation_path.py
=> chore(iast): add memory tests

scripts/needs_testrun.py
Backport of #6818 to 1.18
We make sure to fetch all the pages from the call to the pull request GitHub REST API so that we can get the full list of changed files, instead of just the first 30 entries.
=> ci: use pagination to retrieve complete list of changed files [backport #6818 to 1.18]

ddtrace/appsec/ddwaf/__init__.py, ddtrace/appsec/iast/__init__.py, ddtrace/appsec/iast/_ast/ast_patching.py, ddtrace/appsec/iast/_ast/visitor.py, ddtrace/appsec/iast/_metrics.py, ddtrace/appsec/iast/_patch.py, ddtrace/appsec/iast/_patches/json_tainting.py, ddtrace/appsec/iast/_taint_dict.py, ddtrace/appsec/iast/_taint_tracking/__init__.py, ddtrace/appsec/iast/_taint_tracking/aspects.py, ddtrace/appsec/iast/_taint_utils.py, ddtrace/appsec/iast/processor.py, ddtrace/appsec/iast/taint_sinks/__init__.py, ddtrace/appsec/iast/taint_sinks/_base.py, ddtrace/appsec/iast/taint_sinks/command_injection.py, ddtrace/appsec/iast/taint_sinks/insecure_cookie.py, ddtrace/appsec/iast/taint_sinks/path_traversal.py, ddtrace/appsec/iast/taint_sinks/sql_injection.py, ddtrace/appsec/iast/taint_sinks/weak_cipher.py, ddtrace/appsec/iast/taint_sinks/weak_hash.py
=> refactor(iast): refactor imports to make them local

benchmarks/appsec_iast_propagation/scenario.py
=> fix(benchmark/iast): fix import error in propagation scenario

docs/spelling_wordlist.txt, releasenotes/notes/add-312-73857cf79c64c924.yaml, releasenotes/notes/release-2.0-3af0045e2261bd02.yaml
Minor revisions to release note.
=> chore(2.0): revisions to release notes

releasenotes/notes/release-2.0-3af0045e2261bd02.yaml
=> chore(release): update version to upgrade to

releasenotes/notes/release-2.0-3af0045e2261bd02.yaml
(cherry picked from commit b5b0bf1980f80be5552ad27f4b8178f18dd4bad0)
=> chore(release): update version to upgrade to (backport #6956 to 2.0)

README.md
=> chore: update circleci badge

.github/workflows/system-tests.yml
System tests are scheduled, but the recent check that compute if the run is needed is not working in that use case.
Also simplifying a little bit the yaml file.
=> chore(ci): fix scheduled system tests

ddtrace/appsec/_iast/_ast/visitor.py, ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp, ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.h, ddtrace/appsec/_iast/_taint_tracking/README.txt, ddtrace/appsec/_iast/_taint_tracking/_native.cpp, ddtrace/appsec/_iast/_taint_tracking/aspects.py, tests/appsec/iast/aspects/test_index_aspect_fixtures.py, tests/appsec/iast/fixtures/aspects/str_methods.py
=> feat(iast): index propagation

ddtrace/appsec/_iast/_ast/visitor.py, ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSlice.cpp, ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSlice.h, ddtrace/appsec/_iast/_taint_tracking/_native.cpp, ddtrace/appsec/_iast/_taint_tracking/aspects.py, tests/appsec/iast/aspects/test_slice_aspect_fixtures.py, tests/appsec/iast/fixtures/propagation_path.py, tests/appsec/iast/test_iast_mem_check.py, tests/appsec/iast/test_iast_propagation_path.py
=> feat(iast): slice propagation

.github/workflows/system-tests.yml
=> chore(ci): remove forgotten if at job level in system tests ci

tests/tracer/runtime/test_metric_collectors.py
relax a condition to get less flaky failures on CI in tracer test.
=> chore(tests): tracer test relaxed

ddtrace/appsec/_capabilities.py
drop python 2 and `ddtrace.internal.compat` dependency in `appsec/_capabilities.py`
simplify some imports
follows https://github.com/DataDog/dd-trace-py/pull/7121
=> chore(asm): migrate appsec capabilities to drop python2 compatibility

ddtrace/appsec/_iast/taint_sinks/ssrf.py
System tests are rising a SSRF assert error due to a conflict between IAST PRs
The problem followed the flow below:
- We added the SSRF feature in this PR https://github.com/DataDog/dd-trace-py/pull/7139
- We updated and tested that PR locally on the system test, but we set a future version, 2.2.0, here https://github.com/DataDog/system-tests/pull/1660  
- Then, we didn't notice that we have conflicts between https://github.com/DataDog/dd-trace-py/pull/7149 and https://github.com/DataDog/dd-trace-py/pull/7139 and SSRF metrics stopped working
- Now, when we published version 2.2.0 these days, the error has been raised
=> fix(iast): ssrf telemetry metrics

docs/spelling_wordlist.txt
=> chore: add prepend spelling

ddtrace/opentelemetry/_context.py
Currently we are relying on opentelemetry-api internal constants. This approach is brittle and can break at anytime. This PR refactor context management in the OpenTelemetry Datadog API to only use public functions and classes.
This PR does not change any functionality. No tests are required.
=> chore(opentelemetry): avoid using opentelemetry api internals

ddtrace/appsec/_iast/_stacktrace.c, ddtrace/appsec/_iast/_stacktrace_py2.py, ddtrace/appsec/_trace_utils.py, ddtrace/contrib/flask_login/patch.py, tests/appsec/iast/taint_sinks/test_weak_hash.py
Reverts DataDog/dd-trace-py#7482
=> Revert "fix: user login event report error"

.gitlab-ci.yml, releasenotes/notes/package_arm-1beb3c4a7d6f945a.yaml
We are adding ARM64 support for Single-Step instrumentation. The work is tracker in Jira at https://datadoghq.atlassian.net/browse/APMON-252 . 
As part of this work, we need to build RPMs/DEBs with arm64 binaries. This PR adds a step to the gitlab pipeline that should do this.
Testing strategy:
It's primarily manual. 
- We need to get a pipeline run
- The agent-install team needs to manually publish the RPM/DEB
- We (I) need to stand up an arm64 vm, try to install the package from it, and then ensure that a program can be successfully instrumented.
Risk:
A mistake in the gitlab script could break the build pipeline. No code changes are being made.
Maintainable:
Once arm64 support is working, there's nothing further to do.
No additional documentation or backporting is required in the …
=> fix(lib-inject): enable arm builds

tests/.suitespec.json
Remove appsec_integrations suite from "flask" suite as it's not needed
=> ci: remove appsec_integrations suite from "flask" suite

.github/workflows/lib-injection.yml, lib-injection/Dockerfile, releasenotes/notes/lib-inject-execute_perm-e8a4c834895a6372.yaml
Resolves: https://github.com/DataDog/dd-trace-py/issues/7454
=> fix(lib-inject): set execute permissions on package files 

ddtrace/appsec/rules.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
update appsec event rules to version 1.9.0
=> chore(asm): update security rules to 1.9.0

tests/appsec/iast_memcheck/test_iast_mem_check.py
=> ci(iast): fix flaky test

ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSlice.cpp
IAST aspect error introduced in https://github.com/DataDog/dd-trace-py/pull/7753/files
=> fix(iast): slice aspect with negative stop values

tests/profiling/simple_program_gevent.py
We fix the import and patching order in the simple gevent program script to match what a user is supposed to do to correctly initialise the library when using the programmatic API.
=> test(profiling): import and patching order

tests/.suitespec.json
This PR removes a previously deleted file `_trace_utils_llm.py` from the suitespec JSON file which was causing CI failures in precheck.
=> fix(ci): remove deleted file from suitespec

tests/.suitespec.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
Reverts DataDog/dd-trace-py#8393
=> Revert "ci(django): regenerate django appsec snapshots [backport 2.4]"

tests/telemetry/test_telemetry.py
This change fixes failures [like this](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/55920/workflows/d8807f78-fd90-45cd-a7ef-0e5f8d398a1a/jobs/3557288) arising from the unreliability of a telemetry test.
=> ci: mark flaky telemetry test

.github/workflows/system-tests.yml
=> chore: fix system tests

tests/appsec/contrib_appsec/test_fastapi.py
Use a 5 seconds waf timeout for fastapi unit tests (due to multithreading in FastAPI) on Threats to avoid waf timeouts on slow CI.
=> chore(asm): less flakyness in fastapi tests

ddtrace/appsec/_handlers.py
functions in `ddtrace/appsec/_handlers.py` must not raise exceptions.
This PR ensure that we catch all exceptions no matter what.
=> chore(asm): catch all exceptions

CHANGELOG.md
=> chore: update changelog for version 2.7.6

scripts/release.py
When I used release script for 2.8 release:
errored out on this step:
```
File "/Users/zach.groves/projects/dd-trace-py/scripts/release.py", line 489, in <module>
create_changelog_pull_request(dd_repo, name, rn)
File "/Users/zach.groves/projects/dd-trace-py/scripts/release.py", line 276, in create_changelog_pull_request
commit_and_push(dd_repo, f"release.script/changelog-update-{name}", name)
File "/Users/zach.groves/projects/dd-trace-py/scripts/release.py", line 269, in commit_and_push
dd_repo.create_pull(DEFAULT_BRANCH, branch_name, title=f"chore: {pr_body}", body=f"- [x] {pr_body}", draft=False)
File "/Users/zach.groves/projects/dd-trace-py/scripts/venv/lib/python3.9/site-packages/github/Repository.py", line 1399, in create_pull
return …
```
=> chore: release script make create_pull all kwargs, better file adding for changelog

CHANGELOG.md
=> chore: update changelog for version 2.8.2

CHANGELOG.md
=> chore: update changelog for version 2.6.11

CHANGELOG.md
=> chore: update changelog for version 2.7.9

CHANGELOG.md
=> chore: update changelog for version 2.7.10 via release script

tests/profiling/collector/test_threading.py
This change updates a line-number expectation in the profiling test suite to match reality.
=> ci(profiling): adjust expectation

ddtrace/appsec/_iast/_taint_tracking/__init__.py, tests/appsec/iast/aspects/test_side_effects.py, tests/appsec/iast/iast_utils_side_effects.py
=> fix(iast): ensure no side-effects in IAST encode aspect

ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectFormat.cpp, ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp, ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.h, ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.cpp, ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.cpp, ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSplit.cpp, ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectsOsPath.cpp, ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp, ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h, ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.cpp, ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.h, ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp, ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h, ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.cpp, ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.h, ddtrace/appsec/_iast/_taint_tracking/__init__.py, tests/appsec/iast/aspects/test_add_aspect.py, tests/appsec/iast/aspects/test_bytearray_extend_aspect.py, tests/appsec/iast/aspects/test_format_aspect_fixtures.py, tests/appsec/iast/aspects/test_index_aspect_fixtures.py, tests/appsec/iast/aspects/test_join_aspect_fixtures.py, tests/appsec/iast/aspects/test_ospath_aspects_fixtures.py, tests/appsec/iast/aspects/test_slice_aspect_fixtures.py, tests/appsec/iast/aspects/test_split_aspect.py, tests/appsec/iast/taint_tracking/test_taint_tracking.py
=> Christophe papazian/tmp branch to merge

CHANGELOG.md
=> chore: update changelog for version 2.8.5

ddtrace/appsec/_iast/_overhead_control_engine.py
Fixes regression introduced in #9307
=> fix(iast): fix threading import regression

setup.py
=> chore: exclude scripts folder in build package step

tests/appsec/iast/aspects/test_common_aspects.py
=> chore: remove unneeded import from test_common_aspects

.gitlab/macrobenchmarks.yml
=> ci: macrobenchmark use a better endpoint for iast worst case scenarios

.github/CODEOWNERS
=> chore(codeowners): make @DataDog/profiling-python owners of ddtrace/settings/profiling.py

releasenotes/notes/asm-boto-denylist-9ea0dee3a33fff7c.yaml
Add changelog for https://github.com/DataDog/dd-trace-py/pull/9784 which merged too fast.
=> chore: add changelog for #9784

tests/commands/test_runner.py
=> chore(profiling): enable test

scripts/gen_circleci_config.py
=> chore(ci): trigger `riot run lint:typing` for `mypy.ini` changes

ddtrace/profiling/collector/_lock.py, ddtrace/profiling/collector/asyncio.py, ddtrace/profiling/collector/memalloc.py, ddtrace/profiling/collector/stack_event.py, ddtrace/profiling/collector/threading.py, ddtrace/profiling/event.py
=> chore(profiling): use `__slots__` instead of `attr.s(slots=True)` for Event classes

ddtrace/profiling/_threading.pyx, ddtrace/profiling/collector/stack.pyx
=> chore(profiling): remove `@attr.s` from `_Thread*Link` classes

ddtrace/internal/datadog/profiling/dd_wrapper/src/crashtracker_interface.cpp
=> chore(profiling): fix CI issues from crashtracker update

ddtrace/_trace/processor/__init__.py, tests/tracer/test_processors.py
Remove `attrs` dependency
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#inte …
=> chore: remove attrs from trace processor

ddtrace/_trace/_span_link.py
Remove `attrs` usage
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interface …
=> chore: remove attrs from _trace/_span_link.py

.gitlab/macrobenchmarks.yml
=> ci: add macrobenchmarks scenarios with profiling enabled

CHANGELOG.md
=> chore: update changelog for version 2.10.1

tests/appsec/iast_packages/test_packages.py
=> chore: ensure string comparison on package testing expected result

ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader_builder.cpp, releasenotes/notes/profiling-stack-v2-runtime-7a4700f8571deddc.yaml
=> fix(profiling): propagates runtime_id to libdatadog exporter

.clang-format, hooks/scripts/run-clang-format.sh, scripts/cformat.sh
=> chore: use .clang-format

docs/versioning.rst
=> docs: update the definition of internal

ddtrace/profiling/collector/_lock.py, ddtrace/profiling/collector/memalloc.py, ddtrace/profiling/collector/stack_event.py, ddtrace/profiling/event.py, ddtrace/profiling/scheduler.py
Makes profiling more compatible with mypy and fixes up some type errors along the way. …
=> chore(profiling): fix mypy typing in profiling

releasenotes/notes/profiling-add-lock-with-f75908e35a70ab71.yaml
=> chore: update release note wording for #9610

CHANGELOG.md
=> chore: update changelog for version 2.8.6

CHANGELOG.md
=> chore: update changelog for version 2.9.5

CHANGELOG.md
=> chore: update changelog for version 2.10.3

.github/workflows/build_deploy.yml
=> chore(ci): run build_deploy on release branches and build_deploy* branches

tests/profiling/collector/test_memalloc.py, tests/profiling/collector/test_stack.py, tests/profiling/collector/test_threading.py, tests/profiling/collector/utils.py, tests/profiling/test_main.py, tests/profiling/test_uwsgi.py
=> chore(profiling): fix flaky tests

ddtrace/internal/datadog/profiling/cmake/FindLibdatadog.cmake, ddtrace/internal/datadog/profiling/cmake/tools/libdatadog_checksums.txt, ddtrace/internal/datadog/profiling/dd_wrapper/include/crashtracker.hpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/crashtracker.cpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/crashtracker_interface.cpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/receiver_interface.cpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp
=> chore(profiling): use libdatadog version v12.0.0

.gitlab/build-oci.sh, releasenotes/notes/fix-ssi-permissions-647693af3d5ce49d.yaml
=> fix(SSI): set the right permissions

releasenotes/notes/fix-ssi-permissions-647693af3d5ce49d.yaml
=> docs: fix 2.9 release note

tests/appsec/iast_memcheck/test_iast_mem_check.py
=> ci: fix iast_memcheck flakyness

tests/appsec/contrib_appsec/utils.py
Small fix for 4 wrong asserts.
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html …
=> chore(asm): fix for threats test

CHANGELOG.md
=> chore: update changelog for version 2.10.4

ddtrace/settings/profiling.py
=> chore(profiling): set libdd_required when timeline_enabled

tests/.suitespec.json
Follow-up on #10172
- Adds ddtrace/contrib/internal for each refactored contrib module
- Runs telemetry tests for any contrib modified code …
=> chore(ci): update contrib suitespec

ddtrace/opentelemetry/_span.py, releasenotes/notes/otel-ensure-sampling-decision-is-made-40ab760eada20b20.yaml, tests/opentelemetry/test_trace.py, tests/snapshots/tests.opentelemetry.test_trace.test_distributed_trace_with_flask_app[with_ddtrace_run].json, tests/snapshots/tests.opentelemetry.test_trace.test_distributed_trace_with_flask_app[with_opentelemetry_instrument].json
=> fix(opentelemetry): resolve lazy sampling + distributed tracing bug (#9974 to 2.8)

releasenotes/notes/profiling-libdd-required-685835434cda9968.yaml
=> fix(profiling): add missing release note for #10182

ddtrace/internal/datadog/profiling/dd_wrapper/test/initialization.cpp, ddtrace/internal/datadog/profiling/dd_wrapper/test/test_utils.hpp
Tested using `./build_standalone.sh -- Release all_test` …
=> chore(profiling): update native tests

tests/.suitespec.json, tests/contrib/flask_cache/test_utils.py
Addresses https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/68834/workflows/ed71b2c4-add6-4bb2-8b09-8476dd466de4/jobs/4206305 . …
=> chore(flask): fix test_extract_redis_connection_metadata expected meta

CHANGELOG.md
=> chore: update changelog for version 2.8.7

CHANGELOG.md
=> chore: update changelog for version 2.10.6

tests/conftest.py
=> chore(ci): add logging when pytest raised OSError on shutdown

.gitlab-ci.yml
=> ci: enable onboarding_tests_installer tests

CHANGELOG.md
=> chore: update changelog for version 2.11.0

ddtrace/appsec/_iast/_ast/visitor.py, ddtrace/appsec/_iast/_taint_tracking/aspects.py, tests/appsec/app.py, tests/appsec/iast/aspects/test_re_aspects.py, tests/appsec/iast/fixtures/non_re_module.py, tests/appsec/integrations/test_flask_iast_patching.py
IAST: Aspect for `re.findall` function. …
=> chore(iast): `re.findall` aspect

CHANGELOG.md
=> chore: update changelog for version 2.11.1

ddtrace/contrib/internal/django/patch.py, releasenotes/notes/fix_django_db_connection_instrumentation-c23defb666caff3c.yaml
Ensure the instrumentation does not fail on non str/bytes attributes. …
=> fix(tracer): small fix for db instrumentation

.github/CODEOWNERS
=> chore: update iast codeowner

benchmarks/bm/iast_fixtures/str_methods.py, ddtrace/appsec/_iast/_ast/visitor.py, ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.cpp, ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.h, ddtrace/appsec/_iast/_taint_tracking/_native.cpp, ddtrace/appsec/_iast/_taint_tracking/aspects.py, tests/appsec/iast/_ast/test_ast_patching.py, tests/appsec/iast/aspects/test_add_aspect_fixtures.py, tests/appsec/iast/aspects/test_add_inplace_aspect.py, tests/appsec/iast/aspects/test_add_inplace_aspect_fixtures.py, tests/appsec/iast/aspects/test_other_patching.py, tests/appsec/iast/fixtures/ast/add_operator/inplace.py, tests/appsec/iast_packages/test_packages.py
IAST: Aspect for inplace add (`+=` operator) function. …
=> chore(iast): inplace add aspect

ddtrace/internal/datadog/profiling/ddup/_ddup.pyi, ddtrace/profiling/exporter/http.py, ddtrace/profiling/profiler.py, ddtrace/settings/profiling.py, releasenotes/notes/profiling-fix-tags-libdd-5aba4fd5ceb63539.yaml, tests/profiling/exporter/test_ddup.py, tests/profiling/exporter/test_http.py
=> fix(profiling): propagate tags when using libdatadog exporter

tests/appsec/iast/aspects/test_asyncio.py, tests/appsec/iast/fixtures/aspects/asyncio_functions.py
=> chore(iast): asyncio tests

ddtrace/debugging/_signal/model.py, ddtrace/debugging/_signal/snapshot.py
We fix more snapshot schema discrepancies to align with the other runtimes. …
=> chore(di): fix more snapshot schema discrepancies

.github/workflows/generate-package-versions.yml
=> ci: update frequency of auto-update package PR generation

tests/appsec/iast/aspects/test_add_inplace_aspect_fixtures.py
=> chore(iast): inplace add aspect tests

ddtrace/internal/flare/flare.py
=> chore: trivial change for test

tests/tracer/test_rate_limiter.py
=> ci: fix tracer rate_limiter flaky test

.github/workflows/system-tests.yml
Add APPSEC_STANDALONE scenario to appsec system tests on dd-trace-py CI. …
=> chore(asm): add appsec_standalone to system tests

.gitlab/release.yml
=> ci: make pypi test upload actually upload

.circleci/config.templ.yml, .gitlab/tests.yml, .gitlab/tests/contrib.yml
=> ci: move FastAPI tests from CircleCI to GitLab

tests/contrib/fastapi/test_fastapi_appsec_iast.py
=> chore(iast): testing fastapi and sqli

scripts/gen_circleci_config.py
circle ci is broken after #10487 …
=> ci: remove slotscheck and conftests from circleci

ddtrace/internal/flare/flare.py
=> chore: MQ TEST udpate flare.py

.circleci/config.templ.yml, .gitlab/tests/contrib.yml, tests/contrib/grpc/test_grpc.py
Migration of a large number of contrib jobs from CircleCI to GitLab. …
=> ci: move contrib jobs to GitLab

.gitlab-ci.yml, .gitlab/services.yml, .gitlab/tests.yml
Help prevent GHCR rate limits and timeouts …
=> ci: use mirrors testrunner and ddapm-test-agent

.github/workflows/backport.yml
=> ci: update required backport workflow permissions

CHANGELOG.md
=> chore: update changelog for version 2.12.0

CHANGELOG.md
=> chore: update changelog for version 2.11.4

tests/profiling-v2/collector/test_asyncio.py, tests/profiling-v2/collector/test_threading.py, tests/profiling/collector/pprof_utils.py
=> chore(profiling): asyncio lock collector tests with libdatadog exporter

.gitlab/tests/contrib.yml
Alphabetizing the test suites for readability. No functional changes in this PR. …
=> chore: alphabetize .gitlab/tests/contrib.yml

ddtrace/profiling/collector/_lock.py, releasenotes/notes/profiling-asyncio-lock-with-ef209edcdd346093.yaml, tests/profiling-v2/collector/test_asyncio.py, tests/profiling/collector/test_asyncio.py
=> feat(profiling): captures `asyncio.Lock` usages with `with` context managers

.circleci/config.templ.yml, .gitlab/services.yml, .gitlab/tests/appsec.yml, .gitlab/tests/contrib.yml
=> ci: move django tests from CircleCI to GitLab

CHANGELOG.md
=> chore: update changelog for version 2.11.6

.circleci/config.templ.yml, ddtrace/appsec/_iast/_ast/ast_patching.py, tests/appsec/iast_packages/test_packages.py
Code Security: Propagate for `tomli` package.
Tests for tomli propagation are passing: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/72073/workflows/a3511db9-0ade-4db2-8721-328f9cf085bd/jobs/4302073
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contribu …
=> chore(iast): fix `tomli` iast propagation

ddtrace/appsec/_iast/_patch.py, tests/contrib/fastapi/test_fastapi_appsec_iast.py
=> chore(iast): fastapi body

ddtrace/internal/coverage/instrumentation_py3_10.py
=> Avoid insert

pyproject.toml
Fix the usual version problem
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html# …
=> chore(tracer): fix version computation for 2.13 for system tests

pyproject.toml
Fix the usual version problem
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html# …
=> chore(tracer): fix version computation for 2.12 for system tests

ddtrace/appsec/_iast/_taint_tracking/Utils/PythonErrorGuard.cpp, ddtrace/appsec/_iast/_taint_tracking/Utils/PythonErrorGuard.h, ddtrace/appsec/_iast/_taint_tracking/tests/test_helpers.cpp
=> chore(iast): fix C format

ddtrace/appsec/_iast/_taint_tracking/_native.cpp
=> chore: run clang-format for 2.10 branch

ddtrace/appsec/_iast/_taint_tracking/_native.cpp
https://github.com/DataDog/dd-trace-py/pull/10782 didn't fix the issue - retrying.  …
=> chore: fix formatting

ddtrace/internal/datadog/profiling/ddup/_ddup.pyx
=> chore(profiling): prevent strings from GC'ed whose string_views are passed to native side

tests/appsec/iast/fixtures/propagation_path.py, tests/appsec/iast_memcheck/test_iast_mem_check.py
=> chore: asyncio mememory checks tests

ddtrace/appsec/_iast/_taint_tracking/tests/test_stringutils.cpp
Code Security: Add tests for PyIOBase_Check function …
=> chore(iast): pyiobase_check tests

ddtrace/profiling/event.py, tests/profiling/collector/test_stack.py, tests/profiling/exporter/test_pprof.py
=> chore(profiling): remove unused field, timestamp

.github/workflows/system-tests.yml
=> ci: add system-tests finished job (#10699)

CHANGELOG.md
=> chore: update changelog for version 2.12.1

CHANGELOG.md
=> chore: update changelog for version 2.12.2

CHANGELOG.md
=> chore: update changelog for version 2.14.1

ddtrace/bootstrap/preload.py, ddtrace/internal/products.py, tests/internal/test_products.py
We introduce a product plugin interface that allows us to implement dependency inversion for product life-cycle logic. This also allows us to encapsulate common support logic, such as the uWSGI master process forking support, so that individual products don't have to implement the same logic.
- Backport …
=> chore: introduce product plugin interface

ddtrace/appsec/_iast/_taint_tracking/tests/test_helpers.cpp
=> chore(iast): cformat test file

ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt, ddtrace/internal/datadog/profiling/stack_v2/__init__.py, ddtrace/internal/datadog/profiling/stack_v2/include/thread_span_links.hpp, ddtrace/internal/datadog/profiling/stack_v2/src/sampler.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/thread_span_links.cpp, ddtrace/profiling/collector/stack.pyx, releasenotes/notes/profiling-fix-stack-v2-endpoint-82a1e26366166b8d.yaml, tests/profiling_v2/collector/test_stack.py
=> fix(profiling): endpoint profiling for stack v2

ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt, ddtrace/internal/datadog/profiling/stack_v2/__init__.py, ddtrace/internal/datadog/profiling/stack_v2/include/thread_span_links.hpp, ddtrace/internal/datadog/profiling/stack_v2/src/sampler.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/thread_span_links.cpp, ddtrace/profiling/collector/stack.pyx, releasenotes/notes/profiling-fix-stack-v2-endpoint-82a1e26366166b8d.yaml, tests/profiling_v2/collector/test_stack.py
Manual backport of #10882 to 2.14 …
=> fix(profiling): endpoint profiling for stack v2 [backport-2.14]

ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt, ddtrace/internal/datadog/profiling/stack_v2/__init__.py, ddtrace/internal/datadog/profiling/stack_v2/include/thread_span_links.hpp, ddtrace/internal/datadog/profiling/stack_v2/src/sampler.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/thread_span_links.cpp, ddtrace/profiling/collector/stack.pyx, releasenotes/notes/profiling-fix-stack-v2-endpoint-82a1e26366166b8d.yaml
Manual backport of #10882 to 2.12 …
=> fix(profiling): endpoint profiling for stack v2 [backport-2.12]

CHANGELOG.md
=> chore: update changelog for version 2.13.1

ddtrace/bootstrap/preload.py, ddtrace/debugging/_debugger.py, ddtrace/debugging/_products/code_origin/span.py, ddtrace/debugging/_products/dynamic_instrumentation.py, ddtrace/debugging/_products/exception_replay.py, ddtrace/internal/symbol_db/__init__.py, ddtrace/internal/symbol_db/product.py, pyproject.toml, tests/debugging/exploration/debugger.py, tests/debugging/test_api.py
We migrate all the debugging products to the product plugin interface for automatic life-cycle management.
- …
=> refactor(di): migrate to the product interface

tests/appsec/contrib_appsec/utils.py
Add priority test in the threat tests to ensure we don't mark as manual keep all traces. …
=> test(asm): add priority test

ddtrace/_trace/utils_botocore/span_pointers/__init__.py, ddtrace/_trace/utils_botocore/span_pointers/dynamodb.py, ddtrace/_trace/utils_botocore/span_pointers/s3.py, tests/tracer/utils_botocore/test_span_pointers.py
as we add more code, it would be nice to have some not-too-large files …
=> chore: rearrange botocore span pointer code

ddtrace/_trace/utils_botocore/span_pointers/dynamodb.py, releasenotes/notes/span-pointers-aws-dynamodb-deleteitem-ad22b22efa1a7789.yaml, tests/tracer/utils_botocore/test_span_pointers.py
=> feat(tracer): [SVLS-5674] DynamoDB DeleteItem pointers

tests/appsec/iast/_ast/test_ast_patching.py
Code Security: Simplify regression test and explain it …
=> chore(iast): simplify test, add comment

ddtrace/internal/datadog/profiling/build_standalone.sh
Forgot to add in #10950 
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#inter …
=> chore(profiling): pass python3 root dir from standalone build script

mypy.ini
=> chore(profiling): mypy ignores python files in native build dir

ddtrace/_trace/utils_botocore/span_pointers/dynamodb.py, releasenotes/notes/span-pointers-aws-dynamodb-transactwriteitem-faf3ad03a100631d.yaml, tests/tracer/utils_botocore/test_span_pointers.py
This is similar but slightly different than BatchWriteItem. …
=> feat(tracer): [SVLS-5676] DynamoDB TransactWriteItems pointers

ddtrace/_trace/trace_handlers.py, ddtrace/contrib/botocore/__init__.py, ddtrace/contrib/internal/botocore/patch.py, releasenotes/notes/span-pointers-aws-opt-out-option-45f852835e642e98.yaml, tests/contrib/botocore/test.py
=> feat(tracer): [SVLS-5765] option to control botocore span pointers

setup.py
=> chore(iast): propagate python executable

ddtrace/appsec/_iast/_iast_request_context.py
=> chore(iast): report iast enabled metric based on environment variable

tests/contrib/fastapi/test_fastapi_appsec_iast.py
=> test(ci): iast prechecks

ddtrace/appsec/_iast/_iast_request_context.py
Fix a recent mistake in a merge. …
=> chore(asm): add small fix for span in IASTEnvironment

ddtrace/appsec/_asm_request_context.py, ddtrace/appsec/_handlers.py, ddtrace/contrib/internal/asgi/middleware.py, pyproject.toml, tests/appsec/appsec/test_appsec_trace_utils.py, tests/appsec/appsec/test_processor.py, tests/appsec/utils.py
Following https://github.com/DataDog/dd-trace-py/pull/10899 and https://github.com/DataDog/dd-trace-py/pull/11012, this PR removes the last traces of the previous instrumentation for ASM.
APPSEC-55053
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#back …
=> chore(asm): finalize refactor

scripts/iast/leak_functions.py, tests/appsec/iast_aggregated_memcheck/test_aggregated_memleaks.py
reduce the number iterations in `test_aggregated_leaks` …
=> chore(ci): iast, reduce the number iterations in test_aggregated_leaks

tests/profiling_v2/test_gunicorn.py
Copied and edited from https://github.com/DataDog/dd-trace-py/blob/a04689875b71cb99acb38a2a4c07cbaeb3bc6270/tests/profiling/test_gunicorn.py …
=> chore(profiling): add gunicorn test for stack v2

.gitlab/tests/appsec.yml, hatch.toml
Remove python 3.9 from appsec_aggregated_leak_testing …
=> chore(ci): remove python 3.9 from appsec_aggregated_leak_testing

.gitignore, ddtrace/appsec/_iast/_taint_tracking/__init__.py, tests/appsec/iast/aspects/test_re_aspects.py, tests/appsec/iast_packages/test_packages.py, tests/utils.py
This fix is not enough we add extra validations
https://github.com/DataDog/dd-trace-py/pull/11107/files#diff-187a73402e1c19057794a003245a9ee6087a6ee4a62ca2739777529eda47c6d8R267
- Title is …
=> chore(iast): copy_ranges_to_string errors

tests/appsec/appsec_utils.py, tests/appsec/iast_packages/test_packages.py
IAST: Small quality of life changes for debugging propagation …
=> chore(iast): make debug propagation tool work in propagation on tests

CHANGELOG.md
=> chore: update changelog for version 2.15.0

releasenotes/notes/ci_visibility-fix_codeowners_including_comments-82d9cb733a2c7285.yaml
=> fix wrong release note format

CHANGELOG.md
=> chore: update changelog for version 2.16.2

CHANGELOG.md
=> chore: update changelog for version 2.16.4

scripts/iast/print_patched_code.py
IAST: debugging tool to understand how a module would be patched. …
=> chore(iast): add tool to debug iast patched code

tests/profiling/gunicorn-app.py
=> chore(profiling): make gunicorn app to run shorter

ddtrace/internal/ci_visibility/_api_client.py, ddtrace/internal/ci_visibility/telemetry/git.py
Follow-up to #11545 that was missed in the last PR. …
=> chore(ci_visibility): fix API telemetry and make ordering stable with better logging

benchmarks/appsec_iast_aspects/config.yaml, benchmarks/appsec_iast_aspects/functions.py
=> chore(iast): benchmarks for modulo bytes

ddtrace/internal/datadog/profiling/dd_wrapper/test/CMakeLists.txt, ddtrace/internal/datadog/profiling/stack_v2/test/CMakeLists.txt
=> chore(profiling): upgrade googletest

ddtrace/internal/datadog/profiling/dd_wrapper/test/test_api.cpp, ddtrace/internal/datadog/profiling/dd_wrapper/test/test_forking.cpp, ddtrace/internal/datadog/profiling/dd_wrapper/test/test_initialization.cpp, ddtrace/internal/datadog/profiling/dd_wrapper/test/test_threading.cpp
=> chore(profiling): update agent url and port for native tests

.circleci/config.templ.yml, .circleci/config.yml, .github/workflows/generate-package-versions.yml, .github/workflows/requirements-locks.yml, .gitlab-ci.yml, .gitlab/tests.yml, docs/contributing-testing.rst, hatch.toml, scripts/ddtest
=> chore: use latest patched riot version in CI

docs/configuration.rst
This was released in 2.18 , not 2.19.  …
=> chore(ci_visibility): update RUM flush env var release

ddtrace/internal/datadog/profiling/dd_wrapper/include/uploader.hpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp, tests/profiling_v2/collector/test_threading.py
=> chore(profiling): simplify usage of cancellation token

.github/workflows/system-tests.yml
Update debugger system tests scenarios.
Depends on https://github.com/DataDog/system-tests/pull/3616
- Avoids …
=> chore(debugger): - update debugger system tests scenarios

.gitlab-ci.yml, .gitlab/dramatiq.yml, tests/contrib/dramatiq/test_integration.py
=> chore(test): add a known new flaky test

.gitlab-ci.yml, .gitlab/quality-gates-tests.yml
=> chore: clean up base branch for R&D

releasenotes/notes/waf_1.22.0-05b1dfbaa0d47059.yaml, setup.py, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Upgrade libddwaf to 1.22.0
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#int …
=> chore(asm): libddwaf 1.22.0

ddtrace/internal/packages.py, ddtrace/internal/telemetry/data.py, ddtrace/internal/telemetry/modules.py, ddtrace/internal/telemetry/writer.py
- package resolution was not working optimally if only a sub module of a package was loaded. This PR improves that by trying to explore the parent module if the package is not found.
- remove dead code using import hook as it was never loaded. Simplify code base.
APPSEC-56104 …
=> refactor(asm): update package resolution

ddtrace/internal/datadog/profiling/dd_wrapper/test/CMakeLists.txt
=> chore: fix cmake format

.github/workflows/system-tests.yml
=> ci: store fake DD_API_KEY as a secret

docs/integrations.rst, docs/spelling_wordlist.txt
=> chore(docs): add vertexai docs

ddtrace/internal/datadog/profiling/dd_wrapper/include/sample_manager.hpp
=> chore(profiling): remove unused mutex

releasenotes/notes/threethirteen-d40d659d8939fe5e.yaml
This change lists everything that is currently known not to work with Python 3.13 …
=> docs: add details to the release note about 3.13

ddtrace/internal/datadog/profiling/dd_wrapper/test/CMakeLists.txt, ddtrace/internal/datadog/profiling/stack_v2/test/CMakeLists.txt, scripts/gen_circleci_config.py
=> ci: cmake format fix

hatch.toml
Update the python version for threats tests, to include python 3.13 when available. …
=> chore(asm): update python version for threats tests

tests/profiling/test_accuracy.py, tests/profiling_v2/test_accuracy.py
=> chore(profiling): increase error margin for flaky tests

tests/appsec/iast_packages/test_packages.py, tests/appsec/suitespec.yml
=> chore: enable iast packages

.gitlab-ci.yml, .gitlab/testrunner.yml, .gitlab/tests.yml
=> chore(ci): new testrunner for check_new_flaky_tests [2.18] 

tests/profiling_v2/gunicorn.conf.py, tests/profiling_v2/test_gunicorn.py
=> chore(profiling): print gunicorn worker startup times in test

.github/workflows/pypa_musllinux_1_2_i686.yml
=> ci: add missing permissions to publish musl i686 image

ddtrace/appsec/_iast/_handlers.py, tests/contrib/fastapi/test_fastapi_appsec_iast.py
=> chore(iast): taint parameter name and header name in fastapi

ddtrace/appsec/_iast/_handlers.py, tests/appsec/integrations/django_tests/test_django_appsec_iast.py, tests/appsec/integrations/flask_tests/test_iast_flask_telemetry.py
=> chore(iast): refactor django handlers and tests

ddtrace/appsec/_constants.py, ddtrace/settings/asm.py, releasenotes/notes/removal_of_DD_APPSEC_AUTOMATED_USER_EVENTS_TRACKING-c1b4d2141ee92add.yaml, tests/telemetry/test_writer.py
remove deprecated env var DD_APPSEC_AUTOMATED_USER_EVENTS_TRACKING for 3.0 release. …
=> chore(asm): remove deprecated env var

CHANGELOG.md
Forwardporting https://github.com/DataDog/dd-trace-py/pull/12088 …
=> chore: update changelog for version 2.19.2 [forwardport 3.x]

releasenotes/notes/iast-feat-xss-django-6781a8b9a4092832.yaml
An update in the XSS release note …
=> chore(iast): update xss release note

ddtrace/__init__.py, ddtrace/trace/__init__.py
Cleans up code introduced in v3.0 …
=> chore(tracing): remove unused imports

ddtrace/profiling/collector/_lock.py, releasenotes/notes/lock-log-df92d0fddb165ebe.yaml
=> fix(profiling): reduce log spam from lock collector

tests/internal/test_auto.py
=> ci(flaky): mark `tests/internal/test_auto.py` with flaky for 30 days

releasenotes/notes/fix-iast-avoid-native-import-6cef954e3c98c9e8.yaml
Release note of the PR https://github.com/DataDog/dd-trace-py/pull/12298 …
=> chore(iast): relase note of #12298 [backport 2.20]

tests/appsec/suitespec.yml
The goal is to decrease the time required to pass those tests as well as decrease the potential timeout flaky failures. …
=> chore(ci): increase parallelism for integrations tests

hatch.toml, tests/appsec/integrations/fastapi_tests/test_fastapi_appsec.py, tests/appsec/suitespec.yml
=> ci(iast): enable fastapi integrations tests

ddtrace/appsec/_iast/taint_sinks/weak_cipher.py
=> chore(iast): remove print

CHANGELOG.md
=> chore: update changelog for version 2.20.2

ddtrace/internal/products.py
We normalise the name of products reported by telemetry when they are enabled/disabled. …
=> chore(internal): normalise product telemetry names

ddtrace/llmobs/_constants.py
It wasn't clear what action to take and I found myself confused why LLMObs was not working when setting `DD_LLMOBS_ENABLED=1` but not using `ddtrace-run`.
- All changes …
=> chore(llmobs): improve disabled log message

tests/suitespec.yml
We include the products.py source in the core component to ensure that changes to the product plugin machinery trigger any suites that depend on core. …
=> test: include products.py in core component

ddtrace/profiling/collector/_memalloc_heap.c
The heap profiler does statistical sampling of allocations. There is no
explanation in the code (or elsewhere) how the sampling in the profiler
works or why the chosen method is justified. We want to know whether
it's fair and whether our reported numbers accurately represent the real
heap size and the relative portion of the heap taken by different
objects of varying sizes.
Prior to working on this code, I was particularly concerned about the
weighting of sampled values. The method this profiler uses is different
than the methods used by either the Go profiler or tcmalloc, which seem
to generally do a good job. I've done some testing which seems to
indicate that the weighting we do is actually pretty good. So this
commit documents _why_ it's okay. My model of sampling borrows pretty …
=> refactor(profiling): document heap profile sampling

.gitlab/testrunner.yml
=> ci: store junit xml results to GitLab job

ddtrace/_trace/tracer.py
Wrap executor is now private
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#i …
=> chore(docs): update docs to reflect changes in tracer.configure()

CHANGELOG.md
=> chore: update changelog for version 2.21.3

ddtrace/settings/_config.py
=> chore(config): remove unused configurations

ddtrace/appsec/_asm_request_context.py, ddtrace/appsec/_constants.py, ddtrace/appsec/_trace_utils.py, ddtrace/appsec/_utils.py, ddtrace/contrib/internal/django/patch.py, ddtrace/settings/_config.py, releasenotes/notes/django_signup_instrumentation-c7f7db227105c851.yaml, tests/appsec/integrations/django_tests/django_app/urls.py, tests/appsec/integrations/django_tests/django_app/views.py, tests/appsec/integrations/django_tests/test_django_appsec.py
Add support for signup events on Django
- add unit test for standard user class
- will be tested on system tests with a custom user class https://github.com/DataDog/system-tests/pull/4222
- tiny improvements
APPSEC-56662 …
=> feat(asm): add signup event auto instrumentation for Django

.gitlab-ci.yml
=> ci: remove extra conditionals besides stage override for non-prod OCI jobs

tests/profiling/test_accuracy.py
=> ci(flaky): mark `test_accuracy` as flaky for 30 days

tests/contrib/flask/test_flask_snapshot.py
=> chore(ci): remove flask flaky decorator

tests/contrib/fastapi/test_fastapi.py, tests/profiling/test_accuracy.py
Remove flaky decorator from `test_background_task` …
=> chore(ci): remove flaky decorator from fastapi

.gitlab/package.yml
=> ci: prevent git fatal warning in download artifacts job

tests/contrib/botocore/test_bedrock.py
Remove flaky from botocore.
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#in …
=> chore(botocore): remove flaky from botocore

docs/build_system.rst, docs/configuration.rst, docs/index.rst
=> chore: add build system docs

ddtrace/internal/module.py
We prevent the unnecessary import of importlib.abc in module.py since it is just used for type checking.
- …
=> chore(internal): prevent import of importlib.abc

releasenotes/notes/fix-missing-injection-images-8879c5f2c3fce6e0.yaml
=> fix(lib-injection): add release note for missing OCI image fix

ddtrace/ext/ci.py, ddtrace/internal/ci_visibility/api/_base.py, ddtrace/internal/ci_visibility/api/_test.py, ddtrace/internal/ci_visibility/constants.py, ddtrace/internal/ci_visibility/recorder.py, ddtrace/internal/ci_visibility/telemetry/events.py
Test Optimization: Adds provider name and is auto injected tags to telemetry event …
=> chore(testopt): add provider name and auto_injected to telemetry

ddtrace/contrib/internal/rq/patch.py
=> chore: replaced os.env with _get_config in rq integration

.circleci/config.templ.yml, .gitlab/services.yml, docker-compose.yml, lib-injection/docker-compose.yml
Update test agent version to `1.21.0` …
=> chore(ci): update test agent versions

ddtrace/appsec/_asm_request_context.py
remove useless old code.
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#inter …
=> chore(asm): remove asm_request_context initialisation for iast

.github/dependabot.yml, .github/workflows/backport.yml, .github/workflows/build-and-publish-image.yml, .github/workflows/build_deploy.yml, .github/workflows/build_python_3.yml, .github/workflows/changelog.yml, .github/workflows/check_old_target_branch.yml, .github/workflows/codeowners.yml, .github/workflows/codeql-analysis.yml, .github/workflows/django-overhead-profile.yml, .github/workflows/encoders-profile.yml, .github/workflows/flask-overhead-profile.yml, .github/workflows/generate-package-versions.yml, .github/workflows/generate-supported-versions.yml, .github/workflows/pr-name.yml, .github/workflows/profiling-native.yml, .github/workflows/prune_workflow.yml, .github/workflows/pytorch_gpu_tests.yml, .github/workflows/require-checklist.yaml, .github/workflows/requirements-locks.yml, .github/workflows/rust-ci.yml, .github/workflows/set-target-milestone.yml, .github/workflows/stale.yml, .github/workflows/system-tests.yml, .github/workflows/test_frameworks.yml, .github/workflows/test_lib_injection.yml, .github/workflows/unit_tests.yml, .github/workflows/upstream-issues.yml
backport of #12189 to `2.21`
Changes with this PR are:
- **Add dependabot for github actions**
- **Pin all actions by hash**
Pinning 3rd-party GitHub Actions by commit SHA makes them less vulnerable to compromise of the 3rd party. To avoid outdating and non-verbosity, versions are commented after the SHA and updating via dependabot is introduced that will automatically update the commented version tag as well.
In case of a false commit SHA, this change could break the corresponding workflow. Typically, this does not cause major interruptions, but it can for example affect a release pipeline and require restart causing delays.
- The change includes tests OR the PR …
=> ci: pin all GitHub Actions by SHA and update via dependabot (#12189) [backport 2.21]

ddtrace/_trace/utils_botocore/span_pointers/dynamodb.py, tests/tracer/utils_botocore/test_span_pointers.py
=> chore: switch warning to debug for dynamo span pointers

tests/internal/test_auto.py
Bumping this timestamp to give more time to investigate. …
=> ci(flaky): bump flaky timestamp for test_auto

ddtrace/internal/ci_visibility/recorder.py, ddtrace/internal/ci_visibility/writer.py
Add type hints and other small improvements to CI visibility recorder …
=> chore(ci_visibility): type hinting

ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp
=> chore(profiling): compress code-provenance file when exporting

ddtrace/appsec/_iast/_taint_tracking/tests/CMakeLists.txt
=> ci(iast): update google tests

ddtrace/_logger.py, ddtrace/bootstrap/sitecustomize.py
We refactor the logic for the enablement of log injection to avoid some potential circular imports.
- Avoids …
=> refactor: logs injection configuration

.gitlab/benchmarks/macrobenchmarks.yml
=> chore(runtime_metrics): add a new nightly macrobenchmark run: tracing-runtime-metrics-enabled

CHANGELOG.md
=> chore: update changelog for version 3.3.0

.github/workflows/build-and-publish-image.yml, .github/workflows/build_deploy.yml, .github/workflows/build_python_3.yml, .github/workflows/check_old_target_branch.yml, .github/workflows/codeowners.yml, .github/workflows/codeql-analysis.yml, .github/workflows/generate-package-versions.yml, .github/workflows/generate-supported-versions.yml, .github/workflows/lib-inject-prune.yml, .github/workflows/pr-name.yml, .github/workflows/pytorch_gpu_tests.yml, .github/workflows/set-target-milestone.yml, .github/workflows/stale.yml, .github/workflows/system-tests.yml, .github/workflows/test_frameworks.yml, .github/workflows/unit_tests.yml
Reverts DataDog/dd-trace-py#12583
=> Revert "chore(deps): bump the gh-actions-packages group across 1 directory with 13 updates"

ddtrace/__init__.py, ddtrace/_monkey.py, ddtrace/_trace/processor/__init__.py, ddtrace/_trace/provider.py, ddtrace/_trace/sampler.py, ddtrace/_trace/span.py, ddtrace/_trace/tracer.py, ddtrace/contrib/internal/subprocess/patch.py, ddtrace/contrib/internal/trace_utils.py, ddtrace/internal/core/event_hub.py, ddtrace/internal/datastreams/processor.py, ddtrace/internal/processor/stats.py, ddtrace/internal/sampling.py, ddtrace/internal/schema/processor.py, ddtrace/propagation/http.py, ddtrace/settings/_config.py, ddtrace/settings/asm.py, tests/datastreams/test_public_api.py
Reverts DataDog/dd-trace-py#12970
=> Revert "refactor: configuration instance"

tests/opentelemetry/test_context.py, tests/opentelemetry/test_span.py, tests/opentelemetry/test_trace.py
=> chore(otel): make snapshots less flaky

docs/build_system.rst
=> chore(docs): update docs on gcc version

ddtrace/appsec/_iast/_ast/visitor.py, ddtrace/appsec/_iast/_handlers.py, ddtrace/appsec/_iast/_patches/json_tainting.py, ddtrace/appsec/_iast/_taint_tracking/aspects.py, ddtrace/appsec/_iast/_taint_utils.py, ddtrace/appsec/_iast/taint_sinks/_base.py, tests/appsec/iast/aspects/aspect_utils.py, tests/appsec/iast/aspects/test_add_aspect.py, tests/appsec/iast/aspects/test_common_aspects.py, tests/appsec/iast/iast_utils.py, tests/appsec/iast/taint_sinks/test_sql_injection.py, tests/appsec/integrations/django_tests/django_app/settings.py, tests/appsec/integrations/django_tests/django_app/urls.py, tests/appsec/integrations/django_tests/django_app/views.py, tests/appsec/integrations/django_tests/test_django_appsec_iast.py
=> chore(iast): add more iast tests types

ddtrace/appsec/_asm_request_context.py, ddtrace/appsec/_ddwaf/waf.py, ddtrace/appsec/_ddwaf/waf_mock.py, ddtrace/appsec/_ddwaf/waf_stubs.py, ddtrace/appsec/_processor.py, ddtrace/appsec/_utils.py, tests/appsec/appsec/api_security/test_schema_fuzz.py, tests/appsec/appsec/test_processor.py
remove cycles with
- _utils and _asm_request_context
- _ddwaf and _metrics
APPSEC-57233 …
=> chore(asm): remove static cycles

.gitignore
=> chore(iast): update gitignore

.gitlab/benchmarks/microbenchmarks.yml
=> ci: allow flaky benchmarks to fail

benchmarks/appsec_iast_aspects/scenario.py
=> perf(iast): make benchmarks more stable

ddtrace/appsec/_api_security/api_manager.py
- remove code supposed to set headers in api_manager: this code is outdated and not required anymore
- upgrade warning logs in apisec_manager to the improved interface with 1hour sampling.
- …
=> chore(asm): remove dead code for headers and improve warning logs

tests/appsec/integrations/pygoat_tests/test_pygoat.py
- Test vulnerability locations in pygoat tests.
- Make assertions more informative in case of failure.
- …
=> chore(iast): test vulnerability locations in pygoat

ddtrace/internal/datadog/profiling/cmake/AnalysisFunc.cmake
=> chore(build): fix windows build errors from ddup

tests/ci_visibility/suitespec.yml
CI Visibility: Update suitespec to add missing parts. …
=> ci: add missing parts to the ci_visibility suitespec

.gitlab-ci.yml
=> chore(build): disable VPA

ddtrace/appsec/_iast/_stacktrace.c, ddtrace/appsec/_iast/taint_sinks/_base.py, tests/appsec/iast/test_stacktrace.py
=> chore(iast): avoid exception when no relevant frame is found [2.21]

benchmarks/appsec_iast_django_startup/requirements.in, benchmarks/appsec_iast_django_startup/requirements_scenario.txt, benchmarks/django_simple/requirements_scenario.txt, benchmarks/errortracking_django_simple/requirements_scenario.txt
following https://github.com/DataDog/dd-trace-py/pull/13347 `Datadog Summary` reports an error in benchmark dependencies
57161 …
=> chore: fix benchmak dependencies

docs/conf.py, hatch.toml
=> ci(docs): clean up docs job and set static title

docs/conf.py, scripts/gen_gitlab_config.py
Artifacts uploaded must be contained in the CI_PROJECT_DIR …
=> ci: fix build_docs artifacts

.github/workflows/system-tests.yml
=> ci: pin system-tests version [3.7]

.github/workflows/all-green.yml
=> ci: ignore devflow/* jobs for all-green status

CHANGELOG.md
=> chore: update changelog for version 3.7.1

scripts/gen_gitlab_config.py
CI: all tests are run if anything changes in pytest integration.
Follow-up from: https://github.com/DataDog/dd-trace-py/pull/13463#issuecomment-2895012109
- All changes …
=> ci: all tests are run if anything changes in pytest integration

CHANGELOG.md
=> chore: update changelog for version 3.8.0

docs/shared.rst
updated development guide anchor link to appropriately point to the contribution guide …
=> chore: updated development guide anchor link

docs/configuration.rst
=> chore(docs): update baggage tags config

hatch.toml, releasenotes/notes/waf_trace_tagging-56448e2332bc0433.yaml, tests/appsec/appsec/rules-trace-tagging.json, tests/appsec/contrib_appsec/utils.py, tests/appsec/rules.py
following https://github.com/DataDog/dd-trace-py/pull/13587
- add tests for the new trace tagging feature with a new security rules
- add a release note
APPSEC-57563
- …
=> feat(asm): new trace tagging feature tests

.github/workflows/unit_tests.yml
=> ci: skip windows 3.13 multiple os unit tests

tests/appsec/iast/_ast/conftest.py, tests/appsec/iast/aspects/conftest.py, tests/appsec/iast/aspects/test_add_aspect.py, tests/appsec/iast/conftest.py, tests/appsec/iast/iast_utils.py, tests/appsec/iast/secure_marks/conftest.py, tests/appsec/iast/taint_sinks/test_command_injection.py, tests/appsec/iast/taint_sinks/test_insecure_cookie.py, tests/appsec/iast/taint_sinks/test_ssrf.py, tests/appsec/iast/taint_sinks/test_stacktrace_leak.py, tests/appsec/iast/taint_sinks/test_vulnerability_detection.py, tests/appsec/iast/taint_sinks/test_weak_cipher.py, tests/appsec/iast/taint_tracking/conftest.py, tests/appsec/integrations/django_tests/conftest.py, tests/appsec/integrations/django_tests/test_appsec_django.py, tests/appsec/integrations/django_tests/test_iast_django.py, tests/appsec/integrations/django_tests/utils.py, tests/appsec/integrations/packages_tests/conftest.py, tests/contrib/dbapi/test_dbapi_appsec.py
Cherry pick some refactor that I made in security controls: https://github.com/DataDog/dd-trace-py/pull/13655 …
=> chore(ci): remove duplicated functions

ddtrace/llmobs/experimentation/_config.py, tests/llmobs/test_experimentation_config.py
=> accept DD_APP_KEY and log warnings for DD_APPLICATION_KEY

.github/workflows/system-tests.yml
=> chore(ci): update st

docs/contributing-release.rst
=> docs: update release pandoc script

.gitlab-ci.yml
=> ci: fix macrobenchmark trigger to run on rc releases

tests/appsec/iast/taint_tracking/test_native_taint_range.py, tests/appsec/iast/test_env_var.py
Reduce execution time
tests/appsec/iast/taint_tracking/test_native_taint_range.py: 32s -> 9s
tests/appsec/iast/test_env_var.py -> 46s -> 7s …
=> ci(iast): fix flaky and slow tests

ddtrace/_trace/span.py, ddtrace/llmobs/_integrations/langchain.py, hatch.toml, releasenotes/notes/add-sqs-lambda-context-support-5062a60d81055ed7.yaml, releasenotes/notes/ci-vis-gzip-payload-a93c4b5d4687f1c4.yaml, releasenotes/notes/ci-vis-gzip-payload-evp-8269d43f2721afa1.yaml, tests/contrib/logging/test_logging.py, tests/lib_injection/conftest.py, tests/tracer/test_correlation_log_context.py, tests/tracer/test_settings.py, tests/tracer/test_span.py
=> chore: fix spelling mistakes in codebase

hatch.toml
=> chore(ci): remove errortracking from hatch since it's already on riot

tests/profiling/suitespec.yml
=> ci(profiling): split v1 and v2 profiling gitlab jobs

.gitlab/benchmarks/bp-runner.microbenchmarks.fail-on-breach.yml
=> ci(benchmarks): bump lower bounds for max_rss_usage SLOs

.gitlab/benchmarks/bp-runner.microbenchmarks.fail-on-breach.yml
Saw a run that just barely failed, lets bump up just a tad more. …
=> ci: bump otelspan start-finish rss slo

riotfile.py
CI: Disable ITR on sensitive jobs (where ITR can cause some trouble), so we can enable it for the rest.
- …
=> ci: disable itr on sensitive jobs

.github/workflows/system-tests.yml
set ST to workaround commit to unlock CI …
=> chore(ci): building base images

.github/workflows/system-tests.yml, pyproject.toml
unlock ci with system tests
- update st pinned version
- update setuptools version scheme …
=> chore(ci): unlock 3.11 ci

.github/workflows/system-tests.yml
=> chore(ci): do not use a API KEY in system-tests

ddtrace/_monkey.py
=> chore: add the traceback to the integration failed to enable errors

ddtrace/contrib/internal/pytest/_plugin_v2.py, tests/contrib/pytest/test_pytest.py
The solution in PR #14328 was incomplete. This PR ensures all exceptions are cleared up at the end of each test.
I'm not adding a release note because this is a continuation of #14328, which already has a release note. …
=> chore(ci_visibility): ensure exception dictionary is cleared after each test

.gitlab/benchmarks/macrobenchmarks.yml
Add macrobenchmarks scenario for native writer …
=> chore(benchmarks): add native writer macro benchmarks

ddtrace/contrib/internal/ray/tracer.py
The change allows to capture host name which in conjunction with process ID will provide GPU utilization information. …
=> Add hostname tag to enable GPU monitoring

.github/workflows/system-tests.yml, .gitlab-ci.yml
=> ci: update system-tests commit

ddtrace/appsec/_common_module_patches.py, ddtrace/contrib/internal/urllib3/patch.py, ddtrace/internal/_unpatched.py, ddtrace/internal/http.py
This reverts commit 392f6950f74d5192c5af7b041c65f49f91f5985e. …
=> Revert "chore(iast): experiment ci visibility"

tests/contrib/integration_registry/registry_update_helpers/integration_update_orchestrator.py
Ensures integration registry updater has a clean file system for each run. Fixes a problem where the venv of required packages was corrupted, and where the file holding all update data can't have a lock acquired on it. Now we just do a clean delete of all necessary files and start from scratch each time. …
=> chore(testing): fix update manager to delete necessary files / venvs each run

.github/workflows/profiling-native.yml
=> ci: fix valgrind profiling native test

.github/workflows/system-tests.yml, .gitlab-ci.yml
Backport e13717ff2bf9c6c2e41945f1e877ca8f6e888a78 from #14735 to 3.15.
=> chore: update system-tests (#14735)
