.circleci/config.yml
Dockerfile.buster

ci: add buster based Docker image
This adds a Buster based Docker image to upgrade the CI.
I'll add this to Docker Hub to be built and then we'll be able to upgrade
CircleCI without breaking everything.

ci: add buster based Docker image

---

.circleci/config.yml
riotfile.py
tox.ini

Integration testing for the pytest plugin was moved from tox to riot.

chore: move pytest tests from tox to riot

---

.circleci/config.yml
.circleci/scripts/test_build.sh

This just pulls Rust and Cargo to allow building Cryptography latest version
which embeds some Rust code.
Alpine does not have wheels so it needs to compile everything.

ci: allow to use latest cryptography on Alpine

---

scripts/run-tox-scenario

The current code does not fail and returns an empty list if no matching test
env is found.
tox -e '' actually runs the whole list of scenarios, which takes hours.
This makes sure the script exits with an error if no env matches.

ci: stop ci if no scenario is found

---

scripts/run-tox-scenario

There was a left over from debugging with an echo command that has been almost
missed in https://github.com/DataDog/dd-trace-py/pull/2480

ci: fix run-tox-scenario on CircleCI

---

ddtrace/contrib/tornado/constants.py
ddtrace/contrib/tornado/handlers.py

This reference isn't used anywhere.

tornado: remove unused context reference

---

ddtrace/bootstrap/sitecustomize.py
ddtrace/tracer.py
docs/configuration.rst
releasenotes/notes/add-dd_call_basic_config-env-15570281d176f438.yaml
tests/conftest.py
tests/integration/test_integration.py
tests/utils.py

Short term fix for #2482.
With the addition of `DD_CALL_BASIC_CONFIG` env variable, customers can control whether we call `logging.basicConfig()` or not.
- ~[ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).~

Add DD_CALL_BASIC_CONFIG={true,false} environment variable

---

tests/contrib/pymemcache/test_client_mixin.py

pymemcache changed to use set_many in HashClient in v3.4.4 so our tests
needed to be updated.
ref: https://github.com/pinterest/pymemcache/pull/320

Fix pymemcache tests

---

.circleci/config.yml

This will help ensure that provider specific environment variabls are available
to tests.
For example: CI=true, CIRCLE_JOB=xxx, etc

Add --pass-env to run_test riot call

---

.circleci/config.yml
.github/workflows/bottle.yml
.github/workflows/django.yml
.github/workflows/fastapi.yml
.github/workflows/flask.yml
.github/workflows/starlette.yml

This variable is meant to be used to control exceptional behaviour and whether to let the exception bubble up or handle it and turn it into a warning.

ci: introduce the internal DD_TESTING_RAISE variable

---

.circleci/config.yml
ddtrace/contrib/django/patch.py
docs/spelling_wordlist.txt
releasenotes/notes/fix-django-db-connections-b9b98a7b49f27c5f.yaml
riotfile.py
tests/contrib/django/django1_app/settings.py
tests/contrib/django/django_app/settings.py
tests/contrib/django/test_django.py

If multiple database backends are used, the Django db instrumentation fails to patch all of their cursor functions as expected. This problem was discovered in #2463.
While #2084 was intended as a performance change, there were no tests for the case of multiple db backends so a regression was missed. Previous to this, the `django.db.connections.all()` was wrapped. The reason that had worked was because this happened to be called during initialization time: https://github.com/django/django/blob/main/django/db/__init__.py#L27.
The solution here is preferable as it does not depend on a side effect of initialization in the supported library.
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/8703/workflows/d9ec6881-10f7-46c9-b8cb-d5d22c554cff/jobs/708236
```
assert …
```

fix(django): fix instrumentation for multiple db backends

---

setup.py

For a weird reason there is a `**dict()` indirection to `setup()` kwargs which
seems unnecessary.
I imagine this was a left-over from a previous hack we had around `setup`.

chore: remove setup() call dict indirection

---

.circleci/config.yml
docker-compose.yml

This is needed to deploy Python 3.10 which requires newer libssl version.

ci: use Debian Buster image to run tests

---

riotfile.py

mypy 0.900 was released today where they moved to a modular typeshed setup, this causes a bunch of errors missing library type hinting in CI.
locally when trying to do `mypy --install-types` as suggested I get segfaults/failures.
we can manually install the missing typing for each library individually, but until then we will just pin to `<0.900`.

Pin mypy to <0.900 until we can resolve new modular typeshed issues

---

.circleci/config.yml
docker-compose.yml

Updating the `datadog/dd-trace-py:latest` tag to point to the new `:buster` tag broke the CI on 0.49.
This PR uses the last known good image tag for 0.49 CI.

Fix circleci dd-trace-py image to pre-buster

---

.circleci/config.yml
riotfile.py
tox.ini

This change sets the `DD_TESTING_RAISE` variable via riot and tox to ensure consistent behaviour between CI and local test runs.

fix: enable `DD_TESTING_RAISE` via riot and tox

---

ddtrace/internal/agent.py
ddtrace/internal/writer.py
docs/configuration.rst
releasenotes/notes/add-dd-trace-agent-timeout-seconds-env-844b53ff0ccc7c9f.yaml

For sending apm metrics to localhost, the defaults of `2.0` is enough. However, for setup where datadog agents are exposed over `https`, the timeout of 2.0 is not sufficient. Such kind of setup is used for non-prod environment for devs to test their apm/stats configuration without having to install ddagent on every non-prod machines or generate multiple ddagent key for each dev to test themselves.

Adds DD_TRACE_AGENT_TIMEOUT_SECONDS

---

hooks/scripts/run-black.sh
hooks/scripts/run-flake8.sh
hooks/scripts/run-mypy.sh
riotfile.py

Our current pre-commit hooks `run-black.sh`, `run-mypy.sh`, and `run-flake8.sh` use riot commands respectively to check black, mypy, and flake8. However, our current configuration for calling those commands implicitly calls every file in the tracer library (`ddtrace/` and `tests/`) to be checked, which considerably slows down the pre-commit checks (approximately 1 minute for the checks to succeed at the moment).
To fix this issue, this PR updates the pre-commit hooks to only read files in staging to be committed, including added, copied, modified, and renamed `.py` files. This results in our pre-commit hooks taking approximately less than 10 seconds to succeed.
Note: `riotfile.py` has been marked with `# type: ignore` temporarily, will be addressed in a future PR.

Update pre-commit hooks to only read files in staging

---

ddtrace/span.py
releasenotes/notes/fix-span-finish-signature-b0c1073b56c3b559.yaml

The argument to `Span.finish` should accept a `float` rather than an `int`. Also removed a redundant branching.

fix(span): correct `Span.finish` signature

---

ddtrace/internal/processor/trace.py

The trace can be walked once to separate finished/unfinished spans in one pass. This also halves the number of calls to the `finished` property.

perf(trace): loop over trace once when aggregating

---

ddtrace/profiling/collector/memalloc.py
ddtrace/profiling/collector/stack.pyx
docs/configuration.rst
releasenotes/notes/profiling-ignore-profiler-daa056f8384008dc.yaml
tests/profiling/collector/test_stack.py

In order to gather more (internal) stats about the profiler resource usage, we
shouldn't try to remove the profiler from the profiles.
This deprecates the option in case anyone wanted to use it and until we remove
the code completely.
The changelog keeps things simple as it's supposedly not a user-controlled
change, but it could still be visible.

chore(profiling): do not ignore the profiler by default

---

hooks/scripts/run-mypy.sh

The mypy pre-commit hook was updated to check all files in `ddtrace/` and `test/`, not just files in staging. This was done because a change to one API can potentially lead to mypy errors (including typing and function signatures) in other parts of the library.

Mypy commit hook to read all files, not just staging

---

tests/tracer/test_ext.py

#2458 added a test git repository fixture for testing git metadata extraction for CI. For testing in local development however, gpg commit signing will be prompted every time the test git repository is set up (as it makes a test commit). This requirement for gpg commit signing was removed for this temporary git repository fixture.

Removed gpg commit signing for test git repo fixture

---

ddtrace/internal/processor/trace.py

Updating the log level for the TraceSamplingProcessor from info to debug. Since we call `logging.basicConfig()` logging even as `info` can prove noisy, especially when the log messages are not directly actionable by the users of this library.

Update TraceSamplingProcessor log level to be debug

---

ddtrace/internal/forksafe.py
tests/tracer/runtime/test_runtime_id.py
tests/tracer/test_forksafe.py

There weren't any before. Also documents the existing behaviour of `forksafe.register`.

Add double fork test cases

---

tests/tracer/test_compat.py

This test hangs occasionally on Python 2, making the tracer test flaky.

test(compat): skip maybe_stringify test on PY2

---

ddtrace/internal/_rand.pyx
tests/tracer/test_rand.py

Registered forksafe hooks are not discarded once executed so the current implementation of _rand would cause over-registration of hooks.

fix(rand): do not over-register forksafe hooks

---

README.md

This documentation had fallen out of date. Contributors should use the ddtest script rather than start the testrunner themselves as the script handles installing dependencies. Also, no instructions had been included about running tests managed by riot.

fix(docs): update testing with ddtest and riot

---

tests/runtime/test_runtime_metrics_api.py

Add a test case to ensure that ddtrace-run behaves as expected based on the value of the `DD_RUNTIME_METRICS_ENABLED` environment variable.

test(runtime-metrics): test env variable

---

ddtrace/contrib/celery/signals.py
ddtrace/contrib/celery/utils.py
releasenotes/notes/perf-celery-reduced-overheads-6afe03acf1af703f.yaml
tests/contrib/celery/test_utils.py

This change tries to reduce the overheads introduced by the Celery instrumentation. Tags are set straight from the context extraction rather than via an intermediate dictionary. Tag names are pre-computed to avoid the cost of string concats at runtime.

perf(celery): reduce tracing overheads

---

ddtrace/internal/agent.py
ddtrace/internal/writer.py
docs/configuration.rst
releasenotes/notes/add-writer-env-config-7c0916dff4f7f80c.yaml
tests/integration/test_integration.py

DD_TRACE_WRITER_BUFFER_SIZE_BYTES - How many bytes of traces to buffer between flushes to the agent
DD_TRACE_WRITER_MAX_PAYLOAD_SIZE_BYTES - Max size of any payload to write to the trace agent
DD_TRACE_WRITER_INTERVAL_SECONDS - How many seconds between flushes to the agent
- ~[ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).~

Add env variables to configure Writer behavior

---

riotfile.py

Latest celery appears to be broken until
https://github.com/celery/celery/issues/6829 is resolved.

fix(ci): pin celery

---

ddtrace/contrib/falcon/middleware.py
ddtrace/ext/http.py

This updates two files. This first file /dd-trace-py/ddtrace/ext/http.py is to remove the function [normalize_status_code]. The second is to update where the function was used, ddtrace/contrib/falcon/middleware.py.

removing ddtrace.ext.http.normalize_status_code

---

ddtrace/context.py
ddtrace/span.py
ddtrace/tracer.py

Each span needs its own context copy as the `span.context` property
returns the trace context specialized with the span's id.
The lock is removed from `context._with_span` as the copied references
are not volatile.

Context copy improvements

---

tests/utils.py

This allows the token to be overridden manually if need-be.

Add token override to snapshot decorator

---

ddtrace/contrib/rediscluster/__init__.py
ddtrace/contrib/rediscluster/patch.py
pyproject.toml
tests/contrib/rediscluster/test.py

The `ddtrace.contrib.rediscluster` and `tests.contrib.rediscluster` directories were formatted with black and subsequently removed from the black excludes configuration.

chore(rediscluster): format with black

---

ddtrace/contrib/pytest/plugin.py
ddtrace/ext/ci.py
ddtrace/ext/git.py
tests/tracer/test_ext.py

We currently read `ci.WORKSPACE_PATH` from CI Env vars for the CIApp, but we can also extract this information from the local git executable on top of the git author/committer/repository_url/commit_message as a fallback in case this information is not provided via the CI env vars.

Added `ci.workspace_path` from git executable, not just CI env vars

---

tests/tracer/test_ext.py
tests/tracer/test_sampler.py

The PR fixes some silent errors from the tests.
The first patch fixes the default git branch and silents this message:
```
tests/tracer/test_ext.py::test_git_extract_user_info hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint:   git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint:   git branch -m <name>
```
The second patch fixes a silent exceptions on the `DummyWriter`:
```
tests/tracer/test_sampler.py::RateSamplerTest::test_deterministic_b …
```

chore(tests): fix silent errors

---

docs/advanced_usage.rst

In gunicorn, the `post_fork` hook is called before the worker's `init_process`. The gevent worker calls gevent's `patch_all` during the worker's `init_process`. This means that the current documentation would result in ddtrace's patching occurring before gevent's. Instead gunicorn users should use the `post_worker_init` hook which is called after the gevent patching has been applied and the gevent hub has been reinitialized following the fork.
https://github.com/benoitc/gunicorn/blob/1299ea9e967a61ae2edebe191082fd169b864c64/gunicorn/arbiter.py#L588-L589
https://github.com/benoitc/gunicorn/blob/1299ea9e967a61ae2edebe191082fd169b864c64/gunicorn/workers/ggevent.py#L143-L146
https://github.com/benoitc/gunicorn/blob/1299ea9e967a61ae2edebe191082fd169b864c64/gunicorn/workers/base.py#L138

fix(docs): use gunicorn post_worker_init hook

---

ddtrace/contrib/pylibmc/__init__.py
ddtrace/contrib/pylibmc/client.py
ddtrace/contrib/pylibmc/patch.py
pyproject.toml
tests/contrib/pylibmc/test.py

The `ddtrace.contrib.pylibmc` and `tests.contrib.pylibmc` directories were formatted with black and subsequently removed from the black excludes configuration.

chore(pylibmc): format with black

---

ddtrace/contrib/aiopg/__init__.py
ddtrace/contrib/aiopg/connection.py
ddtrace/contrib/aiopg/patch.py
pyproject.toml
tests/contrib/aiopg/py35/test.py
tests/contrib/aiopg/py37/test.py
tests/contrib/aiopg/test.py

The `ddtrace.contrib.aiopg` and `tests.contrib.aiopg` directories were formatted with black and subsequently removed from the black exclude configuration.

Chore(aiopg): format with black

---

ddtrace/contrib/gevent/__init__.py
docs/installation_quickstart.rst

Make it clear in our docs for gevent users that they must perform
gevent's monkeypatching before ddtrace's.

Add notice for gevent in docs

---

.github/workflows/django.yml

This PR fixes failing tests on Django 3.1.7 due to the Python 3.8.11 release.

Use stable branch for Django tests

---

ddtrace/contrib/pytest/plugin.py
ddtrace/ext/__init__.py
ddtrace/profiling/exporter/pprof.pyx
ddtrace/span.py
releasenotes/notes/span-types-enum-5ca7cb35031a199e.yaml
tests/contrib/pymongo/test.py
tests/profiling/exporter/test_pprof.py
tests/tracer/test_encoders.py

The getter and setter for `Span.span_type` had unrelated types (`str` and subclass of `Enum` respectively), which is a sign that something is not quite right. By making `ddtrace.ext.SpanTypes` a "namespace" object one can avoid making `span_type` a property, thus benefitting from the `__slots__` optimisation.

perf(span): make `span_type` a slot attribute

---

ddtrace/contrib/wsgi/wsgi.py
releasenotes/notes/wsgi-73cf1d35043e7fef.yaml

It is possible for `tracer.current_root_span()` to return None which was
not handled here.
Handle the possiblity that the current root span is None.

fix(wsgi): handle no root span

---

.github/workflows/flask.yml
.github/workflows/mako.yml

Mako and flask run their tests with tox, but tox clears out the environment
before running the test command. This means DD_TESTING_RAISE is not passed by
default.
This leverages TOX_TESTENV_PASSENV to inform tox we want to pass this down to
the test suite, making sure the tracer raises on important errors.

ci: pass DD_TESTING_RAISE correctly for tox-based tests

---

ddtrace/contrib/pytest/plugin.py
docs/spelling_wordlist.txt
releasenotes/notes/fix-pytest-parameterized-606fbc3a574c67c6.yaml
tests/contrib/pytest/test_pytest.py

In cases of parameterized pytest cases, the current pytest plugin attempts to JSON-encode non-serializable Python objects to include their attributes via the `__dict__` attribute, and defaulting to `__repr__` if the `__dict__` is empty or non-existent. However, complex Python objects like the `MagicMock()` class can sometimes contain circular references to itself (for example, including a reference to its child, itself which also includes a reference to its parent) and cause the following error:
```ValueError: Circular reference detected```
To fix this and the likely similar issues in the future, the pytest plugin now defaults straight to the string representation `__repr__` of a non-serializable Python object when attempting to JSON-encode pytest test parameters.

fix[pytest]: Default JSON encoding for non-serializable types to __repr__

---

riotfile.py

With the new riot release packages are not propagated down the venv instance parenting relation and therefore no longer provide overrides nor pins for packages at the previous level.

Use explicit dependency in riotfile

---

benchmarks/django_simple.Dockerfile
ddtrace/ext/sql.py
ddtrace/internal/compat.py
ddtrace/internal/nogevent.py
ddtrace/internal/uwsgi.py
ddtrace/profiling/collector/threading.py
ddtrace/utils/config.py
mypy.ini
setup.cfg

There are several third party library imports in the ddtrace library that result in `Cannot find implementation or library stub for module named ...`, which have up until now been suppressed with individual `# type: ignore[import]` ignores. These individual warnings have been replaced with a global configuration setting `ignore_missing_imports = true`.
Secondly, the codespell configuration has been changed to exclude the `ddtrace/vendor` and `.git/` directories, which were being unintentionally checked during pre-commit hooks if no python files were present in a commit (as the riot codespell command defaults to checking all files in the library).

Update mypy, codespell configurations

---

.circleci/config.yml
scripts/ddtest

We broke some things in 0.7 so lets pin until we can get them fixed up.

ci: pin riot to 0.6

---

riotfile.py

Should fix the following CI error: https://github.com/DataDog/dd-trace-py/pull/2667/files#diff-c2bbf2d05171ce6e867e127133d651ae7217320d295ab9ead7f28b04930f1a3fR41-R49

mysql-connector-python 8.0.24 requires Python 3.6

---

ddtrace/internal/writer.py
tests/tracer/test_writer.py

For testing it's desirable to be able to pass additional headers with
the trace requests made to the agent. With this ability we can propagate
tokens which can be used to associate traces with test cases when
running snapshot tests in subprocesses (like in https://github.com/DataDog/dd-trace-py/pull/2640).
I debated having the flag be read at run-time instead of
initialization-time but opted against it as reading from the env is not
cheap (on the order of 1µs):
>>> %timeit os.environ.get("")
1.23 µs ± 49.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

Add internal setting for additional writer headers

---

ddtrace/internal/writer.py
tests/conftest.py
tests/utils.py

The snapshot decorator worked ok for basic integration tests but isn't
compatible for more advanced pytest usage like parametrization.
By creating a fixture we can `pytest.mark.snapshot` test cases which
will make use of a `snapshot` pytest fixture which supports more
advanced pytest usage.
~(Draft until #2689 is decided upon)~

Add pytest snapshot fixture

---

ddtrace/contrib/sanic/patch.py
releasenotes/notes/fix-sanic-non-str-args-4d1b0f506bee3436.yaml
tests/contrib/sanic/test_sanic.py

This change fixes the handling of endpoint paths that take non-string arguments.
Fixes #2678.

fix(sanic): fix handling of non-string arguments

---

ddtrace/ext/ci.py
tests/tracer/fixtures/ci/bitrise.json

Updating ci extraction and the bitrise ci spec test fixture file after `datadog-ci-spec` changed Bitrise's environment variable for `ci.pipeline.name` from `BITRISE_APP_TITLE` to `BITRISE_TRIGGERED_WORKFLOW_ID`.

Updated bitrise CI environment var for ci.pipeline.name

---

ddtrace/contrib/flask/patch.py
releasenotes/notes/fix-flask-werkzeug-ignore-server-error-5131cbe28afca03a.yaml
tests/contrib/flask/test_errorhandler.py
tests/contrib/flask/test_request.py

It was found through #2347 that `werkzeug.exceptions.NotFound` 404 errors are currently raised and logged as server errors in `flask.dispatch_request` spans. This 404 error is no longer raised and logged as such.
Resolves #2347.

fix[flask]: ignore werkzeug.NotFound errors as server errors

---

ddtrace/contrib/django/utils.py
tests/contrib/django/test_django.py

This line was duplicated when factoring out the request/response tagging
done in 84a48a6.
Surprisingly this wasn't caught by the test suite so a regression test
is added as well. It should have resulted in a failure at some point
as reactivating the headers after a span is created should change the
parenting.

django: remove duplicate tracing header extraction

---

tests/profiling/collector/test_memalloc.py

This rewrite slightly the test so it uses an extra "profiler-like" thread
rather than trying to use the MemoryCollector thread itself.
While that works in most cases, in certain cases the few allocations done by
MemoryCollector are missed and the test fails.

test(profiling): rewrite test_memory_collector_ignore_profile to be more robust

---

ddtrace/contrib/trace_utils.py
tests/tracer/test_trace_utils.py

Pull out how we check if distributed tracing is enabled for an integration config into a helper that can be used by integrations and will match the logic we have in `activate_distributed_headers`

Add additional tests for distributed tracing enabled

---

docs/configuration.rst

Add `id` to table rows that can be used to refer to environment variables in the configuration.
E.g., https://788960-61572326-gh.circle-artifacts.com/0/tmp/docs/configuration.html#dd-profiling-capture-pct

chore(docs): add anchors to environment variables

---

ddtrace/opentracer/tracer.py
releasenotes/notes/opentracer-config-4b0422f49f325584.yaml
tests/opentracer/core/test_tracer.py

fix(opentracer): don't override default ddtrace settings
As outlined in #2267, some of the ddtrace default settings were being
overridden as the default opentracer config specified its own overrides.
This patch makes it so that the opentracer doesn't override the ddtrace
defaults.
Fixes #2267

fix(opentracer): don't override default ddtrace settings

---

ddtrace/contrib/asgi/middleware.py
releasenotes/notes/asgi-bc983a8dfffe823e.yaml
tests/contrib/asgi/test_asgi.py

Reported in #2103.
The ASGI specification on headers:
> headers: These are byte strings of the exact byte sequences sent by the client/to be sent by the server. While modern HTTP standards say that headers should be ASCII, older ones did not and allowed a wider range of characters. Frameworks/applications should decode headers as they deem appropriate.
This patch adds error handling for when headers cannot be decoded.
Fixes #2103

fix(asgi): handle invalid headers

---

tests/conftest.py

Adding in a new pytest fixture to provide a `snapshot_context` context manager with a preconfigured token based on the `pytest` `request` data.
We are using this in #2420 to test both sync and async clients in the same test case and the same snapshot files.
```python
async def test(snapshot_context):
with snapshot_context():
httpx.get(url)
with snapshot_context():
async with httpx.AsyncClient() as client:
await client.get(url)
```

Add pytest fixture for snapshot_context with preconfigured test token

---

riotfile.py

Version 7.14 of the Python client introduced a breaking change which causes the
library to raise an exception when an "unsupported" version of elasticsearch is
detected.
Unfortunately our CI isn't flexible enough to support matching server versions with
client versions... until we have bandwidth to make this adjustment we have to pin
elasticsearch.

Pin elasticsearch version

---

ddtrace/monkey.py
releasenotes/notes/fix-monkey-patch-typing-ab13fc458c90a260.yaml

Fixes #2743
As pointed out in #2743 when typing `*args` or `**kwargs` you do not need to type as a `Tuple`/`Dict`, that is implied.
```python
def func(*args, **kwargs):
def func(*args, **kwargs):
```

Fix type hint for patch/patch_all **patch_modules

---

ddtrace/contrib/flask/patch.py
releasenotes/notes/fix-flask-non-string-view-args-ed0283ddb1541e27.yaml
tests/contrib/flask/test_request.py

Fix issue with tagging non-string Flask view args

---

.github/workflows/build_deploy.yml

The filter used with the `workflow_dispatch` was using the incorrect attribute on the `github` context.
https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context

fix(ci): fix manual trigger of build job

---

benchmarks/base/Dockerfile

When trying to run benchmarks with a `DDTRACE_INSTALL_V#=git+https://github.com/datadog/dd-trace-py@master` would result in an error because no root certificates were available in the app image.

Ensure ca-certificates is installed for benchmark

---

ddtrace/bootstrap/sitecustomize.py
ddtrace/utils/formats.py
mypy.ini

The `ddtrace.bootstrap` module was removed from the mypy ignores configuration, and type hinting was added.

chore[mypy]: removed bootstrap from mypy ignores

---

.circleci/config.yml

Build the base venvs at the same time as the pre checks to save 1m30 in the CircleCI whole duration (and get results faster).

Faster CircleCI

---

tests/tracer/test_ci.py

Adds a test assertion to #2768 to ensure that a git commit hash is extracted even without user-provided git metadata.

Ensure git commit hash is extracted in CI

---

scripts/perf-run-scenario

The artifacts option was not actually optional even though examples show it being optional.
As well, artifacts needs to be an absolute path not relative for volume mounting to work in `docker run`.

perf: make artifacts dir optional for running a scenario

---

benchmarks/encoder/config.yaml
benchmarks/encoder/scenario.py
benchmarks/encoder/utils.py
ddtrace/internal/_encoding.pyx

Currently, the `dd_origin` key and value is encoded from text to the msgpack buffer PER span in a trace, even though the key and value are constant. This results in an unnecessary conversion and encoding every time a span is encoded.
The proposed solution is to convert the `dd_origin` value once per trace into a constant char array, and then directly encode that into the buffer per span, which is a much less costly operation.
The `_dd.origin` key is now also encoded directly as a constant char array into the msgpack buffer instead of importing and reading from the constants file.

Optimize encoding dd_origin

---

benchmarks/encoder/config.yaml

Incorrect `ntags` for `many-tags` scenario run.

fix(perf): fix many-tags encoder scenario

---

benchmarks/flask_simple/app.py
benchmarks/flask_simple/config.yaml
benchmarks/flask_simple/gunicorn.conf.py
benchmarks/flask_simple/requirements_scenario.txt
benchmarks/flask_simple/scenario.py
benchmarks/flask_simple/utils.py
scripts/perf-build-push

Similar to the `django_simple` scenario, but with Flask. We are not hitting any databases, but just generating some random numbers and rendering a template to simulate work load.
Adding some middleware tracing could be good.
A lot of the gunicorn/scenario/utils are copy/pasta from Django. We should consider in the future how we can refactor/DRY this up.

perf: Add flask_simple benchmark scenario

---

ddtrace/opentracer/helpers.py
ddtrace/opentracer/propagation/http.py
ddtrace/opentracer/propagation/propagator.py
ddtrace/opentracer/settings.py
ddtrace/opentracer/span.py
ddtrace/opentracer/span_context.py
ddtrace/opentracer/tags.py
ddtrace/opentracer/tracer.py
ddtrace/opentracer/utils.py
mypy.ini

The `ddtrace.opentracer` module was removed from the mypy ignores configuration, and type hinting was added.

chore[mypy]: add type hinting to opentracer module

---

CHANGELOG.md

While the `Migration from ddtrace<=0.33.0` section in the tracer's Django documentation was removed in #2641 as it was deprecated, there are still possible users who have yet to make the migration and need the link to the legacy documentation. In `CHANGELOG.md`, the provided link is out of date and points to an address that does not exist. The provided link has been replaced by on that correctly links to the documentation for ddtrace=`0.50.3` which still contains the legacy documentation.

chore: Update changelog link to legacy django documentation

---

ddtrace/contrib/pytest/plugin.py
docs/spelling_wordlist.txt
releasenotes/notes/fix-pytest-doctest-4918b724f736ef88.yaml
tests/contrib/pytest/test_pytest.py

From #2792, the pytest plugin caused errors when attempting to use with doctest. The bug was caused by the fact that the pytest hooks used by the plugin takes in pytest `Item` objects as arguments, which contain references to the test module. When used with doctest however, the hooks are provided `DoctestItem` objects which are subclasses of the pytest `Item` class, but do not contain references to the test module in the same manner as `item.module`. Instead, the `DoctestItem` objects store the test module name in its `globs` dictionary.
This fix adds a special case to check if the pytest item contains a `module`, and if not checks for the corresponding `dtest` (Doctest) item which will contain the module name.
Resolves #2792

fix[pytest]: extract module name from DoctestItem

---

benchmarks/README.rst
benchmarks/threading/README.rst
benchmarks/threading/config.yaml
benchmarks/threading/scenario.py
docs/spelling_wordlist.txt
scripts/perf-build-push

This benchmark test is used to simulate the creation, encoding, and flushing of traces in threaded environments.
It uses a ``concurrent.futures.ThreadPool`` to manage the total number of workers.
The only modification to the tracing workflow that has been modified is the ``AgentWriter``'s ``_send_payload`` has been overridden to do nothing.
This means we will still start the background worker for the agent, put traces into the queue, and encode them into payloads to send. We will just
not try to make the HTTP call to the agent to reduce any impact from an external process on this test.

perf: add threading benchmark scenario

---

ddtrace/pin.py

Fixed the type hint of the `get_from` method, which could return `None`.

fix(pin): `get_from` type hint

---

ddtrace/contrib/pytest/plugin.py
tests/contrib/pytest/test_pytest.py

* Set `AUTO_KEEP` to span priority for `pytest` test spans. 
This way we make sure that the agent does not drop *any* test span, which is the intended behavior.

[ci-app] Add `AUTO_KEEP` to All `pytest` Test Spans

---

ddtrace/contrib/django/_asgi.py
ddtrace/contrib/django/patch.py
ddtrace/contrib/django/utils.py
releasenotes/notes/fix-django-resource-override-135d9ad7a668a51d.yaml
tests/contrib/django/django1_app/urls.py
tests/contrib/django/django_app/urls.py
tests/contrib/django/test_django.py
tests/contrib/django/views.py

Now that we are setting the `django.request` resource name at the end of the request rather than the beginning, if someone was manually setting the resource name we are overwriting it now.
This change makes is to we will check if the value has been overridden manually first before we set it.

Do not set django.request resource if it was set by the user manually

---

ddtrace/contrib/pytest/plugin.py
tests/contrib/pytest/test_pytest.py

We were setting the pytest error as error tag, which made it hard to debug the actual error: 
Before:
After:

[ci-app] Pytest – Fix Exception Information

---

.gitignore
setup.py

Adds an environment variable to enable Cython annotations.
https://docs.cython.org/en/stable/src/userguide/source_files_and_compilation.html?highlight=annotate#Cython.Compiler.Options.annotate
https://docs.cython.org/en/stable/src/userguide/source_files_and_compilation.html#cythonize-arguments
```
_DD_CYTHON_ANNOTATE=1 pip install -e .
```

internal: Add _DD_CYTHON_ANNOTATE=1 to configure Cython annotations

---

ddtrace/internal/_encoding.pyx
ddtrace/internal/_utils.h
ddtrace/internal/_utils.pxd

Start to collect some common C helpers into `ddtrace/internal/_utils.h` to be shared by all Cython/C modules.

internal: Move common helper to _utils.h

---

riotfile.py

This is a package we currently install by default in `tox`, would be nice to also make available to `riot` venvs.
`pytest-mock`'s biggest benefit is adding `mocker` fixture for pytest functions which will auto-cleanup/reset any mocking at the end of the test execution.

test: add pytest-mock to default packages for riot

---

ddtrace/internal/_encoding.pyx

Define the return type of `cdef pack_span` to avoid converting `cdef int ret` to and from `PyObject*`.
This didn't have as big of a performance change as I expected, but the change to the CPython calls in `pack_span` is improved.
<details>
<summary><b>Before</b></summary>
</details>
<details>
<summary><b>After</b></summary>
</details>

internal: Define return type on pack_span method

---

ddtrace/contrib/pytest/plugin.py
releasenotes/notes/fix-pytest-test-status-dcdef93ac5b988d7.yaml
tests/contrib/pytest/test_pytest.py

When there's a `pytest` internal error, `pytest_runtest_makereport` is not called, so we never set the `test.status`. By preemptively setting a failed test status we make sure that if a test fails because of an internal error, we do set `test.status`.

[ci-app] Pytest – Fix Potentially Missing `test.status`

---

.github/workflows/codeql-analysis.yml

Static code analysis on dd-trace-py using Github's Code Scanning.
This PR has Github workflow configs to trigger the Code Scanning on every PR and on push to default branch. As of now only default security based CodeQL queries are configured. We can gradually add queries for `Code Quality` later. The SARIF results for the code-scanning job is uploaded as an artifact for reference.
The alerts will not show up on master branch until the PR gets merged. But we can see the alerts created for this PR change here: https://github.com/DataDog/dd-trace-py/security/code-scanning?query=pr%3A2842+tool%3ACodeQL

Setting up codescanning for dd-trace-py

---

riotfile.py

setuptools v58 removed support for `use_2to3`. this version of setuptools can be installed on python>=3.6 and has caused some CI failures for some older libraries that we test with (celery, pymongo, mongoengine).
https://github.com/pypa/setuptools/issues/2086
rather than removing testing for these older versions we will just cap the max version we can test them with to Python 3.5.

fix(ci) for packages that use setuptools `use_2to3`

---

.circleci/config.yml
riotfile.py
tox.ini

This is an easy enough review that I've omitted the `riot list`/`tox -l` results
The redis suite run time is now down from ~14 minutes to about 5 minutes

tests: move redis tests to riot

---

.circleci/config.yml

The mypy check takes ~1m30s in CI which increases each CI run by about a minute.

Skip building base for mypy check

---

ddtrace/profiling/collector/stack.pyx
ddtrace/profiling/collector/threading.py
ddtrace/profiling/event.py
releasenotes/notes/profiling-option-to-disable-endpoint-collection-48ab251acb0d9b4e.yaml
tests/profiling/collector/test_stack.py
tests/profiling/collector/test_threading.py

To disable endpoint collection. Enabled by default.

Add support for DD_PROFILING_ENDPOINT_COLLECTION_ENABLED

---

.github/workflows/test_frameworks.yml

Added a new test suite for the requests library. It currently passes all of the tests they are using for their own library when patching with `ddtrace-run` - https://github.com/psf/requests/tree/main/tests.

New test suite on github actions for the request library

---

scripts/profiles/encoders/setup.sh

https://github.com/P403n1x87/austin/pull/85 was merged and the base branch was finally deleted.
It doesn't look like these `austinp` changes have been released yet, so just updating CI to use the `devel` branch instead.

fix(ci) Use austin devel branch instead of austinp

---

ddtrace/contrib/django/patch.py
releasenotes/notes/django-multiple-function-middleware-54999c787cf003a0.yaml
tests/contrib/django/middleware.py
tests/contrib/django/test_django.py
tests/snapshots/tests.contrib.django.test_django_snapshots.test_404_exceptions.snap
tests/snapshots/tests.contrib.django.test_django_snapshots.test_404_exceptions_21x.snap
tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_200_30.snap
tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_200_31.snap
tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_200_3x.snap
tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_500_30.snap
tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_500_31.snap
tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_500_3x.snap
tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_callable_view.snap
tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_callable_view_21x.snap
tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_partial_based_view.snap
tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_partial_based_view_21x.snap
tests/snapshots/tests.contrib.django.test_django_snapshots.test_safe_string_encoding.snap
tests/snapshots/tests.contrib.django.test_django_snapshots.test_safe_string_encoding_21x.snap
tests/snapshots/tests.contrib.django.test_django_snapshots.test_urlpatterns_include.snap
tests/snapshots/tests.contrib.django.test_django_snapshots.test_urlpatterns_include_21x.snap

Fixes #2873
Just like it was pointed out in #2873 we evaluate the resource name for function middleware after we have looped through all of the middleware and we were using a shared reference to the `mw_path` variable used for the resource name.
This change adds a function wrapper to allow us to close over the proper resource name.

fix(django): Fix multiple fn middleware sharing the same resource name

---

ddtrace/constants.py
ddtrace/contrib/pytest/plugin.py
ddtrace/ext/priority.py
ddtrace/sampler.py
ddtrace/span.py
ddtrace/tracer.py
releasenotes/notes/moved-priority-constants-316d6b3b791d6b3e.yaml
tests/contrib/django/test_django.py
tests/contrib/gevent/test_tracer.py
tests/opentracer/core/test_span.py
tests/opentracer/core/test_tracer.py
tests/tracer/test_sampler.py
tests/tracer/test_tracer.py

The constants from `ddtrace.ext.priority` have been deprecated and been relocated to the `ddtrace.constants`. This is to  help restructure the tracer for v1.0

moved ddtrace.ext.priority to ddtrace.constants

---

tests/contrib/sanic/conftest.py
tox.ini

The sanic latest tests are failing due to the pytest-sanic plugin not updating in response to the `21.9.0` sanic release.

Pin latest sanic tests

---

ddtrace/constants.py
ddtrace/ext/system.py
ddtrace/tracer.py
releasenotes/notes/moved-system-constants-7894698d5734235a.yaml
tests/tracer/test_tracer.py

Relocated system constant from `ddtrace.ext.system` to the `ddtrace.constants` module. This is to help restructure the tracer for v1.0

moved ddtrace.ext.system constant

---

ddtrace/constants.py
ddtrace/contrib/cassandra/session.py
ddtrace/contrib/cherrypy/middleware.py
ddtrace/contrib/flask/middleware.py
ddtrace/contrib/grpc/client_interceptor.py
ddtrace/contrib/grpc/server_interceptor.py
ddtrace/ext/errors.py
ddtrace/opentracer/span.py
ddtrace/span.py
releasenotes/notes/moved-error-constants-97c7278a381b56d0.yaml
tests/contrib/cassandra/test.py
tests/contrib/cherrypy/test_middleware.py
tests/contrib/django/test_django.py
tests/contrib/flask/test_middleware.py
tests/contrib/grpc/test_grpc.py
tests/contrib/molten/test_molten.py
tests/contrib/pylons/test_pylons.py
tests/contrib/requests/test_requests.py
tests/contrib/sqlite3/test_sqlite3.py
tests/contrib/urllib3/test_urllib3.py
tests/contrib/vertica/test_vertica.py
tests/opentracer/core/test_span.py
tests/tracer/test_span.py

Relocated error constant from `ddtrace.ext.error` to the `ddtrace.constants` module and deprecated the `get_traceback()` method. This is to help restructure the tracer for v1.0

moved ddtrace.ext.error constant

---

riotfile.py

Pin async-timeout to <4.0.0 for older aiohttp versions
async-timeout introduces a breaking change (changing the `timeout` class
to a function) which breaks older versions of aiohttp.

Pin async-timeout to <4.0.0 for older aiohttp versions

---

ddtrace/internal/writer.py
tests/integration/test_integration.py

Adding new environment variable `_DD_TRACE_WRITER_LOG_ERROR_PAYLOADS`
which when enabled will update the existing "failed to send traces to Datadog agent" log message
to include the payload.
The purpose of this is to debug any trace agent decoding issues.
With this we will be able to validate that the payloads
generated are valid and complete messages as expected.
The resulting log will look like:
```
ERROR:ddtrace.internal.writer:failed to send traces to Datadog Agent at http://localhost:8126: HTTP error status 400, reason Bad Request, payload <hex_encoded_mspack_binary_data>
```
You can then decode via:
```python
import binascii
import msgpack
payload = msgpack.unpackb(binascii.unhexlify("<hex_encoded_mspack_binary_data>"))
```
{{title}}
Adding new environment variable …

Add option to log payloads on error response from the trace agent

---

.github/workflows/build_deploy.yml

{{title}}
The 3.10 package that cibuildwheel is trying to download no longer exists
on python.org.
Skip this version of Python on macos until this PR is resolved:
https://github.com/pypa/cibuildwheel/issues/902

fix(ci) Skip running cibuildwheel for Python 3.10 on macos

---

benchmarks/encoder/utils.py

1. Set fixed random seed to ensure that generated input is the same between runs.
2. Use dict.fromkeys instead of set to guarantee the same order in generated input. (https://stackoverflow.com/a/53657523/2678487)
I assume that the goal of benchmark for **Encoder** is to measure latency of encoding. The only factor that must be different between runs is a version of tracer. Thus I propose a fix for variability in randomly generated input data.
_Long version:_
I encountered the issue - the results from **Encoder** family of benchmarks deviate a lot when running multiple times (not only quantitatively, but qualitatively as well). I believe we can improve this by introducing 2 simple fixes in benchmark script.
There are several methods to design experiments. One of the simplest and most …

Improve determinism of encoder benchmarks

---

.github/workflows/build_deploy.yml

Reverts DataDog/dd-trace-py#2976
The issue has been resolved, this work around is no longer needed.

Revert "fix(ci) Skip running cibuildwheel for Python 3.10 on macos"

---

ddtrace/contrib/botocore/patch.py
docs/spelling_wordlist.txt
releasenotes/notes/fix-botocore-env-vars-89b106aadf2bba1d.yaml
tests/contrib/botocore/test.py

{{title}}
fixes #2978
We were not calling `asbool` when parsing the values

fix(botocore) ensure env vars are parsed as booleans

---

tests/profiling/collector/test_stack.py

This test regularly fails because the first events from the stack collector are
from the gevent thread booting up, while we expect to get frames from the
thread running.
This changes the test to ignore events where we see the thread boot time, and
only look for when the thread actually runs. If we find it once, we know we're
good.

test(profiling): enhance gevent thread hub/task detection

---

tests/profiling/collector/test_stack.py

This tests still fails from time to time because we don't see sleep() or
_nothing() in the last stack: calling gevent sleep might trigger the gevent hub
switch() function which is reported as the last function called.
Nevertheless, _nothing() and/or sleep() are still in the stack trace, which is
what we want. We just need to look deeper.

test(profiling): improve gevent task testing

---

tests/contrib/urllib3/test_urllib3.py

The previous test attempted to use a subdomain to mimic a broken
resolution but this actually is not broken for later versions of linux +
docker.

tests(urllib3): use an actual broken url

---

ddtrace/contrib/falcon/__init__.py

We previously recommended the use of `DATADOG_FALCON_DISTRIBUTED_TRACING` when it should be `DD_FALCON_DISTRIBUTED_TRACING` since we've deprecated DATADOG_ envars.

Update Falcon doc to not suggest a DATADOG_ envar

---

benchmarks/bm/__init__.py
benchmarks/bm/_scenario.py
benchmarks/bm/_to_bool.py
benchmarks/django_simple/scenario.py
benchmarks/encoder/scenario.py
benchmarks/flask_simple/scenario.py
benchmarks/span/scenario.py

Boolean values are incorrectly parsed and are always set to True. This bugfix uses code from [not yet released attrs 21.3.0](https://www.attrs.org/en/latest/api.html#attr.converters.to_bool) to fix the issue.

Fix how bool values from config.yml are parsed for perf benchmarks

---

riotfile.py

Tests failing for pytest, flask, cherrypy, and celery.
more_itertools>=8.10.11 is not compatible with python 3.5

fix more_itertools in ci

---

ddtrace/internal/writer.py
releasenotes/notes/fix-writer-recreate-8780a0713812efeb.yaml
tests/tracer/test_writer.py

{{title}}
Configure a writer thread in a child process after forking based on writer configuration from its parent process.

fix(internal): preserve writer configuration when forking

---

ddtrace/internal/writer.py
tests/integration/test_encoding.py
tests/integration/test_integration.py

{{title}}
Add the api endpoint to the log messages where we are reporting the agent url.

Add agent endpoint to log messages

---

.github/workflows/test_frameworks.yml

Pin graphene version to previous version (2.1.9)
New 3.0.0 release contains breaking graphql changes

ci fix: starlette

---

ddtrace/internal/_encoding.pyx
ddtrace/internal/pack_template.h
riotfile.py
tests/vendor/msgpack/test_buffer.py
tests/vendor/msgpack/test_case.py
tests/vendor/msgpack/test_except.py
tests/vendor/msgpack/test_limits.py
tests/vendor/msgpack/test_pack.py
tests/vendor/msgpack/test_read_size.py
tests/vendor/msgpack/test_seq.py
tests/vendor/msgpack/test_subtype.py
tests/vendor/msgpack/test_unpack.py

{{title}}
It's handy to have a general msgpack encoder that can be used for
encoding arbitrary payloads of primitive Python types (see #2915).
The encoder added here is based off the one added in #1491.
It might be useful to use as a fallback for encoding traces as well if
an issue with the custom msgpack encoder is suspected.
The relevant tests from the msgpack-python implementation are included
as well to ensure that the implementation is correct.

Add msgpack Packer based off msgpack-python 0.6.2

---

riotfile.py
tests/contrib/pymongo/test.py

{{title}}
Our tests relied on `Collection.count` which has been deprecated in favor of `Collection.count_documents`. Other than the API change the resource name changed from `count ...` to `aggregate ...`.
https://github.com/mongodb/mongo-python-driver/blob/2c28149a301bb33b3347bf38f8dbfe085215ca38/doc/migrate-to-pymongo4.rst

tests(pymongo) support pymongo 4.0 in tests

---

ddtrace/contrib/futures/threading.py
releasenotes/notes/fix-futures-args-a206048e19889ad7.yaml
tests/contrib/futures/test_propagation.py

{{title}}
Calling `ThreadPoolExecutor.submit(fn=target)` would raise an `IndexError: tuple index out of range` exception.
This is because we assumed that `args[0]` would always be the target function and never considered that it could be provided in `kwargs`.
We are not using our helper function because we need to remove `fn` from either `args` or `kwargs` once it is found.
Fixes #3000

fix(futures) Allow calling ThreadPoolExecutor.submit with fn kwarg

---

.circleci/config.yml
ddtrace/profiling/collector/_task.pyx

{{title}}
Our CI relied on flake8-isort to catch isort issues but it doesn't run
on Cython files. Instead, we can run the formatting command and verify
that no changes are made to source files which better ensures that all
formatting has been done.

Catch Cython isort formatting issues in CI

---

ddtrace/context.py

{{title}}
Small optimization to avoid creating a `threading.RLock` or two dicts if we are just going to overwrite them anyways.
This gives us a very tiny performance optimization, but mostly helps us avoid creating an additional RLock/two dicts which will save us on object creation + GC.
**Benchmark: tracer**
| Benchmark      | _master_ | _this branch_ |
| -- | -- | -- |
| tracer-small | 506 us | 500 us: 1.01x faster | 
| tracer-medium  | 4.90 ms | 4.79 ms: 1.02x faster |
| tracer-large   | 50.6 ms | 47.2 ms: 1.07x faster |
| Geometric mean | (ref) | 1.03x faster |
**Benchmark: flask_simple**
| Benchmark      | _master_ | _this branch_ |
| -- | -- | -- |
| flasksimple-baseline | 4.66 ms | 3.72 ms: 1.25x faster | 
| flasksimple-tracer   | 4.31 ms | 3.78 ms: 1.14x faster |
| …

perf: don't create unnecessary lock with Context._with_span usage

---

ddtrace/context.py
ddtrace/span.py
docs/advanced_usage.rst

{{title}}
Previously in #3036 we made a change to use a forksafe RLock
but did not re-measure the performance overhead of the change.
Creation of a `forksafe.RLock()` is 3 times slower than a
regular `threading.RLock`.
master   - Context(): Mean +- std dev: 3.24 us +- 0.34 us
v0.56.1  - Context(): Mean +- std dev: 754 ns +- 17 ns
Given that we do not _require_ a forksafe lock here we
should use a normal `threading.RLock` for performance reasons.

perf: use non-forksafe RLock in context

---

riotfile.py
tests/contrib/rq/test_rq.py
tests/snapshots/tests.contrib.rq.test_rq.test_queue_failing_job.json
tests/snapshots/tests.contrib.rq.test_rq.test_queue_failing_job_pre_1_10_1.json

{{title}}
They changed the behavior for calling sync tasks, they
will now no longer raise an exception.

tests(rq) support RQ 1.10.1

---

docker-compose.yml
riotfile.py
tests/contrib/botocore/test.py

{{title}}
New version of `botocore` added a new region that was not recognized by `moto` causing a startup error.
This PR:
- upgrades `localstack`/`moto` server containers to latest.
- update `moto` test library to latest for `botocore`
- Fix `mock_kinesis`/`mock_firehose` usage

fix failing botocore test suite

---

conftest.py
tox.ini

{{title}}
We have tests which are flaky because of this health check.
While we do not want tests to be too slow, we don't need to
fail the tests if it is slow.

tests: disable hypothesis too_slow health check

---

docs/configuration.rst

DD_LOGS_INJECTION defaults to false here: https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/settings/config.py#L141
update documentation to reflect the default value

reflect proper default for DD_LOGS_INJECTION

---

ddtrace/profiling/collector/_task.pyx
ddtrace/profiling/collector/stack.pyx
tests/profiling/collector/test_task.py

This moves the task listing thread check into `list_tasks()` which allows to
simplify a bit the logic of injecting wall time, and prepare the future for
being able to list tasks per thread (hello asyncio).

refactor(profiling): simplify task listing with gevent

---

pyproject.toml

I have been using [lsp-pyright](https://emacs-lsp.github.io/lsp-pyright/) for development, found that I need a minimal config of ignores for it to work properly (not be very very slow since it'll look in all of these folders).
I can also configure this in a `pyrightconfig.json` and just not commit it if we don't want to add this to the repo. I don't have strong opinions / won't be hurt if someone rejects this.
{{title}}

internal: add tool.pyright excludes to pyproject.toml

---

ddtrace/profiling/profiler.py

This is getting annoying to maintain on the long run and its error prone.
If an attribute is missing on the Profiler, just forward the request to the
underlying profiler instance.

refactor(profiler): implement __getattr__ rather than listing properties

---

riotfile.py

fix snowflake tests by pinning the responses package from latest (0.17.0) to v0.16.0

fix: snowflake ci

---

ddtrace/internal/hostname.py
tests/tracer/test_hostname.py

Currently the test `test_get_hostname` depends on hostname._hostname not being set before the test is run. This won't always be the case (telemetry client may set this global variable in the future). 
This change ensures that this test does not depend on the state of a global variable.

Update tracer get hostname unit test

---

riotfile.py

{{title}}
This will save us from needing to have PostgreSQL dev headers
available in order to install/run these tests.
It will also allow us to more easily run these tests from macos

internal: use psycopg2-binary for testing

---

scripts/profiles/encoders/setup.sh

The latest development version of austinp requires the bfd headers to build, which on Debian-like distros are provided by binutils-dev.
{{title}}

ci(encoders): add missing austinp build dependency

---

docs/installation_quickstart.rst

{{title}}
We now publish `musllinux` wheels so installing from source is
no longer required

docs: remove Alpine installation instructions

---

docs/spelling_wordlist.txt

This doesn't get picked up locally, but CircleCI jobs just started failing all of a sudden with this.
{{title}}

fix(docs): add formatter to spelling wordlist

---

ddtrace/profiling/auto.py

{{title}}
Added a log debug statement in ddtrace.profiling.auto to log if the profiler has been enabled automatically on module import.

fix(profiling): add logging in prifling.auto

---

ddtrace/profiling/collector/_traceback.pyx
ddtrace/profiling/collector/threading.py
ddtrace/profiling/event.py
ddtrace/profiling/exporter/pprof.pyx

In some cases, f_lineno can be `None` which would trigger an error in the pprof
output. This is not even caught by mypy, and I've proposed a fix here:
https://github.com/python/typeshed/pull/6769
This patch makes sure we always use 0 if the line number is `None`.
It also makes sure a funcname is always passed — in practice it's now the case,
but make sure typing reflects that.
Fixes #3046

fix(profiling): make sure lineno is always an int and funcname is never None

---

ddtrace/contrib/aioredis/patch.py
releasenotes/notes/fix-aioredis-coroutine-execute-10fc849a7123b456.yaml
tests/contrib/aioredis/test_aioredis.py
tests/snapshots/tests.contrib.aioredis.test_aioredis.test_closed_connection_pool.json

Fixes #3133
Problem reproduced: 
[_Example of the error in CI_](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/13278/workflows/d03dd931-9619-4a9d-8626-ec2fb10aa55c/jobs/948017)
* aioredis 1.3 execute can be a coroutine
The execute command might be `coroutine` instead of `future` ([source](https://github.com/aio-libs/aioredis-py/blob/v1.3.1/aioredis/pool.py#L191)), that is why it is producing this error:
`AttributeError: 'coroutine' object has no attribute 'add_done_callback'`
This PR creates another future from the coroutine and assigns the callback function to that future.
Build is failing for Python 3.10, but couldn't find out why exactly, might be due to creating the pool in aioredis 1.3 (default behavior of aioredis 2). Might be related to …

fix(aioredis): function is coroutine instead of future when pool is empty in aioredis 1.3

---

riotfile.py

{{title}}
Fixes:
```
dd-trace-py/ddtrace/span.py:docstring of ddtrace.span.Span::more than one target found for cross-reference 'Tracer': ddtrace.opentracer.Tracer, ddtrace.opentracer.tracer.Tracer, ddtrace.Tracer, ddtrace.tracer.Tracer
```

fix(docs): Sphinx 4.4.0 has trouble resolving type hinted Tracer class

---

.github/workflows/codeql-analysis.yml

`upload_artifact` is used only for debugging reasons (to export the SARIF results from the GitHub action). So, this PR removes the `upload_artifact` step

removing upload_artifact step

---

.circleci/config.yml
riotfile.py

Disabling coverage reporting will avoid this `coverage` error.
```
internal error
File /root/project/.riot/venv_py3101_mock_pytest_pytest-mock_coverage_pytest-cov_opentracing_hypothesis/lib/python3.10/site-packages/_pytest/main.py, line 269, in wrap_session
session.exitstatus = doit(config, session) or 0
File /root/project/.riot/venv_py3101_mock_pytest_pytest-mock_coverage_pytest-cov_opentracing_hypothesis/lib/python3.10/site-packages/_pytest/main.py, line 323, in _main
config.hook.pytest_runtestloop(session=session)
File /root/project/.riot/venv_py3101_mock_pytest_pytest-mock_coverage_pytest-cov_opentracing_hypothesis/lib/python3.10/site-packages/pluggy/_hooks.py, line 265, in __call__
return self._hookexec(self.name, self.get_hookimpls(), kwargs, …
```

fix(ci): disable code coverage for Flask tests

---

ddtrace/profiling/exporter/pprof.pyx
tests/profiling/exporter/test_pprof.py

{{title}}
In python 2.7 the profiler fails to export http events if the resource name is unicode (commit which introduced typing in the profiler 652021270e81922cbb1edb60180e42619c7203a2). 
This error was introduced in v0.57.0. In a recent release to dogweb there was a significant increase in errors. 
Sample Error:
```
File "/usr/local/lib/python2.7/site-packages/ddtrace/profiling/scheduler.py", line 53, in flush
exp.export(events, start, self._last_export)
File "/usr/local/lib/python2.7/site-packages/ddtrace/profiling/exporter/http.py", line 150, in export
profile = super(PprofHTTPExporter, self).export(events, start_time_ns, end_time_ns)
File "ddtrace/profiling/exporter/pprof.pyx", line 594, in ddtrace.profiling.exporter.pprof.PprofExporter.export
File …
```

fix (python 2.7): profiler raises a typing error when Span.resource is unicode

---

docs/release_notes.rst

In #3085 when we moved to manually specifying release branches
we stopped including any release notes on the current branch
in the docs build.
This means that spell checking for a release note won't occur
until it is merged into a release branch which is far too late.
With this change we will include the full change log entry list
for the current branch when we are using the 'spelling'
builder.

fix(ci): Re-enable spell checking for PR release notes

---

ddtrace/helpers.py

As per the title.
IMO, it's important to show the alternative when a function or something gets deprecated.
The alternative is only shown in [the releasenote](https://github.com/DataDog/dd-trace-py/blob/master/releasenotes/notes/log-correlation-context-22d56ee0b5cc9cfa.yaml).

fix: update deprecation warning for get_correlation_ids to include alternative

---

ddtrace/contrib/pymongo/client.py
releasenotes/notes/pymongo-disabled-tracer-bug-fix-d7782296afe5c1a9.yaml
tests/contrib/pymongo/test.py

Currently we attempt to wrap pymongo operations in a span when `tracer.enabled == False`. This raises an exception since spans are not generated on a disabled tracer. An example of this error is linked below:
Fix: https://github.com/DataDog/dd-trace-py/issues/3140

fix: Pymongo raises an AttributeError when the tracer is disabled

---

ddtrace/profiling/collector/_memalloc_heap.c

This should use the heap tracker passed as argument.
Since there's only one heap tracker currently, this does not change anything in
practice.

refactor(profiling/heap): do not use global heap tracker

---

ddtrace/profiling/collector/_memalloc_heap.c
releasenotes/notes/profiler-heap-max-alloc-bugfix-646423cdd7f7811f.yaml

There's a possibility that the number of tracked allocs overflow the maximum
if, e.g., 65k allocs are stored in the alloc tracker and then 1k allocs are
stored in the freezer: when the freezer is merged back in the alloc tracker,
then it will overflow.

fix(profiling/heap): check correctly maximum number of tracked allocs

---

ddtrace/profiling/collector/_memalloc_heap.c
ddtrace/profiling/collector/_memalloc_heap.h
releasenotes/notes/profielr-heap-iterate-freezer-frees-a366cc6dbeadd188.yaml

The current type that was being used was a uint16_t, which would overflow if
there was more than 2^16 frees in the freezer. The freezer can contain up to
2^64 frees.

fix(profiling/heap): use the right integer type to iterate over freezer frees

---

ddtrace/internal/encoding.py
releasenotes/notes/fix-json-encoder-bytes-d35121d00f2b8caf.yaml
tests/tracer/test_encoders.py

{{title}}
If a `bytes` string is used in span metadata and you are using
the lambda layer/`LogWriter` which uses the `JSONEncoder`
you will get an exception.
This change turns our base `JSONEncoder` class into a subclass
of `json.JSONEncoder` so we can overwrite `JSONEncoder.default`
and properly decode `bytes`.
Subclassing from `json.JSONEncoder` means we don't need to define
an `encode` method on the base class.
Fixes #3115

fix: decode bytes strings when using JSON encoder

---

ddtrace/contrib/pyramid/trace.py

Span.tracer will be removed in ddtracev1.0.
This change replaces `_datadog_span` attribute with `_datadog_tracer`.

fix: update pyramid instrumentation to add tracer attribute to requests

---

ddtrace/filters.py

fixes flake8 error introduced by a merge conflict

fix: spantypes in ddtrace1.0

---

setup.py

This is currently included and shipped as a Python module.

build: remove benchmarks from generated zip/wheels

---

.github/workflows/pr-name.yml
commitlint.config.js

Use [commitlint](https://commitlint.js.org/) for ensuring the PR titles used for squash merges will follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
Output for invalid PR title: https://github.com/DataDog/dd-trace-py/runs/5009766892?check_suite_focus=true

ci: add conventional commits linter

---

ddtrace/internal/writer.py
tests/integration/test_integration.py

fix(internal): use correct max item size variable in log warning

---

.github/workflows/test_frameworks.yml

This PR bumps the framework test suite from v0.18.1 to v0.22.0.
`pytest_asyncio==0.17` raises an AssertionError which causes the `httpx-testsuite-0_18_1` framework test suite to fail. This dependency was fixed in the latest release (v0.22.0).

ci: bump httpx framework tests

---

docs/requirements.txt

The docs build is failing on readthedocs due to a missing dependency
```
/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/docs/checkouts/readthedocs.org/user_builds/ddtrace/checkouts/latest/ddtrace/profiling/_build.pyx
tree = Parsing.p_module(s, pxd, full_module_name)
/home/docs/checkouts/readthedocs.org/user_builds/ddtrace/envs/latest/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/docs/checkouts/readthedocs.org/user_builds/ddtrace/checkouts/latest/ …
```

fix: readthedocs build

---

ddtrace/appsec/processor.py
tests/appsec/test_processor.py

Update from https://github.com/DataDog/dd-trace-py/pull/3192/ given new code added by https://github.com/DataDog/dd-trace-py/pull/3027.

fix(appsec): ddtrace.ext.SpanTypes not an Enum

---

tox.ini

The .ddriot directory can be large and does not need to be linted so it should be ignored.

chore(flake): ignore .ddriot directory

---

riotfile.py

The tracer ci job began to fail for a single test file once pytest 7.0.0 was released:
```
collection failure
ImportError while importing test module '/root/project/tests/tracer/test_http.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py:127: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
tests/tracer/test_http.py:3: in <module>
from hypothesis.provisional import urls
.riot/venv_py399_mock_pytest_pytest-mock_coverage_pytest-cov_opentracing_hypothesis/lib/python3.9/site-packages/hypothesis/provisional.py:35: in <module>
_tlds = read_text("hypothesis.vendor", "tlds-alpha-by-domain.txt").splitlines()
../.pyenv/versions/3.9.9/lib/python3.9/importlib/resources.py:139: in …
```

ci: pin pytest < 7.0.0

---

ddtrace/tracer.py
releasenotes/notes/remove-tracer-writer-b1875a1fa3230236.yaml
tests/contrib/aiohttp/test_middleware.py
tests/contrib/falcon/test_suite.py
tests/integration/test_integration.py
tests/integration/test_integration_snapshots.py
tests/utils.py

The `Tracer.writer` is exposed as part of the public API but is in fact an internal structure. This PR moves the writer to a private attribute `_writer`, following the convention in the codebase without exposing this attribute as a property.

chore(tracer)!: remove Tracer.writer

---

ddtrace/utils/__init__.py
releasenotes/notes/fix-utils-import-c0f574d76de77261.yaml

Fixes: #3242
This will otherwise bring up the following error from mypy when type checking a code base that import ddtrace:
> Source file found twice under different module names: "ddtrace.internal.utils" and "ddtrace.internal.utils.__init__"
This error didn't occur with version 0.57.3 but did with 0.58.0.

fix: correct import to not reference `__init__`

---

benchmarks/encoder/utils.py
benchmarks/sampling_rule_matches/scenario.py
ddtrace/opentracer/span.py
ddtrace/span.py
ddtrace/tracer.py
releasenotes/notes/remove-span-tracer-ddtrace-1-0-bc0ced48b2806e3c.yaml
tests/contrib/celery/test_utils.py
tests/contrib/grpc/test_grpc.py
tests/tracer/test_context.py
tests/tracer/test_encoders.py
tests/tracer/test_filters.py
tests/tracer/test_processors.py
tests/tracer/test_rand.py
tests/tracer/test_sampler.py
tests/tracer/test_span.py
tests/tracer/test_trace_utils.py
tests/tracer/test_tracer.py
tests/tracer/test_writer.py

Deprecated `Span.tracer` was removed. Tracer parameter was also removed from Span.__init__()

chore!: remove Span.tracer property

---

setup.cfg
tox.ini

Move the flake8 configuration out of `tox.ini` and into `setup.cfg`.
We cannot use `pyproject.toml` as flake8 does not yet support [PEP 518](https://www.python.org/dev/peps/pep-0518/). 
https://github.com/PyCQA/flake8/issues/234

chore: move flake8 configuration

---

ddtrace/internal/debug.py
ddtrace/tracer.py
releasenotes/notes/deprecate-tracer-sampler-attribute-c7c9d0523a8162a7.yaml
tests/commands/ddtrace_run_priority_sampling.py
tests/contrib/aiohttp/test_middleware.py
tests/integration/test_integration_snapshots.py
tests/tracer/test_sampler.py

Addes deprecations warnings to Tracer.sampler and Tracer.priority_sampler. These attributes will be removed from the public api in v1.0

chore(tracing): internalize Tracer.sampler and Tracer.priority_sampler

---

tests/tracer/test_global_config.py

This test is no longer necessary after #2996.

chore: remove DATADOG_ENV test

---

ddtrace/internal/debug.py
ddtrace/internal/runtime/tag_collectors.py
ddtrace/tracer.py
releasenotes/notes/deprecate-tracer-tags-attribute-e1b3706820110a09.yaml
tests/commands/ddtrace_run_env.py
tests/commands/ddtrace_run_global_tags.py
tests/contrib/tornado/test_config.py
tests/tracer/test_tracer.py

Global tags should be set via environment variable `DD_TAGS<dd-tags>`

chore(tracing): deprecate Tracer.tags

---

tests/appsec/test_processor.py

SpanType is no longer an Enum in ddtrace v1.0.  This change updates an appsec snapshot test which was introduced in this PR DataDog/dd-trace-py/pull/3239.

fix(appsec): remove SpanType Enum

---

ddtrace/contrib/httpx/patch.py
releasenotes/notes/httpx-service-ensure-text-03dbf31d2ff29fc2.yaml
tests/contrib/httpx/test_httpx.py

This can cause issues for sampling since we generate a rate by service key
by concatenating `str` with the span service name. In this case if it is
`bytes` then the concatenation will fail

fix(httpx): ensure httpx service name is not bytes

---

ddtrace/internal/debug.py
ddtrace/tracer.py
releasenotes/notes/deprecate-tracer-log-attribute-a7fb4c9c23d5b7b4.yaml
tests/commands/ddtrace_run_debug.py
tests/commands/ddtrace_run_no_debug.py
tests/integration/test_debug.py
tests/tracer/test_tracer.py

This change makes logging consistent with the other ddtrace modules (ex. writer.py). 
Note: `from ddtrace.tracer import log` is used to avoid import conflicts with the global tracer's log attribute (`ddtrace.tracer.log` -> Tracer.log)

chore(tracer): deprecate Tracer.log attribute

---

ddtrace/bootstrap/sitecustomize.py
ddtrace/tracer.py
docs/configuration.rst
releasenotes/notes/ddtrace-1.0-disable-basic-config-call-by-default-b677844e4a13a794.yaml
tests/commands/test_runner.py
tests/integration/test_debug.py
tests/integration/test_integration.py

ddtrace should not call `logging.basicConfig` since it is not a logging library.  
This PR updates the default value of ``DD_CALL_BASIC_CONFIG`` to False and logs a deprecation warning if DD_CALL_BASIC_CONFIG configuration is set to True.

chore(logging)!: set default value of DD_CALL_BASIC_CONFIG to False

---

.circleci/config.yml
ddtrace/contrib/sanic/patch.py
releasenotes/notes/support-sanic-21.9.0-6c5de52c832f9dcc.yaml
riotfile.py
tests/contrib/sanic/run_server.py
tests/contrib/sanic/test_sanic.py
tests/contrib/sanic/test_sanic_server.py
tests/snapshots/tests.contrib.sanic.test_sanic_server.test_multiple_requests_sanic_http.json
tests/snapshots/tests.contrib.sanic.test_sanic_server.test_multiple_requests_sanic_http_pre_21.9.json
tests/snapshots/tests.contrib.sanic.test_sanic_server.test_sanic_errors.json
tests/snapshots/tests.contrib.sanic.test_sanic_server.test_sanic_errors_pre_21.9.json
tox.ini

Newer versions of Sanic will now "touchup" methods
on the `sanic.Sanic` class. This process involves
parsing an AST from the source function, then potentially
modifying the tree before compiling and evaling to get a
new codeobject for the method.
They also now have a `__setattr__` defined to block us
from overwriting methods on the `sanic.Sanic` class.
These together make our patching no longer work.
With Sanic 21.9.0 request lifecycle signals have been added.
In order to support newer versions we now patch `sanic.Sanic.__init__`
and automatically add signals for request start, routing, and response.
We now create a span on request start, attach it to the Sanic request
context, then in subsequent events we'll pull the span from the
request context and either modify or finish the span.
As …

feat(sanic): add support for Sanic>=21.9.0

---

ddtrace/tracer.py
releasenotes/notes/remove-deprecated-tracer-attributes-4bb24b794a1aacb9.yaml

Removes:
- Tracer.sampler
- Tracer.priority_sampler
- Tracer.tags
- Tracer.log

chore(tracer)!: remove deprecated tracer attributes

---

ddtrace/contrib/pytest/plugin.py
releasenotes/notes/pytest-fix-xfail-unsafe-access-f579fef50d5bd4fa.yaml
tests/contrib/pytest/test_pytest.py

Fixes https://github.com/DataDog/dd-trace-py/issues/3276
It seems we were aware `wasxfail` might not be in `result` according to https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/pytest/plugin.py#L205. This just extends this safe access to every time we use it.

fix(ciapp/pytest): do not access XFAIL reason unsafely

---

ddtrace/contrib/flask/patch.py
releasenotes/notes/flask_improve_resource_naming_when_error_occurs-ea094145551e4ec7.yaml
tests/contrib/flask/test_request.py

Before this change, if an error was thrown in the middleware, we would just get `<method> <status_code>` as the resource name. With this change, we get `<method> <path>` which means the error will be grouped with the rest of the endpoint's hits/errors.

fix: fix Flask resource naming when error thrown in middleware

---

ddtrace/contrib/aiopg/connection.py
ddtrace/contrib/dbapi/__init__.py
ddtrace/contrib/django/patch.py
ddtrace/contrib/mariadb/patch.py
ddtrace/contrib/mysql/patch.py
ddtrace/contrib/mysqldb/patch.py
ddtrace/contrib/psycopg/patch.py
ddtrace/contrib/pymysql/patch.py
ddtrace/contrib/pyodbc/patch.py
ddtrace/contrib/snowflake/patch.py
ddtrace/contrib/sqlite3/patch.py
ddtrace/contrib/vertica/constants.py
ddtrace/contrib/vertica/patch.py
tests/contrib/dbapi/test_dbapi.py
tests/contrib/mysql/test_mysql.py

The dbapi `TracedCursor` uses the `Pin.app` to set span names. As we want to deprecate `Pin.app`, we need to add support for this functionality to dbapi itself. This PR adds support for `config._dbapi_span_name_prefix`. This approach is straightforward in all but the aiopg and django integration. The aiopg integration does not make use of the dbapi integration `TracedCursor` but we can make its span name fixed. The django integration needs to set the prefix based on the vendor of the database connection being patched. To support this an integration config is initialized specific to the database connection.

chore(dbapi): deprecate Pin.app

---

ddtrace/contrib/aiobotocore/patch.py
ddtrace/contrib/aiohttp/patch.py
ddtrace/contrib/algoliasearch/patch.py
ddtrace/contrib/aredis/patch.py
ddtrace/contrib/boto/patch.py
ddtrace/contrib/botocore/patch.py
ddtrace/contrib/cassandra/session.py
ddtrace/contrib/consul/patch.py
ddtrace/contrib/dogpile_cache/patch.py
ddtrace/contrib/httplib/patch.py
ddtrace/contrib/httpx/patch.py
ddtrace/contrib/kombu/patch.py
ddtrace/contrib/mako/patch.py
ddtrace/contrib/molten/patch.py
ddtrace/contrib/pymemcache/patch.py
ddtrace/contrib/pymongo/client.py
ddtrace/contrib/pymongo/patch.py
ddtrace/contrib/redis/patch.py
ddtrace/contrib/rediscluster/patch.py
ddtrace/contrib/requests/patch.py
ddtrace/contrib/sqlalchemy/engine.py
ddtrace/contrib/tornado/application.py
ddtrace/pin.py
releasenotes/notes/deprecate-pin-app-de153348b61a9905.yaml
tests/tracer/test_pin.py

Deprecate `Pin.app`. Though this property is set in many integrations, it is not set on span data.

chore: deprecate Pin.app

---

tests/contrib/grpc/test_grpc_patch.py

Adds tests for patching and unpatching of the GRPC integration.

chore(tracing/grpc): add patch/unpatch tests for grpc integration

---

ddtrace/context.py
releasenotes/notes/remove-clone-context-3cc6f3d73f15345e.yaml

Context.clone was deprecated in the following PR: https://github.com/DataDog/dd-trace-py/pull/2427
With the removal of [active span management](https://github.com/DataDog/dd-trace-py/pull/1936), a trace Context is managed internally and should not be accessed by users.

chore(tracing/context)!: remove Context.clone

---

riotfile.py

`itsdangerous>=2.0` and `markupsafe>=2.0` introduced a breaking
change and older versions of `flask` and `jnija2` do not restrict
upper bound on version.
This change pins `itsdangerous` and `markupsafe` for test environments
for `jinja2` and older versions of `flask`

fix(ci): pin itsdangerous and markupsafe to avoid breaking change

---

riotfile.py

This will help speed up installing `psycopg2` since it will use pre-built wheels when possible.

chore: use psycopg2-binary for django test env

---

ddtrace/tracer.py
releasenotes/notes/tracer-write-5d46dc5c4e870b9b.yaml

The write method is no longer used by the library and it's not a
use-case that we'd like to support.
If a user desires to write spans to a writer then it can be done
manually by using a writer reference.

chore(tracer): deprecate tracer.write method

---

.circleci/config.yml

``origin/master`` branch no longer exists, this change generates a coverage report against 0.x

chore: fix coverage report in 0.59 branch

---

ddtrace/internal/_tagset.pyx
releasenotes/notes/fix-encode-tagset-value-2b8bb877a88bc75a.yaml
tests/tracer/test_tagset.py

`=` is an allowed character in a tag value, but not a tag key.
Fixes: #3318

fix(tracing/internal): fix encoding of propagated internal tags

---

ddtrace/span.py
tests/tracer/test_span.py

This bug was introduced in 0.59.0rc1. This fix should be backported before 0.59.0 is released

fix: set_meta and set_metas deprecation warnings

---

releasenotes/notes/release-1.0-758fc917e40d7eb3.yaml
releasenotes/notes/remove-v1deprecationwarning-2c251ca219182b97.yaml

The `ddtrace.V1DeprecationWarning` category will be introduced with #3333 and released in v0.59.0 which will be the guidance for those looking to upgrade to v1.0.0.

docs: fix warning filter for v1 deprecations

---

tests/tracer/test_rand.py
tests/tracer/test_tracer.py

For some reason multiprocessing tests on macOS and Python 3.8 and above
fail because functions are not pickleable and all locals are pickled which
included the target functions. For some reasons these tests pass fine in Linux
though.
Locally on macOS:
```
obj = <Process name='Process-1' parent=18589 initial>, file = <_io.BytesIO object at 0x106bd0d60>, protocol = None
def dump(obj, file, protocol=None):
'''Replacement for pickle.dump() using ForkingPickler.'''
>       ForkingPickler(file, protocol).dump(obj)
E       AttributeError: Can't pickle local object 'test_tracer_usage_multiprocess.<locals>.target'
/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/reduction.py:60: AttributeError
```

fix(tests): use non-local task functions in multiprocessing tests

---

docs/advanced_usage.rst
releasenotes/notes/release-1.0-758fc917e40d7eb3.yaml

We made some changes in prep for v0.59.0 that require updating the guidance in this release note.

docs: fix deprecation guide in release notes

---

docs/advanced_usage.rst

#3347 forward ported with a cherry-pick from #3338 of the changes to the advanced section. The section label was missing so the docs were failing to build but we had gone ahead with merging because of another known issue with the docs build.

docs: fix missing ref

---

docs/_release_notes_all.rst
docs/release_notes.rst
releasenotes/config.yaml
releasenotes/notes/deprecate-span-get-set-meta-c6fb2528d198414c.yaml
releasenotes/notes/remove-span-get-set-meta-c6fb2528d198414d.yaml

- [fix(docs): fix duplicate release note existing for 0.59 and 1.0](https://github.com/DataDog/dd-trace-py/commit/cd5095415be24ebe2d5780ec152e4637bdfa6bad)
- [fix(reno): set correct default branch name](https://github.com/DataDog/dd-trace-py/commit/7817d80ff14b675afaac100df49d7e5db834d512)
- [fix(docs): build all release notes for spell checking in a different file](https://github.com/DataDog/dd-trace-py/commit/2e5b61fe6744e236dc95ed9f9a83d719d01235ce)

fix(docs): fix broken docs builds for 1.0 branch

---

ddtrace/contrib/pymongo/client.py
releasenotes/notes/pymongo-4.0.2-1f5d2b6af5c158d2.yaml

Pymongo 4.0.2 released which introduced a breaking change to the method signature of `Socket.write_command`: https://github.com/mongodb/mongo-python-driver/compare/4.0.1...4.0.2#diff-43b0ab0dab45c7b3e339879a4452c7dcb43a659ef6603532348a745e6405afd4R819
The patching attempted to match the signature exactly so the fix is trivial in just accepting args/kwargs and extracting what is needed from them.

fix(pymongo): use generic arguments for write_command

---

.circleci/config.yml

The goal is to ensure a regular cadence of builds for our currently active and maintenance release lines. This should help us validate that maintenance branches are still building properly.

chore(ci): run nightly builds of 0.x and 1.x branches

---

ddtrace/opentracer/span.py
releasenotes/notes/opentracer-span-1abe3738df78d3c1.yaml
tests/opentracer/core/test_span.py

As pointed out in #3365 the opentracing Span object returns itself in
its set_tag and set_operation_name methods and our implementation should
match.
Fixes #3365

fix(opentracer/Span): return self in methods

---

ddtrace/vendor/psutil/_psutil_osx.c

Newer versions of macos do not have `getpagesize()`, and instead `PAGE_SIZE` should be used.
https://github.com/giampaolo/psutil/pull/1794

chore(vendor): fix psutil getpagesize() for newer macos

---

ddtrace/contrib/fastapi/patch.py
releasenotes/notes/fastapi-trace-serialize-response-7aa66e459cceb26c.yaml
tests/contrib/fastapi/test_fastapi.py
tests/snapshots/tests.contrib.fastapi.test_fastapi.test_table_query_snapshot.json

We want to add visibility into the time spent calling `jsonable_enoder` for FastAPI. We could wrap `jsonable_encoder`, but because it is called recursively there is a chance we create an unwieldy trace and introduce a performance regression from tracing.
However, `jsonable_encoder` is called from` fastapi.routing.serialize_response`, so we can wrap this instead to get an overall time spent in `jsonable_encoder`.
This does not give us insight into how much time is spent calling `json.dumps()`/`orjson.dumps()`/`ujson.dumps()`/etc (or any time for any call to `Response.render`). `jsonable_encoder` only converts the response data into something that can be encoded as JSON.

feat(tracing/fastapi): add support for tracing fastapi.routing.serialize_response

---

ddtrace/profiling/collector/_lock.py
ddtrace/profiling/collector/threading.py
ddtrace/profiling/exporter/pprof.pyi
ddtrace/profiling/exporter/pprof.pyx
ddtrace/profiling/profiler.py
tests/profiling/collector/test_threading.py
tests/profiling/collector/test_threading_asyncio.py
tests/profiling/exporter/test_pprof.py
tests/profiling/simple_program_fork.py

This splits the lock profiling code to be able to profile any type of lock.

refactor(profiling): split lock profiling in two parts

---

ddtrace/tracer.py
releasenotes/notes/deprecate-tracer-log-attribute-a7fb4c9c23d5b7b4.yaml
releasenotes/notes/fix-tracer-log-deprecation-f0664631263c6fda.yaml

``dtrace.tracer.log`` is no longer supported. ``logging.getLogger("ddtrace.tracer")`` should be used instead.

fix(tracer): tracer log deprecation warning

---

tests/integration/test_integration.py

Something changed causing the number of warning logs to change from 75 to something else. To us it doesn't matter if there are 75 or more warning logs, instead we want to assert that those are the only kind of logs on stderr.
This change changes to a loop and assertions over all log lines instead of trying to do an exact match.
Example failure from CI that prompted this change:
```
=================================== FAILURES ===================================
_______________________________ test_no_warnings _______________________________
def test_no_warnings():
env = os.environ.copy()
env["DD_TRACE_SQLITE3_ENABLED"] = "false"
out, err, status, pid = call_program("ddtrace-run", sys.executable, "-Wall", "-c", "'import ddtrace'", env=env)
assert out == b"", out
if sys.version_info < (3, …
```

chore(tests): update brittle warning log assertion

---

ddtrace/contrib/aiohttp/patch.py
releasenotes/notes/fix-aiohttp-jinja2-import-2b7e29a14a58efdc.yaml

It is possible for Python to try and import the `ddtrace.contrib.aiohttp_jinja2.patch` module instead of the `ddtrace.contrib.aiohttp_jinja2.patch()` function.
Import `patch()` from the `patch` module directly to be more clear.
```
$ docker run --rm -it python:3.9.9 bash
root@413e57731dd1:/# pip install ddtrace==0.60.0rc1
root@413e57731dd1:/# python -c $'from ddtrace.contrib.aiohttp_jinja2 import patch\nprint(patch)'
<module 'ddtrace.contrib.aiohttp_jinja2.patch' from '/usr/local/lib/python3.9/site-packages/ddtrace/contrib/aiohttp_jinja2/patch.py'>
root@413e57731dd1:/# pip install aiohttp_jinja2
root@413e57731dd1:/# python -c $'from ddtrace.contrib.aiohttp_jinja2 import patch\nprint(patch)'
<function patch at 0x7f21ba6fd1f0>
```

fix(tracing/aiohttp): fix error importing `aiohttp_jinja2` integration from `aiohttp`

---

ddtrace/contrib/celery/app.py
releasenotes/notes/remove-app-arg-from-celery-instrumentation-4742d04f4e6474d2.yaml

The following deprecation warning is logged when celery instrumentation is enabled and a Pin object is not set.
```
/usr/local/lib/python2.7/site-packages/ddtrace/contrib/celery/app.py:28: DDTraceDeprecationWarning: Using the 'app' argument is deprecated and will be removed in version '1.0.0'
```

fix(celery): remove deprecated Pin.app

---

Dockerfile.buster

We no longer are using sirun for benchmarks.

chore: remove sirun

---

conftest.py
tests/conftest.py
tests/contrib/gevent/test_monkeypatch.py
tests/contrib/httpx/test_httpx.py
tests/contrib/mariadb/test_mariadb.py
tests/contrib/snowflake/test_snowflake.py
tests/integration/test_debug.py
tests/integration/test_integration.py
tests/runtime/test_runtime_metrics_api.py
tests/tracer/telemetry/test_data.py
tests/tracer/test_atexit.py
tests/tracer/test_encoders.py

The `subprocess` pytest marker can be used to run arbitrary Python code in a Python
subprocess. This is meant to replace the existing fixture to allow actual
Python code to be written and tested, instead of using literal strings.

test: add marker for running tests in subprocess

---

docs/conf.py
docs/release_notes.rst
mypy.ini
riotfile.py

This new `.. ddtrace-release-notes::` directive will dynamically search for all
release branches + earliest release version and generate the desired release notes

chore(docs): add custom directive to dynamically generate release notes

---

ddtrace/internal/writer.py
tests/tracer/test_writer.py

Issues with reusing connections were detected when testing in the environment.
With the timing of 1.0 we're pushing this feature off until version 1.1.

revert(tracer): reusing connections (#2999)

---

ddtrace/contrib/asyncio/__init__.py
docs/advanced_usage.rst

There has been confusion about whether or not the asyncio integration creates traces (it does not) or just provides tracing context management (it does). This doc update clarifies the wording and also increases specificity around when the integration is required.

docs: clarify asyncio support

---

ddtrace/profiling/collector/_task.pyx

This can prevent some cases of circular imports.

chore(profiling): remove unused import in collector._task

---

ddtrace/internal/telemetry/writer.py
tests/tracer/telemetry/test_data.py
tests/tracer/telemetry/test_writer.py

Currently integrations are not sent to the trace agent (telemetry is enabled after patching occurs). 
This change ensures integrations are queued when ``patch`` or ``patch_all()`` is called. 
If telemetry is never enabled we will queue configuration data for up to 64 integrations and these values will persist in memory. The cost of each integration entry is ~100 bytes.

fix(telemetry): ensure integrations are queued on startup

---

.github/workflows/test_frameworks.yml

The 2.1.0 release of MarkupSafe comes with some changes that break some
of the projects that depend on it. We fix the framework tests by pinning
the version to the latest 2.0 release for now.

test: pin MarkupSafe dependency

---

riotfile.py

The recently released version of click is incompatible with `black==21.4b2`:
```
File "/home/circleci/project/.riot/venv_py3912_black214b2_isort/bin/black", line 8, in <module>
sys.exit(patched_main())
File "/home/circleci/project/.riot/venv_py3912_black214b2_isort/lib/python3.9/site-packages/black/__init__.py", line 7010, in patched_main
patch_click()
File "/home/circleci/project/.riot/venv_py3912_black214b2_isort/lib/python3.9/site-packages/black/__init__.py", line 6999, in patch_click
from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/home/circleci/project/.riot/venv_py3912_black214b2_isort/lib/python3.9/site-packages/click/__init__.py)
```

chore: pin click to fix incompatibility

---

ddtrace/profiling/collector/_task.pyx

There is a short window of time where the list can be modified by the coroutine
tracer which triggers this kind of errors:
Unhandled exception in thread started by <bound method _GeventPeriodicThread.run of <_GeventPeriodicThread(ddtrace.profiling.collector.stack:StackCollector, initial daemon)>>
File "/usr/local/lib/python2.7/site-packages/ddtrace/internal/periodic.py", line 141, in run
self._target()
File "/usr/local/lib/python2.7/site-packages/ddtrace/profiling/collector/__init__.py", line 42, in periodic
for events in self.collect():
File "ddtrace/profiling/collector/stack.pyx", line 480, in ddtrace.profiling.collector.stack.StackCollector.collect
File "ddtrace/profiling/collector/stack.pyx", line 298, in …

fix(profiling): copy greenlet list before iterating

---

docker/Dockerfile.buster

Optimizations:
- Squash run commands
- Use binary for ci-app (https://github.com/DataDog/datadog-ci/blob/4518a88465af66d13a838b339fdfb6be7fb96c06/README.md?plain=1#L36-L40)
- Delete node (only needed for installing ci-app)
- Use `--enable-shared` when installing Pythons instead of `--keep` which should replace saving the entire Python source with just the dev headers.
- Remove no longer required packages
This should save some disk space
```
test                                                 latest        056956e4e0fc   About a minute ago   1.79GB
datadog/dd-trace-py                                  latest        5c0d1a225d7a   5 days ago      3.95GB
```
seems to be about 2.16gb (uncompressed) (54% reduction)

ci: dockerfile optimizations

---

ddtrace/internal/processor/__init__.py
ddtrace/internal/processor/trace.py
ddtrace/tracer.py
releasenotes/notes/reset_span_processors_on_shutdown-3d63f33e1354cd5e.yaml
tests/tracer/test_tracer.py

Spans should not be sent to the agent after ``Tracer.shutown()`` is called

fix(tracing): add span processors shutdown

---

ddtrace/tracer.py
releasenotes/notes/add-warning-after-shutdown-tracer-dd8799467c4d29c8.yaml
tests/contrib/gevent/test_monkeypatch.py
tests/tracer/test_tracer.py

Warns users when ``Tracer.trace()`` or ``Tracer.start_span()`` is called after a tracer is shutdown.

feat(tracing): spans not sent to agent after tracer shut down

---

ddtrace/internal/processor/trace.py
ddtrace/span.py
tests/tracer/test_tracer.py

So it can be reused by other parts of the codebase.

refactor(tracer): move top level logic into helper function

---

.circleci/config.yml
tests/integration/test_debug.py

Reverts DataDog/dd-trace-py#3279
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/14858/workflows/de2c5714-7c27-4d3f-bf6f-d1788fbce6a9/jobs/1034017
This flag is broken but somehow the test passes.
```
179c3509: Pulling fs layer
c67aaeb4: Pulling fs layer
734aa436: Pulling fs layer
c8775b19: Pulling fs layer
472d7196: Pulling fs layer
Digest: sha256:a0127e42e224fb60b02de71532fe7e3c2da7b90aa66ae76e286bc470ac4f5d78 28.28MB/28.28MBB
Status: Downloaded newer image for datadog/dd-trace-py:buster
Creating project_testrunner_run ... 
Creating project_testrunner_run ... done^@^@WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: …
```

revert(ci): "fail fast when integration tests fail"

---

hooks/scripts/run-slotscheck.sh
riotfile.py

Reduce the check run time by only scanning staged files

chore: run slotscheck only on staged files

---

tests/opentracer/core/test_tracer.py
tox.ini

Running pytest as an entry point in tox started causing import
errors. Running it as a module fixes this.

test: run pytest as a module

---

.github/workflows/test_frameworks.yml

It takes 4+ hours to install the dependencies to test fastapi. Fastapi
themselves cache the install: https://github.com/tiangolo/fastapi/commit/d75126a4cef0b4b1ac01de79c42d4ce677eab4d4

chore(ci/fastapi): cache fastapi dependency install

---

benchmarks/encoder/utils.py
benchmarks/span/scenario.py
benchmarks/span/utils.py

The expectation with the 0.x to 1.x migration is that changes to the API would not affect performance. With the understanding that noise has not been entirely controlled with runs, the comparisons below show that v0.60.1 is between 1.0 and 1.15 times slower than v1.0.0.rc3.
| Benchmark                                | 1.0.0rc3 | 0.60.1                |
|------------------------------------------|----------|-----------------------|
| encoder-one-trace                        | 324 us   | 373 us: 1.15x slower  |
| encoder-many-traces                      | 37.0 ms  | 41.2 ms: 1.11x slower |
| encoder-one-tag                          | 456 us   | 500 us: 1.10x slower  |
| encoder-one-metric                       | 461 us   | 496 us: 1.08x slower  |
| encoder-many-metrics                     | …

perf: update benchmarks for 1.x

---

docs/conf.py
riotfile.py

This PR introduces the ability to define per-version reno options
for generating release notes.
The config is a yaml encoded map of release version to reno options.
```rst
.. ddtrace-release-notes::
"1.0.0":
ignore_notes:
- "keep-alive-b5ec5febb435daad"
```

chore(docs): allow specifying reno options per-version

---

docs/index.rst
docs/spelling_wordlist.txt
docs/versioning.rst
riotfile.py

This adds a versioning section to the library docs that:
- defines internal and public interfaces
- sets out when versions are incremented
- development on release lines
[Preview](https://output.circle-artifacts.com/output/job/904716c3-5067-45fa-97ca-9d672dd0cb71/artifacts/0/tmp/docs/versioning.html)

docs: add versioning policy

---

.circleci/config.yml

We already cache the tox folder but do not do any caching for riot. This PR caches the pip download cache for all riot jobs. The cache is specific to the parallel node where venvs are created and run.

ci: cache pip downloads per test node

---

docs/release_notes.rst

`pymongo-4.0.2-1f5d2b6af5c158d2` was not getting ignored because
it is assumed that the filename would be provided and `os.path.splitext()`
is called, which would take `2-1f5d2b6af5c158d2` as the file extension.

chore(docs): fix ignore_notes for 1.0

---

tests/integration/test_integration.py

~The test previously had a workaround for the agent being delayed in
sending the updated service sampling rates. However, if the rates are
sent in the first request then the test will fail since the second
request might not contain them and the test would fail.~
The logic was updated in https://github.com/DataDog/datadog-agent/pull/10958
to only return the rates after both 5 seconds have passed and another request
has been sent.

chore(ci): fix priority_sampling test case

---

tox.ini

Doesn't seem like this is necessary?
This fixes an issue with running the tests locally (on macOS)
```
self.consider_pluginarg(parg)
File "/Users/kverhoog/dev/dd-trace-py/.venv2/lib/python2.7/site-packages/_pytest/config/__init__.py", line 531, in consider_pluginarg
self.import_plugin(arg, consider_entry_points=True)
File "/Users/kverhoog/dev/dd-trace-py/.venv2/lib/python2.7/site-packages/_pytest/config/__init__.py", line 581, in import_plugin
six.reraise(ImportError, new_exc, tb)
File "/Users/kverhoog/dev/dd-trace-py/.venv2/lib/python2.7/site-packages/_pytest/config/__init__.py", line 572, in import_plugin
__import__(importspec)
ImportError: Error importing plugin "tests.cache.conftest": No module named cache.conftest
```
as, for some reason, pytest locates and uses another `tests` …

chore(ci): remove tests.cache.conftest early load

---

.circleci/config.yml

Some of the jobs were using parallelism 6 but we run with 7 versions of
Python so some parallel runners run two versions of Python. By bumping
the parallelism to 7 we effectively half the job duration of profiling,
opentracing, kombu and celery.
We missed this regression when we added support for Python 3.10.
This cuts down our cI time from ~40 mins to ~25 mins.

chore(ci): use more parallelism

---

scripts/profiles/encoders/run.sh

Adding the current working directory to the `PYTHONPATH` to allow Python to locate the `tests` package. Why this is now required beats me.

ci: fix encoders profile job

---

tests/conftest.py

This change adds support for running Python code as a module in tests using the `subprocess` marker.

test: add run module support to subprocess marker

---

tests/contrib/botocore/test.py

https://github.com/DataDog/dd-trace-py/pull/3178 introduced a flaky
test, until it can be fixed we'll allow it to fail.

chore(botocore): allow flaky test to fail

---

ddtrace/profiling/collector/stack.pyx
releasenotes/notes/profiling-asyncio-fix-missing-main-thread-dec4b0759094c571.yaml
tests/profiling/collector/test_stack_asyncio.py

The current asyncio code does not report CPU time for the main thread when
there are tasks running.
The code expects one of the task to be the main thread; this is only true for
gevent. Asyncio does not have this behaviour, which means we only can account
wall time for tasks.
The CPU time must be assigned to the regular main thread, just like we'd do for
a non-async program.
Fixes #3572

fix(stack,asyncio): add missing CPU time in asyncio apps

---

ddtrace/internal/writer.py

There existed a critical section with the connection object on writer as
the `periodic` logic of the writer could be invoked from the periodic
writer thread as well as from other threads calling `periodic`
(`tracer.flush()` or `tracer.shutdown()`). The critical section would
result in corrupted http connections. This bug was introduced in #2999.
The solution is to lock the connection when used. I don't suspect that
this would lead to any performance degradation for the vast majority of
users since there is little overhead added to the writer. A degradation
would occur if contending threads were calling `periodic()` as now the
connection is a shared resource.
Example symptom of the error if a race were to occur:
```
except Exception as e:
conn = httplib.HTTPConnection(parsed.hostname, …
```

fix(tracer/writer): lock the connection

---

riotfile.py

celery is the longest running job in CI and we were running many different configurations of the tests (with different kombu versions)

chore(ci): reduce number of celery tests

---

ddtrace/appsec/processor.py
tests/appsec/test_processor.py

The addresses specification states that header keys must be lowercase when passed to the WAF. Without it, some attacks can't be detected.

fix(asm/appsec): header names must be lowercase when passed to the WAF

---

.circleci/config.yml
.github/workflows/set-target-milestone.yml
riotfile.py
scripts/get-target-milestone.py

When a PR is closed with a merge we:
- Determine the target release/milestone based on the target branch name
- If the base branch is `[0-9].x` (dev branch)
- Set the milestone as the next minor release for that release line.
- If the base branch is `[0-9].[0-9]+` (release branch)
- Set the milestone as the next patch release for that version.
- If the branch does not match one of those patterns
- Do not set a milestone.

ci: automatically add release milestone to each PR

---

.circleci/config.yml

We haven't been using them, and they take a minute or two to generate and upload. Save the CPU.

ci: do not generate or update coverage html report

---

ddtrace/contrib/flask/patch.py
tests/contrib/flask/test_flask_appsec.py

On Flask, path_params is broken. I used the wrong data first and the call to `set_http_meta` happens before the call to the method that makes the dispatch in the framework. Meaning we will need to update the instrumentation to cover this.
Let's put it on the side for now (to not have buggy code) and I will find a solution for it later this week/early next week.

fix(asm): remove path_params for flask

---

ddtrace/internal/writer.py
releasenotes/notes/tracer-toplevel-a1600adc84be9039.yaml

This header is required to indicate to the agent that the client is
computing the top level span (otherwise the top level tags the client
sets are ignored). This was missed in the top level implementation
(#2730).
There isn't really a way to integration test this functionality as we don't
have testing for what the agent passes on to the backend. So there isn't
a good way for us to enforce this functionality to ensure no regressions
in the future.
This fix was verified with a manual test case outlined here: https://gist.github.com/Kyle-Verhoog/928243fecb5e4a32c0270cf7ac2d7a0f
According to the top level logic in the agent, we should not ever need to set
`_dd.top_level` to 0 since it is implicitly `0`. It only needs to be set to `1` for
actual top level spans. Not setting the tag should net …

fix(tracer): set top level header

---

ddtrace/contrib/gevent/__init__.py

The statement was contradicting the section above which says the opposite.

docs(gevent): remove redundant, contradictory statement

---

ddtrace/contrib/logging/__init__.py

We missed updating the logs injection documentation in response to the
change of basicConfig call logic in 1.0.

docs(logs): update docs for no basicConfig call

---

tests/conftest.py
tests/internal/test_module.py

This change uses the from_call class method from CallInfo instead of constructing this private object directly to avoid pytest warnings.

ci: use class method to avoid pytest warnings

---

tests/contrib/psycopg/test_psycopg_snapshot.py

This was not consistently working with `@pytest.mark.subprocess`
This change is already incorporated into the #3610 backport PR.

fix(ci): fix psycopg2 snapshot subprocess test

---

README.md

The readme was a little stale with references only to the tracing
functionality. Profiling is really cool and should be mentioned.
Also add a bits logo and fix some references.
Preview the readme here: https://github.com/Kyle-Verhoog/dd-trace-py/tree/readme

chore(readme): update and add bits

---

.github/workflows/test_frameworks.yml

Tests ddtrace compatibility with graphene v3.0
- ddtrace graphql-core integration will be released in a future PR

ci(framework-tests): add graphene framework test

---

ddtrace/bootstrap/sitecustomize.py
ddtrace/internal/agent.py
releasenotes/notes/fix-ddtrace-run-url-envs-087ab03d4f25a732.yaml

`ddtrace-run` will try to parse some env variables like `DD_TRACE_AGENT_HOSTNAME`,
`DD_AGENT_HOST`, and `DD_TRACE_AGENT_PORT` and used them to call `tracer.configure()`.
However, the existing default logic when configuring a tracer uses `agent.get_trace_url()`
which knows about these env variables and the appropriate priority order when configuring.
Fixes #3648

fix(tracing): properly resolve when multiple trace agent url env variables are used

---

ddtrace/propagation/http.py

Suggested in https://github.com/DataDog/dd-trace-py/pull/3625#discussion_r862080605
```
+------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Benchmark                                            | /artifacts/3fd8f93f-09ab-49af-88ef-e7ee2243d0b7/http_propagation_extract/1.1.0rc2.dev37+gd363d6c4//results.json | /artifacts/3fd8f93f-09ab-49af-88ef-e7ee2243d0b7/http_propagation_extract/1.1.0rc2.dev37+g91fb4af9//results.json |
+======================================================+====================================================================================== …
```

perf: avoid exceptions in extract headers

---

ddtrace/contrib/sanic/patch.py
releasenotes/notes/fix-sanic-dont-send-error-traces-on-non-500s-b194927b887ad9d9.yaml
tests/contrib/sanic/test_sanic.py

Currently, only `NotFound` exceptions are excluded from sending the error traces. That causes 400 and others to show up on APM as an error making it harder to create SLOs and use other functionalities. This is more in line with how the Django integration also works.

fix(sanic): don't send error traces on non 500s errors

---

ddtrace/ext/ci.py
ddtrace/filters.py
tests/tracer/test_filters.py

Adds `library_version` to the root span which is missing in the CI Visibility intake track.

chore(ciapp): add library_version tag to the root test span

---

.circleci/config.yml
scripts/ddtest

Remove the unnecessary progress bars for docker pulls from output of jobs.

chore(ci): make docker pulls quiet

---

ddtrace/profiling/_asyncio.py
releasenotes/notes/profiling-asyncio-less-clear-threads-33d3436ab76ea158.yaml

The current code calls DdtraceProfilerEventLoopPolicy.clear_threads each time a
task is resolved, which can be up to 100 times a second. This is way too much
and we don't expect for the thread->loop mapping to change that often.
Instead we often try to clear the mapping when a new loop is attached to a
thread. In a regular application, this is the expected workflow: a thread
appears and gets a new loop, so we clear the old ones.
The worst case scenario would be an app spawning 100 threads with 100 loops and
then not doing that ever again, which would make the profiler keep a reference
on the 100 loops — until a new loop is attached, which if never, would kept the
reference forever.
Since this far from being a common pattern, it should be safe to switch to a
simpler model like this.

fix(profiling): do not clear thread-loop link too often

---

ddtrace/contrib/botocore/__init__.py
ddtrace/contrib/botocore/patch.py
releasenotes/notes/allow-disabling-s3-headobject-404-fd69f83dfd2eac4e.yaml
releasenotes/notes/botocore-error-statuses-fd69f83dfd2eac4e.yaml
tests/contrib/botocore/test.py

Adds a new `ddtrace.config.botocore["error_statuses"][<operation.name>].error_status = "500-599"` configuration option to allowing configuring the which HTTP response status codes will mark the span as an error.
The default is `500-599` for all operations.
Example setting `404` from `s3.headobject` as an error:
```python
config.botocore["error_statuses"]["s3.headobject"].error_statuses = "404,500-599"
```

feat(botocore): allow specifying which http status codes are errors

---

tox.ini

`aiobotocore==2.3.2` included `tests` module in it's distribution
this causes conflicts with our `tests` module.
Pin until https://github.com/aio-libs/aiobotocore/issues/937 is resolved

chore(ci): pin aiobotocore<=2.3.1 for gevent tox tests

---

ddtrace/internal/dogstatsd.py
ddtrace/internal/metrics.py
tests/internal/test_metrics.py

This change introduces a higher-level interface to DogStatsD that allows for the handling of metrics namespaces and run-time enablement control.

chore(internal): add higher-level metrics interface

---

riotfile.py

dulwich released a new version but did not publish wheels for the
version. Our build-docs job does not have the required dependencies
to build the package.
See: https://github.com/jelmer/dulwich/issues/963

fix(docs): pin dulwich version

---

riotfile.py

Undo pinning of dulwich.
0.20.37 now has been published with wheels.
Sorry about breaking this. We've committed some improvements to make it less
likely that this breaks in the future. See
https://github.com/jelmer/dulwich/issues/963 for details.

fix(docs): unpin dulwich version

---

tests/contrib/django/test_django_patch.py
tests/contrib/patch.py
tests/contrib/snowflake/test_snowflake_patch.py
tests/contrib/urllib3/test_urllib3_patch.py

Also remove the assertion that the module be not imported for a bunch of
the tests as almost all of our integrations import the patched module when
the patch method is imported.
Unfortunately it seems like the `self.skipTest()` call doesn't show up as a
skipped test since we just mark the test case as successful if the subprocess
returned an exit code of 0 so there isn't a good way to know if the test passed
or was skipped.

chore(tests): skip unpatch tests when no unpatch method given

---

.github/workflows/pr-name.yml

The main reason to use `wagoid/commitlint-github-action` for linting PR titles is that it outputs more detailed information in the log output than the current action `JulienKode/pull-request-name-linter-action`.

ci: use wagoid/commitlint-github-action

---

.github/workflows/pr-name.yml

Fixes the current PR title conventional commit linting.
This is closer to what we had in the past, but uses the GitHub Action `core.*` APIs to expose error messages in a nicer way.

chore(ci): update script for linting PR title

---

riotfile.py

dulwich released a new version but did not publish wheels for the
version. Our build-docs job does not have the required dependencies
to build the package.
See: https://github.com/jelmer/dulwich/issues/963, https://github.com/jelmer/dulwich/issues/968

fix(docs): pin dulwich version again

---

setup.py

Add a links to the sidebar on PyPI, to make it easier for folks to jump to the relevant pages. Example: https://pypi.org/project/django-htmx/ (PyPI adds the icons based on the link names).
You'll see this on the next release.
- N/A Added to the correct milestone.
- N/A Library documentation is updated.
- N/A [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

chore: add package links to pypi

---

ddtrace/profiling/profiler.py
releasenotes/notes/profiling-fix-profiler-copy-6d775a134ec2233f.yaml

The current code would miss copying some customer-provided attributes on fork.

fix(profiling): copy all profiler non-private attributes

---

releasenotes/notes/fix-profile-max-event-float-93288688036f669f.yaml

This fix was for something that was not yet released, so no note is necessary

chore(docs): remove unnecessary release note

---

.github/workflows/pr-name.yml

If the PR title contains a `'` then it'll mess up the script, this is because GitHub Actions does a template replacement on `${{ ... }}` before executing the script. Instead we should use `context.payload` which is the contents of the GitHub Event.

fix(ci): use context instead of replacement for PR title

---

riotfile.py

With the release of `mypy==0.960` mypy fails with the following error:
```
File "/home/circleci/project/.riot/venv_py3912_mypy_types-attrs_types-docutils_types-protobuf_types-PyYAML_types-setuptools_types-six_mock_pytest700_pytest-mock_coverage_pytest-cov_opentracing_hypothesis6451/bin/mypy", line 10, in <module>
sys.exit(console_entry())
File "/home/circleci/project/.riot/venv_py3912_mypy_types-attrs_types-docutils_types-protobuf_types-PyYAML_types-setuptools_types-six_mock_pytest700_pytest-mock_coverage_pytest-cov_opentracing_hypothesis6451/lib/python3.9/site-packages/mypy/__main__.py", line 12, in console_entry
main(None, sys.stdout, sys.stderr)
File "mypy/main.py", line 96, in main
File "mypy/main.py", line 173, in run_build
File "mypy/build.py", …
```

ci: pin mypy version to less than 0.960

---

.github/PULL_REQUEST_TEMPLATE.md

This change updates the ddtrace pull request template to include action items for reviewers. This is meant to streamline the review process and provide a set of acceptance criteria to contributors.

chore(docs): add reviewer checklist PR template

---

ddtrace/internal/safety.py
tests/internal/test_safety.py

The current safety implementation treated builtin collection types as safe, thus allowing iteration over their elements, which in general might not be safe. This change ensures that elements retrieved from collections are wrapped by a safe object proxy.

fix(internal): make collections safe

---

ddtrace/contrib/redis/asyncio_patch.py
ddtrace/contrib/redis/patch.py
releasenotes/notes/redis-asyncio-4b0b6a2a9d8f58c0.yaml
riotfile.py
tests/contrib/redis/test_redis_asyncio.py
tests/snapshots/tests.contrib.redis.test_redis_asyncio.test_parenting.json
tests/snapshots/tests.contrib.redis.test_redis_asyncio.test_pin.json
tests/snapshots/tests.contrib.redis.test_redis_asyncio.test_two_traced_pipelines.json

This PR adds support for asyncio part of redis >= 4.2
https://github.com/redis/redis-py#python-notice
https://redis-py.readthedocs.io/en/stable/connections.html#async-client
https://github.com/redis/redis-py/tree/master/redis/asyncio
- Integration docs: ???
- Corp docs PR: ???
writing `unittest` style test cases.

feat(redis): add asyncio support of redis >= 4.2

---

ddtrace/contrib/asgi/middleware.py
tests/contrib/asgi/test_asgi.py

This PR to change fastapi and starlette resource naming requires that we add each request span to the scope so that they can be accessed to assign the correct resource name: https://github.com/DataDog/dd-trace-py/pull/3612 
This PR covers the "add each request span to the scope" part.
Asgi applications can call back into themselves to process a "single incoming request", causing multiple request spans to be created. One example of this happening is when starlette or FastAPI applications use sub apps, each additional sub app causes the middleware to be hit again: https://fastapi.tiangolo.com/advanced/sub-applications/
There were already a lot of tests around the function `span_from_scope` to make sure that this change did not affect that behavior. In addition, I added another test where we …

chore(asgi): enable scope to hold multiple request spans if needed

---

scripts/ddtest

If the script is used on something else than CircleCI, then the test return
`false` and `set -e` makes the script exit with 1, therefore never running
docker-compose.
It would also passe "" as an argument to docker-compose making it fail.
The --quiet-pull does not exist (at least on Docker Desktop) so avoid using it
if not in CircleCI.

ci: fix ddtest on != CircleCI

---

tests/contrib/django/test_django_snapshots.py

The tag will break with every requests release:
```
meta mismatch on 'http.request.headers.user-agent': got 'python-requests/2.28.0' which does not match expected 'python-requests/2.27.1'.
```

fix(tests/django/appsec): ignore user agent header tag

---

setup.py

When using overlapping `python_version` constraints sometimes the wrong one is chosen and causes installation issues.
In our CI this resulted in:
```
raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (protobuf 3.19.4 (/root/project/.riot/venv_py3510/lib/python3.5/site-packages), Requirement.parse('protobuf<3.18,>=3'), {'ddtrace'})
```

fix: fix install requires python_version constraint for protobuf

---

ddtrace/contrib/redis/util.py

#3299 moved a utility function in the redis integration as part of a refactoring. This breaks the library's versioning policy for a minor release. We add back this function as an alias to the new function.

fix(redis): alias format_command_args

---

.github/workflows/stale.yml

At 00:00:00 UTC, label any issues and PRs which have had no activity
in the past 30 days with the `Stale` label.
We will not comment on the issues/PR, and we will not auto-close them.

chore: add stale bot to label inactive issues and PRs

---

ddtrace/contrib/starlette/patch.py
releasenotes/notes/add-back-starlette-fastapi-aggregate-resources-21855734c8b45d45.yaml
tests/contrib/fastapi/test_fastapi.py
tests/contrib/starlette/test_starlette.py
tests/snapshots/tests.contrib.fastapi.test_fastapi.test_subapp_no_aggregate_snapshot.json
tests/snapshots/tests.contrib.starlette.test_starlette.test_subapp_no_aggregate_snapshot.json

`aggregate_resources` was removed by https://github.com/DataDog/dd-trace-py/pull/3612 which breaks our public interface contract.
Added tests to Fastapi and Starlette as well as recorrected the test that was supposed to test this feature.

fix(starlette/fastapi): add back `aggregate_resources` feature

---

ddtrace/settings/config.py
releasenotes/notes/fix-trace-tag-config-e1bc9c83f066eb51.yaml
tests/tracer/test_settings.py

Fix a typo in the exception message when an invalid value is provided for `DD_TRACE_X_DATADOG_TAGS_MAX_LENGTH`.
The existing test case did not check the message. Once the test was updated, it fails with the following:
```
>               assert expected[1] in exc.value.args[0]
E               AssertionError: assert 'Invalid value 513' in 'Invalid value ddtrace.settings.integration.IntegrationConfig(analytics_enabled, analytics_sample_rate, service, service_name) provided for DD_TRACE_X_DATADOG_TAGS_MAX_LENGTH, only non-negative values less than
or equal to 512 allowed'
```
Test cases updated.

fix(internal): fix exception raised for invalid trace tag length

---

ddtrace/contrib/django/__init__.py
ddtrace/contrib/django/patch.py
releasenotes/notes/add-django-disable-templates-af5bdf524f27156f.yaml
tests/contrib/django/test_django.py
tests/contrib/django/test_django_snapshots.py
tests/snapshots/tests.contrib.django.test_django_snapshots.test_templates_disabled_30.json
tests/snapshots/tests.contrib.django.test_django_snapshots.test_templates_disabled_31.json
tests/snapshots/tests.contrib.django.test_django_snapshots.test_templates_disabled_3x.json
tests/snapshots/tests.contrib.django.test_django_snapshots.test_templates_enabled_30.json
tests/snapshots/tests.contrib.django.test_django_snapshots.test_templates_enabled_31.json
tests/snapshots/tests.contrib.django.test_django_snapshots.test_templates_enabled_3x.json

Introduction of a new configuration option for Django to allow turning off tracing for template rendering.
You can disable via `DD_DJANGO_INSTRUMENT_TEMPLATES=false`, or `ddtrace.config.django.instrument_templates = False`.
Fixes #3863
This change will check for the configuration at patching time and not patch `Template.render`, and it also checks for the option at runtime in the template render wrapper in case we end up patching before the user can disable the setting.
Automated tests have been added.
- Unit tests to ensure that setting the env variable properly configures the setting
- Unit tests to ensure that disabling the instrumentation at runtime will not produce spans
- Snapshot tests to verify the default and disabled behavior of template rendering
- For the enabled snapshots you …

feat(django): allow disabling template rendering tracing

---

.github/workflows/apm-transport-stress-test.yml

Add GitHub action to run the [APM transport stress tests](https://github.com/DataDog/apm-transport-stress-tests) once every hour.
We want to run these tests this often to ensure we are generating enough data
for reporting purposes.

chore(ci): add Datadog APM transport stress tests hourly job

---

ddtrace/contrib/asgi/middleware.py
releasenotes/notes/fix-asgi-middleware-url-tags-06051605794f88f7.yaml
tests/contrib/asgi/test_asgi.py
tests/contrib/fastapi/test_fastapi.py
tests/contrib/starlette/test_starlette.py
tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_200_traced_simple_app.json

In the asgi `TraceMiddleware`, `http.url` span tag should be set using the value of the `host` request header. 
If the `host` request header is not set, the host of the asgi server should be used. This fix will ensure forwarded requests are tagged with the original host name. 
Replace [the url parsing](https://github.com/DataDog/dd-trace-py/blob/v1.1.2/ddtrace/contrib/asgi/middleware.py#L131-L137) in ddtrace asgi middleware with the [starlette approach](https://github.com/encode/starlette/blob/e7a92ee4cd43b6d7acf4e2fdedb20fe0e86f9620/starlette/datastructures.py#L31-L47).

fix(asgi): set hostname using request headers

---

docker/Dockerfile.buster

The latest version of `mariadb` client library requires a newer version of the C library in order to build.
This PR updated our development docker image to install latest MariaDB C connector headers
#3883 is a follow-up PR to update the snapshot files / fix the MariaDB tests.

chore(ci): install official MariaDB C headers in dev image

---

ddtrace/contrib/aiomysql/patch.py
releasenotes/notes/fix-aiomysql-async-with-usage-ac6510f48ed0e6fe.yaml
tests/snapshots/tests.contrib.aiomysql.test_aiomysql.test_async_with_usage.json

The implementation of [Connection.cursor](https://github.com/aio-libs/aiomysql/blob/8a32f052a16dc3886af54b98f4d91d95862bfb8e/aiomysql/connection.py#L431-L461) is a sync function that returns a context manager around a coroutine. Our integration changed the `def cursor()` function into an `async def cursor():` function. This causes issues when using `async with conn.cursor():` as the result of our wrapped function would be a coroutine and not an async friendly context manager.
Fixes #3877 
Tests added for different async/await/async with usage for aiomysql. All of them share the same snapshot file since the resulting span should be the same no matter what.

fix(aiomysql): fix AttributeError: __aenter__ when using cursor as a context manager

---

ddtrace/contrib/flask_cache/tracers.py
ddtrace/contrib/flask_cache/utils.py
releasenotes/notes/flask_caching-dc23b94171041b4f.yaml
riotfile.py

flask-caching released version 2.0 which moves the cache client to a new library
called [`cachelib`](https://github.com/pallets-eco/cachelib).
Diff here: https://github.com/pallets-eco/flask-caching/compare/v1.10.0...v2.0.0
This breaks our logic which collects tags for the redis client.
It was noticed that both `_write_client` and `_read_client` use the same connection information
so we don't need to dynamically check for each.
Also [`_read_clients`](https://github.com/pallets-eco/flask-caching/blob/ac13e01baa11d65c68dcba64f99ccaafd9b5419c/src/flask_caching/backends/rediscache.py#L62) was moved to [`_read_client`](https://github.com/pallets-eco/cachelib/blob/13c8bf8db156dd06154f5e08e23bdd9e73480a5b/src/cachelib/redis.py#L29) when the logic was moved to `cachelib`.

fix(flask-caching): support v2.0

---

tests/contrib/sanic/test_sanic.py

This function was removed in sanic [v22.6.0](https://github.com/sanic-org/sanic/pull/2487).
We can just use ResponseStream directly.

fix(sanic/tests): replace usage of response.stream

---

docker-compose.yml

Allow docker-compose to work seamlessly on M1 Macs for containers where arm64 images don't exist.
Allow the same containers to be run on amd64 and arm64 platforms for testing purposes.
The alternative would be to find other images that have amd64 and arm64 support, but they would be different than current ones.

feat: :adhesive_bandage: run linux/amd64 containers on M1 Macs

---

docker-compose.yml

MariaDB `latest` only works on newer versions of Docker (see https://github.com/MariaDB/mariadb-docker/issues/434).
So we are pinning to `mariadb:10.7` for now to ensure consistent startup of the container in CircleCI.
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/18717/workflows/de909835-3fae-4a51-b620-5e94da79d81b/jobs/1267024

chore(ci): pin mariadb container to 10.7 image tag

---

ddtrace/contrib/pytest_bdd/plugin.py
releasenotes/notes/fix-pytest-bdd-6-88421928af50dc42.yaml
riotfile.py

This change fixes the support for the latest release of pytest-bdd v6. The issue was caused by some changes in the internal interface. With the right handling in place, the existing tests pass.
This issue was caught in CI
The existing tests are still good.

fix(pytest-bdd): support for version 6

---

ddtrace/internal/telemetry/writer.py
tests/tracer/telemetry/test_writer.py

Do not log warnings in telemetry, generate debug logs instead. Unblocks https://github.com/DataDog/dd-trace-py/pull/3925
Failing to send telemetry events should not log a warning in a customer's application.
Replace log.warning with log.debug
Ensure existing telemetry tests pass. Replace `log.warning` mocks with `log.debug`

chore(telemetry): replace warning logs with debug logs

---

riotfile.py

Cassandra tests hang and then timeout in python 3.10: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/18539/workflows/46570928-4859-4916-9645-00d0c108aa02/jobs/1254874.
Since cassandra-driver does not [officially support 3.10](https://github.com/datastax/python-driver/pull/1125) we should just avoid testing on these versions.

ci(cassandra): skip python 3.10 tests

---

.gitlab-ci.yml

Add trigger for running benchmark scenario. The execution of the job will be manual.
Run benchmarks in an environment where we can ensure reproducible results.
Downstream Gitlab trigger which runs perf scripts for executing benchmark scenarios.
Manual execution

ci: add benchmark trigger

---

ddtrace/contrib/wsgi/wsgi.py
releasenotes/notes/wsgi-move-request-modifer-code-809521ff9000ea64.yaml
tests/snapshots/tests.contrib.wsgi.test_wsgi.test_500_py2.json
tests/snapshots/tests.contrib.wsgi.test_wsgi.test_500_py3.json
tests/snapshots/tests.contrib.wsgi.test_wsgi.test_generator_exit_ignored_in_top_level_span_snapshot_py2.json
tests/snapshots/tests.contrib.wsgi.test_wsgi.test_generator_exit_ignored_in_top_level_span_snapshot_py3.json

Ensures resource and http tags are always set on `wsgi.request` spans.
The resource name and tags on a `wsgi.request` span is set [after the response is streamed](https://github.com/DataDog/dd-trace-py/blob/v1.2.2/ddtrace/contrib/wsgi/wsgi.py#L135-L144.). If an exception is raised [when the wsgi_app is called](https://github.com/DataDog/dd-trace-py/blob/v1.2.2/ddtrace/contrib/wsgi/wsgi.py#L133) or [during streaming the response](https://github.com/DataDog/dd-trace-py/blob/v1.2.2/ddtrace/contrib/wsgi/wsgi.py#L124) then the resource name and span tags will not be set.
Modify the request span before calling the wsgi app.
Ensure the http_method tag and resource name is set in all wsgi snapshot tests.

fix(wsgi): ensure correct resource and tags are set  on wsgi.request spans

---

ddtrace/debugging/_config.py
ddtrace/debugging/_probe/poller.py
tests/debugging/probe/test_poller.py

This change introduces the probe configuration poller that allows "listening" for probe events, e.g. new, deleted or modified probes. To avoid having to create a dedicated thread that would only increase contention on the GIL, probe status updates are also emitted by the poller.
NOTE: The interfacing with the RCM in this implementation is not super sleek, but it will be changed soon.

chore(debugging): add probe configuration poller

---

ddtrace/profiling/scheduler.py

There is no (end) user impact when profiles are not sent. We got a bunch of errors in our logs last night when `intake.profile.datadoghq.com` was down for approx 45 minutes. I understand it is disputable if it has "user" impact but it looks like java profiler does not log error either.

chore(profiling): lower loglevel for failed profile upload from error -> warning

---

ddtrace/contrib/flask/patch.py
releasenotes/notes/detect-attacks-on-path-params-d6d06c22573d22e8.yaml
tests/appsec/rules-good.json
tests/contrib/django/django1_app/urls.py
tests/contrib/django/django_app/urls.py
tests/contrib/django/test_django_appsec.py
tests/contrib/django/views.py
tests/contrib/flask/test_flask_appsec.py

Detect attacks on path params
Expand Appsec features
Check:
* `tests/contrib/django/test_django_appsec.py`
* `tests/contrib/flask/test_flask_appsec.py`
Run a Flask/Django application with dd-trace-py configured and appsec enabled. This app should hava a endpoint like:
```
@self.app.route("/path/<item>")
def dynamic_url(item):
return item
```
Then, execute a curl command such as:
```
curl -v http://192.168.1.35:8081/path/w00tw00t.at.isc.sans.dfind
```
ddwaf should return:
```
`DEBUG:ddtrace.appsec.processor:[DDAS-011-00] AppSec In-App WAF returned: [{"rule":{"id":"crs-913-120","name":"Known security scanner filename/argument", ... ]}]`
```

feat(asm): detect attacks on path Params

---

ddtrace/profiling/_asyncio.py
ddtrace/profiling/profiler.py
releasenotes/notes/profiler-asyncio-py2-5049a2c3fd02c842.yaml
tests/profiling/test_profiler.py

When used in Python 2, the profiler emits these error logs
```
File "/usr/local/lib/python2.7/site-packages/ddtrace/profiling/profiler.py", line 242, in _start_service
col.start()
File "/usr/local/lib/python2.7/site-packages/ddtrace/internal/service.py", line 58, in start
self._start_service(*args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/ddtrace/profiling/collector/asyncio.py", line 40, in _start_service
return super(AsyncioLockCollector, self)._start_service()
File "/usr/local/lib/python2.7/site-packages/ddtrace/profiling/collector/_lock.py", line 209, in _start_service
self.patch()
File "/usr/local/lib/python2.7/site-packages/ddtrace/profiling/collector/_lock.py", line 223, in patch
self.original = self._get_original()
File …
```

fix(profiling): don't use AsyncioLockCollector unless asyncio available

---

pyproject.toml

Exclude contrib tests directories from `slotcheck` validation as we exclude `ddtrace.contrib` directories
Avoid errors witch not exists in CI
Without these changes, If you run slotchecks you should got an error like:
```
riot run slotscheck -v 'ddtrace/appsec/processor.py' 'ddtrace/contrib/flask/patch.py' 'ddtrace/contrib/trace_utils.py' 'tests/appsec/test_processor.py' 'tests/contrib/django/test_django_appsec.py' 'tests/contrib/flask/test_flask_appsec.py'
tests/contrib/flask/test_flask_appsec.py'
ERROR: Couldn't inspect module 'tests.contrib.flask.test_flask_appsec' due to ImportError("Error while finding loader for 'tests.contrib.flask.test_flask_appsec' (<class 'ModuleNotFoundError'>: No module named 'flask')"). Run `import tests.contrib.flask.test_flask_appsec` to reproduce this …
```

chore(slotcheck): exclude contrib tests directories

---

ddtrace/internal/periodic.py

Trying to awake the awakeable thread on stop might cause deadlocks during shutdowns. The call to on_shutdown should be enough to handle stop events on this kind of services.

chore(internal): prevent deadlock in awakeable services

---

ddtrace/internal/sampling.py
tests/tracer/test_single_span_sampling_rule.py

Refactoring out match from the sample function for easier and more understandable use in the span processor introduced here: https://github.com/DataDog/dd-trace-py/pull/3966

chore(internal): remove match fn from sample for single span sampling

---

ddtrace/debugging/_encoding.py
tests/debugging/test_encoding.py

The debugger encoding tests displayed a certain degree of flakiness. This was due to the same snapshot getting encoded with just a 1-byte length difference (quite likely due to different encoding timings). This change makes the item encoder report the size of the encoded item alone which allows for simpler and more reliable testing logic.

chore(debugging): remove encoding test flakiness

---

.circleci/config.yml
ddtrace/profiling/collector/stack.pyx
releasenotes/notes/profiler-windows-support-6faa2ecfdf4b97e8.yaml
tests/profiling/_test_multiprocessing.py
tests/profiling/collector/test_asyncio.py
tests/profiling/collector/test_stack_asyncio.py
tests/profiling/collector/test_threading.py
tests/profiling/exporter/test_http.py
tests/profiling/simple_program.py
tests/profiling/test_main.py
tests/profiling/test_recorder.py
tests/profiling/test_uwsgi.py
tests/utils.py
tox.ini

This runs the profiler tests on Windows and make sure the profiler works.
This fixes one major issue with the stack profiler which was not using the
right type for storing the process time and made the profiler crash.

ci(profiling): run tests on Windows and fix support

---

ddtrace/internal/telemetry/writer.py
tests/tracer/telemetry/test_telemetry.py

The telemetry writer is still running after a fork. Calling `writer.start()` on a live periodic service logs the following error: 
```
Exception ignored in forksafe hook <bound method TelemetryWriter._fork_writer of TelemetryWriter(status=<ServiceStatus.RUNNING: 'running'>, _interval=60.0)>
File "/Users/munir.abdinur/Documents/ApmPython/dd-trace-py/ddtrace/internal/forksafe.py", line 33, in ddtrace_after_in_child
hook()
File "/Users/munir.abdinur/Documents/ApmPython/dd-trace-py/ddtrace/internal/telemetry/writer.py", line 244, in _fork_writer
self.start()
File "/Users/munir.abdinur/Documents/ApmPython/dd-trace-py/ddtrace/internal/service.py", line 57, in start
raise ServiceStatusError(self.__class__, self.status) …
```

chore(telemetry): avoid starting the telemetry after a process forks

---

riotfile.py

CI is failing on the 1.3 branch after the release of mypy 0.971. This is not an issue on 1.x because of #3919, which is not released in v1.3.0. For now we can pin mypy, backport it, then safely unpin on 1.x.

fix(ci): pin mypy for v1.3.0 release

---

ddtrace/settings/http.py
tests/contrib/wsgi/test_wsgi.py
tests/snapshots/tests.contrib.wsgi.test_wsgi.test_200.json

The tests we had do did not reset the activation of traced headers so the configuration was leaking over to other tests.

fix(ci): fix WSGI tests that did not reset traced headers

---

ddtrace/contrib/jinja2/patch.py
releasenotes/notes/fix-jinja2-non-str-template-name-4cb2aa7cda15828a.yaml
tests/contrib/jinja2/test_jinja2.py

We assume that `Template.name` is going to be a string, but
this is not enforced by Jinja2 so we must be prepared for when
it isn't.
This is not an issue for setting the template name as a tag
since `Span.set_tag` will coerce the value, but it causes
an issue for `Span.resource` for the `jinja2.render` span.
Fixes #4008
Added a new test case for our Jinja2 integration to verify when custom template names are used of various types (str, unicode, int) that we properly coerce them into a string.

fix(tracing/jinja2): ensure template name is a string

---

tests/contrib/grpc_aio/test_grpc_aio.py

New version 1.48.0 of grpc has updated error message: https://github.com/grpc/grpc/releases/tag/v1.48.0
```
>       assert client_span.get_tag(ERROR_MSG) == "failed to connect to all addresses"
E       AssertionError: assert 'failed to co...ction refused' == 'failed to co...all addresses'
E         - failed to connect to all addresses
E         + failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused
```

fix(grpc_aio): new version 1.48.0 has updated error message

---

tox.ini

Fixed gevent error in tox tests:
```
Collecting gevent<20.10,>=20.9
Using cached gevent-20.9.0.tar.gz (5.8 MB)
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'error'
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [60 lines of output]
warning: src/gevent/resolver/cares.pyx:38:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
warning: src/gevent/resolver/cares.pyx:40:0: The 'DEF' statement is deprecated and will …
```

fix(tests/tox): updated gevent in tox config

---

setup.py

Previously we only installed typing_extensions on Python 3.8. This causes tests to fail for other Python versions when typing_extensions is not installed. This is to use `NotRequired` in https://github.com/DataDog/dd-trace-py/pull/3977

chore(tests): remove typing_extensions version specification

---

tests/debugging/probe/test_poller.py

For unknown reasons, the poller event test occasionally fails on Python 2 because a modified probe is handled as a pair of "deleted" and "new" events. Therefore, we mark the test with xfail on Python 2 for now.

test(debugging): mark flaky poller test on Python 2

---

ddtrace/contrib/graphql/patch.py
tests/snapshots/tests.contrib.graphql.test_graphql.test_graphql.json
tests/snapshots/tests.contrib.graphql.test_graphql.test_graphql_error.json
tests/snapshots/tests.contrib.graphql.test_graphql.test_graphql_v2_with_document.json
tests/snapshots/tests.contrib.graphql.test_graphql.test_graphql_with_traced_resolver.json

The graphql top level span is currently named `graphql.query`. This span wraps the execution of the `graphql.graphql()`. The current span name can be misleading since `graphql.graphql()` can execute graphql queries, graphql mutations or graphql subscriptions. This fix proposes setting the span name to `graphql.request` instead. 
An alternative fix would be to set the span name to  `graphql.query`, `graphql.mutation` or `graphql.subscription` depending on the operation name. However getting the operation name would require parsing the query and this can be expensive.

fix(graphql): rename service entry span

---

pyproject.toml

The latest release of setuptools has broken support for editable installs, which is what riot does. See 
https://github.com/pypa/setuptools/issues/3504 for more details.

ci: pin setuptools

---

ddtrace/internal/nogevent.py
ddtrace/profiling/_threading.pyx
releasenotes/notes/profiling-threadlink-lock-27df798c36ed64e6.yaml

It is possible that while the profiling StackCollector is handling the
on_span_activate event that a gc occurs which could result in a weakref
finalize callback being called which then could activate a new span.
This sequence of events results in a deadlock as the lock the
StackCollector uses is not reentrant.
A regression test would be great but we cannot think of a tractable test
case which wouldn't be flaky.
Here's an example stacktrace of this happening:
```
[18:50:46 UTC]   [pytest:unit]                     	File "/opt/dogweb/lib/python2.7/site-packages/ddtrace/contrib/dbapi/__init__.py", line 91, in _trace_method
[18:50:46 UTC]   [pytest:unit]                     		s.set_tag(sql.ROWS, row_count)
[18:50:46 UTC]   [pytest:unit]                     	File …
```

fix(profiling): fix potential StackCollector deadlock 

---

ddtrace/sampler.py

The `_default_sampler` slot of `DatadogSampler` is already declared in the superclass `RateByServiceSampler`.

chore(tracer): remove redundant slot in DatadogSampler

---

ddtrace/profiling/collector/_memalloc_tb.c

On Python 3.9 and later, PyFrame_GetCode returns a new reference that should be
decremented after the function finishes.
The current code calls Py_DECREF without checking that code is not NULL, while
there is a check doing that for safety. The DECREF is also done a little too
soon (in theory, in practice it does not have a real impact).
This switches to XDECREF to make sure that `code` is not NULL and does this at
the end of the function to be sure we have inc-referenced code items that we
cared about.

fix(profiling): fix potential crash in frame converter

---

.github/workflows/build_deploy.yml

On v1.4.0 release, the build failed with:
```
[Build and test wheels on ubuntu-18.04 (aarch64)](https://github.com/DataDog/dd-trace-py/runs/7951686050?check_suite_focus=true)
This is a scheduled Ubuntu-18.04 brownout. The Ubuntu-18.04 environment is deprecated and will be removed on December 1st, 2022. For more details, see https://github.com/actions/runner-images/issues/6002
```
Failing build: https://github.com/DataDog/dd-trace-py/actions/runs/2903881861
https://github.com/actions/runner-images/issues/6002

ci: update github action runner image to ubuntu-latest

---

benchmarks/bm/utils.py
benchmarks/flask_simple/app.py
benchmarks/flask_simple/config.yaml
benchmarks/flask_simple/gunicorn.conf.py
benchmarks/flask_simple/scenario.py
benchmarks/flask_simple/utils.py
benchmarks/set_http_meta/scenario.py
ddtrace/contrib/flask/patch.py
releasenotes/notes/asm-fix-reset-wsgi-input-035e0a7d917af2b2.yaml
tests/contrib/django/django1_app/urls.py
tests/contrib/django/django_app/urls.py
tests/contrib/django/test_django_appsec.py
tests/contrib/django/views.py
tests/contrib/flask/app.py
tests/contrib/flask/test_flask_appsec.py
tests/contrib/pylons/app/controllers/root.py
tests/contrib/pylons/app/router.py
tests/contrib/pylons/test_pylons.py

Fixes an issue with Flask as we read the body request and it is consumed (so Flask cannot parse it afterwards).
Not reported
Unit tests for Django, Flask and Pylons.

fix(asm): fix reading wsgi input

---

ddtrace/internal/nogevent.py
docs/spelling_wordlist.txt
releasenotes/notes/nogevent-rlock-original-9e387eafb2be3d27.yaml
tests/profiling/test_nogevent.py

#4108 replaced an internal use of the original `threading.Lock` function rather than the `gevent.threading.Lock` with the original `threading.RLock` function. However, at least in Python 2, there is an indirection with the implementation of `threading._RLock` class where it the `threading._allocate_lock` called is in fact `gevent.threading._allocate_lock`. 
When the gevent patched lock is used instead, we can encounter deadlocks or even gevent exceptions like the following:
```
ddtrace.profiling.collector.stack._ThreadSpanLinks.get_active_span_from_thread_id
File "ddtrace/profiling/_threading.pyx", line 112, in ddtrace.profiling._threading._ThreadLink.get_object
File "/usr/local/lib/python2.7/threading.py", line 174, in acquire
rc = self.__block.acquire(blocking)
File …
```

fix(profiling): ensure RLock uses original allocate_lock

---

ddtrace/internal/logger.py
tests/tracer/test_logger.py

Before we wouldn't replace a PlaceHolder added by _fixUpParents which would be incorrect since we'd want to get rid of the PlaceHolder and replace it with our DDLogger.
From Gab: 
This was causing issues with some tests that I was running as part of a change I’m working on. With that line the problem goes away.

fix(logging): account for placeholder in get_logger

---

ddtrace/debugging/_debugger.py
ddtrace/internal/injection.py
tests/debugging/test_debugger.py

Since identity comparison between bound methods does not work as expected, probe ejection with a bound method hook always fails. This change replaces the identity comparison with equality to fix the issue.
The problem was not caught in tests because of the default rate limiting on probes and a lax testing logic. The relevant test cases have been enhanced to be stricter and increase the rate on probes to avoid hitting the rate limit.

chore(debugging): fix ejection

---

ddtrace/debugging/_function/discovery.py

If the module discovery finds a function-like object with no `__code__` attribute, we ignore it instead of letting an AttributeError to be thrown. Cases where the problem could have happened are those where the function-like objects are builtin or native functions, which are implemented in native libraries and don't have a code object.

chore(debugging): ignore functions with no __code__

---

ddtrace/appsec/CMakeLists.txt
ddtrace/appsec/_ddwaf.pyx
ddtrace/appsec/_libddwaf.pxd
ddtrace/appsec/processor.py
docs/configuration.rst
docs/spelling_wordlist.txt
releasenotes/notes/asm-configure-sensitive-data-obfuscator-4bf70dcccb9f6350.yaml
tests/appsec/test_processor.py

Enable libddwaf data obfuscator by setting the config properly.
The configuration consists in two regexp that can be overriden by env vars.
ASM feature of sensitive data obfuscation
Unit tests and system tests

feat(asm): configure ddwaf data obfuscator

---

ddtrace/profiling/_threading.pyx

The _ThreadLink data structure historically used a lock to make sure there was
no threads overlapping each other. For example, this could happen:
1. Main thread from the application starts a trace and `link_object` is being
called
2. Stack profiler would run and clear the thread list or get an spans from the
list
Removing the lock makes it possible that, while the stack profiler thread
clears the mapping, a user's thread links a thread to a span.
That's a trade-off we are willing to accept for performance and safeness
reason.

refactor(profiling): remove lock from _ThreadLink

---

.github/workflows/system-tests.yml

We opted to not use the same build/run scripts as normal system tests, so create a new job to run the library injection tests.

chore(lib-injection): update system-tests

---

releasenotes/notes/profiler-threadlink-nolock-200ffbc2d0400d2d.yaml

Add release note for change made in #4147 as it fixes a known issue with gevent deadlocks in the profiler under certain conditions.

docs(profiler): add release note for profiler lock removal

---

benchmarks/bm/utils.py
benchmarks/set_http_meta/config.yaml
benchmarks/set_http_meta/scenario.py
ddtrace/constants.py
ddtrace/contrib/django/utils.py
ddtrace/contrib/flask/patch.py
ddtrace/contrib/pylons/middleware.py
ddtrace/contrib/trace_utils.py
ddtrace/ext/http.py
docs/spelling_wordlist.txt
hooks/scripts/run-slotscheck.sh
releasenotes/notes/asm-collect-header-ip-494f489b1778b6ed.yaml
setup.py
tests/appsec/test_processor.py
tests/contrib/django/test_django_appsec.py
tests/contrib/flask/test_flask_appsec.py
tests/tracer/test_trace_utils.py

```
+-----------------------------------------------------+------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------+
| Benchmark                                           | /artifacts/3240773f-677b-42b7-a71b-9989289b2247/set_http_meta/1.4.0rc2.dev70+ged05a17f//results.json | /artifacts/3240773f-677b-42b7-a71b-9989289b2247/set_http_meta/1.4.0rc2.dev84+g3730ae83//results.json |
+=====================================================+======================================================================================================+======================================================================================================+
| …
```

feat(asm): collect http.client_ip

---

ddtrace/internal/utils/http.py
ddtrace/settings/config.py
ddtrace/settings/integration.py

Cache get header tag name.
Benchmark:
```
+-----------------------------------------------------+---------+-----------------------+
| Benchmark                                           | /1.x    | /artifacts/eb22eac5-98|
+=====================================================+=========+=======================+
| sethttpmeta-no-useragentvariant                     | 29.0 us | 22.6 us: 1.29x faster |
+-----------------------------------------------------+---------+-----------------------+
| sethttpmeta-all-disabled                            | 9.20 us | 7.98 us: 1.15x faster |
+-----------------------------------------------------+---------+-----------------------+
| sethttpmeta-useragentvariant_exists_1               | 23.3 us | 24.1 us: 1.03x slower | …
```

chore(refactor): memoize get header tag name

---

.github/workflows/lib-injection.yml
.gitlab-ci.yml

Deploy the images to the official registries that will be used by the cluster agent. We only do this when a new tag is pushed (matching `v.*`) in which we publish the corresponding version tag for the image and also the `latest` tag.
https://github.com/DataDog/datadog-agent/blob/024346a5c57fa91501b8df25a84601d01b78131e/pkg/clusteragent/admission/mutate/auto_instrumentation.go#L85-L101

feat(lib-injection): add image deploy jobs

---

.mergify.yml

Mergifyio applies the "conflicts" label whereas we apply the "conflict" label.
Example: https://github.com/DataDog/dd-trace-py/pull/4138

chore(mergifyio): use consistent conflict label

---

tests/debugging/exploration/debugger.py
tests/debugging/exploration/test_bootstrap.py

With the recent refactor that enabled RCM for the debugger, the content of the old probe poller module has been moved in the probe remoteconfig one. This change fixes an import that was still referecing the removed module and prevented the exploration debuggers from running.
A test has also been added to catch potential issues with the exploration debuggers in the future.

chore(debugging): fix exploration debugger import

---

tests/contrib/botocore/test.py

With the latest [moto release](https://github.com/spulec/moto/issues/5249), adding a record which exceeds the max size constraint is not supported. Since this test validates unsupported behavior it was removed.
New [Boto Validation Error](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/21184/workflows/33375cfd-6f3f-446e-aae7-2e800994e9df/jobs/1440546):
```
def test_kinesis_put_records_base64_exceeds_max_size(self):
client = self.session.create_client("kinesis", region_name="us-east-1")
stream_name = "test"
client.create_stream(StreamName=stream_name, ShardCount=1)
stream = client.describe_stream(StreamName=stream_name)["StreamDescription"]
shard_id = stream["Shards"][0]["ShardId"]
partition_key = "1234"
sample_string = json.dumps({"Hello": "x" * (1 << 20)}) …
```

ci(boto): remove test_kinesis_put_records_base64_exceeds_max_size

---

ddtrace/contrib/aioredis/patch.py
releasenotes/notes/fix-aioredis-catch-cancellederror-223e8bb3d1aea94f.yaml

This fixes the aioredis integration from raising `CancelledError`. As of Python 3.8 ([Docs link](https://docs.python.org/3/library/asyncio-exceptions.html#asyncio.CancelledError)), `CancelledError` now extends from `BaseException` and not `Exception`, and is currently being raised by the aioredis integration instead of being handled. The aioredis integration now catches all errors extending from `BaseException` in aioredis futures (i.e. the `_finish_span()` callback added to each future).
This should resolve #3253.

fix(aioredis): handle all BaseException, not Exception in _finish_span

---

ddtrace/ext/ci.py
releasenotes/notes/fix-appveyor-commit-message-752b38ce564f5be6.yaml
tests/tracer/fixtures/ci/appveyor.json
tests/tracer/test_ci.py

Fixes getting the full commit message when running on the AppVeyor CI.
Previously we were only checking `APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED` which, [as per the docs](https://www.appveyor.com/docs/environment-variables/) only contains the "rest" of the commit message. The first line of the commit message is in `APPVEYOR_REPO_COMMIT_MESSAGE`.
N/A
Updated appveyor fixture.

fix(ci): correctly extract commit message from AppVeyor

---

ddtrace/contrib/dbapi/__init__.py
docs/spelling_wordlist.txt
releasenotes/notes/fix-dbapi-cursor-iter-3e8eb0fbed08e47f.yaml
tests/contrib/sqlite3/test_sqlite3.py

According to the [dbapi spec](https://peps.python.org/pep-0249/#iter)
cursors can be iterable. For some reason wrapt.ObjectProxy does not
proxy the `__iter__` or `__next__` methods. The solution is to simply
add them to the base TraceCursor class which is used in our dbapi
integrations.
Fixes #4143

fix(dbapi): add iterable methods to object proxy

---

ddtrace/internal/utils/formats.py
releasenotes/notes/fix-dd-tags-0763e940d889b8da.yaml
tests/tracer/test_utils.py

This change allows for URLs to be passed as values to tag labels via the ``DD_TAGS`` environment variable.
**NOTE** This might constitute a slight breaking change, as configuration that was valid before might no longer work with the new logic.
The test suite included a test case that covered the URL case (a tag with a value containing the `:` character).

fix(internal): support URLs in DD_TAGS variable

---

ddtrace/contrib/django/__init__.py

In-code configuration for Django only works prior to Django patching occurring for many of the options which leads to confusion like what was
reported here: https://github.com/DataDog/dd-trace-py/issues/3816.
Resolves #3816

chore(docs): clarify django in-code docs

---

docs/spelling_wordlist.txt
releasenotes/notes/asm-fix-ipaddress-backport-lib-4684ce71e63459e7.yaml
setup.py
tests/tracer/test_trace_utils.py

Fix a failing test in mcnulty by switching to the same backport ipaddress library they're using. 
Also adds a new test to avoid future regressions on the same failure point as their test.

fix(asm): change ipaddress backport library

---

ddtrace/opentracer/propagation/http.py
releasenotes/notes/fix-ot-extract-5faf0276c75d033f.yaml
tests/opentracer/core/test_tracer.py

Extract should not raise an exception if there are no distributed tracing headers present. There is no way to distinguish in the ddtrace api between a failed parse and a successful one (errors are just logged and an empty context returned).
https://opentracing-python.readthedocs.io/en/1.3.0/api.html#opentracing.InvalidCarrierException
(finally) Fixes #2030

fix(opentracing): don't raise on no trace context

---

riotfile.py

Pin sanic and sanic-testing versions to fix tests in CI
The tests for sanic integration are failing for the following new versions: sanic==[22.9.0](https://github.com/sanic-org/sanic/releases/tag/v22.9.0)  and sanic-testing==[22.9.0](https://github.com/sanic-org/sanic-testing/releases/tag/v22.9.0), with the following error:
```
self = <tests.contrib.sanic.test_sanic.client.<locals>.TestClient object at 0x7f4e4c78b0a0>
method = 'GET', url = '/hello', gather_request = True, args = ()
kwargs = {'auth': <httpx._client.UseClientDefault object at 0x7f4e4cfdd550>, 'cookies': None, 'extensions': None, 'follow_redirects': <httpx._client.UseClientDefault object at 0x7f4e4cfdd550>, ...}
route = <Route: name=sanic.hello path=hello>
async def request(  # type: ignore
self, method, url, …
```

chore(ci): pin sanic and sanic-testing version

---

ddtrace/internal/forksafe.py
tests/internal/test_forksafe.py

Re-initialize the gevent hub after-in-child fork hooks when `DD_TRACE_GEVENT_HUB_PATCHED` is set to true. This mitigates a performance regression introduced by: https://github.com/DataDog/dd-trace-py/pull/4070. 
Note: This PR simply mitigates the performance regression introduced by #4070. Reinitializing gevent patching when a process forks is required to use remote config, the profiler and debugger. This issue will be fixed in a follow up change.

chore(gevent): disable gevent hub reinit

---

riotfile.py

The codespell job is failing with the following errors:
```
ddtrace/appsec/include/ddwaf.h:194: emmitted ==> emitted
ddtrace/appsec/include/ddwaf.h:195: emmitted ==> emitted
ddtrace/appsec/include/ddwaf.h:461: calcualted ==> calculated
```
We can safely ignore the `ddwaf.h` included from this appsec dependency when checking spelling in code.

ci(codespell): ignore ddwaf header

---

.circleci/config.yml
riotfile.py
setup.py
tox.ini

CI jobs `profile-windows-*`, `kombu` and `celery` are failing due to the release of `importlib_metadata==5.0.0` which removed deprecated shims, resulting in the following exception:
```
AttributeError: 'EntryPoints' object has no attribute 'get'
```
We fix this by pinning the dependency for kombu and celery. In the case of the Windows tests, we address it by upgrading the Windows image to a version that includes Python 3.10 rather than Python 3.7 which removes the need to install the dependency when installing tox.
- [Example log of failing job](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/21679/workflows/2a7606b5-9ca8-4212-9b02-053665de0198/jobs/1477147)
- https://github.com/python/importlib_metadata/issues/409

fix(ci): pin importlib_metadata<5.0.0

---

tests/debugging/exploration/_config.py
tests/debugging/exploration/_coverage.py
tests/debugging/exploration/_profiler.py
tests/debugging/exploration/debugger.py

This change adds the option to specify a list of module paths to include during exploration test runs. By default, the exploration debuggers will instrument the modules of a package installed in editable mode, if any.
This change also adds checks to collect any modules that might have eluded the import machinery.

test(debugging): include-list and collect elusive modules in exploration tests

---

ddtrace/appsec/processor.py
ddtrace/context.py
ddtrace/contrib/asgi/middleware.py
ddtrace/contrib/asyncpg/patch.py
ddtrace/contrib/botocore/patch.py
ddtrace/contrib/flask_cache/tracers.py
ddtrace/contrib/graphql/patch.py
ddtrace/contrib/httpx/patch.py
ddtrace/contrib/trace_utils.py
ddtrace/contrib/wsgi/wsgi.py
ddtrace/debugging/_debugger.py
ddtrace/debugging/_encoding.py
ddtrace/ext/aws.py
ddtrace/filters.py
ddtrace/internal/_context.py
ddtrace/internal/debug.py
ddtrace/internal/encoding.py
ddtrace/internal/processor/stats.py
ddtrace/internal/remoteconfig/client.py
ddtrace/internal/runtime/runtime_metrics.py
ddtrace/internal/sampling.py
ddtrace/internal/writer.py
ddtrace/opentracer/helpers.py
ddtrace/opentracer/span.py
ddtrace/pin.py
ddtrace/profiling/exporter/__init__.py
ddtrace/sampler.py
tests/contrib/sqlite3/test_sqlite3.py
tests/tracer/test_memory_leak.py

Exclude TYPE_CHECKING from coverage.
`if TYPE_CHECKING:` block works only with `mypy`. Coverage reports never enter in these blocks and if we exclude these, we could have more accurate coverage reports.

chore(coverage): exclude TYPE_CHECKING from coverage

---

setup.py

The `ipaddress` module is part of Python since 3.3, so the requirement is only needed for Python < 3.3. However some functions like subnet_of are available in Python 3.7 and newer only.

fix(deps): only require ipaddress on python<3.7

---

ddtrace/internal/compat.py
ddtrace/internal/utils/cache.py

#4302 added a `callonce()` decorator as a cache utility function. However, this imported `inspect.getargspec()` was removed as of Python 3.11. This was fixed by importing `inspect.getfullargspec()`, which is the recommended replacement for `getargspec()`. Note that `getargspec()` is still used in Python 2.

chore(utils): make cache utils `callonce()` compatible with py 3.11

---

.github/ISSUE_TEMPLATE.md

I have found myself scrolling to the bottom of an issue to get a summary. Similarly, the output of pip freeze should be hidden by default.

chore: make issue template easier to triage

---

.github/PULL_REQUEST_TEMPLATE.md

Help make our PR template a little bit less work to fill out

chore(docs): remove unnecessary checklist items

---

riotfile.py
tox.ini

`pytest` recently vendored specific portions of the `py` library and removed it as a requirement. This broke our `benchmarks` and `profile` test suites in CI as they use the `py.io` module. Specifically, `pytest-benchmark` is the dependency that uses `py.io` and have addressed the issue (https://github.com/ionelmc/pytest-benchmark/issues/226) but haven't yet released a new hotfix. Until they do, we can just add `py` as a dependency in our riot test suites.

fix(ci): add py as a dependency

---

tests/contrib/httpx/test_httpx.py
tests/utils.py

Add a `wait_for_traces` argument to snapshots to poll the test agent until the correct number of traces are available. In particular `httpx` has been flaky:

fix(ci): wait for traces to be sent in snapshot tests

---

ddtrace/appsec/utils.py
tests/appsec/test_remoteconfiguration.py

As spoken on the Python Guild meeting, we'll not enable RCM by default until the gevent issue is fixed and will consider it a beta for 1.6.0. The update to the changelog will be done in the changelog review PR.

chore(asm): set the DD_REMOTE_CONFIGURATION_ENABLED to false default for the beta of RCM

---

.github/workflows/test_frameworks.yml

Pin SQLAlchemy to 1.4.41.
Issue: https://github.com/encode/databases/issues/512
Failing Fastapi Test: https://github.com/DataDog/dd-trace-py/actions/runs/3339686051/jobs/5528937301
Failing Starlette Test: https://github.com/DataDog/dd-trace-py/actions/runs/3340052660/jobs/5529727716
An alternative to pinning sqlachemy is to skip the failing test.
- [ n/a ] Add additional sections for `feat` and `fix` pull requests.

ci(starlette/fastapi): pin SQLAlchemy to fix framework tests

---

releasenotes/notes/asm-1-click-activation-with-RCM-6a2431949768b73b.yaml

This should clarify for library users the new functionality and its support level.
https://www.datadoghq.com/blog/dash-2022-new-feature-roundup/#application-security-management-protection
> We’re excited to announce that we’ve expanded Datadog ASM to include native protection capabilities. You can now prevent attacks by blocking malicious IPs directly from Datadog and in one click. 
**Current**
**Preview**

fix(releasenotes): add prelude for ASM one click feature

---

ddtrace/internal/runtime/container.py
releasenotes/notes/PCF-container-UUID-0f65eed47e42f4ad.yaml
tests/tracer/runtime/test_container.py

Updates the container ID regex to support PCF container UUIDs
PCF container IDs are in a different format than the current assumption so the container IDs are currently not being recognized in PCF environments
N/A
Note: this fix will be implemented on the other tracing libraries as well
- ~Write tests with real PCF containers~
- Test on PCF test env

fix(runtime): add support for PCF containers

---

tests/contrib/mariadb/test_mariadb.py
tests/snapshots/tests.contrib.mariadb.test_mariadb.test_user_specified_dd_mariadb_service_snapshot_post_1_1.json
tests/snapshots/tests.contrib.mariadb.test_mariadb.test_user_specified_dd_mariadb_service_snapshot_pre_1_1.json
tests/snapshots/tests.contrib.mariadb.test_mariadb.test_user_specified_dd_service_snapshot_post_1_1.json
tests/snapshots/tests.contrib.mariadb.test_mariadb.test_user_specified_dd_service_snapshot_pre_1_1.json

Snapshots are not generated when a test is annotated with `@tests.utils.snapshot()` and `@pytest.mark.subprocess()`. This change updates mariadb tests to use the `@pytest.mark.snapshot()`. 
0.61 uses `run_python_code_in_subprocess fixture` to run mariadb snapshot tests so it does not experience this issue: https://github.com/DataDog/dd-trace-py/blob/0.61/tests/contrib/mariadb/test_mariadb.py#L157. We do not need to backport this change to 0.61.

ci(mariadb): add missing snapshot tests

---

docs/conf.py
docs/configuration.rst

This change introduces a helper directive `.. ddtrace-configuration-options::` that will provide a consistent formatting from a list of configuration options. The reason we went with custom directive approach is the formatting of the configuration options can be changed at any time without needing to reformat each option individually.
The large table didn't handle large descriptions or default values very well. Especially if the values were code blocks since they do not overflow.
The input to the directive is a YAML format of:
```yaml
OPTION_NAME:
type: <type>
default: <default>
description: <description>
version_added:
vX.Y.Z:
```
If `type`is not provided then `String` is used.
If `default` is not provided then `(no value)` is used.
`description` **must** be provided.
`version_added` is …

chore(docs): reformat configuration page

---

ddtrace/context.py
releasenotes/notes/fix-context-serializable-2c9768cbe4738b73.yaml
tests/integration/test_context_snapshots.py
tests/snapshots/tests.integration.test_context_snapshots.test_context_multiprocess.json
tests/tracer/test_context.py

`ddtrace.context.Context` object is not serializable, meaning it cannot be pickled/shared between processes.
This breaks the example usage we have in our documentation for passing context through to other threads.
e.g. `Process(target=_target, args=(ctx, ))`
This fix added `__getstate__` and `__setstate__` methods to `Context` class to have pickle ignore the RLock which cannot be serialized.
Fixes #4434
Test cases added for pickling/unpickling `Context` instances, as well as a snapshot test added for the multiprocessing strategy outlined in our documentation.
https://ddtrace.readthedocs.io/en/stable/advanced_usage.html#tracing-across-processes

fix(tracing): ensure Context is serializable

---

ddtrace/contrib/flask/helpers.py
ddtrace/contrib/flask/patch.py
releasenotes/notes/remove-deprecated-flask-methods-8d7a4a3d32c3c69d.yaml

The following flask attributes have been deprecated in flask v2.2.2 and will be removed in the next minor release:
- [flask. _app_ctx_stack](https://github.com/pallets/flask/blob/2a54cfa5cecf4dd9f17525bf3ebae4d33a155776/src/flask/__init__.py#L58) 
- [flask. _request_ctx_stack](https://github.com/pallets/flask/blob/2a54cfa5cecf4dd9f17525bf3ebae4d33a155776/src/flask/__init__.py#L69)
This change replaces deprecated methods with flask globals (flask.current_app and flask.request). 
Context: https://github.com/pallets/flask/pull/4682
Closes: https://github.com/DataDog/dd-trace-py/issues/4430
Ensure existing flask tests pass

chore(flask): avoid using deprecated internals

---

ddtrace/profiling/collector/stack.pyx

From #4125, two sections in the stack collector were modified to reflect Python 3.11 changes. However, those changes are not the exact same logic as the former code, including version gating and exception representation. I'm specifically applying these changes *only* if Python 3.11 or higher are being run. Otherwise, it is being reverted to what it was prior to #4125.
While I'm unsure what is exactly causing the issue, we saw an issue (only when the profiler was activated) when running dogweb CI where tests involving sqlalchemy failed on setup with sessions becoming immediately inactive before any queries were run. Furthermore, we saw failures in asyncpg framework tests and major memory/CPU usage spikes when #4125 was merged into 1.x, both of which went away with this fix.

fix(profiler): version gate python 3.11 changes to stack collector

---

tox.ini

[Earlier versions of gevent](https://github.com/gevent/gevent/blob/20.9.0/setup.py#L196) (v1.1, v1.2, v1.3, v1.4, v20.9) only specify a minimum greenlet version. greenlet v2.0 updated its ABI to support py3.11 and is only compatible with [gevent>=22.10.2.](https://github.com/gevent/gevent/pull/1922).
This change updates gevent and opentracer tests to  install `greenlet<2` if `gevent<=20.9` is used.

ci(gevent): pin greenlet for legacy gevent versions

---

ddtrace/internal/remoteconfig/client.py
tests/internal/test_remoteconfig.py

When producing dev builds, setuptools_scm produces a PEP 440-compliant version string, which is not a SemVer. Since we expect the version string for dev build to have rc following the patch component, we simply replace the first occurrence of "rc" with "-rc" to make the version string SemVer-compliant.

chore(rcm): ensure semver in tracer version

---

docker-compose.yml

Agent version v7.40.0 introduced a breaking change which will cause the agent to fail to start if DD_HOSTNAME is not set and the agent cannot deduce a hostname for the container.
https://github.com/DataDog/datadog-agent/releases/tag/7.40.0 (see the "Other Notes" section)

fix(ci): set DD_HOSTNAME in the agent container

---

tests/contrib/redis/test_redis_asyncio.py

The redis job are flaky on snapshot tests that use asyncio. We can use the work introduced in #4374 to mitigate the flaky tests.
Sample log from a [failing job](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/22753/workflows/a86bbe94-d82e-4f32-b8a7-2096f218d3aa/jobs/1547812):
```
At request <Request GET /test/session/snapshot >:
At snapshot (token='tests.contrib.redis.test_redis_asyncio.test_parenting'):
- Directory: /snapshots
- CI mode: 1
- Trace File: /snapshots/tests.contrib.redis.test_redis_asyncio.test_parenting.json
- Stats File: /snapshots/tests.contrib.redis.test_redis_asyncio.test_parenting_tracestats.json
At compare of 1 expected trace(s) to 0 received trace(s):
Did not receive expected traces: 'web-request'
```

fix(ci): add wait for redis asyncio snapshots

---

ddtrace/debugging/_probe/status.py
tests/debugging/probe/test_registry.py
tests/debugging/probe/test_status.py

This change adds the timestamp field to the probe status messages so that they can be ordered in proper chronological order by the backend

chore(debugging): add timestamp to probe status messages

---

ddtrace/contrib/django/utils.py
releasenotes/notes/fix-cors-errors-0fa947a1a583ad0c.yaml

This PR mitigates the following issue: https://github.com/DataDog/dd-trace-py/issues/4305. Accessing ‘request.user’ is not supported in django async context.  
Support for ddtrace user tags in Django ASGI should be added in a follow up PR.

fix(django): django asgi support (when using debug mode)

---

ddtrace/internal/module.py
tests/internal/test_module.py

Accessing attributes from a module object in Python 2 seems to cause potential side-effects, like loading more modules. To prevent them, we ensure that we access attributes using the object type getter to bypass any potential methods that might trigger said side-effects.
```
>   self._origin_map = {origin(module): module for module in sys.modules.values()}
E   RuntimeError: dictionary changed size during iteration
ddtrace/internal/module.py:212: RuntimeError
```

chore(internal): remove side-effects from origin

---

ddtrace/contrib/flask/patch.py
releasenotes/notes/fix-another-flask-body-blocking-acd533aa3c1bd46e.yaml

Fixed another potencial block on wsgi.input.read() on Flask on POSTed data.
In some cases, a read without a length can block, see:
https://stackoverflow.com/questions/22894078/why-does-environwsgi-input-read-block-even-though-it-is-allowed-by-pep-333

fix(asm): fix another body read blocking problem on Flask

---

riotfile.py

Pin pytest-bdd in riot to to unblock CI. Sample failure: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/23362/workflows/3297c2f8-6425-4d32-adc3-b8f9a6afec3d/jobs/1590764.
Cause of failure: pytest_bdd.__version__ attribute was removed: https://github.com/pytest-dev/pytest-bdd/commit/6f95c5cacdafc954b8d60d6fcf93227230f2623a.
This PR will fix the underlying issue: https://github.com/DataDog/dd-trace-py/pull/4485

ci(pytest-bdd): pin pytest-bdd<6.1

---

ddtrace/contrib/dbapi/__init__.py
ddtrace/contrib/psycopg/patch.py
tests/contrib/dbapi/test_dbapi.py

We recently added support for context propagation to database queries that are instrumented using `ddtrace.contrib.dbapi`. However, this change breaks the instrumentation for fetch methods (`fetchone`, `fetchmany`, and `fetchall`). We can safely disable propagation for these methods.
This PR ensure only `callproc()`, `execute()` and `executemany()` operations are used in DBM propagation. 
The following [dbapi operations](https://peps.python.org/pep-0249/#id20) do not execute queries and should not attempt to link APM Spans to Database Operations:
- Cusor.fetchone()
- Cusor.fetchmany()
- Cusor.fetchall()

chore(dbm): disable propagation for dbapi fetch methods

---

ddtrace/debugging/_function/discovery.py
ddtrace/internal/compat.py
ddtrace/internal/logger.py
ddtrace/internal/wrapping.py
ddtrace/profiling/_asyncio.py
ddtrace/profiling/exporter/pprof.pyx

mypy 0.990 was released which breaks some of our type ignores. Some are no longer necessary, others require a different type of ignore.

chore(typing): update types to be compatible with mypy 0.990

---

riotfile.py

As of `asyncpg==0.27.0`, asyncpg [now supports ](https://github.com/MagicStack/asyncpg/releases/tag/v0.27.0)Python 3.11. The asyncpg test suites are now updated so that we now test with Python 3.11.

chore(ci): add asyncpg test suite for Python 3.11

---

lib-injection/Dockerfile
releasenotes/notes/lib-injection-user-19a5b5516c060d8b.yaml

Containers using the root user can be blocked in Kubernetes which makes our lib injection image incompatible with certain Kubernetes configurations.
The solution is to simply add and use a non-root user in the image.
Follows the suggested user configuration mentioned here:
https://github.com/mhart/alpine-node/issues/48#issuecomment-370171836 and supported by [this](https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b
) write up.
Resolves #4476

chore(lib-injection): use non-root user in image

---

.circleci/config.yml

The installation of Python on Windows require a reboot, which is impossible to
do in the CI:
Packages requiring reboot:
- vcredist140 (exit code 3010)
The recent package changes indicate a reboot is necessary.
Please reboot at your earliest convenience.
Exited with code exit status 194

ci(profiling): disable Python 3.8 and 3.9 on Windows

---

ddtrace/profiling/collector/_memalloc.c
ddtrace/profiling/collector/_memalloc_heap.c
ddtrace/profiling/collector/_memalloc_heap.h
ddtrace/profiling/collector/_memalloc_tb.c
ddtrace/profiling/collector/_memalloc_tb.h
ddtrace/profiling/collector/memalloc.py
tests/profiling/collector/test_memalloc.py

This adds tracking the memory domain that has been allocated for in memalloc.
This makes sure we can later use it in test to assert different kind of domain
tracking, and possibly export it to the users if we see value.

chore(profile): track which memory domain allocated Python memory

---

ddtrace/appsec/_remoteconfiguration.py
ddtrace/internal/remoteconfig/client.py
releasenotes/notes/rcm-fix-disable-product-06e4343ba60a89cd.yaml

Fix error in 1-click Remote Configuration. When an user disabled ASM in a dashboard, it was an error in the Agent response payload.
If ASM is disabled in the dashboard, the Agent returns empty (`{}`) instead of return a boolean. Update the code with the new behavior

fix(rcm): disable ASM if it is disabled in the dashboard

---

tests/contrib/kombu/test.py

Variable names within one of the Kombu integration's unit tests were incorrect. Fixed these variable names so that `consumer_span` variable now makes correctly to span with name `kombu.receive` and `producer_span` variable now makes to span with name `kombu.publish`.
Correct tests are good tests

test: fix Kombu test variable names

---

.github/workflows/prune_workflow.yml

There is no method for delete workflow runs from GitHub for older workflow runs or workflows that are no longer run. The action added here is scheduled to perform regular deletion of older workflow runs. A manual trigger can also be used to specify the types of workflow runs to be deleted, which is useful for those workflows that have become inactive or have been disabled.

ci: add prune workflow runs action

---

.circleci/config.yml
riotfile.py
tox.ini

This should reduce the runtime of the futures CI substantially.
Cut down to [2m44s](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/23925/workflows/60ff9e5c-2e07-42d6-9e72-db9cd33f72b1/jobs/1625150) (from [18m44s](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/23915/workflows/db215273-1772-4b1c-baa7-3bcf013c4a03/jobs/1624638)).

chore(ci/futures): move futures tests to riot

---

riotfile.py

The celery integration only instruments using the public API of celery which should be stable under semver. There is not much value gained in testing so many versions and the integration library support guidelines state to only test the major version when only the public API is instrumented:
https://ddtrace.readthedocs.io/en/stable/contributing.html#library-support
[20m36s](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/23929/workflows/2b116026-96a4-4f8c-9561-6f203c93724a/jobs/1625413/parallel-runs/3?filterBy=ALL) -> [12m55s](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/23935/workflows/2aa6419b-dca9-41a6-abaa-556fc79886f0/jobs/1625664/parallel-runs/3?filterBy=ALL)

chore(ci/celery): test less celery

---

tests/contrib/grpc/test_grpc.py
tests/utils.py

Example flaky job: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/23745/workflows/b4bee4b1-4f99-4c57-a259-4ed6f174781b/jobs/1612294

fix(ci): wait for traces in grpc snapshots

---

.circleci/config.yml
riotfile.py
tox.ini

This should reduce the runtime of the futures CI substantially.
[18m5s](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/23937/workflows/a9e38bc6-0ce3-428e-b9a2-96b24e6ff338/jobs/1625894) -> [2m4s](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/23940/workflows/efddfb5f-81e1-44f3-b3db-43c7b0deb17c/jobs/1626091)

chore(ci/dogpile): move tests to riot

---

tests/profiling/collector/test_stack.py

The test_collect_once_with_class_not_right_type test is very flaky on Windows and is causing noise in our CI. Disable it for now.
eg. https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/24036/workflows/226be696-d0a0-4e80-a6b8-e617dc2faf4f/jobs/1632376

chore(ci/profiling): skip flaky test on windows

---

.mergify.yml

With the CI improvements we should see CI pass consistently which means that mergifyio should only keep branches that are passing up to date (else there is an issue with the PR).
This will save resources resulting in faster CI runs and less money wasted on keeping broken PRs up to date.

chore(ci): update mergifyio update rule

---

.circleci/config.yml

These are breaking consistently:
```
CMake Error at C:/Users/circleci.PACKER-633B1A5A/AppData/Local/Temp/pip-build-env-4_tkbtz5/overlay/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/CMakeTestCXXCompiler.cmake:63 (message):
The C++ compiler
"C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe"
is not able to compile a simple test program.
It fails with the following output:
Change Dir: C:/Users/circleci.PACKER-633B1A5A/AppData/Local/Temp/tmpk0i77wqa/libddwaf-prefix/src/libddwaf-build/third_party/proj_rapidjson-prefix/src/proj_rapidjson-build/CMakeFiles/CMakeScratch/TryCompile-jypmkr
Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_ad5ed.vcxproj …
```

ci: disable broken windows profiling jobs

---

tests/debugging/test_debugger.py

This test run:
```
(snapshot,) = d.test_queue
>           assert 0.9 * duration <= snapshot.duration <= 2.5 * duration, snapshot
E           AssertionError: Snapshot(probe=FunctionProbe(probe_id='duration-probe', tags={}, active=True, rate=1.0, condition=None, module='tests.... 'throwable': None}, duration=284068, timestamp=1668637423.0604956, snapshot_id='0b0bba8c-dfaf-4884-9233-3b3208bfbaa1')
E           assert 284068 <= (2.5 * 100000.0)
E            +  where 284068 = Snapshot(probe=FunctionProbe(probe_id='duration-probe', tags={}, active=True, rate=1.0, condition=None, module='tests.... 'throwable': None}, duration=284068, timestamp=1668637423.0604956, snapshot_id='0b0bba8c-dfaf-4884-9233-3b3208bfbaa1').duration
```
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/24048/wor …

chore(ci/debugger): increase range for flaky test

---

releasenotes/notes/system.pid-tag-change-d9e68052b1e5baaf.yaml
releasenotes/notes/tracing:-ddtrace.constants.PID-changed-from-system.pid-to-process_id-197409ef9b68bd73.yaml

Adds a release note stating the change of `system.pid` to `process_id` within the tracer.

chore: add release note for changing system.pid to process_id

---

.github/workflows/prune_workflow.yml

If the `dry_run` input is set, regardless of value, the deletion is not performed.

chore(ci): fix dry run parameter for prune workflows

---

.github/workflows/docker.yml

The `Datadog/dd-trace-py` image published on Docker Hub only supports linux/amd64 platform. This change adds a `ghcr.io/datadog/dd-trace-py/testrunner` container image for both linux/amd64 and linux/arm64.

ci: add testrunner container

---

.circleci/config.yml
releasenotes/notes/old-agent-8193550a76b21357.yaml
riotfile.py

The minimum supported Datadog Agent version of ddtrace is 7.28[^0] as of
ddtrace v1.0 which means we can drop testing support for it.
With this, support for the v0.3 traces endpoint could also be dropped
but maintaining it is little burden due to its overlap with v0.4.
[^0]: https://ddtrace.readthedocs.io/en/v1.0.0/versioning.html#release-support

chore(tests): remove agent v5 testing support

---

.github/workflows/build_deploy.yml

#4431 added a pattern for branches to skip building wheels but the patterns must be quoted.

fix(ci): add quotes for branch patterns

---

releasenotes/notes/fix-httpx-0.23.1-compatibility-99884a43d17b1222.yaml

#4595 should have included a release note, this is the note for that PR.

chore(docs): add missing release note for #4595

---

.circleci/config.yml

This improves the runtime of the profiling windows jobs from 20+m each to around 6m each.
Each profiling windows job is broken up by python version, so we can only set the parallelism to the max number of tox environments for each. For older Python's this is 4, and newer this is 5. This means each tox env will run on it's own node.

chore(ci/profiling): increase profiling windows jobs parallelism

---

.circleci/config.yml
riotfile.py

Django takes ~15m to run, bump the parallelism to get this under 10m.

chore(ci/django): bump parallelism, run less tests

---

.circleci/config.yml

These were running for each base venv build, taking 1 min each.
This should save 1min of CI time.

ci: move riot tests to precheck

---

riotfile.py
tests/internal/test_utils_version.py
tests/tracer/test_utils.py

This PR moves the internal utils packaging tests out of the tracer test suite and into the internal test suite. This should speed up the tracer test suite by almost half, as this removes `packaging` from the riot tracer venvs.
UPDATE: this decreases the tracer test suite duration from `16 min 58s` to `9 min 16s`. It also increases the internal test suite duration from `3 min 10s` to `4 min 11s`, which is an acceptable tradeoff.

chore(ci): move internal version/packaging tests out of tracer test suite

---

.github/workflows/test_frameworks.yml

GitHub `setup-python@v2` actions now fail to install Python 2.7 for our Pylons framework tests. This is because the ubuntu-latest runner (which is now ubuntu-22.04) does not support Python 2.7. This framework test setup action has been pinned to ubuntu-20.04 as this is the last version to support Python 2.7.
See [upstream issue](https://github.com/actions/setup-python/issues/543) for more information.

chore(framework/pylons): pin github actions ubuntu runner to 20.04

---

.circleci/config.yml
riotfile.py
tox.ini

The bottle tests with tox are currently one of the longer running jobs on CI. By moving to riot, the goal is to further decrease the time spent running tests on CI.
Update: moving tornado from tox to riot decreased the test duration from >18 min to 3 minutes.

chore(ci): move bottle tests to riot

---

.circleci/config.yml
riotfile.py
tox.ini

The tornado tests with tox are currently one of the longer running jobs on CI. By moving to riot, the goal is to further decrease the time spent running tests on CI.
Update: moving tornado from tox to riot decreased the test duration from >18 min to 3 minutes.

chore(ci): move tornado tests to riot

---

.circleci/config.yml
riotfile.py
tests/wait-for-services.py
tox.ini

The kombu tests with tox are currently one of the longer running jobs on CI. By moving to riot, the goal is to further decrease the time spent running tests on CI.
Update: moving kombu from tox to riot decreased the test duration from >13 min to 2 minutes.
Also worth noting that the `wait-for-services.py` job on CI has not been properly running for quite some time now with import errors, but they've been silently failing. ~I've removed the kombu-relevant job for now.~ This is fixed in #4639.

chore(kombu): move kombu tests to riot

---

.circleci/config.yml

Sanic is currently one of the longer lasting jobs in our test CI pipeline. The goal is to increase parallelization from 1 to 4 test runners to decrease the test duration.
Update: this decreased the test duration from >14 min to 6 minutes.

chore(ci): increase parallelization of sanic tests

---

.circleci/config.yml
riotfile.py
tox.ini

The `wait-for-services` job has been silently failing on CI since cassandra was moved from tox to riot and the cassandra dependency removed from the `wait-for-services` job. This has potentially caused kombu/cassandra/psycopg/mysql/vertica test suites to be flaky.
I've moved this `wait-for-service` job to riot, and also set the python runner for this job to Python 3.9, as cassandra is incompatible with Python 3.10 onward.

chore(ci): add missing dependency in wait-for-service

---

.circleci/config.yml
riotfile.py
tox.ini

The algoliasearch tests are currently one of the longer running jobs on CI. By moving the test suite to riot from tox, the goal is to further decrease the time spent running tests on CI.
Update: moving algoliasearch to riot decreased the test duration from >13 min to 5 minutes.

ci(algoliasearch): move algoliasearch tests to riot

---

.circleci/config.yml
riotfile.py
tox.ini

The molten tests are currently one of the longer running jobs on CI. By moving the test suite to riot from tox, the goal is to further decrease the time spent running tests on CI.
Update: moving molten to riot decreased the test duration from >10 min to 3 minutes.

chore(ci): move molten test suite to riot

---

.circleci/config.yml

The pytest tests are currently one of the longer running jobs on CI. By increasing the number of parallel test runners from 4 to 8, the goal is to further decrease the time spent running tests on CI.
Update: this increased parallelization decreased the test duration from >11 min to 3 minutes.

chore(ci): increase parallelization of pytest tests on CI

---

.circleci/config.yml

The mongoengine tests are currently one of the longer running jobs on CI. By increasing the number of parallel test runners from 1 to 4, the goal is to further decrease the time spent running tests on CI.
Update: this increased parallelization decreased the test duration from >11 min to 4 minutes.

chore(ci): increase parallelization for mongoengine tests on CI

---

.circleci/config.yml

The httpx tests are currently one of the longer running jobs on CI. By increasing the number of parallel test runners from 1 to 4, the goal is to further decrease the time spent running tests on CI.
Update: this increased parallelization decreased the test duration from >11 min to 5 minutes.

chore(ci): increase parallelization for httpx tests on CI

---

.github/workflows/test_frameworks.yml

Adding the uwsgi test suite to the framework tests in CI to have better test support for gevent.

chore(framework tests): add uwsgi framework test suite

---

ddtrace/contrib/sanic/patch.py

Replacing usages of `set_tag()` that are known to work only with text arguments to `set_tag_str()` in the sanic integration. This should provide a performance benefit as `set_tag_str()` bypasses the unnecessary type checking that occurs in `set_tag()`.

chore(sanic): replace set_tag usages to set_str_tag

---

ddtrace/contrib/rq/__init__.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in the rq integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(rq): replace set_tag usages with set_tag_str

---

ddtrace/contrib/kombu/patch.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in the kombu integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(kombu): replace set_tag usages with set_tag_str

---

ddtrace/contrib/jinja2/patch.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in the jinja2 integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(jinja2): replace set_tag usages with set_tag_str

---

ddtrace/contrib/wsgi/wsgi.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in the wsgi integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(wsgi): replace set_tag usage with set_tag_str

---

ddtrace/contrib/consul/patch.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in the consul integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(consul): replace set_tag usages with set_tag_str

---

ddtrace/contrib/molten/patch.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in the molten integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(molten): replace set_tag usage with set_tag_str

---

ddtrace/contrib/cassandra/session.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in the cassandra integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(cassandra): replace set_tag usages with set_tag_str

---

ddtrace/contrib/boto/patch.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in the boto integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(boto): replace set_tag usages to set_tag_str

---

ddtrace/contrib/redis/util.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in the redis integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(redis): replace set_tag usages with set_tag_str

---

ddtrace/contrib/mako/patch.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in the mako integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(mako): replace set_tag usages with set_tag_str

---

ddtrace/contrib/aiomysql/patch.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in the aiomysql integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(aiomysql): replace set_tag usage with set_tag_str

---

ddtrace/contrib/pylons/renderer.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in the pylons integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(pylons): replace set_tag usage with set_tag_str

---

ddtrace/contrib/celery/signals.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in our celery integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(celery): replace set_tag usage with set_tag_str

---

ddtrace/contrib/aiohttp/middlewares.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in our aiohttp integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(aiohttp): replace set_tag usage with set_tag_str

---

ddtrace/contrib/flask_cache/tracers.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in our flask_cache integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(flask_cache): replace set_tag usage with set_tag_str

---

ddtrace/contrib/dogpile_cache/region.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in our dogpile_cache integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(dogpile_cache): replace set_tag usage with set_tag_str

---

ddtrace/contrib/aiohttp_jinja2/patch.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in our aiohttp-jinja2 integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(aiohttp-jinja2): replace set_tag usage with set_tag_str

---

ddtrace/contrib/rediscluster/patch.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in our rediscluster integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(rediscluster): replace set_tag usage with set_tag_str

---

ddtrace/contrib/tornado/template.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in our tornado integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(tornado): replace set_tag usage with set_tag_str

---

ddtrace/contrib/flask/wrappers.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in the flask integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(flask): replace set_tag usage with set_tag_str

---

ddtrace/contrib/aiopg/connection.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in our aiopg integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(aiopg): replace set_tag usage with set_tag_str

---

ddtrace/contrib/cassandra/session.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in our cassandra integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(cassandra): replace set_tag usage with set_tag_str

---

ddtrace/contrib/pymemcache/client.py

Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in our pymemcache integration. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

chore(pymemcache): replace set_tag usage with set_tag_str

---

ddtrace/contrib/mako/patch.py

Reverts DataDog/dd-trace-py#4697
The framework tests caught an issue with using set_tag_str (which might have always existed using `set_tag` but just failed silently)
cc @Yun-Kim

revert: "chore(mako): replace set_tag usages with set_tag_str"

---

ddtrace/contrib/dogpile_cache/region.py

Reverts DataDog/dd-trace-py#4731
Accidentally was merged with tests failing
cc @Yun-Kim

revert: "chore(dogpile_cache): replace set_tag usage with set_tag_str"

---

ddtrace/internal/utils/http.py
ddtrace/propagation/http.py
tests/tracer/test_context.py
tests/tracer/test_propagation.py
tests/tracer/test_utils.py

Datadog tag values allows colon `:` (0x3A) which is not currently allowed in the W3C Trace Context propagation with `tracestate`. We update the propagation to allow `:` and not allow `~` (0x7E).

chore(w3c): allow colons in datadog tags propagated in tracestate

---

scripts/profiles/encoders/setup.sh

Ensure Ubuntu package information is update before attempting to install. 
This fixes failing encoders-profiler framework test: [example](https://github.com/DataDog/dd-trace-py/actions/runs/3640431431/jobs/6147151806)

chore(encoders): update package tool before installing packages

---

.circleci/config.yml

Pins tox version to unblock ci. [Tox v4.0](https://tox.wiki/en/latest/changelog.html#v4-0-0-2022-12-07) is not compatible with ddtrace test suite. Sample Failure: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/25228/workflows/bc45adf5-0b42-4747-8932-289ae6cc7771/jobs/1710555.
Since we plan to migrate all ddtrace tests from tox to riot in the coming weeks this mitigation should be sufficient.

ci(tox): avoid running ddtrace with tox v4.0

---

ddtrace/internal/utils/version.py
riotfile.py

Packaging v22 raises an InvalidVersion exception instead of returning a LegacyVersion(). If an InvalidVersion is raised we should set the packaging version to `0.0.0`

chore(packaging): support version parsing in packaging v22

---

.circleci/config.yml

https://github.com/DataDog/dd-trace-py/pull/4751

ci(tox): avoid running ddtrace with tox v4.0 [backport #4751 to 1.5]

---

.circleci/config.yml

We now have these configured as scheduled pipelines via the UI.
This method of scheduling jobs is deprecated.
Moving to scheduled pipelines means we can also inject pipeline parameters for the nightly jobs. This should help with #4627
https://circleci.com/docs/schedule-pipelines-with-multiple-workflows/#schedule-using-pipeline-parameters

chore(ci): remove test_nightly scheduled workflow

---

.circleci/config.yml

backport: https://github.com/DataDog/dd-trace-py/pull/4579

ci: disable broken windows profiling jobs [backport 4579 to 1.5]

---

ddtrace/internal/utils/version.py
riotfile.py

Backport https://github.com/DataDog/dd-trace-py/pull/4752

chore(packaging): support version parsing in packaging v22 [backport #4752 to 1.6]

---

ddtrace/internal/utils/version.py
riotfile.py

Backport: https://github.com/DataDog/dd-trace-py/pull/4752

chore(packaging): support version parsing in packaging v22 [backport #4752 to 1.5] 

---

tests/debugging/test_uploader.py

This change slows down the test uploader to ensure that the buffer has a good chance to fill up during a full buffer test, before it is flushed by the underlying periodic worker.
This should resolve a flaky test observed in CI with Python 2.7.

test(debugging): slow down test uploader to allow buffer to fill

---

ddtrace/_monkey.py

The patching logs generated a scary looking message for rq:
```
DEBUG:ddtrace._monkey:failed to patch rq
File "/Users/kverhoog/dev/dd-trace-py/ddtrace/_monkey.py", line 249, in _patch_module
return _attempt_patch_module(module, patch_modules_prefix=patch_modules_prefix)
File "/Users/kverhoog/dev/dd-trace-py/ddtrace/_monkey.py", line 304, in _attempt_patch_module
imported_module.patch()
File "/Users/kverhoog/dev/dd-trace-py/ddtrace/contrib/rq/__init__.py", line 207, in patch
import rq
ModuleNotFoundError: No module named 'rq'
```
because the rq integration imports the `rq` module on `patch()` and doesn't declare required_modules. Nor does it dynamically expose the patch and unpatch methods.
By making the rq integration a patch-on-import integration the …

chore(logging): fix noisy rq patching log

---

ddtrace/contrib/aiobotocore/__init__.py
ddtrace/contrib/aiobotocore/patch.py
ddtrace/contrib/boto/__init__.py
ddtrace/contrib/boto/patch.py
ddtrace/contrib/botocore/__init__.py
ddtrace/contrib/botocore/patch.py
ddtrace/ext/aws.py
docs/spelling_wordlist.txt
releasenotes/notes/fix-aws-tag-params-0e1488513a0ae5c7.yaml
tests/contrib/aiobotocore/test.py
tests/contrib/boto/test.py
tests/contrib/botocore/test.py

We are reducing the number of API parameters that the boto, botocore and aiobotocore integrations collect as span tags by default. This change limits span tags to a narrow set of parameters for specific AWS APIs using standard tag names. Users can opt out and collect no parameters.
This is a functional breaking change. Users can configure the integrations to retain the existing deprecated behavior of collecting all parameters checked against an exclusion list.
Discussed in #4710 
Test cases have been added for new behavior as well as for the deprecated behavior.

fix(aws): limit api params as span tags

---

docs/release_notes.rst

This PR ensures old release notes are not included in v1.7.0. 1.7.0 release notes should NOT contain release notes published in `ddtrace<=1.6.0`.

chore(releasenotes): ignore 1.6 changes in 1.7 release notes

---

ddtrace/internal/utils/http.py
ddtrace/propagation/http.py
tests/tracer/test_context.py
tests/tracer/test_propagation.py
tests/tracer/test_utils.py

Reverts DataDog/dd-trace-py#4741. `:` should delimit datadog tracestate tags not `~`.  
When injecting/extracting ddtrace tags from headers `=` characters should be replaced with `~`. This fix will be introduced in a future PR.

Revert "chore(w3c): allow colons in datadog tags propagated in tracestate"

---

.github/workflows/test_frameworks.yml

The starlette framework tests currently pin sqlalchemy to 1.4.41 due to an upstream issue which has now closed: https://github.com/encode/databases/issues/512. It looks like we can unpin this dependency.
Note: this also indirectly fixes the failing starlette framework tests due to this now closed upstream issue: https://github.com/encode/databases/pull/513, where sqlalchemy==1.4.42 added a new private field in the SQLAlchemy cursor class. While this job uses the latest databases package that has accounted for this field, this was causing attribute errors since we were using a previous version of sqlalchemy that did not yet have that private field added.

fix(starlette framework tests): unpin sqlalchemy

---

ddtrace/contrib/aiobotocore/__init__.py
ddtrace/contrib/aiobotocore/patch.py
ddtrace/contrib/boto/__init__.py
ddtrace/contrib/boto/patch.py
ddtrace/contrib/botocore/__init__.py
ddtrace/contrib/botocore/patch.py
ddtrace/ext/aws.py
docs/spelling_wordlist.txt
releasenotes/notes/fix-aws-tag-params-0e1488513a0ae5c7.yaml
tests/contrib/aiobotocore/test.py
tests/contrib/boto/test.py
tests/contrib/botocore/test.py

fix(aws): limit api params as span tags [backport #4781 to 1.6]

---

ddtrace/internal/utils/http.py
ddtrace/propagation/http.py
tests/tracer/test_context.py
tests/tracer/test_propagation.py
tests/tracer/test_utils.py

Reverts DataDog/dd-trace-py#4741. `:` should delimit datadog tracestate tags not `~`.
When injecting/extracting ddtrace tags from headers `=` characters should be replaced with `~`. This fix will be introduced in a future PR.

Revert "chore(w3c): allow colons in datadog tags propagated in tracestate" (backport #4799 to 1.7)

---

ddtrace/propagation/http.py
tests/tracer/test_propagation.py

Running the W3C trace context parametric tests (introduced [here](https://github.com/DataDog/system-tests/pull/691)) surfaced four issues with how the python tracer propagates traceparent and tracestate headers. These issues are described below and are fixed in this PR.
Currently `trace_parent.islower()` is used to check if a traceparent contains lower case letters and digits (uppercase letters are invalid). Unfortunately `trace_parent.islower()` also evaluates to False if there are no lowercase letters are present in the traceparent (ex: traceparent=00-12312312003-1232131321 would be marked as invalid and dropped). This is incorrect. Fix:
ddb9dc565aa6916728c1e105d07ab06a7cd214e9.
Since the traceparent should contain 48 randomly generated hex values it is unlikely to only contain digits. …

fix(w3c): fix traceparent validation (backport #4791 to 1.7) 

---

ddtrace/contrib/celery/utils.py
releasenotes/notes/celery-flatten-context-dicts-bc5c33b72bd72ac2.yaml
tests/contrib/celery/test_utils.py

Tag data from celery is included as a raw string representation for `delivery_info`, which makes it impossible to use as a facet or measure in APM. The fix is necessary because routing info is valuable to have when understanding why delays happen between task creation and task execution. Issue #4771.
This is only breaking for the tag output format from celery spans, and should only break any cases currently modifying or depending on dicts to be represented as raw strings.
Fixes #4771 
Modified existing unit tests to expect the new tag structure. Manually tested on project that included celery to ensure expected dictionary (`delivery_info`) would be flattened as expected.
Co-authored-by: Brett …

feat(celery): flatten context `delivery_info` tags (backport #4772)

---

.circleci/config.yml
riotfile.py

Right now the `test_latest` workflow runs on every single PR. We only want to run this workflow either manually or via the nightly job.
I tried to get pipeline parameters working to inject the environment variable for `riotfile.py` but it did weird things where it would run a larger set of tests than were being asked for (e.g. running pymysql tests when we were in the bottle suite).
Instead of still trying to get that working, just disable entirely running `test_latest` until we can either implement a hold/manual approval to run or actually implement the pipeline parameter approach.
Doing this now saves us $$$ on CI costs, when we generally don't need these additional test runs.

chore(ci): remove test_latest workflow

---

ddtrace/internal/module.py
tests/internal/test_module.py

Unblocks backport #4806.
Accessing attributes from a module object in Python 2 seems to cause potential side-effects, like loading more modules. To prevent them, we ensure that we access attributes using the object type getter to bypass any potential methods that might trigger said side-effects.
```
>   self._origin_map = {origin(module): module for module in sys.modules.values()}
E   RuntimeError: dictionary changed size during iteration
ddtrace/internal/module.py:212: RuntimeError
```

chore(internal): remove side-effects from origin [backport #4435 to 1.6]

---

riotfile.py
tests/integration/test_integration.py

`attrs==22.2.0` removed support for Python 3.5 and made Python 3.6 support deprecated.
This causes deprecation warnings to be logged and causes our integration tests to fail.
This change makes sure we install a version of `attrs<22.2.0` only for these failing integration tests.
https://www.attrs.org/en/22.2.0/changelog.html#id1

fix(tests): pin attrs<22.2.0 for Python 3.6 in integration tests

---

ddtrace/contrib/botocore/patch.py
releasenotes/notes/fix-kinesis-newline-strip-issue-3a2419b6f29fcab8.yaml
tests/contrib/botocore/test.py

Backports #4700 to 1.7.
During our serialization & de-serialization of kinesis records, any `\n` at the end of the record is stripped by the json library. Customer pipelines rely on this `\n` delimiter to distinguish between different records. This change appends the line break to the end of the record string if it was originally there.
Add support for Databricks which relies on the `\n` delimiter to be present at the end of the record. Look at the related issue for more details.
If the incoming record has a `\n` at the end of the string, we add the `\n` into the string post serialization since it was stripped during the de-serialization process by the json library.
- two unit tests have been added …

fix(botocore): keep newlines in json data for kinesis records [backport #4700 to 1.7]

---

ddtrace/contrib/botocore/patch.py
releasenotes/notes/fix-kinesis-newline-strip-issue-3a2419b6f29fcab8.yaml
tests/contrib/botocore/test.py

Backports #4700 to 1.6.
During our serialization & de-serialization of kinesis records, any `\n` at the end of the record is stripped by the json library. Customer pipelines rely on this `\n` delimiter to distinguish between different records. This change appends the line break to the end of the record string if it was originally there.
Add support for Databricks which relies on the `\n` delimiter to be present at the end of the record. Look at the related issue for more details.
If the incoming record has a `\n` at the end of the string, we add the `\n` into the string post serialization since it was stripped during the de-serialization process by the json library.
- two unit tests have been added …

fix(botocore): keep newlines in json data for kinesis records [backport #4700 to 1.6]

---

ddtrace/internal/telemetry/data.py
releasenotes/notes/fix-telemetry-platform-libc-ver-call-8872bde91bcc8765.yaml
tests/telemetry/test_data.py

When calling `platform.libc_ver()` on an unsupported system it can raise an `OSError`.
This change adds exception handling for `OSError` and regression test.

fix(internal): catch possible OSError when calling platform.libc_ver() on an unsupported machine

---

.github/workflows/test_frameworks.yml

backport: https://github.com/DataDog/dd-trace-py/pull/4801
The starlette framework tests currently pin sqlalchemy to 1.4.41 due to
an upstream issue which has now closed:
https://github.com/encode/databases/issues/512. It looks like we can
unpin this dependency.
Note: this also indirectly fixes the failing starlette framework tests
due to this now closed upstream issue:
https://github.com/encode/databases/pull/513, where sqlalchemy==1.4.42
added a new private field in the SQLAlchemy cursor class. While this job
uses the latest databases package that has accounted for this field,
this was causing attribute errors since we were using a previous version
of sqlalchemy that did not yet have that private field added.
guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release- …

ci(starlette): unpin sqlalchemy in framework tests [backport #4801 to 1 7]

---

ddtrace/internal/telemetry/data.py
releasenotes/notes/fix-telemetry-platform-libc-ver-call-8872bde91bcc8765.yaml
tests/telemetry/test_data.py

When calling `platform.libc_ver()` on an unsupported system it can raise an `OSError`.
This change adds exception handling for `OSError` and regression test.

fix(internal): catch possible OSError when calling platform.libc_ver() (backport #4828)

---

ddtrace/tracer.py
releasenotes/notes/fix-use-mapped-service-name-dc107848fd53a51e.yaml
tests/tracer/test_tracer.py

Backport of #4782 
After getting the remapped service name we were not using it to determine if the `DD_VERSION` tag should be set, or when keeping track of all the service names seen by the tracer
Added two tests to validate that when setting `DD_SERVICE_MAPPING` we get the expected results for `version` tag and the collected list of services seen by the tracer.

fix(tracing): fix usage of mapped_service when creating a new span (backport #4782)

---

ddtrace/internal/utils/http.py
tests/tracer/test_utils.py

Right now `_dd.propagation_error`  (and any internal tag that starts with p) will get set as a tracestate tag. With this change, we make sure to only add `_dd.p.*` tags.

chore(w3c): update tracestate tag regex

---

.circleci/config.yml
riotfile.py

Backport of #4792 to `1.7`
Right now the `test_latest` workflow runs on every single PR. We only want to run this workflow either manually or via the nightly job.
I tried to get pipeline parameters working to inject the environment variable for `riotfile.py` but it did weird things where it would run a larger set of tests than were being asked for (e.g. running pymysql tests when we were in the bottle suite).
Instead of still trying to get that working, just disable entirely running `test_latest` until we can either implement a hold/manual approval to run or actually implement the pipeline parameter approach.
Doing this now saves us $$$ on CI costs, when we generally don't need these additional test runs.

chore(ci): remove test_latest workflow (backport #4792)

---

ddtrace/internal/writer.py
releasenotes/notes/v05-encoding-eac70f23850a445e.yaml
tests/tracer/test_writer.py

Using the `v0.5` API endpoint on Windows can cause issues (see #4829 for details).
This PR makes it so we default to `v0.4` on Windows and will raise an exception if you try to use `v0.5` on a Windows machine.
Fixes #4829

fix(tracing): disallow v0.5 api usage for windows machines

---

ddtrace/appsec/_remoteconfiguration.py
ddtrace/internal/writer.py
ddtrace/tracer.py

Workaround for remote config to work properly with gevent.
This PR ensures the Remote config worker thread is launched at the very end, not interrupting the gevent patching mechanism.
Without this PR, the gevent patching is interrupted so if gevent is used, it won't work as expected.
As a side effect, if gevent is used and Django is installed, our Django patching mechanism collides with gevent raising a Django ImproperlyConfigured error.

chore(iast): remote config thread workaround for gevent [backport #4749 to 1.7]

---

ddtrace/appsec/utils.py
releasenotes/notes/asm-1-click-activation-with-RCM-by-default-92233ac7f60292e0.yaml
tests/appsec/test_remoteconfiguration.py

Change the value for DD_REMOTE_CONFIGURATION_ENABLED to True by default, so AppSec 1-click-activation feature is enabled by default, unless this environment variable is disabled.

chore(asm): change default value for remote config env var [backport #4813 to 1.7]

---

ddtrace/internal/writer.py
releasenotes/notes/v05-encoding-eac70f23850a445e.yaml
tests/tracer/test_writer.py

Backports: https://github.com/DataDog/dd-trace-py/pull/4830

fix(tracing): disallow v0.5 api usage for windows machines (backports #4830 to 1.7)

---

ddtrace/internal/utils/http.py
tests/tracer/test_utils.py

Right now _dd.propagation_error (and any internal tag that starts with p) will get set as a tracestate tag. With this change, we make sure to only add _dd.p.* tags.

chore(w3c): update tracestate tag regex (backport #4827 to 1.7)

---

ddtrace/contrib/tornado/handlers.py
releasenotes/notes/tornado_error_code_http_server-d1532491cb89563c.yaml
tests/contrib/tornado/test_tornado_web.py

Use `config.http_server.error_ranges` to determine whether   `tornado.request` spans should be marked as error spans.
Resolve: https://github.com/DataDog/dd-trace-py/issues/4838

feat(tornado): support config.http_server.error_ranges

---

ddtrace/internal/utils/http.py
ddtrace/propagation/http.py
tests/tracer/test_context.py
tests/tracer/test_propagation.py
tests/tracer/test_utils.py

Upon review we found that `:` should be allowed in the tags value: https://docs.datadoghq.com/getting_started/tagging/#define-tags  
We were using `:` as a way to represent an "encoded" = in the propagated trace tag values, so we decided to change the "encoded" value of the `=` to `~`.
Therefore, we should allow `=` in tag values. In order to do this in tracestate, we need to encode it. Therefore we encode `~`s in the value as `_` first, and then encode `=` as `~`.

chore(w3c): replace ~ with _ and = with ~

---

ddtrace/internal/utils/http.py
ddtrace/propagation/http.py
tests/tracer/test_context.py
tests/tracer/test_propagation.py
tests/tracer/test_utils.py

Upon review we found that `:` should be allowed in the tags value: https://docs.datadoghq.com/getting_started/tagging/#define-tags
We were using `:` as a way to represent an "encoded" = in the propagated trace tag values, so we decided to change the "encoded" value of the `=` to `~`.
Therefore, we should allow `=` in tag values. In order to do this in tracestate, we need to encode it. Therefore we encode `~`s in the value as `_` first, and then encode `=` as `~`.
Co-authored-by: Munir Abdinur <munir.abdinur@datadoghq.com>

chore(w3c): replace ~ with _ and = with ~ (#4822) [backport #4822 to 1.7]

---

tests/conftest.py
tests/internal/lazy.py
tests/internal/test_module.py

This change adds a test to ensure that the import of ddtrace does not cause lazy modules to be force-loaded when the ModuleWatchdog is installed on start-up.

test(internal): check that ddtrace does not force-load lazy modules

---

ddtrace/profiling/profiler.py
docs/configuration.rst
releasenotes/notes/profiler-code-provenance-issue-a912ea575a43ed07.yaml
releasenotes/notes/profiling-enable-code-provenance-3d9663e0cd742fcd.yaml

Reverts #4519 as this was causing a performance regression. Added release note acknowledging known performance regression. Note that code provenance is still disabled by default.

fix(profiler): revert code provenance enabled by default

---

ddtrace/internal/utils/time.py
tests/internal/test_utils_time.py

Fix error in `parse_isoformat` function with Python 2 retrieving information from Remote Configuration

fix: parse datetime isoformat in python2

---

ddtrace/internal/utils/time.py
tests/internal/test_utils_time.py

fix: parse datetime isoformat in python2 [backport #4874 to 1.7]

---

releasenotes/notes/cython-import-fix-a5b86512a7a59017.yaml
setup.py

This PR makes an error message from `pip install ddtrace` more helpful. The specific error happens when attempting to `import Cython.*` under pip versions older than 18.
I tested this with `pip install -e /path/to/local/repo` and `pip install --upgrade pip==9.0.3`. Because it's only a change to outputted text on install I don't think it's necessary to add unit testing.

fix: display a more helpful error message when cython imports fail

---

ddtrace/contrib/trace_utils.py
releasenotes/notes/asm-event-tracking-sdk-d7e8516511c73589.yaml
tests/tracer/test_trace_utils.py

chore(asm): rename track_user_login to track_user_login_event to match the API in other languages

---

ddtrace/span.py

We don't use _remove_exc_info anywhere since a separate PR removed its usage, and it's a private method.

chore(span): remove unused method _remove_exc_info

---

ddtrace/contrib/trace_utils.py
releasenotes/notes/fix-http-url-200fca099f41ce49.yaml
tests/contrib/aiohttp/test_aiohttp_client.py
tests/contrib/requests/test_requests.py
tests/snapshots/tests.contrib.aiohttp.test_aiohttp_client.test_auth_200_request.json
tests/tracer/test_trace_utils.py

This fix removes unintended url parts in the `http.url` tag.

fix: remove url parts from http.url tag

---

tests/contrib/sanic/test_sanic_server.py

The user agent used in testing may change as the version of `requests` being used changes.
This change ensure that we do not consider the `http.useragent` tag value in the snapshots for the sanic tests.

chore(sanic): ensure sanic tests ignore the http.userganet tag in snapshots

---

tests/contrib/sanic/test_sanic_server.py

Backport of #4907
The user agent used in testing may change as the version of `requests` being used changes.
This change ensure that we do not consider the `http.useragent` tag value in the snapshots for the sanic tests.

chore(sanic): ensure sanic tests ignore the http.userganet tag in snapshots [backport #4907 to 1.6]

---

ddtrace/internal/remoteconfig/client.py

Backport of #4910
The fix for ensuring RCM used a SemVer compliant version string only took into account ddtrace versions that match `x.y.zrc2` or `x.y.zrc2.dev3+gf344hg`, but not `x.y.z.dev3+gf344hg`.
This fix ensures that if we have a `.dev` without `rc` that we properly convert `.dev` -> `-dev` which will make it SemVer compliant.
Since the tests rely heavily on the version of `ddtrace.__version__` writing a test is challenging. We should revisit this in the future so we can mock the version and parametrize the test to ensure all variations are tested.

fix(internal): properly convert PEP 440 version to SemVer for RCM client [backport #4910 to 1.7]

---

ddtrace/contrib/trace_utils.py
releasenotes/notes/fix-http-url-200fca099f41ce49.yaml
tests/contrib/aiohttp/test_aiohttp_client.py
tests/contrib/requests/test_requests.py
tests/snapshots/tests.contrib.aiohttp.test_aiohttp_client.test_auth_200_request.json
tests/tracer/test_trace_utils.py

This fix removes unintended url parts in the `http.url` tag.

fix: remove url parts from http.url tag [backport #4904 to 1.6]

---

tests/contrib/sanic/test_sanic_server.py

Backport of #4907 to 1.7
The user agent used in testing may change as the version of `requests` being used changes.
This change ensure that we do not consider the `http.useragent` tag value in the snapshots for the sanic tests.

chore(sanic): ensure sanic tests ignore the http.useragent tag in snapshots [backport #4907 to 1.7]

---

ddtrace/contrib/trace_utils.py
releasenotes/notes/fix-http-url-200fca099f41ce49.yaml
tests/contrib/aiohttp/test_aiohttp_client.py
tests/contrib/requests/test_requests.py
tests/snapshots/tests.contrib.aiohttp.test_aiohttp_client.test_auth_200_request.json
tests/tracer/test_trace_utils.py

Backport of #4906 
This fix removes unintended url parts in the `http.url` tag.
Co-authored-by: Tahir H. Butt <tahir.butt@datadoghq.com>

fix: remove url parts from http.url tag [backport #4906 to 0.61]

---

riotfile.py

MySQL connector python introduced in version 8.0.32 a `__future__` import making it incompatible with Python < 3.7

chore(ci): pin mysql-connector-python to 8.0.31 for Python 3.6

---

riotfile.py

Backport of #4919
`rq` released 1.12.0 which dropped support for Python 3.5, but did not update the `python_requires` in `setup.py` to reflect this. This means it is possible to install 1.12.0 on Python 3.5, which will not work.
https://github.com/rq/rq/issues/1755
I also updated the overall tested versions of `rq` since the current pattern is fairly (unnecessarily?) verbose.

chore(ci): update tested versions of rq [backport #4919 to 0.61]

---

riotfile.py

`rq` released 1.12.0 which dropped support for Python 3.5, but did not update the `python_requires` in `setup.py` to reflect this. This means it is possible to install 1.12.0 on Python 3.5, which will not work.
https://github.com/rq/rq/issues/1755
I also updated the overall tested versions of `rq` since the current pattern is fairly (unnecessarily?) verbose.

chore(ci): update tested versions of rq

---

ddtrace/contrib/trace_utils.py
releasenotes/notes/fix-verify-url-7d0dd6b0ab53306f.yaml
tests/tracer/test_trace_utils.py

Backport #4914 and #4915 
Fix missing case where the `@` symbol is in the url but not in the netloc.
Testing: This is tested in some framework tests (fastapi at least), that are failing at the moment, this should fix them

chore(test): avoid ValueErorr when `@` not in netloc [backport #4914 to 1.7]

---

riotfile.py

mysql-connector-python still ships a `py2.py3-none-any` Wheel even though the code is not compatible with Python versions older then Python 3.6.
This means we `pip` will still try to install this version on older/unsupported versions.

fix(ci): update tested mysql-connector versions for 3.6

---

riotfile.py

Backport of #4929 
mysql-connector-python still ships a `py2.py3-none-any` Wheel even though the code is not compatible with Python versions older then Python 3.6.
This means we `pip` will still try to install this version on older/unsupported versions.

fix(ci): update tested mysql-connector versions for 3.6 [backport #4929 to 0.61]

---

ddtrace/contrib/trace_utils.py
releasenotes/notes/fix-verify-url-7d0dd6b0ab53306f.yaml
tests/tracer/test_trace_utils.py

Backport #4914 and #4915
Fix missing case where the `@` symbol is in the url but not in the netloc.
Testing: This is tested in some framework tests (fastapi at least), that are failing at the moment, this should fix them

chore(test): avoid ValueErorr when `@` not in netloc [backport #4914 to 0.61]

---

releasenotes/notes/asm-upgrade-libddwaf-cbebe158731bf7d9.yaml
setup.py
tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
tests/snapshots/tests.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot.json
tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
tests/snapshots/tests.contrib.django.test_django_snapshots.test_appsec_enabled.json
tests/snapshots/tests.contrib.django.test_django_snapshots.test_appsec_enabled_attack.json

Bump libddwaf dependency to 1.6.1 and use the sha256 checksums they provide now.

chore(asm): bump libddwaf to 1.6.1 with sha256 checksums

---

ddtrace/debugging/_encoding.py
ddtrace/debugging/_expressions.py
tests/debugging/test_debugger.py
tests/debugging/test_expressions.py

Update expression parser to match with the updated debugger backend expression json format. This change replaces the old syntax for field references with the new reference operators `ref`, `getmember` and `index`.

chore(debugger): use new reference operators in JSON DSL

---

ddtrace/profiling/exporter/pprof.pyx
releasenotes/notes/perf-profiler-lower-overhead-f2c2e7c12c337196.yaml
tests/profiling/exporter/test_pprof.py

This change removes more unnecessary sorting operations that were added to ensure that the data was reproducible. This was only beneficial for tests, and as such only constituted an extra burden on CPU that just added overhead to the profiler.

perf(profiling): remove more unnecessary sorting

---

docs/spelling_wordlist.txt
releasenotes/notes/prof-3-11-traceback-issue-20e06214d4a3879b.yaml

As #4895 has not been merged yet and we don't want to block the 1.8 release any longer, this PR adds a release note entry publishing the known issue of the profiler running in Python 3.11 with the new `PyFrameObject` opaque struct changes.

chore(profiler): add known issue changelog for Python 3.11 PyFrameObject

---

.github/workflows/system-tests.yml

System tests need to know the proper version of the library, and setuptools_scm needs the git history to compute it.

chore(ci): ensure setuptools_scm has all information to compute library version

---

.github/workflows/test_frameworks.yml

The fsatapi framework tests currently pin sqlalchemy to 1.4.41 due to an upstream issue which has now closed: https://github.com/encode/databases/issues/512. It looks like we can unpin this dependency.
Fixes #4800.

chore(framework test): unpin sqlalchemy for fastapi framework tests

---

.github/workflows/lib-injection.yml
.github/workflows/system-tests.yml

Backport of #4545
Move whole lib injection tests to system-tests.
Launch these tests for every PR.

ci: testing python lib injection [backport #4545 to 1.7] 

---

.github/workflows/test_frameworks.yml

This change splits the exploration tests with separate runs for the coverage and deterministic profiling modes to reduce the overhead during each run and lower the chances of CI worker timeouts.

ci(django): split django exploration tests in separate runs

---

ddtrace/appsec/ddwaf/__init__.py
ddtrace/appsec/ddwaf/ddwaf_types.py
ddtrace/appsec/processor.py
tests/appsec/test_processor.py

- Avoid any errors or exceptions raised while running the WAF to interrupt the request
- Add test coverage and regression tests
---------
Co-authored-by: Christophe Papazian <christophe.papazian@datadoghq.com>

chore(asm): fix ddwaf errors found in 1.8.0rc1 [backport #4975 to 1.8]

---

.circleci/config.yml
hooks/scripts/run-slotscheck.sh
pyproject.toml
riotfile.py

#3527 seemed to have inadvertently removed the file argument in the slotscheck job in CI. We can re-enable the CI job with the minor update to the exclude list.

ci: re-enable slotscheck

---

tests/contrib/rq/test_rq.py

The rq test `test_enqueue()` has been found to be flaky in CI runs (example [run](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/27434/workflows/9c729ac6-9ee7-4c25-a9ac-b90fba66f419/jobs/1873546)), with traces not immediately being found. The solution is to use the snapshot function's `wait_for_num_traces` option to make the test retry fetching traces from the testagent for a few seconds.
Note: this workaround is avoided in Python 3.5 as for some reason the snapshot function's `wait_for_num_traces` retry mechanism does not work in 3.5.

chore(rq): wait for snapshot traces in flaky rq test

---

.github/workflows/require-checklist.yaml

Use https://github.com/mheap/require-checklist-action to enforce that the checklist is completed. This should encourage authors and reviewers to manually verify things for which there is no automation yet.

chore(ci): add require checklist action

---

.github/CODEOWNERS

Assign ownership of `tests/contrib/flask/test_flask_appsec.py` and `tests/contrib/django/test_django_appsec.py` to ASM.  
Better ownership of ASM files.

chore: assign ownership of appsec framework tests to asm

---

ddtrace/appsec/_asm_request_context.py
tests/appsec/test_asm_request_context.py

Add a ASM context manager. Didn't include a release note since it's an internal private API.
The new blocking features of ASM, specially IP blocking, require that we store some values, mostly headers and the IP, even before the span is created. This is a stopgap measure until the new tracer context API is created.
This is a simple implementation using `contextvars.ContextVars` and some ad-hoc functions to get or set the values, plus a shortcut function to set some values and a context manager.
This includes some basic unittests.  The PRs to add Flask and Django IP Blocking will also add more tests regarding this for checking that the context is correctly reset on each request cycle.
This is an internal module that only new features will use so there is no risk of breakage.
Signed-off-by: …

feat(asm): add new ASM context manager

---

.github/workflows/build-and-publish-image.yml
.github/workflows/build_deploy.yml
.github/workflows/lib-injection.yml

The [`runs_on` field was missing](https://github.com/DataDog/dd-trace-py/actions/runs/4075923260) which caused the 1.7.4 release workflow to fail. This was introduced in https://github.com/DataDog/dd-trace-py/pull/4931. To avoid this problem, or problems like this from happening again, the shared logic is pulled into a reusable workflow[0]. Now the build and push logic is shared between the test and publish jobs which will give us a better idea if the publish one works.
Note that this still doesn't fully test the deploy path but our release candidate releases do this quite well. We just have a gap for patch releases but I think this is acceptable risk.
[0] https://docs.github.com/en/actions/using-workflows/reusing-workflows

fix(ci/lib-injection): add missing runs_on value

---

.github/workflows/build-and-publish-image.yml
.github/workflows/build_deploy.yml
.github/workflows/lib-injection.yml

The `runs_on` field was missing which caused the 1.7.4 release workflow to fail.  To avoid this problem, or problems like this from happening again, the shared logic is pulled into a reusable workflow[0]. Now the build and push logic is shared between the test and publish jobs which will give us a better idea if the publish one works.
[0] https://docs.github.com/en/actions/using-workflows/reusing-workflows

fix(ci/lib-injection): add missing runs_on value [backport #5039 to 1.7]

---

ddtrace/contrib/pylons/middleware.py
releasenotes/notes/fix-unicode-decode-errors-pylons-52d28b22f82e184a.yaml
tests/contrib/pylons/test_pylons.py

Backports #5029 to 1.7
This PR is related to a critical exception detected two days ago on https://app.datadoghq.com/logs
src="https://user-images.githubusercontent.com/114495376/216595049-a0fa6bb0-5c2b-4e5f-ac97-e83000c225eb.png">
Silently drop non translatable UTF-8 characters instead of raising critical exception in Pylons framework.

fix(asm): fix unicode decode errors in pylons [backport #5029 to 1.7]

---

benchmarks/set_http_meta/config.yaml

#4967 removed an env variable `DD_TRACE_CLIENT_IP_HEADER_DISABLED`, but did not replace it (referenced by `ip_disabled`) in the benchmark tests for `set_http_meta` scenario. This PR replaces the `ip_disabled` with `ip_enabled` as was added in #4967.

chore(benchmarks): update set_http_meta benchmark config

---

.github/workflows/lib-injection.yml

We've been changing the tests quite a bit lately which has led to CI breakage. It makes sense, since we backport so much, to fix the version so that CI remains stable.

test(lib-injection): fix the version of tests used

---

.github/workflows/backport.yml

I still haven't figured out the best way to test this, but I dug into lodash's documentation further, and they have a REPL in their docs to try executing code.
This seems to produce what we want:
```js
var compiled = _.template('<% print(JSON.stringify(labels)) %>');
var res = compiled({ 'labels': ['profiling', 'changelog/no-changelog'] });
JSON.parse(res)
```
This is the closest to a test I could figure out.
If this doesn't work, then I'll just remove the `labels_template`. I'd really like to figure out how to make this work so original labels like `changelog/no-changelog` get copied to the backport PR.

fix: fix the backport GitHub Action's labels_template lodash template

---

benchmarks/threading/scenario.py

#2791 auto-registered any subclasses of `bm.Scenario`, meaning that the decorator `@bm.register` was no longer necessary (and was also removed in that PR). However, #2789 added a new threading benchmark scenario which still had that decorator, meaning that this scenario no longer works. This PR updates that scenario by removing the `@bm.register` decorator.
Unblocks #5040.

chore(benchmarks): remove outdated decorator in threading scenario

---

tests/contrib/django/test_django_appsec.py

Split assert lines on json tag from waf calls into several lines.
- prevents non informative message about json loader in case of failed test.
- allows to more easily understand if json tag is missing or if it is not as expected.

test(asm): small improvement for tests django appsec

---

.github/workflows/lib-injection.yml

We've been changing the tests quite a bit lately which has led to CI breakage. It makes sense, since we backport so much, to fix the version so that CI remains stable.
This particular change, changed the scripts used to run the tests.

test(lib-injection): fix the version of tests used [backport #5062 to 1.8]

---

docs/conf.py

The Configuration page in particular gets messy with longer environment variable names in the sidebar, making it harder to read the docs.
Increasing the overall page width to 1200px (from the default of 940px) and increasing the sidebar size to 400px (from 220px) provides a more hospitable view.
Signed-off-by: Mike Fiedler <miketheman@gmail.com>
- [n/a] Testing strategy is described if automated tests are not included in the PR.
- [n/a] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [n/a] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines) are followed.

docs: update theme to prevent overlap on configuration

---

ddtrace/contrib/pylons/middleware.py
releasenotes/notes/fix-unicode-decode-errors-pylons-52d28b22f82e184a.yaml
tests/contrib/pylons/test_pylons.py

Backports https://github.com/DataDog/dd-trace-py/pull/5029 to 1.8
This PR is related to a critical exception detected two days ago on https://app.datadoghq.com/logs
src="https://user-images.githubusercontent.com/114495376/216595049-a0fa6bb0-5c2b-4e5f-ac97-e83000c225eb.png">
Silently drop non translatable UTF-8 characters instead of raising critical exception in Pylons framework.

fix(asm): fix unicode decode errors in pylons [backport #5029 to 1.8]

---

ddtrace/span.py
releasenotes/notes/span_finish_with_ancestors-da848c160c0af08c.yaml
tests/tracer/test_tracer.py

To support use cases where a span lineage needs to be finished abruptly (eg. AWS Lambda timeouts), a method `Span.finish_with_ancestors` is introduced.
This is a bit of a workaround for the fact that spans cannot be sent unfinished to the backend. Currently, in cases like AWS Lambda functions, the trace will never be sent because the spans are unfinished. This API at least enables traces to be sent with the drawback of not being totally accurate.

feat(span): add finish_with_ancestors method

---

ddtrace/internal/telemetry/writer.py
tests/telemetry/test_writer.py

`TelemetryWriter._debug` field and `"DD-Telemetry-Debug-Enabled"` request header should be set to a boolean (True/False), not a lower case string ("true"/"false"). 
This bug was introduced by the following [commit](https://github.com/DataDog/dd-trace-py/commit/76294ea33dcad52f40bd40b5b7001f34152afba2) and is set to be released in v1.9.0. Since this bug is not released, a release note is not required.

fix(telemetry): debug field should be set to a boolean

---

tests/conftest.py

This change allows passing in callables for performing more complex checks against the standard streams captured during a test run in a subprocess.

test: improve stream checks for subprocess tests

---

releasenotes/notes/prof-3-11-traceback-issue-20e06214d4a3879b.yaml

This PR removes the known issue release note for the profiler on Python 3.11 relating to `PyFrameObjects`, which was mitigated by #5019.

chore(profiler): remove resolved known issue for profiler on Python 3.11

---

releasenotes/notes/prof-3-11-traceback-issue-20e06214d4a3879b.yaml

Backport of #5153 to 1.8
This PR removes the known issue release note for the profiler on Python 3.11 relating to `PyFrameObjects`, which was mitigated by #5019.

chore(profiler): remove resolved known issue for profiler on Python 3.11 [backport #5153 to 1.8]

---

.github/workflows/test_frameworks.yml

The framework test suite started failing with the follow 2 errors:
- The job was hanging due to an issue with Flint.
- There was a failing test that is not related to a change in dd-trace-py:
```
if context.result_column_struct:
>           (
result_columns,
cols_are_ordered,
textual_ordered,
ad_hoc_textual,
loose_column_name_matching,
) = context.result_column_struct
E           ValueError: not enough values to unpack (expected 5, got 4)
```
Instead of trying to debug the cause of this specific error we have updated the framework test suite to use the latest version of FastAPI (0.92.0), and moving from `flint` to `pip` for installing dependencies. This has resolved the issue.
**Risks:** This was likely caused because a dependency was updated. We are still susceptible to updated …

chore(ci): update fastapi framework test suite to latest version 0.92.0

---

ddtrace/appsec/ddwaf/__init__.py

Keep the WAF handle even if the initialisation of the WAF returns some errors.
This is the expected behaviour, from system test `tests/appsec/waf/test_reports.py` `Test_Monitoring.test_waf_monitoring_errors`

chore(asm): keep handle even if they are errors at initialisation

---

ddtrace/appsec/utils.py
tests/appsec/test_remoteconfiguration.py

Error in capabilities. If we set DD_APPSEC_ENABLED env var, we don't report capabilities in RC requests

fix(rcm): error in capabilities

---

ddtrace/appsec/ddwaf/__init__.py
ddtrace/appsec/processor.py

To avoid performance issues, this PR defines a way to keep the same WAF context for all calls to the WAF during a single request.

chore(asm): keep waf context during request

---

setup.py

This change skips compilation of this WIP feature under Windows, which is currently failing on 1.x

fix(asm): skip compilation of _taint_tracking for Windows OS

---

.circleci/config.yml

Graphql is our slowest testsuite. Currently test runs had a parallelism of 1 and take 16mins ([example](https://app.circleci.com/pipelines/gh/DataDog/dd-trace-py/29392/workflows/5d8d5aa6-0a9a-4162-bf1a-6f4d303270d1/jobs/1996793/steps)). With a parallelism of 8 tests should finish in 3-5mins.

ci(graphql): reduce test runs from 16mins to 3mins

---

ddtrace/contrib/psycopg/patch.py
ddtrace/propagation/_database_monitoring.py
releasenotes/notes/dbm-support-sql-queries-with-the-type-bytes-30fb4b75ea2f8cf8.yaml
tests/contrib/psycopg/test_psycopg.py
tests/internal/test_database_monitoring.py
tests/snapshots/tests.contrib.psycopg.test_psycopg.test_postgres_dbm_propagation_tag.json

Database monitoring and APM Linking only supports unicode sql queries. This PR extends support to sql queries with the type: `bytes`.
When `DD_DBM_PROPAGATION_MODE=full` the following code snippet raises an excpetion:
```
import psycopg2
import ddtrace
ddtrace.patch(psycopg=True)
conn = psycopg2.connect(**POSTGRES_CONFIG)
conn.cursor().execute(b"select 'blah'")
```

fix(dbm): support byte string queries (#5188) [backport to 1.9]

---

.gitlab-ci.yml

The public-images job provides RETRY_DELAY and RETRY_COUNT options, use these instead of trying to replicate the behaviour ourselves.
Instead of publishing after 1 day, try after 4 hours which is closer to the time it takes to publish the package.
This new functionality can be tested manually during the next release. The risk is that it might not work due to gitlab killing the job for taking so long. In that case, the images can still be published by manually invoking the job from the gitlab UI.

chore(lib-injection): use provided delay, retry options

---

ddtrace/contrib/dbapi/__init__.py
docs/spelling_wordlist.txt
releasenotes/notes/dbapi-rowcount-3cf18b68114a6cad.yaml

Some database drivers (namely cassandra-driver) do not implement rowcount on cursor objects and so the dbapi integration fails.
I have omitted a test as I believe that the code and inlined comment is sufficient for preventing regressions. Another factor was that it is not trivial to add a test case repro-ing the issue with django + cassandra-driver.
(Aside, perhaps having a special `regression` test suite/environment which can be easily configured to test different permutations of libary and version would be a good addition for cases like this)

fix(dbapi): don't assume rowcount exists (backport #5139 to 1.8)

---

ddtrace/contrib/dbapi/__init__.py
docs/spelling_wordlist.txt
releasenotes/notes/dbapi-rowcount-3cf18b68114a6cad.yaml

Some database drivers (namely cassandra-driver) do not implement rowcount on cursor objects and so the dbapi integration fails.
I have omitted a test as I believe that the code and inlined comment is sufficient for preventing regressions. Another factor was that it is not trivial to add a test case repro-ing the issue with django + cassandra-driver.
(Aside, perhaps having a special `regression` test suite/environment which can be easily configured to test different permutations of libary and version would be a good addition for cases like this)

fix(dbapi): don't assume rowcount exists (backport #5139 to 1.9)

---

.github/workflows/system-tests.yml

We've been changing the tests quite a bit lately which has led to CI breakage. It makes sense, since we backport so much, to fix the version so that CI remains stable.
This particular change, changed the scripts used to run the tests.

test(lib-injection): fix the version of tests used [backport to 1.6]

---

ddtrace/contrib/dbapi/__init__.py
docs/spelling_wordlist.txt
releasenotes/notes/dbapi-rowcount-3cf18b68114a6cad.yaml

Some database drivers (namely cassandra-driver) do not implement rowcount on cursor objects and so the dbapi integration fails.
I have omitted a test as I believe that the code and inlined comment is sufficient for preventing regressions. Another factor was that it is not trivial to add a test case repro-ing the issue with django + cassandra-driver.
(Aside, perhaps having a special `regression` test suite/environment which can be easily configured to test different permutations of libary and version would be a good addition for cases like this)

fix(dbapi): don't assume rowcount exists (backport #5139 to 1.7)

---

ddtrace/appsec/processor.py
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json

Do not accumulate rules loaded metrics. 
Required for system-tests `tests/appsec/waf/test_reports.py`

chore(asm): fix loaded rules metric

---

ddtrace/appsec/_asm_request_context.py
ddtrace/appsec/processor.py
tests/appsec/rules-good.json
tests/appsec/test_processor.py
tests/appsec/test_telemety.py
tests/contrib/flask/test_flask_appsec_telemetry.py
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json

ASM Telemetry Metrics support such as `waf.requests`, `waf.duration`, etc.
This PR is part of the main PR https://github.com/DataDog/dd-trace-py/pull/5046
ASM needs to report telemetry metrics
System tests: 
- https://github.com/DataDog/system-tests/pull/823
- https://github.com/DataDog/system-tests/pull/890
This PR comes from
- https://github.com/DataDog/dd-trace-py/pull/5191
- https://github.com/DataDog/dd-trace-py/pull/5046
- https://github.com/DataDog/dd-trace-py/pull/4943 cc @mabdinur

feat(asm): add telemetry metrics support

---

ddtrace/_tracing/_limits.py
ddtrace/contrib/elasticsearch/patch.py
releasenotes/notes/elasticsearch-body-75bfd855099e9e5a.yaml
tests/contrib/elasticsearch/test_elasticsearch.py

The elasticsearch body tag value in practice can be very large. Since the value is not truncated, it can easily result in traces exceeding the max size limit which results in dropped traces.
The proposed solution is to omit the value. This is because obfuscation logic lives in the Agent and so the body cannot be truncated as sensitive data would be leaked. No body tag is better than no trace.
Ideally the obfuscation logic should exist in the client so that the body can be truncated.

fix(elasticsearch): omit large body tag values

---

ddtrace/internal/remoteconfig/worker.py

Because Remote Configuration is still in beta, display a warning message at this moment is so intrusive to our customers. Update code to show a warning message if the customers are trying to configure RC or tracer is running in debug mode.
Update configuration message with Remote Config with a URL more accurate to configure RC

feat(rcm): update remote config warning message

---

ddtrace/appsec/_remoteconfiguration.py
ddtrace/appsec/ddwaf/__init__.py
ddtrace/internal/remoteconfig/client.py
releasenotes/notes/rcm-fix-product-callback-d4d33b56ed8e17b4.yaml
tests/appsec/test_remoteconfiguration.py

The previous code raises a KeyError in `self._products[config.product_name]` when `ASM_FEATURES` (1-click activation) disabled all ASM products (`ASM`, `ASM_DATA` and `ASM_DD` )

fix(rcm): check if the product callback exists

---

ddtrace/_tracing/_limits.py
ddtrace/contrib/elasticsearch/patch.py
releasenotes/notes/elasticsearch-body-75bfd855099e9e5a.yaml
tests/contrib/elasticsearch/test_elasticsearch.py

The elasticsearch body tag value in practice can be very large. Since the value is not truncated, it can easily result in traces exceeding the max size limit which results in dropped traces.
The proposed solution is to omit the value but include a message that notifies that the body has been omitted due to size. This is because obfuscation logic lives in the Agent and so the body cannot be truncated as sensitive data would be leaked. No body tag is better than no trace.
Ideally the obfuscation logic should exist in the client so that the body can be truncated.

fix(elasticsearch): omit large body tag values [backport #5229 to 1.9]

---

ddtrace/contrib/aws_lambda/patch.py
releasenotes/notes/fix-aws-lambda-crashing-when-timeout-has-no-root-span-4a0fdacf707709a9.yaml
tests/contrib/aws_lambda/handlers.py
tests/contrib/aws_lambda/test_aws_lambda.py
tests/snapshots/tests.contrib.aws_lambda.test_aws_lambda.test_continue_on_early_trace_ending.json

Backport of #5224 to 1.9
The root cause might be that customer is finishing all its spans, even the one provided by `datadog-lambda`. Then hitting an impending timeout, which makes the contrib `aws_lambda` to try to tag an error in the root span. After this, the contrib might try to close all unfinished spans too. Which in turn, if there's no root span, there will not be current span, therefore, adding a conditional for both root span and current span to act only if they are not `None`.
Discovered in issue #5220 
Added a unit test which finishes `aws_lambda` root span and then times out. Expecting not to crash, and to not tag the error.
User will not be getting an Impending Timeout error tagged in their root span, but they will be receiving a warning message in their logs.

fix(aws_lambda): warn when impending timeout but all traces have been finished [backport #5224]

---

ddtrace/appsec/ddwaf/__init__.py
ddtrace/appsec/ddwaf/ddwaf_types.py
ddtrace/appsec/processor.py
releasenotes/notes/fix-memory-leaks-and-segfaults-9fbdc8d66b32fb4f.yaml
tests/appsec/test_processor.py

Backport of https://github.com/DataDog/dd-trace-py/pull/5260 to 1.9

fix(asm): fix memory corruption in waf interface [backport #5260 to 1.9]

---

releasenotes/notes/address-noisy-rcm-warnings-62eb36fb64e0f28f.yaml

Adds a release note for the following change: https://github.com/DataDog/dd-trace-py/pull/5223. This fix and release note will be backported to 1.9

chore(rcm): add missing release note

---

ddtrace/contrib/psycopg/connection.py
ddtrace/contrib/psycopg/patch.py
releasenotes/notes/fix-psycopg-parse-dsn-f645bc9f056305c7.yaml

Backport of #5272 to 1.9
This change fixes an issue with DSN parsing with the psycopg2 integration, likely introduced after the refactor of #4294.
Fixes #5269.

fix: use psycopg2 DSN parser to parse DSN [backport #5272 to 1.9]

---

releasenotes/notes/address-noisy-rcm-warnings-62eb36fb64e0f28f.yaml

Backports https://github.com/DataDog/dd-trace-py/pull/5277

chore(rcm): add missing release note [backports #5277 to 1.9]

---

ddtrace/debugging/_probe/remoteconfig.py
releasenotes/notes/fix-debugger-rcm-disable-events-8e5797d5d0606f50.yaml

This change fixes the handling of disabled configuration targets in dynamic instrumentation. Because of the currently broken RCM callback signature, the disable events were not handled correctly and caused an exception to be thrown during processing of the RCM event. We fix this by working around the problematic callback signature.
Testing is performed via the backend demo job monitoring, which is what allowed the issue to surface in the first place.

fix(debugging): handle disabled probes via RCM

---

docs/releasenotes.rst

This pull request adds a helpful note to the release notes documentation on how to compile all release notes, which can be useful when cutting releases of the library.

chore(docs): add instructions on compiling release notes

---

ddtrace/_monkey.py
releasenotes/notes/patch-on-import-httplib-f98bad4b73cee387.yaml
tests/contrib/httplib/test_httplib_patch.py

Ensure http.client is patched when ddtrace.patch(httplib=True) is used.

fix(httplib): ensure httplib is patched on import [backport #5287 to 1.9]

---

.circleci/config.yml
scripts/ddtest
tests/contrib/starlette/test_starlette.py

This change resolves 2 issues that are blocking ci. Ideally both of these issues would be broken into their own PRs however we can not merge a PR unless all required checks pass. 
Downgrading riot from v1.17.0 to v0.16.0 resolves the following error: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/30677/workflows/e8202b8d-3b73-4753-9bf5-8e32ba7c8241/jobs/2081446.
```
#!/bin/bash -eo pipefail
riot run -s flake8
[notice] A new release of pip is available: 23.0 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
/home/circleci/.pyenv/versions/3.10.10/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
warnings.warn("Setuptools is replacing distutils.")
/bin/bash: line 1: flake8: command not found
Test failed with …
```

ci: pin riot and update starlette tests to pass with non-semvar versions

---

.circleci/config.yml
scripts/ddtest
tests/contrib/starlette/test_starlette.py

Backports: https://github.com/DataDog/dd-trace-py/pull/5304

ci: pin riot and fix starlette tests [backport 5304 to 1.10]

---

ddtrace/debugging/_probe/remoteconfig.py
releasenotes/notes/fix-debugger-rcm-disable-events-8e5797d5d0606f50.yaml

Backport of #5282 to 1.10
This change fixes the handling of disabled configuration targets in dynamic instrumentation. Because of the currently broken RCM callback signature, the disable events were not handled correctly and caused an exception to be thrown during processing of the RCM event. We fix this by working around the problematic callback signature.
Testing is performed via the backend demo job monitoring, which is what allowed the issue to surface in the first place.

fix(debugging): handle disabled probes via RCM [backport #5282 to 1.10]

---

ddtrace/debugging/_debugger.py
ddtrace/internal/remoteconfig/__init__.py
releasenotes/notes/rcm-fix-disable-f45787a4e6576f53.yaml
tests/contrib/gunicorn/test_gunicorn.py
tests/internal/remoteconfig/test_remoteconfig.py

Backport of #5241 to 1.10
Validate ``DD_REMOTE_CONFIGURATION_ENABLED`` environment variable is false before enable Remote Config worker and register Remote Config products.
Without this fix, Remote Config is enabled in some tests where we expected Remote Config is disabled such as:
- tests/contrib/gunicorn/test_gunicorn.py
- tests/debugging/test_debugger.py
- tests/internal/remoteconfig/test_remoteconfig.py
If an application set DD_REMOTE_CONFIGURATION_ENABLED=False, Remote Config would be activated for ASM products and DI. In that scenario, Remote Config capabilities will be wrong and will raise the below unexpected behaviors:
- Application appears in DD dashboards with RC enabled but if you try to block a IP it doesn't work
- Application appears in DD dashboards with RC enabled but if …

fix(rcm): validate remote config is enabled [backport #5241 to 1.10]

---

ddtrace/contrib/django/utils.py
releasenotes/notes/django-http-route-fix-913850f0d53a74b7.yaml
tests/contrib/django/test_django.py

Backports: https://github.com/DataDog/dd-trace-py/pull/5306

fix(django): adding http.route tag regardless of resource naming [backports #5306 to 1.10]

---

ddtrace/contrib/django/patch.py
releasenotes/notes/asm_fix_403_django_body-9adabde1f2f95c98.yaml

Fix 403 response being inadequatly replaced by datadog response block response in 1.9 branch.
This bug was automatically fixed in 1.10rc2 by suspicious request blocking PRs.
Patch to solve tickets #1131460 and #1132841

fix(asm): fix 403 response being inadequatly replaced by datadog response block response (1.9)

---

ddtrace/_monkey.py
releasenotes/notes/patch-on-import-httplib-f98bad4b73cee387.yaml
tests/contrib/httplib/test_httplib_patch.py

Backports: https://github.com/DataDog/dd-trace-py/pull/5287

fix(httplib): ensure httplib is patched on import [backport #5287 to 1.10]

---

ddtrace/appsec/iast/_ast/aspects/__init__.py
ddtrace/appsec/iast/_ast/visitor.py
ddtrace/appsec/iast/_taint_tracking/_taint_tracking.cpp
tests/appsec/iast/aspects/test_encode_decode_aspect.py

1. Add encode and decode aspect for iast. Should support all regular codecs supported by Python and all error modes
2. Fix the add operator aspect by not tainting the result if it is the same object as one of the operand
3. Add large tests for encode and decode with a large combination of codecs, error modes and input.

chore(asm): add encode and decode aspects to iast

---

ddtrace/appsec/_constants.py
ddtrace/appsec/iast/_ast/ast_patching.py
tests/appsec/iast/ast/test_ast_patching.py
tests/appsec/iast/test_env_var.py

**This is works in progress and should not be used by regular users for now**
Add environment variables to allow the user to define the list of modules to be patched by IAST.
For now:
1. _DD_IAST_PATCH_MODULES is a pass list of module name prefixes separated by commas
2. _DD_IAST_DENY_MODULES is a deny list of module name prefixes separated by commas
The longest prefix will be used to choose if a module must be patched or not.
If a prefix is in both lists, the deny list takes priority.

chore(asm): add env var for modules to be patched by iast

---

.gitignore
ddtrace/contrib/celery/app.py
releasenotes/notes/celerybeat-64b7b984461c6d12.yaml
tests/contrib/celery/base.py
tests/contrib/celery/test_integration.py

This pull request adds to the Celery integration support for `celery.beat`. This is a module that can trigger Celery tasks on a schedule. Supporting it in the integration means that users will have more visibility into the conditions under which their tasks are triggered and will get traces when Beat scheduling fails.

feat(celery): trace celery's "beat" scheduling service

---

ddtrace/tracer.py
releasenotes/notes/agent-sample-rate-fix-92c7b15bc8f2e058.yaml
tests/integration/test_integration.py

This change fixes a bug causing sample rate data from the agent not to be honored in the tracer's sampling behavior. The bug is that the sampling decision is made before the `env` tag is set. This tag is a key piece of information necessary to make sampling decisions based on responses from the agent.
The change also includes a regression test.

fix(tracing): honor sample rate set by agent

---

ddtrace/_monkey.py
tests/appsec/iast/test_processor.py
tests/contrib/django/test_django_appsec.py
tests/utils.py

Add `_iast_enabled` to `override_global_config` to be able to use it for iast tests in the same way as `_appsec_enabled`

chore(asm): use _iast_enabled in config for tests in override_global_config

---

.circleci/config.yml

https://github.com/DataDog/dd-trace-py/pull/4853 introduced aws_lambda integration and tests for this integration. However it did not update ddtrace ci circleci configurations to run the new tests.

ci(aws_lambda): run aws lambda tests in circleci

---

.riot/requirements/106972e.txt
.riot/requirements/10d623a.txt
.riot/requirements/1133f63.txt
.riot/requirements/1230ff8.txt
.riot/requirements/129b0f2.txt
.riot/requirements/12db871.txt
.riot/requirements/137147e.txt
.riot/requirements/147a097.txt
.riot/requirements/16025dc.txt
.riot/requirements/16bac29.txt
.riot/requirements/1a1c1fa.txt
.riot/requirements/1ab28fe.txt
.riot/requirements/1cdb1c5.txt
.riot/requirements/1d614be.txt
.riot/requirements/1e72d9c.txt
.riot/requirements/270f95a.txt
.riot/requirements/2d6d58d.txt
.riot/requirements/2eb00ea.txt
.riot/requirements/543c254.txt
.riot/requirements/729b5a8.txt

Revert "chore(deps): bump mysql-connector-python from 8.0.5 to 8.0.14 in /.riot/requirements"

---

ddtrace/internal/telemetry/data.py

This change avoids conflicts between different copies of the platform module when gevent monkeypatching is active.
Fixes https://github.com/DataDog/dd-trace-py/issues/5337

fix(telemetry): call platform.platform once on import and save the result

---

.readthedocs.yml

https://docs.readthedocs.io/en/stable/config-file/v2.html\#python-version
Works around https://github.com/readthedocs/readthedocs.org/issues/10173 by updating the way python version is specified in the ReadTheDocs config file.

fix(docs): stop using deprecated python.version readthedocs configuration

---

docs/configuration.rst

fix(docs): fix incorrect default note in configuration docs

---

ddtrace/appsec/trace_utils.py
releasenotes/notes/asm-missing-tag-custom-events-b4d4087a2a3ce660.yaml
tests/appsec/test_appsec_trace_utils.py

Backport to 1.9 of #5365.
The `track_custom_event()` function was not setting the `appsec.events.<event name>.track` tag, which is required for the event tracking SDK. This PR fixes this.
(cherry picked from commit aced65eef11e85eb8cc745b84125710c90cdac9d)

fix(asm): add missing `track` tag to custom events tracking [backport #5365 to 1.9]

---

ddtrace/appsec/trace_utils.py
releasenotes/notes/asm-missing-tag-custom-events-b4d4087a2a3ce660.yaml
tests/appsec/test_appsec_trace_utils.py

Backport to 1.10
The `track_custom_event()` function was not setting the `appsec.events.<event name>.track` tag, which is required for the event tracking SDK. This PR fixes this.
(cherry picked from commit aced65eef11e85eb8cc745b84125710c90cdac9d)

fix(asm): add missing track tag to custom events tracking [backport #5365 to 1.10]

---

ddtrace/contrib/celery/signals.py

The issue referenced was [resolved](https://github.com/celery/celery/pull/6374), but it actually does not apply to the bit of code it's pointing to.
Fixes https://github.com/DataDog/dd-trace-py/issues/4649
I tried removing the code referenced by the comment, and it causes the test `tests/contrib/celery/test_integration.py::CeleryDistributedTracingIntegrationTask::test_distributed_tracing_propagation_async` to fail. As far as I can tell from about an hour of investigation, the celery [fix](https://github.com/celery/celery/issues/4356) only affects "hybrid messages" (those that blend protocol 1 and 2 syntax as part of a rolling Celery upgrade), which our test suite doesn't use.

fix(celery): remove reference to github issue

---

ddtrace/contrib/falcon/middleware.py

The linked issue was resolved, but the bit of code the comment references cannot be removed without breaking existing behavior.
Resolves https://github.com/DataDog/dd-trace-py/issues/4660

fix(falcon): remove reference to github issue

---

ddtrace/appsec/iast/reporter.py
ddtrace/appsec/iast/taint_sinks/_base.py
tests/appsec/iast/test_reporter.py

Adds the `hash` and `vulnerability` values to the Vulnerability objects. Also add `__hash__` and `__eq__` to the other objects in the module to ensure comparisons are correct and we can generate hashes from them (e.g. to use as part of hashes of other objects).

fix(iast): add hash and spanid values to Vulnerability

---

ddtrace/propagation/http.py
docs/spelling_wordlist.txt
releasenotes/notes/fix-remove-w3c-tracecontext-whitespace-76e3940e11de1745.yaml
tests/tracer/test_propagation.py

Backport of #5351 to 1.9
Previously we were failing system-test `test_tracestate_ows_handling` https://github.com/DataDog/system-tests/blob/main/parametric/test_headers_tracecontext.py#L757-L835
This is because whitespace is allowed in tracecontext and we previously did not account for it. With this change we assure that we deal with whitespace by cutting it out and also ensure we do not send whitespace in our headers.

fix(propagataion): handle whitespace in W3C tracecontext [backport #5351 to 1.9]

---

.circleci/config.yml
scripts/ddtest
tests/contrib/starlette/test_starlette.py

Backport of #5304 to 1.7
This change resolves 2 issues that are blocking ci. Ideally both of these issues would be broken into their own PRs however we can not merge a PR unless all required checks pass. 
Downgrading riot from v1.17.0 to v0.16.0 resolves the following error: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/30677/workflows/e8202b8d-3b73-4753-9bf5-8e32ba7c8241/jobs/2081446.
```
#!/bin/bash -eo pipefail
riot run -s flake8
[notice] A new release of pip is available: 23.0 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
/home/circleci/.pyenv/versions/3.10.10/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
warnings.warn("Setuptools is replacing distutils.")
/bin/bash: line 1: flake8: command …
```

ci: pin riot and update starlette tests to pass with non-semvar versions [backport #5304 to 1.7]

---

ddtrace/propagation/http.py
docs/spelling_wordlist.txt
releasenotes/notes/fix-remove-w3c-tracecontext-whitespace-76e3940e11de1745.yaml
tests/tracer/test_propagation.py

Backport of #5351 to 1.10
Previously we were failing system-test `test_tracestate_ows_handling` https://github.com/DataDog/system-tests/blob/main/parametric/test_headers_tracecontext.py#L757-L835
This is because whitespace is allowed in tracecontext and we previously did not account for it. With this change we assure that we deal with whitespace by cutting it out and also ensure we do not send whitespace in our headers.

fix(propagataion): handle whitespace in W3C tracecontext [backport #5351 to 1.10]

---

ddtrace/propagation/http.py
docs/spelling_wordlist.txt
releasenotes/notes/fix-remove-w3c-tracecontext-whitespace-76e3940e11de1745.yaml
tests/tracer/test_propagation.py

Backport of #5351 to 1.7
Previously we were failing system-test `test_tracestate_ows_handling` https://github.com/DataDog/system-tests/blob/main/parametric/test_headers_tracecontext.py#L757-L835
This is because whitespace is allowed in tracecontext and we previously did not account for it. With this change we assure that we deal with whitespace by cutting it out and also ensure we do not send whitespace in our headers.

fix(propagataion): handle whitespace in W3C tracecontext [backport #5351 to 1.7]

---

.circleci/config.yml
docker-compose.yml

With #5230, we can migrate to using the testrunner image published to ghcr.io with each merge to 1.x. This would be the same image used locally with `scripts/ddtest`. The main benefit is to have arm images, whereas the Docker Hub image is only x86.

chore(ci): use testrunner for ddtest

---

ddtrace/debugging/_debugger.py
releasenotes/notes/fix-debugger-continue-wrapping-07c38a6e7dbe497f.yaml
tests/debugging/test_debugger.py

This change ensures that dynamic instrumentation can continue injecting function probes on a given module after the first failure.

fix(debugging): continue after first function probe failure

---

tests/debugging/test_uploader.py

The encoder buffer full test case remains flaky on Python 2 despite the recent refactor to use synchronised queues. This change marks the test as flaky with the xfail pytest marker to avoid the test from causing the debugging test suite to fail occasionally.

test(debugging): mark buffer full test as flaky on Python 2

---

ddtrace/_monkey.py
ddtrace/bootstrap/sitecustomize.py
ddtrace/contrib/futures/patch.py
ddtrace/contrib/futures/threading.py
releasenotes/notes/fix-futures-module-unload-e84900affff06152.yaml
riotfile.py
tests/conftest.py
tests/contrib/futures/test_futures_patch_generated.py
tests/contrib/futures/test_propagation.py
tests/utils.py

This change ensures that the concurrent.futures submodule is unloaded when doing module unloading (e.g. when gevent is detected). This ensures that the module is reloaded when needed and uses the potential new state of the cloned threading module.
The captured stacks for all the processes during the thread pool deadlock look as follows
~~~
💤🧒 Process 82315 🧵 Thread 4312286592
Thread._bootstrap (/Users/gabriele.tornetta/.pyenv/versions/3.11.2/lib/python3.11/threading.py:995)
Thread._bootstrap_inner (/Users/gabriele.tornetta/.pyenv/versions/3.11.2/lib/python3.11/threading.py:1038)
Thread.run (/Users/gabriele.tornetta/.pyenv/versions/3.11.2/lib/python3.11/threading.py:975)
_worker (/Users/gabriele.tornetta/.pyenv/versions/3.11.2/lib/python3.11/concurrent/futures/thread.py:83)
_WorkItem.run …

fix(futures): unload futures submodule during module cleanup

---

ddtrace/_tracing/_limits.py
ddtrace/contrib/elasticsearch/patch.py
releasenotes/notes/elasticsearch-body-75bfd855099e9e5a.yaml
tests/contrib/elasticsearch/test_elasticsearch.py

Backport of #5229 to 1.8
The elasticsearch body tag value in practice can be very large. Since the value is not truncated, it can easily result in traces exceeding the max size limit which results in dropped traces.
The proposed solution is to omit the value. This is because obfuscation logic lives in the Agent and so the body cannot be truncated as sensitive data would be leaked. No body tag is better than no trace.
Ideally the obfuscation logic should exist in the client so that the body can be truncated.

fix(elasticsearch): omit large body tag values [backport #5229 to 1.8]

---

ddtrace/contrib/aws_lambda/patch.py
releasenotes/notes/fix-aws-lambda-circular-dep-when-patching-in-handler-320de20015a8d5cd.yaml

Backports: https://github.com/DataDog/dd-trace-py/pull/5401

fix(aws_lambda): fix circular dependency when user handler patches modules [backport #5401 to 1.10] 

---

ddtrace/propagation/http.py
releasenotes/notes/fix-add-b3-traceid-and-spanid-padding-919b698c8008346d.yaml
tests/tracer/test_propagation.py

Backport of #4976 to 1.8
If we don't have a full length trace id or span id we should add padding of `0`s to the translated b3 hexadecimal value. For example a Datadog trace_id of `123` should be changed to `'000000000000007b'`
This issue was discoverd in the new system-tests tests: https://github.com/DataDog/system-tests/pull/691/files#r1086730900
added regression test.

fix(propagation): add padding for b3 span id and trace id [backport #4976 to 1.8]

---

ddtrace/propagation/http.py
docs/spelling_wordlist.txt
releasenotes/notes/fix-remove-w3c-tracecontext-whitespace-76e3940e11de1745.yaml
tests/tracer/test_propagation.py

Backport of #5351 to 1.8
Previously we were failing system-test `test_tracestate_ows_handling` https://github.com/DataDog/system-tests/blob/main/parametric/test_headers_tracecontext.py#L757-L835
This is because whitespace is allowed in tracecontext and we previously did not account for it. With this change we assure that we deal with whitespace by cutting it out and also ensure we do not send whitespace in our headers.

fix(propagataion): handle whitespace in W3C tracecontext [backport #5351 to 1.8]

---

.github/workflows/build_deploy.yml
.github/workflows/lib-inject-publish.yml
.github/workflows/lib-injection.yml
lib-injection/Dockerfile
lib-injection/README.md
lib-injection/copy-lib.sh
lib-injection/dl_megawheel.py
lib-injection/dl_wheels.py
lib-injection/sitecustomize.py
releasenotes/notes/lib-injection-local-install-3bbbea28517ba0f0.yaml
tests/lib-injection/dd-lib-python-init-test-django-gunicorn/Dockerfile
tests/lib-injection/dd-lib-python-init-test-django-uvicorn/Dockerfile
tests/lib-injection/dd-lib-python-init-test-django/Dockerfile

Formerly, the Kubernetes lib injection mechanism worked by including a sitecustomize.py file on the path which would execute a `pip install ddtrace==...`. This approach has a few downsides:
- Internet access required
- Application overhead at startup
- python/pip on the path doesn't have permission to install
Instead, the ddtrace package and its dependencies can be baked into the library injection image. This is achieved with the script `dl_wheels.py` which downloads wheels matching ddtrace version, Python versions, platforms and architectures. It downloads the wheels and merges them into one big directory. This works as Python is able to pick out the right binary at run-time to load, so as long as the compatible binary is present, Python will use it correctly.
The sitecustomize.py file …

fix(lib-injection): include package in image

---

ddtrace/_opentelemetry/span.py
ddtrace/span.py
tests/opentelemetry/test_span.py

Timestamps in OpenTelemetry Spans are integers and have a precession of nanoseconds ([reference](
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#timestamp), [code](https://github.com/open-telemetry/opentelemetry-python/blob/v1.0.0/opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py#L741)).
- In `Span.__init__(self, ...., start_time, ...)` start_time should be an integer with a precision of nanoseconds.
- In `Span.end(end_time)` end_time should be an integer with a precision of nanoseconds.
Opentelemetry support is unannounced so a release note is not required.

fix(opentelemetry): fix timestamps on otel spans

---

.github/workflows/build_deploy.yml
.github/workflows/lib-inject-publish.yml
.github/workflows/lib-injection.yml
lib-injection/Dockerfile
lib-injection/README.md
lib-injection/copy-lib.sh
lib-injection/dl_megawheel.py
lib-injection/sitecustomize.py
releasenotes/notes/lib-injection-local-install-3bbbea28517ba0f0.yaml
tests/lib-injection/dd-lib-python-init-test-django-gunicorn/Dockerfile
tests/lib-injection/dd-lib-python-init-test-django-uvicorn/Dockerfile
tests/lib-injection/dd-lib-python-init-test-django/Dockerfile

Formerly, the Kubernetes lib injection mechanism worked by including a sitecustomize.py file on the path which would execute a `pip install ddtrace==...`. This approach has a few downsides:
- Internet access required
- Application overhead at startup
- python/pip on the path doesn't have permission to install
Instead, the ddtrace package and its dependencies can be baked into the library injection image. This is achieved with the script `dl_wheels.py` which downloads wheels matching ddtrace version, Python versions, platforms and architectures. It downloads the wheels and merges them into one big directory. This works as Python is able to pick out the right binary at run-time to load, so as long as the compatible binary is present, Python will use it correctly.
The sitecustomize.py file …

fix(lib-injection): include package in image [backport #5410 to 1.11]

---

README.md
docs/contributing-integrations.rst

This commit contains two small changes to documentation:
1. Adds a WARNING message for installing git pre-commit hooks and instructions on how to uninstall.
2. Updates the link to the integration checklist template in the contributing to integrations document
Testing Strategy: N/A
Risks: None

chore(docs): readme.md and contributing doc updates

---

README.md
docs/contributing.rst
docs/spelling_wordlist.txt
hooks/pre-commit/run-slotscheck.sh
hooks/scripts/run-slotscheck.sh

This PR removes slotscheck from the list of precommit hooks as they have been broken for quite some time and do not provide much benefit, especially considering we always run them in CI anyway.
Contributing docs have also been edited to point out that pre-commit hooks are optional and steps to uninstall them if necessary.

chore(pre-commit hooks): remove slotscheck from pre-commit hooks

---

ddtrace/contrib/pytest/plugin.py
ddtrace/contrib/pytest_bdd/plugin.py
tests/contrib/asynctest/test_asynctest.py
tests/contrib/pytest/test_pytest.py
tests/contrib/pytest_bdd/test_pytest_bdd.py

This PR moves the CI Visibility enabling step to the `pytest_configure` hook instead of the `pytest_sessionstart` hook so that we can enable CI Visibility as early as possible in the pytest run command. See https://github.com/DataDog/dd-trace-py/pull/5446/files#r1156967374 for more context.
This is because the planned test suite level visibility for CI Visibility aims to track the entire pytest command (including test command, test modules, test functions) instead of our current test function traces. This requires the ddtrace pytest plugin to enable the CIRecorder at the earliest possible step in the pytest test command.
This functionally does not change the current behavior of the pytest plugin, since the `pytest_configure` and `pytest_sessionstart` hooks happen almost immediately after …

chore(pytest): move CI visibility initialization to start of pytest command

---

.github/workflows/build_deploy.yml

Re-usable workflows don't support being run in `steps` which isn't well documented. This manifests as
```
The workflow is not valid. .github/workflows/build_deploy.yml (Line: 222, Col: 9): Unexpected value 'secrets' .github/workflows/build_deploy.yml
```
https://github.com/DataDog/dd-trace-py/actions/runs/4612728372
Unfortunately, there isn't a really good way to verify this job before the release. Github doesn't validate the workflows until they have match criteria and are executed.

chore(lib-inject): fix build_deploy

---

ddtrace/internal/writer.py
ddtrace/tracer.py
tests/integration/test_integration.py

This change facilitates the creation of new `*Writer` classes by encapsulating the behavior of the `AgentWriter` that is specific to communication with the Datadog Agent in its own class. This leaves most of the writer's functionality, which could apply to any trace writing workload that uses HTTP, in the new `HTTPWriter` class. This change builds on the approach from https://github.com/DataDog/dd-trace-py/pull/3690.
https://github.com/DataDog/dd-trace-py/pull/5471 builds on this change to implement a new `CIVisibilityWriter` class.
This change only affects code organization, not functionality, so existing tests are sufficient to cover the risk.

chore(tracing): encapsulate agent-specific writer functionality

---

ddtrace/internal/writer.py
tests/tracer/test_writer.py

This change fixes a bug introduced in #5475 that caused headers in `AgentWriter`'s `headers` kwarg to be ignored.
I haven't included a release note because the bug this fixes was introduced after the most recent release.

fix(tracing): avoid dropping extra headers passed to AgentWriter constructor

---

.github/workflows/build_deploy.yml

Re-usable workflows don't support being run in `steps` which isn't well documented. This manifests as
```
The workflow is not valid. .github/workflows/build_deploy.yml (Line: 222, Col: 9): Unexpected value 'secrets' .github/workflows/build_deploy.yml
```
https://github.com/DataDog/dd-trace-py/actions/runs/4612728372
Unfortunately, there isn't a really good way to verify this job before the release. Github doesn't validate the workflows until they have match criteria and are executed.

chore(lib-inject): fix build_deploy [backport #5472 to 1.11]

---

.github/workflows/build_deploy.yml

In order to test build_deploy jobs a special branch pattern is added.
Github doesn't verify that jobs adhere to its workflow schema until the job matches the `on` criteria and is run. Previously this workflow only ran on release branches and on releases. This meant that there was no way to ensure the jobs actually parsed correctly before a PR was merged or a release was done.
To demonstrate the fix, a bug exists in the lib-injection job which results in
on the first commit of this PR.
A commit is pushed with the fix which shows that the workflow at least parses: 
This of course doesn't verify that the job runs successfully but it at least lets us know that it loads fine (which given Github's workflow rules and lack of documentation goes a long way).

chore(ci): add special branches for testing build_deploy, fix lib-inject job

---

.github/workflows/build_deploy.yml

In order to test build_deploy jobs a special branch pattern is added.
Github doesn't verify that jobs adhere to its workflow schema until the job matches the `on` criteria and is run. Previously this workflow only ran on release branches and on releases. This meant that there was no way to ensure the jobs actually parsed correctly before a PR was merged or a release was done.
To demonstrate the fix, a bug exists in the lib-injection job which results in
on the first commit of this PR.
A commit is pushed with the fix which shows that the workflow at least parses:
This of course doesn't verify that the job runs successfully but it at least lets us know that it loads fine (which given Github's workflow rules and lack of documentation goes a long way).

chore(ci): add special branches for testing build_deploy, fix lib-injection [backport #5486 to 1.11]

---

riotfile.py

Pin `websockets` dependency for sanic tests. This is not an issue on 1.x after #5246.

fix(ci): pin websockets in sanic tests

---

ddtrace/propagation/http.py
releasenotes/notes/fix-128bit-trace-id-propagation-b0e262f0fdf45044.yaml
tests/tracer/test_propagation.py

- Ensure datadog headers propagate 128 bit trace ids when ``DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED=False``.
- Ensure only valid `tid` values are propagated. `_dd.p.tid` tag must contain 16 hex characters.
This edge case surfaced by this system tests: https://github.com/DataDog/system-tests/blob/6168fa7e6f485e2655f81801a677356624409620/parametric/test_128_bit_traceids.py#L11

fix(tracing): ensure 128 trace ids are propagated by datadog headers

---

ddtrace/_monkey.py
ddtrace/bootstrap/sitecustomize.py
ddtrace/contrib/futures/patch.py
ddtrace/contrib/futures/threading.py
releasenotes/notes/fix-futures-module-unload-e84900affff06152.yaml
riotfile.py
tests/conftest.py
tests/contrib/futures/test_futures_patch_generated.py
tests/contrib/futures/test_propagation.py
tests/utils.py

Backports: https://github.com/DataDog/dd-trace-py/pull/5402

fix(futures): unload futures submodule during module cleanup [backport #5402 to 1.10]

---

ddtrace/propagation/http.py

Introduced by: https://github.com/DataDog/dd-trace-py/commit/da594c74bdf932b970947a380c19fbe2c3a74f6d
This bug was surfaced by the following system tests: https://github.com/DataDog/system-tests/blob/6168fa7e6f485e2655f81801a677356624409620/parametric/test_128_bit_traceids.py#L11

fix(tracing): ensure propagating errors are set correctly

---

ddtrace/propagation/http.py
releasenotes/notes/fix-128bit-trace-id-propagation-b0e262f0fdf45044.yaml
tests/tracer/test_propagation.py

Backport: https://github.com/DataDog/dd-trace-py/pull/5510

fix(tracing): ensure 128 trace ids are propagated by datadog headers [backports #5510 to 1.11]

---

.github/workflows/build-and-publish-image.yml

v0.10 of buildx by default creates images which aren't compatible with gcr/aws lambda: https://github.com/docker/buildx/releases/tag/v0.10.0.
This was causing the publish for the lib-injection images to fail when pushed to gcr:
```
2023/04/06 21:22:10 Failed to publish image, err: publish failed for registry id: gcr-datadoghq, err: PUT https://gcr.io/v2/datadoghq/dd-lib-python-init/manifests/v1.11.1: MANIFEST_INVALID: Failed to parse manifest for request "/v2/datadoghq/dd-lib-python-init/manifests/v1.11.1": Failed to deserialize application/vnd.docker.distribution.manifest.list.v2+json.
```
Pin buildx to v0.9.1, the version prior to avoid this issue.
The fix was validated by rebuilding `v1.11.1` with buildx v0.9.1 and retrying the `build-images` job which succeeded.
This change pins the …

fix(ci/lib-inject): pin buildx [backport #5496 to 1.11]

---

ddtrace/_monkey.py
ddtrace/bootstrap/sitecustomize.py
ddtrace/contrib/futures/patch.py
ddtrace/contrib/futures/threading.py
releasenotes/notes/fix-futures-module-unload-e84900affff06152.yaml
riotfile.py
tests/conftest.py
tests/contrib/futures/test_futures_patch_generated.py
tests/contrib/futures/test_propagation.py
tests/utils.py

backport https://github.com/DataDog/dd-trace-py/pull/5402

fix(futures): unload futures submodule during module cleanup [backport #5402 to 1.9]

---

docker-compose.yml

The agent wasn't previously configured to accept stats requests.

chore(testing/agent): enable stats to be sent

---

ddtrace/appsec/utils.py
tests/appsec/test_remoteconfiguration.py

Update capabilities logic: 
- if `DD_APPSEC_ENABLED` isn't set, register `ASM_ACTIVATION` capabilities
- AND, if `DD_APPSEC_ENABLED` is enabled or AppSec is enabled through Remote Config, register the products and the rest of capabilities (`ASM_IP_BLOCKING`, `ASM_DD_RULES`, `ASM_EXCLUSIONS`, etc)

fix(asm): update capabilities logic

---

riotfile.py

This PR fixes failing debugger tests after `packaging` released a new version, by pinning packaging as a dependency for debugger tests.

chore(ci): pin debugger packaging dependency

---

benchmarks/span/config.yaml
benchmarks/span/scenario.py

Benchmark creating and finishing spans with 128bit trace ids.
Output:
```
.....................
span-start: Mean +- std dev: 944 us +- 20 us
.....................
span-start-traceid128: Mean +- std dev: 1.14 ms +- 0.02 ms
.....................
span-add-tags: Mean +- std dev: 52.1 ms +- 0.6 ms
.....................
span-add-metrics: Mean +- std dev: 29.4 ms +- 0.5 ms
.....................
span-start-finish: Mean +- std dev: 1.19 ms +- 0.02 ms
.....................
span-start-finish-traceid128: Mean +- std dev: 1.28 ms +- 0.02 ms
```

chore(6to7): add microbenchmarks

---

ddtrace/internal/telemetry/writer.py
tests/telemetry/test_telemetry_metrics.py

Telemetry logs: Fix an error when Telemetry is trying to copy and clear the telemetry logs list and that generates a memory leak on Python 2.7.

fix(telemetry): python 2.7 memory leak

---

tests/profiling/collector/test_stack_asyncio.py

This change ensures that the MainThread Task with name 'None' is run long enough to be targeted by an event collector during this test.
Prior to this change the test
tests/profiling/collector/test_stack_asyncio.py::test_asyncio failed occasionally due to a race condition between event collectors (which scan threads) and collecting data about the MainThread with name=None. If the collectors didn't run in time to catch the MainThread, no CPU time would be recorded.
After this change, the StackCollector class has been updated to have a 'run count' variable, and sleeps are performed until the run time is incremented at least once, thus guaranteeing a run (for both wall_clock and cpu_time).
Sample error:
```
assert wall_time_ns[t1_name] > 0
assert wall_time_ns[t2_name] > 0
if sys.platform != …
```

chore(profiling): fix flaky test_asyncio test

---

ddtrace/internal/ci_visibility/encoder.py
tests/contrib/pytest/test_pytest.py

This PR builds on  #5489 by adding dd_origin propagation to the CIVisibilityEncoder, which is necessary for CI Visibility. This is not a new feature as this functionality is already present in the regular encoder.
This doesn't need a changelog since this is internal and is a fix to an unreleased change.

fix(ci-visibility): add dd_origin propagation to CIVisibilityEncoder

---

tests/contrib/grpc/test_grpc.py

This PR adds the `wait_for_traces` argument in the snapshot test `test_method_service` which has been repeatedly flaky.

chore(grpc): wait for traces in flaky snapshot test

---

ddtrace/appsec/trace_utils.py
ddtrace/contrib/trace_utils.py
releasenotes/notes/fix-block-request-without-span-c5ea72a06bd389b3.yaml
tests/appsec/test_appsec_trace_utils.py

Don't raise a ValueError if there is a call to `set_user` or any of the other event SDK functions that require a span, without a span, just log + regression test.
Fixes https://github.com/DataDog/dd-trace-py/issues/5485

fix: dont raise a ValueError on set_user and other Event Tracking SDK functions if there is no span

---

setup.cfg

Backport of #5428 to 1.9
This change excludes the ddtrace/__init__.py file from flake8 linting because its structure makes it such that it is hard to ensure that it simultaneously passes both linting and formatting checks. Besides, the source already makes extensive use of the noqa comment to effectively ignore linting errors on many lines.

chore(flake8): exclude ddtrace/__init__.py [backport #5428 to 1.9]

---

setup.cfg

Backport of #5428 to 1.10
This change excludes the ddtrace/__init__.py file from flake8 linting because its structure makes it such that it is hard to ensure that it simultaneously passes both linting and formatting checks. Besides, the source already makes extensive use of the noqa comment to effectively ignore linting errors on many lines.

chore(flake8): exclude ddtrace/__init__.py [backport #5428 to 1.10]

---

ddtrace/__init__.py
ddtrace/profiling/_threading.pyx
ddtrace/profiling/collector/_task.pyx
ddtrace/profiling/collector/stack.pyx
releasenotes/notes/fix-profiler-gevent-tasks-76ed862362210cb7.yaml
tests/profiling/collector/test_stack.py
tests/profiling/simple_program_gevent.py

Backport of #5338 to 1.9
This change fixes the accounting of wall and CPU time to gevent tasks by only assigning them to the main Python thread, where they are supposed to run under normal circumstances. This change also ensures that task information does not leak onto any other threads that might be running, most notably the profiler threads themselves.
The rough picture of the gevent task modelling on top of Python threads that comes with this PR is the following
This means that the `MainThread` will account for the wall time of all the tasks running within it, as well as the native thread stacks. For example, if the main, gevent-based, application runs a `sleep(2)` in the main thread, and a `sleep(1)` in a secondary thread, the `MainThread` thread would report a total of about 5 …

fix(profiling): accounting of time for gevent tasks [backport #5338 to 1.9]

---

ddtrace/internal/dogstatsd.py

The dogstatsd client as an option to provide "constant tags" that get applied to every metric produced by the client.
We are planning to use this in the OpenAI integration.

chore(internal/dogstatsd): add constant tags

---

.github/workflows/lib-injection.yml
lib-injection/Dockerfile
lib-injection/README.md
lib-injection/dl_wheels.py
lib-injection/sitecustomize.py
releasenotes/notes/lib-injection-wheels-fd40598c49a47c64.yaml

Change the installation mechanism to only download the wheels and install from the wheels on process start.
Formerly, the wheels were merged together. This causes issues as ddtrace has versioned dependencies based on the Python version. eg. bytecode 0.13 is required for Python <3.8 and 0.14 is required for >3.8. These packages were erroneously merged together.
The risk of this change is that the mechanism is back to `pip install`-ing at runtime which means:
- Performance overhead for application startup.
- Incorrect version of `pip` / `python` are used.
The image size might also be bigger as the ddtrace files aren't deduped. Hopefully the compression used by the image registries is smart enough to figure this out.
These tradeoffs are better than having a broken install however.
The …

fix(lib-injection): install from local wheels

---

ddtrace/contrib/redis/patch.py
ddtrace/internal/schema/__init__.py
ddtrace/internal/schema/span_attribute_schema.py
ddtrace/settings/config.py
tests/contrib/redis/test_redis.py
tests/contrib/redis/test_redis_cluster.py

This is the first of several changes dealing with service naming, gated behind a feature flag.  A future (feat) request will be made when the changes for service naming AND peer.service are complete.
Span service names are the wild west today, both within and across tracers, which has led to a variety of issues:
1. Lack of consistency in naming across tracer libraries in different languages (grpc-client vs grpc.client).
2. Inconsistency with operation names across integrations, even within a tracer. (requests vs httplib)
3. Too-generic service names act as naming 'sinks' (i.e. all databases for 'postgres' are represented as 'postgres')
4. Some clients (i.e. grpc) are represented as full-on services, which is generally unexpected.
The above issues occur because DataDog's features (such as …

chore(service name): initial schema for span attributes (service name)

---

ddtrace/__init__.py
ddtrace/profiling/_threading.pyx
ddtrace/profiling/collector/_task.pyx
ddtrace/profiling/collector/stack.pyx
releasenotes/notes/fix-profiler-gevent-tasks-76ed862362210cb7.yaml
tests/profiling/collector/test_stack.py
tests/profiling/simple_program_gevent.py

Backport of #5338 to 1.10
This change fixes the accounting of wall and CPU time to gevent tasks by only assigning them to the main Python thread, where they are supposed to run under normal circumstances. This change also ensures that task information does not leak onto any other threads that might be running, most notably the profiler threads themselves.
The rough picture of the gevent task modelling on top of Python threads that comes with this PR is the following
This means that the `MainThread` will account for the wall time of all the tasks running within it, as well as the native thread stacks. For example, if the main, gevent-based, application runs a `sleep(2)` in the main thread, and a `sleep(1)` in a secondary thread, the `MainThread` thread would report a total of about 5 …

fix(profiling): accounting of time for gevent tasks [backport #5338 to 1.10]

---

ddtrace/bootstrap/sitecustomize.py
releasenotes/notes/fix-update-logging-module-after-cleanup-60d90b0e11a6dc3a.yaml
tests/tracer/test_logger.py

This change ensures that the logging module can report thread information, such as thread names, correctly when a framework like gevent is used that requires modules cleanup.
Fixes #5516.

fix: update logging module on threading import

---

.github/workflows/lib-injection.yml
lib-injection/Dockerfile
lib-injection/README.md
lib-injection/dl_wheels.py
lib-injection/sitecustomize.py
releasenotes/notes/lib-injection-wheels-fd40598c49a47c64.yaml

Backports #5576 to 1.12.
Change the installation mechanism to only download the wheels and install from the wheels on process start.
Formerly, the wheels were merged together. This causes issues as ddtrace has versioned dependencies based on the Python version. eg. bytecode 0.13 is required for Python <3.8 and 0.14 is required for >3.8. These packages were erroneously merged together.
The risk of this change is that the mechanism is back to `pip install`-ing at runtime which means:
- Performance overhead for application startup.
- Incorrect version of `pip` / `python` are used.
The image size might also be bigger as the ddtrace files aren't deduped. Hopefully the compression used by the image registries is smart enough to figure this out.
These tradeoffs are better than having a broken …

fix(lib-injection): install from local wheels [backport #5576 to 1.12]

---

ddtrace/contrib/algoliasearch/patch.py
releasenotes/notes/fix-algoliasearch-tag-non-text-6a2d90b486ca2553.yaml
tests/contrib/algoliasearch/test.py

Fixes #5557.
A previous change replaced all usages of `set_tag()` with `set_tag_str()` in the algoliasearch integration, however some arguments to the patched `search` method can be non-text types (e.g. `page`, `hitsPerPage`). This PR reverts usage of `set_tag_str` back to `set_tag`.

fix(algoliasearch): use set_tag for non text type search query args

---

ddtrace/contrib/flask/wrappers.py
tests/contrib/flask/test_flask_appsec.py

IAST: Taint Flask path parameters as they are part of the request input.

chore(asm): iast taint Flask path parameters

---

.circleci/config.yml
riotfile.py

This PR fixes the bash conditional on our `run_test` pipeline jobs so that when a pipeline is manually triggered with `coverage=true` on CircleCI, coverage reporting is enabled.
Note: certain integration tests break when running with coverage enabled, for that reason they have been disabled.

chore(ci): allow coverage reporting on CircleCI

---

.circleci/config.yml

Previously we were shuffling the order of the riot venv hashes before passing them to `circleci tests split`. The problem with shuffling them is that we need a consistent ordering between each parallel circleci node so we evenly distribute all jobs. With the way it is now, we sometimes run the same venv twice or (no evidence) we might be skipping a venv entirely.
We noticed a few jobs are running more venvs than `riot list --hash-only <filter>` was giving, so we should expect some runtimes to improve.
We do not have a good way to audit all venvs which ran vs the total list of expected venvs to run, so we do not know if they were all running before, or if they are all running now.

fix(ci): sort riot venv hashes instead of shuffling them when splitting tests

---

.circleci/config.yml
riotfile.py

This PR builds off #5592 and does two things:
1. Separates the Python 3.11 Tracer riot hashes into 4 hashes each, as currently a single hash contained 4 env configurations leading to 4 test sessions. This meant that when CircleCI splits riot hashes, it assumed the Python 3.11 hash was a single test session and led to 2 parallel runners running 5 test sessions when they should have been split evenly. This now evenly splits the tracer test suites among the parallel test runners on CircleCI.
2. Increases parallelization of the tracer test suite to 11 from 8, which means that each test runner only needs to run 2 riot hashes each, greatly improving the tracer test suite duration from 13+ minutes to 7 minutes.

chore(ci): separate tracer riot hashes, increase parallelism

---

.circleci/config.yml
scripts/ddtest

A new version of riot has been released which pins virtualenv to continue to support Python 2.7 venvs.

chore(ci): bump riot to 0.17.2

---

ddtrace/profiling/collector/memalloc.py
releasenotes/notes/fix-profiler-memory-collector-reinit-after-fork-2e6fa30cb75e03a6.yaml
tests/profiling/test_main.py

This change ensures that the memalloc module of the profiler is restarted cleanly after a fork. This fixes a regression introduced by a previous change whereby error messages would be logged about failed attempts to restart the memalloc module.

fix(profiling): memalloc clean restart after fork

---

.circleci/config.yml
scripts/ddtest

Backport of #5603 to 1.11
A new version of riot has been released which pins virtualenv to continue to support Python 2.7 venvs.

chore(ci): bump riot to 0.17.2 [backport #5603 to 1.11]

---

.circleci/config.yml
scripts/ddtest

Backport of #5603 to 1.9
A new version of riot has been released which pins virtualenv to continue to support Python 2.7 venvs.

chore(ci): bump riot to 0.17.2  [backport #5603 to 1.9]

---

ddtrace/profiling/collector/memalloc.py
releasenotes/notes/fix-profiler-memory-collector-reinit-after-fork-2e6fa30cb75e03a6.yaml
tests/profiling/test_main.py

Backport of #5586 to 1.12
This change ensures that the memalloc module of the profiler is restarted cleanly after a fork. This fixes a regression introduced by a previous change whereby error messages would be logged about failed attempts to restart the memalloc module.

fix(profiling): memalloc clean restart after fork [backport #5586 to 1.12]

---

scripts/backport

1. It is possible to end up with "${1}" as an unbound variable, so let's check $# size first
2. Instead of bailing when a merge conflict is found, ask the user to resolve manually and prompt for when to continue
I was able to backport https://github.com/DataDog/dd-trace-py/pull/5624 successfully with the script when it had a merge conflict.
The script paused, waiting for me to manually resolve the conflict, and then after hitting enter it successfully completed creating the backport PR as expected.

chore(dev): improvements to backporting script

---

ddtrace/contrib/django/patch.py
releasenotes/notes/fix-django-rowcount-bug-52d4f30236049c1b.yaml
tests/contrib/django/test_django.py

Fixes #5460 
Add guard against when a Django cache result has ambiguous truth because the class doesn't implement the __bool__() function.

fix(django): guard against cache truthiness [backport #5477 to 1.12]

---

ddtrace/contrib/django/patch.py
releasenotes/notes/fix-django-rowcount-bug-52d4f30236049c1b.yaml
tests/contrib/django/test_django.py

Fixes #5460 
Add guard against when a Django cache result has ambiguous truth because the class doesn't implement the __bool__() function.

fix(django): guard against cache truthiness [backport #5477 to 1.11]

---

ddtrace/appsec/_metrics.py
tests/appsec/test_telemety.py

Remove telemetry tag until telemetry-intake service enables it

feat(asm): remove telemetry tag

---

ddtrace/internal/telemetry/writer.py
tests/telemetry/test_writer.py

Remove redundant headers, when Telemetry writer send the metrics to the agent, it attaches those headers  before send them to backend.

feat(telemetry): remove redundant headers

---

benchmarks/otel_span/scenario.py
benchmarks/span/scenario.py

Start span scenarios generates thousands of spans without calling `Span.finish()`. The handling increased memory usage results in unstable span benchmarks. This fix ensures the span processors (specifically the SpanAggregator) is recreated at the start of each benchmark. This operation ensures SpanAggregator._traces is reset between benchmarks (dereferences spans from previous benchmarks). 
Running benchmarks on 1.x produces the following output:
```
.....................
WARNING: the benchmark result may be unstable
* the standard deviation (1.31 ms) is 11% of the mean (12.5 ms)
Try to rerun the benchmark with more runs, values and/or loops.
Run 'python -m pyperf system tune' command to reduce the system jitter.
Use pyperf stats, pyperf dump and pyperf hist to analyze results.
Use …
```

chore(otel/span): reduce noise in start span benchmarks

---

.gitlab-ci.yml

This PR changes reliability env deploys to only happen when scheduled or manually triggered. Deploying on commits to the main branch noisy to see medium-term trends. Switching to a scheduled deploy should help.
Testing will be ensuring the scheduled job correctly deploys to the rel-env.

ci: switch reliability env deployments to be scheduled

---

ddtrace/contrib/kafka/patch.py
docs/spelling_wordlist.txt
releasenotes/notes/fix-kafka-subclass-b63931a9fd22ddaa.yaml
tests/contrib/kafka/test_kafka_patch.py

Backports #5545 to 1.11.
Fixes #5494.
Previously, we patched `confluent-kafka` by wrapping the `Producer/Consumer` classes with an ObjectProxy
`TracedProducer/TracedConsumer` class. However, since `confluent-kafka`'s `Producer/Consumer` classes are implemented in C and have strictly defined slots, our traced classes break for subclasses such as `AvroProducer/AvroConsumer`.
This PR fixes the issue by basing our traced classes from `confluent-kafka`'s base `Producer/Consumer` classes directly instead of using an ObjectProxy. Local testing shows that the bug from #5494 is resolved.
Before:
```
>>> from ddtrace import patch_all
>>> patch_all()
>>> from confluent_kafka.avro import AvroConsumer
>>> AvroConsumer({"group.id": 12345}, "http://localhost:8080")
<stdin>:1: DeprecationWarning: …
```

fix(kafka): trace using subclass of producer/consumer, not objectproxy [backport #5545 to 1.11]

---

ddtrace/contrib/kafka/patch.py
docs/spelling_wordlist.txt
releasenotes/notes/fix-kafka-subclass-b63931a9fd22ddaa.yaml
tests/contrib/kafka/test_kafka_patch.py

Backport #5545 to 1.12.
Fixes #5494.
Previously, we patched `confluent-kafka` by wrapping the `Producer/Consumer` classes with an ObjectProxy
`TracedProducer/TracedConsumer` class. However, since `confluent-kafka`'s `Producer/Consumer` classes are implemented in C and have strictly defined slots, our traced classes break for subclasses such as `AvroProducer/AvroConsumer`.
This PR fixes the issue by basing our traced classes from `confluent-kafka`'s base `Producer/Consumer` classes directly instead of using an ObjectProxy. Local testing shows that the bug from #5494 is resolved.
Before:
```
>>> from ddtrace import patch_all                             
>>> patch_all()                                               
>>> from confluent_kafka.avro import AvroConsumer
>>> …
```

fix(kafka): trace using subclass of producer/consumer, not objectproxy [Backport #5545 to 1.12]

---

riotfile.py

Old versions of `openai-python` use deprecated `sklearn` instead of `scikit-learn` (fixed here https://github.com/openai/openai-python/pull/227). In order to install `sklearn` in our CI venvs, we need to add an environment variable.
``` 
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [18 lines of output]
The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
rather than 'sklearn' for pip commands.
Here is how to fix this error in the main use cases:
- use 'pip install scikit-learn' rather than 'pip install sklearn'
- replace 'sklearn' by 'scikit-learn' in your pip requirements files
(requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
- if the 'sklearn' package is used by one of your dependencies,
it would be great if you take some time to track which …
```

ci(openai): allow installation of deprecated sklearn package

---

ddtrace/appsec/utils.py
ddtrace/contrib/django/utils.py
docs/spelling_wordlist.txt
releasenotes/notes/fix-extract-django-body-185084700323dce6.yaml
tests/appsec/test_tools.py
tests/contrib/django/test_django_appsec.py
tests/contrib/djangorestframework/app/views.py
tests/contrib/djangorestframework/test_appsec.py
tests/contrib/djangorestframework/test_djangorestframework.py

Backport of #5665 to 1.13
Fix extract Django request body to allow custom parser (Django Rest Framework) to work as expected when activating ASM.
Using `request.POST` or `request.data` before entering client code could parse the body with a non custom parser that would prevent future use of a custom parser. We use only `request.body`
Add a `parse_form_params` function in appsec tools with corresponding tests.
Add a test in djangorestframework to specifically check the problem was fixed.

fix(asm): body parsing for django asm [backport #5665 to 1.13]

---

ddtrace/internal/ci_visibility/encoder.py
tests/ci_visibility/test_encoder.py

This change replaces the dummy values for suite ID and session ID in code coverage payloads with real values derived from the pytest integration.

feat(pytest): put real suite and session ID onto encoded coverage spans

---

ddtrace/contrib/aioredis/patch.py
ddtrace/contrib/aredis/patch.py
ddtrace/contrib/flask_cache/utils.py
ddtrace/contrib/redis/asyncio_patch.py
ddtrace/contrib/redis/patch.py
ddtrace/contrib/trace_utils_redis.py
ddtrace/contrib/yaaredis/patch.py

Backport #5608 to 1.11.
This PR extracts redis-common helpers to outside the `ddtrace.contrib.redis` module and into
`ddtrace.contrib.trace_utils_redis.py`, as `aioredis/aredis/yaaredis` were also using the contained helper functions.
This PR should fix #5601 (see
[comment](https://github.com/DataDog/dd-trace-py/issues/5601#issuecomment-1516265155))

chore(redis): extract redis common helpers to contrib utils [backport #5608 to 1.11]

---

releasenotes/notes/fix-redis-cross-import-40590b3d41f96dcc.yaml

Backports #5710 to 1.13.
This PR adds a release note corresponding to the fix from #5608 that was not marked as a fix.

fix(redis): add release note for redis cross import fix [backport #5710 to 1.13]

---

ddtrace/contrib/aioredis/patch.py
ddtrace/contrib/aredis/patch.py
ddtrace/contrib/flask_cache/utils.py
ddtrace/contrib/redis/asyncio_patch.py
ddtrace/contrib/redis/patch.py
ddtrace/contrib/trace_utils_redis.py
ddtrace/contrib/yaaredis/patch.py

Backport #5608 to 1.13.
This PR extracts redis-common helpers to outside the `ddtrace.contrib.redis` module and into
`ddtrace.contrib.trace_utils_redis.py`, as `aioredis/aredis/yaaredis` were also using the contained helper functions.
This PR should fix #5601 (see
[comment](https://github.com/DataDog/dd-trace-py/issues/5601#issuecomment-1516265155))

chore(redis): extract redis common helpers to contrib utils [backport #5608 to 1.13]

---

ddtrace/profiling/_threading.pyx
tests/profiling/collector/test_threading.py

Patch Thread._bootstrap to retrieve and store the native thread ID (the TID) on Linux. This might come handy for determining whether a call stack is on CPU or not.

chore(profiling): add native ID to user threads

---

releasenotes/notes/fix-redis-cross-import-40590b3d41f96dcc.yaml

Backports #5710 to 1.11.
This PR adds a release note corresponding to the fix from #5608 that was not marked as a fix.

fix(redis): add release note for redis cross import fix [backport #5710 to 1.11]

---

ddtrace/bootstrap/sitecustomize.py
ddtrace/internal/module.py
tests/internal/test_module.py

Add an after module import decorator to register module hooks.

refactor(internal): after module import decorator

---

ddtrace/__init__.py
ddtrace/auto.py
ddtrace/bootstrap/sitecustomize.py
releasenotes/notes/fix-ddtrace-auto-dfcd9456dd666ca4.yaml
tests/internal/test_auto.py

Importing ddtrace.auto causes the import of ddtrace, which pollutes the module space before the sitecustomize logic can freeze the set of start-up modules and do the clean-up when required. This made the import of ddtrace.auto not behave as expected, that is as a programmatic equivalent of the ddtrace-run command. With the proposed change, we compute the initial set of modules in `ddtrace` and import that in the sitecustomize script. This way we ensure that the set is computed at the right time, regardless of how `ddtrace` is used.

fix(bootstrap): make ddtrace.auto work as expected

---

tests/contrib/celery/test_integration.py

This change fixes the 'test_beat_scheduler_tracing' flakiness, which was due to the assertions expecting celery's task scheduler to run an 'expected' number of times.
The main theme is removing magic numbers.  For instance "we don't expect it to run more than 3 extra times" was removed so the logic is "as long as it runs at least as many times as we want".

chore(celery): fix flaky 'test_beat_scheduler_tracing'

---

ddtrace/contrib/aioredis/__init__.py
ddtrace/contrib/aioredis/patch.py
ddtrace/contrib/aredis/__init__.py
ddtrace/contrib/aredis/patch.py
ddtrace/contrib/redis/__init__.py
ddtrace/contrib/redis/asyncio_patch.py
ddtrace/contrib/redis/patch.py
ddtrace/contrib/rediscluster/__init__.py
ddtrace/contrib/rediscluster/patch.py
ddtrace/contrib/trace_utils_redis.py
ddtrace/contrib/yaaredis/__init__.py
ddtrace/contrib/yaaredis/patch.py
ddtrace/internal/utils/formats.py
releasenotes/notes/feat-redis-add-cmd-max-length-config-0ec3bc9effe67244.yaml
tests/contrib/aioredis/test_aioredis.py
tests/contrib/aredis/test_aredis.py
tests/contrib/redis/test_redis.py
tests/contrib/rediscluster/test.py
tests/contrib/yaaredis/test_yaaredis.py
tests/snapshots/tests.contrib.aioredis.test_aioredis.test_cmd_max_length.json
tests/snapshots/tests.contrib.aredis.test_aredis.test_cmd_max_length.json
tests/snapshots/tests.contrib.redis.test_redis.test_custom_cmd_length.json
tests/snapshots/tests.contrib.redis.test_redis.test_custom_cmd_length_env.json
tests/snapshots/tests.contrib.rediscluster.test.test_cmd_max_length.json
tests/snapshots/tests.contrib.yaaredis.test_yaaredis.test_cmd_max_length.json

Today we truncate all redis commands to 1000 characters when setting them as tags on spans.
This PR introduces a configuration option for all redis integrations to allow configuring this truncation length.
There is no way to disable the truncation. The trace agent will continue to truncate to 2000 characters regardless of this configuration.
There are a few tests I had added but which are skipped because they don't appear to be working. They are async tests using subprocess and snapshots. The subprocess appears to be configured properly, but the test agent never receives any requests. I was unable to figure out what is wrong.

feat(redis): add redis command span tag max length configuration

---

ddtrace/tracer.py

This PR removes a redundant check in `tracer._start_span()` where the new span's traceID/parentID are set from the parent span directly or from the context object. Since the [parent span is guaranteed to have a context object which includes its traceID and spanID](https://github.com/DataDog/dd-trace-py/blob/acd0fbaa9d6dde9f60d13848a9b70cd85e6e4f2b/ddtrace/span.py#L512), this logic is redundant.
Existing tests are sufficient for this change as this is a refactor.

refactor(tracer): remove redundant parent check in _start_span

---

benchmarks/ddtrace_run/scenario.py
ddtrace/_monkey.py
ddtrace/internal/telemetry/__init__.py
ddtrace/internal/writer/writer.py
tests/telemetry/conftest.py
tests/telemetry/test_telemetry.py
tests/telemetry/test_writer.py

The telemetry_writer is used to track the state of an application.  It is responsible for sending app-started, app-closed, app-integrations-changed, and app-configurations-changed events. With the introduction of the telemetry_metrics_writer, we should rename `telemetry_writer` to something more descriptive. In this PR I am proposing renaming this variable to  `telemetry_lifecycle_writer`.

chore(telemetry): rename telemetry_writer

---

ddtrace/__init__.py
ddtrace/bootstrap/sitecustomize.py
releasenotes/notes/fix-ddtrace-auto-dfcd9456dd666ca4.yaml
tests/internal/test_auto.py

Backport of #5716 to 1.13
Importing ddtrace.auto causes the import of ddtrace, which pollutes the module space before the sitecustomize logic can freeze the set of start-up modules and do the clean-up when required. This made the import of ddtrace.auto not behave as expected, that is as a programmatic equivalent of the ddtrace-run command. With the proposed change, we compute the initial set of modules in `ddtrace` and import that in the sitecustomize script. This way we ensure that the set is computed at the right time, regardless of how `ddtrace` is used.

fix(bootstrap): make ddtrace.auto work as expected [backport #5716 to 1.13]

---

ddtrace/__init__.py
ddtrace/bootstrap/sitecustomize.py
releasenotes/notes/fix-ddtrace-auto-dfcd9456dd666ca4.yaml
tests/internal/test_auto.py

Backport of #5716 to 1.12
Importing ddtrace.auto causes the import of ddtrace, which pollutes the module space before the sitecustomize logic can freeze the set of start-up modules and do the clean-up when required. This made the import of ddtrace.auto not behave as expected, that is as a programmatic equivalent of the ddtrace-run command. With the proposed change, we compute the initial set of modules in `ddtrace` and import that in the sitecustomize script. This way we ensure that the set is computed at the right time, regardless of how `ddtrace` is used.

fix(bootstrap): make ddtrace.auto work as expected [backport #5716 to 1.12]

---

ddtrace/bootstrap/sitecustomize.py
releasenotes/notes/fix-keep-copyreg-29c28bcc854e13bb.yaml

Some frameworks might extend the pickle capabilities by interacting with the copyreg module. Unloading it as part of the module clean-up process causes issues, so we add it to the list of modules to keep.
Fixes: #5742 
The issue does not occur when the library is installed in edit mode, which makes it tricky to test with `riot` in our CI. Manual testing shows that issue that prompted this fix is resolved.
Because we don't have a reproducer in our test suite we are left vulnerable to regressions.

fix: keep the copyreg module

---

ddtrace/bootstrap/sitecustomize.py
releasenotes/notes/fix-profiler-segfault-in-protobuf-apps-032558829864cdfe.yaml
tests/profiling/test_main.py

Backport of #5747 to 1.13
When cleaning up the modules as part of the support for gevent, we also unload google.protobuf. However, starting with version 4.21, the new default upb backend does not tolerate being unloaded, which resulted in segfaults in applications with a runtime dependency on protobuf.

fix(profiler): do not unload google.protobuf in module clean-up [backport #5747 to 1.13]

---

ddtrace/bootstrap/sitecustomize.py
releasenotes/notes/fix-keep-copyreg-29c28bcc854e13bb.yaml

Backport of #5750 to 1.12
Some frameworks might extend the pickle capabilities by interacting with the copyreg module. Unloading it as part of the module clean-up process causes issues, so we add it to the list of modules to keep.
Fixes: #5742 
The issue does not occur when the library is installed in edit mode, which makes it tricky to test with `riot` in our CI. Manual testing shows that issue that prompted this fix is resolved.
Because we don't have a reproducer in our test suite we are left vulnerable to regressions.

fix: keep the copyreg module [backport #5750 to 1.12]

---

ddtrace/bootstrap/sitecustomize.py
releasenotes/notes/fix-profiler-segfault-in-protobuf-apps-032558829864cdfe.yaml
tests/profiling/test_main.py

Backport of #5747 to 1.12
When cleaning up the modules as part of the support for gevent, we also unload google.protobuf. However, starting with version 4.21, the new default upb backend does not tolerate being unloaded, which resulted in segfaults in applications with a runtime dependency on protobuf.

fix(profiler): do not unload google.protobuf in module clean-up [backport #5747 to 1.12]

---

.github/workflows/requirements-locks.yml

This PR modifies a step in the requirements lockfile check github action, which was to globally specify all python interpreters required for the riot lockfile check. Since this action runs using the testrunner docker image which already has the required interpreters, this step was changed to only specify the minor version which should still automatically match with the testrunner's installed python versions, making this more resistant to changes in the testrunner.

chore(ci): fix python interpreter versions in lockfile github action

---

.github/workflows/test_frameworks.yml

ci: pin urllib3 to 1.26.15 for starlette to fix failing CI

---

ddtrace/internal/telemetry/writer.py

`conn` will be uninitialized if `ddtrace.internal.agent.get_connection()` raises an exception. Calling method on an initalized object raises an `UnboundLocalError`.
This fix resolves an edge case in an internal feature. A release note is not required.

fix(telemetry): resolve unboundlocalerror raised by get_connection

---

ddtrace/bootstrap/sitecustomize.py
releasenotes/notes/fix-keep-copyreg-29c28bcc854e13bb.yaml

Backport of #5750 to 1.13
Some frameworks might extend the pickle capabilities by interacting with the copyreg module. Unloading it as part of the module clean-up process causes issues, so we add it to the list of modules to keep.
Fixes: #5742 
The issue does not occur when the library is installed in edit mode, which makes it tricky to test with `riot` in our CI. Manual testing shows that issue that prompted this fix is resolved.
Because we don't have a reproducer in our test suite we are left vulnerable to regressions.

fix: keep the copyreg module [backport #5750 to 1.13]

---

ddtrace/contrib/openai/patch.py
tests/contrib/openai/cassettes/chat_completion_streamed_async.yaml
tests/contrib/openai/test_openai.py
tests/snapshots/tests.contrib.openai.test_openai.test_achat_completion.json
tests/snapshots/tests.contrib.openai.test_openai.test_acompletion.json
tests/snapshots/tests.contrib.openai.test_openai.test_aembedding.json
tests/snapshots/tests.contrib.openai.test_openai.test_chat_completion.json
tests/snapshots/tests.contrib.openai.test_openai.test_chat_completion_async_stream.json
tests/snapshots/tests.contrib.openai.test_openai.test_completion.json
tests/snapshots/tests.contrib.openai.test_openai.test_embedding.json
tests/snapshots/tests.contrib.openai.test_openai.test_integration_async.json
tests/snapshots/tests.contrib.openai.test_openai.test_integration_sync.json
tests/snapshots/tests.contrib.openai.test_openai.test_misuse.json

Support tagging traces, logs and metrics with the API key. This enables OpenAI admins and users to see usage per-API key. The API key is obfuscated to include only the last 4 characters which is what OpenAI displays in their UI.
Note: with this change, we no longer trace streamed responses and instead include that in the initial openai request/response span. This was done since having the stream captured in the request span itself is likely more useful to users than having a disjointed trace. For example:
Previous behavior:
Trace behavior after this change:
The one risk is if a user never consumers the stream generator, then this span will never be finished. This is a low risk, but should be addressed as a future step.

feat(openai): add support for tagging by API key

---

ddtrace/contrib/openai/patch.py
tests/contrib/openai/cassettes/chat_completion_streamed_async.yaml
tests/contrib/openai/test_openai.py
tests/snapshots/tests.contrib.openai.test_openai.test_achat_completion.json
tests/snapshots/tests.contrib.openai.test_openai.test_acompletion.json
tests/snapshots/tests.contrib.openai.test_openai.test_aembedding.json
tests/snapshots/tests.contrib.openai.test_openai.test_chat_completion.json
tests/snapshots/tests.contrib.openai.test_openai.test_chat_completion_async_stream.json
tests/snapshots/tests.contrib.openai.test_openai.test_completion.json
tests/snapshots/tests.contrib.openai.test_openai.test_embedding.json
tests/snapshots/tests.contrib.openai.test_openai.test_integration_async.json
tests/snapshots/tests.contrib.openai.test_openai.test_integration_sync.json
tests/snapshots/tests.contrib.openai.test_openai.test_misuse.json

This PR backports #5757 to 1.13.
Support tagging traces, logs and metrics with the API key. This enables OpenAI admins and users to see usage per-API key. The API key is obfuscated to include only the last 4 characters which is what OpenAI displays in their UI.
Note: with this change, we no longer trace streamed responses and instead include that in the initial openai request/response span. This was done since having the stream captured in the request span itself is likely more useful to users than having a disjointed trace. For example: Previous behavior:
Trace behavior after this change:

feat(openai): add support for tagging by API key [backport #5757 to 1.13]

---

.github/workflows/test_frameworks.yml

ci: pin urllib3 to 1.26.15 for starlette to fix failing CI [backport #5766 to 1.12]

---

.github/workflows/test_frameworks.yml

ci: pin urllib3 to 1.26.15 for starlette to fix failing CI [backport #5766 to 1.13]

---

ddtrace/bootstrap/sitecustomize.py
releasenotes/notes/fix-profiler-segfault-in-protobuf-apps-032558829864cdfe.yaml
tests/profiling/test_main.py

Backport of #5747 to 1.9
When cleaning up the modules as part of the support for gevent, we also unload google.protobuf. However, starting with version 4.21, the new default upb backend does not tolerate being unloaded, which resulted in segfaults in applications with a runtime dependency on protobuf.

fix(profiler): do not unload google.protobuf in module clean-up [backport #5747 to 1.9]

---

.github/workflows/test_frameworks.yml

ci: pin urllib3 to 1.26.15 for starlette to fix failing CI [backport #5766 to 1.9]

---

ddtrace/bootstrap/sitecustomize.py
releasenotes/notes/fix-profiler-segfault-in-protobuf-apps-032558829864cdfe.yaml
tests/profiling/test_main.py

Backport of #5747 to 1.11
When cleaning up the modules as part of the support for gevent, we also unload google.protobuf. However, starting with version 4.21, the new default upb backend does not tolerate being unloaded, which resulted in segfaults in applications with a runtime dependency on protobuf.

fix(profiler): do not unload google.protobuf in module clean-up [backport #5747 to 1.11]
