.github/workflows/test_frameworks.yml

ci: pin urllib3 to 1.26.15 for starlette to fix failing CI [backport #5766 to 1.10]

---

.github/workflows/test_frameworks.yml

ci: pin urllib3 to 1.26.15 for starlette to fix failing CI [backport #5766 to 1.11]

---

ddtrace/contrib/django/patch.py
releasenotes/notes/guard-against-django-cache-result-errors-6ed2fe989f96eaf9.yaml
tests/contrib/django/test_django.py

Backport of #5723 to 1.12
Patch for issue: https://github.com/DataDog/dd-trace-py/issues/5460. Added try except block to catch potential errors that may occur. Added tests to verify patch works as intended to catch errors.

fix: guard against django cache result errors when setting row_count [backport #5723 to 1.12]

---

ddtrace/contrib/django/patch.py
releasenotes/notes/guard-against-django-cache-result-errors-6ed2fe989f96eaf9.yaml
tests/contrib/django/test_django.py

Backport of #5723 to 1.13
Patch for issue: https://github.com/DataDog/dd-trace-py/issues/5460. Added try except block to catch potential errors that may occur. Added tests to verify patch works as intended to catch errors.

fix: guard against django cache result errors when setting row_count [backport #5723 to 1.13]

---

.github/workflows/test_frameworks.yml
tests/debugging/exploration/_config.py
tests/debugging/exploration/_coverage.py
tests/debugging/exploration/_profiler.py
tests/debugging/exploration/debugger.py

Backport of #5600 to 1.9
We reduce the capture limits in probe installed during exploration testing to reduce the overhead introduced and allow test runs to complete more quickly. The main objective of the exploration tests is to validate the bytecode manipulations, so this does not affect the usefulness of the test runs.

ci(debugging): reduce exploration limits [backport #5600 to 1.9]

---

ddtrace/internal/_encoding.pyx
releasenotes/notes/fix-encoding-exception-ff50914f97554744.yaml
tests/tracer/test_encoders.py

Backport of #5797 to 1.12
If we end up with a meta value that is not a string it can raise a cryptic error that doesn't help deubgging.
This change introduces a new error message that includes the `repr(span)` that caused the issue.
This change will *not* include the meta for the span, but having the span name should help narrow things down.

fix(internal): introduce better error logging when we cannot pack a span [backport #5797 to 1.12]

---

ddtrace/internal/_encoding.pyx
releasenotes/notes/fix-encoding-exception-ff50914f97554744.yaml
tests/tracer/test_encoders.py

Backport of #5797 to 1.13
If we end up with a meta value that is not a string it can raise a cryptic error that doesn't help deubgging.
This change introduces a new error message that includes the `repr(span)` that caused the issue.
This change will *not* include the meta for the span, but having the span name should help narrow things down.

fix(internal): introduce better error logging when we cannot pack a span [backport #5797 to 1.13]

---

ddtrace/internal/utils/http.py
tests/internal/test_utils_http.py

We use the get_connection helper in the connector context manager to ensure that we use the same connection construction logic across all internal products.

refactor(internal): use get_connection in connector

---

.gitlab/benchmarks.yml

Plenty of flask-simple jobs are failing on timeout, e.g. https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-py/-/jobs/264295530
This is a temporary fix to reduce failures count until flask benchmark execution is parallelized.

chore(ci): increase flask-simple timeout

---

ddtrace/span.py
releasenotes/notes/bump-traceback-limit-4b7702bc8f771d65.yaml

Currently we truncate the error.stack tag to 20 frames. Some ddtrace integrations (ex: flask) can produce stacktraces that add almost 10-15 frames that reference the ddtrace libraries. A limit of 20 frames is clearly not enough visibility to debug errors in customers application code. This PR bumps the limit to 30 (another arbitrary value).

chore(span): bump traceback limit from 20 to 30

---

ddtrace/appsec/processor.py
releasenotes/notes/fix-appsec-request-context-cleanup-afd26509cfbf2cc5.yaml
tests/appsec/test_processor.py

Backport of #5813 to 1.12
There is a possible code path that could cause us to not clean up the asm request context added to the span context.
If this occurs, then we will get an error encoding because `span.context._meta` is only meant to hold string values.
This is a short term mitigation to ensure we always cleanup the context manager added to `span.context._meta`, but we should consider an alternative approach which doesn't rely on `span.context._meta`.

fix(appsec): always cleanup any created asm request context managers [backport #5813 to 1.12]

---

ddtrace/contrib/openai/__init__.py

This PR fixes the openai patch docs to include the api_key span tag, as well as adding a missing `openai.organization.` to the org name and org id span tags.

fix(openai): update metric names in docs

---

ddtrace/appsec/_asm_request_context.py
ddtrace/appsec/processor.py
releasenotes/notes/fix-asm-request-context-partial-flushing-7c45aaf55e836261.yaml
tests/appsec/test_processor.py

Backport of #5822 to 1.12
Remove the use of span context._meta to store information about context registration.
update tests for asm request context to unit test the new registration process.

fix(asm): simplify asm request context span registration [backport #5822 to 1.12]

---

ddtrace/appsec/_asm_request_context.py
ddtrace/appsec/processor.py
releasenotes/notes/fix-asm-request-context-partial-flushing-7c45aaf55e836261.yaml
tests/appsec/test_processor.py

Backport of #5822 to 1.13
Remove the use of span context._meta to store information about context registration.
update tests for asm request context to unit test the new registration process.

fix(asm): simplify asm request context span registration [backport #5822 to 1.13]

---

ddtrace/contrib/asgi/middleware.py
tests/contrib/asgi/test_asgi.py
tests/contrib/fastapi/test_fastapi.py
tests/contrib/starlette/test_starlette.py

Backports #5849 to 1.13.
Addresses:
https://github.com/DataDog/dd-trace-py/pull/5818#issuecomment-1543604812 Partially reverts: https://github.com/DataDog/dd-trace-py/pull/5818
We will need to backport this fix to 1.9, 1.10, 1.11, 1.12 and 1.13 release lines.
This regression is unreleased so a release note is not required.

chore(asgi): revert regression [backport #5849 to 1.13]

---

ddtrace/span.py
releasenotes/notes/bump-traceback-limit-4b7702bc8f771d65.yaml

Currently we truncate the error.stack tag to 20 frames. Some ddtrace integrations (ex: flask) can produce stacktraces that add almost 10-15 frames that reference the ddtrace libraries. A limit of 20 frames is clearly not enough visibility to debug errors in customers application code. This PR bumps the limit to 30 (another arbitrary value).

chore(span): bump traceback limit from 20 to 30 (backports #5807 to 1.13)

---

ddtrace/internal/ci_visibility/recorder.py
ddtrace/settings/config.py
releasenotes/notes/fix-ci-app-api-call-12f848d25f93d02d.yaml
tests/ci_visibility/test_ci_visibility.py

Backport of #5872 to 1.13
CI App: Remove extra requests performed if ``DD_CIVISIBILITY_ITR_ENABLED`` env var not set or False.

fix(ci-visibility): remove extra requests performed if env var not set [backport #5872 to 1.13]

---

ddtrace/contrib/kafka/patch.py
releasenotes/notes/pass-args-kwargs-to-kafka-f3ca8128a2c4d612.yaml
tests/contrib/kafka/test_kafka.py

Pass arbitrary positional and keyword arguments to `TracedConsumer` so as to allow client to configure their instance of `KafkaConsumer`. This is, for example, [required for configuring a logger](https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#kafka-client-configuration) internal to the Consumer, where a logger can only be passed as a kwarg.
Currently, passing such a kwarg leads to the following error:
```TypeError: TracedConsumer.__init__() got an unexpected keyword argument 'logger'```
Related to issue [#5837](https://github.com/DataDog/dd-trace-py/issues/5873)
---

fix(kafka): pass *args, **kwargs to TracedConsumer.__init__

---

ddtrace/contrib/kafka/patch.py
releasenotes/notes/pass-args-kwargs-to-kafka-f3ca8128a2c4d612.yaml
tests/contrib/kafka/test_kafka.py

Backports #5887 to 1.12
Pass arbitrary positional and keyword arguments to `TracedConsumer` so as to allow client to configure their instance of `KafkaConsumer`. This is, for example, [required for configuring a
logger](https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#kafka-client-configuration) internal to the Consumer, where a logger can only be passed as a kwarg.
Currently, passing such a kwarg leads to the following error:
```TypeError: TracedConsumer.__init__() got an unexpected keyword argument 'logger'```
Related to issue [#5837](https://github.com/DataDog/dd-trace-py/issues/5873)
---

fix(kafka): pass *args, **kwargs to TracedConsumer.__init__ [backport #5887 to 1.12]

---

.github/workflows/test_frameworks.yml
ddtrace/bootstrap/sitecustomize.py
releasenotes/notes/sanic-fix-is-pattern-check-c6e4109e933bf37f.yaml

When gevent is installed (or
`DD_UNLOAD_MODULES_FROM_SITECUSTOMIZE=auto`), all modules imported by [ddtrace.bootstrap.sitecustomize](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/bootstrap/sitecustomize.py#L91) are unloaded from sys.modules (except for a small [exclude list](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/bootstrap/sitecustomize.py#L103-L113)).
Currently the [typing
module](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/bootstrap/sitecustomize.py#L110) is excluded from module unloading but re is NOT. This causes [isinstance(some_re_pattern,
typing.Pattern)](https://github.com/sanic-org/sanic-routing/blob/main/sanic_routing/router.py#L289) to return False (here typing holds a stale reference to …

fix(sanic): avoids unloading re module when gevent is installed (backport #5867 to 1.13)

---

.github/workflows/test_frameworks.yml
ddtrace/bootstrap/sitecustomize.py
releasenotes/notes/sanic-fix-is-pattern-check-c6e4109e933bf37f.yaml

When gevent is installed (or
`DD_UNLOAD_MODULES_FROM_SITECUSTOMIZE=auto`), all modules imported by [ddtrace.bootstrap.sitecustomize](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/bootstrap/sitecustomize.py#L91) are unloaded from sys.modules (except for a small [exclude list](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/bootstrap/sitecustomize.py#L103-L113)).
Currently the [typing
module](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/bootstrap/sitecustomize.py#L110) is excluded from module unloading but re is NOT. This causes [isinstance(some_re_pattern,
typing.Pattern)](https://github.com/sanic-org/sanic-routing/blob/main/sanic_routing/router.py#L289) to return False (here typing holds a stale reference to …

fix(sanic): avoids unloading re module when gevent is installed (backport #5867 to 1.10)

---

.github/workflows/test_frameworks.yml
ddtrace/bootstrap/sitecustomize.py
releasenotes/notes/sanic-fix-is-pattern-check-c6e4109e933bf37f.yaml

When gevent is installed (or
`DD_UNLOAD_MODULES_FROM_SITECUSTOMIZE=auto`), all modules imported by [ddtrace.bootstrap.sitecustomize](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/bootstrap/sitecustomize.py#L91) are unloaded from sys.modules (except for a small [exclude list](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/bootstrap/sitecustomize.py#L103-L113)).
Currently the [typing
module](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/bootstrap/sitecustomize.py#L110) is excluded from module unloading but re is NOT. This causes [isinstance(some_re_pattern,
typing.Pattern)](https://github.com/sanic-org/sanic-routing/blob/main/sanic_routing/router.py#L289) to return False (here typing holds a stale reference to …

fix(sanic): avoids unloading re module when gevent is installed (backport #5867 to 1.9)

---

.github/workflows/test_frameworks.yml
ddtrace/bootstrap/sitecustomize.py
releasenotes/notes/sanic-fix-is-pattern-check-c6e4109e933bf37f.yaml

When gevent is installed (or
`DD_UNLOAD_MODULES_FROM_SITECUSTOMIZE=auto`), all modules imported by [ddtrace.bootstrap.sitecustomize](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/bootstrap/sitecustomize.py#L91) are unloaded from sys.modules (except for a small [exclude list](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/bootstrap/sitecustomize.py#L103-L113)).
Currently the [typing
module](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/bootstrap/sitecustomize.py#L110) is excluded from module unloading but re is NOT. This causes [isinstance(some_re_pattern,
typing.Pattern)](https://github.com/sanic-org/sanic-routing/blob/main/sanic_routing/router.py#L289) to return False (here typing holds a stale reference to …

fix(sanic): avoids unloading re module when gevent is installed (backport #5867 to 1.12)

---

ddtrace/contrib/wsgi/wsgi.py
releasenotes/notes/fix-wsgi-iterable-len-14777de93b723b00.yaml
tests/contrib/wsgi/test_wsgi.py

Streaming responses with [waitress](https://github.com/Pylons/waitress) is not supported by the wsgi middleware. This incompatibility was introduced by the following commit:
https://github.com/DataDog/dd-trace-py/commit/7ce49bd78b0d510766fc5db12756a8840724febc.
1. `pip install "waitress>=2.1.2" "ddtrace==1.13.0" "Flask>=2.2.4,<2.3.0"`
2. Create a flask application and add an endpoint that streams a response:
app.py: ``` from waitress import serve from flask import Flask
app = Flask(__name__)
@app.route('/large.csv')
def generate_large_csv():
def generate():
for row in [1, 2, 3, 4]:
yield f"{row}\n"
return app.response_class(generate(), mimetype='text/csv')
@app.route("/")
def hello():
return "Hello, World!"
serve(app, listen='*:8080')
```
3. Run ` python path/to/flask_app/app.py`
3. Run …

fix(wsgi): ensure traced iterable does not implement __len__ (backport #5858 to 1.12)

---

ddtrace/contrib/wsgi/wsgi.py
releasenotes/notes/fix-wsgi-iterable-len-14777de93b723b00.yaml
tests/contrib/wsgi/test_wsgi.py

Streaming responses with [waitress](https://github.com/Pylons/waitress) is not supported by the wsgi middleware. This incompatibility was introduced by the following commit:
https://github.com/DataDog/dd-trace-py/commit/7ce49bd78b0d510766fc5db12756a8840724febc.
1. `pip install "waitress>=2.1.2" "ddtrace==1.13.0" "Flask>=2.2.4,<2.3.0"`
2. Create a flask application and add an endpoint that streams a response:
app.py: ``` from waitress import serve from flask import Flask
app = Flask(__name__)
@app.route('/large.csv')
def generate_large_csv():
def generate():
for row in [1, 2, 3, 4]:
yield f"{row}\n"
return app.response_class(generate(), mimetype='text/csv')
@app.route("/")
def hello():
return "Hello, World!"
serve(app, listen='*:8080')
```
3. Run ` python path/to/flask_app/app.py`
3. Run …

fix(wsgi): ensure traced iterable does not implement __len__ (backport #5858 to 1.13)

---

ddtrace/contrib/openai/patch.py
docs/spelling_wordlist.txt
releasenotes/notes/fix-openai-embeddings-input-7feb1198fabac31b.yaml
tests/contrib/openai/test_openai.py
tests/snapshots/tests.contrib.openai.test_openai.test_embedding_array_of_token_arrays.json
tests/snapshots/tests.contrib.openai.test_openai.test_embedding_string_array.json
tests/snapshots/tests.contrib.openai.test_openai.test_embedding_token_array.json

Backports #5890 to 1.14.
Fixes #5884.
This PR adds handling for non-string request input params for the `Embeddings.create()` method. This API method accepts strings, array of strings, as well as token arrays (list of ints) and arrays of token arrays (list of list of ints), but the previous implementation only accounted for strings and array of strings. Token arrays or arrays of token arrays being passed in as arguments would then cause errors as the traced request handler for the Embeddings endpoint did not account for non-string types.

fix(openai): allow token inputs for Embeddings endpoint [backport #5890 to 1.14]

---

lib-injection/sitecustomize.py
releasenotes/notes/lib-inject-fix-offline-0349ef25100f5420.yaml

pip will by default always try to check the internet for packages even when a --find-links option is specified.
This results in a very slow install when there is no internet available in the container:
```
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffffa2e8b070>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/ddtrace/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffffa2e89120>: Failed to establish a new connection: [Errno -2] Name or service not …
```

fix(lib-injection): always install from local packages (backport #5758 to 1.13)

---

lib-injection/sitecustomize.py
releasenotes/notes/lib-inject-fix-offline-0349ef25100f5420.yaml

pip will by default always try to check the internet for packages even when a --find-links option is specified.
This results in a very slow install when there is no internet available in the container:
```
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffffa2e8b070>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/ddtrace/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffffa2e89120>: Failed to establish a new connection: [Errno -2] Name or service not …
```

fix(lib-injection): always install from local packages (backpirt #5758 to 1.12)

---

.circleci/config.yml
ddtrace/internal/telemetry/writer.py
releasenotes/notes/gunicorn-support-debugmode-py27-74c0b8ca63cc7d9f.yaml
tests/contrib/gunicorn/test_gunicorn.py
tests/contrib/gunicorn/wsgi_mw_app.py

fix(telemetry): ensures telemetry threads do block gunicorn workers (backport #5882 to 1.13)

---

.circleci/config.yml
ddtrace/internal/telemetry/writer.py
releasenotes/notes/gunicorn-support-debugmode-py27-74c0b8ca63cc7d9f.yaml
tests/contrib/gunicorn/test_gunicorn.py
tests/contrib/gunicorn/wsgi_mw_app.py

fix(telemetry): ensures telemetry threads do block gunicorn workers (backport #5882 to 1.11)

---

.circleci/config.yml
ddtrace/internal/telemetry/writer.py
releasenotes/notes/gunicorn-support-debugmode-py27-74c0b8ca63cc7d9f.yaml
tests/contrib/gunicorn/test_gunicorn.py
tests/contrib/gunicorn/wsgi_mw_app.py

fix(telemetry): ensures telemetry threads do block gunicorn workers (backport #5882 to 1.10)

---

.circleci/config.yml
ddtrace/internal/telemetry/writer.py
releasenotes/notes/gunicorn-support-debugmode-py27-74c0b8ca63cc7d9f.yaml
tests/contrib/gunicorn/test_gunicorn.py
tests/contrib/gunicorn/wsgi_mw_app.py

fix(telemetry): ensures telemetry threads do block gunicorn workers (backport #5882 to 1.12)

---

.circleci/config.yml
ddtrace/internal/telemetry/writer.py
releasenotes/notes/gunicorn-support-debugmode-py27-74c0b8ca63cc7d9f.yaml
tests/contrib/gunicorn/test_gunicorn.py
tests/contrib/gunicorn/wsgi_mw_app.py

fix(telemetry): ensures telemetry threads do block gunicorn workers (backport #5882 to 1.14)

---

.github/PULL_REQUEST_TEMPLATE.md
benchmarks/flask_simple/config.yaml

This PR disables benchmarks scenarios that produce unstable results. These benchmarks report random performance improvements and regressions. We should reenable these benchmarks after a root cause of the instability is identified.

ci(benchmarks): disable unstable benchmarks

---

.circleci/config.yml
ddtrace/internal/telemetry/writer.py
releasenotes/notes/gunicorn-support-debugmode-py27-74c0b8ca63cc7d9f.yaml
tests/contrib/gunicorn/test_gunicorn.py
tests/contrib/gunicorn/wsgi_mw_app.py

fix(telemetry): ensures telemetry threads do not block gunicorn workers (backport #5882 to 1.9)

---

ddtrace/contrib/openai/patch.py
docs/spelling_wordlist.txt
releasenotes/notes/fix-openai-embeddings-input-7feb1198fabac31b.yaml
tests/contrib/openai/test_openai.py
tests/snapshots/tests.contrib.openai.test_openai.test_embedding_array_of_token_arrays.json
tests/snapshots/tests.contrib.openai.test_openai.test_embedding_string_array.json
tests/snapshots/tests.contrib.openai.test_openai.test_embedding_token_array.json

Backports #5890 to 1.13.
Fixes #5884.
This PR adds handling for non-string request input params for the `Embeddings.create()` method. This API method accepts strings, array of strings, as well as token arrays (list of ints) and arrays of token arrays (list of list of ints), but the previous implementation only accounted for strings and array of strings. Token arrays or arrays of token arrays being passed in as arguments would then cause errors as the traced request handler for the Embeddings endpoint did not account for non-string types.

fix(openai): allow token inputs for Embeddings endpoint [backport #5890 to 1.13]

---

.circleci/config.yml

Currently all gunicorn tests are run 4 times ([link](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/36115/workflows/ba450883-49a6-41a8-86ba-c9642e76570e/jobs/2438853)).  
This change ensure gunicorn tests are split up across four runners and each test is run once.

ci(gunicorn): ensure tests are correctly parallelized

---

.circleci/config.yml

Backport of #5922 to 1.14
Currently all gunicorn tests are run 4 times ([link](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/36115/workflows/ba450883-49a6-41a8-86ba-c9642e76570e/jobs/2438853)).  
This change ensure gunicorn tests are split up across four runners and each test is run once.

ci(gunicorn): ensure tests are correctly parallelized [backport #5922 to 1.14]

---

releasenotes/notes/pass-args-kwargs-to-kafka-f3ca8128a2c4d612.yaml

Blocks the release of v1.12.9, v1.13.4, and 1.14.0
Introduced by: https://github.com/DataDog/dd-trace-py/pull/5887

docs: fix formatting and spelling in kafka release note

---

releasenotes/notes/pass-args-kwargs-to-kafka-f3ca8128a2c4d612.yaml

Backport of #5931 to 1.12
Blocks the release of v1.12.9, v1.13.4, and 1.14.0
Introduced by: https://github.com/DataDog/dd-trace-py/pull/5887

docs: fix formatting and spelling in kafka release note [backport #5931 to 1.12]

---

releasenotes/notes/pass-args-kwargs-to-kafka-f3ca8128a2c4d612.yaml

Backport of #5931 to 1.13
Blocks the release of v1.12.9, v1.13.4, and 1.14.0
Introduced by: https://github.com/DataDog/dd-trace-py/pull/5887

docs: fix formatting and spelling in kafka release note [backport #5931 to 1.13]

---

.circleci/config.yml

Backport of #5922 to 1.13
Currently all gunicorn tests are run 4 times ([link](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/36115/workflows/ba450883-49a6-41a8-86ba-c9642e76570e/jobs/2438853)).  
This change ensure gunicorn tests are split up across four runners and each test is run once.

ci(gunicorn): ensure tests are correctly parallelized [backport #5922 to 1.13]

---

ddtrace/ext/sql.py
docs/spelling_wordlist.txt
releasenotes/notes/fix-tracer-parse-pg-dsn-take2-7ef89362545b2721.yaml
tests/contrib/psycopg/test_psycopg.py
tests/contrib/psycopg2/test_psycopg.py

Resolves: https://github.com/DataDog/dd-trace-py/issues/5926, https://github.com/DataDog/dd-trace-py/issues/5823
This change re-introduces the use of the psycopg's parse_dsn helper when available. Since we cannot import from psycopg directly because of potential patch-on-import circular references, we delegate the job to a post-module import hook to update the function reference from our own fallback one to psycopg's one.

fix(sql): use psycopg's parse_dsn when available

---

ddtrace/appsec/_remoteconfiguration.py
ddtrace/appsec/processor.py
ddtrace/appsec/utils.py
releasenotes/notes/asm_fix_rc_capabilities_with_rule_file_set_in_env-3c24b75abbdf003c.yaml
tests/appsec/test_remoteconfiguration.py

When DD_APPSEC_RULES file is specified in the env, RC capabilities that update the rules should be disabled.
Update two tests (RC capabilities and RC product registration) as regression tests for this fix.

fix(asm): rc must not modify rule file specified by env var

---

ddtrace/bootstrap/sitecustomize.py
ddtrace/ext/sql.py
ddtrace/internal/module.py
docs/spelling_wordlist.txt
releasenotes/notes/fix-tracer-parse-pg-dsn-take2-7ef89362545b2721.yaml
tests/contrib/psycopg/test_psycopg.py
tests/contrib/psycopg2/test_psycopg.py
tests/internal/test_module.py

Backports #5927 + backports a [refactor](https://github.com/DataDog/dd-trace-py/commit/082e1e1188e9e799ab331b809d09ec87b5045243) required by this fix

fix(sql): use psycopg's parse_dsn when available (backport #5927 to 1.13)

---

ddtrace/appsec/_remoteconfiguration.py
ddtrace/appsec/processor.py
ddtrace/appsec/utils.py
releasenotes/notes/asm_fix_rc_capabilities_with_rule_file_set_in_env-3c24b75abbdf003c.yaml
tests/appsec/test_remoteconfiguration.py

Backport of #5930 to 1.12
When DD_APPSEC_RULES file is specified in the env, RC capabilities that update the rules should be disabled.
Update two tests (RC capabilities and RC product registration) as regression tests for this fix.

fix(asm): rc must not modify rule file specified by env var [backport #5930 to 1.12]

---

ddtrace/appsec/_constants.py
ddtrace/appsec/trace_utils.py
tests/appsec/test_appsec_trace_utils.py

Adds the login event mode and arguments which to keep backwards compatibility will default to `LOGIN_EVENTS_MODE.SDK` (meaning manually called using the SDK). This is a requirements for the next PR which will implement the RFC for automated user events tracking.

chore: add login event mode argument and tag

---

.github/workflows/test_frameworks.yml
tests/debugging/exploration/_config.py
tests/debugging/exploration/_profiler.py

In an attempt to speed up the Django runs with exploration tests on we delete probes that have been triggered so that future executions can happen with no overhead.

ci(debugging): delete triggered probes in Django runs

---

ddtrace/debugging/safety.py
tests/debugging/test_safety.py

The existing safety check around the retrieval of `__dict__` are too strict and lead to many objects not being captured down to their fields. This change relaxes the condition on safety by ensuring that we can get an instance of `__dict__` that is of the _exact_ type `dict`.
The example that was found in the FastAPI is probably quite exotic as we don't expect actual objects to implement a `__dict__` attribute on a class with potential side-effects.

chore(debugging): relax safe dict retrieval

---

.github/workflows/test_frameworks.yml
tests/debugging/exploration/_config.py
tests/debugging/exploration/_profiler.py

Backport of #6026 to 1.10
In an attempt to speed up the Django runs with exploration tests on we delete probes that have been triggered so that future executions can happen with no overhead.

ci(debugging): delete triggered probes in Django runs [backport #6026 to 1.10]

---

.github/workflows/test_frameworks.yml
tests/debugging/exploration/_config.py
tests/debugging/exploration/_profiler.py

Backport of #6026 to 1.11
In an attempt to speed up the Django runs with exploration tests on we delete probes that have been triggered so that future executions can happen with no overhead.

ci(debugging): delete triggered probes in Django runs [backport #6026 to 1.11]

---

.github/workflows/test_frameworks.yml
tests/debugging/exploration/_config.py
tests/debugging/exploration/_profiler.py

Backport of #6026 to 1.9
In an attempt to speed up the Django runs with exploration tests on we delete probes that have been triggered so that future executions can happen with no overhead.

ci(debugging): delete triggered probes in Django runs [backport #6026 to 1.9]

---

ddtrace/internal/remoteconfig/_connectors.py
tests/debugging/probe/test_remoteconfig.py
tests/internal/remoteconfig/test_remoteconfig_connector.py

Remote Config detects if there is new information to poll from subscribers by validating a checksum of the Remote Config payloads. When we remove a Dynamic Instrumentation Probe from the UI, the payload is set to 'False'.
The problem occurs when we remove two probes. In both cases, the "config" is set to False, they have the same checksum, and the second probe is not removed correctly.
No change log is needed because this error was introduced in version 1.15.0.

chore(rcm/di): disable multiple target files

---

README.md

Currently our onboarding docs instruct contributors to set python2.7 as the default python version. This is less than ideal. 
Also removes python 3.5.10 from installed versions. Python 3.5.10 can not be installed on arm 😢

chore(docs): ensures python3.11 is set as default version

---

ddtrace/appsec/rules.json
tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
tests/snapshots/tests.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json

Update appsec rules from [appsec-event-rules](https://github.com/DataDog/appsec-event-rules) to version 1.7.1

chore(asm): update appsec rules to 1.7.1

---

ddtrace/internal/processor/trace.py

This commit updates the PeerServiceProcessor to `use set_tag_str` instead of `set_tag`, due to known performance issues.

chore(service.naming): peerServiceProcessor to use set_tag_str

---

ddtrace/appsec/ddwaf/__init__.py
tests/appsec/rules-bad_version.json
tests/appsec/test_processor.py
tests/contrib/flask/test_flask_appsec.py

Improve the case where a static rule file is set with not a single valid rules for the WAF.
Instead of raising an Exception, it will fail with debug log message.
Add a regression test where the waf is silently failing with a bad version rule file.

chore(asm): small improvement to waf interface

---

tests/conftest.py

A bug in the handling of the parametrize argument to the subprocess marker prevented it from generating the correct test matrix. This fix ensures that the correct matrix dictionary is generated so that all the intended test cases are actually run.

test: fix parametrisation support in subprocess marker

---

ddtrace/debugging/_encoding.py
ddtrace/debugging/_uploader.py
ddtrace/internal/remoteconfig/_subscribers.py
ddtrace/internal/remoteconfig/client.py
releasenotes/notes/rcm-fix-payload-errors-808e827b978c829a.yaml
tests/appsec/test_remoteconfiguration.py
tests/internal/remoteconfig/test_remoteconfig_client.py
tests/internal/remoteconfig/test_remoteconfig_subscriber.py

When Remote Configuration (RC) receives new configurations, the RC Client has two kinds of actions: removing target file configurations and loading new target file configurations.
The problem arises when we receive both kinds of actions simultaneously, as the load action overrides the remove action. This error occurs if someone creates and removes Dynamic Instrumentation Probes rapidly, within a time interval shorter than the Remote Config interval (5s).
To fix this issue, we append all new configurations and configurations to remove, and dispatch them at the end of the RC request.

fix(rcm): remote config payloads error 

---

ddtrace/internal/telemetry/writer.py

This PR ensures the url used to send telemetry payloads is consistent.
When the telemetry test suite is run with `DD_TRACE_AGENT_URL=http://localhost:9126/ riot -v run -p 3.11 --pass-env -s telemetry` [test_send_failing_request](https://github.com/DataDog/dd-trace-py/blob/1.x/tests/telemetry/test_writer.py#L149)  hangs. This is because the agent url and endpoint are combined in a format that is not expected by httpretty
- Running tests with `http://localhost:9126/telemetry/proxy/api/v2/apmtelemetry` works 
-  Running tests with `http://localhost:9126//telemetry/proxy/api/v2/apmtelemetry ` hangs   
Run the telemetry tests with: `DD_TRACE_AGENT_URL=http://localhost:9126/ riot -v run -p 3.11 --pass-env -s telemetry`. With this change the tests complete successfully but on 1.x the tests hang …

ci(telemetry): use a helper to join agent url to the telemetry endpoint

---

ddtrace/contrib/fastapi/__init__.py

This change adds a note about an unexpected behavior found in https://github.com/DataDog/dd-trace-py/issues/6030 to the FastAPI integration documentation.

docs(fastapi): add note about fastapi middleware

---

.github/CODEOWNERS
releasenotes/notes/add-fi-owners-52de8ce02f69e946.yaml

This is the first step toward the Framework Integrations team to co-own folders related to instrumentations.
Since changes to span naming and attributes can have a large impact, we also propose to co-own `tests`.
The change is high in the file, so individual teams (e.g. ASM) can set stricter rules on specific files (including tests) that are relevant to them.

chore: make FI team members co-owners of folders containing integrations and tests

---

tests/integration/test_integration.py

Looking at the failing test below we can see `test_single_trace_too_large` generates  over 20MB of trace data but these traces can be sent in separate payloads (yay partial flushing). This PR mocks `AgentWriter.flush_queue()` to ensure traces are not submitted. With this change the `BufferFull` exception will be consistently raised and `"trace buffer (%s traces %db/%db) cannot fit trace of size %db, dropping (writer status: %s)"` will always be logged.
This PR: 
- Removes time interval env var this not required since the mechanism that submits traces is being mocked.
- Removes `tracer.shutdown()` this test should not submit traces to the agent.
- Decreases the total size of the trace from 200,000 to 30,000.
- Generating 200,000 spans is overkill and very slow. We only need to queue 30,000 …

ci(integrations): makes test_single_trace_too_large less flaky

---

ddtrace/propagation/http.py
releasenotes/notes/negative-trace-id-813bd867c1c8553e.yaml
tests/tracer/test_propagation.py

This pull request fixes the symptom reported in https://github.com/DataDog/dd-trace-py/issues/6125 by ensuring that ddtrace does not set negative values in the trace ID propagation header. Whatever underlying issue is causing the trace ID to be negative still exists despite this change.

fix(tracing): disallow the propagation of negative trace IDs

---

ddtrace/internal/ci_visibility/writer.py
tests/ci_visibility/test_ci_visibility.py

CI Visibility: Small refactor to set `intake_cov_url` value properly (ultimately independent from `intake_url` argument)

chore(ci-visibility): improve intake_cov_url logic

---

ddtrace/internal/ci_visibility/git_client.py
tests/ci_visibility/test_ci_visibility.py

CI Visibility: git repository url uses env vars if available, and git output as fallback
See [Jira task](https://datadoghq.atlassian.net/browse/CIAPP-6676) for more info

chore(ci-visibility): git repo url: use env vars over git output

---

ddtrace/contrib/aiohttp/patch.py
ddtrace/contrib/elasticsearch/patch.py
ddtrace/contrib/trace_utils.py
tests/contrib/aiohttp/test_aiohttp_client.py
tests/contrib/elasticsearch/test_elasticsearch.py
tests/snapshots/tests.contrib.elasticsearch.test_elasticsearch_multi.test_elasticsearch.json
tests/snapshots/tests.contrib.elasticsearch.test_elasticsearch_multi.test_elasticsearch6.json
tests/snapshots/tests.contrib.elasticsearch.test_elasticsearch_multi.test_elasticsearch7.json

The peer.service initiative allows Datadog to set better defaults for service names, and to build a more intuitive service map, by mapping outgoing connections with the destinations service names.  In order to implement this functionality, various 'precursor' tags must be added to
This change adds one such precursor tag required for peer.service, for elasticache, which allows us to identify the cluster being connected to.
This change adds the 'out.host' tag for elasticsearch spans using the first connection which returns a valid hostname. If none are found, the tag is not added.

chore(peer.service): report hostname for elasticsearch

---

ddtrace/internal/processor/trace.py
ddtrace/settings/peer_service.py
ddtrace/tracer.py
tests/internal/peer_service/test_processor.py

Peer.Service is currently a beta product and is hidden behind a feature flag, alongside service naming.
This change provides users with the ability to change peer.service names via an environment variable, `DD_TRACE_PEER_SERVICE_MAPPING`. When users specify this variable, any services in the mapping will be automatically remapped to a different value, and the tag `_dd.peer.service.remapped_from` will be set to the prior value.  Note that the remapping happens irregardless of whether or not `DD_TRACE_PEER_SERVICE_DEFAULTS_ENABLED` is enabled

chore(peer.service): add peer.service remap logic

---

.github/CODEOWNERS

Update codeowners for `internal/ci_visibility`

chore: update codeowners for internal/ci_visibility

---

ddtrace/debugging/_signal/tracing.py
tests/debugging/test_debugger_span_decoration.py

dynamic span tags also generate 'instrumentation tags'. they should start with a prefix "_dd.di" as defined by the spec.

chore(debugging): fix dynamic span tags to be _dd.di

---

ddtrace/appsec/ddwaf/__init__.py
tests/contrib/pylons/test_pylons.py
tests/profiling/exporter/test_packages.py
tests/profiling/exporter/test_pprof.py

This change adjusts some test expectations to account for the mysterious failures that appeared in the 1.x branch's CI between https://github.com/DataDog/dd-trace-py/commit/ff9e04024df3a20e99ec56a7ccefa2bd6c70d2a9 and https://github.com/DataDog/dd-trace-py/commit/7c5783b9b70177d81245b810dbd5087566e42678. It's not clear to me what changed in CI to make these tests start failing. None of the failing tests fail on my local. For the `profile` tests, I've tried making a bunch of different local changes to the code and have so far been unable to get my local to replicate the CI failures.
Given this, my opinion at the moment is that these test expectations should be adjusted to unblock CI, and the underlying failure looked into by domain experts next week in #6156 .
~ @emmettbutler

ci(asm): adjust test assertions to match CI behavior

---

.github/workflows/test_frameworks.yml

Related to https://github.com/actions/setup-python/issues/672.
Setup-python removed Python 2.7 from their list of python-versions as of June 19, 2023, meaning our framework tests for Pylons (which is based on Python 2) now fail. The recommended solution was to instead use a Python 2.7 container within the ubuntu-20.04 image, which this PR does.

fix(ci): use container to run Python 2.7 in pylons framework test

---

.github/workflows/test_frameworks.yml

Related to https://github.com/actions/setup-python/issues/672.
Setup-python removed Python 2.7 from their list of python-versions as of June 19, 2023, meaning our framework tests for Pylons (which is based on Python 2) now fail. The recommended solution was to instead use a Python 2.7 container within the ubuntu-20.04 image, which this PR does.
policy](../docs/contributing.rst#release-branch-maintenance)

fix(ci): use container to run Python 2.7 in pylons framework test [backport #6167 to 1.13] 

---

.github/workflows/test_frameworks.yml

Related to https://github.com/actions/setup-python/issues/672.
Setup-python removed Python 2.7 from their list of python-versions as of June 19, 2023, meaning our framework tests for Pylons (which is based on Python 2) now fail. The recommended solution was to instead use a Python 2.7 container within the ubuntu-20.04 image, which this PR does.
policy](../docs/contributing.rst#release-branch-maintenance)

fix(ci): use container to run Python 2.7 in pylons framework test [backport #6167 to 1.14]

---

.github/workflows/test_frameworks.yml

Related to https://github.com/actions/setup-python/issues/672.
Setup-python removed Python 2.7 from their list of python-versions as of June 19, 2023, meaning our framework tests for Pylons (which is based on Python 2) now fail. The recommended solution was to instead use a Python 2.7 container within the ubuntu-20.04 image, which this PR does.
policy](../docs/contributing.rst#release-branch-maintenance)

fix(ci): use container to run Python 2.7 in pylons framework test [backport #6167 to 1.15]

---

tests/integration/test_integration.py

Increase timeout to make integration_agent tests less flaky on CircleCI.

ci(integration): increase timeout to make integration_agent tests less flaky

---

docker/Dockerfile

This should resolve the failing ci build of the testrunner image. We can test this by running the docker build after the update.

ci: update pyenv in testrunner

---

ddtrace/contrib/openai/patch.py
ddtrace/internal/log_writer.py
tests/contrib/openai/test_logger.py

This PR moves the `V2LogWriter` class into `ddtrace.internal.log_writer` from `ddtrace.contrib.openai._logging` as this will be reused by the LangChain integration, and will no longer be specific to the OpenAI integration.
The test file `tests.contrib.openai.test_logging` will remain in the `contrib.openai` module as this reflects the openai integration.

refactor: move V2 logwriter into internal module

---

.circleci/config.yml

The CircleCI step for saving the pip cache assumes it is located in a directory different than that set by `XDG_CACHE_HOME`. This environment variable is not set anywhere so the default path should be `~/.cache/pip`.
Before this change, the file size of the cache reported in the restore step is empty (32 bytes): 
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/38618/workflows/a576c222-5886-470d-81ce-82b57cd2eb0f/jobs/2599223/parallel-runs/0/steps/0-104
After this change, the cache will not be empty.

chore(ci): update pip cache path

---

.github/workflows/prune_workflow.yml

The scheduled pruning workflow job has been failing. This change adds write permissions and makes the job definition consistent with the action recommendations.
This is not backported as the action is only run from the 1.x branch.

fix(ci): add write permissions for prune workflows

---

ddtrace/internal/telemetry/writer.py
tests/telemetry/test_telemetry_metrics.py

- Sending language and library version in the `generate-metrics` payload is not part of the telemetry spec:  https://github.com/DataDog/dd-trace-py/pull/new/telemetry-metrics-clean-up 
- These fields are sent in main request body. Including it here is redundant.

chore(telemetry): remove unnecessary fields from metrics payloads

---

ddtrace/internal/processor/trace.py
ddtrace/tracer.py
tests/internal/peer_service/test_processor.py

Prior to this change, the peer.service processor (PeerServiceProcessor) processed invidual spans on_finish.  After this change, the processor now operates at a (partial) trace level.  Whenever a whole or part of a trace is being completed, all spans will be processed at once.

chore(peer.service): perf - process traces instead of spans

---

ddtrace/contrib/django/patch.py
ddtrace/contrib/django/utils.py
tests/contrib/django/django_app/appsec_urls.py
tests/contrib/django/test_django_appsec_api_security.py

Only to be merged after https://github.com/DataDog/dd-trace-py/pull/6163 and https://github.com/DataDog/dd-trace-py/pull/6180 (it's ok for now).
Activate full support of API security into the Django framework.
This feature is still in private phase and not officially released.

chore(asm): add api security django support

---

docs/contributing.rst
docs/spelling_wordlist.txt
docs/versioning.rst

This change updates the contribution guidelines to assume minimal knowledge of ddtrace's development practices and expectations.

docs: flesh out contribution guidelines

---

.github/workflows/test_frameworks.yml

Merge checks are failing because of system dependency that is failing to install.
This change updates the apt cache before installing with necessary options to avoid tty input.

fix(ci): update django framework test image

---

.github/PULL_REQUEST_TEMPLATE.md

This change makes the links to the backport policy point to the newly updated backporting documentation, where before they had been 404s.

docs: fix broken links in pr checklist

---

ddtrace/contrib/pytest/plugin.py
releasenotes/notes/feat-pytest-changes-in-modules-and-suites-bbdda83c3c40bfee.yaml
tests/contrib/pytest/test_pytest.py

CI Visibility: Report tests suites as the filename and test modules as a fully qualified name

feat(ci-visibility): change how test module and suite names are reported

---

ddtrace/appsec/iast/_taint_utils.py
tests/appsec/iast/test_taint_utils.py

Rework on LazyTaintDict:
1. make it recursive, tainting lazily any list or dict at any level in the structure
2. force taint is now working on keys and values if the dict is iterated
3. add LazyTaintList working as LazyTaintDict
4. refactor some code
Also add a unit test to check for recursive tainting.

chore(asm): rework on lazytaintdict

---

.circleci/config.yml
tests/datastreams/test_encoding.py

This change adds a workflow to run datastreams tests in circleci.  Prior to this change, we relied on reviewers to know to run the test.

chore(datastreams): enable datastreams in circleci

---

ddtrace/internal/sampling.py
setup.py
tests/tracer/test_single_span_sampling_rules.py

We have had issues recently with newer versions of `jsonschema`. Most importantly, it caused issues with our build/release process (mainly `rpds-py` which is a dependency of `jsonschema`s): https://github.com/DataDog/dd-trace-py/actions/runs/5476876584/jobs/9975064818
Looking over the usage of `jsonschema`, there isn't much it is really doing for us. This PR attempts to replace the usage with other/similar manual checks.
If the existing test cases/edge cases continue to pass, then we have successfully replaced `jsonschema`.
The risk with this change is a user ends up with an opaque error message. Instead of getting a message saying `max_per_second` must be an integer, they might instead get an operation error when trying to multiply `None` (or some non-integer value) against another …

chore(dep): remove jsonschema dependency from package

---

ddtrace/appsec/iast/_taint_utils.py

To keep to original behaviour of tainted dict and tainted list that can have overrided method, switch from a lazy taint object model that was inheriting from base classes to a model that encapsulate the object to taint.

(chore)asm: lazy taint dict as capsules

---

benchmarks/bm/utils.py

Fixes the following error ([link](https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-py/-/jobs/293082432)):  
```
File "/app/baseline/benchmarks/bm/_scenario.py", line 73, in _pyperf
run = next(rungen)
File "/app/baseline/benchmarks/scenario.py", line 34, in run
utils.drop_telemetry_events()
File "/app/baseline/benchmarks/bm/utils.py", line 75, in drop_telemetry_events
if telemetry.telemetry_writer.is_periodic():
TypeError: 'bool' object is not callable
```

fix(benchmarks): resolve syntax error

---

ddtrace/bootstrap/sitecustomize.py
releasenotes/notes/fix-re-unload-8770a3d497234243.yaml
tests/commands/test_runner.py

Backport of #6255 to 1.13
The re module imports from the sre_constants module at runtime. This might cause issues when modules are unloaded in the sitecustomize.
Fixes #6197.

fix: keep the sre_constants module [backport #6255 to 1.13]

---

ddtrace/bootstrap/sitecustomize.py
releasenotes/notes/fix-re-unload-8770a3d497234243.yaml
tests/commands/test_runner.py

Backport of #6255 to 1.14
The re module imports from the sre_constants module at runtime. This might cause issues when modules are unloaded in the sitecustomize.
Fixes #6197.

fix: keep the sre_constants module [backport #6255 to 1.14]

---

ddtrace/contrib/flask/patch.py
ddtrace/contrib/flask/wrappers.py
ddtrace/contrib/wsgi/wsgi.py

This change updates some import statements in the flask and wsgi contribs to avoid referencing the AppSec product code when importing internal code. This helps clarify the separation of concerns between AppSec and contribs.

chore: update flask and wsgi imports to avoid mentioning appsec

---

.circleci/config.yml
pyproject.toml
setup.py

Hotfix to avoid build/typing errors related to the latest release of `cython==3.0.0`. We'll need to investigate further to see what's going on.

fix: pin cython<3 in setup

---

releasenotes/notes/pin-cython-042240c7d4fdd977.yaml

Adds a release note for #6376.

chore: release note for pinning cython<3

---

pyproject.toml
releasenotes/notes/pin-cython-042240c7d4fdd977.yaml
setup.py

Backports https://github.com/DataDog/dd-trace-py/pull/6376 to 1.15.

fix: pin cython<3 on setup [backport #6376 to 1.15]

---

pyproject.toml
releasenotes/notes/pin-cython-042240c7d4fdd977.yaml
setup.py

Backports https://github.com/DataDog/dd-trace-py/pull/6376 to 1.16.

fix: pin cython<3 on setup [backport #6376 to 1.16]

---

pyproject.toml
releasenotes/notes/pin-cython-042240c7d4fdd977.yaml
setup.py

Backports https://github.com/DataDog/dd-trace-py/pull/6376 to 1.14.

fix: pin cython<3 on setup [backport #6376 to 1.14]

---

ddtrace/contrib/langchain/patch.py
tests/contrib/langchain/test_langchain.py

Builds on top of work done by @NarekA in #6369. This PR does not need a changelog as the LangChain integration has not been released yet.
Current behavior of the traced LangChain chain is to grab the `prompt.template` attribute from the chain instance, but certain `PromptTemplate` classes do not have simple string `template` attributes which causes errors when we look these items up in code. For example the `ChatPromptTemplate` class stores a list of messages each with their own prompt template, making this non-trivial to parse and tag.
As a result, we'll check if simple string templates are available on the PromptTemplate, and do nothing otherwise. In the future, we can consider tagging complex prompt values, but this is outside the scope of this PR (which aims to avoid raising errors by …

chore(langchain): ignore tagging complex prompt templates

---

.github/workflows/build_deploy.yml
.github/workflows/build_python_3.yml

In order to combat the ever increasing build/release time we are breaking up the build/publish job into multiple jobs so the work can be better parallelized.
Before this change the build process would take at least 4 hours (sometimes more, or timing out at 6 hours), after this change it completes in about 1.5 hours.
The Python 2.7 + 3.5 build job is kept as-is with no changes.
For Python 3.6+ we have created a reusable workflow and then creates one build step per-python version that we want to support (3.6, 3.7, 3.8, 3.9, 3.10, 3.11).
This change also changes the `workflow_dispatch` trigger to not publish to PyPI so it can be used to validate the build process without releasing.
This change was validated by running manually, and then validating that the number of release files and the …

fix(ci): break wheel building into multiple jobs

---

ddtrace/profiling/recorder.py
releasenotes/notes/fix-profiler-recorder-rrlock-3c16195829e29acd.yaml

Backport of #6374 to 1.17
Prevent the event recorder from deadlocking on itself when multiple events are being recorded along the same call stack
The occurrence of the issue seems to be circumstantial, which makes it reproducing it difficult. We have evidence from user reports that the proposed fix does indeed solve the issue.
It is unclear at the moment whether a re-entrant lock would expose the recorder to an infinite recursion issue instead of a deadlock. Possible reports of such issues might be related to this, in which case a more sophisticated fix would be required.
Fixes #6308.

fix(profiling): use re-entrant lock in recorder [backport #6374 to 1.17]

---

.circleci/config.yml

We validate package installations via `riot` and `build_base_venvs`. We will no longer get the debug flags, but we feel we are getting enough testing of this via other jobs.
This makes the runtime of `ccheck` go from 3+ mins -> <20 seconds.
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/41133/workflows/707decd8-bb5e-4f4a-8bc2-c930661b8553/jobs/2756075

chore(ci): remove installation test of ccheck

---

releasenotes/notes/fix-cmake-dep-f25774b77cb7a795.yaml
setup.py

Fixes #6467
`cmake` was added to `install_requires` instead of `setup_requires` when it isn't needed there.

fix(dep): install cmake as setup_requires instead of install_requires

---

.circleci/config.yml

#6412 changed our circleci configuration setup to be dynamic, but this inadvertently removed the `coverage` and `riot_run_latest` circleci pipeline parameters from the main `.circleci/config.yml` file, which breaks our nightly 1.x coverage pipeline runs. This PR re-adds those parameters back and re-enables coverage reporting. 
Note that `datastreams`, `langchain`, `elasticsearch`, `integration-snapshot` test suites are still failing on 1.x nightly coverage runs and will need to be fixed.

chore(ci): re-add circleci config coverage parameters

---

scripts/needs_testrun.py
tests/.suitespec.json

This change ensures that test suites run when changes to the riotfile or testrunner script are pull requested.

ci: run tests when riotfile changes

---

ddtrace/contrib/pytest/plugin.py
ddtrace/ext/git.py
ddtrace/internal/ci_visibility/git_client.py
ddtrace/internal/ci_visibility/recorder.py
tests/ci_visibility/test_ci_visibility.py
tests/tracer/test_ci.py

Backport https://github.com/DataDog/dd-trace-py/commit/d4d2f78 from https://github.com/DataDog/dd-trace-py/pull/6268 to 1.17.
An unshallow command compatible with git >= 2.27 is now used when a shallow repository is detected.
Additionally, packfile upload is improved by searching for commits found in the repo that are not known to the ITR backend, rather than just HEAD.
For tests, a shallow clone was created using `git clone --depth=1 https://github.com/pallets/flask.git`, with git log showing only one result:
```
% git log --pretty=oneline
cb825687a592709f902f3d320d93987a0546fd28 (grafted, HEAD -> main, origin/main, origin/HEAD) Bump actions/checkout from 3.5.2 to 3.5.3 (#5186)
```
After:
```
cb825687a592709f902f3d320d93987a0546fd28 (HEAD -> main, origin/main, origin/HEAD) Bump …
```

chore(ci-visibility): unshallow repository when git >= 2.27 [backport 1.17]

---

releasenotes/notes/fix-itr-test-skipping-e4b99a581138a8fd.yaml

CI Visibility: Add missing release note for ITR test skipping fix ([original PR](https://github.com/DataDog/dd-trace-py/pull/6306))

fix(ci-visibility): add ITR test skipping fix release note

---

ddtrace/contrib/pytest/plugin.py
ddtrace/internal/ci_visibility/constants.py
ddtrace/internal/ci_visibility/coverage.py
ddtrace/internal/ci_visibility/encoder.py
ddtrace/internal/ci_visibility/git_client.py
ddtrace/internal/ci_visibility/recorder.py
ddtrace/internal/ci_visibility/writer.py
releasenotes/notes/fix-itr-test-skipping-e4b99a581138a8fd.yaml
tests/ci_visibility/test_coverage.py
tests/ci_visibility/test_coverage_per_suite.py
tests/ci_visibility/test_encoder.py
tests/contrib/pytest/test_pytest.py

Backport [ddf8d41](https://github.com/DataDog/dd-trace-py/commit/ddf8d41a4b5174117ba8c096eba0f2ea9036307b) from https://github.com/DataDog/dd-trace-py/pull/6306 to 1.17.
CI Visibility:
- Fix for test or suite skipping (controlled by env var to use the latter)
- Create spans for ITR-skipped items (as agreed at ITR skipped tests/suites RFC)

fix(ci-visibility): fix ITR test skipping [backport 1.17]

---

docs/spelling_wordlist.txt
releasenotes/notes/fix-git-unshallow-84b5b81db6e79287.yaml

CI Visibility: Add git unshallow fix release note missing in original PR: https://github.com/DataDog/dd-trace-py/pull/6268

fix(ci-visibility): add git unshallow fix release note

---

.circleci/config.templ.yml
scripts/gen_circleci_config.py
scripts/needs_testrun.py

We dynamically generate the list of pre-checks to run on a PR based on the paths included in the PR.

ci: run only the necessary pre-checks

---

tests/suitespec.py

#6518 missed an update to the doctest, which can be skipped so was not caught.

ci: fix suitespec doctest

---

ddtrace/bootstrap/sitecustomize.py
ddtrace/tracer.py

This adds a removal version for the already deprecated `DD_CALL_BASIC_CONFIG`.

chore: add removal version for deprecated DD_CALL_BASIC_CONFIG

---

setup.py
tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
tests/snapshots/tests.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot.json
tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json

Update libddwaf to 1.12.0
[1.12.0 release](https://github.com/DataDog/libddwaf/releases/tag/1.12.0)

chore(asm): update libddwaf to 1.12.0

---

docker-compose.yml

We weren't pinning the Docker image for kafka when we updated to use `bitnami/kafka:3.5.1`.
They released a new version of this tag which caused use issues/deadlocking in the application. Pinning to this tag helps resolve that (what we should have done before).

ci: pin kafka image

---

tests/contrib/subprocess/test_subprocess.py

Fix two subprocess integration tests that were failing after the latest changes to 1.x

chore(asm): fix 2 subprocess integration tests

---

.circleci/config.templ.yml

In an effort to reduce the occurance of the following error, this PR proposes to remove the pip cache, at least temporarily to try and bisect where the problem could be coming from.
> ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE.
Since the error only seems to occur in CircleCI, and is intermittent running/re-running this PR's tests a few times might not be enough to validate if this actually resolves the issue or not.
**Negative impact of this change:**
- We save/restore the pip cache for each job and node hashed on `riotfile.py` and `setup.py`. This is meant to save us time and bandwidth from downloading packages from pip every time they are installed. With this cache removed we may see job runtimes to increase a bit because more downloads need to happen. The …

ci: do not use pip cache

---

ddtrace/internal/ci_visibility/git_client.py
ddtrace/internal/ci_visibility/recorder.py

CI Visibility: Decode `bytes` response if in Python2

chore(ci-visibility): python2 compatibility issue

---

tests/ci_visibility/test_ci_visibility.py
tests/ci_visibility/test_coverage_per_suite.py
tests/ci_visibility/test_encoder.py
tests/ci_visibility/util.py
tests/contrib/asynctest/test_asynctest.py
tests/contrib/pytest/test_pytest.py
tests/contrib/pytest_bdd/test_pytest_bdd.py
tests/integration/test_integration.py
tests/integration/test_integration_civisibility.py

CI Visibility: Refactored tests
1. Extract `_patch_dummy_writer` for better reusability
2. Extract ci_visibility integration tests to a separate suite

refactor(ci-visibility): tests refactor

---

tests/.suitespec.json

This reverts a change to the suitespec from #6523 that appears to have broken test suite selection on 1.x. See [this CI run](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/42187/workflows/51fe1083-51c5-4a69-8703-6c3a8bbb8989) for an example: a run on the 1.x did not run any suites, when it should run *all* suites.

ci: undo change that appears to have broken suite selection

---

ddtrace/internal/ci_visibility/recorder.py
ddtrace/provider.py
ddtrace/tracer.py
tests/utils.py

CI Visibility: decouple from regular Tracer and ContextProvider to avoid issues when self-instrumenting ddtrace.
Also decouple env vars so we can have 2 separate sets of DD_API_KEY and DD_APP_KEY

chore(ci-visibility): decouple from tracer

---

tests/conftest.py

Conftest: The way we're using the ``pytest_runtest_protocol`` hook in our conftest blocks the subsequent calls to ``pytest_runtest_makereport`` hooks for the ``call`` step. This change fixes that issue.

chore(tests): fix pytest hooks

---

.github/workflows/test_frameworks.yml

We filter on paths within the repository that require the framework tests to run to avoid running them when not necessary. To do this we introduce an extra check job that we make a dependency for the test suites. If the check job determines that no tests are required, the steps within each framework test is not run. This way we can still effectively run the job, which is required by PRs, but turn them into no-op for a quicker and cheaper feedback.

ci: run framework tests only when necessary

---

.circleci/config.templ.yml
scripts/gen_circleci_config.py

ci: build docs only if necessary

---

ddtrace/profiling/collector/_lock.py
pyproject.toml

chore(profiling): resolve bandit warnings

---

.github/workflows/lib-injection.yml

ci: run lib-injection workflow only when needed on PRs

---

.readthedocs.yml

readthedocs build has been failing because of a shallow git clone. This adds an unshallow fetch as a post checkout step.

ci: fix readthedocs build

---

ddtrace/tracer.py
releasenotes/notes/deprecate_dd_log_format-bce67441fe2c92cb.yaml

`DD_LOG_FORMAT` has been part of the public API but is not used anywhere else other than our own log injection mechanisms in `bootstrap/sitecustomize.py` and `tracer.py`. As part of the 2.0 release, this will be made private in `ddtrace/_logger.py`, so we can deprecate it here and announce it to be removed from the 2.0 public API.

chore: deprecate DD_LOG_FORMAT

---

.circleci/config.templ.yml
ddtrace/internal/ci_visibility/encoder.py

CI: This PR fixes the issue with forks that do not have the API keys to run --ddtrace in pytest

ci: fix pytest --ddtrace for forks

---

.circleci/config.templ.yml
tests/ci_visibility/test_ci_visibility.py
tests/contrib/pytest/test_pytest.py
tests/utils.py

Pytest: Tests using `subprocess_run` should use `override_env` to avoid CI_Visibility env vars from leaking to the inner execution.

chore(tests): make sure pytest tests run with a clean environment

---

riotfile.py

CI: Disable CI Visibility (or --ddtrace pytest plugin) for integration tests, since the 403 log from the request to the backend is being picked up by the integration tests that don't expect that log.

ci: disable civisibility for integration tests

---

ddtrace/internal/_encoding.pyx
releasenotes/notes/decrease_max_string_size-6a2802b4ce6a90af.yaml
tests/integration/test_integration.py

Resolves: https://github.com/DataDog/dd-trace-py/issues/6587
Previously the maximum size of a span tag was set to the full size of trace writer buffer (via DD_TRACE_WRITER_BUFFER_SIZE_BYTES).With this change the maximum size of span tags will be set to 10% of the size of the writer's buffer. This should decrease the frequency of encoding errors due to large span tags.
Note: The new maximum size of span tags (10% of the buffer size) was chosen arbitrary. Feel free to suggest a more appropriate value.
Note: This change intentionally avoids adding a new tracer configuration. Allowing two configurations could add unnecessary complexity. Making the max string size a function of buffer size should be good enough.

chore(tracing): decrease the maximum size of span tags

---

scripts/needs_testrun.py

The dynamic CI configuration is broken on 1.x for merge commits, causing us not to run `build_docs`, `pre_checks` steps, and `check`.
See https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/42828/workflows/0510ed4b-8f27-4a9d-8c65-6fff21065fc5/jobs/2849569?invite=true#step-102-18007_113
```
INFO: Configuration generation steps:
INFO: - gen_required_suites: Generate the list of test suites that need to be run. [took 34ms]
WARNING: Failed to get changed files from GitHub API, using git diff instead
ERROR: - gen_pre_checks: Generate the list of pre-checks that need to be run. [reason: HTTP Error 404: Not Found]
```

ci: fix dynamic config on default branch

---

scripts/needs_testrun.py

We ensure that a PR is reported as matching a given set of file patterns when we fail to retrieve a list of changed files. This ensures that we run all the jobs out of precaution instead of potentially skipping them.

ci: make PR match patterns if unable to get changed files

---

ddtrace/appsec/handlers.py
tests/contrib/django/django_app/appsec_urls.py
tests/contrib/django/test_django_appsec_iast.py

- add request body tainting for Django framework
- add 2 tests with and without iast
It works by tainting an internal private field of Django HttpRequest `_body`

chore(asm): raw body django tainting for IAST

---

tests/contrib/psycopg/test_psycopg_async.py

ci: remove erroneously committed breakpoint

---

tests/debugging/mocking.py
tests/debugging/test_debugger.py

We remove some flakiness around probe status message testing by adding a wait logic to the mocked probe status logger.

test(debugging): reduce flakiness in status logger

---

scripts/run-test-suite
tests/appsec/test_asm_request_context.py

This pull request fixes a regression in the test runner that caused jobs with failing tests to get green checkmarks.

ci: fail the job when tests fail

---

scripts/needs_testrun.py

This change makes the warning output from failed GitHub API requests a bit nicer, and removes an unnecessary variable from the script.

ci: clean up code in needs_testrun script

---

tests/conftest.py
tests/profiling/test_profiler.py

A test for the profiler exporter in agentless mode required the DD_SITE variable to be unset. We modify the test to ensure that this variable is unset in the subprocess to exercise and  test the correct logic.

test(profiling): unset DD_SITE variable in agentless URL check

---

.github/workflows/lib-injection.yml
docs/spelling_wordlist.txt
lib-injection/Dockerfile
releasenotes/notes/lib-injection-pkg-dir-permissions-aaac0059b6c21f30.yaml

Backport of #6569 to 1.18
When library injection is used the `/datadog-lib/ddtrace_pkg` directory is created with permissions that prevents other users from reading certain files. This PR ensures all files in`/datadog-lib/ddtrace_pkgs` are readable to all users.
When  `find /datadog-lib/ddtrace_pkgs ! -perm -a=r` is run on a host using library injection with `ddtrace==1.17.3` the following output is generated:
<details>
/datadog-lib/ddtrace_pkgs/ddtrace_pkgs/site-packages-ddtrace-py3.10-manylinux2014/protobuf-4.23.4.dist-info/METADATA
/datadog-lib/ddtrace_pkgs/ddtrace_pkgs/site-packages-ddtrace-py3.10-manylinux2014/protobuf-4.23.4.dist-info/RECORD
/datadog-lib/ddtrace_pkgs/ddtrace_pkgs/site-packages-ddtrace-py3.10-manylinux2014/protobuf-4.23.4.dist-info/WHEEL …

fix(lib-inject): allow all users to read and modify installed packages [backport #6569 to 1.18]

---

tests/ci_visibility/test_ci_visibility.py
tests/contrib/pytest/test_pytest.py
tests/utils.py

Pytest: Tests using `subprocess_run` should use `override_env` to avoid CI_Visibility env vars from leaking to the inner execution.
(cherry picked from commit ee5bd3555206048df932505cf94eca76f708a750)

chore(tests): make sure pytest tests run with a clean environment (backport #6582 to 1.17)

---

scripts/needs_testrun.py

This is a cherry-pick of test commit https://github.com/DataDog/dd-trace-py/pull/6626/commits/c5c7d0a7872033218979eab5ea39fd2c7a7b40f1. 
We currently use the Github REST API to see all changed files in a PR, and default to using a `git diff` against a base commit if that fails. However, the REST API call will return at most 30 changed files which are used to compute which test suites to run, so large PRs (potentially with many lockfiles changed) will potentially not trigger test suites.
This PR adds a workaround where if we get exactly 30 changed files in the Github REST call, we will default to using `git diff` instead. The only risk is PRs with exactly 30 changed files, but using `git diff` should not significantly change any result.

chore(ci suitespec): default to diffing against base branch if exactly 30 changed files returned

---

ddtrace/contrib/httplib/patch.py
ddtrace/internal/constants.py
ddtrace/internal/writer/writer.py
tests/ci_visibility/test_ci_visibility.py
tests/contrib/httplib/test_httplib.py
tests/utils.py

Avoids tracing http requests made by trace writers to datadog internal services (i.e. prevents the ci visibility writer from sending traced requests to internal services). 
- Prevents tracing internals from being traced.
- Resolves flakiness in the httplib test suite with the agentless ci visibility writer

fix(httplib): avoid tracing requests made by trace writers

---

hatch.toml
scripts/gen_circleci_config.py
tests/conftest.py

`riot` was removed from the pre-check CircleCI setup by https://github.com/DataDog/dd-trace-py/pull/6640/files#diff-8166c31d8ba62357b4a7cac4407d8744e60cf6b6ba32b09af939807db4c8f490L246 .
This updates config to run the `meta-testing` check via `hatch` instead of via `riot`.

chore(ci): add meta-testing to hatch

---

.circleci/config.templ.yml
.circleci/config.yml

This PR pins the docker images used in our CircleCI tests. This is in preparation for the 2.0 release and freezing docker images and test dependencies for the 1.x release line to ease maintenance of the 1.x branch.

chore(ci): pin circleCI images

---

.github/workflows/lib-injection.yml
docs/spelling_wordlist.txt
lib-injection/Dockerfile
releasenotes/notes/lib-injection-pkg-dir-permissions-aaac0059b6c21f30.yaml

Backport of #6569 to 1.17
When library injection is used the `/datadog-lib/ddtrace_pkg` directory is created with permissions that prevents other users from reading certain files. This PR ensures all files in`/datadog-lib/ddtrace_pkgs` are readable to all users.
When  `find /datadog-lib/ddtrace_pkgs ! -perm -a=r` is run on a host using library injection with `ddtrace==1.17.3` the following output is generated:
<details>
/datadog-lib/ddtrace_pkgs/ddtrace_pkgs/site-packages-ddtrace-py3.10-manylinux2014/protobuf-4.23.4.dist-info/METADATA
/datadog-lib/ddtrace_pkgs/ddtrace_pkgs/site-packages-ddtrace-py3.10-manylinux2014/protobuf-4.23.4.dist-info/RECORD
/datadog-lib/ddtrace_pkgs/ddtrace_pkgs/site-packages-ddtrace-py3.10-manylinux2014/protobuf-4.23.4.dist-info/WHEEL …

fix(lib-inject): allow all users to read and modify installed packages [backport #6569 to 1.17]

---

tests/appsec/test_remoteconfiguration_e2e.py

Add exponential backoff and more retries to prevent flakiness in appsec test: `tests/appsec/test_remoteconfiguration_e2e.py`

chore(asm): add exponential backoff and more retries to prevent flakiness in appsec test

---

ddtrace/appsec/_constants.py
ddtrace/appsec/handlers.py
ddtrace/contrib/flask/patch.py
ddtrace/internal/constants.py
ddtrace/tracing/trace_handlers.py

This change leverages the fact that the constant denoting WAF request blocking is [defined](https://github.com/DataDog/dd-trace-py/blob/8918337c84d6da8a8a3fbcc972723bb7f7bb508c/ddtrace/appsec/_constants.py#L143) in `ddtrace.internal` to move logic mentioning ASM out of the flask contrib and trace handlers code.

use shared constant for asm blocking flag

---

ddtrace/opentelemetry/__init__.py
releasenotes/notes/fix-undefined-var-in-otel-docs-508ff00a82264aef.yaml

`otel_span` isn't declared, presumably the original author intended to use `parent_span` here, which is in scope.

fix(docs): fix undefined variable reference in otel docs

---

ddtrace/contrib/mariadb/patch.py
releasenotes/notes/maria-missing-port-e30630b4f5a5ee33.yaml
tests/contrib/mariadb/test_mariadb.py

This change fixes https://github.com/DataDog/dd-trace-py/issues/6203 by supplying defaults for the accesses of `port` and `user` fields from the MariaDB connection info object.

fix: don't crash when mariadb connection string doesn't include port or user

---

ddtrace/appsec/iast/_taint_utils.py
ddtrace/contrib/httplib/patch.py
ddtrace/ext/ci.py
ddtrace/internal/datadog/profiling/ddup.py
ddtrace/profiling/collector/memalloc.py
ddtrace/profiling/exporter/pprof.pyx
hatch.toml
pyproject.toml
tests/contrib/httplib/test_httplib.py
tests/contrib/pytest_benchmark/test_pytest_benchmark.py
tests/contrib/tornado/utils.py

This change fixes the `pre_check` job, which had become a noop in many cases after a regression a few weeks ago.
All of the non-toml changed files are the result of running `black` and `isort` against the repo.

ci: use check diff arguments in black and isort checks

---

.github/workflows/test_frameworks.yml

Backport of #6539 to 1.16
The sanic framework tests have recently started failing a single test: `test_redirect_with_params`, which has a weird error relating to string formatting: `"sanic%20test" != "sanic test"`.
This test's assertion was subtly changed in the most recent release of sanic by altering the string formatting of the asserted string value, and this only started failing once the new version of sanic (23.3.0) was released, so we can consider skipping this test for now until we upgrade to match the latest version of sanic.

ci(framework tests): skip failing sanic test [backport #6539 to 1.16]

---

.github/workflows/test_frameworks.yml

Backport of #6539 to 1.17
The sanic framework tests have recently started failing a single test: `test_redirect_with_params`, which has a weird error relating to string formatting: `"sanic%20test" != "sanic test"`.
This test's assertion was subtly changed in the most recent release of sanic by altering the string formatting of the asserted string value, and this only started failing once the new version of sanic (23.3.0) was released, so we can consider skipping this test for now until we upgrade to match the latest version of sanic.

ci(framework tests): skip failing sanic test [backport #6539 to 1.17]

---

ddtrace/appsec/_asm_request_context.py
ddtrace/appsec/_metrics.py
ddtrace/appsec/handlers.py
ddtrace/appsec/iast/_metrics.py
ddtrace/appsec/iast/_taint_tracking/aspects.py
ddtrace/appsec/iast/taint_sinks/_base.py
ddtrace/appsec/utils.py
tests/appsec/test_telemetry.py

Aspects handle all kinds of errors with an Exception and report an error log metric if something goes wrong.
There is a Deduplication class that controls duplicate messages, preventing the reporting of numerous repeated errors.

feat(iast): report telemetry error logs

---

ddtrace/contrib/asgi/__init__.py
ddtrace/contrib/fastapi/__init__.py
ddtrace/contrib/sanic/__init__.py
ddtrace/contrib/starlette/__init__.py

This pull request updates the documentation of ASGI integrations to be clearer about the requirements of legacy Python versions, and to conform with [this docstring](https://github.com/DataDog/dd-trace-py/blob/45532233f6e9e70c84c2946aab06513c947f4500/ddtrace/contrib/asyncio/provider.py#L12).

docs(asgi): clarify python version requirements for AsyncioContextProvider

---

.github/workflows/system-tests.yml

System tests are mandatory to merge PR. The issue is that system tests requires an API_KEY stored in secrests, and it's not possible to share secrets when the PR comes from a forks. Hacks exists, but none of them is fully satisfaying.
Turns out that this key does not have to be a valid key for most scenario, as long as nothing is tested on the backend.
So trying to use a fake key.

ci: use a fake key for system tests

---

ddtrace/appsec/_capabilities.py
ddtrace/appsec/_remoteconfiguration.py
ddtrace/appsec/processor.py
ddtrace/appsec/utils.py
ddtrace/internal/remoteconfig/client.py
tests/appsec/test_remoteconfiguration.py

Fixes a potencial cyclic import when importing `appsec.utils._appsec_rc_capabilities`.

chore: move some functions to a new appsec/_capabilities.py file to avoid cyclic imports

---

.github/workflows/system-tests.yml

Backport of #6702 to 1.17
System tests are mandatory to merge PR. The issue is that system tests requires an API_KEY stored in secrests, and it's not possible to share secrets when the PR comes from a forks. Hacks exists, but none of them is fully satisfaying.
Turns out that this key does not have to be a valid key for most scenario, as long as nothing is tested on the backend.
So trying to use a fake key.

ci: use a fake key for system tests [backport #6702 to 1.17]

---

.github/workflows/lib-injection.yml

The lib injection workflow defined a job called test which might race and conflict with the test job from the CircleCI configuration. This would case the state of the test suite to be reported by a GitHub app that is not the expected one, thus blocking PRs where the CircleCI run terminates quickly.
We also include the workflow file as a trigger for these jobs.

ci: rename lib-injection job name

---

ddtrace/appsec/iast/_taint_tracking/aspects.py
tests/appsec/iast/aspects/test_str_aspect.py

chore(iast): repr propagation

---

ddtrace/appsec/iast/_taint_tracking/aspects.py
tests/appsec/iast/aspects/test_str_aspect.py
tests/appsec/iast/fixtures/aspects/str_methods.py

chore(iast): zfill propagation

---

ddtrace/debugging/_probe/remoteconfig.py
releasenotes/notes/fix-di-probe-status-emit-on-no-data-eb9b13d0343f92c7.yaml
tests/debugging/test_debugger.py

Backport of #6714 to 1.18
We ensure that probe status update are sent when due, regardless of whether the RCM worker has found new data. This fixes a regression introduced by the IPC refactor for the RCM client.

fix(debugging): emit probe status updates unconditionally [backport #6714 to 1.18]

---

ddtrace/debugging/_probe/remoteconfig.py
releasenotes/notes/fix-di-probe-status-emit-on-no-data-eb9b13d0343f92c7.yaml
tests/debugging/test_debugger.py

Backport of #6714 to 1.16
We ensure that probe status update are sent when due, regardless of whether the RCM worker has found new data. This fixes a regression introduced by the IPC refactor for the RCM client.

fix(debugging): emit probe status updates unconditionally [backport #6714 to 1.16]

---

ddtrace/debugging/_probe/remoteconfig.py
releasenotes/notes/fix-di-probe-status-emit-on-no-data-eb9b13d0343f92c7.yaml
tests/debugging/test_debugger.py

Backport of #6714 to 1.17
We ensure that probe status update are sent when due, regardless of whether the RCM worker has found new data. This fixes a regression introduced by the IPC refactor for the RCM client.

fix(debugging): emit probe status updates unconditionally [backport #6714 to 1.17]

---

ddtrace/internal/injection.py
ddtrace/internal/utils/inspection.py
releasenotes/notes/fix-debugger-multiple-inject-locs-2dd1d33810cf6405.yaml
tests/internal/test_injection.py
tests/submod/stuff.py

Backport of #6759 to 1.18
Some code constructs might be translated into non-linear bytecode, meaning that some line numbers might appear multiple time, as code blocks might be copied in multiple place (e.g. finally blocks).

fix(debugging): handle multiple injection points [backport #6759 to 1.18]

---

tests/telemetry/test_writer.py

Test failure was introduced in https://github.com/DataDog/dd-trace-py/commit/619c4bfb5e368dfea3ee152c611c7a8b590a8040
This fix was cherry-picked from the following commit: https://github.com/DataDog/dd-trace-py/pull/6712/commits/e738aa9a2a8cb0838bf090c2ead4d8637322043b

ci(telemetry): fix failing instrumentation telemetry test [backport to 1.18]

---

.github/workflows/system-tests.yml

We backport the changes to the system tests GitHub action configuration to get its benefits on lower release branches, since the jobs are now marked as required on PRs.

ci: backport of conditional system tests configuration

---

docs/contributing-integrations.rst
docs/contributing-testing.rst
docs/contributing.rst
docs/releasenotes.rst

The docs still point to some `.rst` files, causing a 404 as mentioned in [this issue](https://github.com/DataDog/dd-trace-py/issues/6788)

fix(docs): fix more broken links still pointing to .rst files

---

ddtrace/debugging/_probe/remoteconfig.py
tests/debugging/probe/test_remoteconfig.py

We make a slight refactor of the DI remote config adapter to allow manually emitting probe status message. This way we can remove the `sleep` calls in tests and force the probe status emission, thus removing any potential race conditions. This should remove the flakiness in these tests.

test(debugging): remove flakiness in RCM tests

---

.github/workflows/build_deploy.yml
.github/workflows/build_python_3.yml
.github/workflows/system-tests.yml
.github/workflows/test_frameworks.yml
.gitlab/benchmarks.yml
docs/spelling_wordlist.txt
releasenotes/notes/setup-oom-errors-426c9951d5c9ed57.yaml
riotfile.py
setup.py

When running setup.py extensions with the CMake parameter "-j", it could potentially raise an out-of-memory error. If someone wants to expedite the ddtrace installation, they should manually set the "CMAKE_BUILD_PARALLEL_LEVEL" environment variable.

fix(setup): out-of-memory error

---

ddtrace/profiling/_threading.pyx
docs/spelling_wordlist.txt
releasenotes/notes/fix-profiler-thread-link-cbe14bf53e6071db.yaml

Backport of #6798 to 1.17
We use the C API to retrieve the thread ID of the current thread to create a link between threads and objects. This way we protect ourselves from frameworks such as gevent that might turn thread IDs into task IDs.
Tested with a sample application that the endpoint information is attached to profiles with this change.

fix(profiling): ensure correct thread link [backport #6798 to 1.17]

---

pyproject.toml
scripts/needs_testrun.py
setup.py

1.x branch was reporting a wrong version number in ddtrace/_version.py
- ensure setuptools scm configuration is given both in toml file and in setup.py to fix that problem

chore(dev): fix version for trunk branch

---

.github/workflows/system-tests.yml

Partial revert of https://github.com/DataDog/dd-trace-py/pull/6780
As 1.x version problem was fixed in https://github.com/DataDog/dd-trace-py/pull/6826, we shouldn't need to pin system tests version for the trunk branch anymore.

chore(tracer): unpin system-tests

---

docs/requirements.txt
hatch.toml

Follow up to: https://github.com/DataDog/dd-trace-py/commit/463855774f3bf11da62110511d284167345ea378
Unfortunately the dependencies used to generate [docs in read the docs](https://github.com/DataDog/dd-trace-py/blob/9ee956f1e970c49b6d6a9fbac5fc97e959bc3ce2/docs/requirements.txt#L8) differ from the [dependencies used in ci](https://github.com/DataDog/dd-trace-py/blob/1.x/hatch.toml#L75). This problem is beyond the scope of this PR.

docs: pin furo in readthedocs

---

lib-injection/Dockerfile
releasenotes/notes/lib-inject-8dcd6537312fddf3.yaml

Change the base library injection image from `busybox` to `alpine` to make the image more compatible with other software environments.
`libdl.so.2: cannot open shared object file: No such file or directory` errors have been reported in customer environments which prevents application containers from starting up when using [library injection](https://docs.datadoghq.com/tracing/trace_collection/library_injection_local/?tab=kubernetes#step-3---tag-your-pods-with-unified-service-tags). Likely this is due to some other software such as instrumentation or security that modifies the command run in the container. The modified command fails as the `libdl.so.2` shared library isn't present in the `busybox`-based image.
The `busybox` image [lacks many standard C …

fix(lib-inject): use alpine base image

---

docs/configuration.rst
releasenotes/notes/resource-sampling-f80db0b13d995c83.yaml

We want to make the following updates to resource matching before anouncing its release:
1. Merge tags matching
2. Evaluate which integrations we set resource name on late, change the ones that can have resource set upon span creation, and have a list of those for which resource matching will not currently work.
To that end we'll revert the release note and config option for now.

chore(sampling): remove config and release note for resource matching

---

ddtrace/appsec/_api_security/api_manager.py
ddtrace/appsec/_api_security/processors.json
ddtrace/appsec/_constants.py
ddtrace/appsec/processor.py
tests/appsec/api_security/test_schema_fuzz.py

Add first support for security scanners for api security.
- use libddwaf to find and track confidential and pii data into api security schemas
- use `waf.context.processor` for processor input address to be compliant with last version of the RFC
- add tests

chore(asm): security scanners for api security

---

.github/workflows/build_deploy.yml
setup.py

Revert change to `setup.py` in #6826 and ensure `cython<3` is used for sdist build. This issue is breaking the alpine build and blocking releases.
This was tested locally by building an sdist and then building with alpine.

chore(ci): fix sdist build

---

ddtrace/ext/sql.py
tests/.suitespec.json

Resolves an [unreleased bug](https://github.com/DataDog/dd-trace-py/commit/371f3f7d0c026a921645579744cd17575eec86ec) in the starlette and sqlalchemy integrations. This issue went undetected due to misconfigured components in `suitesspec.json`. 
Sample failure: https://circleci.com/gh/DataDog/dd-trace-py/2981533

ci(sqlalchemy/starlette): add back missing constant

---

tests/suitespec.py

https://github.com/DataDog/dd-trace-py/pull/6879 made Circle CI precheck tests failed.
This PR fix that.

chore(ci): fix precheck

---

ddtrace/appsec/iast/_taint_tracking/__init__.py
ddtrace/appsec/iast/_utils.py
ddtrace/appsec/iast/processor.py
ddtrace/appsec/iast/reporter.py
ddtrace/appsec/iast/taint_sinks/_base.py
tests/appsec/iast/taint_sinks/test_insecure_cookie.py

Insecure Cookies report should not send line number and empty file

fix(iast): invalid line number on insecure cookie report

---

tests/suitespec.py

https://github.com/DataDog/dd-trace-py/pull/6879 made Circle CI precheck tests failed.
This PR fix that.

chore(ci): fix precheck (#6882) [backport 1.19]

---

ddtrace/contrib/openai/_endpoint_hooks.py
ddtrace/contrib/openai/patch.py
releasenotes/notes/fix-openai-stream-error-unfinished-span-d62df398912b0f56.yaml
tests/contrib/openai/cassettes/completion_stream_wrong_api_key.yaml
tests/contrib/openai/test_openai.py
tests/snapshots/tests.contrib.openai.test_openai.test_span_finish_on_stream_error.json

Resolves #6769.
This PR fixes an unhandled case in our OpenAI integration specifically regarding streamed `Chat/Completion` requests that have errors and result in an empty response. In this case, streamed spans were not finished (as we avoided finishing streamed response spans until the underlying generator was exhausted) because we did not handle empty response cases. The fix here is to add manual span finishing for streamed response spans with error, as we already do that for non-streamed spans.
The only risk is if there are requests that we trace that might result in a non-empty response even with an error. This is highly unlikely as we shouldn't get any response if the corresponding request was faulty.
Note: this PR also moves tagging prompt token usage information to the …

fix(openai): ensure streamed spans with error are manually finished

---

ddtrace/internal/core.py

This change reduces the very large amount of debug logs that the Core API can generate in the course of normal usage, especially with AppSec enabled.

chore(internal): reduce log volume from core api (#6886) [backport 1.19]

---

tests/debugging/mocking.py
tests/debugging/test_debugger.py

We make the probe status log message generation synchronous to prevent race conditions in tests that might result in flakiness.

test(debugger): synchronous probe status generation

---

ddtrace/debugging/_debugger.py
ddtrace/debugging/_probe/remoteconfig.py
tests/debugging/exception/test_auto_instrument.py
tests/debugging/probe/test_remoteconfig.py

We improve some of the coding in the debugging area to make the logic easier to follow and to remove some unnecessary complexity.

chore(debugging): general coding improvements

---

.github/workflows/build_deploy.yml

We currently delete Python 3.12 wheels when publishing to PyPI, but `2.x` should support 3.12.

chore(ci): don't delete Python 3.12 wheels when publishing to PyPI

---

docs/upgrading.rst
releasenotes/notes/release-2.0-3af0045e2261bd02.yaml

This fixes the failing CI docs job because of a duplicated anchor in reno release notes.

ci(docs): update deprecated interface anchor

---

ddtrace/contrib/botocore/patch.py

We are using boto3 to push protobuf encoded data to kinesis. We noticed the following error in our logs:
```
Unable to parse payload, unable to inject trace context.
```
It seems that any data that isn't json encoded will cause this error message. I don't believe there's any requirement for data to be json encoded so I believe this should not be an error level log.

chore(botocore): don't log an error when kinesis payload isn't json

---

docs/upgrading.rst
releasenotes/notes/release-2.0-3af0045e2261bd02.yaml

This fixes a failure in build_docs that we thought was handled by #6968 but [appears not to have been](https://circleci.com/gh/DataDog/dd-trace-py/3010124).

chore(docs): fix ref by turning it into a simple link

---

docs/spelling_wordlist.txt
docs/upgrading.rst
releasenotes/notes/release-2.0-3af0045e2261bd02.yaml

fix(docs): fix broken link to release note anchor

---

.github/workflows/build_deploy.yml
.github/workflows/build_python_3.yml

ci: fix build release actions [backport 2.0]

---

.circleci/config.yml

Backport b406ab127c09fd5dbc55a6a0d3a80adf2cf18f0e from #6941 to 1.17.
Note: this isn't a direct backport since the files modified in the original PR weren't introduced yet in `1.17`
This switches the output to use pipe mode (which, among other things, prints every line without wrapping) as a safety mechanism to prevents reoccurrences of secrets leaking into logs because they were unexpected wrapped by `riot`'s pretty output. 
`riot -v run` is the only place where we show environment variables.
Note that this is an immediate band-aid, not a long-term strategy.

ci: use pipe mode when calling riot run in run-test-suite  [backport 1.17]

---

pyproject.toml
setup.py

This change pins setuptools_scm below version 8, which dropped support for Python versions <=3.6.

chore: pin setuptools_scm

---

pyproject.toml
setup.py

This change pins setuptools_scm below version 8, which dropped support for Python versions <=3.6.

chore: pin setuptools_scm [backport #7005 to 1.18]

---

ddtrace/contrib/botocore/patch.py

(this is a duplicate of the change in https://github.com/DataDog/dd-trace-py/pull/6970 but targeting 1.19). 
We are using boto3 to push protobuf encoded data to kinesis. We noticed the following error in our logs:
```
Unable to parse payload, unable to inject trace context.
```
It seems that any data that isn't json encoded will cause this error message. I don't believe there's any requirement for data to be json encoded so I believe this should not be an error level log.

chore(kinesis): don't log an error when kinesis payload isn't json [backport to 1.19]

---

ddtrace/contrib/redis/asyncio_patch.py
ddtrace/contrib/trace_utils_redis.py
releasenotes/notes/fix-redis-exception-handling-32964d6cc673c7bc.yaml
releasenotes/notes/fix-redis-unbound-variable-5fc0bbfa777cc2b0.yaml
tests/contrib/redis/test_redis.py
tests/contrib/redis/test_redis_asyncio.py
tests/snapshots/tests.contrib.redis.test_redis_asyncio.test_connection_error.json

The exception handling in Redis monkey patch in completely bugged, making Redis+ddtrace broken.
This fixes it.
Fixes #6993

fix(redis): don't use unbound variable

---

.circleci/config.templ.yml
.circleci/config.yml
scripts/compile-and-prune-test-requirements

These were missed in https://github.com/DataDog/dd-trace-py/pull/6941 .
```
romain.komorn@COMP-CLXFH7L2J3 dd-trace-py % rg -. 'riot.*-v'  | rg -- '-P'
.circleci/config.templ.yml:                      command: riot -P -v run -s 'wait' << parameters.wait >>
.circleci/config.templ.yml:          command: "riot list -i tracer | circleci tests split | xargs -I PY riot -P -v generate --python=PY"
.circleci/config.yml:            riot -P -v run --pass-env -s circleci-gen-config -- -v
scripts/compile-and-prune-test-requirements:    [[ ! -f .riot/requirements/"$hash".txt ]] && $RIOT_CMD -P -v requirements "$hash"
scripts/run-test-suite:    if ! $DDTEST_CMD riot -P -v run --exitfirst --pass-env -s $hash $DDTRACE_FLAG $COVERAGE_FLAG; then
```
```
romain.komorn@COMP-CLXFH7L2J3 dd-trace-py % rg -. …
```

ci: add pipe mode to more CI utils using riot

---

scripts/release.py

I tested this manually for rc, patch, and minor releases, all seemed good. 
This also makes an improvement, allowing the addition of sub-sections within our normal sections. Before something like `###### Whatever` as a header would cause issues due to us splitting on `###` now a more complex regex was introduced to avoid splitting on those, and therefore dropping them.

chore(release): make script support 1.x and 2.x releases

---

scripts/gen_circleci_config.py
tests/suitespec.py

Backport 0dede174c57a99e98cbb87f78874198199b9a6ed from #7000 to 1.18.
This fixes failing `pre_check` failing wherever https://github.com/DataDog/dd-trace-py/pull/6941 was merged.
`tests/.suitespec.json` being modified should trigger the doctests in `tests/suitespec.py`, otherwise a change there may merge, and then cause `pre_check` to fail on `2.x` where the `scripts/*py` tests are run.
Also, the non `.py` scripts in `scripts/` should still cause tests to run.
As part of this backport, some now-defunct `riot` calls are converted to use `-P` to match up with https://github.com/DataDog/dd-trace-py/pull/7023 .

ci: reflect scripts/run-test-suite fix harness dependency in suitespec test [backport 1.18]

---

ddtrace/propagation/_database_monitoring.py

This change is a forward port of a fix from https://github.com/DataDog/dd-trace-py/pull/7034 that makes the database monitoring propagation logic compatible with Python 2.7. That change was necessary because the 1.x release line still supports Python 2.
It's not strictly necessary to forward-port this change, but I think it makes sense to do forward ports when they're easy, since it will tend to keep future backports from getting hairy.
There's no changelog because this change is a no-op.

fix(dbm): ensure peer service is str for py2.7

---

ddtrace/internal/wrapping/__init__.py
releasenotes/notes/fix-py311-closure-wrapping-fed33b584d65a844.yaml
tests/internal/test_wrapping.py

We fix the bytecode wrapping for closures to ensure that the frame objects don't end up referencing missing data, ultimately resulting in a segmentation fault in profiling tools.
Fixes #6701.

fix(internal): closure bytecode wrapping for Python 3.11

---

.circleci/config.templ.yml
.circleci/config.yml
scripts/compile-and-prune-test-requirements

Backport 7c7885245d339b76c2813bc1e805dd8cb9bb9889 from #7023 to 1.18.
These were missed in https://github.com/DataDog/dd-trace-py/pull/6941 .
```
romain.komorn@COMP-CLXFH7L2J3 dd-trace-py % rg -. 'riot.*-v'  | rg -- '-P'
.circleci/config.templ.yml:                      command: riot -P -v run -s 'wait' << parameters.wait >>
.circleci/config.templ.yml:          command: "riot list -i tracer | circleci tests split | xargs -I PY riot -P -v generate --python=PY"
.circleci/config.yml:            riot -P -v run --pass-env -s circleci-gen-config -- -v
scripts/compile-and-prune-test-requirements:    [[ ! -f .riot/requirements/"$hash".txt ]] && $RIOT_CMD -P -v requirements "$hash"
scripts/run-test-suite:    if ! $DDTEST_CMD riot -P -v run --exitfirst --pass-env -s $hash $DDTRACE_FLAG …
```

ci: add pipe mode to more CI utils using riot [backport 1.18]

---

.circleci/config.templ.yml
.circleci/config.yml
scripts/compile-and-prune-test-requirements

Backport 7c7885245d339b76c2813bc1e805dd8cb9bb9889 from #7023 to 1.19.
These were missed in https://github.com/DataDog/dd-trace-py/pull/6941 .
```
romain.komorn@COMP-CLXFH7L2J3 dd-trace-py % rg -. 'riot.*-v'  | rg -- '-P'
.circleci/config.templ.yml:                      command: riot -P -v run -s 'wait' << parameters.wait >>
.circleci/config.templ.yml:          command: "riot list -i tracer | circleci tests split | xargs -I PY riot -P -v generate --python=PY"
.circleci/config.yml:            riot -P -v run --pass-env -s circleci-gen-config -- -v
scripts/compile-and-prune-test-requirements:    [[ ! -f .riot/requirements/"$hash".txt ]] && $RIOT_CMD -P -v requirements "$hash"
scripts/run-test-suite:    if ! $DDTEST_CMD riot -P -v run --exitfirst --pass-env -s $hash $DDTRACE_FLAG …
```

ci: add pipe mode to more CI utils using riot [backport 1.19]

---

.circleci/config.templ.yml
.circleci/config.yml
scripts/compile-and-prune-test-requirements

Backport 7c7885245d339b76c2813bc1e805dd8cb9bb9889 from #7023 to 1.20.
These were missed in https://github.com/DataDog/dd-trace-py/pull/6941 .
```
romain.komorn@COMP-CLXFH7L2J3 dd-trace-py % rg -. 'riot.*-v'  | rg -- '-P'
.circleci/config.templ.yml:                      command: riot -P -v run -s 'wait' << parameters.wait >>
.circleci/config.templ.yml:          command: "riot list -i tracer | circleci tests split | xargs -I PY riot -P -v generate --python=PY"
.circleci/config.yml:            riot -P -v run --pass-env -s circleci-gen-config -- -v
scripts/compile-and-prune-test-requirements:    [[ ! -f .riot/requirements/"$hash".txt ]] && $RIOT_CMD -P -v requirements "$hash"
scripts/run-test-suite:    if ! $DDTEST_CMD riot -P -v run --exitfirst --pass-env -s $hash $DDTRACE_FLAG …
```

ci: add pipe mode to more CI utils using riot [backport 1.20]

---

ddtrace/internal/compat.py
tests/contrib/redis/test_redis.py

Reverts the following commit: https://github.com/DataDog/dd-trace-py/pull/7025/commits/80ff6f357f08efaefd53d446a50247f2eb0897d3.
Fixes the failing v1.20.2 build action: https://github.com/DataDog/dd-trace-py/actions/runs/6314357914/job/17150041391.
- Mock is installed in all dd-trace-py venvs: https://github.com/DataDog/dd-trace-py/blob/v1.20.2/riotfile.py#L90
- Mock is not listed as a ddtrace dependency: https://github.com/DataDog/dd-trace-py/blob/v1.20.2/setup.py#L538
- These two conditions create a scenario where this [commit](https://github.com/DataDog/dd-trace-py/pull/7025/commits/80ff6f357f08efaefd53d446a50247f2eb0897d3) passed all tests but caused `ddtrace` smoke tests in the 1.20.2 release to fail. Since mock is not a ddtrace dependency this import should should be declared in …

ci(redis): fix python<3.7 support

---

tests/debugging/mocking.py
tests/debugging/test_debugger.py

Backport of #6927 to 1.19
We make the probe status log message generation synchronous to prevent race conditions in tests that might result in flakiness.

test(debugger): synchronous probe status generation [backport #6927 to 1.19]

---

ddtrace/settings/config.py
tests/contrib/flask/test_flask_appsec.py

Small guard for unreleased feature merged in https://github.com/DataDog/dd-trace-py/pull/6929
- add check to not fill the queue if remote config is not enabled
- add max size to the queue to avoid any memory leak in case of a remote config malfunction that would lead to never empty the queue. If the queue is full, new service names will be silently discarded.
- improve flask unit test of the feature to avoid flakiness due to thread concurrency.

chore(tracer): limit memory usage for extra services reports

---

tests/.suitespec.json
tests/suitespec.py

All tests suites should run if the CircleCI config, templates (or preemptively: anything CircleCI related), changes.

ci: add circle CI directory to harness suite

---

ddtrace/internal/wrapping/__init__.py
releasenotes/notes/fix-py311-closure-wrapping-fed33b584d65a844.yaml
tests/internal/test_wrapping.py

Backport of #7044 to 1.20
We fix the bytecode wrapping for closures to ensure that the frame objects don't end up referencing missing data, ultimately resulting in a segmentation fault in profiling tools.
Fixes #6701.

fix(internal): closure bytecode wrapping for Python 3.11 [backport #7044 to 1.20]

---

ddtrace/settings/config.py
tests/contrib/flask/test_flask_appsec.py

Reverts DataDog/dd-trace-py#7060, which broke the `internal` test suite due to that suite not being run pre-merge.

chore(tracer): revert "limit memory usage for extra services reports"

---

ddtrace/settings/config.py
tests/contrib/flask/test_flask_appsec.py
tests/internal/service_name/test_extra_services_names.py

Fix tests of PR #7064
Revert #7074

chore(rcm): fix remote config extra service name test

---

ddtrace/appsec/_ddwaf/ddwaf_types.py

drop python 2 in ddwaf_types.py

chore(asm): migrate ddwaf_types to drop python2 compatibility

---

ddtrace/contrib/logging/__init__.py

docs: append timestamp awareness to logs docs and example code

---

ddtrace/settings/config.py

https://github.com/DataDog/dd-trace-py/pull/6929 introduced a bug that makes remote config spawns an infinite number of processes, but only on mac osx with some specific settings.
This is related to the different default settings of the multiprocessing python module (not the same on unix and osx).
This fix the problem.

chore(tracer): defuse osx thread bomb

---

.github/workflows/system-tests.yml

On system tests YAML file, #7053 tried to simplify the yaml file by moving an `if` from each step to jobs.
The issue is that if system-tests are note needed, jobs never starts, and those jobs are mandatory.
Rollbacking this change, and moving the new condition (the initial purpose was fixing the nightly jobs) on each step.

chore(ci): rollback simplification made on #7053

---

ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.cpp
ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.cpp
ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.h
ddtrace/appsec/_iast/_taint_tracking/__init__.py
tests/appsec/iast/aspects/test_join_aspect_fixtures.py
tests/appsec/iast/taint_sinks/test_command_injection_redacted.py

IAST C++ refactor, remove `object_len` from `new_pyobject_id` C++ function

chore(iast): remove new_pyobject_id param

---

ddtrace/ext/git.py
releasenotes/notes/fix-git-version-extraction-8db3a639976e725c.yaml
tests/tracer/test_ci.py

This PR aims to fix Git version extraction which was relying on getting the last argument of `git --version` output. This is invalid since it could happen that the output: `git version 2.39.3 (Apple Git-145)`
[JIRA issue](https://datadoghq.atlassian.net/browse/CIAPP-7884?atlOrigin=eyJpIjoiNGJhODU0YzM3NDlkNGMxZWIzNWI4NWE3NzJmOWE0NmYiLCJwIjoiaiJ9)
Instead, we extract the Git version with the 3rd argument (`2.39.3`), which is in line with how `dd-trace-js` operates.

fix(git): fix git version extraction

---

ddtrace/appsec/_constants.py

drop python 2 in appsec/_constants.py
follows https://github.com/DataDog/dd-trace-py/pull/7102

chore(asm): migrate appsec constants to drop python2 compatibility

---

ddtrace/appsec/_trace_utils.py

drop python 2 in `appsec/_trace_utils.py`
follows https://github.com/DataDog/dd-trace-py/pull/7117

chore(asm): migrate appsec trace_utils to drop python2 compatibility

---

ddtrace/appsec/_constants.py
ddtrace/appsec/_processor.py

- drop python 2 and  six and attr dependency in appsec/_processor.py
- small fixes on names and types in appsec/_constants.py
follows https://github.com/DataDog/dd-trace-py/pull/7118
Motivation : we don't need attr anymore as features needed are covered by python 3 api in dataclasses.

chore(asm): migrate appsec processor to drop python2 compatibility

---

ddtrace/appsec/_utils.py

drop python 2 and ddtrace.internal.compat dependency in appsec/_utils.py
follows https://github.com/DataDog/dd-trace-py/pull/7135

chore(asm): migrate appsec utils to drop python2 compatibility

---

ddtrace/appsec/_handlers.py

drop python 2 and six dependency in `appsec/_handlers.py`
follows https://github.com/DataDog/dd-trace-py/pull/7136

chore(asm): migrate appsec handlers to drop python2 compatibility

---

ddtrace/settings/config.py

Follow-up on the fix for "Mac OS X spawn bomb" https://github.com/DataDog/dd-trace-py/pull/7096
There is no "fork" context in Win32 platform, only "spawn"
Fixes Windows builds, currently broken: https://github.com/DataDog/dd-trace-py/actions/runs/6387793629

chore(asm): fix win32 fork usage error

---

ddtrace/profiling/profiler.py
docs/spelling_wordlist.txt
releasenotes/notes/fix-profiler-protobuf-if-needed-9c64068ab27e7352.yaml

Importing protobuf when this is a shared dependency with the tracer might cause issues. We make sure to import it only if necessary. This means that we can avoid importing the protobuf Python module when exporting exclusively via libdatadog.

fix(profiling): import protobuf only if needed

---

ddtrace/contrib/kafka/patch.py
ddtrace/internal/datastreams/__init__.py
ddtrace/internal/datastreams/kafka.py
ddtrace/internal/datastreams/processor.py
ddtrace/tracer.py
pyproject.toml
releasenotes/notes/dsm-fix-offsets-and-metrics-7e34b2734667e986.yaml
tests/contrib/kafka/test_kafka.py
tests/datastreams/test_processor.py
tests/utils.py

This commit swaps out all remaining DSM code in the kafka integration to
use the core API.
This commit also contains the addition of two tests and fixes to the
commit wrapper which were required to safely transition.

chore(kafka): use core api for data streams monitoring [backport 1.20]

---

pyproject.toml

Similarly to https://github.com/DataDog/dd-trace-py/pull/6914/files , this forces `setuptools_scm` to use a versioning scheme that works with systems-tests.

ci: force setuptools_scm to use guess-next-dev scheme in 2.0

---

ddtrace/internal/gitmetadata.py
ddtrace/internal/remoteconfig/client.py
ddtrace/settings/dynamic_instrumentation.py
releasenotes/notes/fix-rc-git-metadata-in-request-bc95d730be17831a.yaml

We make sure that git metadata is added to the tags when making requests for configuration to the agent. This allows SCI to work as expected with services that rely on the git metadata to be transmitted with RC requests.
We also add the tags to every DI upload.
This will be covered by system tests.

fix(rcm): add git metadata to requests

---

ddtrace/appsec/_deduplications.py

drop python 2 in appsec/_deduplication.py and small refactor
follows https://github.com/DataDog/dd-trace-py/pull/7138

chore(asm): migrate appsec deduplication to drop python2 compatibility

---

ddtrace/appsec/_iast/taint_sinks/_base.py
ddtrace/appsec/_iast/taint_sinks/ast_taint.py
ddtrace/appsec/_iast/taint_sinks/command_injection.py
ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
ddtrace/appsec/_iast/taint_sinks/path_traversal.py
ddtrace/appsec/_iast/taint_sinks/weak_cipher.py
ddtrace/appsec/_iast/taint_sinks/weak_hash.py
ddtrace/contrib/dbapi/__init__.py
ddtrace/contrib/dbapi_async/__init__.py
releasenotes/notes/fix-executed-sink-telemetry-metric-1d961a4e618a4843.yaml

Backport 0a8275454acfd115d4cd6a05a008562175308264 from #7149 to 2.0.
IAST: Fix executed sink telemetry metric by extracting it from the report and calling it separately, as we may reach the sink point without reporting a vulnerability.
Testing strategy: Existing telemetry system tests (there is a corner case that they are not covering at the moment)

fix(iast): decouple executed sink metric call [backport 2.0]

---

.github/workflows/system-tests.yml

add FastAPI new system-tests variant to github workflow.
As ASM plan to add support for FastAPI, the new FastAPI weblog should be used in our CI.
https://github.com/DataDog/system-tests/pull/1663

chore(tests): add fastapi new variant to github workflow

---

releasenotes/notes/ci_visibility-fix-distributed_tracing-733103ba3a19f3f7.yaml

For some reason, build_docs' spellcheck didn't catch this and it merged.

chore: fix typo in release note

---

ddtrace/contrib/langchain/constants.py
ddtrace/contrib/langchain/patch.py
releasenotes/notes/langchain-fix-imports-dddd44cd581e6baa.yaml
tests/contrib/langchain/test_langchain_patch.py

Fixes #7123.
This PR fixes an issue brought up with `langchain>=0.0.300` where directly importing from langchain root is not supported anymore, which was previously not an issue in our patch wrapping code. The fix was to import the base modules containing the functions this integration wraps around before wrapping to get around the import error from trying to access directly from langchain root.

fix(langchain): avoid direct root imports from langchain

---

docs/configuration.rst

The example for Dogstatsd configuration was incorrect.

docs: correct dogstatsd example configuration

---

ddtrace/appsec/_iast/_taint_tracking/aspects.py
releasenotes/notes/iast-fix-fstring-format-d8f0fc1533c75cdb.yaml
tests/appsec/iast/aspects/test_str_py3.py
tests/appsec/iast/fixtures/aspects/str_methods_py3.py

IAST: There was a missing step in the construction of f-strings replacements for IAST patching, where non-string values should be formatted. This was causing a segfault in those cases, and this PR should fix them. 
As you can see in the PEP 498, in the code equivalence section, a format call is performed: https://peps.python.org/pep-0498/#code-equivalence
Also add unit tests as regression tests.

fix(asm): fix segfault in IAST for f-string formatting of non-text values

---

.github/workflows/lib-injection.yml
.gitlab/build-deb-rpm.sh
lib-injection/Dockerfile
releasenotes/notes/lib-inject-permissions-8222a09585eb5350.yaml

Package files should not be world-writable. Users noticed injected ddtrace package files being flagged by security scanners.
In particular the `bytecode` package in Python 3.7 includes world-writable sources files.
The existing tests should cover that the feature still works in the K8s library injection. The existing assertion for the permissions on the files is updated to assert that the permission is correctly applied to all package files.
For the deb/rpm I manually tested the commands that the build runs and validated that the files are not world-writable.
There may be unknown situations where Python packages require these permissions. In the worst-case with these situations the application may crash due to an unexpected exception at runtime.

fix(lib-inject): set correct permissions on package files

---

.gitlab/build-deb-rpm.sh
lib-injection/Dockerfile
releasenotes/notes/lib-inject-version-9236836076cc3c79.yaml

There are no code changes in `1.20.5` only packaging updates so we can safely use the previous tracer version. This allows us to rapidly get fix `1.20.5` out without waiting for the corresponding PyPI build to finish which takes 4+ hours.
The risk is that users who are confused when manually specifying version `1.20.5` in their K8s chart or deb/rpm install will see ``ddtrace`` version [`1.20.4`](https://pypi.org/project/ddtrace/1.20.4/) installed instead. There is no harm as the 1.20.5 release is only fixing a packaging issue for the library injection packages.
This change will be reverted as soon as `1.20.5` is released to ensure subsequent `1.20` releases include the code changes to the library.

chore(ci): pin the library version being built

---

.gitlab/build-deb-rpm.sh
lib-injection/Dockerfile
releasenotes/notes/lib-inject-version-9236836076cc3c79.yaml

In reviewing the 1.20.5 release it was noticed that a [fix](https://github.com/DataDog/dd-trace-py/pull/7230) got merged and but not released to the 1.20 branch.
This makes #7255 semantically incorrect and we have to release a 1.20.5 version.

revert: chore(ci): pin the library version being built

---

pyproject.toml

Compatibility with #7185's link update. In reference to #7176
#7185 updated reference from https://github.com/DataDog/dd-trace-py/blob/master/CHANGELOG.md -> https://github.com/DataDog/dd-trace-py/releases

chore: update pypi changelog link

---

ddtrace/contrib/openai/patch.py

This PR refactors the `patch()` function for the openai integration such that each function is dynamically wrapped using a pre-declared mapping between openai functions and wrapper functions. There is no change in functionality, this just cleans up almost 200 lines of duplicate code.

chore(openai): refactor patch wrapping code

---

tests/contrib/logging/test_logging.py

This change skips the `test_log_DD_TAGS` test case, which has been reliably [failing](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/48104/workflows/ed977f44-51d2-410c-a13d-5b9204414ad9/jobs/3105560) on trunk since https://github.com/DataDog/dd-trace-py/commit/fe6c74ff4e6de5b726393ad618318cc64ba6cd3a.
This test should be unskipped when it's fixed to pass reliably.
@mabdinur your commit is the oldest one that exhibits this issue. I'm not sure if it's related.

chore: skip reliably failing test

---

ddtrace/appsec/_handlers.py
releasenotes/notes/asm-fix-flask-body-blocking-aa4836d70f8e1ea8.yaml
tests/appsec/app.py
tests/appsec/appsec_utils.py
tests/appsec/test_handlers.py
tests/appsec/test_remoteconfiguration_e2e.py

Backport cc35fafb140a2ee171c8e5f4066d2f2469e61b75 from #7266 to 2.0.
This PR fix https://github.com/DataDog/dd-trace-py/issues/7265
Local and debug Flask applications hang when Appsec `_on_request_span_modifier` handler calls to `wsgi_input.read()` and the body is empty
file1.py:
```python
@app.route("/test-body-hang", methods=["POST"])
def apsec_body_hang():
return "OK", 200
if __name__ == "__main__":
app.run(port=8000)
```
then:
```bash
DD_APPSEC_ENABLED=true poetry run ddtrace-run python -m file1:app
DD_APPSEC_ENABLED=true python -m ddtrace-run python file1.py
```
If you make an empty POST request `curl -X POST '127.0.0.1:8000/'` Flask hangs when the ASM handler tries to read the body

fix(appsec): flask hangs on empty body requests [backport 2.0]

---

ddtrace/appsec/handlers.py
releasenotes/notes/asm-fix-flask-body-blocking-aa4836d70f8e1ea8.yaml
tests/appsec/app.py
tests/appsec/appsec_utils.py
tests/appsec/test_handlers.py
tests/appsec/test_remoteconfiguration_e2e.py

Backport cc35fafb140a2ee171c8e5f4066d2f2469e61b75 from #7266 to 1.20.
This PR fix https://github.com/DataDog/dd-trace-py/issues/7265
Local and debug Flask applications hang when Appsec `_on_request_span_modifier` handler calls to `wsgi_input.read()` and the body is empty
file1.py:
```python
@app.route("/test-body-hang", methods=["POST"])
def apsec_body_hang():
return "OK", 200
if __name__ == "__main__":
app.run(port=8000)
```
then:
```bash
DD_APPSEC_ENABLED=true poetry run ddtrace-run python -m file1:app
DD_APPSEC_ENABLED=true python -m ddtrace-run python file1.py
```
If you make an empty POST request `curl -X POST '127.0.0.1:8000/'` Flask hangs when the ASM handler tries to read the body

fix(appsec): flask hangs on empty body requests [backport 1.20]

---

ddtrace/appsec/trace_utils.py
releasenotes/notes/fix_manual_keep_for_users_events-3b4b37a9ef9e50ea.yaml
tests/appsec/test_appsec_trace_utils.py

Partial backport of https://github.com/DataDog/dd-trace-py/pull/6633 to fix user events being dropped by the tracer

fix(asm): fix manual keep for user event

---

ddtrace/appsec/handlers.py
releasenotes/notes/asm-fix-flask-body-blocking-aa4836d70f8e1ea8.yaml
tests/appsec/app.py
tests/appsec/appsec_utils.py
tests/appsec/test_handlers.py
tests/appsec/test_remoteconfiguration_e2e.py

Backport cc35fafb140a2ee171c8e5f4066d2f2469e61b75 from #7266 to 1.19.
This PR fix https://github.com/DataDog/dd-trace-py/issues/7265
Local and debug Flask applications hang when Appsec `_on_request_span_modifier` handler calls to `wsgi_input.read()` and the body is empty
file1.py:
```python
@app.route("/test-body-hang", methods=["POST"])
def apsec_body_hang():
return "OK", 200
if __name__ == "__main__":
app.run(port=8000)
```
then:
```bash
DD_APPSEC_ENABLED=true poetry run ddtrace-run python -m file1:app
DD_APPSEC_ENABLED=true python -m ddtrace-run python file1.py
```
If you make an empty POST request `curl -X POST '127.0.0.1:8000/'` Flask hangs when the ASM handler tries to read the body

fix(appsec): flask hangs on empty body requests [backport 1.19]

---

ddtrace/contrib/unittest/patch.py
releasenotes/notes/fix-unittest-git-patch-887a3963d4f58d8b.yaml

This PR aims to fix [this GitHub issue](https://github.com/DataDog/dd-trace-py/issues/7257) from dd-trace-py, which was causing unexpected log messages. Related JIRA issue: [CIVIS-7652](https://datadoghq.atlassian.net/browse/CIVIS-7652?atlOrigin=eyJpIjoiM2EyMTI2YzY5YWI3NDBiMGI5OWE2ODk3MzE1Nzc2ZDUiLCJwIjoiaiJ9).
Now, the `unittest` integration will enable `CIVisibility` only if `unittest` is running any tests. This will prevent log messages as CIVisibility won't be enabled until tests are detected.
[CIVIS-7652]: https://datadoghq.atlassian.net/browse/CIVIS-7652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ci_visibility): fixes unittest enabling the CI VIsibility plugin

---

ddtrace/debugging/_debugger.py
releasenotes/notes/fix-debugger-same-module-wrapping-5fa0653ca015874c.yaml
tests/debugging/test_debugger.py

Fix a typo that caused a module lookup to fail with a KeyError exception, even though it was followed by a check against None.
This caused function probes on the same module that was not yet loaded to fail to instrument and be reported in the ``ERROR`` status in the UI.

fix(debugging): function probes on same lazy module

---

tests/appsec/conftest.py

Bumping the telemetry service interval to 120 seconds from 10 for tests only.
`tests/appsec/iast/test_telemetry.py` can be failing as flaky on CircleCI due to threads sleeping for too long, causing the telemetry service to flush the values before the main test thread finished, creating AssertionError on telemetry content.
This would make the whole `appsec` test suite to fail.

chore(asm): tests, change telemetry service interval to 120 seconds to avoid flakyness

---

ddtrace/appsec/iast/_taint_tracking/Aspects/AspectExtend.cpp
ddtrace/appsec/iast/_taint_tracking/TaintTracking/TaintRange.h
releasenotes/notes/iast-fix-id-collisions-87da1c4229876398.yaml
tests/appsec/iast/aspects/test_bytearray_extend_aspect.py
tests/appsec/iast/taint_tracking/test_native_taint_range.py

Backport 77540c1a28495937170cba1d2b45230b70d9dae2 from #7318 to 1-x.
Fix potential string id collisions that could cause false positives with non tainted objects being marked as tainted.

fix(iast): potential string id collisions [backport 1.x]

---

ddtrace/internal/ci_visibility/writer.py
ddtrace/internal/writer/__init__.py
ddtrace/internal/writer/writer.py
ddtrace/tracer.py
releasenotes/notes/fix-make-tracer-acknowledge-agent-sampling-decisions-2919150951ed1b81.yaml

This reverts commit ec3e14d3fb008d0104951abca31790f32ee35a32. Which caused the tracer to ignore trace-agent sampling rates, often times leading to much higher ingestion rates.
I tested this manually by looking at `datadog.trace_agent.receiver.traces_priority` between <1.19 and >=1.19. 
<1.19:  some P1 and a lot of P0 
>=1.19: a lot more P1 (and  a little more  P-1) and no P0
Basically before 1.19 there were a ton of traces getting dropped with P0 priority due to the trace-agent recommended rates. After 1.19 we ignored the trace-agent recommended rates, leading to no P0 traces, and far more being sampled overall.

fix(sampling): revert "refactor(writer): handle agent responses in the tracer (#6178)"

---

.github/workflows/build_deploy.yml

Ensure that the wheel build job is run when all the relevant files are touched by a PR.

ci: run build job on more paths

---

ddtrace/debugging/_async.py
ddtrace/debugging/_debugger.py
ddtrace/debugging/_encoding.py
ddtrace/debugging/_exception/auto_instrument.py
ddtrace/debugging/_expressions.py
ddtrace/debugging/_function/discovery.py
ddtrace/debugging/_function/store.py
ddtrace/debugging/_probe/model.py
ddtrace/debugging/_probe/registry.py
ddtrace/debugging/_probe/remoteconfig.py
ddtrace/debugging/_probe/status.py
ddtrace/debugging/_safety.py
ddtrace/debugging/_signal/collector.py
ddtrace/debugging/_signal/model.py
ddtrace/debugging/_signal/snapshot.py
ddtrace/debugging/_signal/tracing.py
ddtrace/debugging/_signal/utils.py
ddtrace/debugging/_uploader.py
ddtrace/internal/module.py
tests/debugging/exploration/_config.py
tests/debugging/exploration/_coverage.py
tests/debugging/exploration/_profiler.py
tests/debugging/exploration/debugger.py
tests/debugging/mocking.py
tests/debugging/test_async.py

With support for Python 2 now dropped we can switch to using type annotations instead of comments. This will allow us to use the latest versions of tools like mypy on the codebase.
The changes in this PR have been generated (and just slightly tweaked) with [com2ann](https://github.com/ilevkivskyi/com2ann).

chore(debugging): convert type comments to annotations

---

ddtrace/appsec/iast/_patches/json_tainting.py
releasenotes/notes/iast-fix-lazy-taint-json-encoder-89cdd9aba0351d96.yaml
tests/appsec/iast/test_taint_utils.py

Backport fee5ed0204b4ff225c4e4e76ae2456807f776b07 from #7348 to 1.x.
IAST: Fix an issue where JSON encoder would fail at encoding a tainted dict or list.

fix(iast): patch json.encoder to encode LazyTaintDict as dict [backport 1.x]

---

.github/workflows/test_frameworks.yml

This PR is against the 1.20 branch, since it and below are the ones that are failing or timing out on the Sanic framework test.
Sanic test is consistently timing out or failing on <=1.20. Skipping for now.  I tried to add a time based skip, however I ran into some issues getting the time in an easily comparable format.

ci(sanic): skip sanic framework test

---

.github/workflows/test_frameworks.yml

Currently if you just edit only test_frameworks.yml, we won't actually run those tests, which keeps PRs that do this from being merged since the tests don't run e.g.: https://github.com/DataDog/dd-trace-py/pull/7374 
With this change we check if this file is changed, if so, we make sure to run them.

ci: run framework tests if frameworks.yml modified

---

.github/workflows/test_frameworks.yml

I made a PR before for Sanic failing/timing out always on 1.20 and 1.19 and it seemed that this wasn't the case for 2.x at the time. However, after looking at more PRs it seems that this test_suite is actually super flakey for 2.x as well, so skipping for now.

ci(sanic): disable sanic framework test

---

.github/workflows/test_frameworks.yml

Backport of #7379 to 1.20
Currently if you just edit only test_frameworks.yml, we won't actually run those tests, which keeps PRs that do this from being merged since the tests don't run e.g.: https://github.com/DataDog/dd-trace-py/pull/7374 
With this change we check if this file is changed, if so, we make sure to run them.

ci: run framework tests if frameworks.yml modified [backport #7379 to 1.20]

---

tests/profiling/test_profiler.py

We improve the logic around log call testing in a profiling collector test to ensure that we ignore non-profiling-related log calls. This fixes recent flakiness probably caused by some extra logging done by other products that would show up in the fixed profiling test.

test(profiling): collector log tests

---

tests/conftest.py

A few telemetry tests are consistently failing with the following exception when getting telemetry payloads from the testagent: `http.client.RemoteDisconnected: Remote end closed connection without response`. These failures was first detected on [f86ac69](https://github.com/DataDog/dd-trace-py/commit/f86ac699ef96e9a2b7c7df511b081f292d5cda9e) ([failing tests](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/49186/workflows/3f35aef2-d79b-47f6-b16b-2cfae26f26c2/jobs/3160014)) and the root cause is still unclear. 
This PR attempts to address these connection issues by setting a 5 second timeout on tracer-testagent connections. This will hopefully reduce the rate of premature disconnection.

ci(telemetry): tries to resolve RemoteDisconnected errors in tests

---

ddtrace/settings/config.py
releasenotes/notes/lift_max_tag_length_setting-366b3b60d458355b.yaml
tests/tracer/test_settings.py

Previously the limit was 512 characters (still the default). However, a user reached out saying they wanted to send larger tags than this, and we aren't aware of a version to limit it to strictly 512 characters.

chore(tracing): remove 512 char limit on X_DATADOG_TAGS_MAX_LENGTH

---

ddtrace/internal/injection.py

Some source lines might be implemented over multiple bytecode offset blocks, and in some cases some are just NOPs. We reduce the chances of double injections by ignoring these instruction offsets

chore(internal): ignore NOP in bytecode hook injection

---

.github/workflows/test_frameworks.yml

We make sure that the framework tests don't fail when they are actually skipped on a PR, and no exploration data is generated.

ci: do not fail on missing exploration data

---

hatch.toml

TL;DR is:
- flake8-builtin 2.2.0 was released recently, adds rule A004 for shadowing builtins https://github.com/gforcada/flake8-builtins/blob/main/CHANGES.rst
It's breaking pre_check for [some backport PRs](https://github.com/DataDog/dd-trace-py/pull/7418) (and I assume it would also break builds for releases)
- Release branches (1.*, 2.0 , and 2.1)  still use flake8 in CI as part of hatch run style
- We need to either pin flake8-builtin to 2.1.0  or backport :pr: [chore: migrate to ruff](https://github.com/DataDog/dd-trace-py/pull/6658/files) to those branches
I started by backporting, but the conflict was pretty ugly given the number of files changed. Therefore I propose we just merge the pin to 2.1 and backport to other versions.

ci: pin flake8 builtins to avoid failing on 2.2.0

---

hatch.toml

TL;DR is:
- flake8-builtin 2.2.0 was released recently, adds rule A004 for shadowing builtins
https://github.com/gforcada/flake8-builtins/blob/main/CHANGES.rst It's breaking pre_check for [some backport
PRs](https://github.com/DataDog/dd-trace-py/pull/7418) (and I assume it would also break builds for releases)
- Release branches (1.*, 2.0 , and 2.1) still use flake8 in CI as part of hatch run style
- We need to either pin flake8-builtin to 2.1.0 or backport :pr: [chore: migrate to ruff](https://github.com/DataDog/dd-trace-py/pull/6658/files) to those branches
I started by backporting, but the conflict was pretty ugly given the number of files changed. Therefore I propose we just merge the pin to 2.1 and backport to other versions. …

ci: pin flake8 builtins to avoid failing on flake8-builtins==2.2.0 (backport #7466 to 1.20)

---

hatch.toml

TL;DR is:
- flake8-builtin 2.2.0 was released recently, adds rule A004 for shadowing builtins
https://github.com/gforcada/flake8-builtins/blob/main/CHANGES.rst It's breaking pre_check for [some backport
PRs](https://github.com/DataDog/dd-trace-py/pull/7418) (and I assume it would also break builds for releases)
- Release branches (1.*, 2.0 , and 2.1) still use flake8 in CI as part of hatch run style
- We need to either pin flake8-builtin to 2.1.0 or backport :pr: [chore: migrate to ruff](https://github.com/DataDog/dd-trace-py/pull/6658/files) to those branches
I started by backporting, but the conflict was pretty ugly given the number of files changed. Therefore I propose we just merge the pin to 2.1 and backport to other versions. …

ci: pin flake8 builtins to avoid failing on flake8-builtins==2.2.0 (backport #7466 to 2.0)

---

hatch.toml
pyproject.toml

This change fixes https://github.com/DataDog/dd-trace-py/issues/4664 by upgrading `black` and `click` to the current latest versions.

ci: upgrade black now that 2.7 support is no longer a requirement

---

ddtrace/contrib/django/__init__.py

This change fixes https://github.com/DataDog/dd-trace-py/issues/2991 by updating the documentation of the configuration parameter `config.django.http.trace_query_string` to match its actual behavior encoded in the test suite.
This approach seems to be an appropriate fix because the issue ticket uses existing documentation as a source of truth and doesn't articulate any issues with the current behavior.

docs: fix documentation of django trace_query_string configuration param

---

.github/workflows/test_frameworks.yml

We make the reporting step conditional like the other steps in the framework test suites to avoid it failing on the missing working directory.

ci(debugging): fix exploration reporting step

---

tests/tracer/runtime/test_metric_collectors.py

Failure: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/49395/workflows/fe5d73de-dc61-4175-bd94-149ee4aaa4f4/jobs/3172352

chore(tracer): skip flaky runtime metrics test

---

ddtrace/appsec/_ddwaf/__init__.py
ddtrace/appsec/_ddwaf/ddwaf_types.py
setup.py
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json

- Update libddwaf to 1.15.0
- Use the new `musl` linux builds for libddwaf installation

chore(asm): update to libddwaf 1.15.0

---

ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
tests/appsec/iast/taint_sinks/test_insecure_cookie.py
tests/contrib/flask/test_flask_appsec_iast.py

Fix Cookie vulnerability errors: When IAST finds ONE of the Cookie vulnerabilities, it stops and returns the report. IAST should check all possible Cookie vulnerabilities and report if any one, two, or all three types of Cookie vulnerabilities are found.

fix(iast): report cookies vuln

---

ddtrace/appsec/iast/taint_sinks/insecure_cookie.py
tests/appsec/iast/taint_sinks/test_insecure_cookie.py
tests/contrib/flask/test_flask_appsec_iast.py

Backport 58a59680b4518f43503c582ec963d2dc12ee1b0e from #7497 to 1.20.
Fix Cookie vulnerability errors: When IAST finds ONE of the Cookie vulnerabilities, it stops and returns the report. IAST should check all possible Cookie vulnerabilities and report if any one, two, or all three types of Cookie vulnerabilities are found.

fix(iast): report cookies vuln [backport 1.20]

---

ddtrace/internal/ci_visibility/recorder.py

This PR adds the `_DD_CIVISIBILITY_ITR_PREVENT_TEST_SKIPPING` environment variable which disables test skipping in order to benchmark and test code coverage and ITR more efficiently. This will be an internal environment variable, so no changelog is needed.

feat(itr): add internal env var to prevent test skipping

---

ddtrace/internal/_encoding.pyi
ddtrace/internal/_encoding.pyx
ddtrace/internal/writer/writer.py
releasenotes/notes/fix-msgpack-errors-3fcf9f77a77c9786.yaml
tests/integration/test_integration.py
tests/tracer/test_encoders.py
tests/utils.py

Reverts: https://github.com/DataDog/dd-trace-py/pull/7277 and lints files to pass ci.
Note - there is a chain of reversions here. https://github.com/DataDog/dd-trace-py/pull/7277 (ci fix) reverted https://github.com/DataDog/dd-trace-py/commit/fe6c74ff4e6de5b726393ad618318cc64ba6cd3a (encoding fix) which reverted https://github.com/DataDog/dd-trace-py/pull/7099 (feature to debug v05 encoding). Here we are rolling back to the first revert.
There is an edge case were the string table used by the v0.5 encoder swaps entries. This corrupts trace payloads. In this PR I will add debug logs that will help us reproduce the behavior that triggered incident-24455.
RISK
This PR maybe increase memory usage when v0.5 is enabled. With this change we will hold a reference to a all encoded spans until the …

Revert "Revert "fix(tracing): fix msgpack import error""

---

ddtrace/appsec/_iast/_taint_tracking/aspects.py
tests/appsec/iast/aspects/test_encode_decode_aspect.py
tests/appsec/iast/aspects/test_format_aspect_fixtures.py
tests/appsec/iast/aspects/test_index_aspect_fixtures.py
tests/appsec/iast/aspects/test_str_aspect.py
tests/appsec/iast/fixtures/aspects/str_methods.py

IAST Aspects report a log metric each time an exception is raised. We noticed an application that wants to raise and control exceptions, such as in this dummy example:
```python
my_data = {"element1": 1}
is_element2_in_my_data = False
try:
my_data["element1"]
is_element2_in_my_data = True
except KeyError:
pass
```
Those operations should not log a metric.

fix(iast): remove logs metrics noise

---

ddtrace/appsec/_iast/_ast/ast_patching.py
ddtrace/appsec/_iast/_stacktrace.c
ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSlice.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.cpp
ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.h
ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintedObject.cpp
ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintedObject.h
ddtrace/appsec/_iast/_taint_tracking/__init__.py
ddtrace/appsec/_iast/_taint_tracking/aspects.py

Backport IAST refactors and fixes from 2.x to 2.1:
https://github.com/DataDog/dd-trace-py/pull/7485: Remove NULL returns from get_file_and_line native function
https://github.com/DataDog/dd-trace-py/pull/7340: Store hash and id separately in tx_taint_map
https://github.com/DataDog/dd-trace-py/pull/7192: Slice propagation ranges error

chore(iast): slice propagation ranges error and store hash and id separately [Backport 2.1]

---

tests/internal/test_injection.py

We remove support for Python 2 in injection tests.

test: remove Python 2 support from injection tests

---

pyproject.toml

This change avoids linting the `_version.py` file with black during `hatch run lint:style`. The file is autogenerated and not committed to source control, so this only affects local runs of the linter.

ci: don't black the version file

---

ddtrace/tracer.py

Automated conversion of type comments to annotations with com2ann, which we can do now that Py2 is not supported.

chore: com2ann tracer.py

---

tests/appsec/iast/aspects/test_common_aspects.py

Change `teardown` to `teardown_module` as it should be run after all tests are executed instead of after each one.

chore(test): change teardown to teardown_module

---

ddtrace/appsec/_iast/_overhead_control_engine.py
ddtrace/appsec/_iast/taint_sinks/_base.py
riotfile.py
tests/appsec/iast/taint_sinks/test_command_injection.py
tests/appsec/iast/taint_sinks/test_insecure_cookie.py
tests/appsec/iast/taint_sinks/test_path_traversal.py
tests/appsec/iast/taint_sinks/test_sql_injection.py
tests/appsec/iast/taint_sinks/test_ssrf.py
tests/appsec/iast/taint_sinks/test_weak_cipher.py
tests/appsec/iast/taint_sinks/test_weak_hash.py
tests/contrib/django/test_django_appsec_iast.py

IAST vulnerability deduplication: If we report and attach a vulnerability to a span, we don't report it again until 1 hour later to reduce the number of spans marked as "manually keep."
Example of this feature on Java Tracer: https://github.com/DataDog/dd-trace-java/pull/4855

feat(iast): vulnerability deduplication

---

.gitignore
benchmarks/appsec_iast_propagation/scenario.py
ddtrace/appsec/_iast/_ast/visitor.py
ddtrace/appsec/_iast/_taint_tracking/aspects.py
ddtrace/appsec/_iast/taint_sinks/__init__.py
ddtrace/appsec/_iast/taint_sinks/ast_taint.py
ddtrace/appsec/_iast/taint_sinks/command_injection.py
releasenotes/notes/iast-fix-ast-patching-arguments-67b838a27a6c01f8.yaml
tests/appsec/iast/aspects/test_common_aspects.py
tests/appsec/iast/aspects/test_encode_decode_aspect.py
tests/appsec/iast/aspects/test_str_aspect.py
tests/appsec/iast/fixtures/aspects/callees.py
tests/appsec/iast/fixtures/aspects/str_methods.py
tests/appsec/iast/taint_tracking/test_native_taint_range.py
tests/contrib/django/django_app/appsec_urls.py

IAST: This PR addresses two interconnected issues in the AST patching process that replaces code with aspects:
1. Resolves a bug that occurs during AST patching, where a custom function or method call could be replaced by one of our aspects. In situations where the function has a different number of arguments than our aspects, a runtime ``TypeError`` occurs. This is fixed by ensuring that all aspects now receive ``(*args, **kwargs)`` and pass them appropriately to the original custom function or method.
2. Fixes another bug in the AST patching process, where the module of a function is incorrectly passed as the first argument to the aspect. In cases where it's a custom function, our logic inadvertently passes the module received as the first argument to the original function. The solution …

fix(iast): prepare aspect for unexpected args (#7491) [backport 2.0]

---

scripts/release.py

This change fixes a crash I encountered in `scripts/release.py` by truncating the release notes before using them in a Github API request. This is a fallback for a case that probably indicates other problems with the script and generally will not change the release notes.

chore: limit github release notes size

---

ddtrace/opentelemetry/__init__.py
ddtrace/opentelemetry/_span.py
ddtrace/opentelemetry/_trace.py
scripts/release.py

The current inconsistency between the 2.2 branch and the 2.2.0rc1 tag is the result of me having manually created this branch and tag instead of letting the publishing of the release handle that for me. I've updated release process documentation to clarify this point.

chore: fix inconsistency in release process by updating 2.2 from 2.x

---

tests/.suitespec.json
tests/contrib/logbook/test_logbook_logging.py
tests/contrib/loguru/test_loguru_logging.py
tests/contrib/structlog/test_structlog_logging.py

Updates tests in new logging libraries to reflect new 128 bit trace_id standard. 
The logic remains untouched that 128bit trace_ids continue to only be logged iff `_128_bit_trace_id_logging_enabled` is `True`

ci(logging): update tests to reflect new 128 bit trace_id standard

---

ddtrace/contrib/unittest/patch.py

This PR ensures that code coverage for ITR won't be enabled if it is a skipped `unittest` test.

fix(itr): add skipped test check for coverage

---

.gitignore
hatch.toml
hooks/scripts/run-black.sh

Introduces lint:black_check as a new hatch script, and uses it during pre-commit so that pre-commit fails when black would reformat files, rather than reformat the file, succeed, and leave an uncommitted file behind.
This also tweaks .gitignore to ignore cmake_build which was introduced in 3ad6f126c0e7b97a74f58c2ea66ff368ac273b2c .

ci: make black fail pre-commit rather than succeed and modify file

---

ddtrace/bootstrap/sitecustomize.py
tests/commands/test_runner.py

This change ensures that using both `ddtrace-run` and `import ddtrace.auto` does not double load the `ddtrace.bootstrap.sitecustomize` module, which has unexpected behavior.
The reason we double load `ddtrace.bootstrap.sitecustomize` today is because with `ddtrace-run` `ddtrace.bootstrap.sitecustomize` gets imported as `sitecustomize` and will get added to the `sys.modules` cache under `sitecustomize` name. Then when we go to `import ddtrace.auto`, which imports `ddtrace.bootstrap.sitecustomize` the module gets loaded again since `ddtrace.bootstrap.sitecustomize` is not in the `sys.modules` cache.
This change ensures that whenever we load `ddtrace.bootstrap.sitecustomize` we explicitly add the module to `sys.modules` cache to avoid re-loading it again when `ddtrace.auto` imports it.

chore(core): make ddtrace-run and import ddtrace.run compatible with no side effects

---

ddtrace/appsec/_iast/_stacktrace.c
releasenotes/notes/iast-fix-stacktrace-leak-82032de411963780.yaml

This PR contiunes the work of @pablogsal and suggestion in this PR https://github.com/DataDog/dd-trace-py/pull/7112
This PR decref a reference for Current directory variable on C file.

fix(iast): stacktrace leak

---

ddtrace/appsec/_remoteconfiguration.py
ddtrace/internal/remoteconfig/client.py
ddtrace/internal/remoteconfig/worker.py
docs/spelling_wordlist.txt
releasenotes/notes/fix-debugger-rc-instance-954539a2e57b7887.yaml
tests/internal/remoteconfig/test_remoteconfig.py

Backport 1da4fc4761494c16cea7bb547929a1266b699d9b from #7548 to 1.20.
The Remote Configuration Publisher/Subscriber System https://github.com/DataDog/dd-trace-py/pull/5464 restarts all pubsub instances when the application forks (for example, [gunicorn workers](https://docs.gunicorn.org/en/stable/design.html#server-model), uwsgi workers, etc.).
Dynamic Instrumentation needs to update the pubsub instance at this point because the probe mechanism should run in the child process. For that, DI needs the callback as the method of an instance of Debugger, which lives in the child process.
https://github.com/DataDog/dd-trace-py/blob/2.x/ddtrace/debugging/_debugger.py#L276
When the application forks and restarts the subscribers, this happens before the debugger updates its callback instance. 
``` …
```

fix(rcm): update the forking behavior in remote config [backport 1.20]

---

ddtrace/contrib/trace_utils.py
releasenotes/notes/iast-fix-cookie-report-573f444827a1f3f5.yaml
tests/contrib/django/test_django_appsec_iast.py
tests/contrib/flask/test_flask_appsec_iast.py

IAST is independent of Appsec; `iast_enabled` doesn't require `asm_enabled`. With that, this PR introduces a small refactor when both IAST and ASM check the request cookies.

fix(iast): report cookies

---

ddtrace/opentelemetry/_span.py
releasenotes/notes/otel-operation-name-7a2bccb294aed8cd.yaml
tests/opentelemetry/test_span.py
tests/snapshots/tests.opentelemetry.test_context.test_otel_ddtrace_mixed_parenting.json
tests/snapshots/tests.opentelemetry.test_context.test_otel_multithreading.json
tests/snapshots/tests.opentelemetry.test_context.test_otel_span_parenting.json
tests/snapshots/tests.opentelemetry.test_context.test_otel_trace_across_fork.json
tests/snapshots/tests.opentelemetry.test_context.test_otel_trace_multiple_coroutines.json
tests/snapshots/tests.opentelemetry.test_span.test_otel_span_attributes.json
tests/snapshots/tests.opentelemetry.test_span.test_otel_span_attributes_overrides[override0].json
tests/snapshots/tests.opentelemetry.test_span.test_otel_span_attributes_overrides[override1].json
tests/snapshots/tests.opentelemetry.test_span.test_otel_span_attributes_overrides[override2].json
tests/snapshots/tests.opentelemetry.test_span.test_otel_span_attributes_overrides[override3].json
tests/snapshots/tests.opentelemetry.test_span.test_otel_span_attributes_overrides[override4].json
tests/snapshots/tests.opentelemetry.test_span.test_otel_span_kind.json
tests/snapshots/tests.opentelemetry.test_trace.test_distributed_trace_with_flask_app[with_ddtrace_run].json
tests/snapshots/tests.opentelemetry.test_trace.test_distributed_trace_with_flask_app[with_opentelemetry_instrument].json
tests/snapshots/tests.opentelemetry.test_trace.test_otel_start_current_span_with_default_args.json
tests/snapshots/tests.opentelemetry.test_trace.test_otel_start_current_span_without_default_args.json
tests/snapshots/tests.opentelemetry.test_trace.test_otel_start_span_ignore_exceptions.json
tests/snapshots/tests.opentelemetry.test_trace.test_otel_start_span_with_default_args.json
tests/snapshots/tests.opentelemetry.test_trace.test_otel_start_span_without_default_args.json

Resolves: https://github.com/DataDog/dd-trace-py/issues/7543
This changes the mapping of OpenTelemetry semantics to Datadog operation names. 
We are adopting the mapping implemented in [dd-trace-java](https://github.com/DataDog/dd-trace-java/blob/4131e509a94db430b47104769800ec14de5f0a0d/dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/trace/OtelConventions.java#L107). 
Testing is covered by system-tests.

feat(opentelemetry): datadog operation name from semantic conventions

---

ddtrace/internal/ci_visibility/recorder.py

This PR aims to add a new env var called `_DD_CIVISIBILITY_ITR_FORCE_ENABLE_COVERAGE` to force-enable coverage in order to ease debugging efforts.

feat(civis): add force test coverage env var

---

ddtrace/internal/writer/writer.py
docker-compose.yml
releasenotes/notes/fix-writer-concurrent-dictionary-modification-d37e2f918c51578c.yaml
tests/integration/test_integration.py
tests/tracer/test_writer.py

fix(tracing): resolve concurrency bug in health metrics (backport #7413 to 2.2) 

---

ddtrace/appsec/iast/_ast/visitor.py
ddtrace/appsec/iast/_taint_tracking/aspects.py
releasenotes/notes/iast-fix-patching-side-effect-56d0b168e74839fc.yaml
tests/appsec/iast/_ast/fixtures/misleading_methods.py
tests/appsec/iast/_ast/test_proper_patching.py
tests/appsec/iast/aspects/test_common_aspects_generator.py
tests/appsec/iast/fixtures/aspects/callees.py
tests/appsec/iast/fixtures/aspects/obj_callees.py

IAST: This fix resolves an issue where, at AST patching to replace code with IAST aspects, the original function/method was passed as an extra parameter for accurate patching (i.e. check the function inside the aspect), and this strategy lead to unintentionally triggers side effects in methods obtained from an expression (like ``decode`` in ``file.read(n).decode()``), resulting in unexpected multiple calls to the expression (``file.read(n)`` in the example).
---------
Co-authored-by: Alberto Vara <alberto.vara@datadoghq.com>
(cherry picked from commit 601fd6ab7f1eef11134ece39f0d8fd9fa4386f9c)

fix(iast): ast patching side effect (#7638) [backport 1.20]

---

pyproject.toml
releasenotes/notes/fix-setuptools-license-c061c22889799c6c.yaml

Resolves: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/50959/workflows/fc3694ee-c64a-4a56-bd74-94ef0a9d0552/jobs/3258065
This error prevents ddtrace from being installed from source.
This issue was introduced by setuptools v69: https://setuptools.pypa.io/en/stable/history.html#deprecations-and-removals

fix(setuptools): update deprecated license format

---

pyproject.toml
releasenotes/notes/fix-setuptools-license-c061c22889799c6c.yaml

fix(setuptools): update deprecated license format [backport #7684 to 1.20]

---

setup.py

This PR removes redundant `DEBUG_COMPILE` validation

chore: redundant `DEBUG_COMPILE` validation

---

ddtrace/appsec/_iast/_stacktrace.c
ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectExtend.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSlice.cpp
ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.cpp
ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.cpp

For some reason, both Py_DECREF and Py_XDECREF Python C API functions aren't releasing PyObjects correctly. This PR replace all those calls with `Py_DecRef`
```python
for _ in range(5):
gc.collect()
a = sys.gettotalrefcount()
s.get_info_frame(CWD)
gc.collect()
print(sys.gettotalrefcount() - a)
```
Before:
```
python3.11 ddtrace/appsec/_iast/test.py
10
7
7
7
7
```
After
```
python3.11 ddtrace/appsec/_iast/test.py
4
1
1
1
1
```
```python
for _ in range(15):
gc.collect()
a = sys.gettotalrefcount()
b = taint_pyobject(
pyobject="abc",
source_name="dd",
source_value="abc",
source_origin=OriginType.PARAMETER
)
c = "efg"
res = _add_aspect(b, c)
gc.collect()
print(sys.gettotalrefcount() - a)
```
Before:
```
python3.11 ddtrace/appsec/_iast/test2.py
34
9
9
9
9
```
After
```
python3.11 …
```

fix(iast): iast leak for python 3.11

---

.github/workflows/requirements-locks.yml
.github/workflows/testrunner.yml
ddtrace/tracer.py
docker-compose.yml

This PR pins the version of testrunner used in the 1.20 branch. This will allow us to run tests with `python<=3.6`.
The latest testrunner image does not support python<3.7 ([image](https://github.com/datadog/dd-trace-py/pkgs/container/dd-trace-py%2Ftestrunner/150490464?tag=253febbef2d235970f1c71ced77df6fe4fbeb449)):
`command`: `docker run -it ghcr.io/datadog/dd-trace-py/testrunner:latest cat root/.python-version`
`output`:  `3.10.11  3.7.16  3.8.16  3.9.16  3.11.3  3.12-dev`
The second most recent version of testrunner supports `py<3.7` ([image](https://github.com/datadog/dd-trace-py/pkgs/container/dd-trace-py%2Ftestrunner/141140913?tag=0f49c377e3568020d82e8fa2b4f314900deb8f8d)):
`command`: `docker run -it ghcr.io/datadog/dd-trace-py/testrunner:0f49c377e3568020d82e8fa2b4f314900deb8f8d cat …

ci: pin testrunner to test py<3.7 [targets 1.20]

---

ddtrace/bootstrap/preload.py
ddtrace/bootstrap/sitecustomize.py
releasenotes/notes/fix-bootstrap-no-imports-after-module-cleanup-8592af3c81df0576.yaml
tests/internal/test_auto.py
tests/telemetry/test_telemetry_metrics_e2e.py

Backport of #7649 to 2.1
We refactor the logic of the sitecustomize bootstrap script to make it harder to introduce new initialisation logic that can break some of the boilerplate bootstrapping logic, such as the module cleanup mechanism for the support of frameworks like gevent. We move all the logic into a dedicated module, preload, and expose post_preload hooks in case that some code needs to be run after the module cleanup. However, the problem is now slightly shifted towards these hooks. Care must be taken not to register any hooks that import modules that are not already imported during the execution of the preload script.
The test that was supposed to catch the presence of the `threading` module after initialisation when cleaning up the imported modules failed because RC was …

fix(bootstrap): do not load new modules after module cleanup [backport #7649 to 2.1]

---

docs/contributing-testing.rst
docs/spelling_wordlist.txt

This change documents the process of updating the lockfiles for a riot venv that uses the `latest` version specifier.

docs: add instructions documentation on how to update venv locks to latest

---

.circleci/config.templ.yml
docker-compose.yml
tests/integration/test_priority_sampling.py
tests/snapshots/tests.integration.test_priority_sampling.test_agent_sample_rate_keep.json
tests/snapshots/tests.integration.test_priority_sampling.test_agent_sample_rate_reject.json
tests/utils.py

To avoid [regressions](https://github.com/DataDog/dd-trace-py/pull/7333) like #6178 a test case is added to assert that agent sample rates are respected by the tracer.
In order to do this, a new functionality is used in the test agent to customize the sample rates returned by the agent (https://github.com/DataDog/dd-apm-test-agent/pull/149)

chore(tracer): add agent sample rate regression test

---

.github/workflows/test_frameworks.yml

This pull request fixes
[failures](https://github.com/DataDog/dd-trace-py/actions/runs/7085298702/job/19281284381?pr=7819) of the Mako framework test suite caused by the recent release of transitive dependency Chameleon==4.3.0 in
https://github.com/malthe/chameleon/commit/3f7c9044ac243af9b907b40dd4bb9d0e4c074336. Luckily, it turns out that the latest version of Mako doesn't exhibit the same issue, so upgrading the tested version is sufficient to unblock our merges.
@brettlangdon note that if we decide to merge this, someone with the permission to do so will need to update the github action requirement to reference the new framework test name.
(cherry picked from commit f2d38250fc259c11e9b07eeb298eeef34c820404)

ci: test against the latest minor release of Mako [backport 2.3]

---

tests/contrib/openai/test_openai_v0.py

#7759 introduced a regression test for testing openai's ChatCompletion endpoint, but omitted a conditional test skip if the version of openai being tested does not support ChatCompletions (`<=0.26.5`). For some reason this was not being reported in regular CI runs but was being caught on CI runs on the main branch.

chore(ci): fix skipping test if chat completion not available

---

.gitlab-ci.yml
.gitlab/benchmarks.yml
benchmarks/core_api/config.yaml
benchmarks/core_api/scenario.py

The following adds some basic microbenchmarks for the internal core api.
We are trying to measure the following scenarios:
- Calling `core.dispatch`
- When there are no listeners registered for the event
- When there are 10 no-op listeners registered
- Using the `core.context_with_data` context manager
- When there are no listeners registered for the event
- When there are 10 no-op listeners registered
- Creating a context via `core.context_with_data` and then setting 100 keys on it
- Calling `core.get_item` on the root context
- When the key does not exist
- When the key does exist

chore(perf): add microbenchmarks for the internal core api

---

ddtrace/profiling/collector/stack.pyx
releasenotes/notes/fix-profiling-thread-lock-d18f104a9f479be3.yaml

We use the new _PyThread_CurrentFrames and _PyThread_CurrentExceptions to retrieve the current top frames and exceptions for each thread to avoid the use of a lock that has been removed in CPython 3.12.

fix(profiling): thread lock segfault with 3.12

---

tests/tracer/test_logger.py

ci: mark logger test as flaky

---

ddtrace/contrib/openai/patch.py
tests/contrib/openai/test_openai_v0.py
tests/contrib/openai/test_openai_v1.py
tests/internal/test_llmobs.py

This PR changes the request durations metric on the llmobs payloads generated by the openai integration to be in seconds rather than milliseconds as initially written in #7840. This metric should now conform to the documented API for LLMObs payloads.
Note: this PR does not need a release note as sending LLMObs payloads is still in private beta.

fix(openai): change llmobs request duration from milliseconds to seconds

---

ddtrace/contrib/asgi/middleware.py

ensure that asgi middleware instrumentation can handle any query strings, even wrongly encoded ones.
This PR should fix Framework tests / Django 3.1 (with DI coverage) in the github actions.

fix(django): fix decode query strings in asgi middleware

---

docs/configuration.rst

This pull request clarifies the documentation of `DD_TRACE_METHODS` to indicate a recently-discovered failure case when it's used to trace methods from integrated libraries.

docs: add a clarification to the documentation of DD_TRACE_METHODS [APMS-10881]

---

ddtrace/contrib/asgi/middleware.py
tests/contrib/fastapi/test_fastapi_appsec.py

https://github.com/DataDog/dd-trace-py/pull/7220 introduced a bug in the asgi middleware if for some reason, the related asm dispatch function was not registered.
This fix this.
As PR 7220 was not released yet, no release note is necessary for this fix.
Also: add regression test with locally unregistering core callback mechanism

fix(asm): fix asgi core dispatch call

---

ddtrace/internal/ci_visibility/writer.py
ddtrace/internal/writer/__init__.py
ddtrace/internal/writer/writer.py
ddtrace/tracer.py

This prevents coupling the writer to the sampling implementations. The logic is moved to the tracer, which is already coupled with the sampling implementation.
This also centralizes mutation of the samplers to the tracing class. This will simplify future updates (like dynamic configuration of sampling).
This change was previously [reverted](https://github.com/DataDog/dd-trace-py/pull/7333) due to a regression in the sampling behaviour. The regression was due to a missing callback (identified here: https://github.com/DataDog/dd-trace-py/pull/6178/files#r1416553567). To prevent this regression in the future a test case was added in https://github.com/DataDog/dd-trace-py/pull/7805. I confirmed that the test covers the regression by running it locally: 
```
(.venv) ~/d/dd-trace-py ❮❮❮ …
```

refactor(writer): handle agent responses in the tracer

---

releasenotes/notes/trace-api-v05-encoding-reset-string-table-17ee19c026b22af9.yaml

We will need to re-enable spellchecks on docs.

docs: fix typo in release note

---

ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectFormat.cpp
releasenotes/notes/iast-fix-propagation-error-b59b1b0db93c0f23.yaml
tests/appsec/iast/aspects/test_format_aspect_fixtures.py
tests/appsec/iast/aspects/test_format_map_aspect_fixtures.py

IAST: Fix propagation error on ``.format`` string method.
Error partially introduced in: https://github.com/DataDog/dd-trace-py/pull/7772

fix(iast): format aspect propagation error

---

ddtrace/appsec/rules.json
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json

Update appsec event rule static file to 1.10
https://github.com/DataDog/appsec-event-rules/releases/tag/1.10.0

chore(asm): update appsec event rule static file to 1.10

---

ddtrace/appsec/_iast/_taint_tracking/CMakeLists.txt

In order to fix alpine compilation issue:
https://github.com/DataDog/dd-trace-py/actions/runs/7179979155/job/19551323413?pr=7892
Upstream fix in abseil:
https://github.com/abseil/abseil-cpp/commit/4500c2fada4e952037c59bd65e8be1ba0b29f21e

ci: bump absl dependency

---

ddtrace/appsec/iast/_taint_tracking/CMakeLists.txt

Backport 14e5b24f113ab42133fb4505e15742fd91fe1d15 from #7895 to 1.20.
In order to fix alpine compilation issue:
https://github.com/DataDog/dd-trace-py/actions/runs/7179979155/job/19551323413?pr=7892
Upstream fix in abseil:
https://github.com/abseil/abseil-cpp/commit/4500c2fada4e952037c59bd65e8be1ba0b29f21e

ci: bump absl dependency [backport 1.20]

---

setup.py
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json

Update libddwaf to 1.15.1
https://github.com/DataDog/libddwaf/releases/tag/1.15.1

chore(asm): update libddwaf to 1.15.1

---

ddtrace/contrib/trace_utils.py
releasenotes/notes/iast-fix-cookies-error-2084dea1413104bd.yaml
tests/contrib/flask/test_flask_appsec_iast.py
tests/tracer/test_trace_utils.py

Cookies vulnerabilities are only reported  if response cookies are insecure.

fix(iast): insecure cookies error

---

tests/contrib/fastapi/test_fastapi_appsec.py

Small improvement on suspicious request blocking test for query parameters for fastapi to ensure we are decoding query parameters as expected.

test(asm): improve fastapi srb query test

---

ddtrace/appsec/_capabilities.py
ddtrace/bootstrap/preload.py
ddtrace/internal/remoteconfig/client.py
ddtrace/settings/config.py
ddtrace/tracer.py
releasenotes/notes/sample-rate-rc-13119efdf34bc462.yaml
tests/appsec/appsec/test_remoteconfiguration.py
tests/integration/test_settings.py
tests/internal/remoteconfig/test_remoteconfig_client_e2e.py
tests/internal/test_settings.py
tests/utils.py

Add support for remotely configuring the trace sample rate via the Remote Config platform. This enables the trace sample rate to be configured through the Datadog UI, enabling users to easily configure it for their service without requiring a deploy. 
The feature is enabled by default when using `ddtrace-run` or the various injection methods but is not enabled by default for manual usage of the library to avoid unnecessary overhead. Instead, `ddtrace.config.enable_remote_configuration()` is provided for advanced users to enable the functionality.
This extends on #6192 to add a remote config source to configuration items.

feat(tracer): add remote config support of sample rate

---

ddtrace/contrib/trace_utils.py
releasenotes/notes/iast-fix-cookies-error-2084dea1413104bd.yaml
tests/contrib/flask/test_flask_appsec_iast.py
tests/tracer/test_trace_utils.py

Backport fed517046da1798a3c16edc5f5cde311d4953a57 from #7893 to 2.3.
Cookies vulnerabilities are only reported  if response cookies are insecure.

fix(iast): insecure cookies error [backport #7893 to 2.3]

---

ddtrace/contrib/trace_utils.py
releasenotes/notes/iast-fix-cookies-error-2084dea1413104bd.yaml
tests/contrib/flask/test_flask_appsec_iast.py
tests/tracer/test_trace_utils.py

Backport fed517046da1798a3c16edc5f5cde311d4953a57 from #7893 to 1.20.
Cookies vulnerabilities are only reported  if response cookies are insecure.

fix(iast): insecure cookies error [backport #7893 to 1.20]

---

ddtrace/contrib/kafka/patch.py
releasenotes/notes/fix-bug-for-setting-message-key-span-tag-from-kafka-serialization-classes-630b09004a97063a.yaml
tests/contrib/kafka/test_kafka.py

Backport 0e3a2936248fdebe1582503f1861fd6914b8d5e4 from #7725 to 1.20.
Fixes #7674 . Sets `SerializedProducer` span tag for `message.key` by serializing key to bytes. Does not set the tag for a `DeserializedConsumer` unless the key is a `str` or `bytes` since we do not have the serialization function

fix(kafka): message.key span tag for kafka serialization classes [backport 1.20]

---

ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
releasenotes/notes/iast-fix-cookies-name-report-d5c3381d8c951bab.yaml
tests/appsec/iast/taint_sinks/test_insecure_cookie.py

Ensure that Cookies vulnerabilities report only the cookie name

fix(iast): report cookie name

---

ddtrace/appsec/iast/taint_sinks/insecure_cookie.py
releasenotes/notes/iast-fix-cookies-name-report-d5c3381d8c951bab.yaml
riotfile.py
tests/appsec/iast/taint_sinks/test_insecure_cookie.py

Backport ccfc0ab776cb617823421301d51814e6c01ac838 from #7927 to 1.20.
Ensure that Cookies vulnerabilities report only the cookie name

fix(iast): report cookie name [backport 1.20]

---

ddtrace/appsec/_iast/_patches/json_tainting.py
ddtrace/appsec/_iast/_taint_utils.py
releasenotes/notes/less_imports_for_iast_tainting-d38a2ad26ad98f40.yaml

backport of https://github.com/DataDog/dd-trace-py/pull/7923 to 2.4

fix(asm): remove import and dependency to avoid circular import [backport 2.4]

---

ddtrace/internal/_encoding.pyx
releasenotes/notes/fix-span-link-trace-id-encoding-errror-abe142ac4a6c5fc3.yaml

Attempts to resolve https://github.com/DataDog/dd-trace-py/issues/7701 by replacing `numbers.Number` with `ddtrace.internal.compat.NumericType`. Hopefully this resolves this weird cython typing issue. 
Testing strategy: I could not reproduce this bug in a unit test. I plan to test this fix on impacted internal services.
Note: This bug only impacts the `v0.4` span encoder. `DD_TRACE_API_VERSION` must be set to `v0.4` to reproduce this bug (`DD_TRACE_API_VERSION` was upgraded from `v0.4` to `v0.5` in `ddtrace>2.3`)

fix(encoding): resolves v04 span links encoding bug

---

ddtrace/contrib/pytest/plugin.py
ddtrace/internal/ci_visibility/constants.py
ddtrace/internal/ci_visibility/utils.py
ddtrace/settings/config.py
docs/configuration.rst
releasenotes/notes/ci_visibility-feat-civisbility_specifci_logger-c3205b659f4ae6fd.yaml
riotfile.py

This introduces the `DD_CIVISIBILITY_LOG_LEVEL` env var, which adds a log handler to the root logger that filters messages specifically from the CI Visibility-related paths (`ddtrace.internal.ci_visibility` and `ddtrace.ext.git`). The use of `DD_TRACE_DEBUG` preempts this behavior and maintains the original debug behavior. 
This is to support better logging for products like the `pytest` plugin, where logging to `pytest`'s plugin is both intrusive, and results in double-logging due to the stream handler on the `DDTrace` logger.
The handler is added to the root logger, instead of the `DDTrace` logger, in order to preserve the latter's log levels (specifically for the `FileHandler`).
This PR enables the behavior by default for `pytest`, and is considered a feature (the extra logging is not …

feat(ci_visibilty): introduce CI Visibility-specific log handler controlled by env var

---

ddtrace/contrib/aiohttp/__init__.py
ddtrace/contrib/aiohttp/patch.py
docker-compose.yml
releasenotes/notes/add-aiohttp-split-by-domain-f8f3242025c96cc1.yaml
tests/contrib/aiohttp/test_aiohttp_client.py
tests/snapshots/tests.contrib.aiohttp.test_aiohttp_client.test_configure_service_name_split_by_domain.json

Adds `split_by_domain` flag for the aiohttp_client so we can use the domain name of requests as the service name.
This is already an option for a number of the other request clients ([httpx](https://ddtrace.readthedocs.io/en/stable/integrations.html#id81), [requests](https://ddtrace.readthedocs.io/en/stable/integrations.html#id153), [urllib3](https://ddtrace.readthedocs.io/en/stable/integrations.html#urllib3)).
Includes a happy path test.
Risk seems low; we are adding new functionality that is by default disabled

feat(aiohttp): add split_by_domain option

---

ddtrace/internal/telemetry/writer.py
ddtrace/settings/config.py
ddtrace/tracer.py
docker-compose.yml
tests/telemetry/test_writer.py
tests/tracer/test_tracer.py
tests/utils.py

This reverts commit 34f2d3b8dbb2c17dc07fffa75974b0e2f2e2384b.
We are going to make some changes to the strategy.

Revert "chore(tracing): add first trace telemetry (#7844)"

---

ddtrace/_monkey.py
ddtrace/settings/config.py
releasenotes/notes/lazy-load-instrumentation-telemetry-again-f1ae23c302e234c4.yaml

In a previous PR, we lazily-loaded `telemetry_writer` during init, unless it was disabled. This is important because it has a very high cold start cost, as detailed in [the pr](https://github.com/DataDog/dd-trace-py/pull/7683).
Unfortunately another [PR](https://github.com/DataDog/dd-trace-py/commit/c328aea335b8a0f319d96220c592ac442c66bb79#diff-b79457a3006017376c6ffaaeb34f3ffafa4f7f12e8f28dc96307faa196fd3e58R659) which landed in the same release also imported this upon init, so the effect of #7683 was basically moot.
I then discovered another path where we import the telemetry writer without checking if it is enabled.
This PR fixes this, and thus we see no telemetry writer loaded in the cold start trace:
https://ddserverless.datadoghq.com/apm/trace/14863221237695016030?colorBy=service&env= …

feat: lazy load instrumentation telemetry everywhere

---

scripts/run-test-suite
tests/appsec/appsec/test_processor.py
tests/appsec/iast_memcheck/test_iast_mem_check.py
tests/appsec/integrations/test_remoteconfiguration_e2e.py
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json

IAST:
- Improved some tests that used to be flaky so they are not anymore.
- Expanded expiration date for memory check tests.

chore(iast): fix flaky tests

---

.github/workflows/system-tests.yml

Configure parametric test to get the python tracer in same way as sytem-tests.
The variable PYTHON_DDTRACE_PACKAGE will no longer be necessary after merge the system-tests PR "robertomonteromiguel/parametric_use_load_binary_python"
Once system-tests PR is merged we will create a new dd-trace-py PR to remove PYTHON_DDTRACE_PACKAGE definitively.

ci: configure parametric test to get the python tracer in same way as system-tests

---

ddtrace/internal/telemetry/writer.py
ddtrace/settings/config.py
tests/telemetry/test_telemetry.py

Add metadata about ddtrace installation to app-started events. These values will be used to track customer onboarding via Single Step Instrumentation.
Jira: [Update Python library to handle install signature](https://datadoghq.atlassian.net/browse/AIT-9230)

chore(telemetry): track ddtrace installations

---

ddtrace/appsec/_iast/taint_sinks/command_injection.py

`is_pyobject_tainted` is faster than `get_tainted_ranges`

chore(iast): cmdi performance

---

ddtrace/appsec/_trace_utils.py
releasenotes/notes/fix_bool_report_for_appsec_custom_event-da5503b0fbb78c95.yaml

For custom appsec events, python tracer was reporting boolean properties as `True` and `False` while other tracers are using `true`/`false`. This PR fixes that discrepancy. 
A specific test should be added to system tests to ensure all tracers follow the same standard.

fix(asm): fix boolean property reporting for appsec

---

CHANGELOG.md

This change fixes https://github.com/DataDog/dd-trace-py/issues/7999 by updating the link to release notes. In the future we plan to have a single page containing all of the release notes for the entire history of the library.

docs: fix broken release notes link in changelog document

---

tests/contrib/aws_lambda/test_aws_lambda.py
tests/contrib/redis/test_redis_cluster_asyncio.py

This pull request marks a flaky test and makes some tests permissive of a deprecation warning raised by a third-party library probably related to redis.

ci: fix a few broken tests

---

tests/contrib/asyncpg/test_asyncpg.py
tests/contrib/aws_lambda/test_aws_lambda.py
tests/contrib/django/test_django.py
tests/contrib/django/test_django_snapshots.py
tests/contrib/httpx/test_httpx.py
tests/contrib/kafka/test_kafka.py
tests/contrib/langchain/test_langchain.py
tests/contrib/redis/test_redis_asyncio.py
tests/contrib/wsgi/test_wsgi.py
tests/opentelemetry/test_context.py
tests/opentelemetry/test_span.py
tests/opentelemetry/test_trace.py
tests/telemetry/test_telemetry.py

Adds flaky decorator to failing tests in CI

ci(flaky): add flaky decorator to failing tests

---

scripts/run-test-suite

chore(ci): revert commented check

---

scripts/needs_testrun.py

Allow `itr:noskip` to be used (in commit message) to prevent skipping of tests.
In addition with `circleci:all`, it allows to run the entire test suite on a commit no matter what.

chore(ci): add itr:noskip check in needs_testrun.py

---

tests/contrib/httpx/test_httpx.py

Failure log:
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/53265/workflows/9306e4ae-0a84-4472-9026-5fafc1f0dc04/jobs/3393207
This failure started to show up after #7980 randomized test order:
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/53153/workflows/776e765c-059b-4946-b502-a36da99dbaae/jobs/3386362

ci: mark httpx flaky test

---

tests/contrib/wsgi/test_wsgi.py

This test does what #8024 intended to do, skipping the execution of a test that has problematic side effects on other tests rather than executing it with XPASS.

ci(wsgi): actually skip executing the problematic test instead of just xpassing it

---

tests/appsec/integrations/test_flask_remoteconfig.py
tests/appsec/integrations/test_flask_telemetry.py
tests/contrib/asyncio/test_tracer_safety.py
tests/contrib/django/test_django_snapshots.py
tests/contrib/flask/test_flask_snapshot.py
tests/contrib/gunicorn/test_gunicorn.py
tests/contrib/kafka/test_kafka.py
tests/contrib/pyramid/test_pyramid.py
tests/debugging/probe/test_remoteconfig.py
tests/debugging/test_debugger.py
tests/telemetry/test_writer.py
tests/tracer/runtime/test_metric_collectors.py

Delay the expiration date for flaky tests as they have not been fixed.

ci: delay expiration for flaky tests

---

.github/workflows/test_frameworks.yml

starlette framework `starlette-testsuite-0_17_1` is failing due to trio last release 0.24.0
Pin trio version to avoid errors.
(cherry picked from commit 7683e60f5b1b43f14e1c806c56af71879e81d3c4)

ci: pin trio for starlette (#8058) [backport 2.4] 

---

.github/workflows/test_frameworks.yml

starlette framework `starlette-testsuite-0_17_1` is failing due to trio last release 0.24.0
Pin trio version to avoid errors.
(cherry picked from commit 7683e60f5b1b43f14e1c806c56af71879e81d3c4)

ci: pin trio for starlette (#8058) [backport 2.3]

---

ddtrace/contrib/django/patch.py

Following https://github.com/DataDog/dd-trace-py/pull/8057 allowing less import if appsec is not loaded, wsgi_environ may not be registered. But the wrapper was making the assumption it was always registered. 
This PR fixes that.
No changelog needed as it's fixing an unreleased bug.
Note: Bug was detected on python3.12 weblog on system-tests

fix(asm): do not imply the callback is registered

---

tests/profiling/collector/test_stack.py

The gevent tests are known to throw segmentation faults on 3.12. Skipping them until we fix this.
This has been flaky for a while, so also backporting to assist the backport pipeline.

ci: skip some test_stack.py tests on 3.12

---

ddtrace/appsec/_iast/taint_sinks/ast_taint.py
releasenotes/notes/iast-fix-valueerror-on-ast-function-a06975ec55afc26b.yaml
tests/appsec/iast/taint_sinks/test_ast_taint.py

IAST: Fixes an issue where a ValueError is thrown by numpy while checking the existence of an array.
Regression test added.

fix(iast): handle value error thrown by numpy

---

ddtrace/internal/_encoding.pyx
tests/tracer/test_encoders.py

Partially Reverts: https://github.com/DataDog/dd-trace-py/pull/8054
This regression is unreleased so a release note is not required [if we can get this fix on the 2.5, 2.4, and 2.3 release lines fast enough]

fix(span_links): revert regression in v04 encoding

---

ddtrace/appsec/_iast/_ast/visitor.py
releasenotes/notes/disable-multiple-assign-02565491d5d74083.yaml
tests/appsec/iast/aspects/test_other_patching.py
tests/appsec/iast/aspects/test_str_aspect.py
tests/appsec/iast/fixtures/aspects/str_methods.py

We were doing several operations on the AST ASSIGN node that were not needed for propagation like splitting the multiple assigments and introducing temporary vars, which cause problems with introspection tools. This removes all these operations and only keep the ignore tag to left-side operands when they're a tuple or subscript.

fix: avoid changing the AST assign node since it's not needed for propagation

---

ddtrace/settings/asm.py
tests/utils.py

`override_global_config` allows tests to use different global config options.
This PR moves the list of asm global config options into asm owned config file.

chore(tests):  move asm overridable config keys for tests into asm config

---

ddtrace/appsec/_api_security/api_manager.py
ddtrace/appsec/_asm_request_context.py
ddtrace/appsec/_constants.py
ddtrace/settings/asm.py
tests/contrib/django/test_django_appsec_api_security.py
tests/contrib/fastapi/test_fastapi_appsec_api_security.py
tests/contrib/flask/test_appsec_api_security.py

Improve support of RFC "Tracer Schema Extraction Integration" last additions by adding new configuration option via env var with `DD_API_SECURITY_PARSE_RESPONSE_BODY`
Improve unit tests for Django for api security to check for that parameter. Use parametrization to improve the test reports.
This will also be tested in new system tests with https://github.com/DataDog/system-tests/pull/2023

chore(asm): add new api security env var support

---

ddtrace/tracing/_span_link.py
releasenotes/notes/otel-span-links-json-encoding-b91b3923d19e78fb.yaml
tests/tracer/test_encoders.py

Booleans in span links are currently serialized as strings with uppercase letters (ex: `True`/`False`). This format is incompatible with json's representation of strings. To address this issue we ensure booleans are converted to a lowercase string (`true`/`false`).

fix(otel): ensure booleans have json compatible representation

---

docs/configuration.rst

Per solutions request, this part of the feature is currently a bit confusing and may mislead users to some degree. Work to fix this (lazy sampling) is planned for this quarter.

docs: add caveat note for DD_TRACE_SAMPLING_RULES

---

docs/contributing.rst

Updated `contributing.rst` with small note specifying "Squash and Merge" as the merge option, not the merge queue.

docs: updated `contributing.rst` with small note about merge option

---

ddtrace/settings/config.py
releasenotes/notes/tracer-rc-unset-361dc5080cd4a112.yaml
tests/internal/test_settings.py

The remote configuration backend omits settings when they are unset. This fix ensures that if settings are not set via remote config then we unset the previously set remote configuration values.
Regression tests are added by matching the backend behaviour of not including the configuration item at all in the payload.

fix(tracing): enable settings to be unset (#8126) [backport 2.5]

---

scripts/run-test-suite
scripts/run-test-suite-hatch

This change updates the testrunner scripts used in CI to avoid skipping tests on the main branch. This was always the intent of the script, and it regressed when we changed the main branch from *.x to main.

ci: avoid skipping tests on main

---

ddtrace/contrib/botocore/patch.py
ddtrace/contrib/botocore/services/kinesis.py
ddtrace/contrib/botocore/services/sqs.py
ddtrace/contrib/botocore/utils.py
ddtrace/internal/datastreams/__init__.py
ddtrace/internal/datastreams/botocore.py
tests/contrib/botocore/test.py

Prior to this change, the datastreams logic lived side by side with the tracing logic in the botocore contrib.  After this change, this logic has been moved into the datastreams internal folder.  The change uses the core API to refactor.

chore(datastreams): botocore - dsm core API refactor

---

ddtrace/appsec/_iast/taint_sinks/ast_taint.py
releasenotes/notes/iast-fix-valueerror-on-ast-function-a06975ec55afc26b.yaml
tests/appsec/iast/taint_sinks/test_ast_taint.py

Backport b8ca6e90ef3b6a6ead3632d998261cf83458eeae from #8088 to 2.5.
IAST: Fixes an issue where a ValueError is thrown by numpy while checking the existence of an array.
Regression test added.

fix(iast): handle value error thrown by numpy [backport 2.5]

---

docs/contributing-testing.rst

This pull request documents my thinking about the intended use of the `@flaky` test decorator.

docs: document use of the flaky decorator

---

tests/appsec/appsec/test_appsec_trace_utils.py
tests/appsec/appsec/test_processor.py
tests/appsec/appsec/test_remoteconfiguration.py
tests/appsec/appsec/test_telemetry.py
tests/appsec/rules.py
tests/contrib/django/test_django_appsec.py
tests/contrib/django/test_django_appsec_snapshots.py
tests/contrib/fastapi/test_fastapi_appsec.py
tests/contrib/flask/test_appsec_flask_snapshot.py
tests/contrib/flask/test_flask_appsec.py
tests/contrib/flask/test_flask_appsec_telemetry.py

Remove many imports between different appsec tests.
Create a new file containing definitions without dependencies.
Importing between tests from different test suites can force dependencies to be installed for tests that does not require them. It can also create side effects. We want to avoid that.

chore(tests): remove dependencies between appsec tests

---

ddtrace/appsec/_handlers.py
releasenotes/notes/asm-fix-json-decode-error-none-af2c99becf9041a4.yaml
tests/contrib/flask/test_flask_appsec.py

ASM: This fix resolves an issue where we would log an exception while parsing a flask request with empty body

fix(asm): avoid logging exception on flask empty body

---

ddtrace/bootstrap/preload.py

We ensure that we can handle any profiling startup failures so that the bootstrap script can run in its entirety, instead of stopping early.

chore(profiling): handle startup errors

---

ddtrace/internal/module.py
releasenotes/notes/fix-incomplete-pkg_resources-support-58baf819ea8705ef.yaml
tests/internal/test_module.py

We fix an incomplete support for pkg_resources. This change covers for the case where pkg_resources was somehow already imported before ddtrace.
Follow-up on #8113.

fix: incomplete pkg_resources support

---

ddtrace/appsec/_utils.py
ddtrace/settings/asm.py
tests/appsec/appsec/test_remoteconfiguration.py

Following new changes in API Security RFC, api security should now be activated by default.
Also:
- update rc tests to reflect the new default values
- improve api security response handler for some fastapi old versions

chore(asm): api security activated by default

---

docs/contributing-testing.rst

This change makes one of the example riot commands in the documentation more likely to work on the first attempt. A few contributors have stubbed their toes on this command recently.

docs: remove confusing -s from example riot command

---

ddtrace/appsec/_ddwaf/__init__.py
ddtrace/appsec/_ddwaf/ddwaf_types.py
ddtrace/settings/asm.py
ddtrace/tracer.py

PR to hot fix CI on gitlab involving jobs with lambda.
- move filename of libddwaf to asm config. Check here if the file exists and disable asm and api security if it doesn't.
- add a failsafe in the tracer. Even if asm or apisec is enabled later, do not activate them if libddwaf is unavailable.

fix(tracer): do not try to load asm if libddwaf unavailable

---

tests/profiling/collector/test_task.py
tests/profiling/collector/test_threading.py

This pull request adds skips to a few tests that have been consistently failing for unknown reason on main. They should be reenabled once the root cause is determined.

ci(profiling): skip failing tests

---

.github/workflows/build_python_3.yml

Bump to the latest cibuildwheel to fix Windows builds.
See more about the issue: https://github.com/pypa/cibuildwheel/issues/1740

ci: bump cibuildwheel

---

tests/contrib/fastapi/test_fastapi.py
tests/profiling/collector/test_stack.py
tests/tracer/test_logger.py

This change xfails some tests that failed on the [most recent CI run on trunk](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/54768/workflows/7c164f0b-cb9d-4677-88e4-c2f8e8b8facf).
[Another recent failed trunk run](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/54774/workflows/9b84dda0-2b46-4a1b-ad24-24e1ab548891)

ci: mark and adjust a few unreliable tests

---

docs/advanced_usage.rst

It was brought to our attention that one of the hyperlinks in our Advanced Usage page was broken. This change should fix this.

docs: fix hyperlink typo for `advanced_usage.rst`

---

ddtrace/contrib/botocore/utils.py

Small change to only use first message's extracted context during propagation for AWS messaging services
Also fixes bug where if context is not found, the span is created with a new context. After the fix, if a context is not found, the active context is used.

fix: only use first message context for trace propagation in aws messaging

---

tests/contrib/redis/test_redis_asyncio.py
tests/contrib/redis/test_redis_cluster_asyncio.py

This pull request resolves all of the unreliable behavior I'm currently aware of in the `redis` test suite. After having done a few of these I'm starting to notice a pattern in which leaving a global object patched with the `DummyTracer` after a test can cause corrupt results in snapshot tests that run later.

ci(redis): unpatch after patching to avoid corrupting later test results

---

tests/.suitespec.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json

This change fixes a regression apparently introduced by #8288 that wasn't caught before merge because the Django suite wasn't triggered on a change to the asgi module. It regenerates snapshots to match expectations and updates the suitespec to avoid similar issues in the future.

ci(django): regenerate django appsec snapshots

---

ddtrace/contrib/botocore/services/kinesis.py
ddtrace/contrib/botocore/services/sqs.py

This is an unreleased bug. The bug prevents skipping the creation of `sqs.receiveMessage` and `kinesis.getRecords` spans when no messages/records are received specifically when `config.botocore.empty_poll_enabled=false` is set. 
fixes Botocore to use the correct config name when checking if `empty_poll_enabled` is set.

fix(botocore): bug with empty_poll_enabled config check for botocore sqs and kinesis

---

scripts/release.py

This change fixes the bug that caused releases `2.5.0` and `2.6.0` not to have release candidates pushed to PyPI.

ci(release): set tag name correctly for release candidates

---

setup.py
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json

chore(asm): update libddwaf to 1.16.0

---

ddtrace/profiling/collector/_traceback.pyx

We retrieve the variable name corresponding to the first argument only if the code object actually has any arguments. This prevents us blindly trying to retrieve the first entry of the variable name array in the hope that it is one between `self` and `cls`. The benefit of this is a less noisy debug log where all the failed attempts to resolve a local variable that might not be set already are currently logged.

refactor(profiling): variable name if arguments available

---

tests/conftest.py

This pull request puts the green checkmark on CI failures like [this one](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/55345/workflows/a896df03-2389-46a2-a23c-3b0f9803f1fd/jobs/3521852) in which the test agent mysteriously becomes unreachable. Once we have found and mitigated the root cause of this behavior, this change should be reverted.

ci: xfail instead of fail when testagent becomes unreachable

---

tests/telemetry/test_writer.py

This change builds on https://github.com/DataDog/dd-trace-py/pull/8300 by allowing the expected event to be anywhere in the payload rather than only at the end. This can probably sometimes happen due to unreliable communication with the test agent.

ci(telemetry): loosen an assertion that can sometimes fail

---

.circleci/config.templ.yml

This change removes a source of CI failures by turning off the coverage step for a few suites in which it recently failed.

ci: turn off coverage for a few suites where it recently failed

---

tests/tracer/test_logger.py

This change silences a [test failure](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/55382/workflows/ce60a7f7-f773-4599-a197-1a696a7dc0f4/jobs/3524966) that happens ephemerally on main by making the relevant assertion accept the data it actually receives during such failures.

ci(tracing): loosen an assertion that can sometimes fail

---

ddtrace/appsec/_iast/_ast/visitor.py
releasenotes/notes/do-not-patch-bytesio-b16ccc16f36e8b67.yaml

We had BytesIO as a patcheable module but it actually wasn't since we didn't have any aspects for it and could cause an exception. This comments it out in the visitor's list.

fix: dont patch BytesIO since we dont have any aspects for it

---

ddtrace/contrib/botocore/services/kinesis.py
ddtrace/contrib/botocore/services/sqs.py
releasenotes/notes/fix-botocore-bug-when-empty-poll-disabled-config-set-033d13dee074ec23.yaml
tests/contrib/botocore/test.py

fix(botocore): fix bug causing no response to be returned from SQS and Kinesis when config.botocore.empty_poll_enabled is false

---

tests/snapshots/test_sampling_with_rate_sampler_with_tiny_rate.json

Somehow we merged a snapshot test without the actual snapshot file. Perhaps the test suite spec needs to be changed? Regardless this is failing now for tests that run  `tests/integration/test_sampling.py`, because the snapshot doesn't exist. This unblocks CI.

ci: add missing sampling snapshot test

---

tests/.suitespec.json

Backport 06170cac10fa3e6a5dd3ca5aa2e08768268e196b from #8349 2.4.
This fixes the fact that some of the CI Visibility-related files were not covered by suite specs.
`git` and `ci` are being added as components because, for example, they are imported by other things:
```
ddtrace/internal/gitmetadata.py
5:from ddtrace.ext.ci import _filter_sensitive_info
6:from ddtrace.ext.git import COMMIT_SHA
7:from ddtrace.ext.git import MAIN_PACKAGE
8:from ddtrace.ext.git import REPOSITORY_URL
```
or
```
ddtrace/profiling/exporter/http.py
18:from ddtrace.ext.git import COMMIT_SHA
19:from ddtrace.ext.git import MAIN_PACKAGE
20:from ddtrace.ext.git import REPOSITORY_URL
```

ci: fix missing paths in suitespec for CI Visibility-related jobs [backport 2.4]

---

tests/.suitespec.json

Backport 06170cac10fa3e6a5dd3ca5aa2e08768268e196b from #8349 2.6.
This fixes the fact that some of the CI Visibility-related files were not covered by suite specs.
`git` and `ci` are being added as components because, for example, they are imported by other things:
```
ddtrace/internal/gitmetadata.py
5:from ddtrace.ext.ci import _filter_sensitive_info
6:from ddtrace.ext.git import COMMIT_SHA
7:from ddtrace.ext.git import MAIN_PACKAGE
8:from ddtrace.ext.git import REPOSITORY_URL
```
or
```
ddtrace/profiling/exporter/http.py
18:from ddtrace.ext.git import COMMIT_SHA
19:from ddtrace.ext.git import MAIN_PACKAGE
20:from ddtrace.ext.git import REPOSITORY_URL
```

ci: fix missing paths in suitespec for CI Visibility-related jobs [backport 2.6]

---

scripts/needs_testrun.py

CI: fix needs test run command to get latest commit message
This PR will effectively disable the "needs_testrun" mechanism if "ITR:NoSkip" is added in the commit message.
An improvement could be just disabling the "last successful run" cache just for the required test suite if "ITR:NoSkip" is found so we run only the required suites instead of all.

ci: get latest commit message to look for itr:noskip

---

tests/.suitespec.json

Backport 06170cac10fa3e6a5dd3ca5aa2e08768268e196b from #8349 2.5.
This fixes the fact that some of the CI Visibility-related files were not covered by suite specs.
`git` and `ci` are being added as components because, for example, they are imported by other things:
```
ddtrace/internal/gitmetadata.py
5:from ddtrace.ext.ci import _filter_sensitive_info
6:from ddtrace.ext.git import COMMIT_SHA
7:from ddtrace.ext.git import MAIN_PACKAGE
8:from ddtrace.ext.git import REPOSITORY_URL
```
or
```
ddtrace/profiling/exporter/http.py
18:from ddtrace.ext.git import COMMIT_SHA
19:from ddtrace.ext.git import MAIN_PACKAGE
20:from ddtrace.ext.git import REPOSITORY_URL
```

ci: fix missing paths in suitespec for CI Visibility-related jobs [backport 2.5]

---

ddtrace/appsec/processor.py
releasenotes/notes/fix_required_waf_addresses-6c51ddbcaca95129.yaml
tests/appsec/test_processor.py

Backport https://github.com/DataDog/dd-trace-py/commit/ac9bc9b94100ecc66466a10ee26eeffdf2ccbca7 from https://github.com/DataDog/dd-trace-py/pull/8420 to 1.20.
Required waf addresses were not updated in the appsec processor after a remote config rules update.
Hence, it was possible for some custom rules to be ignored.
This PR fixes this.

fix(asm): update required address when new rules are updated [backport 1.20]

---

tests/snapshots/test_sampling_with_rate_sampler_with_tiny_rate.json

Somehow we merged a snapshot test without the actual snapshot file. Perhaps the test suite spec needs to be changed? Regardless this is failing now for tests that run `tests/integration/test_sampling.py`, because the snapshot doesn't exist. This unblocks CI.

ci: add missing sampling snapshot test [backport 2.5]

---

.gitlab/benchmarks.yml

ci: fix if rule for benchmark pr comments gitlab job

---

releasenotes/notes/ci_visibility-fix-socket-timeout-exception-fabf40a398249c26.yaml

Somehow codespell must not've ran on the original pr so this is now blocking merging to main

chore: fix release note spelling

---

ddtrace/internal/ci_visibility/recorder.py
releasenotes/notes/ci_visibility-fix-socket-timeout-exception-fabf40a398249c26.yaml
tests/ci_visibility/test_ci_visibility.py

Backport a89d85e757a904590f66759084ecbbd90717fe7c from #8434 to 2.4.
This fixes an issue where older Python versions raise `socket.timeout` errors which are not equivalent to `TimeoutError`.
Eg, in python 3.9:
```
Python 3.9.16 (main, Jun 13 2023, 17:56:34)
>>> import socket
>>> isinstance(socket.timeout(), TimeoutError)
False
```
vs 3.10:
```
Python 3.10.5 (main, Jun 16 2023, 11:07:50) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
>>> import socket
>>> isinstance(socket.timeout(), TimeoutError)
True
>>>
```

fix(ci_visibility): catch socket.timeouterrors [...] generated by python<3.10 [backport 2.4]

---

ddtrace/internal/ci_visibility/recorder.py
releasenotes/notes/ci_visibility-fix-socket-timeout-exception-fabf40a398249c26.yaml
tests/ci_visibility/test_ci_visibility.py

Backport a89d85e757a904590f66759084ecbbd90717fe7c from #8434 to 2.5.
This fixes an issue where older Python versions raise `socket.timeout` errors which are not equivalent to `TimeoutError`.
Eg, in python 3.9:
```
Python 3.9.16 (main, Jun 13 2023, 17:56:34)
>>> import socket
>>> isinstance(socket.timeout(), TimeoutError)
False
```
vs 3.10:
```
Python 3.10.5 (main, Jun 16 2023, 11:07:50) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
>>> import socket
>>> isinstance(socket.timeout(), TimeoutError)
True
>>>
```

fix(ci_visibility): catch socket.timeouterrors [...] generated by python<3.10 [backport 2.5]

---

ddtrace/internal/packages.py
ddtrace/internal/remoteconfig/client.py
ddtrace/internal/remoteconfig/worker.py

We add an internal option to RC to skip the shutdown step and prevent products from being unregistered. This is a workaroud for adding support for systems such as Django Q. On platforms like Linux, these systems use multiprocessing, and the default fork start method, to spawn child processes. The main process then invokes the shutdown, potentially leaving the child processes without an RC client to listen to for new configuration payload. With the proposed changes, we prevent the RC client in the parent process to responding to the shutdown, thus keeping the RC poller worker alive. We also prevent products from being unregistered, which would also prevent configuration from being fetched for these products.
A comprehensive testing scenario would require a working Django Q instance. The …

chore(rc): add skip shutdown option

---

ddtrace/appsec/_processor.py

When `asm_request_contest` was put in place, `_set_waf_request_metrics` was added to the callbacks of the request, but the initial call was not removed. This PR fixes that.
No new tests are required, this branch pass all APPSEC_SCENARIOS tests in system tests.

fix(asm): remove unneeded call to set waf metrics

---

ddtrace/internal/module.py
releasenotes/notes/fix-ignore-non-standard-modules-318862ee5c68be0f.yaml
tests/internal/test_module.py

Backport of #7732 to 1.20
When mapping imported modules to their origin, we handle non-standard objects to ensure that we do not raise an exception if we find a module that either has no origin, or that cannot be referenced weakly. We expect these cases to be of no importance to the tracking process, as these modules are unlikely to provide useful information via the Python runtime.
Fixes #7730.

fix(internal): ignore non-standard modules [backport #7732 to 1.20]

---

.github/workflows/build_python_3.yml
.gitlab/benchmarks.yml
setup.py

- Comment-out this experimental extension to try to unblock 1.20 build.
- Bump cbuildwheel to 2.16.5 to avoid failures related to windows builds.
- Update gitlab benchmarks to use the new micro benchmarking platform

chore: fixes for 1.20 build

---

scripts/check_suitespec_coverage.py

chore: ignore embedded doc sources in suitespec check

---

ddtrace/appsec/_asm_request_context.py
ddtrace/appsec/_constants.py
ddtrace/appsec/_handlers.py
ddtrace/appsec/_iast/_overhead_control_engine.py
ddtrace/appsec/_iast/_patch.py
ddtrace/appsec/_iast/_patches/json_tainting.py
ddtrace/appsec/_iast/_taint_tracking/__init__.py
ddtrace/appsec/_iast/processor.py
ddtrace/appsec/_iast/taint_sinks/_base.py
ddtrace/appsec/_iast/taint_sinks/path_traversal.py
ddtrace/appsec/_iast/taint_sinks/ssrf.py
releasenotes/notes/iast-fix-oce-logic-4369ebeed72759fc.yaml
tests/appsec/iast/conftest.py
tests/appsec/iast/test_overhead_control_engine.py

IAST: Improve overhead control logic so the decision to analyze a request is done at span start and is saved at the span level using the core API. This should fix issues where requests were analyzed when they shouldn't be and viceversa.
(cherry picked from commit 7e8aaacab0e80466294b59d5fced7d53cb3e7eda)

fix(iast): improve overhead control logic (#8452)

---

tests/.suitespec.json

chore: remove unused test_module2

---

scripts/check_suitespec_coverage.py
tests/.suitespec.json
tests/suitespec.py

This change updates the suitespec to cover all existing filepaths. This means that there is no code file in the repo whose editing will not trigger at least one test suite in CI.

ci: update suitespec coverage

---

hatch.toml
scripts/gen_circleci_config.py

We add a check to ensure that all files are covered by the suitespec and that there are no stale patterns.

ci: add suitespec coverage check

---

ddtrace/internal/packages.py

This change fixes #8355 by changing the log level of warnings about the package-file mapping to warning from error. The error message was originally added in #3761, and as far as I can tell the guidelines about error and warning messages have changed since then. As described in the ticket, ddtrace can operate without the mapping having been built, so its failure does not need to be an error.

chore(internal): do not let package file mapping warning be an error

---

CHANGELOG.md

This change adds release notes for all currently extant x.x.0 releases, as well as some patch releases, to the single-file changelog. I did this with a lot of manual steps, but in the near future I hope to automate this process and include it in the release script.
Related to #7227

docs: update changelog with all x.x.0 releases

---

.github/workflows/pr-name.yml

commitlint 1.19.0 [was released today](https://www.npmjs.com/package/commitlint?activeTab=versions) (February 27, 2024) and is likely causing this issue: https://github.com/DataDog/dd-trace-py/actions/runs/8068170404/job/22040283374?pr=8461.

ci: pin commitlint versions to <1.19.0 to fix error

---

.github/workflows/pr-name.yml

commitlint 1.19.0 [was released
today](https://www.npmjs.com/package/commitlint?activeTab=versions) (February 27, 2024) and is likely causing this issue: https://github.com/DataDog/dd-trace-py/actions/runs/8068170404/job/22040283374?pr=8461.
(cherry picked from commit 826c602478e9a5a3bff39d40dc6236dcdfc5f849)

ci: pin commitlint versions to <1.19.0 to fix error [backport 1.20]

---

.github/workflows/pr-name.yml

commitlint 1.19.0 [was released
today](https://www.npmjs.com/package/commitlint?activeTab=versions) (February 27, 2024) and is likely causing this issue: https://github.com/DataDog/dd-trace-py/actions/runs/8068170404/job/22040283374?pr=8461.
(cherry picked from commit 826c602478e9a5a3bff39d40dc6236dcdfc5f849)

ci: pin commitlint versions to <1.19.0 to fix error [backport 2.4]

---

.github/workflows/pr-name.yml

commitlint 1.19.0 [was released
today](https://www.npmjs.com/package/commitlint?activeTab=versions) (February 27, 2024) and is likely causing this issue: https://github.com/DataDog/dd-trace-py/actions/runs/8068170404/job/22040283374?pr=8461.
(cherry picked from commit 826c602478e9a5a3bff39d40dc6236dcdfc5f849)

ci: pin commitlint versions to <1.19.0 to fix error [backport 2.6]

---

.github/workflows/pr-name.yml

commitlint 1.19.0 [was released
today](https://www.npmjs.com/package/commitlint?activeTab=versions) (February 27, 2024) and is likely causing this issue: https://github.com/DataDog/dd-trace-py/actions/runs/8068170404/job/22040283374?pr=8461.
(cherry picked from commit 826c602478e9a5a3bff39d40dc6236dcdfc5f849)

ci: pin commitlint versions to <1.19.0 to fix error [backport 2.5]

---

tests/conftest.py

This pull request resolves failures like [this one](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/56935/workflows/ae60ef0e-2215-43e7-be75-004e35ad97f8/jobs/3610594) recently observed on main by propagating xfails that happen in subprocess tests back to the main pytest session.

ci: honor xfails that happen in subprocess snapshot tests

---

conftest.py

CI: Remove unused hook that is giving problems with pytest 8.1

ci: remove ``pytest_ignore_collect`` hook

---

ddtrace/internal/atexit.py
ddtrace/internal/forksafe.py

In python 3.7 (what we support currently on main)  `hasattr(atexit, "unregister")` is always true, so we don't need to check it.  `hasattr(os, "register_at_fork")` is also ways true, so we don't need to check it.

chore(tracing): remove atexit dead code and forksafe dead code

---

.github/workflows/test_frameworks.yml

CI: pin Pytest due to deprecations in the latest release.
Addresses failures like: https://github.com/DataDog/dd-trace-py/actions/runs/8142342485/job/22251729134?pr=8565#step:8:371

ci: pin pytest

---

ddtrace/internal/forksafe.py

Windows doesn't have a fork, so we need to still check that the value is available. Changing this [here](https://github.com/DataDog/dd-trace-py/pull/8573/files) by not checking broke our windows smoke tests: Broke our smoke tests for windows
[1:21](https://dd.slack.com/archives/D04K89NC8LF/p1709576494347919)
https://github.com/DataDog/dd-trace-py/actions/runs/8144944835/job/22260155677?pr=8565#step:5:444

chore(tracing): check that register at fork is available on os

---

ddtrace/llmobs/_llmobs.py
tests/llmobs/_utils.py

This PR adds a `ddtrace.version` tag for each LLMObs span event submitted to LLMObs to track the tracer version.

feat(llmobs): add tracer version as `ddtrace.version` tag

---

ddtrace/appsec/_api_security/api_manager.py
ddtrace/appsec/_constants.py
ddtrace/settings/asm.py
tests/appsec/contrib_appsec/utils.py

This PR implements last addition to RFC "API Security Sampling Algorithm RFC", allowing sampling delay to be set by a private, non documented environment variable.

chore(asm): use sample delay env var for api sec sampling

---

tests/.suitespec.json

Backport 06170cac10fa3e6a5dd3ca5aa2e08768268e196b from #8349 1.20.
This fixes the fact that some of the CI Visibility-related files were not covered by suite specs.
`git` and `ci` are being added as components because, for example, they are imported by other things:
```
ddtrace/internal/gitmetadata.py
5:from ddtrace.ext.ci import _filter_sensitive_info
6:from ddtrace.ext.git import COMMIT_SHA
7:from ddtrace.ext.git import MAIN_PACKAGE
8:from ddtrace.ext.git import REPOSITORY_URL
```
or
```
ddtrace/profiling/exporter/http.py
18:from ddtrace.ext.git import COMMIT_SHA
19:from ddtrace.ext.git import MAIN_PACKAGE
20:from ddtrace.ext.git import REPOSITORY_URL
```

ci: fix missing paths in suitespec for CI Visibility-related jobs [backport 1.20]

---

ddtrace/profiling/exporter/pprof.pyx
releasenotes/notes/fix-profiling-stack-event-data-dc50c8e7663718cc.yaml

Backport of #8435 to 2.7
Ensure that the stack key used to group events is actually hashable.
This is an attempt to mitigate #8218, for which we don't have a reproducer. Should the issue occur again, we should be able to act on any future reports with the extra context that this proposed change provides.

fix(profiling): serialisable stack key [backport #8435 to 2.7]

---

ddtrace/profiling/exporter/pprof.pyx
releasenotes/notes/fix-profiling-stack-event-data-dc50c8e7663718cc.yaml

Backport of #8435 to 2.5
Ensure that the stack key used to group events is actually hashable.
This is an attempt to mitigate #8218, for which we don't have a reproducer. Should the issue occur again, we should be able to act on any future reports with the extra context that this proposed change provides.

fix(profiling): serialisable stack key [backport #8435 to 2.5]

---

ddtrace/appsec/_asm_request_context.py
releasenotes/notes/fix_incident_25768-043ae458e46c9620.yaml

This PR fixes a cpu leak in ASM instrumentation, that would add additional overhead to all requests if ASM, API Security and Telemetry were enabled on Flask instrumentation.
Related to incident 25768.
Add one regression unit test for all ASM supported frameworks.

fix(asm): fix cpu leak (#8629) [backport 2.5]

---

.github/workflows/lib-inject-prune.yml

These are not needed and we've accumulated over 40k images. We may or may not have broken Github's backend 😳
Job is mostly prior art from the Java team: https://github.com/DataDog/dd-trace-java/blob/e9c489fd8cac5ff142baf503eb8d38bf832d6895/.github/workflows/lib-injection-prune-registry.yaml

chore(ci): clean-up old init and test app images

---

ddtrace/_trace/context.py
tests/tracer/test_context.py
tests/tracer/test_propagation.py
tests/tracer/test_tracer.py

Currently `Context._is_remote` is set to `True` on ALL child spans. This is incorrect. 
FIX: When copying a Context object from a parent span to a child span ensure is_remote is set to `False`!
This regression was introduced in: https://github.com/DataDog/dd-trace-py/commit/90a3e3fed47763abf64cb4c04c6a32f5c64076cb. This bug is unreleased and does not require a release note.
`isRemote` is an OpenTelemetry concept and it's expected behavior is described here: https://opentelemetry.io/docs/specs/otel/trace/api/#isremote

fix(tracing): fix context cloning

---

docker/Dockerfile

We add the GDB debugger to the testrunner docker image to make it easier to debug core dumps, either locally or in CI.

chore: add gdb to testrunner image

---

ddtrace/settings/asm.py

Values provided by the user for waf timeout are in milliseconds.
- default value is 5 milliseconds defined in [`ddtrace/appsec/_constants.py` ligne 207](https://github.com/DataDog/dd-trace-py/blob/e4d3f7f687078b98f043dcd3e070dd131dd064ed/ddtrace/appsec/_constants.py#L207)
- timeout is converted to microseconds in [`ddtrace/appsec/_ddwaf/__init__.py` ligne 163](https://github.com/DataDog/dd-trace-py/blob/e4d3f7f687078b98f043dcd3e070dd131dd064ed/ddtrace/appsec/_ddwaf/__init__.py#L163)
This PR fix the faulty comment in asm settings.

fix(asm): fix comment about waf timeout in asm settings

---

docker/Dockerfile

This fixes the change from #7888 so the testrunner image is properly built for amd64.
See error:
https://github.com/DataDog/dd-trace-py/actions/runs/7264375897/job/19791778138#step:6:5816

ci: fix amd64 testrunner build

---

ddtrace/debugging/_expressions.py
tests/debugging/test_expressions.py

We implement the instanceof operator for the DI expression language to determine if a value is of a given type.

chore(di): implement instanceof operator

---

ddtrace/appsec/_api_security/api_manager.py
ddtrace/appsec/_asm_request_context.py
ddtrace/appsec/_processor.py

To prepare for more features, make the waf callback return all waf results.
(code change is still covered by threat tests)

chore(asm): return all waf results from the waf callback

---

ddtrace/appsec/_api_security/api_manager.py

We moved from a "maybe we need" to "we always need" in the api security schema computation in the api security manager, the logic should reflect that.
- ensure that we always do the computation, even if all addresses are already in the context.
(This PR does not change the default behaviour of the tracer, but, later,  if we use response body in the waf context for another feature before api security, we don't want api security to be disabled because of that).

chore(asm): improve logic of api security manager

---

.github/workflows/test_frameworks.yml

Pytest v8.1.1 updated how warnings are validated and this breaks the flask v1.1.4 test suite:
https://docs.pytest.org/en/stable/changelog.html#pytest-8-1-1-2024-03-08
This PR pins pytest to a compatible version.
TODO: Upgrade the flask version used in framework tests
---------
Co-authored-by: Christophe Papazian <114495376+christophe-papazian@users.noreply.github.com>
(cherry picked from commit 699f92678db2a7d35e6b5968ec8d106e02c4466a)

ci: resolve failing flask framework tests [backport 2.5]

---

ddtrace/internal/telemetry/writer.py
releasenotes/notes/elemetry-always-send-heartbeats-a133f02ba2f5bb6e.yaml
tests/conftest.py
tests/telemetry/test_telemetry.py
tests/telemetry/test_writer.py

The python instrumentation telemetry client only sends heartbeats events if no other telemetry events are queued. This behavior does not align with other client libraries. Heartbeat events should be sent every 60 seconds.
This keeps the service active in the Datadog UI.
---------
Co-authored-by: Federico Mon <federico.mon@datadoghq.com>
(cherry picked from commit 18a7e49dd44706dbf4f3b5d2f27194dc629755eb)

fix(telemetry): always send heartbeats [backport 2.5]

---

ddtrace/internal/telemetry/writer.py
releasenotes/notes/elemetry-always-send-heartbeats-a133f02ba2f5bb6e.yaml
tests/conftest.py
tests/telemetry/test_telemetry.py
tests/telemetry/test_writer.py

The python instrumentation telemetry client only sends heartbeats events if no other telemetry events are queued. This behavior does not align with other client libraries. Heartbeat events should be sent every 60 seconds.
This keeps the service active in the Datadog UI.
---------
Co-authored-by: Federico Mon <federico.mon@datadoghq.com>
(cherry picked from commit 18a7e49dd44706dbf4f3b5d2f27194dc629755eb)

fix(telemetry): always send heartbeats [backport 2.6]

---

ddtrace/internal/module.py
docs/spelling_wordlist.txt
releasenotes/notes/fix-chained-namespace-loader-1701e040d7b3af9b.yaml
tests/internal/test_module.py

Backport of #8603 to 2.5
We fix the implemention of the support for namespace module imports that caused issues with some standard library modules, such as `importlib`. We make sure that the internal module attribute initialisation can create the correct namespace loader, and then we make sure that we chain it with the custom loader used to trigger import hooks.
Addresses #8003

fix(internal): chained namespace loader [backport #8603 to 2.5]

---

.riot/requirements/1185813.txt
.riot/requirements/135e6d3.txt
.riot/requirements/1420734.txt
.riot/requirements/16653b8.txt
.riot/requirements/16711f6.txt
.riot/requirements/16c5a53.txt
.riot/requirements/17ed83b.txt
.riot/requirements/1b75c2c.txt
.riot/requirements/1ef0c35.txt
.riot/requirements/36231be.txt
.riot/requirements/3cdaaae.txt
.riot/requirements/60ac461.txt
.riot/requirements/7a59aa8.txt
.riot/requirements/9c022dd.txt
.riot/requirements/dc69f1e.txt

CI: Nightly job on main is failing due to missing greenlet dependency in some lockfiles:
- https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/57791/workflows/0f925a1b-c165-4275-94fd-28cf36976e7b/jobs/3660780
- https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/57791/workflows/0f925a1b-c165-4275-94fd-28cf36976e7b/jobs/3660814

ci: add greenlet dependency to riot lockfiles

---

ddtrace/appsec/_handlers.py
releasenotes/notes/fix_asgi_receive_wrapper-685522a1af75d59d.yaml

- Fix receive wrapper for asynchronous requests with more than one message received.
(cherry picked from commit 28a03cc093b3e5c4582a71fd2d0347be88ee3195)

fix(asm): fix receive wrapper for asgi [backport 2.5]

---

ddtrace/appsec/_handlers.py
releasenotes/notes/fix_asgi_receive_wrapper-685522a1af75d59d.yaml
tests/appsec/contrib_appsec/fastapi_app/app.py
tests/appsec/contrib_appsec/utils.py

- Fix receive wrapper for asynchronous requests with more than one message received.
- Add a test_streaming (only for FastAPI) to cover the fix
- Add one other possible large request body for threat blocking tests on request body
(cherry picked from commit 28a03cc093b3e5c4582a71fd2d0347be88ee3195)

fix(asm): fix receive wrapper for asgi [backport 2.6]

---

ddtrace/appsec/_trace_utils.py
releasenotes/notes/appsec-django-login-anonymous-user-fix-3c1faae6df4106e9.yaml
tests/contrib/django/test_django_appsec.py

ASM: This fix resolves an issue where a failed login attempt could be sent for a valid user if the name of the user was `AnonymousUser`.

fix(asm): improve django login events logic

---

ddtrace/contrib/langchain/patch.py
releasenotes/notes/fix-langchain-vision-apis-58e4de9b52198e43.yaml

Backports #8681 to 2.6.
Note that in 2.6 the `test_langchain_community.py` file is not present as there is no explicit support yet for langchain_community. The test added by #8681 is based in the now-not-present test file, so we've just deleted it for now but the fix still applies for regular langchain.

fix(langchain): addresses compatibility with vision API [backport #8681 to 2.6]

---

ddtrace/llmobs/_constants.py
ddtrace/llmobs/_llmobs.py
ddtrace/llmobs/_trace_processor.py
ddtrace/llmobs/decorators.py
tests/llmobs/test_llmobs_decorators.py
tests/llmobs/test_llmobs_service.py
tests/llmobs/test_llmobs_trace_processor.py

This PR follows up on #8530 by adding an ml_app override option on the LLMObs SDK span start methods if a service provides functionality for more than one ml_app as configured in `DD_LLMOBS_APP_NAME`.
Users can now add an `ml_app: str` keyword argument in the `LLMObs.{llm/agent/workflow/task/tool}` methods and `LLMObs.decorators.{llm/agent/workflow/task/tool}` decorators, which will override the tagged `ml_app` value instead of using the default `DD_LLMOBS_APP_NAME` value.
This PR also moves the `LLMObsTraceProcessor` class into its own `ddtrace/llmobs/_trace_processor.py` module.

feat(llmobs): add ML App override option to LLMObs SDK span methods

---

ddtrace/_trace/tracer.py
ddtrace/internal/debug.py
releasenotes/notes/deprecate_tracer_sampler-69c81b7ccf8fb6f9.yaml
tests/tracer/test_sampler.py

chore(tracer): make tracer.sampler private and add tracer.sample()

---

ddtrace/contrib/kafka/patch.py
releasenotes/notes/kafka-none-2-4f9e600e115eb44c.yaml

This pull request fixes
https://github.com/DataDog/dd-trace-py/issues/8602 by changing `if message` tests in the Kafka contrib to `if message is not None`. This avoids the runtime calling `__len__` on the message object, which is not guaranteed by confluent-kafka to be defined.

fix(kafka): do identity checks on kafka messages to work around… [backport 2.5]

---

.github/workflows/system-tests.yml

This pull request fixes main-branch CI failures like [this one](https://github.com/DataDog/dd-trace-py/actions/runs/8362741898/job/22894090313) that resulted from attempting to fetch all of the repo's hundreds of branches and tags during system tests. The root cause is visible [here](https://github.com/DataDog/dd-trace-py/actions/runs/8362741898/job/22894073563) in the "check if run is needed" step. The fix applied in this pull request is to only fetch the `main` branch when running on a merge or schedule, instead of fetching all branches and tags due to an empty pull request hash variable as in the previous behavior.
The whitespace changes are something I noticed while in this file and are not directly related to the bugfix.

ci: fetch main branch when not in a pull request build

---

ddtrace/llmobs/_trace_processor.py
tests/llmobs/_utils.py

This PR adds `error.type` to LLMObs spans marked with error.

feat(llmobs): add error.type to llmobs spans

---

ddtrace/_trace/context.py
tests/tracer/test_propagation.py

`Context._spans_links` should only be set on local root spans. It does not make sense to copy this value to child spans. This is not a bug fix, it just removes an unnecessary and potentially confusing operation.

chore(tracing): remove span_links from context._with_span

---

ddtrace/appsec/_trace_utils.py
releasenotes/notes/asm-fix-login-failure-events-4c79ea4b5c6f5e29.yaml
tests/contrib/django/test_django_appsec.py

ASM: This fix resolves an issue where django login failure events may send wrong information of user existence.

fix(asm): login failure events `user exists` field optional

---

ddtrace/internal/datastreams/processor.py
releasenotes/notes/dsm-error-logs-to-debug-1b3322c4a8790b72.yaml

Prior to this change DSM Processor failures to contact the agent were logged with `log.error(...)`, even though they might be retried and be successful.
After this change, those messages are now _debug level_.  To make sure the message still appears, the enclosing try/catch statement has been updated to include the stack trace in the error message.

chore(dsm): processor retries now fail as debug, unless retry limit is exceeded

---

ddtrace/contrib/kafka/patch.py
releasenotes/notes/trace-kafka-consume-10a797a1305b1cd9.yaml
tests/contrib/kafka/test_kafka.py
tests/snapshots/tests.contrib.kafka.test_kafka.test_commit_with_consume_single_message.json
tests/snapshots/tests.contrib.kafka.test_kafka.test_commit_with_consume_with_error[False].json
tests/snapshots/tests.contrib.kafka.test_kafka.test_commit_with_consume_with_multiple_messages.json

Backported because it contains a fix for #8752
Adds tracing and DSM support for
https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#confluent_kafka.Consumer.consume

feat: kafka trace consume [backport 2.7]

---

releasenotes/notes/fix-iast-patches-module-6a940829e13849ba.yaml

Fixes an issue where importing `ddtrace.internal.peer_service` would fail raising an `ImportError`

fix: add ``__init__.py`` to ``ddtrace.appsec._iast._patches`` module

---

tests/telemetry/test_telemetry.py

This change makes an unreliable test expect the results that it actually gets in CI: 
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/58336/workflows/1bed424b-752e-4748-b3ef-ce3cad32ea72/jobs/3688991

ci(telemetry): expect observed test result

---

riotfile.py

This change helps debug test timeouts like [this one](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/58336/workflows/1bed424b-752e-4748-b3ef-ce3cad32ea72/jobs/3688919) in the `profile` suite by outputting the name of each test as it starts.

ci: make pytest output verbose during profile suite

---

ddtrace/appsec/_iast/processor.py
releasenotes/notes/iast-fix-context-creation-2d0dee033723514c.yaml

IAST: Ensure context is created in the current span, as some tainting operations occur regardless of `oce.acquire_request`. 
Note: The bug was introduce in this PR: https://github.com/DataDog/dd-trace-py/pull/8452

fix(iast): ensure context is created for current span

---

pyproject.toml

chore(setuptools_scm): add comment explaining version scheme

---

pyproject.toml
releasenotes/notes/setuptools_scm-use-guess-next-dev-1e7754df76c78e94.yaml

Prior to this change, setuptools_scm reported the version for patch releases as the next minor release. Afterwards, versions are patch releases (as expected).

fix(setuptools_scm): backport setuptools_scm version scheme to guess-next-dev

---

ddtrace/contrib/botocore/services/bedrock.py
ddtrace/llmobs/_integrations/bedrock.py
releasenotes/notes/feat-bedrock-message-api-673e527cb1b0befd.yaml
tests/contrib/botocore/bedrock_cassettes/anthropic_message_invoke.yaml
tests/contrib/botocore/bedrock_cassettes/anthropic_message_invoke_stream.yaml
tests/contrib/botocore/test_bedrock.py
tests/snapshots/tests.contrib.botocore.test_bedrock.test_anthropic_message_invoke.json
tests/snapshots/tests.contrib.botocore.test_bedrock.test_anthropic_message_invoke_stream.json

This PR adds support to the botocore integration's bedrock service to correctly tag input/output messages from Anthropic calls.
Previously bedrock's models only supported raw text prompts and returned text outputs. However, Anthropic's newest claude 3 supports a chat message API, which means we need to support that as well.
This change also switches to using `tracer.trace()` instead of `tracer.start_span(..., activate=False)` for bedrock spans, because the latter meant that bedrock spans would always be root spans (messing up parenting for traces containing non-root bedrock spans). 
Additionally by getting rid of the `activate=False` argument, this means that bedrock spans will now continue to be the active span until the stream/body is completely consumed. Previously we allowed bedrock …

feat(botocore): add support for tagging bedrock message input/outputs

---

tests/profiling/test_main.py

This change fixes CI failures like [this one](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/58472/workflows/ecbc60dd-6972-4246-ad54-fee72c9adef8/jobs/3695968) by skipping the test.

ci: skip forkserver multiprocessing profiling test because it is unreliable

---

CHANGELOG.md

chore: update changelog for version 2.7.5

---

ddtrace/contrib/starlette/patch.py
releasenotes/notes/fix-starlette-background-67d4822042028d6b.yaml
tests/contrib/starlette/app.py
tests/snapshots/tests.contrib.starlette.test_starlette.test_background_task.json

Don't crash when encountering functions without `__name__` or `__module__` attributes.
Starlette background tasks can be started with any `callable`, and not all `callable`s (annoyingly) are guaranteed to have `__name__` attributes. Specifically, `functools.partial` generates a function without a `__name__`. There is some debate (see https://github.com/python/cpython/issues/91002) about whether this is the right behavior (it's clearly confusing, since it caused a bug here!) but right now, this makes the whole background task crash due to an attribute error.
This PR just tries to get the name/module, and if not available, replaces them with the string `<unknown>` rather than crashing the whole task. (Happy to switch to a different string here, `<unknown>` is just a placeholder that kind of …

fix(starlette): don't crash on functions without `__name__`

---

.github/workflows/system-tests.yml

CI: Introduces concurrency to System Tests execution in order to decrease wall time.
Decreases wall time for system tests from ~37 min to ~23 min.
---------
Co-authored-by: Emmett Butler <723615+emmettbutler@users.noreply.github.com>
(cherry picked from commit ad2fe2554a53d6bbee12a0f5a97f44c54f27b508)

ci: parallel system tests [backport 2.7]

---

.github/workflows/system-tests.yml

CI: Introduces concurrency to System Tests execution in order to decrease wall time.
Decreases wall time for system tests from ~37 min to ~23 min.
---------
Co-authored-by: Emmett Butler <723615+emmettbutler@users.noreply.github.com>
(cherry picked from commit ad2fe2554a53d6bbee12a0f5a97f44c54f27b508)

ci: parallel system tests [backport 2.5]

---

tests/tracer/runtime/test_metric_collectors.py

Marks a test that has failed occasionally recently ([example](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/58597/workflows/b57ad60b-d526-46d5-a383-7ed9c4dfe46b/jobs/3701995))

ci(tracer): mark unreliable test as flaky

---

ddtrace/contrib/langchain/patch.py
releasenotes/notes/fix-langchain-chain-invoke-792219fb95ac1889.yaml
tests/contrib/langchain/test_langchain_community.py
tests/snapshots/tests.contrib.langchain.test_langchain_community.test_chain_invoke.json

This PR fixes the langchain integration's patched chain method to check for the correct input argument name.
In `LangChain<0.1`, we patch `langchain.Chain.__call__()`, which uses `inputs: Union[Dict[str, Any], str]` as the argument to the chain invocation. However in `LangChain>=0.1`, we patch `langchain.Chain.invoke()`, which uses `input: Dict[str, Any]` as the argument to the chain invocation. We use the same traced function to patch both methods, but this subtle change broke our argument parsing, which expected the name `inputs` instead of `input`.

fix(langchain): type check chain.invoke() input argument name

---

ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
releasenotes/notes/iast-fix-native-exceptions-e6299dc2b9ad54d3.yaml
tests/appsec/iast/aspects/test_add_aspect.py

Some native exceptions were not being caught correctly by the python tracer. This fix remove those exceptions to avoid fatal error executions like:
```
File "/usr/local/lib/python3.10/dist-packages/ddtrace/appsec/_iast/_taint_tracking/__init__.py", line 106 in taint_pyobject
Current thread 0x0000ffff83fbc420
Fatal Python error: g_initialstub: greenlet: Unhandled C++ exception: Tainted Map isn't initialized. Call create_context() first
```
```python
destroy_context()
try:
result = taint_pyobject(
pyobject=string_to_taint,
source_name="test_add_aspect_tainting_left_hand",
source_value=string_to_taint,
source_origin=OriginType.PARAMETER,
)
except Exception:
pass
```
```
Fatal Python error: Aborted
Thread 0x000078a301cc9700 (most recent call first):
File …
```

fix(iast): remove native exceptions

---

ddtrace/appsec/_processor.py
tests/appsec/appsec/test_telemetry.py

WAF timeouts create redundant and excessive noise.
Additionally, this log is redundant since that information is included within the span as `_dd.appsec.event_rules.errors` and as a tag within the `dd.instrumentation_telemetry_data.appsec.waf.requests` metric, under the tag `waf_timeout `.

chore(asm): remove WAF timeout & WAF error log metric

---

ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
releasenotes/notes/iast-fix-native-exceptions-e6299dc2b9ad54d3.yaml
tests/appsec/iast/aspects/test_add_aspect.py

Backport 79f99eff41dbc825c23e934152f9dd7ffc835972 from #8841 to 2.5.
Some native exceptions were not being caught correctly by the python tracer. This fix remove those exceptions to avoid fatal error executions like:
```
File "/usr/local/lib/python3.10/dist-packages/ddtrace/appsec/_iast/_taint_tracking/__init__.py", line 106 in taint_pyobject
Current thread 0x0000ffff83fbc420
Fatal Python error: g_initialstub: greenlet: Unhandled C++ exception: Tainted Map isn't initialized. Call create_context() first
```
```python
destroy_context()
try:
result = taint_pyobject(
pyobject=string_to_taint,
source_name="test_add_aspect_tainting_left_hand",
source_value=string_to_taint,
source_origin=OriginType.PARAMETER,
)
except Exception:
pass
```
```
Fatal Python error: Aborted
Thread 0x000078a301cc9700 …
```

fix(iast): remove native exceptions [backport 2.5]

---

tests/.suitespec.json

ci: trigger telemetry tests on settings changes

---

ddtrace/contrib/langchain/patch.py
releasenotes/notes/fix-langchain-avoid-patching-partners-4c5fb04db6d083b0.yaml
tests/contrib/langchain/test_langchain_community.py

This PR changes the langchain integration such that it will check for partner libraries before attempting to patch them.
The langchain integration patches `langchain_openai.OpenAIEmbeddings.*` and `langchain_pinecone.PineconeVectorStore.*`, which are partner libraries that are not required to be installed. Currently if they are not available, we raise `ModuleNotFoundError`. This PR fixes this so that we'll skip patching those methods if the corresponding partner library is not available.
Additionally, this PR also adds importing `langchain_community.llm/chat_models` as those are not automatically imported by importing `langchain_community`. This is important as we reference those submodules in our patch code later on.

fix(langchain): avoid patching partner libraries if not available

---

.github/PULL_REQUEST_TEMPLATE.md

Removing reference of Security Design and Guidance team in PR review template as the team no longer exists. We will work with the trace team to understand the requirements of review.

chore(dev): remove reference to SDG from PR template

---

tests/contrib/kafka/test_kafka.py
tests/opentelemetry/test_trace.py

https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/58731/workflows/afca0788-9a59-4cab-ad3a-6c0b5fd855a1/jobs/3708237
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/58689/workflows/0ff13615-4ff3-4383-8738-323fad95670a/jobs/3705777

ci: mark unreliable tests as flaky

---

ddtrace/profiling/_threading.pyx

We limit the wrapping of the tread bootstrapping logic to capture the native ID only on CPython 3.7, which is the only version of CPython that we support that has no thread native ID support.

refactor(profiling): patch for native ID if necessary

---

ddtrace/contrib/aioredis/patch.py
ddtrace/contrib/algoliasearch/patch.py
ddtrace/contrib/django/patch.py
ddtrace/contrib/starlette/patch.py
releasenotes/notes/versions-arent-just-ints-909349433f58b79b.yaml
tests/contrib/algoliasearch/test.py

This pull request fixes https://github.com/DataDog/dd-trace-py/issues/8823 by updating package version checks that used `int()` and `split('.')` to use the spec-compliant version specifier parsing implementation from `vendor.packaging`.

fix: support all valid package version specifiers in version checks

---

ddtrace/contrib/kafka/patch.py
releasenotes/notes/kafka-empty-message-list-d4358af8f4b72567.yaml
tests/contrib/kafka/test_kafka.py

This pull request fixes https://github.com/DataDog/dd-trace-py/issues/8846 by handling the case where the list of messages is empty, which can happen when `consume` calls time out.

fix(kafka): handle empty message lists

---

.github/workflows/system-tests.yml

This pull request attempts to fix #8801 by setting the git ref used during system-tests' library checkout to one that corresponds to a real commit in the history. The [theory](https://github.com/DataDog/dd-trace-py/issues/8801#issuecomment-2038091563) is that this allows the version specifier to be guessed accurately by setuptools_scm.
This approach has been tested on a pull request #8879 with 2.7 as a base. In that test, the [observed version string](https://github.com/DataDog/dd-trace-py/actions/runs/8560819851/job/23460660021?pr=8879#step:3:36) was `2.7.7.dev13+<hash>`, as opposed to the string observed in #8801 `2.8.0.dev0`.

ci: checkout PR head instead of merge branch when running system tests

---

tests/.suitespec.json

CI: Disables IAST TDD Propagation suite while the fix to the proper issue is done

ci: disable appsec_iast_tdd_propagation suite temporarily

---

ddtrace/contrib/kafka/patch.py
releasenotes/notes/kafka-empty-message-list-d4358af8f4b72567.yaml
tests/contrib/kafka/test_kafka.py

This pull request fixes
https://github.com/DataDog/dd-trace-py/issues/8846 by handling the case where the list of messages is empty, which can happen when `consume` calls time out.

fix(kafka): handle empty message lists [backport 2.7]

---

ddtrace/appsec/_api_security/api_manager.py
releasenotes/notes/removing_api_security_metrics-4b6a6ba8643b5ab3.yaml

Metrics were added during R&D phase on API Security. This PR removes them.
It prevents to send unneeded data to DD backend.
APPSEC-52415
https://github.com/DataDog/dd-analytics/pull/30330 is also put in place to ensure no additional charges for customers using non updated tracers.
This PR is backported to all versions containing api security.

fix(asm): remove datadog.api_security metrics

---

ddtrace/appsec/_api_security/api_manager.py
releasenotes/notes/removing_api_security_metrics-4b6a6ba8643b5ab3.yaml

https://github.com/DataDog/dd-trace-py/pull/8906
Backport https://github.com/DataDog/dd-trace-py/commit/616c5a93ad26647a6b9cb98f45e9bc4a35687d83 from https://github.com/DataDog/dd-trace-py/pull/8906 to 2.7.
Metrics were added during R&D phase on API Security. This PR removes them.
It prevents to send unneeded data to DD backend.
APPSEC-52415
https://github.com/DataDog/dd-analytics/pull/30330 is also put in place to ensure no additional charges for customers using non updated tracers.
This PR is backported to all versions containing api security.

fix(asm): remove datadog.api_security metrics [backport 2.7]

---

ddtrace/appsec/_processor.py
tests/appsec/contrib_appsec/utils.py
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json

Makes 3 request headers always to be sent if ASM is enabled:
- accept
- content-type
- user-agent
APPSEC-52404

chore(asm): add support for headers always sent when ASM enabled

---

ddtrace/appsec/_iast/_ast/ast_patching.py
ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSlice.cpp
ddtrace/appsec/_iast/_taint_tracking/aspects.py
releasenotes/notes/iast-fix-cipher-error-48882bb289eb4353.yaml
tests/appsec/iast/aspects/test_slice_aspect_fixtures.py
tests/appsec/iast/fixtures/aspects/str_methods.py
tests/appsec/iast/fixtures/propagation_path.py
tests/appsec/iast/fixtures/taint_sinks/weak_algorithms.py
tests/appsec/iast/taint_sinks/test_weak_cipher.py
tests/appsec/iast/test_iast_propagation_path.py
tests/appsec/iast_tdd_propagation/flask_orm_app.py
tests/appsec/iast_tdd_propagation/flask_taint_sinks_app.py
tests/appsec/iast_tdd_propagation/flask_taint_sinks_views.py
tests/appsec/iast_tdd_propagation/test_flask.py

This PR fix an issue with AES functions from the pycryptodome package that caused the application to crash and stop.
The problem was a negative start variable of a slice operation in the `pycryptodome` package.
```python
def update(self, msg):
"""Authenticate the next chunk of message.
Args:
data (byte string/byte array/memoryview): The next chunk of data
"""
```
C++ slice aspect function was fixed an Crypto package skipped from AST patching

fix(iast): aes cipher functions break applications if iast is enabled

---

ddtrace/appsec/_asm_request_context.py
releasenotes/notes/fix_incident_25768-043ae458e46c9620.yaml

This PR fixes a cpu leak in ASM instrumentation, that would add additional overhead to all requests if ASM, API Security and Telemetry were enabled on Flask instrumentation.
Related to incident 25768.

fix(asm): fix cpu leak (#8629) [APMS-11823] [backport 1.20]

---

tests/contrib/langchain/test_langchain_community.py

The `test_lcel_chain_batch_311` test is flaky and is blocking CI. Marking this as flaky to xpass while we investigate the issue.

chore(langchain): mark flaky chain test

---

ddtrace/appsec/_processor.py
tests/appsec/contrib_appsec/utils.py

Implementation of [RFC] WAF Integration : Identify Requests for the python tracer.
APPSEC-52393
(no system tests yet)

chore(asm): add waf integration headers to be reported always with asm

---

tests/contrib/langchain/test_langchain_community.py

The following tests have been flagged as flaky in the nightly runs in CircleCI:
- `test_global_tags`
- `test_openai_llm_sync_with_multiple_prompts`
- `test_openai_chat_model_sync_call_langchain_openai`
- `test_openai_chat_model_sync_generate`
- `test_chat_model_metrics`
- `test_openai_math_chain_sync`
- `test_chain_invoke_dict_input`
- `test_chain_invoke_str_input`
- `test_openai_sequential_chain_with_multiple_llm_sync`
- `test_chain_logs`
- `test_llm_logs_when_response_not_completed`
- `test_lcel_chain_simple`
- `test_lcel_chain_batch_311`
- `test_lcel_chain_nested`
- `test_llmobs_openai_llm`
- `test_llmobs_openai_chat_model`
- `test_llmobs_openai_chat_model_custom_role`
Marking these as flaky as well until we can narrow down exactly why these are flaky (it seems on Python 3.11 …

chore(langchain): mark additional tests as flaky

---

pyproject.toml
releasenotes/notes/setuptools_scm-use-guess-next-dev-1e7754df76c78e94.yaml

Prior to this change, setuptools_scm reported the version for patch releases as the next minor release. Afterwards, versions are patch releases (as expected).
(cherry picked from commit 1ffb660728e5b338c2381db9764d46fa5d12e62b)

fix(setuptools_scm): backport setuptools_scm version scheme to guess-next-dev [backport 2.8]

---

ddtrace/appsec/_iast/taint_sinks/command_injection.py

chore(iast): metrics order

---

ddtrace/appsec/_iast/_taint_tracking/__init__.py

chore(iast): update type checking

---

ddtrace/llmobs/_trace_processor.py
ddtrace/llmobs/_writer.py
tests/llmobs/_utils.py
tests/llmobs/test_llmobs_trace_processor.py

This PR changes the `span.error` field to `span.status`, with the possible values being `'ok', 'error'` replacing `0, 1` respectively.

feat(llmobs): change error field to status

---

.github/CODEOWNERS

chore: fix grpc contrib codeowners

---

ddtrace/appsec/_iast/_taint_tracking/__init__.py

Fix IAST metrics log error format:
Before:
After:

chore(iast): fix metrics log error format

---

ddtrace/contrib/langchain/patch.py
releasenotes/notes/fix-langchain-openai-submodule-check-ea81685e31cb9720.yaml

Backport of #8896 to 2.8.
Fixes #8889.
This PR adds a safe check for if a traced LLM/Chat model instance is an OpenAI instance by adding try/catch and reversing the order of the type checks. Previously we were checking directly against the installed langchain package, i.e.
```python
if isinstance(instance, BASE_LANGCHAIN_MODULE.chat_models.ChatOpenAI) or (
langchain_openai and isinstance(instance, langchain_openai.ChatOpenAI)
):
```
But `langchain_community` does not allow automatically accessing its submodules, i.e. `langchain_community.chat_models.ChatOpenAI` will result in an error unless `from langchain_community import chat_models` is performed already.
With this fix, there are three scenarios for
`langchain_community/langchain_openai` users:
1. They use `langchain_openai` --> we …

fix(langchain): safely check if instance is openai llm/chat [backport #8896 to 2.8]

---

ddtrace/contrib/langchain/patch.py
releasenotes/notes/fix-langchain-chain-invoke-792219fb95ac1889.yaml
tests/contrib/langchain/test_langchain_community.py
tests/snapshots/tests.contrib.langchain.test_langchain_community.test_chain_invoke.json

Backport #8835 to 2.8.
This PR fixes the langchain integration's patched chain method to check for the correct input argument name.
In `LangChain<0.1`, we patch `langchain.Chain.__call__()`, which uses `inputs: Union[Dict[str, Any], str]` as the argument to the chain invocation. However in `LangChain>=0.1`, we patch
`langchain.Chain.invoke()`, which uses `input: Dict[str, Any]` as the argument to the chain invocation. We use the same traced function to patch both methods, but this subtle change broke our argument parsing, which expected the name `inputs` instead of `input`.

fix(langchain): check chain.invoke() argument name [backport #8835 to 2.8]

---

ddtrace/contrib/langchain/patch.py
releasenotes/notes/fix-langchain-avoid-patching-partners-4c5fb04db6d083b0.yaml
tests/contrib/langchain/test_langchain_community.py

Backport #8339 to 2.8.
This PR changes the langchain integration such that it will check for partner libraries before attempting to patch them.
The langchain integration patches `langchain_openai.OpenAIEmbeddings.*` and `langchain_pinecone.PineconeVectorStore.*`, which are partner libraries that are not required to be installed. Currently if they are not available, we raise `ModuleNotFoundError`. This PR fixes this so that we'll skip patching those methods if the corresponding partner library is not available.
Additionally, this PR also adds importing
`langchain_community.llm/chat_models` as those are not automatically imported by importing `langchain_community`. This is important as we reference those submodules in our patch code later on. …

fix(langchain): avoid patching libraries if not available [backport #8339 to 2.8]

---

ddtrace/appsec/_iast/_taint_tracking/Constants.h
ddtrace/appsec/_iast/_taint_tracking/__init__.py

Fix IAST metrics log error typo

chore(iast): fix metrics log error typo

---

ddtrace/appsec/_iast/_taint_tracking/__init__.py
tests/appsec/iast/aspects/test_add_aspect.py

Validate `_DD_IAST_DEBUG` as bool introduced in #8954

chore(iast): validate iast_debug env var as bool

---

tests/appsec/contrib_appsec/test_fastapi.py

Improve support and remove deprecation warnings for fastapi threat tests.

chore(asm): add better support for recent versions of fastapi starlette httpx in unit tests

---

ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
tests/appsec/iast/taint_tracking/test_taint_tracking.py

`api_set_ranges` threw  an unexpected error if we're out of context

fix(iast): fix `api_set_ranges` return type

---

ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectExtend.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectFormat.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSlice.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.cpp
ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.h
ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintedObject.cpp
ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.cpp
ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.h
ddtrace/appsec/_iast/_taint_tracking/_native.cpp
ddtrace/appsec/_iast/_taint_tracking/aspects.py
tests/appsec/iast/aspects/test_join_aspect_fixtures.py

Boy scout rule: "Always leave your code cleaner than you found it.":
- Remove narrowing conversion from unsigned long to int and cast manually
- Remove TODOs (and add test to verify the TODO was resolved)
- Add doc strings
- Remove unused functions (`context_id` and `allocate_tainted_object`)
- Update type hinting on Python aspect file

chore(iast): clean native code

---

ddtrace/appsec/_iast/_taint_tracking/_vendor/pybind11/tools/pybind11Common.cmake

IAST: FLTO compiler option is not set properly in upstream pybind11.
See:https://github.com/pybind/pybind11/issues/5098

fix(iast): pybind11 flto option

---

.circleci/config.templ.yml

CI: coverage upload job is failing when there is nothing to upload. This PR should fix the issue
[Sample failure](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/60069/workflows/225951f3-212d-4877-9186-64214d02c2b5/jobs/3777882)

ci: ensure coverage cli doesn't exit with code 1

---

ddtrace/appsec/_constants.py
ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
ddtrace/appsec/_iast/_taint_tracking/__init__.py
tests/appsec/iast/taint_tracking/test_taint_tracking.py

Backport f9fbc36f6d193d1d7a5b09c45101efb55daa23a7 from #9067 to 2.8.
`api_set_ranges` threw  an unexpected error if we're out of context

fix(iast): fix `api_set_ranges` return type [backport 2.8]

---

ddtrace/profiling/_threading.pyx

When run in aws lambda, this import takes ~6ms.
Moving this import sadly does not actually remove it from being imported entirely. It is also being imported from ddtrace.contrib.aws_lambda. There are plans to lazy load it there as well.
https://datadoghq.atlassian.net/browse/SVLS-4701

chore(serverless): lazy load slow package ddtrace.internal.wrapping

---

ddtrace/_logger.py
ddtrace/internal/compat.py
ddtrace/internal/utils/http.py
tests/internal/test_serverless.py

Lazy loads
+ `logging.handlers`
+ `multiprocessing`
+ `email.mime.application`
+ `email.mime.multipart`
All of which are slow to import and not needed when run in aws lambda. This improves cold start time.
Also, updates tests to ensure the code is not accidentally updated in the future to import these packages.

chore(serverless): lazy load slow package imports

---

.github/workflows/test_frameworks.yml

CI: Add a timeout to Django framework tests so it doesn't hang.
When these tests pass (not often), it takes almost 10 minutes, so a 15 minute timeout should be good enough. When it hangs it can take hours.
It's safe to timeout as it is not a "required for merge" job.
Hang example:
https://github.com/DataDog/dd-trace-py/actions/runs/8813403580/job/24191102553
Proper run example:
https://github.com/DataDog/dd-trace-py/actions/runs/8813298346/job/24190769113
(cherry picked from commit 7c6be310b5f129af0fa6b5b9c2f43d0507c08871)

ci: add timeout to django framework tests [backport 2.6]

---

ddtrace/internal/telemetry/writer.py
tests/telemetry/test_telemetry_metrics.py

Telemetry: Wrong payload format is being sent to Telemetry logs.
See System Test: https://github.com/DataDog/system-tests/pull/2392

fix(telemetry): logs payload format

---

.github/workflows/test_frameworks.yml

CI: Add a timeout to Django framework tests so it doesn't hang.
When these tests pass (not often), it takes almost 10 minutes, so a 15 minute timeout should be good enough. When it hangs it can take hours.
It's safe to timeout as it is not a "required for merge" job.
Hang example:
https://github.com/DataDog/dd-trace-py/actions/runs/8813403580/job/24191102553
Proper run example:
https://github.com/DataDog/dd-trace-py/actions/runs/8813298346/job/24190769113
(cherry picked from commit 7c6be310b5f129af0fa6b5b9c2f43d0507c08871)

ci: add timeout to django framework tests [backport 2.8]

---

.github/workflows/build_python_3.yml

CI: Use native arm64 github runners to build arm64 wheels
The usual nice things are not ready yet in arm64 runners, things like pip or docker have to be installed separately, so the `acl` trick is intented to use docker in the same session where it's installed.

ci: native arm64 build

---

ddtrace/appsec/_iast/_taint_tracking/aspects.py
releasenotes/notes/fix-fstring-zeropadding-e8e463a4d8623040.yaml
tests/appsec/iast/aspects/test_str_py3.py
tests/appsec/iast/fixtures/aspects/str_methods_py3.py

IAST: This fixes an issue where f-strings receiving int parameters were not properly formatted.

fix(iast): fstring int formatting

---

ddtrace/appsec/_iast/_taint_tracking/aspects.py
releasenotes/notes/fix-fstring-zeropadding-e8e463a4d8623040.yaml
tests/appsec/iast/aspects/test_str_py3.py
tests/appsec/iast/fixtures/aspects/str_methods_py3.py

IAST: This fixes an issue where f-strings receiving int parameters were not properly formatted.
(cherry picked from commit 5e6184cc9782eb40a4eee307abc144653e5ff7d7)

fix(iast): fstring int formatting [backport 2.6]

---

ddtrace/appsec/_iast/_taint_tracking/aspects.py
releasenotes/notes/fix-fstring-zeropadding-e8e463a4d8623040.yaml
tests/appsec/iast/aspects/test_str_py3.py
tests/appsec/iast/fixtures/aspects/str_methods_py3.py

IAST: This fixes an issue where f-strings receiving int parameters were not properly formatted.
(cherry picked from commit 5e6184cc9782eb40a4eee307abc144653e5ff7d7)

fix(iast): fstring int formatting [backport 2.7]

---

ddtrace/appsec/_iast/_taint_tracking/aspects.py
releasenotes/notes/fix-fstring-zeropadding-e8e463a4d8623040.yaml
tests/appsec/iast/aspects/test_str_py3.py
tests/appsec/iast/fixtures/aspects/str_methods_py3.py

IAST: This fixes an issue where f-strings receiving int parameters were not properly formatted.
(cherry picked from commit 5e6184cc9782eb40a4eee307abc144653e5ff7d7)

fix(iast): fstring int formatting [backport 2.8]

---

.github/workflows/build_python_3.yml

CI: Use native arm64 github runners to build arm64 wheels
The usual nice things are not ready yet in arm64 runners, things like pip or docker have to be installed separately, so the `acl` trick is intented to use docker in the same session where it's installed.
(cherry picked from commit 7c65a286ed500e9da03ce0be60d4f4423f6df102)

ci: native arm64 build [backport 2.6]

---

ddtrace/internal/packages.py
tests/internal/test_packages.py

Backport of #9047 to 2.8
We refactor the implementation of the mapping that allows us to convert a file path to the corresponding distribution. Instead of mapping each individual file path to the containing distribution, we extract the root modules and map those to the distribution instead. This leads to a significant compression of the in-memory mapping. Part of the saved memory can thus be used to cache the result of the conversions to avoid repeating unnecessary mapping work.
The following is an example for the mapping built for a sample Django application
<details><summary>Previous mapping</summary>
<pre>
{'.../sample-django/.venv310/bin/__pycache__/django-admin.cpython-310.pyc': Distribution(name='Django', version='3.1.13', path=None), …

refactor: compress the packages index [backport #9047 to 2.8]

---

.circleci/config.templ.yml
docker-compose.yml
tests/contrib/config.py

This pull request disables the reliably-failing `vertica` test suite to unblock CI while we figure out how to resolve the failure.
[This](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/60382/workflows/959242f7-9615-4cb8-a324-3a1e829071ef/jobs/3792168) is the failure currently happening on main. My attempts to use the [official image](https://hub.docker.com/r/vertica/vertica-ce) have failed so far.

ci: temporarily disable vertica test suite

---

.circleci/config.templ.yml
docker-compose.yml

This pull request disables the reliably-failing `vertica` test suite to unblock CI while we figure out how to resolve the failure.
[This](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/60382/workflows/959242f7-9615-4cb8-a324-3a1e829071ef/jobs/3792168) is the failure currently happening on main. My attempts to use the [official image](https://hub.docker.com/r/vertica/vertica-ce) have failed so far.

ci: temporarily disable vertica test suite [backport 1.20]

---

.circleci/config.templ.yml
docker-compose.yml

This pull request disables the reliably-failing `vertica` test suite to unblock CI while we figure out how to resolve the failure.
[This](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/60382/workflows/959242f7-9615-4cb8-a324-3a1e829071ef/jobs/3792168) is the failure currently happening on main. My attempts to use the [official image](https://hub.docker.com/r/vertica/vertica-ce) have failed so far.
---------
(cherry picked from commit f682b230039d15deef5a187405b0c87793a86801)

ci: temporarily disable vertica test suite [backport 2.7]

---

tests/integration/test_integration_civisibility.py

This change broadens an assertion to expect the result sometimes observed in main-branch CI failures https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/60433/workflows/bc3f1e10-28ef-4fb5-91c0-300b90a4a021/jobs/3795336

ci(ci-visibility): expect observed test result

---

.gitlab/benchmarks.yml
.gitlab/benchmarks/bp-runner.yml

Example of running dd-agent in parallel with microbenchmarks via bp-runner

---

.github/workflows/build_deploy.yml

Since #9084 has been merged our build times are much faster (~20 minutes). This makes it worth running the build job as a validation for every PR to catch any changes which may break package building before they are merged.

chore(ci): enable testing package building on every PR

---

ddtrace/contrib/trace_utils_redis.py
tests/.suitespec.json

Adds back and deprecates old `tracer_utils_redis` module with public method and variables.

fix(redis): added back tracer_utils_redis with deprecation warn

---

riotfile.py
tests/contrib/celery/test_integration.py
tests/internal/test_tracer_flare.py

This change marks these two ephemeral CI failures as flaky:
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/60664/workflows/e6f953d9-721e-4a27-8064-5209f7ac3a15/jobs/3805647 last touched by @zarirhamza 
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/60685/workflows/c25bae04-8827-4893-ac67-f239b2226774/jobs/3806940 last touched by @erikayasuda 
It also adds verbose output to the `appsec_iast` test suite to aid in figuring out which test or tests generates this ephemeral segfault: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/60686/workflows/21d8cecd-9345-4e16-9157-71425bd65ccb/jobs/3807035

ci: mark some flaky tests

---

ddtrace/internal/telemetry/writer.py
tests/telemetry/test_writer.py

When enabling library injection remotely through the UI, we'd like to show which
services have been instrumented as a result. To do this we are proposing
to submit the remote configuration ID that was used to instrument the service.
[](https://datadoghq.atlassian.net/browse/APMON-887)

chore(telemetry): add item for instrumentation config id

---

ddtrace/appsec/_handlers.py
ddtrace/contrib/grpc/client_interceptor.py
ddtrace/internal/core/event_hub.py

The usage of the core API was not correct in the gRPC integration. It was working on accident based on how the listener was written.
Since the listener mutates the underlying response class and not the response instance, there is nothing that needs to be returned, so we can change the `dispatch_with_results` to `dispatch`.
As well, the previous usage of the `dispatch_with_results` API was not correct, the response was always replaced with the result from the ASM listener even when the response was `None`.
No changelog entry is added since this is a fix for an unreleased change so it is not yet a "bug".

fix(grpc): resolve issue with incorrect gRPC response being returned

---

ddtrace/appsec/_handlers.py
ddtrace/contrib/grpc/client_interceptor.py
ddtrace/internal/core/event_hub.py

…(#9157)
The usage of the core API was not correct in the gRPC integration. It was working on accident based on how the listener was written.
Since the listener mutates the underlying response class and not the response instance, there is nothing that needs to be returned, so we can change the `dispatch_with_results` to `dispatch`.
As well, the previous usage of the `dispatch_with_results` API was not correct, the response was always replaced with the result from the ASM listener even when the response was `None`.
No changelog entry is added since this is a fix for an unreleased change so it is not yet a "bug".
(cherry picked from commit 1ca90d51c8a840f8c5cf0332a844ded3d990f053)

fix(grpc): resolve issue with incorrect gRPC response being returned [backport 2.9]

---

tests/profiling/collector/test_memalloc.py
tests/profiling/collector/test_threading.py
tests/profiling/test_uwsgi.py

This change temporarily skips unreliable tests in the `profile` suite. Recent failures of these tests on the main branch:
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/60782/workflows/078778dd-deb8-4c4d-bb3c-1325370eba89/jobs/3812548
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/60798/workflows/7a11bd02-5a05-412e-9e07-c98dd0dd85ea/jobs/3813849
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/60814/workflows/80c5392d-0991-401f-8119-c290a15141b9/jobs/3814905

ci: mark flaky tests in the profile suite

---

ddtrace/appsec/_iast/taint_sinks/_base.py

If the vulnerability is outside client code, skip the vulnerability

fix(iast): false positives outside client code

---

.gitlab/benchmarks.yml
.gitlab/macrobenchmarks.yml

Currently microbenchmarks are broken, because wrong BASE_CI_IMAGE is substituted in CI job.
This PR fixes references to CI images, so both macro- and microbenchmarks work.

chore(ci): fix benchmarks images

---

tests/profiling/collector/test_threading.py

This change updates the expected line number in a failing profile test. Not sure how this managed to pass its pre-merge checks.
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/60875/workflows/96e1dbf5-dd5e-409a-a513-74404953c893/jobs/3818904

ci(profile): update outdated test assumption

---

ddtrace/appsec/_iast/_loader.py
releasenotes/notes/iast-fix-iast-import-error-2eedea126bb9d92d.yaml
tests/appsec/app.py
tests/appsec/iast_packages/packages/pkg_beautifulsoup4.py
tests/appsec/iast_packages/test_packages.py
tests/appsec/integrations/module_with_import_errors.py
tests/appsec/integrations/test_flask_iast_patching.py

When loading a Python module, AST patching was catching the ImportError exception and not propagating it correctly, causing if one wanted to catch this exception, it couldn't be done, generating unexpected effects as in the BeautifulSoup4 package. In Example:
```python
try:
from . import _html5lib
register_treebuilders_from(_html5lib)
except ImportError:
pass
```

fix(iast): unexpected Import error catching

---

.github/CODEOWNERS

Probably should have done this a while ago.  This directory is the new home for certain native-code assets for supporting the libdatadog (profiling) exporter and "stack v2."

chore(codeowners): add new directory to profiling

---

.github/workflows/stale.yml

This change makes inactive issues get closed at a slower rate than inactive pull requests, reflecting actual usage patterns of this repo.

chore: different lifetimes for PRs and issues

---

tests/appsec/iast/test_telemetry.py

chore: mark telemetry test as flaky

---

ddtrace/appsec/_iast/taint_sinks/header_injection.py

In some cases, django patching doesn't work for header injection due to a circular import: https://github.com/DataDog/system-tests/pull/2437

fix(iast): improve header injection patching

---

ddtrace/internal/rate_limiter.py
tests/tracer/test_rate_limiter.py

This pull request introduces a new feature to the rate limiter module by adding a time_window parameter. The end goal is to make the rate limiter configurable, allowing for rate limiting at different time periods such as 1 minute, 1 hour, or the default of 1 second.

chore(internal): add ``time_window`` parameter to rate limiter

---

tests/appsec/iast/test_telemetry.py

flaky telemetry test again

---

tests/appsec/iast/test_telemetry.py

Some sink points that are very commonly called, like `http.client` could be internally while executing telemetry test. This makes these tests check only the required sinks or vulnerabilities.
This should remove flakyness from those tests.

chore: more robust telemetry tests, immune to some internal sink points side effects

---

releasenotes/notes/asm-gprc-import-not-crash-e13c48dcbcc1985e.yaml

chore: remove release note

---

.gitlab/benchmarks.yml

This benchmark test returns timeout and it's blocking the CI

chore(ci): disable flaky benchmark test

---

ddtrace/appsec/_ddwaf/ddwaf_types.py
setup.py
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json

- update libddwaf to 1.18.0
- remove the specific patch to avoid a bug introduced in 1.17.0 and now fixed.

chore(asm): update libddwaf to 1.18.0

---

ddtrace/contrib/mysql/patch.py
ddtrace/contrib/mysqldb/patch.py
ddtrace/contrib/requests/patch.py
ddtrace/contrib/sqlalchemy/patch.py
ddtrace/contrib/sqlite3/patch.py
ddtrace/contrib/urllib3/patch.py
tests/appsec/iast/test_telemetry.py

Enable SQLi and SSRF instrumented sink metric
This PR continues #9214
APPSEC-52863 & APPSEC-52863

chore(iast): sqli and ssrf instrumented sink metric

---

tests/internal/test_serverless.py

This test was messing with the global state of `sys.modules`. It was causing some modules to get unloaded causing them to get re-imported, which would cause issues.
Moving this test to a subprocess test will help isolate the behavior it is trying to test, and simplifies the test setup.

chore(ci): convert serverless slow import test to a subprocess test

---

ddtrace/contrib/botocore/services/bedrock.py
releasenotes/notes/bedrock-response-key-checking-845ef1f191fcc120.yaml

Backports #9173 to 2.9
This PR adds some additional key name checking and adds defaults when `get`ing these attributes. Additionally, adds an additional exception type to catch as a fallback in the case if incorrect response handling.
This PR addresses app-crashing cases where different model versions have different key names for certain output fields.
Fixes #9135 
A follow-up PR will address the discrepancies in more detail when we have time to go through the model providers and make sure our response parsing is up-to-date.

fix(botocore): add defaults for response types and exception handling [backport #9173 to 2.9]

---

ddtrace/internal/constants.py
ddtrace/propagation/http.py
tests/tracer/test_propagation.py

This reverts commit 22302147a2ac3baa03727c73085fd6575fba60e9.
W3C-Datadog header specification has significant gaps and needs to be revised. This change is unreleased so a release note is not required.

revert(distributed_tracing): ensure last datadog parent id tag is always set

---

ddtrace/appsec/_iast/_ast/ast_patching.py
ddtrace/appsec/_iast/_ast/visitor.py
releasenotes/notes/asm-open-disabled-090eefa08b8b69a4.yaml
tests/appsec/iast/taint_sinks/test_path_traversal.py
tests/appsec/iast/test_iast_propagation_path.py

fix(asm): workaround disabling builtins.open aspects [backport 2.9]

---

ddtrace/llmobs/_integrations/langchain.py
tests/contrib/langchain/cassettes/langchain/openai_chain_schema_io.yaml
tests/contrib/langchain/cassettes/langchain_community/lcel_openai_chain_schema_io.yaml
tests/contrib/langchain/test_langchain.py
tests/contrib/langchain/test_langchain_community.py

Backports #9194 to 2.9
Changes the parsing of input/output from chain calls using LangChain. Previously, if a `langchain.schema` type was present in the input or output and was passed into a `json.dumps` call, we would catch a "non-serializable JSON" exception, and log it, not appending the message appropriately to the span event.
This changes the parsing to go over all attributes of input/outputs, and in the case of a non-string, attempts to map it to a string by accessing its content.
Make sure input and output are appropriately tagged on LLMObs span events (fix) for LangChain chains, which are in a readable format (feat, as before it would've read something like `content=xyz` by just stringifying the schema object)
* No release note included as this is an internal bug fix for LLMObs …

fix(llmobs): format langchain schema inputs and outputs [backport #9194 to 2.9]

---

ddtrace/appsec/_common_module_patches.py

We register an import hook to perform the patching of objects to prevent force-loading modules during bootstrap.
This fix a regression introduced by https://github.com/DataDog/dd-trace-py/pull/9246
APPSEC-53121

chore(asm): avoid importing when patching with import hook

---

ddtrace/appsec/_iast/_ast/visitor.py
tests/appsec/iast/aspects/test_ospath_aspects_fixtures.py

In some corner cases, modules with a function like `split` that are also string methods, could call the string method instead of the module function, which could even cause a segmentation fault with the to-be-fixed-on-another-PR `Initializer`.
This also changes the `aspects_specs` from being creating on each instantiation of the `AstVisitor` to being a module constant. This was done mostly for making it easier to test but as a nice side-effect it should improve performance.

fix(asm): fix string aspects potentially being called on module aspects

---

ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
tests/contrib/flask/test_flask_appsec_iast.py

Not report empty cookies vulnerabilities

fix(iast): empty insecure cookies

---

ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectFormat.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.h
ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSplit.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectsOsPath.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.cpp
ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.h
ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.cpp
ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.h
ddtrace/appsec/_iast/_taint_tracking/__init__.py
releasenotes/notes/iast-segfaults-fix-d25c5c132dd8482e.yaml
tests/appsec/iast/aspects/test_add_aspect.py
tests/appsec/iast/aspects/test_bytearray_extend_aspect.py
tests/appsec/iast/aspects/test_format_aspect_fixtures.py
tests/appsec/iast/aspects/test_index_aspect_fixtures.py
tests/appsec/iast/aspects/test_join_aspect_fixtures.py
tests/appsec/iast/aspects/test_ospath_aspects_fixtures.py
tests/appsec/iast/aspects/test_slice_aspect_fixtures.py
tests/appsec/iast/aspects/test_split_aspect.py
tests/appsec/iast/taint_tracking/test_taint_tracking.py

Backport #9284 to 2.9
Fix several segmentation faults (3 confirmed, probably more).
This is done by a small rework of the Initializer which includes:
- Moving `active_map_addreses` from `unordered_set` to `unordered_map` so we can iterate and change it without making a copy (making a copy was actually causing one of the segmentation faults because we were setting the `tx_map` pointer to `nullptr`, but on the copy, not the original, so `get_tainting_map` would return `not nullptr` but still garbage since it was deleted).
- Convert the `TaintRangeMapType` pointer to a `shared_ptr`. This fixed another segfault and makes the codebase more robust.
- Make `ThreadContextCache` not use a dangerously magical number-pointer but just a reference to the active `tx_map` so we only need to check if …

fix(asm): initializer rework and fix for segmentation faults [backport 2.9]

---

.github/CODEOWNERS

as all teams may want to modify it for the settings of hatch tests, make `hatch.toml` a guild file

chore(tracer): hatch.toml as a guild file

---

ddtrace/appsec/_iast/_ast/ast_patching.py
tests/appsec/iast/test_env_var.py

IAST: Performance optimization. Chages logic for IAST allowlist and denylist, now allowlist has precedence over denylist.
---------
Co-authored-by: Alberto Vara <alberto.vara@datadoghq.com>
(cherry picked from commit d0811139d2d101043f7fd20b4c97a9b83a806e22)

perf(iast): improve performance for patching decision [backport 2.9]

---

ddtrace/appsec/_iast/_ast/ast_patching.py
ddtrace/appsec/_iast/_ast/visitor.py

IAST: Performance improvement: Reuse AST Visitor object.

chore(iast): ast Visitor as singleton

---

ddtrace/appsec/_common_module_patches.py
ddtrace/appsec/_iast/taint_sinks/command_injection.py
tests/appsec/contrib_appsec/utils.py

- remove delayed patching for rasp/iast as now rasp patching is always lazy.
- enable rasp threat tests with iast
APPSEC-51853

chore(asm): enable rasp with iast

---

ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
tests/contrib/flask/test_flask_appsec_iast.py

Backport 55a274fb51821a25f8fc00f695d3d49af66e487c from #9288 to 2.9.
Not report empty cookies vulnerabilities

fix(iast): empty insecure cookies [backport 2.8]

---

tests/appsec/appsec/api_security/test_schema_fuzz.py

Add more timeout (50 seconds) for schema computation test for api security test.
The hypothesis fuzzer could create large input and the CI could lag at the same time. This ensures the waf doesn't run out of time.

chore(asm): remove small flakyness in api security test

---

ddtrace/appsec/_common_module_patches.py
ddtrace/appsec/_iast/_ast/visitor.py
ddtrace/appsec/_iast/_patch_modules.py
ddtrace/appsec/_iast/taint_sinks/__init__.py
ddtrace/appsec/_iast/taint_sinks/path_traversal.py
tests/appsec/iast/conftest.py
tests/appsec/iast/taint_sinks/test_path_traversal.py
tests/appsec/iast/test_iast_propagation_path.py
tests/appsec/iast/test_telemetry.py

Revert https://github.com/DataDog/dd-trace-py/pull/9247 and restore path traversal patching but this time, instead to patch `open` by AST, we're monkey patching like we're doing with Exploit Prevention

fix(asm): enabling builtins.open sink point

---

ddtrace/contrib/openai/_endpoint_hooks.py
releasenotes/notes/fix-openai-none-n-kwarg-04e0f81074a13191.yaml
tests/contrib/openai/test_openai_v1.py

Fixes #9283.
If users explicitly pass in `n=None` as a kwarg for OpenAI's completion/chat endpoints, this will break our tracing as we rely on the value of the passed `n` to instantiate a list of `n` elements.
Normally if `n` is not passed into the chat/completion method we assume a default value of 1 via `kwargs.get("n", 1)` but if `n` is explicitly passed as None this breaks our check. This fix ensures we default to a `n=1` in this case.

fix(openai): handle explicit n=None case for chat completions

---

.github/workflows/apm-transport-stress-test.yml
.github/workflows/build-and-publish-image.yml
.github/workflows/build_deploy.yml
.github/workflows/build_python_3.yml
.github/workflows/changelog.yml
.github/workflows/codeql-analysis.yml
.github/workflows/django-overhead-profile.yml
.github/workflows/encoders-profile.yml
.github/workflows/flask-overhead-profile.yml
.github/workflows/lib-inject-publish.yml
.github/workflows/lib-injection.yml
.github/workflows/pr-name.yml
.github/workflows/requirements-locks.yml
.github/workflows/set-target-milestone.yml
.github/workflows/system-tests.yml
.github/workflows/test_frameworks.yml
.github/workflows/upstream-issues.yml

This helps to avoid 'Node.js 16 actions are deprecated.' messages
- checkout v3 -> v4
- setup-python v4 -> v5
- setup-node v3 -> v4
- upload-artifact v3 -> v4
- download-artifact v3 -> v4

chore(ci): update GitHub Actions to latest version

---

ddtrace/contrib/django/utils.py
tests/contrib/django/django_app/appsec_urls.py
tests/contrib/django/test_django_appsec_iast.py

core.dispatch("django.after_request_headers.post") built a invalid cookie payload
```python
def view_insecure_cookies_insecure(request):
res = HttpResponse("OK")
res.set_cookie("insecure_cookie", "cookie_value", secure=False, httponly=True, samesite="Strict")
```
:x: Before:  `{"insecure_cookie": "insecure_cookie=cookie_value; HttpOnly; Path=/; SameSite=Strict"}`
:white_check_mark: After: `{"insecure_cookie": "cookie_value; HttpOnly; Path=/; SameSite=Strict"}`
or if the cookie was empty
```
def view_insecure_cookies_insecure(request):
res = HttpResponse("OK")
res.set_cookie("insecure_cookie", "", secure=False, httponly=True, samesite="Strict")
```
:x: Before:  `{"insecure_cookie": "insecure_cookie=""; HttpOnly; Path=/; SameSite=Strict"}`
:white_check_mark: After: `{"insecure_cookie": "; …

fix: error parsing django cookies

---

.github/workflows/build-and-publish-image.yml
.github/workflows/pypa_musllinux_1_2_i686.yml
docker/Dockerfile.pypa_musllinux_1_2_i686

We need to get i686-unknown-linux-musl compatible rust compiler into the pypa i686 musl image for use with cibuildwheel in order to support compiler rust extensions.
The PR originally built and published the image from this PR. This resulted in the following image being created: https://github.com/DataDog/dd-trace-py/pkgs/container/dd-trace-py%2Fpypa_musllinux_1_2_i686
This image was tested locally to ensure ddtrace would build properly:
```
$ docker run --rm -it ghcr.io/datadog/dd-trace-py/pypa_musllinux_1_2_i686:latest /bin/sh
> git clone https://github.com/DataDog/dd-trace-py.git
> cd ./dd-trace-py
> git checkout brettlangdon/core.rate_limiter
> python3.12 -m pip install .
```
This was also tested by updating the `build` job for the PR #9232, showing it working as expected with …

chore(ci): add custom pypa_musllinux_1_2_i686 image with Rust compiler

---

ddtrace/debugging/_exception/auto_instrument.py
tests/debugging/exception/test_auto_instrument.py

The change that added third-party code detection to exception replay introduced a potential infinite loop. We change the coding to avoid that scenario.

chore(di): fix infinite loop in exception replay

---

.gitlab/macrobenchmarks.yml

More macrobenchmarks, grouped with a name for better discovery in UI

ci: grouped macrobenchmarks

---

ddtrace/appsec/_iast/_ast/ast_patching.py

While a new PR with a fix for the `terminate` calls caused by uncatched exceptions coming from pybind11 is coming, this adds the urlreverse Django's test to the ignore list (which is needed anyway because the `assertRaises` of a testcase eats any exceptions so the `join_aspect` can't catch it and call the original function).

chore: ignore django test for patching

---

ddtrace/internal/assembly.py
ddtrace/internal/wrapping/context.py
tests/internal/test_wrapping.py

We introduce a new mechanism of wrapping functions via a special context manager that is capable of capturing return values as well. The goal is to allow observability into the called functions, to have access to local variables on exit. This approach has the extra benefit of not introducing any extra frames in the call stack of the wrapped function.

chore(internal): bytecode wrapping context

---

ddtrace/debugging/_redaction.py
tests/debugging/exception/test_auto_instrument.py

Consolidate PII redaction keys for all libraries.
Related PRs:
`dotnet` - https://github.com/DataDog/dd-trace-dotnet/pull/5522
`java` - https://github.com/DataDog/dd-trace-java/pull/6980

chore(debugger): consolidate pii redaction keys for all libraries

---

.github/CODEOWNERS
ddtrace/__init__.py
ddtrace/appsec/_common_module_patches.py
ddtrace/appsec/_iast/_overhead_control_engine.py
ddtrace/appsec/_processor.py
ddtrace/internal/_unpatched.py
ddtrace/internal/utils/http.py
ddtrace/profiling/_threading.pyx
ddtrace/profiling/collector/stack.pyx
tests/.suitespec.json

To improve performances and avoid unwanted interactions with exploit prevention, this PR ensures that we used unpatched open function for loading rules or blocking content for asm.
- add `_unpatched` module to keep track of unpatched references
- move threading to _unpatched
- ensure we use the unpatched version of open for blocking content and waf rule files

chore(asm): use unpatched open for asm

---

ddtrace/debugging/_debugger.py
ddtrace/debugging/_function/store.py
ddtrace/debugging/_signal/snapshot.py
tests/debugging/function/test_store.py
tests/debugging/test_debugger.py

We make use of the new bytecode context wrapping to gain access to local variables in function probes.

chore: retrieve locals from function probes

---

ddtrace/internal/flare/_subscribers.py
ddtrace/internal/flare/flare.py
ddtrace/internal/flare/handler.py
ddtrace/settings/config.py
tests/internal/test_tracer_flare.py

This PR fixes two bugs with the tracer flare.
First, the RC poller behavior for the tracer flare. Prior to this PR, it would assume that the first product when polling the RC backend would be the target config/metadata we need. However, this is not a safe assumption as multiple products could be updated and polled at once. This, in addition to the fact that currently the tracer flare shares the `AGENT_CONFIG` and `AGENT_TASK` product with the **agent** flare, means that we need to check all products to ensure we don't accidentally skip a tracer flare product.
Second, we were passing in the RC config, not the actual ddtrace config when generating the config file for the flare. This is fixed, and the correct config is being generated now.

fix(tracer): ensure all metadata and configs are checked for flare + correct config file

---

.github/workflows/test_frameworks.yml

CI: parametrize framework tests to run them separately with Profiling, IAST or Appsec enabled

ci: parametrized framework tests

---

ddtrace/appsec/_iast/_ast/visitor.py
ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectExtend.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
ddtrace/appsec/_iast/_taint_tracking/aspects.py
releasenotes/notes/no-terminate-on-extend-join-aspects-0cf5ddcaaf836168.yaml
tests/appsec/iast/aspects/test_bytearray_extend_aspect.py
tests/appsec/iast/aspects/test_ospath_aspects.py

fix(asm): avoid terminate being called on native aspect [backport 2.9]

---

.github/CODEOWNERS
ddtrace/__init__.py
ddtrace/appsec/_processor.py
ddtrace/internal/_unpatched.py
ddtrace/internal/utils/http.py
ddtrace/profiling/_threading.pyx
ddtrace/profiling/collector/stack.pyx
tests/.suitespec.json

Backport of https://github.com/DataDog/dd-trace-py/pull/9326

chore(asm): use unpatched open for asm [backport 2.9]

---

tests/internal/service_name/test_extra_services_names.py

Marking flaky tests exposed from running CI on another PR: https://github.com/DataDog/dd-trace-py/pull/9339

chore(flake): marking `test_service_name` as flaky

---

.github/workflows/test_frameworks.yml

Avoids these kind of errors in the CI: https://github.com/DataDog/dd-trace-py/actions/runs/9204318180/job/25317642591?pr=9344#step:8:62

ci: upgrade pytest for requests framework test

---

ddtrace/appsec/_capabilities.py
tests/appsec/appsec/test_remoteconfiguration.py

This PR adds all exploit prevention capabilities and enable 2 of them RASP_LFI and RASP_SSRF, if remote config and exploit prevention are enabled in the tracer.

chore(asm): add exploit prevention capabilities

---

.github/workflows/lib-inject-prune.yml

These jobs are failing: https://github.com/DataDog/dd-trace-py/actions/runs/9223336076

chore(ci): fix up injection image prune job

---

.github/workflows/test_frameworks.yml
ddtrace/internal/compat.py

Add BeautifulSoup and Sanic to the framework tests.  
Add a small fix in `ddtrace/internal/compat.py` to avoid raising an error if we receive a mock instead of a string. There is the error: https://github.com/DataDog/dd-trace-py/actions/runs/9223552867/job/25377041389#step:7:257

chore(ci): bs4 & sanic framework test

---

ddtrace/llmobs/_utils.py
ddtrace/propagation/http.py

This PR is a follow up of #9152, and attempts to minimize any added memory overhead by moving the `llmobs` utility import to inside the conditional check that `LLMObs` is enabled.
By importing inside the `ddtrace.llmobs.` directory we are implicitly running the `ddtrace.llmobs.__init__.py` code, which involves instantiating a `LLMObs` instance. This is likely the largest culprit of the memory overhead.
Moving the import to only happening if LLMObs is enabled should avoid that added overhead, given that LLMObs is only running in a select few customer applications at the moment.

fix(llmobs): fix propagation memory usage

---

ddtrace/internal/telemetry/writer.py
tests/telemetry/test_telemetry_metrics.py

Telemetry: Wrong payload format is being sent to Telemetry logs.
See System Test: https://github.com/DataDog/system-tests/pull/2392
(cherry picked from commit 104d7522aa124fa77617929084bccbfb0e998441)

fix(telemetry): logs payload format [backport 2.7]

---

lib-injection/Dockerfile
releasenotes/notes/lib-inject-base-image-dffa9a9579a9350d.yaml

3.18.3 has a known vulnerability, CVE-2023-5363 that can trigger warnings even though this image is not used to run any applications.

chore(lib-injection): update base image to alpine 3.20

---

ddtrace/contrib/openai/_endpoint_hooks.py
ddtrace/llmobs/_integrations/base.py
ddtrace/llmobs/_integrations/bedrock.py
ddtrace/llmobs/_integrations/openai.py
ddtrace/llmobs/_trace_processor.py

This PR adds a fix to add handling for integration-generated spans for LLMObs parent ID propagation. #9152 added a edge case handling in `LLMObs._start_span()` if the span was part of the first service in a distributed trace, in which case we would need to check the `span.get_tag(PROPAGATED_PARENT_KEY)` due to the distributed header being propagated upwards to the local root of the original service at span finish time (but would always be propagated to all spans in subsequent services at span start time).
Integration (openai, bedrock, langchain) generated spans use `BaseLLMIntegration.trace(...)` instead of `LLMObs._start_span()` so we needed to add handling here.

fix(llmobs): add parent ID handling for integration-generated spans

---

scripts/ddtest

We set the size of core dumps to unlimited at runtime inside the testrunner image instance to allow any failing tests with fatal error to generate core dumps.

ci: set ulimit inside the testrunner instance

---

ddtrace/internal/writer/writer.py
releasenotes/notes/fix-internal-writer-recreate-keep-extra-headers-dc8cd1d57c95d692.yaml
tests/tracer/test_writer.py

internal: this fixes an issue where a writer recreate call would make it drop extra headers passed to the ``__init__``.

fix(internal): writer recreate maintain extra headers

---

ddtrace/llmobs/_llmobs.py

Increase the default timeout for writing llmobs span evens and evaluation metrics. We've seen timeout errors with the default 2 seconds, so bump it to 5 to be more generous.

chore(llmobs): increase default write timeout

---

ddtrace/appsec/_constants.py
ddtrace/appsec/_trace_utils.py
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json

ASM: Adds appsec propagation tag to any (and all) traces with security events

chore(asm): appsec propagation tag

---

tests/.suitespec.json
tests/tracer/test_propagation.py

Ensure we run tracer tests whenever we make changes to llmobs.
This would have caught this failing test, which did not run on #9449
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/62935/workflows/f6fd3f80-bbf7-46cc-b4ee-189f49578fc8/jobs/3917045

chore(ci): ensure we run tracer tests on llmobs changes

---

tests/tracer/test_propagation.py

#9455 fixed a failing test in the tracer test suite due to not being tested when llmobs made some changes to `_inject_llmobs_parent_id()`, and also ensured that tracer tests run on llmobs changes moving forward.
This PR also changes the corresponding tracer tests to be less focused on exact implementation of `_inject_llmobs_parent_id()`, as `tests/llmobs/test_propagation.py` is responsible for testing the actual injection logic. We only care on the tracer propagation test level that `_inject_llmobs_parent_id()` is called if llmobs is enabled.

chore(tracer): simplify llmobs injection assertion on tracer propagation tests

---

ddtrace/llmobs/_llmobs.py
ddtrace/settings/config.py
releasenotes/notes/llmobs-deprecate-ml-app-name-71c71132c700f3ac.yaml
tests/llmobs/test_llmobs_decorators.py
tests/llmobs/test_llmobs_service.py
tests/llmobs/test_llmobs_trace_processor.py

This PR changes the environment variable name for the user's ML application name from `DD_LLMOBS_APP_NAME` to `DD_LLMOBS_ML_APP` to better reflect LLM Observability's corp docs and guides.
We are deprecating the old name instead of removing it outright so that users won't break their apps.

chore(llmobs): deprecate name of ML app env var

---

tests/internal/test_packages.py

This is a manual backport to fix the CI. The fix is cherry-picked from https://github.com/DataDog/dd-trace-py/pull/9339. We don't want to backport this entire PR because the tracer flare is not in scope for 2.9

chore(ci): fix incorrect importlib_metadata name

---

.gitlab/benchmarks.yml
benchmarks/Dockerfile

1. Update python and pyenv versions in microbenchmarks.
2. Dogfooding stage won't block benchmarks anymore.
3. Simplify a call to bp-runner.
4. Ensure that benchmarks' PR comment is created, even when dogfooding fails.

chore(ci): restore microbenchmarks runs

---

tests/tracer/test_tracer.py

This change updates `join()` calls in `test_tracer.py` to limit the amount of time they can spend waiting on a hung subprocess, fixing CI failures like [this one](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/63032/workflows/a935d176-194e-41e7-8c34-f824a8bcff77/jobs/3921815). After this change, this example would still be a test failure, but it would also run all subsequent tests in the suite rather than timing out midway through.

ci(tracer): limit time spent waiting for subprocesses to join in tracer tests

---

.gitlab/benchmarks.yml

This change avoids running Gitlab jobs on the main branch that have been failing consistently recently. One of them, `benchmarks-pr-comment`, is not applicable outside the context of a pull request and thus can remain disabled on the main branch. The other is a serverless benchmark job that would ideally run and pass on main. This change should be considered a stopgap to be kept in place only until the job failure is resolved.

ci: avoid running failing benchmark gitlab jobs on main branch

---

tests/contrib/langchain/test_langchain_community.py

This change marks some unreliable tests in the langchain_community suite. Some of these had been recently unmarked in https://github.com/DataDog/dd-trace-py/commit/ecc56cf09809703e8e1260435ba956cd1b31aa7e, but it seems like they still have some underlying unreliability ([example](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/63192/workflows/693a2566-c19c-43c9-9f62-fda445a51e29/jobs/3926490)).

ci: mark unreliable langchain_community tests

---

tests/appsec/integrations/pygoat_tests/test_pygoat.py

These tests recently started [failing reliably](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/63423/workflows/0223d1e4-4426-4117-92bb-b7848420989c/jobs/3937986) on the main branch, so they're skipped here to keep CI unblocked.

ci(appsec): skip pygoat tests because they are failing on main

---

tests/appsec/integrations/pygoat_tests/Dockerfile.pygoat.2.0.1
tests/appsec/integrations/pygoat_tests/test_pygoat.py

ci: force pyyaml reinstall in pygoat dockefile

---

CHANGELOG.md

Update CHANGELOG.md to reflect changes we made in the [GitHub release note](https://github.com/DataDog/dd-trace-py/releases/tag/v2.9.0)

docs: updated changelog to reflect changes in GH 2.9.0 release note

---

.github/CODEOWNERS

This PR makes the team @DataDog/ml-observability as codeowners for the Anthropic integration.

chore(anthropic): make team ml-obs as codeowners

---

ddtrace/appsec/_capabilities.py
tests/appsec/appsec/test_remoteconfiguration.py

Following https://github.com/DataDog/dd-trace-py/pull/9450. 
- Add capabilities for exploit prevention sqli
- Update tests

chore(asm): add sqli capabilities to exploit prevention RC

---

.github/CODEOWNERS

`tests/utils.py` contains a lots of tools for all test suites and it would make sense to put it under the python-guild review instead of the default apm-core

chore(ci): ownership change

---

releasenotes/notes/add-anthropic-streaming-support-01937d2e524f1bd0.yaml

Make 2 separate release notes for anthropic streaming support

chore(release notes): fix anthropic release note

---

.circleci/config.templ.yml
tests/appsec/iast_packages/test_packages.py

CI: Disables Pyarrow IAST package test as it's failing consistently on CI

ci: disable pyarrow iast package test

---

.gitlab/macrobenchmarks.yml

Improve macrobenchmarks by using the new BP_ENDPOINT env var to set the endpoint to test. See
https://github.com/DataDog/benchmarking-platform/pull/68
This way we can add worst case scenarios for AppSec and IAST, added in the PR as well.
(cherry picked from commit ec618736689caed90fa62fe1a478e95e7b9251e2)

ci: improve macrobenchmarks [backport 2.9]

---

tests/internal/test_packages.py

Follow-up on: https://github.com/DataDog/dd-trace-py/pull/9467/files#r1642430035

ci: add `importlib_metadata` to `test_get_distributions`

---

tests/internal/test_packages.py

Follow-up on:
https://github.com/DataDog/dd-trace-py/pull/9467/files#r1642430035
(cherry picked from commit 68bb423a2ed3ef23a87eb34d32ac96c8d1005016)

ci: add `importlib_metadata` to `test_get_distributions` [backport 2.8]

---

.gitlab/macrobenchmarks.yml

Improve macrobenchmarks by using the new BP_ENDPOINT env var to set the endpoint to test. See
https://github.com/DataDog/benchmarking-platform/pull/68
This way we can add worst case scenarios for AppSec and IAST, added in the PR as well.
(cherry picked from commit ec618736689caed90fa62fe1a478e95e7b9251e2)

ci: improve macrobenchmarks [backport 2.8]

---

.gitlab/macrobenchmarks.yml

CI: adds option to retry the macrobenchmarks, useful since we can fail to allocate all the required machines for running the different scenarios at once
(cherry picked from commit 30f6413449eeb806d0d95ee5be7f73398d7de77d)

ci: add macrobenchmarks retry option [backport 2.8]

---

repository.datadog.yml

Remove the internal `/merge` merge queue helper command since it doesn't work on this repo.

chore: disable internal merge queue settings

---

ddtrace/contrib/futures/threading.py
releasenotes/notes/fix-futures-propagation-f5b33579e0fdafc3.yaml
tests/contrib/futures/test_propagation.py

There is a bug when scheduling work onto a `ThreadPoolExecutor` and not waiting for the response (e.g. `pool.submit(work)`, and ignoring the future) we not properly associate the spans created in the task with the trace that was active when submitting the task.
The reason for this bug is because we propagate the currently active span (parent) to the child task, however, if the parent span finishes before the child task can create it's first span, we no longer consider the parent span active/available to inherit from. This is because our context management code does not work if passing spans between thread or process boundaries.
The solution is to instead pass the active span's Context to the child task. This is a similar process as passing context between two services/processes via HTTP …

fix(futures): fix incorrect context propgation with ThreadPoolExecutor

---

ddtrace/contrib/grpc/server_interceptor.py
releasenotes/notes/asm-new-gprc-server-propagation-89812a5e161fe0f6.yaml
tests/appsec/iast/test_grpc_iast.py

Adds tainting support for gRPC server sources.

feat(asm): add propagation for grpc server sources

---

ddtrace/llmobs/utils.py
releasenotes/notes/fix-llmobs-document-typing-5ff08feef2659220.yaml

Resolves #9600.
This PR addresses the incorrect typing hint in the `ddtrace.llmobs.utils.py` Documents constructor. The documents constructor currently accepts integer/float values for the document score field, but the typing specifies only string field values. The typing fix resolves this inconsistency.

fix(llmobs): fix document typing

---

ddtrace/profiling/collector/_lock.py
releasenotes/notes/profiling-add-lock-with-f75908e35a70ab71.yaml
tests/profiling/collector/test_threading.py

Python profiler doesn't capture lock usages with `with lock:` statement even though this seems to be more common usage pattern. 
GitHub search with `/with.*lock:/ language:Python -path:test` shows [228k code results](https://github.com/search?q=%2Fwith.*lock%3A%2F+language%3APython+-path%3Atest&type=code)
GitHub search with `/.*lock.acquire\(\)/ language:Python -path:test` shows [89.1k code results 
](https://github.com/search?q=%2F.*lock.acquire%5C%28%5C%29%2F+language%3APython+-path%3Atest&type=code)
We'll get more lock related samples in profiles with this change.

fix(profiling): capture lock usages with `with` statement context managers

---

.github/CODEOWNERS

chore(ci): remove @DataDog/apm-core-python from profiling paths

---

tests/internal/test_packages.py

Follow-up on:
https://github.com/DataDog/dd-trace-py/pull/9467/files#r1642430035
(cherry picked from commit 68bb423a2ed3ef23a87eb34d32ac96c8d1005016)

ci: add `importlib_metadata` to `test_get_distributions` [backport 2.7]

---

docker-compose.yml

#9119 incorrectly added pygoat to the `docker-compose.yml` file, which was not merged in the 2.7 branch. This fixes it.

ci: remove wrongly backported pygoat in docker compose from 2.7

---

.github/workflows/test_frameworks.yml

HTTPX 0.22.0 requirements.txt uses a notation not compatible with latest `pip` (24.1).
This PR downgrades pip to 24.0 before trying to install HTTPX requirements.

ci: downgrade pip to 24.0 for httpx

---

ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt
setup.py
tests/profiling/collector/test_threading.py
tests/profiling/test_profiler.py

stack v2 and the libdatadog uploader have been built as part of the normal ddtrace wheel distribution process for a while.
A recent PR also made this non-optional, so builds of these products must succeed.
However, for inplace builds (which is what is used to run tests), while the build process itself was "succeeding," it failed to copy non-module products from the temporary build directory into the source directory.
This fixes that, adds tests for it, and cleans up some other debris around the change of interface.

chore(profiling): fixups for profiling cmake artifacts

---

ddtrace/internal/ci_visibility/recorder.py
tests/ci_visibility/test_ci_visibility.py

`DD_CIVISIBILITY_AGENTLESS_URL` is an env var meant for internal use (mainly testing) to override endpoints the tracer should send data to (or make requests to).
This fixes the fact that the env var was not being used to control where CI visiblity setting, and skippable test requests were being sent.
No changelog as the env var is not meant for public use.

chore(ci_visibility): respect DD_CIVISIBILITY_AGENTLESS_URL when set

---

ddtrace/contrib/pytest/_plugin_v1.py
ddtrace/internal/ci_visibility/utils.py
releasenotes/notes/fix-ci_visibility-properly_unwrap_functions-7c631b68720adab2.yaml
tests/contrib/pytest/test_pytest.py

Backport 203e89489f1e698a127317dc57b01e9d6467e859 from #9586 to 2.9.
Fixes an issue where decorated test functions could resolve to the wrong location when certain decorators (eg: @mock.patch) were used.
This also fixes the fact that source file info paths might not always be relative to the current repo root.
The test added in this PR verifies the above by using a variety of decorators as well as executing from the `nested_dir` directory instead of the git repo root, with the source file info properly showing the path as `nested_dir/test_mydecorators.py`.

 fix(ci_visibility): properly resolve decorated functions for test source file information [backport 2.9]

---

ddtrace/contrib/pytest/plugin.py
releasenotes/notes/fix-ci_visibility-properly_unwrap_functions-7c631b68720adab2.yaml
tests/contrib/pytest/test_pytest.py

Backport 203e89489f1e698a127317dc57b01e9d6467e859 from #9586 to 2.7.
Fixes an issue where decorated test functions could resolve to the wrong location when certain decorators (eg: @mock.patch) were used.
This also fixes the fact that source file info paths might not always be relative to the current repo root.
The test added in this PR verifies the above by using a variety of decorators as well as executing from the `nested_dir` directory instead of the git repo root, with the source file info properly showing the path as `nested_dir/test_mydecorators.py`.

fix(ci_visibility): properly resolve decorated functions for test source file information [backport 2.7]

---

ddtrace/contrib/pytest/plugin.py
releasenotes/notes/fix-ci_visibility-properly_unwrap_functions-7c631b68720adab2.yaml
tests/contrib/pytest/test_pytest.py

Backport 203e89489f1e698a127317dc57b01e9d6467e859 from #9586 to 2.8.
Fixes an issue where decorated test functions could resolve to the wrong location when certain decorators (eg: @mock.patch) were used.
This also fixes the fact that source file info paths might not always be relative to the current repo root.
The test added in this PR verifies the above by using a variety of decorators as well as executing from the `nested_dir` directory instead of the git repo root, with the source file info properly showing the path as `nested_dir/test_mydecorators.py`.

 fix(ci_visibility): properly resolve decorated functions for test source file information [backport 2.8]

---

.github/workflows/test_frameworks.yml

HTTPX 0.22.0 requirements.txt uses a notation not compatible with latest `pip` (24.1).
This PR downgrades pip to 24.0 before trying to install HTTPX requirements.
(cherry picked from commit 03650f8b59624561d33b0d138503a6bd700e8518)

ci: downgrade pip to 24.0 for httpx [backport 2.10]

---

tests/contrib/tornado/test_executor_decorator.py

Fix failing tornado jobs.
When we updated the `ThreadPoolExecutor` implementation to pass `Context` instead of `Span` one piece of information we are not passing along is the current Span's "service".
We do not need this since spans created within the `ThreadPoolExecutor` will use the `DD_SERVICE` that is set.
These tests do not set a `DD_SERVICE` so it is expected that their service names are `None` (will inherit from their parent).

chore(tornado): fix failing tornado test cases

---

tests/.suitespec.json
tests/telemetry/test_writer.py

This change resolves a reliable failure from the `main` branch that appears to have resulted from the `telemetry` suite not running on a `profiling` change that affected it: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/64311/workflows/c67de0aa-58b3-42ca-8f52-68d6ea9b45a8/jobs/3979111

ci(telemetry): fix incorrect assertion in telemetry test

---

tests/.suitespec.json

This change updates the suitespec to run the tornado and tracer suites on pull requests that change `contrib/futures`. This is necessary because https://github.com/DataDog/dd-trace-py/pull/9588 introduced failures ([1](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/64311/workflows/c67de0aa-58b3-42ca-8f52-68d6ea9b45a8/jobs/3979086) [2](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/64311/workflows/c67de0aa-58b3-42ca-8f52-68d6ea9b45a8/jobs/3979102)) in those suites that were only discovered post-merge.

ci(tornado): run the tornado suite when the futures contrib changes

---

ddtrace/appsec/_common_module_patches.py
tests/appsec/appsec/test_exploit_prevention.py

LFI exploit prevention is encapsulating all regular calls to builtins.open in a wrapper.
If, for any regular reason, the call is raising an Exception (like FileNotFound), the top of the trace is pointing inside the wrapper, obfuscating the initial line of code in the customer code that is responsible for the exception.
This PR adds back that frame on top of the exception traceback. This is not perfect as the instrumentation is still present in the strack trace and the initial frame will be duplicated, but it definitely makes easier to find the root cause of the exception.

chore(asm): add initial frame on top of traceback for lfi exploit prevention for regular exception

---

ddtrace/internal/module.py

We restore the original loader after a module has been imported. We only need our custom chained loader while the module is being imported to allow the import hooks to be triggered at the right time. There is no need for the custom loader once the module is fully imported.

chore: restore module loader after import

---

ddtrace/contrib/pytest/constants.py

This bumps the minimum `pytest` version for ITR-supported behavior, but that version check is only happening when enabling the new internal coverage collector.

chore(ci_visibility): bump minimum ITR-supported pytest

---

.github/workflows/test_frameworks.yml

HTTPX 0.22.0 requirements.txt uses a notation not compatible with latest `pip` (24.1).
This PR downgrades pip to 24.0 before trying to install HTTPX requirements.
(cherry picked from commit 03650f8b59624561d33b0d138503a6bd700e8518)

ci: downgrade pip to 24.0 for httpx [backport 2.9]

---

.github/workflows/test_frameworks.yml

HTTPX 0.22.0 requirements.txt uses a notation not compatible with latest `pip` (24.1).
This PR downgrades pip to 24.0 before trying to install HTTPX requirements.
(cherry picked from commit 03650f8b59624561d33b0d138503a6bd700e8518)

ci: downgrade pip to 24.0 for httpx [backport 2.7]

---

.circleci/config.templ.yml

We only build for 6 Python versions, so 2 runners spin up, do nothing, and stop.

chore(ci): reduce build base venv job from 8 to 6

---

.circleci/config.templ.yml

Improve library build times across all jobs by setting `CMAKE_BUILD_PARALLEL_LEVEL` in most task environments.
Current p95 `build_base_venv` duration:
This change reduces `build_base_venvs` to <4 minutes. It also has an impact on hatch jobs (e.g. `slotscheck`, `conftests`, `build_docs`, etc).

chore(ci): increase cmake parallelization level

---

tests/appsec/appsec/test_processor.py

remove flaky decorator in tests/appsec/appsec/test_processor.py and prevent flakyness by using a large waf timeout

chore(asm): remove flaky decorator and add more waf timeout

---

.github/workflows/build_python_3.yml
scripts/zip_filter.py

It looks like the centos project has decomissioned the package repositories for centos 5 and 7.  Since our cibuildwheel configuration has us stripping source files out of the wheel during the repairwheel phase, this breaks our CI as we rely on centos.
The centos thing will probably emerge as a significant issue, but I noticed that the manylinux docker image has the `zipfile` library, so I wrote a drop-in replacement for our use of `zip -d`.  Looks like it works.

chore(ci): deal with missing zip dependency

---

lib-injection/README.md

This change fixes https://github.com/DataDog/dd-trace-py/issues/9606 by noting directly in the lib-injection documentation that it works without ddtrace-run and other manual instrumentation methods.

docs: explicitly say in lib-injection docs that it doesnt require ddtrace-run

---

ddtrace/profiling/collector/_lock.py
ddtrace/settings/profiling.py
riotfile.py

chore(profiling): add debug asserts for our stack assumptions

---

ddtrace/profiling/collector/_lock.py
releasenotes/notes/profiling-timeline-lock-init-loc-and-frames-39a43f924bde88d2.yaml
tests/profiling/collector/test_asyncio.py
tests/profiling/collector/test_threading.py
tests/profiling/collector/test_threading_asyncio.py
tests/profiling/simple_program_fork.py

- Lock Name shows the line number of where `acquire/release/__enter__/__exit__` was called, which is duplicated in the Call Stack 
- Call Stack shows a frame for Profiler internal function, [\_\_enter\_\_](https://github.com/DataDog/dd-trace-py/blob/42ccea9b13e232bcce4a1d20b9d11eda7904226d/ddtrace/profiling/collector/_lock.py#L235)
- Lock Name shows the line number where the lock was initialized. 
- Call Stack shows user codes only. 
This actually reverts some of the changes I made in https://github.com/DataDog/dd-trace-py/pull/9615, but I believe this PR makes everything clearer.

fix(profiling): show lock init location and hide internal frame

---

ddtrace/internal/remoteconfig/_publishers.py
ddtrace/internal/remoteconfig/client.py
pyproject.toml

Remove dependencies to `attrs` and `cattrs` in remoteconfig.
- Use dataclasses
- use post_init to simulate validators and parsers
After that PR, `cattrs` is **no longer used** in ddtrace and removed from install dependencies

chore(tracer): remove attr and cattr from remoteconfig

---

ddtrace/internal/packages.py
releasenotes/notes/fix_packages_oserror-b8da190cea6997de.yaml
tests/internal/test_packages.py

This should fix the issue reported in #9718 , whereby pathlib propagates an OSError from the underlying WindowsPath implementation.  This is an allowed error as per the [docs](https://docs.python.org/3/library/pathlib.html#pathlib.WindowsPath).
I'm proposing a test for this, but I'm actually unable to validate the fix since I don't have the means to test this without significant investment.  Hopefully a reviewer can suggest something...

fix(internal): catch pathlib OSError in packages.py

---

.github/workflows/build_deploy.yml
.github/workflows/build_python_3.yml

Parallelize building wheel using unique identifier used by cibuildwheel, which is a combination of python version, target OS, and target architecture. 
We've been building wheels in parallel across OS's used for builds, as defined [here](https://github.com/DataDog/dd-trace-py/blob/bc14f9f982f1412ed16774d13d210de696e4525b/.github/workflows/build_python_3.yml#L20-L29). For `ubuntu-latest`, it has to build all combinations of `[manylinux, musllinux] * [x86_64, i686]` in serial, which takes about ~[23 mins](https://github.com/DataDog/dd-trace-py/actions/runs/9783802837/job/27013245565). 
However, when split into unique identifier, the slowest one takes about ~9 mins. 
To reviewer: We'd need to change the set of required CI checks from previous set of build_wheels to these new ones. Please let …

chore(ci): parallelize build wheels

---

.github/workflows/build_python_3.yml
scripts/zip_filter.py

Backport for https://github.com/DataDog/dd-trace-py/pull/9697
It looks like the centos project has decomissioned the package repositories for centos 5 and 7. Since our cibuildwheel configuration has us stripping source files out of the wheel during the repairwheel phase, this breaks our CI as we rely on centos.
The centos thing will probably emerge as a significant issue, but I noticed that the manylinux docker image has the `zipfile` library, so I wrote a drop-in replacement for our use of `zip -d`. Looks like it works.

chore(ci): deal with missing zip dependency [backport 2.10]

---

.github/workflows/build_python_3.yml
scripts/zip_filter.py

Backport for https://github.com/DataDog/dd-trace-py/pull/9697
It looks like the centos project has decomissioned the package repositories for centos 5 and 7.  Since our cibuildwheel configuration has us stripping source files out of the wheel during the repairwheel phase, this breaks our CI as we rely on centos.
The centos thing will probably emerge as a significant issue, but I noticed that the manylinux docker image has the `zipfile` library, so I wrote a drop-in replacement for our use of `zip -d`.  Looks like it works.

chore(ci): deal with missing zip dependency [backport 2.9]

---

.github/workflows/build_python_3.yml
scripts/zip_filter.py

Backport for https://github.com/DataDog/dd-trace-py/pull/9697
It looks like the centos project has decomissioned the package repositories for centos 5 and 7. Since our cibuildwheel configuration has us stripping source files out of the wheel during the repairwheel phase, this breaks our CI as we rely on centos.
The centos thing will probably emerge as a significant issue, but I noticed that the manylinux docker image has the `zipfile` library, so I wrote a drop-in replacement for our use of `zip -d`. Looks like it works.

chore(ci): deal with missing zip dependency [backport 2.8]

---

hatch.toml

pytest-coverage is obsolete and pytest-cov should be used instead

chore(asm): replace dependency with updated one

---

ddtrace/internal/datadog/profiling/dd_wrapper/include/interface.hpp
ddtrace/internal/datadog/profiling/dd_wrapper/include/profile.hpp
ddtrace/internal/datadog/profiling/dd_wrapper/include/sample.hpp
ddtrace/internal/datadog/profiling/dd_wrapper/src/interface.cpp
ddtrace/internal/datadog/profiling/dd_wrapper/src/profile.cpp
ddtrace/internal/datadog/profiling/dd_wrapper/src/sample.cpp
ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
ddtrace/internal/datadog/profiling/stack_v2/include/stack_renderer.hpp
ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp
releasenotes/notes/fix-stack-v2-task-encoding-447f39478749027c.yaml
setup.py

Backport da759a93a772d88120f4983d7fdf8c34699152f2 from #9501 to 2.8.
This adjusts the stack V2 API in order to conform to the new proposed echion renderer.  This also fixes an encoding error in stack V2 which was caused by the old task renderer.

fix(profiling): fix encoding-related issues in stack v2 [backport 2.9] (#9501)

---

ddtrace/contrib/langchain/patch.py
releasenotes/notes/langchain-non-dict-inputs-310427c510acf1e5.yaml
tests/contrib/langchain/test_langchain_community.py
tests/snapshots/tests.contrib.langchain.test_langchain_community.test_lcecl_chain_non_dict_input.json

Backport d012b1da5e6662dfd91cca1bbfc9f576e61e7681 from #9747 to 2.9.
Tags langchain LCEL chain non-dict inputs appropriately. Previously, this logic considered strings and, as a default, dicts. This PR changes this logic to consider non-dicts (and stringify), and then fall back on it being a dict.
Fixes #9707 
This PR cherry-picks #9706 to add a test and run CI

fix(langchain): tag non-dict inputs appropriately [backport 2.9]

---

.github/workflows/system-tests.yml

Backport for https://github.com/DataDog/dd-trace-py/pull/9741
Per title
(cherry picked from commit 2022a3bf338c3a90d3dfd179e504c3904e8228c9)

ci: switch system-tests to python 3.12 [backport 2.7]

---

.github/workflows/system-tests.yml

As it was done in https://github.com/DataDog/dd-trace-py/pull/9741

chore(ci): use python 3.12 for parametric tests

---

ddtrace/_trace/tracer.py
ddtrace/internal/serverless/__init__.py
ddtrace/internal/serverless/mini_agent.py
ddtrace/internal/writer/writer.py
ddtrace/settings/config.py
releasenotes/notes/allow-mini-agent-to-run-on-all-hosting-plans-5e8df7330c108d71.yaml
tests/internal/test_serverless.py

Runs the Serverless Mini Agent for Azure Functions on all consumption plans not just if the hosting plan is consumption.
The changes were tested by running the test suite for the internal folder using the following instructions for the repo: https://ddtrace.readthedocs.io/en/stable/contributing-testing.html#testing-guidelines
(cherry picked from commit 4f31f7e0e7c0d8f2cb2e4c225c8d187fee84a83a)

fix(azure_functions): run the mini agent regardless of azure hosting plan [backport 2.10]

---

.github/workflows/system-tests.yml

Manual backport of https://github.com/DataDog/dd-trace-py/pull/9775 for 2.9
As it was done in https://github.com/DataDog/dd-trace-py/pull/9741

chore(ci): use python 3.12 for parametric tests (#9775) [backport 2.9]

---

.github/workflows/system-tests.yml

Manual backport of #9775 for 2.8
As it was done in https://github.com/DataDog/dd-trace-py/pull/9741

chore(ci): use python 3.12 for parametric tests (#9775) [backport 2.8]

---

.github/workflows/system-tests.yml

Manual backport of #9775 for 2.7
As it was done in https://github.com/DataDog/dd-trace-py/pull/9741

chore(ci): use python 3.12 for parametric tests (#9775) [backport 2.7]

---

ddtrace/appsec/_iast/_ast/ast_patching.py

Adds the `moto` package to the IAST patching denylist. It's a AWS-mocking package so propagation is not needed, and it's problematic.

chore: add moto to IAST denylist

---

.github/workflows/system-tests.yml

Backport for https://github.com/DataDog/dd-trace-py/pull/9741
Per title
(cherry picked from commit 2022a3bf338c3a90d3dfd179e504c3904e8228c9)

ci: switch system-tests to python 3.12 [backport 2.8]

---

.github/workflows/system-tests.yml

Backport for https://github.com/DataDog/dd-trace-py/pull/9741
Per title
(cherry picked from commit 2022a3bf338c3a90d3dfd179e504c3904e8228c9)

ci: switch system-tests to python 3.12 [backport 2.9]

---

.gitlab-ci.yml
.gitlab/build-lib-init.sh

Manual backport created for https://github.com/DataDog/dd-trace-py/pull/9332
(cherry picked from commit c8ac79cbb531249d3852afec2f83765241892562)

chore(lib-injection): publish additional docker tags for lib injection image [backport 2.9]

---

ddtrace/appsec/_iast/_ast/ast_patching.py
releasenotes/notes/asm-boto-denylist-9ea0dee3a33fff7c.yaml

Adds the `moto` package to the IAST patching denylist. It's a AWS-mocking package so propagation is not needed, and it's problematic. Also add other packages from `main`.

chore: add moto to IAST denylist [backport 2.10]

---

.gitlab/build-oci.sh

Manual backport for https://github.com/DataDog/dd-trace-py/pull/8932
Need this to be backported to 2.9 in order to fully enable https://github.com/DataDog/dd-trace-py/pull/9790 (which has already been backported). This is currently erroring out (see example [here](https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-py/-/jobs/569985194)) …

chore(ci): add OCI packaging [backport 2.9]

---

.circleci/config.templ.yml

The coverage job was not omitting the directories specified as intended, which was skewing the coverage report to be significantly lower (see [here](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/65442/workflows/574d568f-90d3-41f8-9c8f-8fb70f24d397/jobs/4033899) for example).
Making this syntax fix so that the omission works as intended. Reproduced original behavior locally, and tested the solution locally. …

chore(ci): added quotes to fix the `--omit` flag for coverage report

---

ddtrace/llmobs/_constants.py
ddtrace/llmobs/_integrations/bedrock.py
ddtrace/llmobs/_integrations/openai.py
tests/contrib/botocore/test_bedrock.py
tests/contrib/openai/test_openai_v0.py
tests/contrib/openai/test_openai_v1.py
tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_chat_completion_event.yaml
tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_completion_bad_api_key.yaml
tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_completion_event.yaml
tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_multiple_events.yaml
tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_timed_events.yaml
tests/llmobs/test_llmobs_decorators.py
tests/llmobs/test_llmobs_service.py
tests/llmobs/test_llmobs_span_writer.py

Manual backport for https://github.com/DataDog/dd-trace-py/pull/9657
Backport allows us to remove logic in the backend which parses both (prompt/completion_tokens) and (input/output_tokens) keys
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backportin …

chore(llmobs): backport token metric key name changes to 2.9

---

.readthedocs.yml

[Our readthedocs build is failing currently due to not having Rust installed](https://app.readthedocs.org/projects/ddtrace/builds/24988009/). This change should fix this, so our docs can be updated.
Currently, the readthedocs builds haven't happened in 2 months (2.8.1). We need at least 2.9.2 to be published. …

chore(docs): install rust for .readthedocs.yml
