DataDog/dd-trace-py

ddtrace/llmobs/_constants.py, ddtrace/llmobs/_integrations/anthropic.py, ddtrace/llmobs/_integrations/bedrock.py, ddtrace/llmobs/_integrations/openai.py, tests/contrib/anthropic/test_anthropic_llmobs.py, tests/contrib/botocore/test_bedrock_llmobs.py, tests/contrib/openai/test_openai_llmobs.py, tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_chat_completion_event.yaml, tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_completion_bad_api_key.yaml, tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_completion_event.yaml, tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_multiple_events.yaml, tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_timed_events.yaml, tests/llmobs/test_llmobs_decorators.py, tests/llmobs/test_llmobs_service.py, tests/llmobs/test_llmobs_span_writer.py
Manual backport for https://github.com/DataDog/dd-trace-py/pull/9657 to 2.10
Backport allows us to remove logic in the backend which parses both (prompt/completion_tokens) and (input/output_tokens) keys
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#ba …
=> chore(llmobs): backport token metric key name changes to 2.10

.github/CODEOWNERS
CODEOWNERS file was missing `tests/contrib/botocore/test_bedrock_llmobs.py` for `@DataDog/ml-observability`, which made apm-core-python a required reviewer for that file. This is specific to the LLMObs team, so no core review should be required.
=> chore: added missing tests/contrib/botocore/test_bedrock_llmobs.py

mypy.ini
This reverts commit 15355d7df49a0d97244b3700ee6d7ea12d798370. …
=> ci: revert mypy lint against the oldest supported py version (#9684)

.github/workflows/codeowners.yml
The current implementation doesn't take into account multiline strings which need to be handled with heredoc strings.
I have decided to roll forward a fix rather than revert and then fix since this job is not required and will not be blocking any PRs. …
=> fix(ci): fix incorrect format for multi-line github action codeowners comment

.github/CODEOWNERS
`.github/**`, `.gitlab/**`, and `.circleci/**` should be approvable by the Python guild members, not just core. …
=> chore: update guild code ownership

tests/appsec/iast_packages/test_packages.py
IAST: Set as `xfail` instead of `fail` a known package that is successfully propagating sometimes (not always) when it was usually not propagating at all.
- All changes …
=> ci(iast): change logic for fixme_propagation_fails

tests/.suitespec.json
We've run into multiple instances where changes that should have triggered the `internal` test suite have not. In order to prevent future false negatives, we're adding the entire `ddtrace/internal/**` directory to the internal test suitespec.
The goal is to remove false positives as we encounter them, rather than doing one-offs of adding back false negatives as we encounter them.
- The change follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.h …
=> chore: added entire `ddtrace/internal/*` to internal test suite

tests/appsec/iast/fixtures/propagation_path.py, tests/appsec/iast_memcheck/test_iast_mem_check.py
One of the memleak tests compared the count of number of elements in the `tx_map`. The problem was that the test generated one temporal string with an operator add that got added to the map and then deallocated, whose address could or could not be reused later thus making the size if the `tx_map` "flaky" between tests. This changes the test so the string is assigned a name and thus not deallocated. …
=> chore: fix memtest taint count test

tests/appsec/iast_packages/test_packages.py
Fixes CI tests that only run on main: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/65973/workflows/49c8b4e7-651a-4486-9ab9-5a5aabc02e7e/jobs/4060571/tests#failed-test-0
- …
=> ci: fix by unsetting `test_import` to `google-auth` package

.github/CODEOWNERS
Currently suitespec files are only approvable by core. This should be updated to be core OR guild.
- Avoids …
=> chore: update CODEOWNERS for suitespec files

tests/.suitespec.json, tests/telemetry/test_telemetry.py
https://github.com/DataDog/dd-trace-py/pull/9857 removed the usage of `attr` which removed the `__str__` and `__repr__` from trace processor. This means the assertions in the telemetry tests started to fail.
The telemetry tests were not run on tracing changes, which is why it wasn't found in the original PR. …
=> fix(ci): fix failing telemetry test_app_started_error_handled_exception

tests/internal/test_packages.py
Backport https://github.com/DataDog/dd-trace-py/commit/d4b8e9dfcc8e90e20b51b2e89b0e0495e356713c from https://github.com/DataDog/dd-trace-py/pull/9871 to 2.9.
Currently we have some internal test failures like [this](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/66174/workflows/c90a65a7-ba6a-4fa2-b834-73c5bfe51d80/jobs/4070901) on importlib-resources due to naming discrepancies. Seems like they started happening on main after https://github.com/DataDog/dd-trace-py/pull/9866 was merged into main. This should fix these failures.
- The PR description notes risks associated with the …
=> fix(ci): add workaround for `importlib-resources` name discrepancies [backport 2.9]

.github/CODEOWNERS
These two .md files should be approvable by anyone in apm-python, not just core. …
=> chore: add `CODEOWNERS.md` and `README.md` to apm-python team

.github/CODEOWNERS
The `benchmarks/appsec*` directories should only require ASM approval, not blocked on core. …
=> chore: add `benchmarks/appsec*` for ASM approval

setup.py, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
update libddwaf to [1.19.0](https://github.com/DataDog/libddwaf/releases/tag/1.19.0)
_no further changes in the tracer are required as this update does not contain any breaking changes._
Backporting to 2.10 to able the backend to test the new waf features while deploying 2.10rc on staging
- Backport …
=> chore(asm): update libddwaf to 1.19.0

.github/CODEOWNERS, .github/workflows/unit_tests.yml, ddtrace/internal/_file_queue.py, ddtrace/settings/config.py, hatch.toml, tests/.suitespec.json, tests/internal/service_name/test_extra_services_names.py
…of multiprocessing (#9701)
To prevent further problems with multiprocessing in config:
- remove multiprocessing queue from main config file
- add a new File_Queue using low level locking to write into temporary file
- Use the new queue to exchange messages between multiple processes for extra service names
- update tests
- added a new unit-tests workflow on github to launch any tests on linux(x86), macos(arm64) and windows(x86). (For now, only the test relevant to that PR is used).
This is an alternative solution to
https://github.com/DataDog/dd-trace-py/pull/9626 ensuring that we still report extra service names.
[APPSEC-53927]
[APPSEC-53927]:
https://datadoghq.atlassian.net/browse/APPSEC-53927?atlOrigin=eyJp …
=> chore(tracer): use simple queue file for extra service names instead of multiprocessing [backport 2.10]

ddtrace/appsec/rules.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
Update the static security rule file used for asm to last version.
https://github.com/DataDog/appsec-event-rules/releases/tag/1.13.0
APPSEC-54212 …
=> chore(asm): update security rules to 1.13.0

.gitlab/benchmarks.yml, src/core/Cargo.toml
https://doc.rust-lang.org/nightly/cargo/reference/config.html#netgit-fetch-with-cli
The built-in git client used by Cargo does not support all of the same Git authentication configuration as the git binary. This setting ensures the system git binary is used instead of the built-in client, ensuring that any/all custom git configuration is used.
This means we require `git` to be installed to build from source, but this should already be the case. …
=> fix(internal): set net.git-fetch-with-cli=true for core rust extension

ddtrace/appsec/_common_module_patches.py, ddtrace/appsec/_constants.py, ddtrace/appsec/_processor.py, ddtrace/bootstrap/sitecustomize.py, releasenotes/notes/rasp_conditional_call-f700a122b82b4c4f.yaml, tests/appsec/appsec/rules-rasp-disabled.json, tests/appsec/contrib_appsec/utils.py, tests/appsec/rules.py
Unless explicitly disabled by an environment variable, the WAF is used for each supported exploit prevention endpoint. This PR enhances this behaviour by leveraging the WAF's "known addresses" feature, which, as of version 1.19.0, skips disabled rules, to prevent calling the WAF if unnecessary. 
Now, calls to the WAF will only occur if at least one specific rule for that endpoint has been enabled via remote configuration.
Also:
- add new Shell Injection address in the address list in appsec constants and corresponding property in appsec span processor
- add regression tests in the hatch threat test for exploit prevention to check that no call and no telemetry is generated for disabled rules
APPSEC-54272 …
=> chore(asm):  improve rasp call mechanism

ddtrace/appsec/_remoteconfiguration.py, ddtrace/internal/remoteconfig/_publishers.py, ddtrace/internal/remoteconfig/client.py, releasenotes/notes/rc_asm_features_fix-56fb35d0ca6c5d69.yaml, tests/appsec/appsec/test_remoteconfiguration.py, tests/internal/remoteconfig/test_remoteconfig_client_e2e.py
Backport to 2.9 of https://github.com/DataDog/dd-trace-py/pull/9874
This PR fixes a small problem in the Remote Config layer for ASM_FEATURES product.
After that PR:
On the worker side:
1. if we receive a key in the rc configuration and the value is non empty, it means the value was changed
2. if we receive a key in the rc configuration and the value is empty, it means the value was deleted
3. if we don't receive a key in the rc configuration, it means the value was unchanged.
Previously, if the value was a list, it was already the case, but if the value was a dictionary, case 2 and 3 were not correctly separated. Now, an empty dictionary is sent if the key is deleted (case 2).
Also:
- small refactor
- update unit tests appropriately
- increase coverage on ASM_FEATURES unit tests for one …
=> fix(asm): one click remote config fix (#9874) [backport 2.9]

ddtrace/appsec/_remoteconfiguration.py, ddtrace/internal/remoteconfig/_publishers.py, ddtrace/internal/remoteconfig/client.py, releasenotes/notes/rc_asm_features_fix-56fb35d0ca6c5d69.yaml, tests/appsec/appsec/test_remoteconfiguration.py, tests/internal/remoteconfig/test_remoteconfig_client_e2e.py
Backport to 2.10 of https://github.com/DataDog/dd-trace-py/pull/9874
This PR fixes a small problem in the Remote Config layer for ASM_FEATURES product.
After that PR:
On the worker side:
1. if we receive a key in the rc configuration and the value is non empty, it means the value was changed
2. if we receive a key in the rc configuration and the value is empty, it means the value was deleted
3. if we don't receive a key in the rc configuration, it means the value was unchanged.
Previously, if the value was a list, it was already the case, but if the value was a dictionary, case 2 and 3 were not correctly separated. Now, an empty dictionary is sent if the key is deleted (case 2).
APPSEC-54105
Also:
- small refactor
- update unit tests appropriately
- increase coverage on ASM_FEATURES unit …
=> fix(asm): one click remote config fix (#9874) [backport 2.10]

CHANGELOG.md
We made a small change to the release note for 2.9.4. Matching the CHANGELOG to reflect this.
- Avoids …
=> chore: update 2.9.4 CHANGELOG to match GitHub release note

scripts/release.py
This change adds to the release script the ability to promote a release candidate to a stable minor release. This ability is important to ensure that the content of a minor release is exactly what underwent testing as a release candidate.
The mechanism used to accomplish this is making the `BASE` environment parameter to the script work as either a branch name (current behavior) or a tag name. A few adjustments to release-note gathering and branch resolution are made to support this. The way to promote a release candidate to a minor release is simply to specify `BASE=x.x.0rcx` when invoking this script.
This branch was used to generate this release https://github.com/DataDog/dd-trace-py/releases/tag/untagged-9f4f7354e2642b01030e, which exactly matches 2.10.0rc4 in code content.
- The PR …
=> chore(release-script): add ability to promote release candidates

ddtrace/internal/writer/writer.py, ddtrace/llmobs/_constants.py, ddtrace/llmobs/_llmobs.py, ddtrace/llmobs/_writer.py, releasenotes/notes/feat-llmobs-span-writer-via-agent-evp-proxy-d8ea55491a1db2be.yaml, tests/contrib/anthropic/conftest.py, tests/contrib/botocore/test_bedrock.py, tests/contrib/botocore/test_bedrock_llmobs.py, tests/contrib/langchain/conftest.py, tests/contrib/langchain/test_langchain_llmobs.py, tests/contrib/openai/conftest.py, tests/llmobs/_utils.py, tests/llmobs/conftest.py, tests/llmobs/test_llmobs_service.py, tests/llmobs/test_llmobs_span_agent_writer.py, tests/llmobs/test_llmobs_span_writer.py
Implementation of the `llm_span_agent_writer` that sends llm span via agent endpoint's EvP proxy. 
Context: we want to use existing Agent EvP proxy available in `HTTPWriter` class, so that LLMOBS customers don't need to configure api key & site explicitly.
https://datadoghq.atlassian.net/browse/MLOB-1207
Test:
Unit tests updated.
E2e test, with updated [test script ](https://github.com/DataDog/llm-obs/blob/main/test-scripts/openai/patch_simple_chat_completions_call.py), we can see the payload gets successfully forwarded via agent EvP proxy and shows in Datadog LLMOBS UI. …
=> feat(llmobs): span writer via agent evp proxy

ddtrace/profiling/collector/_lock.py, releasenotes/notes/profiling-add-lock-with-f75908e35a70ab71.yaml, tests/profiling/collector/test_threading.py
Manual backport https://github.com/DataDog/dd-trace-py/commit/3cf37988ab677c1f0ad903aa9edfae42809b15fa from https://github.com/DataDog/dd-trace-py/pull/9610 to 2.9.
Python profiler doesn't capture lock usages with `with lock:` statement even though this seems to be more common usage pattern.
GitHub search with `/with.*lock:/ language:Python -path:test` shows [228k code results](https://github.com/search?q=%2Fwith.*lock%3A%2F+language%3APython+-path%3Atest&type=code) 
GitHub search with `/.*lock.acquire\(\)/ language:Python -path:test` shows [89.1k code results](https://github.com/search?q=%2F.*lock.acquire%5C%28%5C%29%2F+language%3APython+-path%3Atest&type=code)
We'll get more lock related samples in profiles with this change.
policy](https://ddtrace.readthedocs.io/en/latest/contributing.h …
=> fix(profiling): capture lock usages with `with` statement context manager [backport 2.9]

ddtrace/profiling/collector/_lock.py, releasenotes/notes/profiling-add-lock-with-f75908e35a70ab71.yaml, tests/profiling/collector/test_threading.py
Manual backport https://github.com/DataDog/dd-trace-py/commit/3cf37988ab677c1f0ad903aa9edfae42809b15fa from https://github.com/DataDog/dd-trace-py/pull/9610 to 2.8.
Python profiler doesn't capture lock usages with `with lock:` statement even though this seems to be more common usage pattern.
GitHub search with `/with.*lock:/ language:Python -path:test` shows [228k code results](https://github.com/search?q=%2Fwith.*lock%3A%2F+language%3APython+-path%3Atest&type=code) 
GitHub search with `/.*lock.acquire\(\)/ language:Python -path:test` shows [89.1k code results](https://github.com/search?q=%2F.*lock.acquire%5C%28%5C%29%2F+language%3APython+-path%3Atest&type=code)
We'll get more lock related samples in profiles with this change.
policy](https://ddtrace.readthedocs.io/en/latest/contributing.h …
=> fix(profiling): capture lock usages with `with` statement context managers [backport 2.8]

ddtrace/profiling/collector/_lock.py, releasenotes/notes/profiling-add-lock-with-f75908e35a70ab71.yaml, tests/profiling/collector/test_threading.py
Manual backport https://github.com/DataDog/dd-trace-py/commit/3cf37988ab677c1f0ad903aa9edfae42809b15fa from https://github.com/DataDog/dd-trace-py/pull/9610 to 2.7.
Python profiler doesn't capture lock usages with `with lock:` statement even though this seems to be more common usage pattern.
GitHub search with `/with.*lock:/ language:Python -path:test` shows [228k code
results](https://github.com/search?q=%2Fwith.*lock%3A%2F+language%3APython+-path%3Atest&type=code) GitHub search with `/.*lock.acquire\(\)/ language:Python -path:test` shows [89.1k code results
](https://github.com/search?q=%2F.*lock.acquire%5C%28%5C%29%2F+language%3APython+-path%3Atest&type=code)
We'll get more lock related samples in profiles with this change.
policy](https://ddtrace.readthedocs.io/en/latest/contributing.h …
=> fix(profiling): capture lock usages with `with` statement context managers [backport 2.7]

lib-injection/Dockerfile, releasenotes/notes/fix-lib-injection-docker-image-size-ae171009a786f185.yaml
The main issue was the `RUN chown`/`RUN chmod` commands which were duplicating the package files in their own layers. This caused the final image to be about 3x the actual size it should have been.
Current v2.10.1 image
```
❯ docker history datadog/dd-lib-python-init:v2.10.1
IMAGE          CREATED      CREATED BY                                      SIZE      COMMENT
90c84773b524   2 days ago   ADD copy-lib.sh /datadog-init/copy-lib.sh # …   12.3kB    buildkit.dockerfile.v0
<missing>      2 days ago   ADD sitecustomize.py /datadog-init/sitecusto…   20.5kB    buildkit.dockerfile.v0
<missing>      2 days ago   ADD min_compatible_versions.csv /datadog-ini…   12.3kB    buildkit.dockerfile.v0
<missing>      2 days ago   WORKDIR /datadog-init                           4.1kB …
```
=> fix(lib-injection): fix lib-injection docker image size

docs/advanced_usage.rst
Fix docstrings [here](https://ddtrace.readthedocs.io/en/stable/advanced_usage.html#ddtrace-run:~:text=ddtrace%2Drun%20%3Cmy_program%3E-,%E2%80%93info%3A,-This%20argument%20prints), the `--info` arg hyphens were being combined into one large hyphen, which is the wrong symbol. Use double backticks to prevent this.  …
=> docs(advanced_usage): clarify ddtrace-run info command

ddtrace/contrib/pytest/_plugin_v1.py, ddtrace/ext/git.py, ddtrace/internal/ci_visibility/recorder.py, releasenotes/notes/ci_visibility-fix-dont_make_pytest_contrib_depend_on_git-d922e9326c981f38.yaml, tests/contrib/pytest/test_pytest.py
Backport c460441c0c43d40b5d12e647ce60086b2f8f493f from #9989 to 2.9.
Fixes an issue introduced by #9586 and reported in #9981 where the pytest plugin would crash if the `git` binary was absent.
The workspace is instead grabbed from the `CIVisibility` service's tags (via a new getter classmethod).
In order for the variable to persist through to the `pytest_terminal_summary` hook, it is moved from being stashed on the pytest `session` object to the nested `config` object (which itself is passed to `pytest_terminal_summary`).
For improved testability, a function to get the location of the `git` binary's passed, using `@cached()` to avoid re-fetching the path each time we call `git`.
- The PR description articulates the motivation for …
=> fix(ci_visibility): don't rely on git in pytest plugin [backport 2.9]

ddtrace/appsec/_processor.py, ddtrace/appsec/_remoteconfiguration.py, releasenotes/notes/fix_rc_asm_dd_no_file-37e6f733583e334c.yaml, tests/appsec/appsec/test_processor.py, tests/appsec/appsec/test_remoteconfiguration.py
backporting https://github.com/DataDog/dd-trace-py/pull/10030
APPSEC-54105
(cherry picked from commit bc50e9cd69c4a21a101e11bf250a7904dc6b6937)
- All changes are related …
=> fix(asm): switch back to default if remote config stop sending the security rule file [backport 2.10]

tests/appsec/appsec/test_remoteconfiguration.py
Add a little more coverage on https://github.com/DataDog/dd-trace-py/pull/10030 to ensure that the rule structure is not modified by new features. …
=> chore(asm): add test for immutability of static rules in appsec processor

ddtrace/internal/telemetry/writer.py, releasenotes/notes/ci_visibility-fix-update_eu_telemetry_url-0642a6f665c75a0f.yaml, tests/telemetry/test_writer.py
Backport 513f7e56b783f0b700b8baba9d5d76c6f57874b9 from #10021 to 2.9.
This PR fixes incorrect URL for telemetry intake in EU that was causing missing telemetry data and SSL error log messages.
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting) …
=> fix(internal): fix telemetry URL for EU [backport 2.9]

ddtrace/internal/telemetry/writer.py, releasenotes/notes/ci_visibility-fix-update_eu_telemetry_url-0642a6f665c75a0f.yaml, tests/telemetry/test_writer.py
Backport 513f7e56b783f0b700b8baba9d5d76c6f57874b9 from #10021 to 2.10.
This PR fixes incorrect URL for telemetry intake in EU that was causing missing telemetry data and SSL error log messages.
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting …
=> fix(internal): fix telemetry URL for EU [backport 2.10]

tests/appsec/iast_packages/test_packages.py
`setuptools` was recently removed as a dependency but the `cffi` package requires it for the IAST package testing. This PR adds it only for that test' virtual environment as an extra dependency.
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backportin …
=> chore: add setuptools for the cffi package test

ddtrace/internal/packages.py
Current implementation uses the default size of the `cached` decorator which is 256. This is often (always?) lower than the number of files of a Python program loaded in memory creating cache churn. This is problematic for functions like `filename_to_package` since it performs an expensive operation by calling `_root_module` that walks the filesystem.
Simple benchmark show a 7800% improvement on cache acces for `filename_to_package` function:
Current implementation:
```python
def fill_cache(i=10000):
for j in range(i):
filename_to_package(f"/home/benjamin/workspace/dd-trace-py/lib/python3.10/site-packages/ddtrace/internal/test{j}.py")
timeit.timeit("fill_cache(257)", setup="from __main__ import fill_cache", number=10000)
```
```
115.0306228880072
```
With patch:
```python
def …
```
=> chore(internal): update cache max size to for module/package/file

ddtrace/profiling/collector/_lock.py, ddtrace/settings/profiling.py, riotfile.py
Manual backport of #9689 to 2.10
(cherry picked from commit 076772500ef5f67deafcd4efef0df1f969380693)
=> fix(profiling): add debug asserts for our stack assumptions (#9689) [backport-2.10]

ddtrace/profiling/collector/_lock.py, releasenotes/notes/profiling-timeline-lock-init-loc-and-frames-39a43f924bde88d2.yaml, tests/profiling/collector/test_asyncio.py, tests/profiling/collector/test_threading.py, tests/profiling/collector/test_threading_asyncio.py, tests/profiling/simple_program_fork.py
Manual backport of #9692 to 2.10
- Lock Name shows the line number of where `acquire/release/__enter__/__exit__` was called, which is duplicated in the Call Stack
- Call Stack shows a frame for Profiler internal function, [\_\_enter\_\_](https://github.com/DataDog/dd-trace-py/blob/42ccea9b13e232bcce4a1d20b9d11eda7904226d/ddtrace/profiling/collector/_lock.py#L235)
- Lock Name shows the line number where the lock was initialized.
- Call Stack shows user codes only.
This actually reverts some of the changes I made in https://github.com/DataDog/dd-trace-py/pull/9615, but I believe this PR makes everything clearer.
(cherry picked from commit 97969ee7d3870854e6638574397e386586783b0a)
=> fix(profiling): show lock init location and hide internal frame (#9692) [backport-2.10]

ddtrace/appsec/_common_module_patches.py, tests/appsec/appsec/test_exploit_prevention.py
This PR allows to appsec common_module_patches mechanism to wrap a different wrapper.
This fix a discrepancy that could prevent exploit prevention for command injection to work.
(not released yet, so no release note).
APPSEC-54439
(cherry picked from commit 14f33c2e8c51b7f985a790ecce86a463ef22077a)
- …
=> chore(asm): improve patching mechanism (#10098) [backport 2.11]

ddtrace/profiling/exporter/http.py
The PR changes the code provenance content type from `application/json` to `application/octet-stream` as the underlying code provenance data is binary. Also the change makes the content type consistent with DataDog profiler for other languages like Ruby (refer [here](https://github.com/DataDog/dd-trace-rb/issues/3767#issuecomment-2217325350)) …
=> fix(profiling): use octet-stream as code provenance content type

ddtrace/internal/datadog/profiling/dd_wrapper/include/uploader.hpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp
`Uploader::runtime_id` has never been updated and we set it correctly via https://github.com/DataDog/dd-trace-py/pull/9987/files#diff-ce7731c2f99d39b0496ece12ed6e487c0d400ecf0204d17b381f31746d9d9936
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backpo …
=> chore(profiling): remove unnecessary add_tag for runtime_id

ddtrace/internal/datadog/profiling/dd_wrapper/src/crashtracker.cpp
Similar to https://github.com/DataDog/dd-trace-py/pull/9987/files …
=> chore(profiling): set runtime_id for crashtracker

.github/workflows/build_python_3.yml
Previously we were setting the env var `CMAKE_BUILD_PARALLEL_LEVEL`, but it wasn't being passed into the containers used by cibuildwheel, so we were seeing no benefits.
This PR only updates the env var for linux since updating for macos and windows didn't seem to work, I need to investigate further, but I figured this is a good incremental change.
The benefit is linux builds that complete in around/under 4 minutes. It doesn't make a big change to the overall runtime of the whole build (until we can get windows/macos faster), but it does drop the "billable minutes" by 20-30 minutes (good show of the impact of the change).
We had parallel of 12 before, 24 wasn't that much faster, but we can just saturate the CPUs. …
=> chore(ci): properly set CMAKE_BUILD_PARALLEL_LEVEL for cibuildwheel

.gitlab/build-oci.sh, releasenotes/notes/fix-ssi-permissions-647693af3d5ce49d.yaml
=> fix(SSI): set the right permissions (backport #10141 to 2.9)

tests/tracer/test_writer.py
With this [change](https://github.com/DataDog/dd-trace-py/commit/a7e765f07481971e148e6c41faa7cba3a910eac4) the CIVisibilityWriter no longer encodes empty payloads and therefore does not raise an OSError in test_flush_queue_raise.
This PR ensures writer.write() is called with a non-empty list of spans.
Sample Failure: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/68186/workflows/1c3c051b-5a86-4744-9f9e-656fe45861fd/jobs/4168676 …
=> ci(tracer): fix test_flush_queue_raise

tests/appsec/contrib_appsec/conftest.py
To avoid flakyness in threat tests, increase waf timeout even more. …
=> chore(asnm): less flakyness in threat tests

ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.cpp, releasenotes/notes/iast-new-pyobject-check-6aecf9c4f22e2ae9.yaml
=> fix: add nullptr checks for new_pyobject_id [backport 2.9]

tests/.suitespec.json
The tracer test suite tests `CIVisibilityWriter`, and therefore changes to ci_visibility must cause tracer tests to run. This avoids issues like https://github.com/DataDog/dd-trace-py/pull/10150 where a change in ci_visibility breaks a tracer test but does not cause the tests to be run. …
=> ci(tracer): make tracer suite depend on ci_visibility

ddtrace/appsec/_common_module_patches.py, ddtrace/internal/_unpatched.py
To avoid any potential issues we should avoid importing critical modules in post-preload hooks.
This PR moves import of gc from asm hooks to intial _unpatched module.
- …
=> chore(asm): import gc in unpatched

ddtrace/internal/packages.py
This change removes some code that is only active under Python 2, which the library no longer supports.
- …
=> chore: remove py2.7 compatibility code

tests/tracer/runtime/test_runtime_metrics.py
This change skips a test that [fails occasionally](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/68392/workflows/89aa0b8b-ab98-4d82-9921-3c1c22e6c04c/jobs/4181400) on main.
- …
=> ci: mark flaky test

ddtrace/internal/datadog/profiling/ddup/__init__.py, ddtrace/internal/datadog/profiling/stack_v2/__init__.py, ddtrace/profiling/collector/stack.pyx, ddtrace/profiling/profiler.py, ddtrace/settings/profiling.py
Manual backport of #9719 to 2.10
Crashtracker was not backported to 2.10 and this PR is #9719 without crashtracker edits. 
The profiler bundles some native components which are not available on all platforms. The pattern we were using for detecting and handling this case was needlessly fiddly and incomplete.
This patch refactors some aspects of this.
(cherry picked from commit 20579134bf261f40c2632af05208ea95eab43690)
=> chore(profiling): improve native module loading [backport-2.10]

.circleci/config.templ.yml
https://support.circleci.com/hc/en-us/articles/360007188574-Build-has-Hit-Timeout-Limit
Sometimes the `tracer` job runs for a really long time and doesn't time out until after 30+m (sometimes hours?!).
Trying out this setting to see if we can prevent that from happening and get it to fail faster.
- …
=> chore(ci): set 5m no output timeout for riot run steps

ddtrace/internal/datadog/profiling/ddup/_ddup.pyx, releasenotes/notes/profiling-fix-endpoint-v2-a6ca2ebbc9701fe5.yaml
Stack v1 implementation
https://github.com/DataDog/dd-trace-py/blob/9029186edf9d21e3ff375eb694e60d47f92c0f96/ddtrace/profiling/event.py#L107-L108
Wrong stack v2 implementation
https://github.com/DataDog/dd-trace-py/blob/f42fb50fcef8ef4dd00c168551a5e3b624c25878/ddtrace/internal/datadog/profiling/ddup/_ddup.pyx#L286-L287
Found this while working on #10230. Submitting this as a separate PR to merge and backport this ASAP.  …
=> fix(profiling): fix endpoint profiling for stack v2

.gitlab-ci.yml, .gitlab/benchmarks.yml
The microbenchmarking setup was really repetitive and could easily be refactored to use a matrix instead of individual jobs.
This refactor also gives us the benefit of collapsing all benchmark runs under a single "microbenchmark" item in the UI so it takes up less real estate. It also allows us to get rid of the benchmark pr comment specific stage and instead make it just depend on the single "microbenchmarks" job.
We also trigger the serverless benchmarks immediately instead of waiting on prior stages completion first.
- …
=> chore(ci): refactor gitlab benchmarks stage

scripts/check-releasenotes
PR https://github.com/DataDog/dd-trace-py/pull/10112 was merged, backported, and released without a release note. This causes confusion when the changelog/release notes do not reflect what is include in the release.
This PR updates the release note CI check to explicitly fail if the PR title starts with `fix` and includes the `changelog/no-changelog` label.
- The change …
=> chore(ci): ensure 'fix' PRs include a release note

.gitignore
Manual backport generation instructions use .worktrees as temporary worktree locations.
Adding `.worktrees/` to `.gitignore` makes it easier to work and keep things clean (eg: `git status` won't show the directory and it won't be possible to accidentally commit things from the worktree).
This does not prevent commits to the worktree itself. …
=> chore: add .worktrees directory to .gitignore

ddtrace/internal/module.py, releasenotes/notes/fix-module-callback-type-error-ba5583fa8e2cf0fc.yaml
We add handling of native module specs in the chained loader to prevent `TypeError` exceptions being thrown when the original loader and spec are being set when calling back on module import.
Addresses #10285.
The issue was caught in yum-based Linux OS distributions. We will look into adding a regression test for this scenario later. …
=> fix(internal): handle native module specs

releasenotes/notes/fix-wheel-file-permissions-59b497ed8163e885.yaml, scripts/zip_filter.py
The problem is the script we used to strip unwanted files from the resulting wheels on linux were not maintaining the original file attributes.
This hasn't been a problem before before files just needed read permissions only. However with the introduction of the crashtracker which brings with it an executable, the executable attribute was being stripped from the file.
We never caught this because we do not have any smoke or integration tests on the wheels we generate which validate crashtracking behavior (or the stderr logs).
- …
=> fix: fix ddtrace file attributes being stripped when repairing linux wheels

ddtrace/internal/remoteconfig/worker.py
We allow products being registered with remote config to specify whether they need to be automatically restarted on fork. …
=> chore(rc): register restart on fork

.gitlab-ci.yml, .gitlab/download-wheels-from-gh-actions.sh, .gitlab/package.yml
Right now we download all artifacts from the GitHub Actions build job, but we don't save them to as GitLab artifact. This change ensures we include all artifacts.
What we are missing right now is the source distribution. …
=> ci: download all GitHub Actions artifacts

ddtrace/debugging/_debugger.py
We guard the debugger inline wrapping operations with exception blocks to prevent causing an exception in the wrapped function which would result in altered behaviour.
- …
=> chore(debugger): guard inline wrapping operations

ddtrace/debugging/_probe/remoteconfig.py
We make sure that the default capture limits are used for log probes when none are specified in the probe configuration. …
=> chore(debugger): ensure default limits are used when not set

ddtrace/debugging/_signal/metric_sample.py, ddtrace/debugging/_signal/model.py, ddtrace/debugging/_signal/snapshot.py, ddtrace/debugging/_signal/tracing.py, tests/debugging/signal/test_model.py
We make sure that local and global variables are available to expression evaluations on function probe exit.
- …
=> chore(debugger): include locals/globals in evals

ddtrace/internal/module.py, releasenotes/notes/fix-module-callback-no-side-effects-df422ae52b87772d.yaml, tests/internal/side_effect_module.py, tests/internal/test_module.py
We make sure that we avoid side-effects when looking up methods from module objects, as these could be of arbitrary type and have custom attribute lookups implemented.
Addresses #10314.
We try to replicate the side-effect caused by attribute lookup of the custom module object in `yt-dlp`, and use that as a base for a regression test. …
=> fix: prevent module import callback side-effects

ddtrace/appsec/_constants.py, ddtrace/appsec/_iast/_ast/visitor.py, ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp, ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.h, ddtrace/appsec/_iast/_taint_tracking/__init__.py, ddtrace/appsec/_iast/_taint_tracking/aspects.py, tests/appsec/app.py, tests/appsec/iast/aspects/test_re_aspects.py, tests/appsec/iast/fixtures/non_re_module.py, tests/appsec/integrations/test_flask_iast_patching.py
IAST: Aspects for `re.match()` and `re.Match.groups()`
Note: this change involves allowing to taint `re.Match` objects and not only `text objects` as before.
- All …
=> chore(iast): `re.match` and `re.Match.groups` aspects

ddtrace/internal/periodic.py, tests/internal/test_periodic.py
It is likely that a periodic service wanting to restart after fork needs some clean-up logic to be triggered before the periodic worker process is spawned. We extend the API with a reset method that needs to be implemented in order to define such logic when needed. …
=> chore: reset logic for forksafe periodic service

ddtrace/contrib/openai/patch.py, releasenotes/notes/openai-async-timeout-errors-f9ccc1adbe4ed14e.yaml, tests/contrib/openai/test_openai_v1.py
Backport 16cdd6aac0ab77a5e6caac1a7c7417d2e58eb12f from #10265 to 2.11.
Fixes #10191 
In the case of an `asyncio` future cancellation, we want to propagate that error up appropriately. What this looks like is the `response` from the OpenAI function being `None`, which does not conform to the typing from the OpenAI SDK (see original issue). If the result is ever `None`, we don't pass that result to our shared generator to handle OpenAI responses, and instead let the error bubble up.
- The …
=> fix(openai): propagate asyncio.TimeoutErrors correctly when openai operation canceled [backport 2.11] 

ddtrace/contrib/openai/patch.py, releasenotes/notes/openai-async-timeout-errors-f9ccc1adbe4ed14e.yaml, tests/contrib/openai/test_openai_v1.py
Backport 16cdd6aac0ab77a5e6caac1a7c7417d2e58eb12f from #10265 to 2.10.
Fixes #10191 
In the case of an `asyncio` future cancellation, we want to propagate that error up appropriately. What this looks like is the `response` from the OpenAI function being `None`, which does not conform to the typing from the OpenAI SDK (see original issue). If the result is ever `None`, we don't pass that result to our shared generator to handle OpenAI responses, and instead let the error bubble up.
- The …
=> fix(openai): propagate asyncio.TimeoutErrors correctly when openai operation canceled [backport 2.10]

.gitlab-ci.yml
Backport of #10305 to 2.11
Right now we download all artifacts from the GitHub Actions build job, but we don't save them to as GitLab artifact. This change ensures we include all artifacts.
strategy
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)) …
=> ci: download all GitHub Actions artifacts (#10305) [backport 2.11]

.gitlab-ci.yml, .gitlab/release.yml
In order to have 1:1 with what we upload to pypi.org we need #10305. It is ok to merge this PR with that one, we will just be missing the sdist.
When building tags test uploading built files to https://test.pypi.org/ …
=> ci: test upload artifacts to test.pypi.org

ddtrace/debugging/_signal/model.py, ddtrace/debugging/_signal/snapshot.py, tests/debugging/test_debugger.py
We improve the logic to retrieve the enriched locals with extra values and globals. There is no need to split between arguments and actual locals, as their union is just the full set of the frame locals.
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#b …
=> chore(di): improve enriched locals

.circleci/config.templ.yml, .gitlab/tests.yml, .gitlab/tests/tracer.yml, ddtrace/internal/runtime/collector.py
This change moves the `tracer` test suite to internal gitlab for billing purposes. …
=> ci: run `tracer` suite in gitlab instead of circleci

.github/workflows/system-tests.yml
CI time goes from 25mn to 19mn
Billable time goes from 3h45 to 3h15
1. Build only once the agent image
* expected time gain : 30s
* expected cost gain : as it was build 5 times, we gain 30s * 4 seconds of CI cost ( actually way more, as the cost part is not building the image, but compress it)
2. use the system-tests action for building runner (optimized to be reused across jobs)
* expected time gain : 50s (10s vs 60s)
* expected cost gain : as it was build 5 times, and as it's now cached across job, the gain is 5 * 60 - 10 * split_scenario = 560 s 
2. (bis) use the system-tests action for building runner for parametric test (optimized to be reused across jobs)
* expected time gain : 50s (10s vs 60s), but as it was in parallel with other scenario
* expected cost gain : 50 s also.
3. use …
=> chore(ci): optimize system-tests

setup.cfg
Some instances of flake8 expect to find their `max-line-length` config in `setup.cfg`. …
=> chore(dev): let more tools know that we use 120 character per line

.github/CODEOWNERS
This PR updates the codeowners file following the `contrib` code move to `contrib/internal` so that team MLObs can continue to be the codeowners for the MLObs integration patch code.
- Title …
=> chore(llmobs): add internal contrib files to MLObs codeownership

.github/workflows/generate-package-versions.yml
This PR adds the following that was missing from the automated version update PRs:
- the `changelog/no-changelog` label
- PR template checklist 
Still TODO: figure out appropriate CODEOWNERs. 
Example run here:
https://github.com/DataDog/dd-trace-py/actions/runs/10563875400/job/29265054055
- Backport …
=> chore: add no-changelog label and checklist to auto-generated PR updates

hatch.toml, scripts/gen_circleci_config.py, tests/meta/test_conftest.py
#10373 modified docker/Dockerfile but didn't trigger conftests circle ci test and merged. After the merge on main, conftests started to fail on main.
1. Fix it by specifying the python version on `hatch.toml`. This actually looks like a bug on hatch and for now setting the version to be 3.10 as circle ci docker image we use for conftests is based on python 3.10, and hatch seems to pick up the version when it's available. If not set, hatch installs 3.12 and results in this weird error, [failing to install ddtrace as it can't find clang compiler. ](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/70063/workflows/21549ae8-682f-4538-bd5a-b1b1077e5043/jobs/4254100)
2. Also updates suitespec generator 
gen_circleci_config.py calls `fnmatch.filter(changed_files, pattern)` to get the …
=> chore: fix broken conftests circle ci

ddtrace/contrib/pytest/_plugin_v2.py, ddtrace/ext/ci_visibility/api.py, ddtrace/internal/ci_visibility/api/ci_base.py, ddtrace/internal/ci_visibility/api/ci_coverage_data.py, ddtrace/internal/ci_visibility/recorder.py, ddtrace/internal/coverage/code.py
This updates the coverage collection mechanism for the new pytest plugin version to only collect dependency coverage once per suite.
`get_coverage_data()` is introduced as an API for `CISuite` and `CITest` items to fetch coverage data from the internal API.
`ModuleCodeCollector` gets a new `get_import_coverage_for_paths()` classmethod that returns coverage for the given paths.
No release note is added since this is still internal/unreleased code. …
=> chore(ci_visibility): pytest: only compute dependency coverage once per suite

ddtrace/internal/ci_visibility/recorder.py, tests/ci_visibility/test_ci_visibility.py
This makes sure that the `content-type` header is properly set when the CI Visibility service uses the EVP proxy method for requests.
This does not, actually, fix anything since the API still responds properly without the header, so no fix release note is added. …
=> chore(ci_visibility): set the content type header when in EVP mode

ddtrace/contrib/pytest/_plugin_v2.py
This primarily addresses warning messages that would be shown if a test was marked as skipped by ITR, but also xfailed.
This would've resulted in a log warning that the test item was already finished, which would result in the tag setting being a noop.
No changelog is added because this plugin is not yet released. …
=> chore(ci_visibility): only store longrepr as XFAIL_REASON if the test is an xfail

.gitlab/dogfood.yml
This job is useful to run, to be able to manually check the results, but given that it fails every time and we ignore the failure in the pipeline, there is no reason to block the entire pipeline waiting for it to finish. …
=> ci: do not block on downstream dogweb job

ddtrace/contrib/dramatiq/patch.py
=> chore: trivial change for test

.github/workflows/build_deploy.yml, .github/workflows/generate-package-versions.yml
Currently, the build pipeline isn't triggered automatically upon an open PR unless we merge or push from main ([example](https://github.com/DataDog/dd-trace-py/pull/10392)).
This update adds the branch prefix `upgrade-latest-` to the 'allowlist' of branches that trigger the build and deploy pipeline, in order to have the auto-generated PRs trigger the appropriate jobs. 
- …
=> chore(ci): update branch for auto-generate package version updates

.gitlab-ci.yml
Right now the default is 1h.
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#i …
=> ci: set testrunner timeout to 20m

ddtrace/internal/flare/flare.py
=> chore: test merge queue

ddtrace/appsec/_ddwaf/ddwaf_types.py
To improve waf bindings efficiency, use byte pointer instead of c_char_p for string retrieval from libddwaf
- …
=> chore(asm): use byte pointer instead of c_char_p

ddtrace/appsec/_ddwaf/ddwaf_types.py
Backport of https://github.com/DataDog/dd-trace-py/pull/10428
(cherry picked from commit 46bb2a83d85cfeb2b2d0301a4d2de1ef9ae3fc20) …
=> chore(asm): use byte pointer instead of c_char_p (#10428)

ddtrace/internal/ci_visibility/recorder.py, ddtrace/internal/codeowners.py
Reverts the `Codeowners.__init__()` behavior introduced in #10094 which changed the exception being caught by the `CIVisibility` service when instantiating `Codeowners()`, resulting in undesirable log messages.
`Codeowners.__init__()` raising a `ValueError` exception, caught by the sole caller (`CIVisibility.__init__()`).
The `of()` behavior is maintained and the caller is updated to check for `[]` as an indication that no codeowner was found.
There is no release note as #10094 was only backported into `2.12`.
As a bonus, type hints are converted from comments to annotations.
- The PR …
=> chore(ci_visibility): don't log exception when codeowners can't be loaded

tests/tracer/test_rate_limiter.py
Previous PR fixed flakiness in one part of this test, but there is a remaining bit which is also flaky.
- …
=> ci: fix flaky tracer tests

.github/workflows/codeowners.yml
The job is currently broken. This should fix it.
The job isn't required so no impact to CI/ability to merge.
- …
=> ci: fix permissions for codeowners actions

ddtrace/internal/ci_visibility/recorder.py, ddtrace/internal/codeowners.py
Backport ca182d060c7ec6d2b15173b9a24658355dc948f0 from #10423 to 2.12. 
Reverts the `Codeowners.__init__()` behavior introduced in #10094 which changed the exception being caught by the `CIVisibility` service when instantiating `Codeowners()`, resulting in undesirable log messages.
`Codeowners.__init__()` raising a `ValueError` exception, caught by the sole caller (`CIVisibility.__init__()`).
The `of()` behavior is maintained and the caller is updated to check for `[]` as an indication that no codeowner was found.
There is no release note as #10094 was only backported into `2.12`.
As a bonus, type hints are converted from comments to annotations.
- The change includes …
=> chore(ci_visibility): don't log exception when codeowners can't be loaded [backport 2.12]

ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
Fix a memleak on the recently introduced `process_flag_added_args` native utlity function.
Leak explanation: 
The new `process_flag_added_args` did a `Py_INCREF` of the returned args. This was correct on isolation, however all the uses of this function called `py::reinterpret_borrow<Typename>` on the returned value, which already internally increases the reference, thus causing a leak. 
Fix: remove the `Py_INCREF` and document the need to potentially do it on the caller if not used with pybind11 stuff.
- Newly-added code is …
=> chore(iast): fix memleak on process_flag_added_args

.circleci/config.templ.yml, .gitlab/tests.yml, .gitlab/tests/appsec.yml, tests/appsec/iast/fixtures/taint_sinks/sql_injection_psycopg2.py, tests/appsec/iast/taint_sinks/test_ssrf.py, tests/appsec/iast_tdd_propagation/test_flask.py
`appsec_iast_tdd_propagation` is currently not being run by CircleCI, and it is failing in GitLab (I suspect it will fail in CircleCI as well). For now I have migrated it to GitLab but marked it as `allow_failure: true` until it is fixed. …
=> ci: move more appsec suites to GitLab

.github/workflows/test_frameworks.yml, ddtrace/appsec/_handlers.py
Fix and enable again starlette tests that were disabled.
Reason of the bug:
- starlette was fixed in 0.38.3 for an issue that was causing trouble in our appsec instrumentation. Tests were upgraded accordingly
Fix: 
https://github.com/encode/starlette/pull/2620
Issue:
https://github.com/encode/starlette/issues/2516
Also improve the guards in the asgi middleware appsec instrumentation for request body to ensure that we never break. …
=> chore(CI): starlette tests

.circleci/config.templ.yml, .gitlab/tests/core.yml
This change moves the `slotscheck` and `conftests` suites from circleci to gitlab for billing purposes.
- …
=> ci: move some misc non-contrib suites to gitlab

ddtrace/internal/coverage/instrumentation_py3_10.py
The line number information in Python 3.10 bytecode is encoded using pairs of (offset_delta, line_number_delta) bytes ([more info here](https://github.com/python/cpython/blob/3.10/Objects/lnotab_notes.txt)). When the line number delta exceeds the limits of a signed byte, this is encoded by using an offset_delta of 0, which was not handled correctly by our instrumentation. This PR fixes that.
This solves an issue where two consecutive opcode instructions with a line gap greater than 127 would be assigned incorrect line numbers, which was triggering an error in dogweb CI.
This PR was tested in two ways:
- Verifying that the error in the dogweb CI is solved by the change.
-  Comparing the output of `dis.dis()` on the bytecode of the offending function in dogweb (1) before instrumentation, …
=> chore(ci_visibility): fix line numbers in Python 3.10 bytecode

ddtrace/internal/ci_visibility/recorder.py, releasenotes/notes/ci-visibility-handle-exception-in-tests-to-skip-675db3b857f8e232.yaml, tests/ci_visibility/test_ci_visibility.py
=> fix(ci_visibility): handle errors while fetching skippable test data

docs/contributing-testing.rst
Replaces https://github.com/DataDog/dd-trace-py/pull/10500 .
Thank you @taegyunkim for reviewing!
In the current docs for running specific tests, it says: 
> Find the directive in the [CI config](https://github.com/DataDog/dd-trace-py/blob/32b88eadc00e05cd0bc2aec587f565cc89f71229/.circleci/config.yml#L664) whose pattern is equal to the suite name. Note the docker_services section of the directive, if present - these are the "suite services".
This is referring to an older version of the repo, and assumes these lines are there:
```
gevent:
<<: *contrib_job
docker:
- image: *ddtrace_dev_image
- *testagent
steps:
- run_test:
pattern: 'gevent'
```
However, if I change the branch to `main`, it no longer looks like this.
Instead, it looks like this logic has been shifted to `config.templ.yml`: …
=> chore(docs): update the contributing testing instructions for specific tests

releasenotes/notes/fingerprinting_stability-cfe856d1e09b6a20.yaml
This PR adds a release note for the improvement PR https://github.com/DataDog/dd-trace-py/pull/10439 that is indeed also a fix for internal stability problems with fingerprinting reports, previously released in 2.11
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contrib …
=> fix(asm): improve fingerprinting stability

.circleci/config.templ.yml, .gitlab/tests/contrib.yml
This reverts commit 9fa8f407d5a48f0dc9ae044b3a782da2b55cb414. …
=> ci: revert "ci: migrate elasticsearch suite to GitLab (#10468)"

ddtrace/profiling/profiler.py, tests/profiling/test_profiler.py
=> chore(profiling): use ddtrace config instead of reading os.environ

ddtrace/llmobs/_llmobs.py, releasenotes/notes/fix-llmobs-fork-custom-filters-5ba642f9395a0ddd.yaml, tests/llmobs/test_llmobs_service.py
Backports #10493 to 2.12.
Fixes #10478.
This PR ensures that any custom trace filters are not overwritten in forked processes. Previously on forked processes, the `LLMObs` service restarting on fork was overwriting all tracer filters with the llmobs internal filter. …
=> fix(llmobs): keep custom trace filters in child processes [backport #10493 to 2.12]

ddtrace/internal/ci_visibility/recorder.py, releasenotes/notes/ci-visibility-handle-exception-in-tests-to-skip-675db3b857f8e232.yaml, tests/ci_visibility/test_ci_visibility.py
Backport 82650538b from #10460 to 2.12.
---------
Co-authored-by: Romain Komorn <136473744+romainkomorndatadog@users.noreply.github.com>
(cherry picked from commit 82650538b376a545e23362c1dd7f124ac79d6c88) …
=> fix(ci_visibility): handle errors while fetching skippable test data [backport 2.12]

ddtrace/internal/ci_visibility/recorder.py, releasenotes/notes/ci-visibility-handle-exception-in-tests-to-skip-675db3b857f8e232.yaml, tests/ci_visibility/test_ci_visibility.py
Backport 82650538b from #10460 to 2.11.
---------
Co-authored-by: Romain Komorn <136473744+romainkomorndatadog@users.noreply.github.com>
(cherry picked from commit 82650538b376a545e23362c1dd7f124ac79d6c88) …
=> fix(ci_visibility): handle errors while fetching skippable test data [backport 2.11]

ddtrace/settings/profiling.py
Manual backport of #10182 to 2.11 …
=> chore(profiling): set libdd_required when timeline_enabled (#10182) [backport-2.11]

.gitlab/release.yml
Backport https://github.com/DataDog/dd-trace-py/commit/d80d22d7650ddd1e858128bf3989084af4f7fb50 from #10449 to 2.12.
strategy
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)) …
=> ci: make pypi test upload actually upload [backport 2.12] (#10449)

.circleci/config.templ.yml, .gitlab/tests/contrib.yml, riotfile.py, tests/contrib/unittest/test_unittest_snapshot.py, tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_generates_coverage_correctly.json, tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_generates_coverage_correctly_with_skipped.json, tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_generates_source_file_data.json, tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_force_run_multiple_unskippable_tests.json, tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_force_run_unskippable_tests.json, tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_include_custom_tests.json, tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_include_lines_pct.json, tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_report_coverage_by_test_with_itr_skipped.json, tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_report_coverage_by_test_with_itr_skipped_multiple.json, tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_skip_invalid_unskippable_tests.json, tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_skip_unskippable_test_if_skip_decorator.json
- Removed unittest from config.templ.yaml file in circleCI
- Added unittest to the contrib.yml file in Gitlab …
=> ci: moved unittest config to Gitlab

docs/contributing-integrations.rst
updated the links in the snapshot-tests section of the doc to direct you to the [datadog-apm-test-agent](https://github.com/DataDog/dd-apm-test-agent?tab=readme-ov-file#datadog-apm-test-agent)
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting) …
=> docs: update contributing-integrations.rst

.github/CODEOWNERS, .gitlab/tests.yml, .gitlab/tests/contrib.yml, .gitlab/tests/llmobs.yml
This change updates codeowners for suites defined in gitlab. It also moves llmobs tests to their own file for this purpose. …
=> ci: update codeowners for gitlab suites

ddtrace/contrib/pytest/_plugin_v2.py, ddtrace/internal/ci_visibility/recorder.py, ddtrace/internal/test_visibility/api.py
Adds a `test_visibility.session.get_path_codeowners` core event handler to get codeowners without having to fetch a codeowner object from the internal API.
No release note since the API is currently unreleased.
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing …
=> chore(ci_visibility): add get_path_codeowners event handler

ddtrace/internal/ci_visibility/recorder.py, releasenotes/notes/ci_visibility-fix_properly_strip_dotgit_from_repo_url-523a908075aea559.yaml, tests/ci_visibility/test_ci_visibility.py
Fixes issue #10554  where `rstrip` was being used to remove the `.git` suffix from repo URLs, causing repo names that end in one or more of `g`, `i`, or `t` to be incorrectly extracted. eg: `fastapi.git` -> `fastap` or `test-environment` -> `test-environmen` . …
=> fix(ci_visibility): properly strip .git from repo URL when getting repo name

.github/workflows/build_deploy.yml, .gitlab-ci.yml
**What does this PR do?**
Converts the Gitlab workflow to use the unified pipeline.
By using the unified pipeline across all APM libraries, there is less maintenance hassle, fewer mistakes, and a more uniform creation of artifacts.
Additionally, this change creates OCI packages and lib inject images for every `dd-trace-py` build. Previously, only released versions to pypi were built and tested.
The changes can be summarized as follows:
* Removing github actions that are now taken over by the unified pipeline
* Removing Gitlab jobs taken over by the unified pipeline
* Adding a job to download artifacts from the github build
* Merging the download artifacts with dependencies from pypi
`.gitlab-ci.yml` is best reviewed in its final form rather than as a diff.
**How to test the change?**
The …
=> chore(ci): use unified Gitlab pipeline for APM libraries [backport 2.12]

ddtrace/internal/ci_visibility/recorder.py, releasenotes/notes/ci-visibility-handle-exception-in-tests-to-skip-675db3b857f8e232.yaml, tests/ci_visibility/test_ci_visibility.py
Backport 82650538b from #10460 to 2.10.
---------
Co-authored-by: Romain Komorn <136473744+romainkomorndatadog@users.noreply.github.com>
(cherry picked from commit 82650538b376a545e23362c1dd7f124ac79d6c88) …
=> fix(ci_visibility): handle errors while fetching skippable test data [backport 2.10]

ddtrace/internal/ci_visibility/recorder.py, releasenotes/notes/ci-visibility-handle-exception-in-tests-to-skip-675db3b857f8e232.yaml, tests/ci_visibility/test_ci_visibility.py
Backport 82650538b from #10460 to 2.9.
---------
Co-authored-by: Romain Komorn <136473744+romainkomorndatadog@users.noreply.github.com>
(cherry picked from commit 82650538b376a545e23362c1dd7f124ac79d6c88)
- The change includes or references documentation updates …
=> fix(ci_visibility): handle errors while fetching skippable test data [backport 2.9]

ddtrace/internal/datadog/profiling/stack_v2/include/sampler.hpp, ddtrace/internal/datadog/profiling/stack_v2/src/sampler.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp, ddtrace/profiling/collector/stack.pyx, ddtrace/profiling/collector/threading.py
Backport https://github.com/DataDog/dd-trace-py/commit/9848190b10af9e07f32cd79b333d1c23a0a0c60a from https://github.com/DataDog/dd-trace-py/pull/10066 to 2.10.
Looks like we dropped this part in the first cut for stack v2. Adding it back in.
Basically, stack v2 needs to know when threads are created in order to be able to track them off-GIL. In the future, we should probably harmonize on a common backplane for thread tracking, but for now... let's not.
- The change follows the [library …
=> fix(profiling): stack_v2 properly tracks Threading [backport-2.10]

ddtrace/appsec/_iast/taint_sinks/command_injection.py, ddtrace/appsec/_iast/taint_sinks/header_injection.py, ddtrace/appsec/_iast/taint_sinks/weak_cipher.py, releasenotes/notes/iast-fix-iast-import-error-f26e1451571ecbae.yaml, tests/contrib/django/test_django_appsec_snapshots.py
Fix potencial AttributeError exception in IAST functions that wrap with trace_utils.wrap instead of try_wrap_function_wrapper …
=> fix(iast): avoid potencial attribute error raise errors

.circleci/config.templ.yml, .gitlab/tests.yml, .gitlab/tests/contrib.yml
This change ensures that every node actually runs at least 1 env/command (riot or hatch).
We also have to fix the broken tests:
- aredis and asynctest were running with `parallel: 4` when they only had 3 envs to run
- `pytest_v2` was running as a riot job when it needed to be hatch
- the snapshots aren't working on GitLab so we had to convert it back to a CircleCI job
- The …
=> ci: ensure suite names match venvs

.gitlab/release.yml
We did not have the aws cli took available in the image.
Otherwise everything else looked ok: https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-py/-/jobs/634355695
- Title is …
=> ci: fix release publish step missing aws command

ddtrace/appsec/_iast/taint_sinks/command_injection.py, ddtrace/appsec/_iast/taint_sinks/header_injection.py, releasenotes/notes/iast-fix-iast-import-error-f26e1451571ecbae.yaml, tests/contrib/django/test_django_appsec_snapshots.py
Backport ad0d22344cae524949898ac88f034e2c7e731578 from #10586 to 2.10.
Fix potencial AttributeError exception in IAST functions that wrap with trace_utils.wrap instead of try_wrap_function_wrapper
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backport …
=> fix(iast): avoid potencial attribute error raise errors [backport 2.10]

ddtrace/appsec/_iast/taint_sinks/command_injection.py, ddtrace/appsec/_iast/taint_sinks/header_injection.py, releasenotes/notes/iast-fix-iast-import-error-f26e1451571ecbae.yaml, tests/contrib/django/test_django_appsec_snapshots.py
Backport ad0d22344cae524949898ac88f034e2c7e731578 from #10586 to 2.9.
Fix potencial AttributeError exception in IAST functions that wrap with trace_utils.wrap instead of try_wrap_function_wrapper
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporti …
=> fix(iast): avoid potencial attribute error raise errors [backport 2.9]

.gitlab/tests/core.yml
There are 6 envs for `ddtracerun` job, default parallel is 4. …
=> ci: update parallelism for ddtracerun job

tests/profiling-v2/collector/test_threading.py
=> chore(profiling): fix a flaky test

ddtrace/_trace/span.py, ddtrace/internal/_encoding.pyx, tests/contrib/fastapi/test_fastapi.py, tests/contrib/starlette/test_starlette.py, tests/opentelemetry/test_trace.py, tests/tracer/test_encoders.py, tests/tracer/test_propagation.py, tests/tracer/test_span.py
We are going to be using the `Span._links` structure to store Span Pointers soon. Span Pointers will have look like SpanLinks but will have `(trace_id=0, span_id=0)` so we cannot keep them in the old `_links` dictionary keyed by `span_id`. …
=> chore: [SVLS-5261] change Span._links to a list

ddtrace/contrib/internal/openai/utils.py, ddtrace/llmobs/_integrations/openai.py, releasenotes/notes/feat-openai-streamed-tokens-ed7f5c6a779006a9.yaml, tests/contrib/openai/cassettes/v1/chat_completion_streamed_tokens.yaml, tests/contrib/openai/test_openai_llmobs.py, tests/contrib/openai/test_openai_v1.py
This PR adds support to capture token metrics if provided in the OpenAI streamed response. If `stream_options={"include_usage": True}` is specified as an argument in a streamed Completion/ChatCompletion call, OpenAI provides a chunk containing the request/response pair's token usage metrics. 
We do this by prepending the token usage chunk (if provided in the response) at the beginning of the streamed chunks list we keep track of. Instead of computing/estimating token usage from streamed responses (which are not guaranteed to be accurate), we can ensure correct token metrics IF the user adds this option.
This PR also makes a small refactor to clean up the stream handler code involved in getting/setting the token metrics, and submitting token metrics as Datadog integration metrics.
- The PR …
=> feat(openai): capture token usage for streamed chat/completions

ddtrace/_trace/_span_link.py, ddtrace/_trace/span.py, tests/tracer/test_encoders.py, tests/tracer/test_span.py
Span Pointers are stored alongside Span Links. The API is private for now, so we don't have much documentation and all the new classes are prefixed with underscores.
- …
=> feat(tracer): [SVLS-5261] private Span Pointers

.gitlab/tests/appsec.yml, hatch.toml, scripts/iast/test_leak_functions.py, tests/appsec/iast_aggregated_memcheck/test_aggregated_memleaks.py
- Remove Python 3.7 for memleak testing since it have a tendency to timeout.
- Lower the number of iterations to 75.000. Now the reference RSS will always be taken at 50k iterations and no less than 60k total iterations will be allowed.
- Add some verbosity options so the output and progress of the script can be seen from the gitlab page. …
=> chore: easier memleak testing so gitlab does not timeout

ddtrace/contrib/psycopg/__init__.py, releasenotes/notes/fix-postgres-circular-req-0904bf22c32c785d.yaml
=> fix(postgres): remove require modules to resolve circular imports (backport #10658 to 2.12)

ddtrace/contrib/internal/anthropic/patch.py, ddtrace/contrib/internal/anthropic/utils.py, releasenotes/notes/fix-anthroipc-json-serializable-99af0985bd967e5d.yaml, tests/contrib/anthropic/test_anthropic.py, tests/snapshots/tests.contrib.anthropic.test_anthropic.test_anthropic_llm_unserializable_arg.json
Backports #10659 to 2.13.
Fixes #10420
Ensures that any JSON dumping we do will not crash due to unserializable objects, and safely cast all `set_tag_str()` args as string.
- Title is …
=> fix(anthropic): safely json dump unserializable objects [backport #10659 to 2.13]

docs/contributing-integrations.rst, docs/contributing-testing.rst, docs/contributing.rst, lib-injection/README.md, scripts/ddtest
With newer versions of Docker (20.10+), `docker compose` is used instead of `docker-compose`. Using `docker-compose` with the newer version of Docker will cause an error, and the `scripts/ddtest` will not run. This PR updates the script to check if `docker compose` is available, and if so will use that. Otherwise, it will default to using the original `docker-compose` command.
Docs have also been updated to use `docker compose` instead. …
=> chore: prefer `docker compose` instead of older `docker-compose`

pyproject.toml
Fix the usual version problem
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html# …
=> chore(tracer): fix version computation for 2.11 for system tests

docker/Dockerfile_py311_debug_mode, scripts/iast/.env, scripts/iast/run_memory.sh, scripts/iast/run_memray.sh, scripts/iast/run_references.sh, scripts/iast/test_references.py
Update Python in debug mode dockerfile and scripts.
- Migrate to debian:bookworm-slim due to ddtrace core needs glibc-2.29
- .sh files are not running the last version of *.py files. Now the py files needs arguments
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contrib …
=> chore(iast): python debug dockerfile update

ddtrace/llmobs/_trace_processor.py, tests/llmobs/_utils.py
Adds a `language:python` tag to all LLMObs span events, to be used for internal analysis. No changelog needed since this isn't a user-facing functional change or fix (it will just show as an extra tag in the UI).
[MLOB-1543] …
=> chore(llmobs): add language tag to span events

ddtrace/_trace/_span_pointer.py
I realized you may not want to merge these all to that branch.
Reverts DataDog/dd-trace-py#10685
=> Revert "feat(tracer): [SVLS-5262] private Span Pointer Description"

ddtrace/contrib/internal/anthropic/patch.py, ddtrace/contrib/internal/anthropic/utils.py, releasenotes/notes/fix-anthroipc-json-serializable-99af0985bd967e5d.yaml, tests/contrib/anthropic/test_anthropic.py, tests/snapshots/tests.contrib.anthropic.test_anthropic.test_anthropic_llm_unserializable_arg.json
Backports #10659 to 2.12.
Fixes #10420
Ensures that any JSON dumping we do will not crash due to unserializable objects, and safely cast all `set_tag_str()` args as string.
- Title is …
=> fix(anthropic): safely json dump unserializable objects [backport #10659 to 2.12]

ddtrace/_trace/_span_pointer.py
In order to help decouple code that calculates span pointers from the spans and pointers themselves, we make a private Span Pointer Description class. …
=> feat(tracer): [SVLS-5262] private Span Pointer Description

ddtrace/_trace/_span_pointer.py, tests/tracer/test_span_pointers.py
Adding a standard hashing function for Span Pointers. This continues to be a private API for now.
- Avoids …
=> chore: [SVLS-5262] Span Pointer standard hashing

ddtrace/llmobs/_integrations/base.py, releasenotes/notes/fix-llm-integrations-metrics-default-bc597eb5a5218b32.yaml, tests/llmobs/test_llmobs_integrations.py
Follows up on #10084, which missed a condition where agentless mode should always disable integration metrics.
Adds standard testing cases for the `BaseLLMIntegration` class, which was missing prior to this (and thus the reason for missing this edge case prior) …
=> fix(llmobs): ensure integration metrics are disabled in agentless mode

ddtrace/_trace/utils_botocore/span_pointers.py, tests/tracer/utils_botocore/test_span_pointers.py
Span Pointer calculations for the AWS S3 PutObject operation. These are private functions for now.
- Avoids …
=> chore: [SVLS-5262] AWS S3 PutObject pointer calc

ddtrace/appsec/_iast/_taint_tracking/_native.cpp, releasenotes/notes/initializer-atexit-6f9a025488fe14b4.yaml
Partial backport of the Initializer atexit fix from #10706. …
=> fix(iast): backport fix from 10706 to 2.12

ddtrace/appsec/_iast/_taint_tracking/_native.cpp, releasenotes/notes/initializer-atexit-b353744cf1af7917.yaml
Partial backport of the `Initializer` `atexit` fix from https://github.com/DataDog/dd-trace-py/pull/10706.
- …
=> fix(iast): backport fix from 10706 to 2.10

ddtrace/appsec/_iast/_taint_tracking/_native.cpp, releasenotes/notes/initializer-atexit-a04b2c908d3e8eeb.yaml
Partial backport of the `Initializer atexit` fix from https://github.com/DataDog/dd-trace-py/pull/10706.
- …
=> fix(iast): backport fix from 10706 to 2.9

ddtrace/appsec/_iast/_taint_tracking/_native.cpp, releasenotes/notes/initializer-atexit-4c10671e585ac3e7.yaml
Partial backport of the `Initializer` `atexit` fix from https://github.com/DataDog/dd-trace-py/pull/10706.
- …
=> fix(iast): backport fix from 10706 to 2.11

.github/workflows/build_deploy.yml, .gitlab/release.yml
Moving the artifact uploading to GitLab means we can include other GitLab validations as requirements to uploading to PyPI.
We have validated this by first having the pipeline upload to test.pypi.org.
This was enabled for the 2.12.2 release, and we can validate the artifacts uploaded were the same:
- pypi.org: https://pypi.org/project/ddtrace/2.12.2/#files
- test.pypi.org: https://test.pypi.org/project/ddtrace/2.12.2/#files
All files were downloaded, and the sha256 sums were validated to be the same.
- Newly-added code is easy …
=> ci: move PyPI artifact uploading to GitLab

ddtrace/_trace/trace_handlers.py, releasenotes/notes/span-pointers-aws-s3-putobject-32b66688c9cad5e6.yaml, tests/contrib/botocore/test.py
Creating Span Pointers for successful botocore patched api calls. Still a private feature. …
=> feat(tracer): [SVLS-5262] Botocore Success Span Pointers

ddtrace/_trace/utils_botocore/span_pointers.py, releasenotes/notes/span-pointers-aws-s3-copyobject-3d8ab886b32695b9.yaml, tests/tracer/utils_botocore/test_span_pointers.py
Adding span pointers for the S3 CopyObject operation. …
=> feat(tracer): [SVLS-5264] S3 CopyObject span pointers

tests/contrib/openai/test_openai_llmobs.py
This PR follows up on #10727, which accidentally omitted a `integration="openai"` line in a backported test case. Due to all the other changes to the OpenAI integration which were backported at the same time, this line got omitted during the merge conflict resolution. …
=> chore(llmobs): fix omitted test assertion from backport #10694 to 2.13

ddtrace/_trace/utils_botocore/span_pointers.py, releasenotes/notes/span-pointers-aws-s3-completemultipartupload-7ddd8a88050e710b.yaml, tests/tracer/utils_botocore/test_span_pointers.py
=> feat(tracer): [SVLS-5263] S3 CompleteMultipartUpload span pointers

tests/appsec/iast/aspects/test_join_aspect_fixtures.py
Fix flaky test with tuple elements order …
=> chore(iast): flaky test

tests/debugging/test_encoding.py
We relax the snapshot count check in batching tests to account for possible rounding errors. …
=> test(debugger): allow rounding error in batching

ddtrace/llmobs/_trace_processor.py, tests/llmobs/_utils.py
Reverts DataDog/dd-trace-py#10700 …
=> Revert "chore(llmobs): add language tag to span events [backport 2.9]"

ddtrace/internal/ci_visibility/_api_client.py, ddtrace/internal/ci_visibility/constants.py, ddtrace/internal/ci_visibility/recorder.py, ddtrace/internal/ci_visibility/telemetry/api_request.py, ddtrace/internal/ci_visibility/telemetry/early_flake_detection.py, ddtrace/internal/ci_visibility/telemetry/git.py, ddtrace/internal/ci_visibility/telemetry/itr.py, tests/ci_visibility/api_client/_util.py, tests/ci_visibility/api_client/test_ci_visibility_api_client.py, tests/ci_visibility/api_client/test_ci_visibility_api_client_setting_responses.py, tests/ci_visibility/api_client/test_ci_visibility_api_client_unique_tests_responses.py, tests/ci_visibility/test_ci_visibility.py
This adds the unique tests request (`self.fetch_unique_tests()`) to the API client to support Early Flake Detection work.
A refactor wraps the client's `_do_request()` method is also wrapped in `_do_request_with_telemetry()` to DRY the three `_do_request()` callers. The telemetry calls are also refactored into a `api_request` telemetry module.
This also fixes the test verifying the skippable API request payload which had been shamefully copy/pasted and was actually not testing what it was supposed to.
- Newly-added code is easy …
=> chore(ci_visibility): add unique tests request to test vis API client

ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectFormat.cpp, ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp, ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.h, ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.cpp
Return earlier if there are no ranges in some aspects, specifically the index, operator add and format aspects. This hopefully should improve performance in the most common case.
- Title is …
=> chore(iast): return earlier if there are no ranges in some aspects

ddtrace/internal/datadog/profiling/dd_wrapper/include/ddup_interface.hpp, ddtrace/internal/datadog/profiling/dd_wrapper/include/sample.hpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/ddup_interface.cpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/sample.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp, releasenotes/notes/profiling-stack-v2-upside-down-82ebd3073b5e8e43.yaml
Manual backport of #10851 to 2.13
Fixes an issue where flamegraph was upside down for stack v2, when `DD_PROFILING_STACK_V2_ENABLED` …
=> fix(profiling): reverse locations for stack v2 [backport-2.13]

ddtrace/internal/datadog/profiling/dd_wrapper/include/ddup_interface.hpp, ddtrace/internal/datadog/profiling/dd_wrapper/include/sample.hpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/ddup_interface.cpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/sample.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp, releasenotes/notes/profiling-stack-v2-upside-down-82ebd3073b5e8e43.yaml, tests/profiling/collector/pprof_utils.py, tests/profiling_v2/collector/test_stack.py
Manual backport of https://github.com/DataDog/dd-trace-py/pull/10851 to 2.14
Fixes an issue where flamegraph was upside down for stack v2, when DD_PROFILING_STACK_V2_ENABLED
- Title is …
=> fix(profiling): reverse locations for stack v2 [backport-2.14]

.gitignore
With [fix(profiling): platform-specific files should have platform-specific filenames](https://github.com/DataDog/dd-trace-py/pull/10840), crashtracker binaries have trailing platform specific strings in their names, e.g. `crashtracker_exe-glibc-aarch64` …
=> chore: ignore crashtracker binary in git

repository.datadog.yml
This PR will enable the Datadog merge queue in this repo …
=> ci: enable dd merge queue

ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.cpp, ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.h, ddtrace/appsec/_iast/_taint_tracking/tests/test_other.cpp, scripts/gen_circleci_config.py
This PR updates the Circleci `pre_check` job to run style checks on `.cpp` and `.h` file changes.
The `pre_check` job is consistently failing on the main branch due to these style check failures. This means the other CircleCI jobs do not run on the main branch, since `pre_check` is the prerequisite. Example failure [here](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/73979/workflows/87f87583-5cb6-4b24-872d-fa6f671602c7/jobs/4322936).
This PR updates the triggers for style checks, and also tweaks the files causing the style failures to conform to them.
Tested by creating a dummy PR and committing failing changes and then passing changes. See test PR [here](https://github.com/DataDog/dd-trace-py/pull/10916).
See passing style check …
=> ci: update the circleci `pre_check` job to run style checks on `.cpp` and `.h` file changes

releasenotes/notes/iast-feat-iast-telemetry-error-f6ba4a6aadf96ec9.yaml
The release note for https://github.com/DataDog/dd-trace-py/pull/10784 (original: https://github.com/DataDog/dd-trace-py/pull/10740) was marked as a new feature when it should have been a fix. In order to conform to SemVer, we cannot be adding new features to patch releases.  …
=> chore: change release note type from feature to fix

ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt, ddtrace/internal/datadog/profiling/stack_v2/__init__.py, ddtrace/internal/datadog/profiling/stack_v2/include/thread_span_links.hpp, ddtrace/internal/datadog/profiling/stack_v2/src/sampler.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/thread_span_links.cpp, ddtrace/profiling/collector/stack.pyx, releasenotes/notes/profiling-fix-stack-v2-endpoint-82a1e26366166b8d.yaml
Manual backport of #10882 to 2.13 …
=> fix(profiling): endpoint profiling for stack v2 [backport-2.13]

.readthedocs.yml
Our ReadTheDocs builds have been failing for a long time due to permission issues when trying to install hatch in `/usr/local/bin` (see example [here](https://app.readthedocs.org/projects/ddtrace/builds/25806367/)). The latest stable version is 2.9.6, and we are currently on 2.14.2.
This PR moves the installation to happen in `$HOME/.asdf/bin` instead, as it's already created and exists on the PATH. I attempted to create `$HOME/.local/bin` instead, but for some reason I'm unable to update the PATH to include this path, so it doesn't work and I needed to use an existing path. 
Resolving this issue also surfaced Rust issues, so I went ahead and fixed that as well.
- The …
=> docs: use `$HOME/.asdf/bin` instead of `/usr/local/bin` for installing hatch

ddtrace/contrib/pytest/_utils.py, tests/contrib/pytest/test_pytest.py
Fixes the way module path was being computed. Now uses the parent of the `item`'s `path` attribute if available, and if not, uses `item.module.__path__`'s parent. Otherwise it defaults to the current directory.
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing …
=> chore(ci_visibility): fix module path collection

.github/workflows/build_deploy.yml, .github/workflows/build_python_3.yml, .github/workflows/codeql-analysis.yml, .github/workflows/django-overhead-profile.yml, .github/workflows/encoders-profile.yml, .github/workflows/flask-overhead-profile.yml, .github/workflows/pypa_musllinux_1_2_i686.yml, .github/workflows/requirements-locks.yml, .github/workflows/rust-ci.yml, .github/workflows/system-tests.yml, .github/workflows/test_frameworks.yml, .github/workflows/testrunner.yml, .github/workflows/unit_tests.yml
GitHub jobs are not running when PRs are added to the DD MQ. We need to add a branch trigger for `'mq-working-branch**'` for them to run on the merge queue.
- All changes …
=> ci: clean up github mq configs and add dd mq configs

mypy.ini
`ddtrace/internal/datadog/profiling/build/dd_wrapper/_deps` could contain Python files from googletest. 
- …
=> chore: mypy ignores `dd_wrapper/_deps` directory

hatch.toml
=> chore(ci): set build parallel level for hatch ddtrace_unit_tests

.github/workflows/unit_tests.yml
1. Use matrix in actions: No need to specify archs as GitHub actions runners only support specific archs for given OSes and we've only been running ubuntu-latest (x86_64), windows-latest (x86_64) and macos-latest (arm64).
2. Pass python version to hatch run. …
=> chore(ci): parallelize unittest github actions

.github/workflows/django-overhead-profile.yml
We enable Code Origin for Spans in the Django profile job to collect profiling data with the featured turned on. …
=> ci: enable code origin for spans in django profile

.gitlab-ci.yml
Fix for alpine test failing on gitlab after some changes on system tests. …
=> chore(ci): fix alpine test

releasenotes/notes/profiling-fix-stack-v2-endpoint-82a1e26366166b8d.yaml
=> chore(profiling): update relnote for endpoint stack v2

ddtrace/_trace/trace_handlers.py, ddtrace/_trace/utils_botocore/span_pointers.py, ddtrace/contrib/botocore/__init__.py, ddtrace/contrib/internal/botocore/patch.py, releasenotes/notes/span-pointers-aws-dynamodb-putitem-f4be08418bc99093.yaml, tests/contrib/botocore/test.py, tests/tracer/utils_botocore/test_span_pointers.py
PutItem is a bit tricky since it doesn't have a separate primary key section. The primary key is mixed into the Item itself. So we need a way for our customers to identify the primary key field names for a table. We'll start by doing this with configuration, and we may add a way for the user to opt in to us making a (cached) DescribeTable call on their behalf.
- The change …
=> feat(tracer): [SVLS-5672] DynamoDB PutItem pointers

ddtrace/internal/encoding.py, tests/integration/test_encoding.py, tests/tracer/test_encoders.py
=> chore: [SVLS-5265] add span links to encoded spans

.github/workflows/system-tests.yml
CI: Removes conditions to check wether should run or "dry run" system tests, and just runs them
- Avoids …
=> ci: always run system tests [backport 2.13]

.github/workflows/test_frameworks.yml
CI: Adds timeouts to the framework test suites so they don't hang like:
https://github.com/DataDog/dd-trace-py/actions/runs/11250518980/job/31279581076?pr=10899
- All …
=> ci: add timeout minutes to `sanic` and `starlette` suites

ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt, ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt, releasenotes/notes/profiling-pthread-aarch64-d4548fd1842d0665.yaml
python:3.11-bookworm image for aarch64 has `pthread_atfork` in static libpthread.a not in libpthread.so so need to explicitly link for those cases. Otherwise, we get undefined symbol `pthread_atfork`. 
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#bac …
=> fix(profiling): explicitly link with thread library

ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt, ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt, releasenotes/notes/profiling-pthread-aarch64-d4548fd1842d0665.yaml
Backport #10994 to 2.15.
python:3.11-bookworm image for aarch64 has `pthread_atfork` in static libpthread.a not in libpthread.so so need to explicitly link for those cases. Otherwise, we get undefined symbol `pthread_atfork`. …
=> fix(profiling): explicitly link with thread library [backport-2.15]

ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt, ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt, releasenotes/notes/profiling-pthread-aarch64-d4548fd1842d0665.yaml
Backport https://github.com/DataDog/dd-trace-py/pull/10994 to 2.14.
python:3.11-bookworm image for aarch64 has `pthread_atfork` in static libpthread.a not in libpthread.so so need to explicitly link for those cases. Otherwise, we get undefined symbol `pthread_atfork`. …
=> fix(profiling): explicitly link with thread library [backport-2.14]

ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt, ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt, releasenotes/notes/profiling-pthread-aarch64-d4548fd1842d0665.yaml
Manual backport of #10994 to 2.13
python:3.11-bookworm image for aarch64 has `pthread_atfork` in static libpthread.a not in libpthread.so so need to explicitly link for those cases. Otherwise, we get undefined symbol `pthread_atfork`. …
=> fix(profiling): explicitly link with thread library [backport-2.13]

ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt, ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt, releasenotes/notes/profiling-pthread-aarch64-d4548fd1842d0665.yaml
Manual backport of #10994 to 2.12
python:3.11-bookworm image for aarch64 has `pthread_atfork` in static libpthread.a not in libpthread.so so need to explicitly link for those cases. Otherwise, we get undefined symbol `pthread_atfork`. …
=> fix(profiling): explicitly link with thread library [backport-2.12]

ddtrace/appsec/rules.json, releasenotes/notes/security_rule_update_1.13.1-374c18e4f0a8c338.yaml, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
Update security rules to 1.13.1.
https://github.com/DataDog/appsec-event-rules/releases/tag/1.13.1
- Avoids …
=> chore(asm): update security rules

ddtrace/_trace/utils_botocore/span_pointers/dynamodb.py, releasenotes/notes/span-pointers-aws-dynamodb-updateitem-bd6a81e26371a855.yaml, tests/tracer/utils_botocore/test_span_pointers.py
UpdateItem thankfully includes the primary key in the request parameters, so there's not much extra for us to do. …
=> feat(tracer): [SVLS-5673] DynamoDB UpdateItem pointers

ddtrace/appsec/_iast/_ast/visitor.py, releasenotes/notes/iast-aspects-partial-matches-f43dc04584ca6788.yaml, tests/appsec/iast/_ast/test_ast_patching.py, tests/appsec/iast/fixtures/ast/other/globals_builtin.py
Code Security: This PR fixes an issue where partial matches of the functions we want to patch would be patched instead of exact matches …
=> fix(iast): partial matches on function names should not be patched

setup.py, tests/appsec/appsec/test_processor.py, tests/contrib/django/test_django_appsec_snapshots.py, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Update libddwaf to [last version 1.20.0](https://github.com/DataDog/libddwaf/releases/tag/1.20.0)
Also add fingerprinting session to the ignore tags for snapshot tests, as the new libddwaf version is generating them. …
=> chore(asm): waf update to 1.20.0

benchmarks/bm/iast_fixtures/str_methods.py, ddtrace/appsec/_iast/_taint_tracking/aspects.py, releasenotes/notes/iast-fix-re-finditer-aspect-8925b30073169222.yaml, tests/appsec/app.py, tests/appsec/iast/aspects/test_join_aspect_fixtures.py, tests/appsec/iast/aspects/test_re_aspects.py, tests/appsec/iast_packages/packages/pkg_python_multipart.py, tests/appsec/iast_packages/test_packages.py, tests/contrib/fastapi/test_fastapi_appsec_iast.py
Ensure IAST propagation does not raise side effects related to re.finditer.
We detect this error in #10988 PR, when FastAPI headers were empty in framework tests: https://github.com/DataDog/dd-trace-py/actions/runs/11273577079/job/31350947622
We can revert this system tests PR after this PR: https://github.com/DataDog/system-tests/pull/3230
This error was detected in [python-multipart==0.0.05](https://pypi.org/project/python-multipart/0.0.5/) …
=> fix(iast): re.finditer aspect error

ddtrace/appsec/_iast/_ast/visitor.py, releasenotes/notes/iast-aspects-partial-matches-f43dc04584ca6788.yaml, tests/appsec/iast/_ast/test_ast_patching.py, tests/appsec/iast/fixtures/ast/other/globals_builtin.py
backport of #11015
Code Security: This PR fixes an issue where partial matches of the functions we want to patch would be patched instead of exact matches
- All changes …
=> fix(iast): partial matches on function names should not be patched [backport 2.11]

scripts/release.py
A few clean up things in the release script. Mainly that the regex to grab the PR number from the commit message broke because it was looking for a 4 digit number, but we recently hit 5 digits.
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting …
=> chore: fix notebook bug with release script

.github/workflows/codeowners.yml
The CODEOWNERS comment job is failing on 2.11 backports (and most likely any other older branches) because of missing write permissions. This is a manual backport to fix this.
- Title is …
=> fix(ci): manual backport of the new codeowners github actions definition

benchmarks/django_simple/app.py, benchmarks/django_simple/config.yaml, benchmarks/django_simple/gunicorn.conf.py, benchmarks/django_simple/scenario.py, benchmarks/django_simple/utils.py
We add a benchmark scenario for Exception Replay. …
=> ci: exception replay benchmark scenario

ddtrace/llmobs/_llmobs.py, releasenotes/notes/metadata-for-eval-metrics-3d3bac0e0738fdc2.yaml, tests/llmobs/_utils.py, tests/llmobs/test_llmobs_service.py
The evaluation metric api supports a `metadata` field now which represents arbitrary metadata that can be tied to an evaluation metric.
This PR adds support for that field via the `submit_evaluation` method
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.htm …
=> feat(llmobs): support metadata field for custom evaluation metrics

ddtrace/appsec/__init__.py, ddtrace/appsec/_handlers.py, ddtrace/appsec/_iast/_handlers.py, ddtrace/appsec/_iast/_iast_request_context.py, ddtrace/appsec/_iast/_patch.py, ddtrace/appsec/_iast/processor.py, ddtrace/contrib/internal/fastapi/patch.py, tests/appsec/iast/conftest.py, tests/appsec/iast/test_grpc_iast.py, tests/appsec/iast/test_telemetry.py, tests/appsec/integrations/test_flask_telemetry.py, tests/contrib/fastapi/test_fastapi_appsec_iast.py
Before this PR, IAST and ASM hooks were mixed together inside `asm_listen`. Now, all the IAST and ASM logic has been separated …
=> chore(iast): separate iast and asm listens

.circleci/config.templ.yml, .circleci/config.yml, .github/workflows/generate-package-versions.yml, .github/workflows/requirements-locks.yml, .gitlab/package.yml, .gitlab/tests.yml, hatch.toml, scripts/ddtest
This PR bumps the riot version in dd-trace-py from 0.19.1 to 0.20.0 to fix virtualenv versioning incompatibilities with python3.7.
With the new release of `virtualenv==20.27.0`, we were seeing new failures with `build_base_venv[3.7]` (GitLab) and `build_base_venv` (CircleCI) jobs when running:
```
riot -P -v generate --python=$PYTHON_VERSION
...
File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/.riot/venv_py3717/lib/python3.7/site-packages/pip/_vendor/typing_extensions.py", line 1039
def TypedDict(typename, fields=_marker, /, *, total=True, closed=False, **kwargs):
^
SyntaxError: invalid syntax
ERROR:riot.riot:Dev install failed, aborting!
```
We needed to pin to `virtualenv==20.26.6` to continue supporting python3.7
The `upload-artifact` and `download-artifact` bumps were …
=> chore(ci): bump riot version for 3.7 compatibility issues

ddtrace/appsec/_iast/_iast_request_context.py, ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py, ddtrace/contrib/internal/asgi/middleware.py, tests/contrib/fastapi/test_fastapi_appsec_iast.py
This PR adds support for detecting cookies that are not marked as secure, are not using the HttpOnly mark, or are not using one of the secure options of the Samesite= setting
- Title is …
=> feat(iast): add support for cookie vulnerability for FastAPI

ddtrace/appsec/_constants.py, ddtrace/appsec/_iast/_taint_tracking/__init__.py, tests/contrib/fastapi/test_fastapi_appsec_iast.py
IAST context refactor found a problem with tainted re.Match objects https://github.com/DataDog/dd-trace-py/pull/10988/files#diff-85e91d30afa95f5cf701f8187200d0bdcec50d55999ef03708d49fa5a5ccb1d6R127
It looks this PR fixed the problem https://github.com/DataDog/dd-trace-py/pull/11042 So, this PR enables again Match  …
=> chore(iast): restore Match

.circleci/config.templ.yml, .circleci/config.yml, .github/workflows/generate-package-versions.yml, .github/workflows/requirements-locks.yml, .gitlab/package.yml, .gitlab/tests.yml, hatch.toml, scripts/ddtest
Manual backport of #11085 to 2.13
With the new release of virtualenv==20.27.0, we were seeing new failures with build_base_venv[3.7] (GitLab) and build_base_venv (CircleCI) jobs when running:
```
riot -P -v generate --python=$PYTHON_VERSION
...
File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/.riot/venv_py3717/lib/python3.7/site-packages/pip/_vendor/typing_extensions.py", line 1039
def TypedDict(typename, fields=_marker, /, *, total=True, closed=False, **kwargs):
^
SyntaxError: invalid syntax
ERROR:riot.riot:Dev install failed, aborting!
```
We need to pin to virtualenv==20.26.6 to continue supporting python3.7
The upload-artifact and download-artifact bumps were required to unblock the riot CI. It had been a while since the last update to riot, and since then, v2 has been …
=> chore(ci): bump riot version for 3.7 compatibility issues [backport 2.13]

.circleci/config.templ.yml, .circleci/config.yml, .github/workflows/generate-package-versions.yml, .github/workflows/requirements-locks.yml, .gitlab/package.yml, .gitlab/tests.yml, hatch.toml, scripts/ddtest
Manual backport of #11085 to 2.14
With the new release of virtualenv==20.27.0, we were seeing new failures with build_base_venv[3.7] (GitLab) and build_base_venv (CircleCI) jobs when running:
```
riot -P -v generate --python=$PYTHON_VERSION
...
File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/.riot/venv_py3717/lib/python3.7/site-packages/pip/_vendor/typing_extensions.py", line 1039
def TypedDict(typename, fields=_marker, /, *, total=True, closed=False, **kwargs):
^
SyntaxError: invalid syntax
ERROR:riot.riot:Dev install failed, aborting!
```
We need to pin to virtualenv==20.26.6 to continue supporting python3.7
The upload-artifact and download-artifact bumps were required to unblock the riot CI. It had been a while since the last update to riot, and since then, v2 has been …
=> chore(ci): bump riot version for 3.7 compatibility issues [backport 2.14]

hatch.toml
We fix the dependency on envier for the doc environment to avoid breaking when a new version is released.
- …
=> docs: pin envier dependency

setup.py, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Update libddwaf from 1.20.0 to [1.20.1](https://github.com/DataDog/libddwaf/releases/tag/1.20.1)
- Avoids …
=> chore(asm): update libddwaf to 1.20.1

.circleci/config.templ.yml, .circleci/config.yml, .github/workflows/requirements-locks.yml, .github/workflows/unit_tests.yml, hatch.toml, scripts/ddtest
This PR is a combination of this backport PR https://github.com/DataDog/dd-trace-py/pull/11085 and an additional `virtualenv` version pinning fix that were required to unblock the CI for the 2.11 release branch.
The reason the original backport PR was not sufficient to fix the CI for 2.11 unlike 2.13+ was because of some discrepancies with CircleCI vs. GitLab. Since 2.11 and 2.12 still run the `appsec_threat_*` tests via CircleCI, it was somehow still using the newer `virtualenv==20.27.0` instead of `virtualenv==20.26.0` that we attempted to pin in the previous backport.  …
=> chore(ci): bump riot version and pin virtualenv==20.26.6 for hatch use with python3.7 [2.11]

lib-injection/sources/sitecustomize.py
We noticed we weren't getting any telemetry
https://datadoghq.atlassian.net/browse/INPLAT-11 …
=> chore(onboarding): fix condition to enable SSI telemetry

ddtrace/appsec/_iast/_taint_tracking/__init__.py, tests/appsec/iast/aspects/test_re_aspects.py, tests/contrib/flask/test_flask_appsec_iast.py
IAST context refactor found a problem with tainted re.Match objects https://github.com/DataDog/dd-trace-py/pull/10988/files#diff-85e91d30afa95f5cf701f8187200d0bdcec50d55999ef03708d49fa5a5ccb1d6R127
It looks this PR fixed the problem https://github.com/DataDog/dd-trace-py/pull/11042 So, this PR enables again Match  …
=> chore(iast): restore Match tests

ddtrace/llmobs/_evaluators/ragas/faithfulness.py, ddtrace/llmobs/_evaluators/runner.py, ddtrace/llmobs/_llmobs.py, tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_evaluator_runner.send_score_metric.yaml, tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_ragas_faithfulness_evaluator.emits_traces_and_evaluations_on_exit, tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_ragas_faithfulness_evaluator.emits_traces_and_evaluations_on_exit.yaml, tests/llmobs/test_llmobs_evaluator_runner.py, tests/llmobs/test_llmobs_ragas_faithfulness_evaluator.py
This PR fixes behavior where the last span generated right before process exit was not being evaluated by the ragas faithfulness evaluator.
Previous behavior:
1. On process exit, `LLMObs.disable()` is called
2. `LLMObs.disabled` is set to `True`
3. Eval metric writers and span writers are stopped
4. Evaluator runner is stopped
There is a problem here where span & eval metric writers are stopped & LLM Obs disabled is set to true while the eval runner has not finished tracing & evaluating the span events in it's buffer.
1. Make sure eval runner is stopped **_BEFORE_** eval metric writer and span writers are stopped
2. Make sure `LLMOBs.disabled` is set to false only after the eval runner is stopped
3. Within `_stop_service` call `self.periodic` and `self.executor.shutdown(wait=True)`
The …
=> chore(llmobs): fix faithfulness evaluator behavior on process exit

ddtrace/appsec/_iast/_ast/visitor.py, releasenotes/notes/iast-aspects-partial-matches-f43dc04584ca6788.yaml, tests/appsec/iast/_ast/test_ast_patching.py, tests/appsec/iast/fixtures/ast/other/globals_builtin.py
Code Security: This PR fixes an issue where partial matches of the functions we want to patch would be patched instead of exact matches …
=> fix(iast): partial matches on function names should not be patched [backport 2.12]

ddtrace/appsec/_iast/_ast/visitor.py, releasenotes/notes/iast-aspects-partial-matches-f43dc04584ca6788.yaml, tests/appsec/iast/_ast/test_ast_patching.py, tests/appsec/iast/fixtures/ast/other/globals_builtin.py
Code Security: This PR fixes an issue where partial matches of the functions we want to patch would be patched instead of exact matches …
=> fix(iast): partial matches on function names should not be patched [backport 2.13]

.github/workflows/test_frameworks.yml
The `beautifulsoup` framework tests were using `pip install ddtrace` to install `ddtrace`, which was using the `latest` version of `ddtrace` from PyPI instead of the local version from the branch ([see example here](https://github.com/DataDog/dd-trace-py/actions/runs/11462716535/job/31894873509#step:5:19)).
This PR fixes this to run `pip3 install ./ddtrace` instead so we're testing with the current version of `ddtrace` for the branch that triggered the test.
- The change follows the [library …
=> chore(ci): update `beautifulsoup` framework test to use local `ddtrace` not PyPI latest

ddtrace/_trace/utils_botocore/span_pointers/__init__.py
https://github.com/DataDog/dd-trace-py/pull/11008 rearranged a bunch of code, but some of that code was already being used outside of this repo. Let's unbreak those imports for now.
- Title …
=> chore: unbreak moved private function imports

ddtrace/appsec/_asm_request_context.py, ddtrace/appsec/_ddwaf/__init__.py, ddtrace/appsec/_processor.py, tests/appsec/appsec/test_processor.py
- move span tag logic for ddwaf info data from processor to asm context to do it only once per request. 
- move serialisation of errors from processor to waf interface to do it only when waf is initialised or updated.
- remove warnings log for span tag logic and corresponding test. (json errors are impossible now due to ddwaf_object use)
- add return code from ddwaf_run into DDWaf_result object
Preparatory PR for APPSEC-55199 …
=> chore(asm): move waf info report to asm_context and add return code in ddwaf_result

ddtrace/debugging/_probe/remoteconfig.py, releasenotes/notes/fix-span-decoration-probe-timing-dc4ce0664fa645b9.yaml
We make sure that we get the value from the enum for the evaluate_at property so that proper validation and comparison can be performed. Currently, the timing value is stored as a plain string, whereas the logic that handles them expects one of the possible enum values, thus making the check fail always. …
=> fix(di): use enum value for evaluate_at property

ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp, releasenotes/notes/profiling-stack-v2-endpoint-span-type-none-48a1196296be3742.yaml, tests/profiling_v2/collector/test_stack.py
=> fix(profiling): handle `Span`s with `None` span type for stack v2 endpoint profiling

ddtrace/llmobs/_llmobs.py, releasenotes/notes/fix-numeric-annotations-7cf06b5ceb615282.yaml, tests/llmobs/test_llmobs_service.py
Backport https://github.com/DataDog/dd-trace-py/commit/2f23eb28c6b4d98b6cac4f84edc2ee3c42095aad from https://github.com/DataDog/dd-trace-py/pull/11044 to 2.13.
Fixes an issue where we are dropping I/O annotations that were equal to zero for workflow, task, agent and tool spans.
- Backport labels are set …
=> fix(llmobs): don't drop IO annotations equal to zero (#11044) [backport 2.13]

.gitignore
Those folders are required for tests/appsec/iast_packages/test_packages.py
- template_venv/
- cloned_venvs/
- …
=> chore(iast): update .gitignore

ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp, releasenotes/notes/profiling-stack-v2-endpoint-span-type-none-48a1196296be3742.yaml
Manual backport of #11164 to 2.13
Fixes #11141 …
=> fix(profiling): handle `Span`s with `None` span type for stack v2 endpoint profiling [backport 2.13]

ddtrace/internal/ci_visibility/git_client.py, tests/contrib/pytest/test_pytest.py
This makes sure that `CIVisibilityGitClient.upload_git_metadata()` does not cause a crash if the `git` binary is absent (which could happen after #11175).
It also fixes the `test_pytest_without_git_does_not_crash` test that allowed #11175 to slip through because, since the migration to GitLab, the overall environment in which tests ran is no longer in agentless mode, which meant `_should_upload_git_metadata()` was false, and effectively wasn't exercising `pytest` "without `git`".
There is no release note here since #11175 has not been released yet. The backports for that PR will be updated to cherry-pick this commit, so this PR is also not backported.
- The change …
=> chore(ci_visibility): fix inadequate pytest test and fix broken git check

ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt, ddtrace/internal/datadog/profiling/stack_v2/include/thread_span_links.hpp, ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/thread_span_links.cpp, ddtrace/internal/datadog/profiling/stack_v2/test/CMakeLists.txt, ddtrace/internal/datadog/profiling/stack_v2/test/thread_span_links.cpp, releasenotes/notes/profiling-fix-data-race-segfault-b14f59c06c6bf9ed.yaml
Backport 64b3374 from #11167 to 2.12.
The ThreadSpanLinks singleton holds the active span (if one exists) for
a given thread ID. The `get_active_span_from_thread_id` member function
returns a pointer to the active span for a thread. The `link_span`
member function sets the active span for a thread.
`get_active_span_from_thread_id` accesses the map of spans under a
mutex, but returns the pointer after releasing the mutex, meaning
`link_span` can modify the members of the Span while the caller of
`get_active_span_from_thread_id` is reading them.
Fix this by returning a copy of the `Span`. Use a `std::optional` to wrap
the return value of `get_active_span_from_thread_id`, rather than
returning a pointer. We want to tell whether or not there actually was a
span associated with the thread, but …
=> fix(profiling): fix data race when accessing span for thread [backport 2.12]

ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt, ddtrace/internal/datadog/profiling/stack_v2/include/thread_span_links.hpp, ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/thread_span_links.cpp, ddtrace/internal/datadog/profiling/stack_v2/test/CMakeLists.txt, ddtrace/internal/datadog/profiling/stack_v2/test/thread_span_links.cpp, releasenotes/notes/profiling-fix-data-race-segfault-b14f59c06c6bf9ed.yaml
Backport 64b3374 from #11167 to 2.13.
The ThreadSpanLinks singleton holds the active span (if one exists) for
a given thread ID. The `get_active_span_from_thread_id` member function
returns a pointer to the active span for a thread. The `link_span`
member function sets the active span for a thread.
`get_active_span_from_thread_id` accesses the map of spans under a
mutex, but returns the pointer after releasing the mutex, meaning
`link_span` can modify the members of the Span while the caller of
`get_active_span_from_thread_id` is reading them.
Fix this by returning a copy of the `Span`. Use a `std::optional` to wrap
the return value of `get_active_span_from_thread_id`, rather than
returning a pointer. We want to tell whether or not there actually was a
span associated with the thread, but …
=> fix(profiling): fix data race when accessing span for thread [backport 2.13]

ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt, ddtrace/internal/datadog/profiling/stack_v2/include/thread_span_links.hpp, ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/thread_span_links.cpp, ddtrace/internal/datadog/profiling/stack_v2/test/CMakeLists.txt, ddtrace/internal/datadog/profiling/stack_v2/test/thread_span_links.cpp, releasenotes/notes/profiling-fix-data-race-segfault-b14f59c06c6bf9ed.yaml
Backport 64b3374 from #11167 to 2.14.
The ThreadSpanLinks singleton holds the active span (if one exists) for
a given thread ID. The `get_active_span_from_thread_id` member function
returns a pointer to the active span for a thread. The `link_span`
member function sets the active span for a thread.
`get_active_span_from_thread_id` accesses the map of spans under a
mutex, but returns the pointer after releasing the mutex, meaning
`link_span` can modify the members of the Span while the caller of
`get_active_span_from_thread_id` is reading them.
Fix this by returning a copy of the `Span`. Use a `std::optional` to wrap
the return value of `get_active_span_from_thread_id`, rather than
returning a pointer. We want to tell whether or not there actually was a
span associated with the thread, but …
=> fix(profiling): fix data race when accessing span for thread [backport 2.14]

releasenotes/notes/ci_visibility-fix_codeowners_including_comments-82d9cb733a2c7285.yaml, releasenotes/notes/ci_visibility-fix_logged_errors_when_gitless-66a6cb3245314f3e.yaml
Release notes with `:` in them need to be entered as a block with `|`, otherwise the release script fails to parse it properly …
=> chore:  format release notes so the release script could parse

pyproject.toml
We need to use `guess-next-dev` for versioning for release branches in order to ensure that system tests can work with them.
This is a manual PR, but the goal is to automate this PR generation (probably in the `release.py` script)
**Great context from internal ticket:**
> Using "release-branch-semver" will allow the main branch to have its version computed from last tag adding +1 to minor and .dev decorator. This is what we want. The problem is that algorithm is used on any branch that is not a release branch. So it will also be used on any branch that targets a release branch, meaning all backport PRs.
>
> Using "guess-next-dev" will set any non release branch to the same minor version as last tag. This works for backport branches but not for main that will get the same minor version as …
=> chore: use `guess-next-dev` instead of `release-branch-semver` for versioning [2.16]

ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt, ddtrace/internal/datadog/profiling/stack_v2/include/thread_span_links.hpp, ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/thread_span_links.cpp, ddtrace/internal/datadog/profiling/stack_v2/test/CMakeLists.txt, ddtrace/internal/datadog/profiling/stack_v2/test/thread_span_links.cpp, releasenotes/notes/profiling-fix-data-race-segfault-b14f59c06c6bf9ed.yaml
Backport 64b3374 from #11167 to 2.15.
The ThreadSpanLinks singleton holds the active span (if one exists) for
a given thread ID. The `get_active_span_from_thread_id` member function
returns a pointer to the active span for a thread. The `link_span`
member function sets the active span for a thread.
`get_active_span_from_thread_id` accesses the map of spans under a
mutex, but returns the pointer after releasing the mutex, meaning
`link_span` can modify the members of the Span while the caller of
`get_active_span_from_thread_id` is reading them.
Fix this by returning a copy of the `Span`. Use a `std::optional` to wrap
the return value of `get_active_span_from_thread_id`, rather than
returning a pointer. We want to tell whether or not there actually was a
span associated with the thread, but …
=> fix(profiling): fix data race when accessing span for thread [backport 2.15]

.github/workflows/system-tests.yml
Recently, several error has been introduced in debuggers features, those errros has been caught by system-tests nightlies.
By adding those scenario in the dd-trace-py's CI, we'll prevent those errors to reach `main` branch.
Needs DataDog/system-tests#3354 …
=> chore: add debugger scenarios in system-tests ci

ddtrace/appsec/_iast/_ast/ast_patching.py, releasenotes/notes/iast-fi-import-error-google-37815bda58036c08.yaml, tests/appsec/iast_packages/packages/pkg_google_api_core.py, tests/appsec/iast_packages/test_packages.py
Backport e33e2355e97b2bbd40d4223bb6d0c79f8da5b8a4 from #11240 to 2.14.
This fix resolves an issue where importing the
``google.cloud.storage.batch`` module would fail raising an AttributeError
```
File "site-packages/google/auth/crypt/rsa.py", line 22, in <module>
RSASigner = _cryptography_rsa.RSASigner
^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'google.auth.crypt._cryptography_rsa' has no attribute 'RSASigner'
```
tests_packages are working in this branch:
https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/76358/workflows/427a6bbc-f088-4779-b6fd-35e8e6f988d5/jobs/4346061
- …
=> fix(iast): add google.auth to the IAST denylist [backport 2.14]

pyproject.toml
We need to use guess-next-dev for versioning for release branches in order to ensure that system tests can work with them.
This is a manual PR, but the goal is to automate this PR generation (probably in the release.py script)
Great context from internal ticket:
>
> Using "release-branch-semver" will allow the main branch to have its version computed from last tag adding +1 to minor and .dev decorator. This is what we want. The problem is that algorithm is used on any branch that is not a release branch. So it will also be used on any branch that targets a release branch, meaning all backport PRs.
>
> Using "guess-next-dev" will set any non release branch to the same minor version as last tag. This works for backport branches but not for main that will get the same minor version as last …
=> chore: use guess-next-dev instead of release-branch-semver for versioning [2.15]

ddtrace/internal/datadog/profiling/stack_v2/include/thread_span_links.hpp, ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp, tests/profiling/collector/pprof_utils.py, tests/profiling_v2/collector/test_stack.py
Manual backport of #11139 to 2.14, to facilitate backporting #11235 …
=> refactor(profiling): remove pytest.mark.subprocess from v2/test_stack.py [backport 2.14]

ddtrace/internal/datadog/profiling/stack_v2/include/thread_span_links.hpp, ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp, tests/profiling/collector/pprof_utils.py, tests/profiling_v2/collector/test_stack.py
Manual backport of https://github.com/DataDog/dd-trace-py/pull/11139 to 2.15, to facilitate backporting https://github.com/DataDog/dd-trace-py/pull/11235
- All changes …
=> refactor(profiling): remove pytest.mark.subprocess from v2/test_stack.py [backport 2.15]

.github/workflows/build_python_3.yml
Addresses https://github.com/actions/runner-images/issues/10721 deprecating macos-12 images. …
=> chore(ci): stop using macos 12

.github/workflows/test_frameworks.yml
The old cache action uses node 16 and causes deprecation warnings. …
=> ci: make fastapi test framework use newer cache action

tests/conftest.py
Only Linux is supported right now, but we have some tests that run on Windows and MacOS. …
=> test: only auto-enable crashtracking in tests on linux

ddtrace/appsec/_iast/_ast/ast_patching.py, releasenotes/notes/google-sdk-denylist-0619f1734507019a.yaml
=> fix(iast): add google.auth and googlecloudsdk to the IAST denylist

ddtrace/llmobs/_evaluators/ragas/faithfulness.py, ddtrace/llmobs/_evaluators/runner.py, ddtrace/llmobs/_evaluators/sampler.py
We started to see typing check failures in the `pre_check` test. This was probably due to side effects that were uncaught from not requiring branches to be updated with main before merging. This PR aims to fix the issue that the typing check is complaining about, but the actual fix to prevent this will be to require main updates on branches before merging (this is already done if using the merge queue, but not manual merges). …
=> chore(ci): remove unused type ignore comments

.gitlab-ci.yml, .gitlab/requirements_allow.json, .gitlab/requirements_block.json, lib-injection/sources/requirements.json, releasenotes/notes/add-requirements-json-038073d722697e32.yaml
Adds the `requirements.json` implementation for SSI.
Ensures we bail-out of instrumentation when the machine doesn't meet the glibc requirements.
Tests are handled by the onepipeline, they're essentially unit tests, but are sufficient for now - onboarding tests will handle the "integration test" aspect in due course.
I'm not sure if this needs backporting or not, will defer to you.
https://datadoghq.atlassian.net/browse/APMLP-134 …
=> feat(lib-injection): add SSI denylist using requirements.json

ddtrace/profiling/collector/threading.py, releasenotes/notes/profiling-gunicorn-track-06a211fc1e2643e1.yaml, tests/profiling/collector/pprof_utils.py, tests/profiling/gunicorn-app.py, tests/profiling_v2/collector/test_stack.py, tests/profiling_v2/test_gunicorn.py
Manual backport of #11300 to 2.14
See the following screenshot for cpu profile before and after this change for a service using gunicorn. …
=> fix(profiling): stack v2 tracks threads in gunicorn workers [backport 2.14]

ddtrace/internal/datadog/profiling/dd_wrapper/src/sample_manager.cpp, releasenotes/notes/profiling-sample-pool-461a108e068dea5b.yaml
Tested with native tests
`crossbeam::ArrayQueue` uses Rust `std::sync::atomic` which doesn't seem to be consistent across `fork()` calls as `std::mutex` from C++ isn't. So we need to make sure, an equivalent of `std::mutex::unlock()` happens after fork.  …
=> fix(profiling): clear sample pool after fork

.github/workflows/django-overhead-profile.yml
We run the Django overhead profile job with the profiler enabled and profile both stack v1 and v2.
- Avoids …
=> ci(profiling): v1/v2 matrix in Django overhead job

CHANGELOG.md
Fix two codespell errors in the changelog. These pre-existing errors were blocking new release note generation after enforcing stricter codespell checks.
- All changes …
=> chore: fix codespell errors in changelog

ddtrace/profiling/collector/_lock.py, releasenotes/notes/profiling-reduce-lock-profiler-log-spam-5931d957ff1becd4.yaml
The lock profiler would log a warning if it couldn't determine a
name for a lock, and it would try determining a name multiple times for
the same lock.  This lead to excessive log spam. Downgrade this to a
debug log and only try to determine the name once. …
=> fix(profiling): reduce lock profiler log spam

.gitlab/download-wheels-from-gh-actions.sh, ddtrace/internal/ci_visibility/telemetry/git.py
We reduce the number of requests to the GitHub API made by the GitLab wheel download workflow to reduce the chances of going over the request rate limit. We also make sure that the job re-runs reactively when the GitHub workflow has completed. …
=> ci: reduce API requests in download wheel job

ddtrace/llmobs/_writer.py
This PR adds a `_dd.tracer_version` field to the span payload at the LLMObs writer level. This is only meant to be used internally by the LLMObs team. …
=> chore(llmobs): add tracer version field to llmobs span payload

ddtrace/internal/coverage/instrumentation_py3_10.py, tests/ci_visibility/test_ci_visibility.py, tests/coverage/included_path/async_code.py, tests/coverage/test_coverage_async.py
The code coverage for Python 3.10 has an implicit assumption that the first bytecode offset matches the first line number in the line table, which is wrong because some instructions may not have line numbers. This PR changes it so that the first line number is the code object's first line number attribute, so that it will work even if no line-starting offsets have been seen before.
- The change follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes …
=> chore(ci_visibility): fix line numbers in Python 3.10 code coverage instrumentation

ddtrace/contrib/trace_utils.py, releasenotes/notes/remove_x-forwarded_from_ip_resolution-d63292c0fda42dd9.yaml, tests/tracer/test_trace_utils.py
Removed x-forwarded from headers used for client IP resolution (but not from collected headers).
We lack evidence of actual usage, and whether this should follow RFC 7239 or regular XFF list format.
Also:
- add unit test for priority over all ip headers. check that x-forwarded is now ignored.
APPSEC-55824 …
=> chore(tracer): remove x-forwarded from ip resolution

.circleci/config.templ.yml, tests/appsec/integrations/test_flask_entrypoint_iast_patches.py
1. Increase parallelism to reduce the time to run the suite, there are 13 riot hashes. Each job takes about 30 minutes, where 10 minutes spent for building dd-trace-py and the rest spent for running 2 riot hashes. 
3. Mark a test flaky, it failed 3 times in a row for an unrelated change [ci(profiling): explicitly set cpucount for uwsgi build](https://github.com/DataDog/dd-trace-py/pull/11402), [run 1](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/77339/workflows/b138b8df-bdb5-4cfc-a6ae-e8d8f204661b/jobs/4357608), [run 2](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/77339/workflows/8e33c607-89cb-4bab-89b1-acb6d0931856/jobs/4357577), [run 3](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/77339/workflows/b5609072-9b15-4c46-ae11-10c7c0039ada/jobs …
=> ci(asm): appsec_integrations suite improvments

.github/workflows/generate-package-versions.yml
In the auto-generated PRs generated by the [Generate Package Versions](https://github.com/DataDog/dd-trace-py/actions/workflows/generate-package-versions.yml) workflow, some of the modified files might not directly update the selected package to `latest`. Not all lockfiles for a given `venv` will use the `venv` `latest`, but the workflow also updates dependency versions.
This PR modifies the body of the generated PRs for better clarification. Example: #11354
- The change follows the [library …
=> chore(ci): update description of generate package workflow

ddtrace/_trace/_span_pointer.py, ddtrace/_trace/telemetry.py, ddtrace/_trace/utils_botocore/span_pointers/__init__.py, ddtrace/_trace/utils_botocore/span_pointers/dynamodb.py, ddtrace/_trace/utils_botocore/span_pointers/s3.py, ddtrace/_trace/utils_botocore/span_pointers/telemetry.py, releasenotes/notes/reduce-span-pointer-noise-e1cf01ec581a409c.yaml, tests/tracer/test_telemetry.py, tests/tracer/utils_botocore/test_span_pointers.py
Span pointer issues should be debug messages rather than warnings since they are not really actionable from the perspective of our users.
We'd also like to have some instrumentation telemetry to see how the logic is doing. …
=> fix(botocore): [SVLS-5973] less noisy span pointers

ddtrace/appsec/rules.json, releasenotes/notes/waf_update_to_1.21.0-2f77adaf9ecce679.yaml, setup.py, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Update libddwaf to 1.21.0
Update security rule file to 1.13.3
Update snapshots accordingly
APPSEC-55919
- …
=> chore(asm): updates waf and security rules

ddtrace/appsec/_constants.py, ddtrace/appsec/_iast/_iast_request_context.py, ddtrace/appsec/_iast/_metrics.py, ddtrace/appsec/_iast/_taint_tracking/__init__.py, tests/appsec/iast/test_telemetry.py
- Attach execute source in the span metrics
- Refactor IAST span metrics to use iast context instead of a global variable …
=> feat: iast execute source metric

src/core/Cargo.lock, src/core/Cargo.toml
Overdue to stop referencing a specific commit rather than a release tag. …
=> chore: upgrade ddsketch/libdatadog to v14.1.0

ddtrace/_trace/processor/__init__.py, releasenotes/notes/fix_asm_standalone_span_tag-60b38c1d9d2efbaa.yaml
This fix resolves a possibly missing ASM standalone tag on root spans.
It was only detected previously on uwsgi on nightly system tests.
- ensure that all root spans are tagged.
APPSEC-55222 …
=> fix(asm): standalone missing tag

ddtrace/profiling/collector/_utils.h
We use `PyMem_Raw*` functions for allocating memory for some of the memory
profiling data structures. However, the array implementation uses
`PyMem_Free` to free the associated memory. This isn't necessarily causing
problems, since the Python object allocator has safeguards to fall back
to `PyMem_RawFree` if it gets a pointer it didn't allocate. But it does
mean that those frees are going through our heap tracker code. And it
can also skew runtime allocation statistics. So just use the right free
function.
Other things to consider: just use plain malloc/realloc/free? Or switch
to C++/Rust for this code and use more proper dynamic array
implementaitons? The preprocessor stuff is a little scary, and C++
templates/Rust generics are a little less scary :)
- The PR description includes an …
=> chore(profiling): use raw allocator free for traceback buffers

ddtrace/internal/ci_visibility/recorder.py, releasenotes/notes/ci_visibility-get_agent_default_env-bf4a11283dccdf87.yaml, tests/ci_visibility/api_client/test_ci_visibility_api_client.py
This fixes an issue where, if we are in EVP mode, and the agent has a custom default environment set (eg: using `DD_APM_ENV`), but `DD_ENV` is not set in the environment, we would incorrectly set the environment to `None`.
Instead, we now query the agent's info page and use the `config.default_env` key to choose the environment value.
In somewhat-related changes, we now also explicitly default the environment to `"none"` in agentless mode if it is not set by the user, whereas before we would use a `None` value which would serialize to `null`, and we would rely on the backend to perform the `null` -> `"none"` change. Since the backend was already enforcing this behavior, it should be a no-op from the user's perspective.
- The PR …
=> fix(ci_visibility): get default environment from agent when DD_ENV is not set

ddtrace/contrib/pytest/_retry_utils.py, ddtrace/contrib/pytest/_types.py
In versions > 7.4 of `pytest`, the `tmppath_result_key` key may be stashed on items, which means it needs to be reinstantiated if we retry it.
- All changes are related …
=> chore(ci_visibility): reset tmppath_result_key fixture if need be

setup.py
https://github.com/DataDog/dd-trace-py/commit/83ded1333930e17a87f88c2d81efa02401d526e2
bumped rust min version to 1.76.0 …
=> chore(ci): update rust min version

lib-injection/sources/sitecustomize.py, releasenotes/notes/fix-lib-injection-user-sitecustomize-4ebc76e1b722490f.yaml
Right now we do not preserve any user defined `sitecustomize.py`.
In theory we should be because we `import ddtrace.bootstrap.sitecustomize` which has this logic built-in, but only if the `.../site-packages/ddtrace/bootstrap/` directory exists in the `sys.path`.
The fix here is easy, that we ensure that the `ddtrace/bootstrap` directory is added to the `sys.path` first before `import ddtrace.bootstrap.sitecustomize`. …
=> fix(lib-injection): ensure any user defined sitecustomize.py is loaded after injection

ddtrace/settings/_otel_remapper.py
The namespace for otel metrics should be "tracers" and not "tracer". 
This regression was caught by system tests: https://github.com/DataDog/system-tests/pull/3497. No additional tests are required. 
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backp …
=> chore(telemetry): fix namespace on otel metrics

ddtrace/internal/ci_visibility/_api_client.py, ddtrace/internal/ci_visibility/recorder.py, ddtrace/internal/ci_visibility/telemetry/early_flake_detection.py, ddtrace/internal/ci_visibility/telemetry/events.py, ddtrace/internal/ci_visibility/telemetry/git.py, ddtrace/internal/ci_visibility/utils.py
This fixes some internal telemetry that was using enum names instead of their value, which was creating metrics or tags with the wrong names. …
=> chore(ci_visibility): fix telemetry for events and API requests

ddtrace/debugging/_origin/span.py, ddtrace/internal/packages.py
The creation of Path objects in CPython < 3.11 is known to be slow and inefficient. We implement an overload of the helper function that takes a plain string as argument and caches the results to avoid creating Path objects repeatedly. …
=> perf(cos): cache user code checks

ddtrace/_trace/utils_botocore/span_pointers/dynamodb.py
Unfortunately the config is pretty far away from where we actually use it (since we don't always need to use it). This creates an implicit link between the configuration and the error messaging. But the alternative (feeding the config language down through the stacks, either as a separate parameter or as bundled object for the `dynamodb_primary_key_names_for_tables` variable) seems a bit too heavy-handed unless we absolutely need to do it that way. …
=> chore: improve dynamodb pointer config discoverability

ddtrace/_trace/telemetry.py
This metric is currently generating invalid payloads and is being dropped by the tracer-telemetry-intake service. …
=> chore(telemetry): fixes namespace for span pointer metric

hatch.toml
httpx 0.28.0 is breaking our tests. This PR pins httpx version for fastapi threat tests. …
=> ci(asm): fix fastapi tests

.circleci/config.templ.yml, .github/workflows/requirements-locks.yml, .gitlab/testrunner.yml, .gitlab/tests.yml, docker-compose.yml
This updates the image to the one built in 47c7b5287da25643e46652e6d222a40a52f2382a , with:
- fixed MariaDB repo
- new `azure-functions-core-tools-4` for serverless 
- new `google-chrome-stable` installation to support the Selenium contrib
Additionally, it switches all references to image to include the `label@digest` syntax in order to make easier to:
- know which commit an image comes from
- keep the digest in order to disambiguate any potential case where the same label has different digests 
- Newly-added code is easy to …
=> ci: update image and standardize to using both hash and sha256

ddtrace/internal/datadog/profiling/build_standalone.sh
=> chore(profiling): use clang when --safety is set

ddtrace/internal/datadog/profiling/dd_wrapper/include/profile.hpp, ddtrace/internal/datadog/profiling/dd_wrapper/include/sample.hpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/profile.cpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/sample.cpp, releasenotes/notes/profiling-fix-unbounded-string-buffer-d18056263f3e4bdc.yaml
Profiler samples typically contain several strings, for sample labels
(task name, endpoint/resource, etc) and frame info. Those strings tend
to be repeated. We build samples across several API calls, from Python,
Cython, C Python extensions, and C++ code, making it hard to reason
about the lifetimes of the strings we get. So, it's easier to just copy
the strings we need while building a sample. And it's preferably to only
store one copy. So, our libdatadog wrapper uses a string table, which
addresses both of these concerns. However, nothing is ever removed from
the table. And some things like task names can have new values each
time, meaning we have unbounded memory growth.
I previously tried to fix this by periodically clearing the string
table. However, this comes with its own new …
=> fix(profiling): get rid of leaky string table

.github/workflows/build-and-publish-image.yml, .github/workflows/build_deploy.yml, .github/workflows/build_python_3.yml, .github/workflows/changelog.yml, .github/workflows/codeowners.yml, .github/workflows/codeql-analysis.yml, .github/workflows/django-overhead-profile.yml, .github/workflows/encoders-profile.yml, .github/workflows/flask-overhead-profile.yml, .github/workflows/generate-package-versions.yml, .github/workflows/pr-name.yml, .github/workflows/requirements-locks.yml, .github/workflows/rust-ci.yml, .github/workflows/set-target-milestone.yml, .github/workflows/system-tests.yml, .github/workflows/test_frameworks.yml, .github/workflows/test_lib_injection.yml, .github/workflows/unit_tests.yml, .github/workflows/upstream-issues.yml
Found via [zizmor](https://woodruffw.github.io/zizmor/audits/#artipacked).
I also included one template expansion change as well. …
=> ci: do not persiste git credentials in GitHub Actions

releasenotes/notes/fix-profiler-int-ptr-conversion-4377fbd8724eeaec.yaml, setup.py
The root issue is that
* Alpine 3.21.0 was released on Dec 5
* Alpine 3.21.0 includes an update to gcc (gcc 14)
* gcc 14 is more strict (yay!) about pointer<->integer conversions.  However, cython does not generate code with the proper incantation to avoid compiler errors (I blame pthreads having opaque pointer types)
* Subsequently, any and every python-alpine container image (even and especially patch versions) cut after Dec 5 will have the updated Alpine image, which will have the updated gcc, which will start to break during builds.
This PR effectively undoes the gcc 14 behavior by making int<->ptr conversions less strict again (only for the stack.c cython-generated file which is currently throwing the error).
- The PR …
=> fix(setup): suppress int-ptr conversion errors for stack profiler v1

ddtrace/llmobs/_integrations/langchain.py
This PR updates the Langchain integration to handle LLM calls instrumented in the Vertex AI and Gemini integrations by checking for their respective provider names (`vertexai` and `google_palm`) and instrumenting the wrapper Langchain calls as workflow spans if these provider names are detected.
Importantly, because of the way Langchain invokes chat generations for Vertex AI and Gemini, our integrations will not capture these inner LLM calls (in both cases, the prediction client is called directly with the input instead of using the `chat.send_message` method which we have instrumented in both cases). Therefore, we will only capture the Langchain LLM call and hence leave it as an LLM span for chat generations. 
As we work on a more stable way to test our langchain integration, I opted to …
=> feat(langchain): [MLOB-1972] update langchain to handle vertex and gemini llm calls

.github/workflows/system-tests.yml, ddtrace/internal/datadog/profiling/dd_wrapper/include/uploader.hpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp, tests/profiling_v2/collector/test_threading.py
Reverts DataDog/dd-trace-py#11644 and fix tsan errors …
=> chore(profiling): revert simplify usage of cancellation token

ddtrace/debugging/_uploader.py, ddtrace/internal/http.py, ddtrace/internal/processor/stats.py, ddtrace/internal/remoteconfig/client.py, ddtrace/internal/runtime/container.py, ddtrace/internal/telemetry/writer.py, ddtrace/internal/uds.py, ddtrace/internal/utils/__init__.py, ddtrace/internal/writer/writer.py, ddtrace/profiling/exporter/http.py, tests/tracer/runtime/test_container.py
We encapsulate the logic required to add container information headers to HTTP requests in the connection constructor. This elimiates the need to add the same logic across all products/services that make requests.
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contribut …
=> refactor: encapsulate container info

ddtrace/profiling/collector/_lock.py, ddtrace/profiling/collector/asyncio.py, ddtrace/profiling/collector/threading.py, tests/profiling/collector/test_threading.py, tests/profiling_v2/collector/test_threading.py
This is just a hygiene PR to clarify the implementation of the lock collector. …
=> chore(profiling): tweak lock collector impl for clarity

ddtrace/contrib/pytest/_plugin_v2.py, ddtrace/internal/ci_visibility/recorder.py
This fixes an issue in the new version of the `pytest` plugin where `CODEOWNERS` parsing was incorrect due to the plugin sending absolute paths instead of paths relative to the repo root.
- …
=> chore(ci_visibility): make codeowners file relative to repo path

ddtrace/internal/datadog/profiling/ddup/_ddup.pyi, ddtrace/internal/datadog/profiling/ddup/_ddup.pyx, ddtrace/profiling/profiler.py, ddtrace/profiling/scheduler.py, tests/profiling_v2/collector/test_asyncio.py, tests/profiling_v2/collector/test_stack.py, tests/profiling_v2/collector/test_threading.py
profiling tests that check for span ids are flaky. I wonder whether sharing tracer instance across tests causes that problem.  …
=> chore(profiling): ddup.upload() optionally gets tracer object

.gitlab-ci.yml
Enable Quality Gates to prevent new flaky tests from being merged into main or release branches.
Example branches: 
https://github.com/DataDog/dd-trace-py/tree/erikayasuda/qg-simple-delayed-fix
https://github.com/DataDog/dd-trace-py/tree/erikayasuda/qg-simple-quick-fix …
=> chore(ci): enable quality gates

scripts/needs_testrun.py
`record_mode="all"` is great for the first run to collect all requests, but `none` is better since it'll block any unknown requests. …
=> ci: fix needs_testrun tests. do not record all requests

hatch.toml, scripts/needs_testrun.py, scripts/run-test-suite, scripts/run-test-suite-hatch
This will fix issues like: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/79203/workflows/9f43a358-af41-4d77-8b7b-c931654756d5/jobs/4383102?invite=true#step-108-449_45
> ModuleNotFoundError: No module named 'ruamel' …
=> ci: use hatch to execute needs_testrun.py

.github/workflows/build_deploy.yml
python 3.7 is no longer supported on ubuntu.
This PR update the python version for the build action to 3.12
- …
=> chore(ci): upgrade python for build action

tests/contrib/elasticsearch/test_elasticsearch.py
Previously we would wait up to 20 seconds to Elasticsearch to start, apparently OpenSearch might need longer to start up. So we are updating the logic to wait up to 160 seconds with 2 second sleeps between checks.
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contribut …
=> ci: wait longer for opensearch to start

pyproject.toml
This PR updates the `version_schema` in the `../pyproject.toml` file for the 2.18 release branch from `release-branch-semver` to `guess-next-dev`. This is to ensure that system tests work as intended with backports to this release branch.
IMPORTANT: This PR needs to be merged before the first backport is created for 2.18.Otherwise, system tests will not work as expected.
=> chore: use guess-next-dev instead of release-branch-semver [2.18]

ddtrace/llmobs/_integrations/base.py, ddtrace/llmobs/_integrations/bedrock.py, ddtrace/llmobs/_llmobs.py
This PR makes a small revert to #11543 where accessing propagated parent IDs (for distributed tracing) were unwittingly changed to access via the span store object, even though automatic context propagation results are always added to the span as tags (not the store).
While all other LLMObs SDK data is added/accessed via the span store, `_dd.p.llmobs_parent_id` is automatically added by the tracer internals so we'll continue using this for now until our overall context management solution removes this problem entirely.
- …
=> chore(llmobs): ensure propagated parent IDs are still using span tags

ddtrace/contrib/pytest/_plugin_v2.py, ddtrace/contrib/pytest/_pytest_bdd_subplugin.py, ddtrace/contrib/pytest_bdd/plugin.py, ddtrace/internal/ci_visibility/api/_test.py, ddtrace/internal/ci_visibility/recorder.py, ddtrace/internal/test_visibility/api.py, riotfile.py, tests/contrib/pytest_bdd/test_pytest_bdd.py
This adds support for the `pytest-bdd` plugin to the new version of the `pytest` plugin, bypassing the `ddtrace.pytest_bdd` plugin and instantiating a "subplugin" on demand when `pytest-bdd` is detected and `ddtrace` is enabled.
To support the way the legacy `pytest-bdd` plugin worked, new functionality is added:
- `InternalTestSession.get_tracer()` to have access to the tracer used by Test Visibility
- `InternalTest.overwrite_attributes()` to allow overwriting attributes that have already been set (or in the case of the `suite` name, that are automatically set based on test hierarchy)
- The PR …
=> chore(ci_visibility): add support for pytest_bdd to v2 plugin

ddtrace/appsec/_common_module_patches.py, releasenotes/notes/iast-fix-iast-propagation-error-2-ba4a998133269a7c.yaml
This fix resolves an issue where AppSec was using a patched request and builtins functions,  creating telemetry errors. …
=> fix(iast): check context is enable in request and builtins patched funcions

ddtrace/debugging/_function/discovery.py
We make sure to cache the result of the function code pair resolution for subsequent calls. …
=> chore(di): cache function code pair resolution

.github/workflows/generate-package-versions.yml
`ubuntu-latest` was upgraded to use `ubuntu-24.04`. This is incompatible with `python 3.7`, which we still test and support (and is needed for the `Generate Package Versions` workflow in order to build all the riot environments). 
This PR switches to using the `ubuntu-22.04` image (the previous latest). When we drop 3.7 support, we can switch back to `ubuntu-latest`. 
- The …
=> chore(ci): switch ubuntu runner image in generate package versions workflow

tests/contrib/celery/test_tagging.py
This job is currently experience issues timing out. It is not 100% clear why it is timing out with a 2 second timeout, but increasing to a higher timeout should help when run under high load/resource constraints.
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributi …
=> ci(celery): increase amqp task timeout

.github/workflows/system-tests.yml
CI: Enables [system tests for Standalone SCA billing](https://github.com/DataDog/system-tests/pull/3690) to run on dd-trace-py's CI …
=> ci: enable standalone sca system tests

ddtrace/debugging/_exception/replay.py
We correct the name of the field that is expected to carry the exception ID. …
=> chore(er): correct exception ID field name

.gitlab-ci.yml
The datadog-ci binary is in beta and has known segfaults, this is blocking our CI from completing successfully, even when gates do not fail. …
=> ci: do not use datadog-ci binary

ddtrace/debugging/_signal/utils.py, tests/debugging/exception/test_replay.py, tests/debugging/test_debugger.py, tests/debugging/test_encoding.py
We augment the exception fields with known exception chaining attributes to allow capturing exception chaining relations. The fields need to be added manually because they are part of the BaseException built-in fields and are not included in the object's __dict__ attribute. …
=> chore(di): capture exception chain

ddtrace/debugging/_exception/replay.py
We include the span tag that carries the exception hash, according to the RFC. …
=> chore(er): include exception hash

ddtrace/_monkey.py, releasenotes/notes/refactor-patch-error-ssi-1a2e9fe206d6d6df.yaml, tests/telemetry/test_telemetry.py
- Improves the error message generated when `ddtrace` failed to patch/enable an integration. 
- Ensure patching modules and sub-modules are wrapped in a try-except. The ddtrace library should not crash an application if an integration can not be patched.
Prevent issues like this: https://github.com/DataDog/dd-trace-py/issues/11603 …
=> fix(library): catch exceptions raised while enabling ddtrace integrations

.gitlab/package.yml, .gitlab/tests.yml, hatch.toml, scripts/gen_gitlab_config.py, tests/suitespec.yml
- Remove redundant `build_base_venvs`
- not needed by any downstream jobs, we have to re-do this in the tests-gen pipeline anyways
- Move conftest hatch job from precheck to hatch stage
- hatch jobs that have to install dev take a long time to run 6+ mins
- Remove redundant `.testrunner` definition, and need for injecting `services.yml` into `tests.yml` template
- The change …
=> ci: optimize ci runtime

ddtrace/internal/datadog/profiling/dd_wrapper/include/uploader_builder.hpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/code_provenance.cpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/ddup_interface.cpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/profile.cpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/sample.cpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader_builder.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/sampler.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/thread_span_links.cpp, releasenotes/notes/fix-profiling-native-mutices-62440b5a3d9d6c4b.yaml
=> fix(profiling): reset all profiling c++ mutexes on fork [backport 2.18] (#11768)

scripts/gen_circleci_config.py
This reverts commit fb82c64f516048e7146ce6a5bcd8961a6cded29a.
[This merge commit](https://github.com/DataDog/dd-trace-py/commit/fb82c64f516048e7146ce6a5bcd8961a6cded29a)
seems to have broken the suite-selection mechanism in CircleCI ([example](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/79433/workflows/cc067cf4-bb45-4f8d-8a60-f43e95041847))
- The change …
=> ci: revert CI fix

.github/workflows/build_deploy.yml
Backport https://github.com/DataDog/dd-trace-py/commit/073f7f5e0dcb620d10e85e63c2dbc0974a697280 from https://github.com/DataDog/dd-trace-py/pull/11735 to 2.17.
python 3.7 is no longer supported on ubuntu.
This PR update the python version for the build action to 3.12 …
=> chore(ci): upgrade python for build action [backport 2.17]

.github/workflows/build_deploy.yml
Backport https://github.com/DataDog/dd-trace-py/commit/073f7f5e0dcb620d10e85e63c2dbc0974a697280 from https://github.com/DataDog/dd-trace-py/pull/11735 to 2.16.
python 3.7 is no longer supported on ubuntu.
This PR update the python version for the build action to 3.12 …
=> chore(ci): upgrade python for build action [backport 2.16]

.gitlab/services.yml, tests/contrib/gevent/test_tracer.py, tests/contrib/suitespec.yml
This job can fail with exit code `-11`, but no additional context is provided, likely because there isn't anything on `stderr` ?
This updates the job to output stderr and stdout when the resulting process signal is not `0`.
I was unable to reproduce the issue locally, so this is an attempt to collect more data when it fails on CI.
Example failure:
```
>       assert p.returncode == 0, stderr.decode()
E       AssertionError: 
E       assert -11 == 0
E        +  where -11 = <subprocess.Popen object at 0x7f3144d97eb0>.returncode
```
- The PR description notes risks associated with the change, if …
=> ci(gevent): improve ddtrace-run test assertion message

docs/configuration.rst
These are defined in the corporate docs, so we should just keep them there as the source of truth. The link to the corporate docs has also been added here.
See generated docs for this branch [here](https://ddtrace.readthedocs.io/en/erikayasuda-remove-dd-trace-enabled/configuration.html) …
=> chore(docs): remove `DD_TRACE_ENABLED` from configuration docs

pyproject.toml
This PR updates the `version_schema` in the `../pyproject.toml` file for the 2.19 release branch from `release-branch-semver` to `guess-next-dev`. This is to ensure that system tests work as intended with backports to this release branch.
IMPORTANT: This PR needs to be merged before the first backport is created for 2.19.Otherwise, system tests will not work as expected.
=> chore: use guess-next-dev instead of release-branch-semver [2.19]

ddtrace/contrib/internal/asgi/middleware.py, releasenotes/notes/iast-fix-awsgi-368c173e1f012400.yaml, tests/contrib/asgi/test_asgi.py
This fix resolves an issue parsing response cookies in FastAPI and awsgi
issue: https://github.com/DataDog/dd-trace-py/issues/11818 …
=> fix: error parsing response cookies in FastAPI and awsgi

ddtrace/contrib/internal/django/patch.py, releasenotes/notes/django-cache-service-name-schematization-bef19b44b7414016.yaml, tests/contrib/django/test_django.py
Currently, we treat django caching as a separate service.
This is a quick fix so that behavior aligns with our public docs; inferred services connected to django should be directly connected to the third-party service not django. 
The service name should adhere to the name rule from `schematize_service_name` rather than `django`. …
=> fix: add schematize service name for django caching

ddtrace/profiling/collector/_memalloc.c, ddtrace/profiling/collector/_memalloc_heap.c, ddtrace/profiling/collector/_memalloc_reentrant.h, releasenotes/notes/profiling-remove-getpid-from-memalloc-74f54043accdfc9e.yaml
memalloc uses getpid to detect whether the process has forked, so that
we can unlock the memalloc lock in the child process (if it isn't
already locked). Unfortunately the getpid call is quite slow. From the
man page: "calls to getpid() always invoke the actual system call,
rather than returning a cached value." Furthermore, we _always_ attempt
to take the lock for allocations, even if we aren't going to sample
them. So this is basically adding a syscall to every allocation.
Move this logic out of the allocation path. Switch to using
pthread_atfork handlers to ensure that the lock is held prior to
forking, and unlock it in the parent and child after forking. This
(maybe) has the added benefit of making sure the data structures are in
a consistent state in the child process after forking. …
=> fix(profiling): remove slow getpid call from memalloc path

scripts/freshvenvs.py
Fix to skip over pinned packages when selecting modules to update. This logic was accidentally removed in #11372  …
=> chore(ci): exclude pinned packages from auto-updating requirements

ddtrace/profiling/collector/_memalloc.c, ddtrace/profiling/collector/_memalloc_debug.h, ddtrace/profiling/collector/_memalloc_heap.c
The allocation profiler functions should (in theory) only be called when
allocating Python objects, which should (in theory) only be done with
the GIL held. We have reason to believe that this code is sometimes
reached without the GIL held, since some crashes in the code seem to go
away with our own locking. Add a debug flag,
`_DD_PROFILING_MEMALLOC_CRASH_ON_NO_GIL`, that when set will make the
profiler crash if it detects the GIL is not held in places where we
think it ought to be.
- The …
=> refactor(profiling): add debug check that the GIL is held to memalloc

tests/tracer/test_span.py
Under newer Python versions we sometimes get tracebacks that contain pointers, we need to account for these in the assertion.
```
File "dd-trace-py/tests/tracer/test_span.py", line 279, in test_custom_traceback_size_with_error
wrapper()
~~~~~~~^^
File "dd-trace-py/tests/tracer/test_span.py", line 276, in wrapper
divide_by_zero()
~~~~~~~~~~~~~~^^
ZeroDivisionError: division by zero
``` …
=> ci: fix flaky test_custom_traceback_size_with_error on Python 3.13

tests/contrib/elasticsearch/test_elasticsearch.py
It seems sometimes we don't have the index/mapping set up properly. I didn't try to dig into why since it shouldn't matter too much for this specific test case anyways.
The solution is in the query to specify the type of the `name` field if it is unmapped. …
=> ci: fix flaky es search query

scripts/gen_circleci_config.py
We fix a residual issue in #11668 whereby no suites where actually dynamically selected for CircleCI.
- Avoids …
=> ci: fix CircleCI dynamic job selection

tests/llmobs/conftest.py, tests/llmobs/test_llmobs_decorators.py, tests/llmobs/test_llmobs_evaluator_runner.py, tests/llmobs/test_llmobs_ragas_faithfulness_evaluator.py, tests/llmobs/test_llmobs_service.py, tests/llmobs/test_propagation.py
Follow up of #11781 to further clean up LLMObs tests, specifically replacing potentially flaky LLMObs span writer mocks and assertions with the test LLMObsSpanWriter dummy class. Also clean up the `tests/llmobs/conftest.py` file which previously contained a ton of rarely used and sometimes redundant fixtures. …
=> chore(llmobs): assert using span events instead of mocks

ddtrace/llmobs/_llmobs.py, releasenotes/notes/fix-llmobs-default-writer-hooks-5e456c2f7dfd4381.yaml, tests/llmobs/test_llmobs_service.py
Follow up on #11781 to fix a weird duplicate span writing issue with the new listener hook logic.
Since we were registering these hooks on `LLMObs.__init__()` which also happens at startup (as we create a default LLMObs() instance) as well as on `LLMObs.enable()`, we were double registering these hooks, and the default LLMObsSpanWriter was still saved and called each time the tracer finished a span. A symptom of this issue is that if a user was to manually enable agentless mode, they would see noisy logs indicating a failure to send spans to the agent proxy endpoint (which is the default writer mode) even though they also submitted spans to the agentless endpoint succesfully.
This fix resolves the issue by moving the hook registering to `LLMObs.enable()`, and adding corresponding logic to …
=> fix(llmobs): move listener hooks to enable instead of on init

ddtrace/debugging/_safety.py, releasenotes/notes/fix-er-include-nonlocals-bbeecfbbbde35496.yaml, tests/debugging/exception/test_replay.py, tests/debugging/test_safety.py
We include nonlocal variables in snapshots to provide for better visibility into exception occurrences.
- …
=> fix(er): include nonlocals in snapshots

ddtrace/profiling/collector/_lock.py, releasenotes/notes/profiling-lock-acquired-at-remove-c8b5b96130a46ca8.yaml
=> fix(profiling): remove `_self_acquired_at` after use

ddtrace/contrib/internal/botocore/services/bedrock.py, docs/spelling_wordlist.txt, releasenotes/notes/fix-bedrock-model-id-parsing-611aea2ca2e00656.yaml, tests/contrib/botocore/bedrock_cassettes/amazon_invoke_model_arn.yaml, tests/contrib/botocore/test_bedrock.py, tests/snapshots/tests.contrib.botocore.test_bedrock.test_invoke_model_using_aws_arn_model_id.json
This PR fixes the model ID parsing in the bedrock integration to additionally accept model IDs in AWS ARN format.
Previously bedrock only worked with base/foundation models which were of the format `{model_provider}.{model_name}`. However now [bedrock](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_InvokeModel.html#API_runtime_InvokeModel_RequestSyntax) has expanded to allow custom/provisioned/imported/prompt/inference/sagemaker models, following the typical AWS ARN format:
```
Base model: "{model_provider}.{model_name}"
Cross-region model: "{region}.{model_provider}.{model_name}"
AWS ARNs: Prefixed by "arn:aws{+region?}:bedrock:{region}:{account-id}:"
a. Foundation model: ARN prefix + "foundation-model/{region?}.{model_provider}.{model_name}"
b. Custom model: ARN …
```
=> fix(botocore): accept AWS ARN bedrock model IDs

.gitlab-ci.yml, .gitlab/testrunner.yml, .gitlab/tests.yml
=> chore(ci): new testrunner for check_new_flaky_tests [2.17]

ddtrace/appsec/_iast/_handlers.py, tests/contrib/django/django_app/appsec_urls.py, tests/contrib/django/test_django_appsec_iast.py
Code security: Django request args and form were not tainted properly (they were overwritten).
- Avoids …
=> chore(iast): taint get and post http parameter name in django

ddtrace/__init__.py, ddtrace/contrib/aredis/__init__.py, ddtrace/contrib/httpx/__init__.py, ddtrace/contrib/internal/mongoengine/trace.py, ddtrace/contrib/internal/pylibmc/client.py, ddtrace/contrib/internal/pymongo/client.py, ddtrace/contrib/internal/tornado/application.py, ddtrace/contrib/redis/__init__.py, ddtrace/contrib/yaaredis/__init__.py, docs/api.rst
Ensure deprecation warnings are only logged when users manually use deprecated interfaces.
This change ensures we do not use the deprecated `ddtrace.Pin` reference in docs and integrations. …
=> chore(pin): remove all deprecated references [3.0]

ddtrace/appsec/_iast/taint_sinks/code_injection.py, tests/appsec/iast/fixtures/taint_sinks/code_injection.py, tests/appsec/iast/taint_sinks/test_code_injection.py
=> chore(iast): iast code injection error with locals and globals

ddtrace/internal/datadog/profiling/dd_wrapper/include/uploader_builder.hpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/code_provenance.cpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/ddup_interface.cpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/profile.cpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader_builder.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/sampler.cpp, ddtrace/internal/datadog/profiling/stack_v2/src/thread_span_links.cpp, releasenotes/notes/fix-profiling-native-mutices-62440b5a3d9d6c4b.yaml
Manual backport of #11768 to 2.17 …
=> fix(profiling): reset all profiling c++ mutexes on fork [backport 2.17]

ddtrace/profiling/collector/_memalloc.c
The first GIL assertion I added, to `memalloc_add_event`, has not tripped
yet on a test application. One the one hand, it's reassuring that we
always see the GIL in that part of the code. On the other hand, there
are other parts of the memory profiler that could in theory be called
concurrently where I didn't add the assertion: when stopping the
profiler, and when iterating over the events to aggregate them. Add GIL
assertions to those points.  The goal is ultimately to understand why we
needed to add locks to the profiler to prevent it from crashing, given
that the GIL exists.
- The PR …
=> refactor(profiling): add more GIL assertions to memalloc

ddtrace/contrib/trace_utils.py, ddtrace/settings/config.py, releasenotes/notes/fix-unncessary-header-extraction-c1facf2b30331afb.yaml, tests/contrib/wsgi/test_wsgi.py, tests/utils.py
Reverts DataDog/dd-trace-py#9456
This PR was merged automatically even though there was a failing system test. https://github.com/DataDog/dd-trace-py/actions/runs/12836948874/job/35799900676 …
=> Revert "fix(tracing): only extract distributed headers if a trace is not already started"

pyproject.toml
This PR updates the `version_schema` in the `../pyproject.toml` file for the 2.20 release branch from `release-branch-semver` to `guess-next-dev`. This is to ensure that system tests work as intended with backports to this release branch.
IMPORTANT: This PR needs to be merged before the first backport is created for 2.20.Otherwise, system tests will not work as expected.
=> chore: use guess-next-dev instead of release-branch-semver [2.20]

.github/workflows/build-and-publish-image.yml
Unfortunately https://github.com/DataDog/dd-trace-py/pull/12012 didn't work as the updated job calls another that still doesn't have the rights to push. This PR fixes it: https://github.com/DataDog/dd-trace-py/actions/runs/12903927609 …
=> ci: add missing permissions to publish misl i686 image on child job

tests/contrib/langgraph/test_langgraph.py, tests/contrib/langgraph/test_langgraph_llmobs.py
Tests like `test_fanning_graph_async` would fail because it may be possible for the two children being called from a common node (ie node `a` calling nodes `b` and `c`) to execute in any order. Although this is probably only particular to async fanning tests, this PR changes the logic such that:
- for LLMObs tests, we find spans by name and assert LLMObs properties after. This might be tricky if we have duplicate span names (ie two `LangGraph` spans), but for now this isn't the case
- for APM tests, we assert that all span resource names appear an expected number of times. We can probably make these tests more robust with snapshots but this can be done in a later PR
- The …
=> ci(langgraph): fix flaky test

ddtrace/appsec/_iast/_handlers.py, tests/contrib/fastapi/test_fastapi_appsec_iast.py
Continuation of https://github.com/DataDog/dd-trace-py/pull/12009 …
=> chore(iast): taint parameter name in post requests in fastapi

ddtrace/contrib/internal/pytest/_retry_utils.py, releasenotes/notes/ci_visibility-fix-pytest-classes-b54582b09727fdc1.yaml, tests/contrib/pytest/test_pytest_atr.py
Auto Test Retries had a bug where retries of tests defined inside unittest classes would always succeed, even if the test failed. This was because for unittest classes, pytest saves the exception status in the [`pytest_runtest_makereport` hook](https://github.com/pytest-dev/pytest/blob/8.3.x/src/_pytest/unittest.py#L368), which was not called during retries. This PR fixes it so that the hook is called. …
=> fix(ci_visibility): handle pytest ATR retry failures in unittest classes

tests/profiling_v2/collector/test_stack.py, tests/profiling_v2/collector/test_stack_asyncio.py, tests/profiling_v2/test_accuracy.py, tests/profiling_v2/test_gunicorn.py, tests/profiling_v2/test_main.py
`profile 16/20` has been flaky with the following test
```
FAILED tests/profiling_v2/test_main.py::test_call_script_gevent[False] - AssertionError: (b'', b'')
assert -11 == 0
```
Since the test is for stack v1+libdd exporter and we don't plan to fix stack v1, we're removing those tests.  …
=> chore(profiling): remove `stack_v2_enabled=False` tests

.gitlab/benchmarks.yml, ddtrace/propagation/http.py
APMSP-1689
This PR also needs https://github.com/DataDog/benchmarking-platform/pull/125
After merging we will check and block PRs that introduce a microbenchmark regression of >20%.
- Title …
=> ci: check for benchmark regressions on PRs

ddtrace/internal/datadog/profiling/crashtracker/CMakeLists.txt, ddtrace/internal/datadog/profiling/ddup/CMakeLists.txt
=> ci(profiling): ignore deprecated function `tp_print` warning

ddtrace/contrib/internal/vertexai/_utils.py, ddtrace/contrib/internal/vertexai/patch.py, ddtrace/llmobs/_integrations/vertexai.py, releasenotes/notes/fix-vertexai-content-extraction-b216207bd8192e5f.yaml, tests/contrib/vertexai/test_vertexai.py, tests/contrib/vertexai/test_vertexai_llmobs.py
In [MLOS-42](https://datadoghq.atlassian.net/browse/MLOS-42) a customer was experiencing the following error: 
```
ddtrace.internal.utils.ArgumentError: contents (at position 0)
``` 
where the `content` argument was not being extracted properly from the list of keyword arguments inputted into the `chat.send_message` method. 
This is because in the Vertex AI integration, we look for the `contents` keyword argument. However, the content field is titled `content` in the [send_message](https://github.com/google-gemini/generative-ai-python/blob/main/google/generativeai/generative_models.py#L514) method and `contents` in the [generate_content](https://github.com/google-gemini/generative-ai-python/blob/main/google/generativeai/generative_models.py#L239) method, so it is necessary to …
=> fix(llmobs): fix content arg extraction for vertex ai integration

ddtrace/contrib/internal/vertexai/_utils.py, ddtrace/contrib/internal/vertexai/patch.py, ddtrace/llmobs/_integrations/vertexai.py, releasenotes/notes/fix-vertexai-content-extraction-b216207bd8192e5f.yaml, tests/contrib/vertexai/test_vertexai.py, tests/contrib/vertexai/test_vertexai_llmobs.py
Backports https://github.com/DataDog/dd-trace-py/pull/12034 to 2.19.
In [MLOS-42](https://datadoghq.atlassian.net/browse/MLOS-42) a customer was experiencing the following error:
```
ddtrace.internal.utils.ArgumentError: contents (at position 0)
```
where the `content` argument was not being extracted properly from the list of keyword arguments inputted into the `chat.send_message` method.
This is because in the Vertex AI integration, we look for the `contents` keyword argument. However, the content field is titled `content` in the [send_message](https://github.com/google-gemini/generative-ai-python/blob/main/google/generativeai/generative_models.py#L514) method and `contents` in the
[generate_content](https://github.com/google-gemini/generative-ai-python/blob/main/google/generativeai/gene …
=> fix(llmobs): fix content arg extraction for vertex ai integration [backport #12034 to 2.19]

ddtrace/appsec/_iast/_ast/ast_patching.py
Add django modules by default to the allowlist. This will still deny the django submodules in the denylist.
- …
=> chore(iast): add django to the allowlist

ddtrace/internal/datadog/profiling/cmake/FindLibdatadog.cmake, ddtrace/internal/datadog/profiling/dd_wrapper/src/crashtracker.cpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/receiver_interface.cpp, releasenotes/notes/libdatadog-v15.0.0-1004e5bb7f452d9a.yaml, setup.py, src/core/Cargo.lock, src/core/Cargo.toml
This PR bumps libdatadog to the [newly released v15.0.0](https://github.com/DataDog/libdatadog/releases/tag/v15.0.0). This will let us leverage new features such as library_config in following PRs.
Nothing should change much, so it is fine to only test this PR for non-regression.
- Backport labels are set …
=> chore(libdatadog): bump libdatadog to v15.0.0

benchmarks/http_propagation_extract/scenario.py, ddtrace/settings/config.py
This fixes the benchmarking test to reflect the config change made in this PR: https://github.com/DataDog/dd-trace-py/pull/11925
It also updates the config behavior slightly since the removing of "none" propagation style at the end of the loop was repetitive since we were already excluding that value.
- …
=> ci: fix bm test to reflect behavior of config for propagation

.gitlab-ci.yml, .gitlab/benchmarks.yml
We do not always run the serverless benchmarks job, this means that the CI config is invalid in those cases since regression check has an explicit dependency on serverless benchmarks.
- …
=> ci: move pr/regression check to benchmarks-report stage

.github/workflows/check_safe_main_merge.yml
Creates a GHA job that checks if the `main` branch can be cleanly merged to a 3.x-staging feature branch. This is to avoid scenarios where `main` has changes that conflict with `3.x-staging`, so we can resolve those before merging anything.
This is mainly for the 3.x migration effort. We can clean this job up afterwards. …
=> ci: add GHA job to check if `main` can be merged to 3.x branches

ddtrace/settings/asm.py, releasenotes/notes/msgpack_for_appsec-e09c17e9cb568379.yaml
=> feat(asm): meta struct enable by default for 3.0

ddtrace/appsec/_ddwaf/ddwaf_types.py, ddtrace/appsec/_processor.py, ddtrace/contrib/internal/subprocess/patch.py, ddtrace/settings/asm.py
Depending of the timing, libddwaf loading process could create triggers that would create loops in our instrumentation.
From what I investigated:
- if loaded too early, it could have bad interactions with gevent.
- if loaded too late, it could be self instrumented by the tracer, creating a loop, as ctypes is using Popen and subprocess.
while keeping the late loading introduced by 2 previous PRs
- https://github.com/DataDog/dd-trace-py/pull/11987
- https://github.com/DataDog/dd-trace-py/pull/12013
this PR introduced a mechanism to bypass tracer instrumentation during ctypes loading, to avoid a possible loop that would prevent the WAF to be loaded.
- The change includes …
=> chore(asm): clean libddwaf loading

ddtrace/appsec/_iast/_ast/ast_patching.py, ddtrace/internal/packages.py, releasenotes/notes/fix-asm-package-distributions-import-loop-11693f2a26032774.yaml
The usage of `callonce` in this function (that is now used in IAST and SCA) was triggering an import loop:
```
File "/usr/local/lib/python3.13/site-packages/ddtrace/internal/utils/cache.py", line 124, in _
retval, exc = f.__callonce_result__  # type: ignore[attr-defined]
^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute '__callonce_result__'
During handling of the above exception, another exception occurred:
File "/usr/local/lib/python3.13/site-packages/ddtrace/internal/telemetry/writer.py", line 622, in periodic
self._app_dependencies_loaded_event(newly_imported_deps)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.13/site-packages/ddtrace/internal/telemetry/w …
```
=> fix(iast): fix import loop

ddtrace/llmobs/_constants.py, ddtrace/llmobs/_llmobs.py, releasenotes/notes/remove-llmobs-parameters-annotation-97406f9cece3fac4.yaml, tests/llmobs/_utils.py, tests/llmobs/test_llmobs.py, tests/llmobs/test_llmobs_decorators.py, tests/llmobs/test_llmobs_service.py
Deprecates the `parameters` arg for the LLMObs annotation method in favor of `metadata`.
I verified this change by running the following code:
```
@workflow
def run():
LLMObs.annotate(
input_data="hello",
output_data="bye",
parameters={"example": True},
)
return None
run()
```
Which produced the following error as expected: `TypeError: LLMObs.annotate() got an unexpected keyword argument 'parameters'`.
Replacing `parameters` with `metadata` resolves the issue:
- The change follows the …
=> chore(llmobs): [MLOB-2093] remove deprecated parameters arg from annotate method

ddtrace/profiling/collector/_memalloc.c, releasenotes/notes/profiling-memalloc-iter-events-null-780fd50bbebbf616.yaml
Backports #12075 to 2.19
We added locking to the memory profiler to address crashes. These locks
are mostly "try" locks, meaning we bail out if we can't acquire them
right away. This was done defensively to mitigate the possibility of
deadlock until we fully understood why the locks are needed and could
guarantee their correctness. But as a result of using try locks, the
`iter_events` function in particular can fail if the memory profiler lock
is contended when it tries to collect profiling events. The function
then returns NULL, leading to SystemError exceptions because we don't
set an error.
Even if we set an error, returning NULL isn't the right thing to do.
It'll basically mean we wait until the next profile iteration, still
accumulating events in the same buffer, and try again to …
=> fix(profiling): fix SystemError when collecting memory profiler events [backport 2.19]

.github/CODEOWNERS, ddtrace/provider.py, ddtrace/trace/__init__.py, docs/advanced_usage.rst, releasenotes/notes/feat-expose-base-context-provider-530ebec2225f6c8d.yaml
ddtrace v3.0 is set to remove `ddtrace.providers` module from the public API. However we should still allow users to use their own ContextProviders. This PR ensures the BaseContextProvider remains in the public API and can be used in `tracer.configure(...)`.  …
=> feat(provider): expose context provider in ddtrace.trace

docs/advanced_usage.rst, docs/troubleshooting.rst
Resolves: https://github.com/DataDog/dd-trace-py/issues/12141 …
=> docs: update trace filter docs

ddtrace/llmobs/_llmobs.py, ddtrace/propagation/http.py, releasenotes/notes/fix-llmobs-enable-updates-config-45379a7a30e2e0e3.yaml, tests/llmobs/test_llmobs_service.py, tests/llmobs/test_propagation.py, tests/tracer/test_propagation.py
Backports #12089 to 2.20.
Note that we had to manually cherry-pick from #12089 to account for #11952 not being backported.
This PR makes a change to our shared distributed tracing header injection method to dispatch signals/events instead of relying on the global config settings, which is only modifiable via env vars. This fixes distributed tracing for users that might rely solely on the `LLMObs.enable()` setup config.
Programmatic `LLMObs.enable()/disable()` calls do not set the global `config._llmobs_enabled` boolean setting, which is only controlled by the `DD_LLMOBS_ENABLED` env var. This was problematic for users that relied on manual `LLMObs.enable()` setup (i.e. no env vars) because our distributed tracing injection code only checks the global config to inject llmobs parent IDs …
=> fix(llmobs): propagate distributed headers via signal dispatching [backport #12089]

.github/CODEOWNERS, ddtrace/provider.py, ddtrace/trace/__init__.py, docs/advanced_usage.rst, releasenotes/notes/feat-expose-base-context-provider-530ebec2225f6c8d.yaml
Forwardporting https://github.com/DataDog/dd-trace-py/pull/12135
ddtrace v3.0 is set to remove `ddtrace.providers` module from the public API. However we should still allow users to use their own ContextProviders. This PR ensures the BaseContextProvider remains in the public API and can be used in `tracer.configure(...)`. …
=> feat(provider): expose context provider in ddtrace.trace [forwardport 3.x]

ddtrace/_trace/trace_handlers.py, ddtrace/contrib/internal/aiohttp/middlewares.py, ddtrace/contrib/internal/bottle/trace.py, ddtrace/contrib/internal/cherrypy/patch.py, ddtrace/contrib/internal/falcon/middleware.py, ddtrace/contrib/internal/molten/patch.py, ddtrace/contrib/internal/pyramid/trace.py, ddtrace/contrib/internal/sanic/patch.py, tests/snapshots/tests.contrib.cherrypy.test_middleware.test_child.json, tests/snapshots/tests.contrib.cherrypy.test_middleware.test_error.json, tests/snapshots/tests.contrib.cherrypy.test_middleware.test_fatal.json, tests/snapshots/tests.contrib.cherrypy.test_middleware.test_success.json, tests/snapshots/tests.contrib.sanic.test_sanic_server.test_multiple_requests_sanic_http.json, tests/snapshots/tests.contrib.sanic.test_sanic_server.test_multiple_requests_sanic_http_pre_21.9.json, tests/snapshots/tests.contrib.sanic.test_sanic_server.test_sanic_errors.json, tests/snapshots/tests.contrib.sanic.test_sanic_server.test_sanic_errors_pre_21.9.json
Forwardporting https://github.com/DataDog/dd-trace-py/pull/12035
Refactors all web server integrations still using `tracer.trace` to instead use `core.context_with_data`. This is in preparation for supporting AWS API Gateway to ensure all web servers share the same code path. …
=> chore(tracing): refactor web server integrations to use the core module [forwardport 3.x]

ddtrace/appsec/_iast/_evidence_redaction/_sensitive_handler.py, ddtrace/appsec/_iast/_evidence_redaction/default_sensitive_analyzer.py, ddtrace/appsec/_iast/_handlers.py, tests/appsec/iast/taint_sinks/_taint_sinks_utils.py, tests/appsec/iast/taint_sinks/redaction_fixtures/evidence-redaction-suite.json, tests/appsec/iast/taint_sinks/test_code_injection_redacted.py, tests/appsec/iast/taint_sinks/test_command_injection_redacted.py, tests/appsec/iast/taint_sinks/test_header_injection_redacted.py, tests/appsec/iast/taint_sinks/test_path_traversal_redacted.py, tests/appsec/iast/taint_sinks/test_sql_injection_redacted.py, tests/appsec/iast/taint_sinks/test_ssrf_redacted.py
- Update suite tests to the latest version https://github.com/DataDog/experimental/blob/main/teams/asm/iast/redaction/suite/evidence-redaction-suite.json.  
- Refactor the redaction class and add a default redaction for Code Injection.  
- Mark as "redacted" if the string is too long (partial implementation of this RFC https://docs.google.com/document/d/1cAsBBOusoAvU6wRMez2M5JXqTwUwG6tddmX4LsxSAyI/edit?tab=t.0.  
- Skip tests by description instead of list position to improve readability.   …
=> chore(iast): update evidence redaction suite tests

.github/workflows/build_deploy.yml
It was flagged that Build jobs were not running on 3.x-staging. This adds the branch to the Build job trigger branches. …
=> ci: add `3.x-staging` to the build job trigger branches

benchmarks/bm/utils.py, benchmarks/rate_limiter/scenario.py
https://github.com/DataDog/dd-trace-py/pull/12186 removed deprecated parameters from `tracer.configure(...)` and `rate_limiter.allowed(...)` but did not update the microbenchmarks. This PR address this issue.
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.h …
=> ci(benchmarks): fix failing microbenchmarks

ddtrace/internal/remoteconfig/worker.py, releasenotes/notes/remove_unneeded_unregister-ad20120201768a7e.yaml
Removes unneeded forksafe unregister hook. The unregister is not needed, because we never actually registered the hook to begin with. …
=> fix(logging): remove unneeded forksafe unregister to avoid unneeded logging

ddtrace/contrib/_langchain.py, ddtrace/contrib/internal/langchain/patch.py, ddtrace/llmobs/_integrations/langchain.py, releasenotes/notes/langchain-drop-logs-metrics-a997e8059886b20a.yaml
This PR removes integration metrics and logs from the langchain integration.
Prompt-completion logs were always experimental, rarely used, and unofficially deprecated since the release of LLM Observability. For any customers looking to continue getting visibility into their langchain call prompt/completions, we are now pushing to migrate over to use LLM Observability instead.
Operational Integration metrics can either be replaced with LLM Observability or APM trace metrics instead. The only caveat of using LLM Observability is for customers who may not want prompt/completion logging, and the only caveat of using APM trace metrics is that token metrics will not be included, primarily only operation metrics. …
=> chore(langchain): drop legacy integration metrics and logs

ddtrace/llmobs/_constants.py, ddtrace/llmobs/_integrations/anthropic.py, ddtrace/llmobs/_integrations/bedrock.py, ddtrace/llmobs/_integrations/gemini.py, ddtrace/llmobs/_integrations/openai.py, ddtrace/llmobs/_integrations/utils.py, ddtrace/llmobs/_integrations/vertexai.py
[applying https://github.com/DataDog/dd-trace-py/pull/12026 to 3.x-staging]
This PR generalizes the helper method used to extract token metrics from an APM span to be attached to an LLMObs span. Before, Anthropic, Bedrock, and Open AI had specific methods on each of their integration classes to accomplish this. Now, there is one get_llmobs_metrics_tags utils function adapted from the google-specific get_llmobs_metrics_tags_google function that gets reused across these integrations as well as Vertex AI and Gemini. The Langchain integration was excluded from this change since its logic for extracting token metrics varies significantly compared to the other integrations.
- …
=> chore(llmobs): [MLOB-1944] generalize helper for extracting token metrics

ddtrace/_trace/tracer.py, releasenotes/notes/drop-multitracer-support-ec109486f71c9c62.yaml, tests/ci_visibility/test_ci_visibility.py, tests/ci_visibility/util.py, tests/contrib/aiomysql/test_aiomysql.py, tests/contrib/flask_cache/test_utils.py, tests/contrib/kafka/test_kafka.py, tests/contrib/tornado/test_config.py, tests/integration/test_debug.py, tests/integration/test_encoding.py, tests/integration/test_integration.py, tests/integration/test_integration_civisibility.py, tests/integration/test_integration_snapshots.py, tests/integration/test_priority_sampling.py, tests/integration/utils.py, tests/opentracer/core/test_dd_compatibility.py, tests/opentracer/core/test_tracer.py, tests/profiling/collector/conftest.py, tests/profiling_v2/collector/conftest.py, tests/tracer/test_correlation_log_context.py, tests/tracer/test_gitmetadata.py, tests/tracer/test_memory_leak.py, tests/tracer/test_processors.py, tests/tracer/test_single_span_sampling_rules.py, tests/tracer/test_trace_utils.py, tests/tracer/test_tracer.py, tests/utils.py
This PR ensures an error is logged when more than one instance of the Tracer is initialized in a process. In all scenarios the global tracer must be used to trace an application.
- Title is …
=> chore(tracing): make ddtrace.trace.Tracer a singleton

ddtrace/_trace/tracer.py, tests/tracer/test_propagation.py
Fixes CI issues introduced by: https://github.com/DataDog/dd-trace-py/pull/12209 …
=> ci(fix): fix failing pre-check and broken tracing test

ddtrace/contrib/internal/aiohttp/middlewares.py
This is to ensure no commits on `main` get erased when we force-push `3.x-staging` into `main`. This is to cover the one commit that slipped: https://github.com/DataDog/dd-trace-py/pull/12036
After this is merged, `3.x-staging` should be ready to be merged into `main` safely for dd-trace-py to upgrade to 3.x …
=> chore: update `3.x-staging` with `main`

tests/tracer/test_propagation.py, tests/tracer/test_tracer.py
When the tracer is shutdown span aggregators are removed. If this is done outside of a subprocess it will impact the state of the tracer in future test runs. This PR ensures the tracer shutdown tests are only run in a subprocess.  …
=> ci(tracer): avoids shutting down the global tracer in the main process

tests/appsec/integrations/django_tests/conftest.py, tests/appsec/integrations/django_tests/django_app/urls.py, tests/appsec/integrations/django_tests/django_app/views.py, tests/appsec/integrations/django_tests/test_django_appsec_iast.py
=> chore(iast): more sqli redaction tests

ddtrace/appsec/_iast/taint_sinks/xss.py, tests/appsec/integrations/fastapi_tests/test_fastapi_appsec_iast.py, tests/appsec/integrations/flask_tests/test_iast_flask.py
Even when starting the application with `ddtrace-run ddtrace-run`, `jinja2.FILTERS` is created before this patch function executes. Therefore, we update the in-memory object with the newly patched version.
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html …
=> chore(iast): xss vulnerability for jinja2

ddtrace/contrib/internal/aiohttp/middlewares.py, ddtrace/settings/symbol_db.py, releasenotes/notes/feat-symdb-enabled-by-default-25eebb43fc8c5a0d.yaml, tests/telemetry/test_writer.py
We make Symbol Database enabled by default. …
=> feat(symdb): enable by default

ddtrace/contrib/internal/dd_trace_api/patch.py
=> Emmett.butler/dd trace api wrapping

ddtrace/internal/logger.py, releasenotes/notes/fix-internal-logging-init-6058c02b527cdf77.yaml, tests/tracer/test_logger.py
There were tests not run as part of the CI for #12243 which this change seems to impact.
Reverting to unblock other PRs from merging into `main` until we can resolve it.
=> Revert "fix(internal): move logging rate limiter to log filter"

lib-injection/sources/sitecustomize.py, releasenotes/notes/ssi-constraint-runtime-1d31502a3848369b.yaml
Partially addresses #10932 (https://github.com/DataDog/dd-trace-py/issues/10932#issuecomment-2616189476) by increasing the maximum allowed runtime version for lib-injection to 3.14.
- Title …
=> fix(lib-injection): bump max allowed runtime version for lib-injection

.gitlab/benchmarks.yml
Remove two job setup for serverless benchmarks.
The success/failure of `benchmarks-serverless` will cause the whole pipeline to get marked as a failure and the PR checks to fail.
- Title is …
=> ci: remove benchmark-serverless-trigger check job

ddtrace/llmobs/_integrations/openai.py, releasenotes/notes/deepseek-openai-39564ebad1b6f98d.yaml, tests/contrib/openai/cassettes/v1/deepseek_completion.yaml, tests/contrib/openai/test_openai_llmobs.py
Sets `deepseek` as the model provider and client for the span name if using the [Deepseek API as the base URL for the Python OpenAI SDK](https://api-docs.deepseek.com/).
Most LoC are from adding a new cassette.
**Note**: I tried a generic approach to recognizing providers from the base URL but found that maybe a generic regex wouldn't always catch it. Special casing Deepseek and we can return to modify it as needed down the line. …
=> feat(llmobs): auto-annotate deepseek as span name and model provider through openai

.gitlab-ci.yml, .gitlab/testrunner.yml
This causes the tests to be entirely skipped unless it is the main or release branch.
=> Revert "chore(ci): don't allow `main` or release branches to be interruptible"

riotfile.py
This change prevents a segfault coming from `zope.interface` when running the `ci_visibility` test suite under Python 3.8
This issue was found during the PR #12243. It is unclear why that PR surfaces the issue, but the extracted segfault traceback is showing [zope.interface._compat._c_optimizations_available](https://github.com/zopefoundation/zope.interface/blob/6f56f2c36daecc6f4263bf24a696614c90d4a3ac/src/zope/interface/_compat.py#L50) as the trigger for the segfault.
The fix to work around this issue is to set the [PURE_PYTHON=1](https://github.com/zopefoundation/zope.interface/blob/6f56f2c36daecc6f4263bf24a696614c90d4a3ac/src/zope/interface/_compat.py#L39) environment variable which will tell `zope.interface` to not use this c extension at all.
[Example segfault from …
=> ci: prevent segfaults in ci_visibility Python 3.8 tests

ddtrace/profiling/collector/_memalloc_tb.h, ddtrace/profiling/collector/_utils.h, releasenotes/notes/fix-memalloc-traceback-array-index-wraparound-f12e4da5a7de32f2.yaml
The traceback array type used by the heap profiler is instantiated from
a preprocessor macro in `ddtrace/profiling/collector/_utils.h`. The macro
takes an index/count type, which for the traceback array was a `uint16_t`.
If the heap profiler's traceback array gets large, meaning we're
tracking a lot of allocations, then computing the new size of the array
when growing it can easily overflow the size type. This can lead us to
allocate a smaller array rather than a larger one, and yet the count of
elements stays the same. So we can write out of bounds, free NULL
pointers, etc, when we access elements outside the bounds of the actual
array.
Change the size type to a `size_t` for that array. The other arrays
instantiated from that macro already use 64-bit unsigned integers, which
are at least …
=> fix(profiling): fix crash in heap profiler due to unsigned integer wraparound

ddtrace/contrib/internal/trace_utils.py, ddtrace/llmobs/_constants.py, ddtrace/llmobs/_context.py, ddtrace/llmobs/_integrations/base.py, ddtrace/llmobs/_integrations/bedrock.py, ddtrace/llmobs/_integrations/langgraph.py, ddtrace/llmobs/_llmobs.py, ddtrace/llmobs/_utils.py, ddtrace/llmobs/_writer.py, releasenotes/notes/feat-llmobs-context-e4adabcb6894e4d8.yaml, tests/llmobs/_utils.py, tests/llmobs/test_llmobs.py, tests/llmobs/test_llmobs_service.py, tests/llmobs/test_propagation.py
[MLOB-1342] This is a manual copy of #10767 to 3.x-staging due to merge conflicts between 3.x-staging and main.
Public facing changes:
- Any LLMObs method (`export_span(), annotate()`) that allow an optional span argument will now default to finding the current active LLMObs span rather than the current active APM span.
- ~Adds multithreading (futures.multithreading) support for LLMObs. Previously multithreaded apps would result in broken traces.~ UPDATE: will be moving multithreading support to a separate PR.
Private changes:
- LLMObs has its own context provider which keeps track of the active LLM-type span (generated by both LLMObs._start_span() and LLM integrations)
- HTTPPropagation now adds LLMObs parent ID as a field on the request headers directly, rather than through the context …
=> feat(llmobs): llmobs-specific context manager

ddtrace/llmobs/_llmobs.py
Adds `langgraph` for auto-patching when `LLMObs.enable(...)` is called. It is still further gated behind environment variable. …
=> chore(llmobs): enable langgraph for enabled integrations

ddtrace/_trace/span.py, releasenotes/notes/fix-custom-error-spans-with-__str__-override-a05726045f8751d6.yaml, tests/tracer/test_span.py
Backport of #12307 to 2.21
Today when a custom exception overrides `__str__` by raising an exception, the tracer cannot apply an error message on it because `str(exc_val)` doesn't work (it raises the exception again). As a result the span doesn't close correctly because it's an exception, not a string and thus the span can't get sent.
If this condition occurs, this PR sets the error message to the class name of the custom exception so the spans can still get sent and there's a clue to what the exception was.
The current logic is this:
https://github.com/DataDog/dd-trace-py/blob/6b5f13c2701d55a695afcd4a73db8af2d251b55d/ddtrace/_trace/span.py#L523
When we run the current logic against a custom exception that overrides `__str__`, we can see from the [failed …
=> fix(span): handle errors on spans when a custom exception overrides __str__ (#12307) [backport 2.21]

ddtrace/appsec/__init__.py, ddtrace/appsec/_asm_request_context.py, ddtrace/appsec/_common_module_patches.py, ddtrace/appsec/_constants.py, ddtrace/appsec/_utils.py, ddtrace/contrib/internal/httplib/patch.py, ddtrace/contrib/internal/mysql/patch.py, ddtrace/contrib/internal/mysqldb/patch.py, ddtrace/contrib/internal/pytest/_plugin_v2.py, ddtrace/contrib/internal/pytest/plugin.py, ddtrace/contrib/internal/requests/patch.py, ddtrace/contrib/internal/sqlalchemy/patch.py, ddtrace/contrib/internal/sqlite3/patch.py, ddtrace/contrib/internal/subprocess/patch.py, ddtrace/contrib/internal/urllib/patch.py, ddtrace/contrib/internal/urllib3/patch.py, ddtrace/contrib/internal/webbrowser/patch.py, ddtrace/internal/appsec/product.py, ddtrace/internal/writer/writer.py, ddtrace/settings/asm.py, hatch.toml, releasenotes/notes/ensure_no_appsec_loading-8ce46c58d6ecf81f.yaml, tests/appsec/integrations/flask_tests/mini.py, tests/appsec/integrations/flask_tests/test_appsec_loading_modules.py, tests/appsec/integrations/flask_tests/test_iast_flask_telemetry.py, tests/contrib/flask/test_flask_appsec_iast.py, tests/contrib/subprocess/test_subprocess.py, tests/contrib/subprocess/test_subprocess_patch.py, tests/utils.py
Backport https://github.com/DataDog/dd-trace-py/pull/12212 to  2.20 …
=> fix(asm): decouple appsec [backport 2.20]

.github/workflows/system-tests.yml
We are unable to select this job for branch protection rules, trying to set a unique name to see if that resolves it. …
=> chore(ci): set name for system-tests finished job

ddtrace/appsec/_common_module_patches.py, ddtrace/appsec/_iast/_iast_request_context.py, ddtrace/appsec/_iast/_patch.py, releasenotes/notes/no_IAST_unguarded_loading_in_common_module_patches-123cf6d3f8844823.yaml
backport https://github.com/DataDog/dd-trace-py/pull/12198 to 2.19
Make sure, if iast is disabled, that we don't load any iast modules in the common module mechanism used both by iast and exploit prevention.
APPSEC-56659
Co-authored-by: Ramy Elkest <4thkest@gmail.com>
(cherry picked from commit 362fa22be2f7f6b61b023adb2aa56949aa163210) …
=> fix(asm): make sure iast is not loaded by exploit prevention if disabled [backport 2.19]

ddtrace/settings/_config.py, ddtrace/settings/_core.py, ddtrace/settings/_otel_remapper.py, tests/opentelemetry/test_config.py, tests/telemetry/test_writer.py
Removes all usages of `os.getenv` from `ddtrace.config`. Moving forward the `get_config(..)` helper will be used to parse all Datadog and OpenTelemetry environment variables. 
This will ensure instrumentation telemetry is collected in a consistent manner. …
=> chore(configuration): use get_config to parse all envars used in ddtrace.config

scripts/freshvenvs.py, scripts/regenerate-riot-latest.sh
Updates the script used for the 'update package versions' workflow, as it was previously failing after modules moving to `contrib/internal`
Example successful workflow: https://github.com/DataDog/dd-trace-py/actions/runs/13319654841/job/37201688142 …
=> chore(ci): fix update package version workflow

tests/profiling/collector/test_threading.py, tests/profiling/test_main.py
2 tests on the profile suit seems to have a large probability to be frozen. This creates timeout failures on the suite. …
=> test(ci): disabling non passing tests on gitlab

.gitlab/testrunner.yml, .gitlab/tests.yml
We had this on the base riot and hatch definitions, but we should just have it on the .testrunner definition itself so everything gets it. …
=> ci: add `retry: 2` to the `.testrunner` definition so everything inherits it

ddtrace/appsec/_trace_utils.py, ddtrace/contrib/internal/trace_utils.py, tests/appsec/appsec/test_appsec_trace_utils.py, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
- Improve ATO support by adding collection mode and usr.id tags to set_user sdk
- Add unit test for both tags
- Update snapshot tests
- It will be also tested by new ato system tests. (https://github.com/DataDog/system-tests/pull/4125)
- Add an optional parameter `mode` to set_user to simulate auto instrumentation
APPSEC-56786 …
=> chore(asm): add collection mode tag for set_user sdk

.github/CODEOWNERS
The new team https://github.com/orgs/DataDog/teams/apm-serverless would like to take on ownership of this testing file. …
=> ci: add specific code owners for tests/internal/test_serverless.py

ddtrace/contrib/internal/futures/threading.py, ddtrace/llmobs/_llmobs.py, releasenotes/notes/feat-llmobs-multithreading-783f29a684256b86.yaml, tests/llmobs/test_propagation.py
This PR adds support for propagating llmobs contexts across multithreaded applications.
Prior to #10138 we were using the Context object to propagate distributed tracing parent IDs. This didn't work in multithreaded applications because the context object's _meta field was not thread safe (See #10138 for more details). Since we now have our own context manager/provider, we can simply propagate this across contexts/threads by adding support in the futures concurrent threading integration.
I used signal handling here to avoid any unnecessary import/load/startup of LLMObs code if LLMObs is not enabled. …
=> feat(llmobs): support multithreading context propagation

ddtrace/llmobs/_integrations/langgraph.py
changes a `tracer.current_span()` call to `LLMObs._instance._current_span()` to ensure we are dealing with the current LLMObs span. …
=> chore(langgraph): update tracer.current_span with llmobs context manager check

ddtrace/llmobs/_integrations/langchain.py
refines the beta span linking logic for llmobs langchain spans to reduce memory
removes the `_spans` mapping of instance IDs to spans. instead, since we really only used this for steps in chains, and the same runnable (e.g. chat model) could be used in different chains, we want to do this mapping by chain instance.
when "recording" an instance we trace, we always do the span --> instance mapping. however, now the instance --> span mapping is only done as a temporary property on chains, as steps outside of chains will be defaulted to their parent span for linkage. this also makes cleanup easier, as we can delete the property and let GC take care of getting rid of the mapping that's unreferenced.
[MLOB-2245] …
=> chore(llmobs): better span linking logic for langchain integration

CHANGELOG.md
=> chore: update changelog for version 2.19.4, 2.20.0, 2.20.1, 2.21.0, 2.21.1

ddtrace/contrib/internal/asgi/middleware.py, releasenotes/notes/fix_blocking_on_fastapi_with_middleware-08ac58a6b112e29f.yaml
Fastapi middleware use BaseExceptionGroup on python 3.11. With a custom middleware, this mechanism could encapsulate BlockingException raised by our blocking mechanism, preventing it to be properly caught to generate a proper blocking response.
This will be tested permanently by the `fastapi` weblog, as https://github.com/DataDog/system-tests/pull/4125 adds a custom middleware to simulate ATO automatic instrumentation.
Due to our mandatory compatibility with previous python version, we can't use syntaxic sugar to handle exception group.
- The PR description notes risks associated with the …
=> fix(asm): improve BlockingException catch for fastapi

ddtrace/contrib/internal/langchain/utils.py, ddtrace/contrib/internal/openai/utils.py, ddtrace/llmobs/_integrations/base.py, tests/llmobs/test_llmobs_integrations.py
As of #12211 and #12220, we dropped support for legacy integration metrics and logs from openai and langchain integrations. This PR removes functional support for this in the BaseLLMIntegration class.
Note that we forgot to drop emitting integration metrics for streamed openai/langchain responses. Since #12211 and #12220 officially dropped support with a release note already for the ddtrace 3.0 release, I do not think this warrants a release note. …
=> chore(llmobs): remove integration logs and metrics functionality

.gitlab-ci.yml
Adds `SIMPLE_AUTO_INJECTION_PROFILING` scenario to the onboarding tests' matrix, thus effectively enabling a simple profiling onboarding scenario to run for each PR in addition to a simple tracing scenario. (When `SCENARIO` is not specified, it defaults to `[ SIMPLE_INSTALLER_AUTO_INJECTION ]` so this override is additive.)
Just as `SIMPLE_INSTALLER_AUTO_INJECTION` provides an early indication that a PR is breaking *tracing* functionality with SSI on host and container deployments, `SIMPLE_AUTO_INJECTION_PROFILING` does the same for *profiling*.
This complements a broader set of tested scenarios that are executed as part of the nightly auto-instrumentation CI, with Python profiling just having been added into the matrix there with https://github.com/DataDog/system-tests/pull/3002.
JIRA: …
=> ci: enable a profiling onboarding test scenario

scripts/report_skipped_flaky.py
Fixes a small bug in the flaky test script that would show the wrong test name for some entries. Count is still accurate. …
=> chore: fix incorrect test name issue in flaky test script

ddtrace/internal/datadog/profiling/dd_wrapper/include/ddup_interface.hpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/ddup_interface.cpp, ddtrace/internal/datadog/profiling/ddup/_ddup.pyx
To implement [endpoint profiling](https://docs.datadoghq.com/profiler/connect_traces_and_profiles/?code-lang=python#endpoint-profiling), we maintain two mappings
1. span ids to endpoint names
2. endpoint names to request counts
Both mappings don't need to be ordered, so switch over to `std::unordered_map` from `std::map` for better average time complexity. 
- The change …
=> chore(profiling): use unordered_map instead of map

ddtrace/__init__.py, ddtrace/_logger.py, ddtrace/_monkey.py, ddtrace/_trace/sampler.py, ddtrace/_trace/tracer.py, ddtrace/internal/remoteconfig/worker.py, ddtrace/internal/sampling.py, ddtrace/internal/telemetry/writer.py, ddtrace/internal/writer/writer.py, ddtrace/propagation/_database_monitoring.py, ddtrace/settings/__init__.py, ddtrace/settings/_config.py, ddtrace/settings/_core.py, ddtrace/settings/_otel_remapper.py, ddtrace/settings/_telemetry.py, ddtrace/settings/asm.py, ddtrace/settings/crashtracker.py, ddtrace/settings/dynamic_instrumentation.py, ddtrace/settings/exception_replay.py, ddtrace/settings/peer_service.py, ddtrace/settings/profiling.py, ddtrace/settings/symbol_db.py, tests/contrib/logging/test_tracer_logging.py, tests/opentelemetry/test_config.py, tests/telemetry/test_writer.py
- Uses `ddtrace.settings._core.get_config` to set configurations in the telemtry writer. This allows telemetry to be configured via stable configuration and otel environment variables. Currently the telemetry writer is only uses configures in Datadog environment variables.
- Uses `ddtrace.settings._core.get_config` to set configurations in ddtrace loggers. This will allow us to configure loggers remotely and enable debug mode. 
Ensures `ddtrace.settings._core.get_config` can be used without initializing the global config object. This will allow us to replace most instance of `os.environ` with an function that:
- collects instrumentation telemetry about configurations
- supports loading configurations from files (via stable/static apm config)
- Respects the precedence of ddtrace …
=> chore(configuration): use `get_config` to access telemetry and logging configurations

.gitlab/benchmarks.yml, ddtrace/internal/packages.py, releasenotes/notes/fix-internal-packages-perf-c270b1ff7e68b46a.yaml
Backport 0c7fc1bb94a7c97683a0bbd653c275aa8dfe02f5 from #12327 to 2.19. …
=> fix(internal): improve performance of package resolution [backport #12327 to 2.19]

src/core/lib.rs
Backport #12450 to `2.21` branch. …
=> chore: ignore useless conversion lint warning from pyo3 (#12450)

src/native/Cargo.lock, src/native/lib.rs
Backport https://github.com/DataDog/dd-trace-py/pull/12450 to `3.0` branch.
strategy
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)) …
=> chore: ignore useless conversion lint warning from pyo3 [#12450]

tests/contrib/httpx/test_httpx.py, tests/snapshots/tests.contrib.httpx.test_httpx.test_schematized_unspecified_service_name_env_default.json, tests/snapshots/tests.contrib.httpx.test_httpx.test_schematized_unspecified_service_name_env_v0.json
Two of these httpx tests (**test_schematized_unspecified_service_name_env_default** and **test_schematized_unspecified_service_name_env_v0**) have expired timestamps. This PR attempts to fix that.
While doing this, it looks like the newer changes to httpx has changed the expectation of what service name gets used as the default, so the reviewer is needed also to check that this is expected. …
=> test(httpx): fix expired httpx flaky as of Feb 2024

pyproject.toml, releasenotes/notes/avoid-bad-bytecode-release-2c8cdb1fa0b20b77.yaml
https://github.com/MatthieuDartiailh/bytecode/issues/130 …
=> fix(internal): require bytecode>=0.15.1 for Python 3.12 to avoid known bug

scripts/report_skipped_flaky.py
The test names associated with each `@flaky` decorator was still off by one in some cases. This should fix it. …
=> ci: fix flaky script report test names being off by one

tests/contrib/django/test_django.py, tests/contrib/django/test_django_snapshots.py, tests/snapshots/tests.contrib.django.test_django_snapshots.test_psycopg2_query_default.json, tests/snapshots/tests.contrib.django.test_django_snapshots.test_psycopg3_query_default.json, tests/snapshots/tests.contrib.django.test_django_snapshots.test_urlpatterns_include.json
This change removes the `@flaky` markers from some django tests and updates expectations that had become stale. …
=> test(django): update some stale skipped tests in the django suite

tests/contrib/botocore/test.py
Remove an unnecessary `@flaky` decorator from the botocore test: `test_aws_payload_tagging_s3_invalid_config` …
=> test(botocore): remove flaky decorator from botocore test

.circleci/config.templ.yml, .gitlab/services.yml, tests/contrib/suitespec.yml
This change moves the `cassandra` test suite to gitlab, because we're in the process of migrating off of circleci. …
=> ci(cassandra): move cassandra suite from circleci to gitlab

tests/contrib/botocore/test.py, tests/contrib/grpc/test_grpc.py
Extend flaky expiration date for flaky grpc test until `1767220930` (12/31/25)
notes:
If gitlab does not support `ipv6`, and we do not when this will change, long-term we should either
1) change to use a different protocol that is supported
2) remove the test entirely …
=> chore(ci): extend timestamp on flaky test decorator for grpc

.circleci/config.templ.yml, tests/contrib/suitespec.yml
This change moves to gitlab all of the remaining test suites that communicate with the Postgres or Mysql images as part of the ongoing migration away from circleci.
- All …
=> ci: circleci->gitlab for suites that use the mysql and postgres images

ddtrace/contrib/internal/trace_utils.py, ddtrace/settings/_config.py, tests/internal/service_name/test_inferred_base_service.py
Fixes small edge case for service naming, where if the user-provided service equals the inferred base service, the code returns default service name, even though the actual service name should be returned in this case. Adds a check to see if the service name was user provided.
- Backport labels are set …
=> chore: do not return default service if config.service was user set and equals inferred service

ddtrace/contrib/internal/celery/signals.py, releasenotes/notes/celery-broker-url-list-8998b5629fd2693d.yaml, tests/contrib/celery/test_tagging.py
Resolves issue: #12473 where multiple broker urls are in a list  …
=> fix(celery): list of broker urls

.circleci/config.templ.yml, .gitlab/services.yml, tests/contrib/consul/test.py, tests/contrib/suitespec.yml
This change moves to gitlab the mongoengine, mariadb, and consul test suites as part an the ongoing migration away from circleci. …
=> ci: move consul, mariadb, mongoengine suites to gitlab

ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp, ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h, ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp, ddtrace/settings/asm.py, setup.py, tests/smoke_test.py
With this PR, all macOS wheels should include the IAST `.so` file. If not, it will trigger an error **in the CI**
- Fix IAST C++ code to support macOS 10.13 or later  
- Enable smoke tests for all macOS builds in `build_python_3.yml`  
- Remove the "optional" flag for the IAST build in `setup.py` to ensure a fast failure if any issues arise   …
=> chore(iast): fix wheel build error on macOS

ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp, ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h, ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp, setup.py, tests/smoke_test.py
Backport 2ef9f1ed81db0f1d8d37758976aa892bac131ef3 from #12536 to 2.19.
With this PR, all macOS wheels should include the IAST `.so` file. If not, it will trigger an error **in the CI**
- Fix IAST C++ code to support macOS 10.13 or later  
- Enable smoke tests for all macOS builds in `build_python_3.yml`  
- Remove the "optional" flag for the IAST build in `setup.py` to ensure a fast failure if any issues arise  
APPSEC-56890 …
=> chore(iast): fix wheel build error on macOS [backport 2.19]

ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp, ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h, ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp, setup.py, tests/smoke_test.py
Backport 2ef9f1ed81db0f1d8d37758976aa892bac131ef3 from #12536 to 2.20.
With this PR, all macOS wheels should include the IAST `.so` file. If not, it will trigger an error **in the CI**
- Fix IAST C++ code to support macOS 10.13 or later  
- Enable smoke tests for all macOS builds in `build_python_3.yml`  
- Remove the "optional" flag for the IAST build in `setup.py` to ensure a fast failure if any issues arise  
APPSEC-56890 …
=> chore(iast): fix wheel build error on macOS [backport 2.20]

.gitlab-ci.yml, .gitlab/release.yml
We want to ensure that no artifacts are published anywhere until the very end of the release pipeline. This was true for our PyPI pubilshing, but not for OCI images. This change will make the OCI publish job dependent on no jobs, but part of the release stage to ensure this.
This was tested on [this commit](https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-py/-/pipelines/57265203) (temporarily added this feature branch as a valid trigger for release stage), and it successfully blocked the OCI job when the PyPI publish job failed.
- The PR description notes risks associated with the …
=> ci: move `promote-oci-to-prod` job to release stage

scripts/docs/build.sh, scripts/gen_gitlab_config.py
This change fixes a failing `build_docs` job by unconditionally building the library in editable mode. It also adds some more files to the list that can trigger `build_docs` when changed on a PR.
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporti …
=> ci: fix docs build

tests/internal/test_serverless.py
The test added is flaky and fails sometimes with `ModuleNotFoundError: No module named 'ddtrace'`
=> Revert "ci(serverless): force reimport of modules during serverless test"

ddtrace/internal/packages.py
We add some initial support for Bazel runfiles when trying to infer the root module from a path
- Avoids …
=> chore(packages): add support for Bazel runfiles

ddtrace/internal/gitmetadata.py, ddtrace/internal/native/__init__.py, ddtrace/internal/remoteconfig/client.py, ddtrace/settings/_core.py, ddtrace/settings/_database_monitoring.py, ddtrace/settings/_telemetry.py, ddtrace/settings/asm.py, ddtrace/settings/code_origin.py, ddtrace/settings/crashtracker.py, ddtrace/settings/dynamic_instrumentation.py, ddtrace/settings/exception_replay.py, ddtrace/settings/live_debugging.py, ddtrace/settings/profiling.py, ddtrace/settings/symbol_db.py, ddtrace/settings/third_party.py, tests/debugging/exploration/_config.py, tests/debugging/mocking.py, tests/internal/bytecode_injection/framework_injection/_config.py
Currently `envier.Env` supports reading environment variables from one source (usually os.enviorn). This PR introduces `EnvDD` which will add support for loading environment variables from multiple sources. 
This will be used to load configurations from files and through the DatadogUI.
Note - This PR attempts to support multiple configuration sources without updating the envier library. This approach will be refactored when stable support configurations is GA 🤞.
- The change follows the …
=> chore(envier): support multiple sources

.gitlab/benchmarks/microbenchmarks.yml, benchmarks/telemetry_add_metric/config.yaml, benchmarks/telemetry_add_metric/scenario.py
Related to the efforts in https://github.com/DataDog/dd-trace-py/pull/12430. I separated the benchmarks in a separate PR since it doesn't need to be tied up with that PR.
The goal of this PR is to add the benchmark measuring the impact of creating instrumentation telemetry metrics.
Credits: @erikayasuda and @brettlangdon for pairing with me on this and checking out the results!
- The change follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.htm …
=> chore(telemetry): benchmark to track impact of metrics

ddtrace/debugging/_exception/replay.py
We make sure that a trace with an error has at least a snapshot attached to it. This would make sure that each exception along a trace has some useful debug information that can be used for further investigation.
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributi …
=> chore(er): ensure single snapshot capture

.github/workflows/build_python_3.yml
=> ci(fix): manually install `libatomic.i686` before `rustup` script

.gitlab/benchmarks/microbenchmarks.yml
This finishes up the work from #12563 and enables the benchmarks to run.
They were failing before because the scenario technically existed on the `main` branch, but not in a state where it could run successfully, so the benchmark scenario would always fail. …
=> ci(benchmarks): enable the startup benchmark scenario

tests/contrib/asyncpg/test_asyncpg.py
asyncpg test still pass when the flaky decorator is removed. …
=> chore(asyncpg): remove flaky from asyncpg

ddtrace/contrib/internal/vertica/patch.py, tests/contrib/vertica/test_vertica.py
Fixes vertica patching. `tracer` was removed as an argument to `Pin` but was still being used, causing some vertica tests to fail …
=> chore: fix vertica patching

tests/contrib/aiomysql/test_aiomysql.py, tests/contrib/mariadb/test_mariadb.py
=> chore(ci): remove flaky decorator from mariadb test

tests/contrib/aiomysql/test_aiomysql.py, tests/snapshots/tests.contrib.aiomysql.test_aiomysql.test_pin_override.json
=> chore(ci): remove flaky decorator from aiomysql

ddtrace/appsec/_iast/processor.py, tests/appsec/integrations/flask_tests/test_iast_flask_testagent.py
partialy revert commit d23def992bf99c5fbfda65d6973c0f7339bd33a1 from #12508
We added a workaround but we decided to revert because it would be confuse if we send the stacktrace in the next span. The solution is to change the trace start/finish to ensure the debug_application is inside the trace spans. We need to check with APM …
=> chore(iast): revert #12508

ddtrace/internal/writer/writer.py, ddtrace/vendor/__init__.py
We make some of the dogstatsd imports lazy to prevent some of the vendored modules from being force-loaded even when not needed. …
=> refactor(dogstatsd): make imports lazy

ddtrace/_trace/trace_handlers.py, ddtrace/contrib/internal/botocore/services/bedrock.py, ddtrace/llmobs/_integrations/bedrock.py
Remove reliance on setting/getting span tags for bedrock LLM Obs integration and instead use `ExecutionContext` to store all LLM Obs related attributes.
Previously, `_llmobs_set_tags` relied on extracting out the following data:
- `prompt` in Execution context (which was passed in as the `prompt` kwarg to _llmobs_set_tags)
- Various tags set on the span that will be parsed out
We refactor it so that all the information is stored in the execution context under the following fields:
- `request_params` - contains `prompt` and inference parameters like max_tokens
- `usage` - contains token usage data
- `stop_reason` - (only for converse)
- `model_provider`, `model_name`
And then directly pass in the execution context to `llmobs_set_tags`. This way, we decouple the parsing logic for LLM Obs …
=> chore(llmobs): remove reliance on span tags for bedrock llm integration

tests/contrib/vertica/test_vertica.py
Creating a connection after patching after import causes issues, which makes the test unreliable / failing. Instead of using a vertica Connection object, switch to using a mock Connection object
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backportin …
=> chore(ci): modify vertica flaky test

pyproject.toml
IMPORTANT: This PR needs to be merged before the first backport is created for 3.2.Otherwise, system tests will not work as expected.
=> chore: use guess-next-dev instead of release-branch-semver [3.2]

ddtrace/llmobs/_llmobs.py, releasenotes/notes/llmobs-workflow-io-ae4ab508e7fe336a.yaml, tests/llmobs/test_llmobs.py, tests/llmobs/test_llmobs_decorators.py, tests/llmobs/test_llmobs_service.py
Backports #12416 to 3.0.
Prior to this change, inputs and outputs on workflow or task spans would just be stringified which would produce Python string representations of dicts and lists.
This change proposes changing this representation to valid json so we can render them in the UI.
Before:
src="https://github.com/user-attachments/assets/578e80a1-1efc-4653-8f25-78a7597ae3e0" />
After:
src="https://github.com/user-attachments/assets/c377b0c7-a133-4885-95dd-ef3369b83675" />
---------
- The …
=> fix(llmobs): serialize inputs and outputs to valid json [backport #12416 to 3.0]

.gitlab-ci.yml
v3.2.0 release failed to publish the OCI images because it did not properly inherit the artifacts from the `package-oci` job. …
=> ci(release): ensure promote-oci-* jobs have necessary artifacts (#12659)

.gitlab-ci.yml
=> ci(release): fix publish-lib-init-pinned-tags job dependencies

ddtrace/llmobs/_constants.py, ddtrace/llmobs/_integrations/base.py, ddtrace/llmobs/_llmobs.py, ddtrace/llmobs/_telemetry.py, ddtrace/llmobs/decorators.py, tests/llmobs/_utils.py
[MLOB-2216]
This PR adds a `span.created` telemetry metric, which includes the tags (`decorator`, `integration`, `is_root_span`, `has_session_id`, `model_provider`).
We added this in addition to  `span.start` because right before finishing was the only place we had access to all of the above tags. Otherwise `autoinstrumented` was the only feasible tag we were guaranteed to have at span start time. We kept `span.start` as a metric to be able to count unfinished spans.
- The change follows the …
=> chore(llmobs): add span.finished telemetry metric

.gitlab-ci.yml
Backport https://github.com/DataDog/dd-trace-py/commit/268284eb574296f24a71f3f21ee636d483551a92 from https://github.com/DataDog/dd-trace-py/pull/12670 to 3.1.
- All …
=> ci(release): fix publish-lib-init-pinned-tags job dependencies [backport 3.2]

ddtrace/appsec/_asm_request_context.py, ddtrace/appsec/_constants.py, ddtrace/appsec/_remoteconfiguration.py, ddtrace/settings/asm.py, tests/appsec/appsec/test_remoteconfiguration.py
- add remote config client_id private span tag
- refactor some optional span tags code
- add unit test for rc_client_id span tag
APPSEC-56592 …
=> chore(asm): add client id span tag

ddtrace/llmobs/_telemetry.py, ddtrace/llmobs/_writer.py, tests/llmobs/_utils.py, tests/llmobs/test_llmobs_span_agent_writer.py, tests/llmobs/test_llmobs_span_agentless_writer.py
[MLOB-2355]
This PR adds the following telemetry metrics `dd.instrumentation_telemetry_data.span.raw_size/size` to report encoded span sizes (prior and post truncation). Each metric is tagged with `span_kind, autoinstrumented, integration, error, truncated`, where `truncated` indicates if the span was truncated before sending due to size limitations.
This PR also performs some clenaup and minor type fixes to the other telemetry metrics for llmobs. …
=> chore(llmobs): add telemetry on span event size/truncation

ddtrace/llmobs/_llmobs.py, ddtrace/llmobs/_telemetry.py
[MLOB-2390]
This PR adds telemetry metrics for LLMObs API usage to see how many times users manually call the following API methods:
- `LLMObs.annotate()` --> `dd.instrumentation_telemetry_data.mlobs.annotations`
- `LLMObs.submit_evaluation/submit_evaluation_for()` --> `dd.instrumentation_telemetry_data.mlobs.evals_submitted`
- `LLMObs.export_span()` --> `dd.instrumentation_telemetry_data.mlobs.spans_exported`
- `LLMObs.flush()` --> `dd.instrumentation_telemetry_data.mlobs.user_flushes`
- `LLMObs.inject_distributed_headers()` --> `dd.instrumentation_telemetry_data.mlobs.inject_distributed_headers`
- `LLMObs.activate_distributed_headers()` --> `dd.instrumentation_telemetry_data.mlobs.activate_distributed_headers`
These telemetry metrics are tagged with `error: "1"/"0"`, `error_type: …
=> chore(llmobs): telemetry metrics for LLMObs API usage

ddtrace/llmobs/_telemetry.py, ddtrace/llmobs/_writer.py
[MLOB-2395]
This PR adds telemetry for dropped span/eval events to LLM Observability. …
=> chore(llmobs): add telemetry for dropped spans/evals

.github/workflows/report-skipped-flaky.yml
To reduce the risk of compromise when [using third-party actions](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions), we need to pin GitHub Actions by full-length commit SHA (comment version). …
=> ci: pin GHA actions by sha for security

docs/build_system.rst, setup.py
This change adds two env variables to `setup.py`:
- `DD_BUILD_EXT_INCLUDES`
- comma separated list of `fnmatch` patterns to match native extensions to build
- `DD_BUILD_EXT_EXCLUDES`
- comma separated list of `fnmatch` patterns to match native extensions to _not_ build
`DD_BUILD_EXT_EXCLUDES` takes precedence over `DD_BUILD_EXT_INCLUDES`.
Example usage:
```shell
$ DD_BUILD_EXT_INCLUDES="ddtrace.internal.*" DD_BUILD_EXT_EXCLUDES="*._encoding" pip install --verbose -e .
INFO: Excluding extension ddtrace.profiling.collector._memalloc
INFO: Including extension ddtrace.internal._threads
INFO: Excluding extension ddtrace.appsec._iast._stacktrace
INFO: Excluding extension ddtrace.appsec._iast._taint_tracking._native
INFO: Including extension ddtrace.internal.datadog.profiling.ddup._ddup
INFO: …
```
=> chore: add DD_BUILD_EXT_INCLUDES and DD_BUILD_EXT_EXCLUDES to setup.py

.gitlab-ci.yml
<details open><summary>
</summary>
Benchmark jobs were shifted out of the benchmark stage causing
them to be affected by the VPA as the feature flag.
</details>
<details open><summary>
</summary>
Instead of relying on the stages to disable the flag, we
can add the disable annotation variable on the trigger job
so that it's inherited by the child jobs
</details>
<details><summary>
</summary>
</details> …
=> ci: disable VPA for child jobs of benchmarks

benchmarks/telemetry_add_metric/config.yaml, benchmarks/telemetry_add_metric/scenario.py
@wantsui and I were noticing the previous scenario was showing a much higher overhead than what we were getting locally. This may have just been how we wrote the benchmark and were extrapolating data from it.
This PR changes the benchmarking approach for telemetry metrics.
We now have the following scenarios for all metric types:
- Creating 1 unique metric
- Test to create a single metric in an empty `MetricNamespace`
- Creating 100 unique metrics
- Test to create a 100 unique metrics in an empty `MetricNamespace` 
- Increment 1 unique metric 100 times
- Test to add metrics 100 times for 1 unique metric
- Incrementing 100 unique metrics 100 times
- Test to add metrics 100 times for each of 100 unique metrics
Tests exist for Count, Gauge, Rate, and Distribution metrics.
We have to create a …
=> ci(benchmarks): refactor telemetry_add_metric benchmark scenario

docs/api.rst
Users should only use `DD_TRACE_SAMPLING_RULES` to configure the DatadogSampler. They do not need to know the inner working of the Datadog Sampler. Making these docs internal to avoid confusion. 
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporti …
=> docs: removes sampling docs

ddtrace/appsec/_asm_request_context.py, ddtrace/appsec/_iast/_handlers.py, ddtrace/appsec/_iast/_listener.py, ddtrace/contrib/internal/flask/wrappers.py, tests/appsec/iast/conftest.py, tests/appsec/integrations/flask_tests/test_iast_flask.py
`_on_wrapped_view` contains the logic to block requests for AppSec and to taint path parameters for IAST. However, since the `_on_wrapped_view` hook function is in `load_appsec`, the IAST logic doesn’t run if AppSec isn’t enabled.  
This PR splits that logic and creates two separate hooks.  
This PR is a cherry-pick of one of the commits of this PR https://github.com/DataDog/dd-trace-py/pull/12639 …
=> chore(iast): split wrapped_view hook

.github/CODEOWNERS
A bunch of modules for CI Visibility a.k.a. Test Visibility a.k.a. Test Optimization contribs were moved to `contrib/internal`, but the CODEOWNERS were not changed accordingly. This PR changes that.
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backpo …
=> chore(ci_visibility): change CODEOWNERS for internal Test Optimization contribs

ddtrace/appsec/_common_module_patches.py, ddtrace/appsec/_iast/_ast/visitor.py, ddtrace/appsec/_iast/constants.py, ddtrace/appsec/_iast/sources/__init__.py, ddtrace/appsec/_iast/sources/ast_taint.py, ddtrace/appsec/_iast/taint_sinks/ast_taint.py, ddtrace/appsec/_iast/taint_sinks/path_traversal.py, hatch.toml, tests/appsec/iast/_ast/test_ast_patching.py, tests/appsec/iast/aspects/test_io_aspects.py, tests/appsec/iast/fixtures/taint_sinks/path_traversal.py, tests/appsec/iast/taint_sinks/test_command_injection.py, tests/appsec/iast/test_telemetry.py, tests/appsec/integrations/flask_tests/test_iast_flask_patching.py
In this PR, we're migrating the way we propagate the `open` and `read` functions. Until now, we were using `wrapt`, but it's too invasive since these functions are used in many core operations. That's why we've migrated it to AST, ensuring that only the functions actually used in the application get replaced.  
To achieve this, we've added a new import in the AST visitor. In addition to aspects and sink points, we now define "sources" as well. …
=> chore(iast): refactor open/read wrapping

ddtrace/appsec/_common_module_patches.py, ddtrace/appsec/_iast/_ast/visitor.py, ddtrace/appsec/_iast/constants.py, ddtrace/appsec/_iast/sources/__init__.py, ddtrace/appsec/_iast/sources/ast_taint.py, ddtrace/appsec/_iast/taint_sinks/ast_taint.py, ddtrace/appsec/_iast/taint_sinks/path_traversal.py, tests/appsec/iast/_ast/test_ast_patching.py, tests/appsec/iast/aspects/test_io_aspects.py, tests/appsec/iast/fixtures/taint_sinks/path_traversal.py, tests/appsec/iast/taint_sinks/test_command_injection.py, tests/appsec/iast/test_telemetry.py, tests/appsec/integrations/flask_tests/test_iast_flask_patching.py
Backport 36fa1eef6a77bac45417922d7d82e2348adf43e4 from #12757 to 2.21.
In this PR, we're migrating the way we propagate the `open` and `read` functions. Until now, we were using `wrapt`, but it's too invasive since these functions are used in many core operations. That's why we've migrated it to AST, ensuring that only the functions actually used in the application get replaced.  
To achieve this, we've added a new import in the AST visitor. In addition to aspects and sink points, we now define "sources" as well.
- Newly-added …
=> chore(iast): refactor open/read wrapping [backport 2.21]

.gitlab/benchmarks/serverless.yml
Allow failures temporarily while we figure out what changed and is broken. …
=> ci: skip serverless benchmark failures to unblock CI

.gitlab/benchmarks.yml
Backport #12800 to `2.21` branch.
Allow failures temporarily while we figure out what changed and is broken.
- …
=> ci: skip serverless benchmark failures to unblock CI (#12800) [backport 2.21]

tests/debugging/function/test_discovery.py
We avoid the use of the pytest loader when importing a module in one of the DI tests for decorated function discovery. Because the current implementation of the pytest loader does not implement the get_code method, we cannot wrap around it to get the code object for the module before it is executed. As a workaround in tests, we temporarily remove the pytest loader so that we can import the module under "normal" conditions. Once the test is done we restore the state of the sys.meta_path list. …
=> test(di): avoid pytest loader when importing modules

ddtrace/contrib/internal/pytest/_plugin_v2.py, ddtrace/internal/ci_visibility/_api_client.py, ddtrace/internal/ci_visibility/git_data.py, tests/ci_visibility/api_client/_util.py, tests/ci_visibility/api_client/test_ci_visibility_api_client.py
For attempt-to-fix v2, we have to send the commit message as an argument to the test management endpoint.
- …
=> chore(ci_visibility): support attempt-to-fix v2 API

ddtrace/profiling/collector/_lock.py, releasenotes/notes/profiling-self-acquired-at-963cadba71ac62b8.yaml
```Python
start = None
if hasattr(self, "_self_acquired_at"):
start = self._self_acquired_at
del self._self_acquired_at
```
Above code can raise an `AttributeError`, if there are multiple threads calling on `release()`. Though in such scenarios, except for the thread which actually held and released the lock, such threads would result in a `RuntimeError`, the current behavior makes customers blame our code instead of theirs. 
The following code, by @nsrip-dd, can be used to check whether the code raises an error or not
```Python
import threading
import sys
sys.setswitchinterval(0.0000001)
def unlock(l):
try:
l.release()
except RuntimeError:
pass
except Exception as e:
raise e
while True:
l = threading.Lock()
l.acquire()
threads = [threading.Thread(target=unlock, args=[l,]) for _ in …
```
=> fix(profiling): wrap del with try/except

tests/appsec/integrations/flask_tests/test_flask_remoteconfig.py
the `test_load_testing_appsec_1click_and_ip_blocking_gunicorn_block_and_kill_child_worker` test has this decorator:
```
@flaky(until=1742580778, reason="_request_403 is flaky, figure out the error")
```
and its failing today because `time() > 1742580778`
We need to investigate that error. Removing `flaky`, updating to `skip` and link this problem to task APPSEC-57052
- The …
=> ci(appsec): update flaky test

ddtrace/debugging/_probe/registry.py
We guard the probe registry against potential race conditions when setting the `EMITTING` status. This can happen if a probe that has been instrumented is being deleted, but the instrumentation is triggered in a user thread at around the same time the RC client relies the configuration payload. In this case we simply log the event and do nothing.
The better solution would be to lock the registry access, since the handling of the `EMITTING` status exposes the registry to concurrent access. However, we opted for not introducing a lock to avoid adding blocking in-line on user code.
- The PR …
=> chore(debugging): guard against race on emitting status

ddtrace/contrib/internal/pytest/_atr_utils.py, ddtrace/contrib/internal/pytest/_attempt_to_fix.py, ddtrace/contrib/internal/pytest/_efd_utils.py, ddtrace/contrib/internal/pytest/_plugin_v2.py, ddtrace/contrib/internal/pytest/_retry_utils.py, releasenotes/notes/ci_visibility-fix-junit-xml-retry-count-65de6ad6b9bb35d2.yaml, tests/contrib/pytest/test_pytest_atr.py, tests/contrib/pytest/test_pytest_attempt_to_fix.py, tests/contrib/pytest/test_pytest_efd.py
The pytest JUnit XML plugin uses the test report's [`failed`](https://github.com/pytest-dev/pytest/blob/8.3.x/src/_pytest/junitxml.py#L562) and [`longrepr`](https://github.com/pytest-dev/pytest/blob/8.3.x/src/_pytest/junitxml.py#L201) properties to count failed tests and include them in the output. Because retried tests have their own special statuses (`dd_efd_final_failed`, etc), they don't count as failures, and are excluded from the JUnit XML count. This PR creates a subclass of TestReport that is aware of those special statuses and reports them as passed/failed/skipped accordingly.
This is honestly a bit of a hack. It would probably be best to rewrite the retry logic entirely so it would use normal pytest states, and pass the information that they are retries in some other way. But …
=> fix(ci_visibility): count failed/skipped tests in JUnit XML when retries are enabled

.github/workflows/system-tests.yml, ddtrace/internal/symbol_db/remoteconfig.py
We make changes to the SymbolDB RC adapter to support the recent RC refactor. …
=> chore(symdb): adapt to new RC refactor

.gitlab/scripts/get-riot-hashes.sh, .gitlab/scripts/get-riot-pip-cache-key.sh, .gitlab/tests.yml, scripts/gen_gitlab_config.py
Adds a pip cache to a large number of our CI jobs.
For riot: this does this by using a unique pip cache key per-job based on the sha256sum of all of the `.riot/requirements/*.txt` files for all the venvs matching the suite name or pattern. This way if any deps change we'll invalidate the cache to ensure it doesn't grow in size forever.
For hatch: this uses the job name as the key.
The goal is to cache the downloaded wheels/distributions to save on network bandwidth and effort for downloading every time. This will also help cache built wheels if the downloaded distribution is a source distribution. …
=> ci: add pip cache to CI jobs

ddtrace/appsec/_ddwaf/waf.py, ddtrace/appsec/_ddwaf/waf_mock.py, ddtrace/appsec/_ddwaf/waf_stubs.py, ddtrace/appsec/_processor.py, ddtrace/appsec/_remoteconfiguration.py, tests/appsec/appsec/test_processor.py, tests/appsec/appsec/test_telemetry.py
We need to make sure that removals are applied first in the waf builder.
This PR makes sure of that.
- Avoids …
=> chore(asm): make sure removal are first on waf updates

.gitignore
This PR adds the `.cursor/` directory to the `.gitignore` file to prevent Cursor IDE-specific files from being tracked in the repository.
- Added `.cursor/` to `.gitignore`
- Title is …
=> chore: add .cursor/ directory to .gitignore

ddtrace/internal/remoteconfig/_subscribers.py, ddtrace/internal/remoteconfig/utils.py, ddtrace/internal/remoteconfig/worker.py
We migrate to type hints in the RC subscribers source. This allows us to clean up some of the imports and avoid a few circular references. …
=> chore(rc): migrate to type hints in subscribers

ddtrace/internal/uwsgi.py
We improve the uWSGI support by showing a more informative error when the lack of the import command line option is potentially detected. …
=> chore: improve uWSGI error on missing import option

ddtrace/internal/remoteconfig/product.py, ddtrace/settings/_config.py
We move some of the RC registration logic out of the global configuration and into the RC product to remove circular import paths. We leave it to follow-up work to improve on the modularisation of the current solution. …
=> refactor: move RC registration logic to RC product

.github/workflows/import-analysis.yml, scripts/import-analysis/cycles.py, scripts/import-analysis/requirements-cycles.txt
We extend the import analysis to include a detection of new circular imports that are potentially introduced by the PR the check runs on. Detection is based on the comparison against the base branch, and not in absolute terms. The new checks ensures that no new cycles are introduced, but is not a guarantee that the library itself is cycle-free. …
=> ci: add circular import detection

ddtrace/appsec/_common_module_patches.py, releasenotes/notes/appsec-deepcopy-error-0f898629251881d2.yaml, tests/appsec/app.py, tests/appsec/appsec/test_common_modules.py, tests/appsec/integrations/flask_tests/test_appsec_flask.py
This PR fixes a NotImplementedError that occurred when trying to deepcopy wrapped builtin functions (like `open`) while ASM or IAST were enabled.
When ASM/IAST is enabled, we wrap certain builtin functions to add security instrumentation. However, when these wrapped functions were deepcopied, they would raise a NotImplementedError because the wrapper didn't implement the `__deepcopy__` method:
```python
import copy
copy.deepcopy(open)  # NotImplementedError: object proxy must define __deepcopy__()
```
We've modified the `BuiltinFunctionWrapper` class to properly handle deepcopying by:
1. Implementing `__deepcopy__` to create a new wrapper instance
2. Preserving the original function type through the wrapper
3. Ensuring the wrapped function maintains its original type after deepcopy
- …
=> fix(asm): implement __deepcopy__ for wrapped builtin functions in ASM/IAST

ddtrace/debugging/_expressions.py, ddtrace/debugging/_signal/utils.py, releasenotes/notes/chore-di-support-decimal-e75525e282c50a2f.yaml, tests/debugging/test_debugger.py
We add support to Dynamic Instrumentation for the Decimal type from the standard library. With this change, values of this type will have a more explicit representation in dynamic logs, and can be used, after a convertion to float, in metrics and other expressions. …
=> feat(debugging): add support for Decimal

ddtrace/llmobs/_integrations/anthropic.py, releasenotes/notes/fix-ant-system-219f0c0332831ac4.yaml, tests/contrib/anthropic/cassettes/anthropic_completion_multi_system_prompt.yaml, tests/contrib/anthropic/test_anthropic_llmobs.py
Previously we were assuming the system prompt is just a string. But actually it can be a list of content blocks (similar to the rest of anthropic messages). In this case the input was being dropped since we were setting `content` to be the list of messages.
To fix we just prepend the system prompt to the list of messages and have that undergo the same processing logic that we have for the rest of the messages. …
=> fix(llmobs): support multiple system prompts for anthropic

.github/workflows/build_python_3.yml
https://github.com/DataDog/dd-trace-py/pull/12897 added clang to the musl-i686 image, which breaks the builds for 2.21 currently. Pinning the image to the previous working version while we investigate a better long term fix, but also not block 2.21 PRs and releases in the meantime. See example failures [here](https://github.com/DataDog/dd-trace-py/actions/runs/14132409888/job/39596121749?pr=12786). …
=> ci: pin builds to older musl i686 image

.gitlab-ci.yml
Backport https://github.com/DataDog/dd-trace-py/commit/ab6799af2ab705a0a2d2441b106c6a9815dfdb17 from https://github.com/DataDog/dd-trace-py/pull/12668 to 2.21.
Integrate the latest changes on one-pipeline.
Configure and run the system-tests pipeline (only for ssi tests)
Simplify the pipeline to run the system-tests ssi tests …
=> chore(ci): ssi tests onepipeline [backport 2.21]

ddtrace/internal/ci_visibility/_api_client.py, ddtrace/internal/ci_visibility/constants.py, ddtrace/internal/ci_visibility/coverage.py, ddtrace/internal/ci_visibility/recorder.py, tests/ci_visibility/api/fake_runner_efd_all_pass.py, tests/ci_visibility/api/fake_runner_efd_faulty_session.py, tests/ci_visibility/api/fake_runner_efd_mix_fail.py, tests/ci_visibility/api/fake_runner_efd_mix_pass.py, tests/ci_visibility/api_client/test_ci_visibility_api_client.py, tests/ci_visibility/api_client/test_ci_visibility_api_client_unique_tests_responses.py, tests/ci_visibility/util.py, tests/contrib/pytest/test_pytest_efd.py
CI Visibility: Small renaming from unique tests to known tests …
=> refactor(ci_visibility): rename unique tests to known tests

ddtrace/appsec/_common_module_patches.py, releasenotes/notes/appsec-deepcopy-error-0f898629251881d2.yaml, tests/appsec/app.py, tests/appsec/appsec/test_common_modules.py, tests/appsec/integrations/flask_tests/test_appsec_flask.py
Backport https://github.com/DataDog/dd-trace-py/pull/12716 to 2.21.
This refactor of IAST log messages includes:
- most of the logs have prefixes but no normalized, such as "IAST: ...", "[IAST] ...", "IAST ...".
- Create a hierarchy/namespaces of IAST features (instrumentation, metrics, propagation) and sub-levels:
```
iast::instrumentation::
iast::instrumentation::ast_patching::ast::
iast::instrumentation::ast_patching::compiling::
iast::instrumentation::wrapt::
iast::metrics::error::
iast::propagation::context::
iast::propagation::listener::
iast::propagation::sink_point::
iast::propagation::native::
iast::propagation::native::error::
```
With all these levels, filtering and grouping messages becomes easier, both for use in dashboards and for testing
A lot of logs have been added to …
=> fix(asm): add __deepcopy__ for wrapped builtin functions in asm or iast [backport 2.21]

tests/contrib/mariadb/test_mariadb.py
Reverts DataDog/dd-trace-py#12606
=> Revert "ci(flaky): mark `mariadb` test as flaky for 30 days"

ddtrace/contrib/internal/pytest/_atr_utils.py, ddtrace/contrib/internal/pytest/_efd_utils.py, ddtrace/contrib/internal/pytest/_plugin_v2.py, ddtrace/contrib/internal/pytest/_retry_utils.py, releasenotes/notes/ci_visibility-fix-junit-xml-retry-count-65de6ad6b9bb35d2.yaml, tests/contrib/pytest/test_pytest_atr.py, tests/contrib/pytest/test_pytest_efd.py
Backport 2a506fb25a1bb5791f703329624cd18858dd357d from https://github.com/DataDog/dd-trace-py/pull/12862 to 3.2.
The pytest JUnit XML plugin uses the test report's [`failed`](https://github.com/pytest-dev/pytest/blob/8.3.x/src/_pytest/junitxml.py#L562) and
[`longrepr`](https://github.com/pytest-dev/pytest/blob/8.3.x/src/_pytest/junitxml.py#L201) properties to count failed tests and include them in the output. Because retried tests have their own special statuses (`dd_efd_final_failed`, etc), they don't count as failures, and are excluded from the JUnit XML count. This PR creates a subclass of TestReport that is aware of those special statuses and reports them as passed/failed/skipped accordingly.
This is honestly a bit of a hack. It would probably be best to rewrite the retry logic …
=> fix(ci_visibility): count failed/skipped tests in JUnit XML when retries are enabled [backport 3.2]

.github/workflows/add-2x-backport-tag.yml
Quick GitHub workflow to always label PRs with `backport 2.21` so backporting to the 2.21 branch is an opt OUT, not an opt IN. This should help prevent critical backports from being missed in the 2.21 branch.
It will only skip PRs that are already backports, but by depending on the PR title.
Tested with this PR. …
=> chore: auto opt in all PRs to backport to 2.21

tests/profiling_v2/collector/test_memalloc.py
Add a regression test for races in the memory allocation profiler. The
test is marked skip for now, for a few reasons:
- It doesn't trigger the crash in a deterministic amount of time, so
it's not really reasonable for CI/local dev loop as-is
- It probably benefits more from having the thread sanitizer enabled,
which we don't currently do for the memalloc extension
I'm adding the test so that we have an actual reproducer of the problem
that we can easily run ourselves available to any dd-trace-py
developers, and have it actually committed somewhere people can find it.
It's currently only really useful for local development. I plan to
tweak/optimize some of the synchronization code to reduce memalloc
overhead, and we need a reliable reproducer of the crashes the
synchronization was meant …
=> refactor(profiling): add memalloc race regression test

ddtrace/internal/products.py, tests/internal/test_products.py
We improve the circular reference detection among products to avoid reporting false positive when products fail to load. …
=> chore: avoid false product circular dependency reporting

ddtrace/contrib/internal/azure_functions/patch.py, releasenotes/notes/fix-azure-functions-method-signature-0468812f17348843.yaml, tests/contrib/azure_functions/azure_function_app/function_app.py, tests/contrib/azure_functions/test_azure_functions_snapshot.py, tests/snapshots/tests.contrib.azure_functions.test_azure_functions_snapshot.test_http_get_trigger_arg.json
This PR adds a fix to match the Azure Function method signature using `functools` instead of hardcoding it.
Previously the arguments for the wrap function were hardcoded, resulting in an exception when starting a function where the `trigger_arg_name` was not set to `req` (the default value).
```
Exception: FunctionLoadError: cannot load the http_get_trigger_arg function: the following parameters are declared in Python but not in function.json: {'req'}
```
```
@app.route(
route="httpgettriggerarg",
auth_level=func.AuthLevel.ANONYMOUS,
methods=[func.HttpMethod.GET],
trigger_arg_name="reqarg",
)
def http_get_trigger_arg(reqarg: func.HttpRequest) -> func.HttpResponse:
return func.HttpResponse("Hello Datadog!")
```
https://learn.microsoft.com/en-us/python/api/azure-functions/azure.functions.fun …
=> fix(azure_functions): match method signature using functools instead of hardcoding it

.github/workflows/codeowners.yml, .github/workflows/import-analysis.yml
With the automatic bumping of action versions by dependabot, the comment action broke as it expects parameters with a different name. …
=> ci: fix comment action parameters

ddtrace/appsec/_iast/_taint_utils.py, ddtrace/appsec/_iast/taint_sinks/sql_injection.py, ddtrace/contrib/dbapi.py, ddtrace/contrib/dbapi_async.py, tests/appsec/iast/test_taint_utils.py
This PR reorganizes the SQL injection detection logic by moving it to the IAST folder structure. The changes include:
- Relocated SQL injection detection code from contrib to ddtrace/appsec/_iast/
- Consolidated SQL injection related functionality in a dedicated location
- Improved code organization and maintainability
- Maintained existing functionality while improving code structure
- Updated imports and references to reflect new file locations
This refactoring aligns with our ongoing efforts to better organize IAST-related code and makes the codebase more maintainable by grouping related security features together.
No functional changes are included in this PR, it's purely organizational.
Related to: https://github.com/DataDog/dd-trace-py/pull/13044 and APPSEC-56946
- The PR …
=> refactor(iast): move sql injection logic to iast folder

docs/versioning.rst
This change updates the support level boundaries for the 3.0 release. It also updates language around backports to reduce the amount of bugfixing that happens on old minor versions.
- Title …
=> docs: reduce backport volume promised in docs

ddtrace/appsec/_asm_request_context.py, ddtrace/appsec/_constants.py, tests/appsec/appsec/test_asm_request_context.py
- add support for new private span tags
- add a use case for waf callback failure
- update relevant unit test
APPSEC-56592 …
=> chore(asm): add support for error.type or error.message private span tags

setup.py, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json, tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json, tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json, tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Upgrade libddwaf from 1.24.0 to 1.24.1 …
=> chore(asm): waf upgrade to 1.24.1

tests/contrib/aws_lambda/test_aws_lambda.py
This PR addresses two flaky tests in `tests/contrib/aws_lambda/test_aws_lambda.py`. The issue that needed fixing was that env vars are checked during patch/unpatch. Since unpatch was being called after the env was reset, they were never being unpatched correctly. This PR ensures that the patching and unpatching occurs within the env override. …
=> chore(serverless): remove flaky mark from two serverless tests

tests/llmobs/conftest.py, tests/llmobs/test_llmobs_evaluator_runner.py
Increase the interval for evaluator runner being used in the buffer limit test to try to make it less flaky
previously it was using `active_evaluator_runner` fixture which had a interval of 0.01
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backportin …
=> chore(llmobs): fix flaky evaluator runner log test

ddtrace/appsec/_iast/_metrics.py, ddtrace/appsec/_iast/_taint_tracking/_taint_objects.py, ddtrace/appsec/_iast/_taint_utils.py, ddtrace/appsec/_iast/taint_sinks/ast_taint.py, ddtrace/appsec/_iast/taint_sinks/code_injection.py, ddtrace/appsec/_iast/taint_sinks/command_injection.py, ddtrace/appsec/_iast/taint_sinks/header_injection.py, ddtrace/appsec/_iast/taint_sinks/path_traversal.py, ddtrace/appsec/_iast/taint_sinks/sql_injection.py, ddtrace/appsec/_iast/taint_sinks/ssrf.py, ddtrace/appsec/_iast/taint_sinks/weak_cipher.py, ddtrace/appsec/_iast/taint_sinks/weak_hash.py, ddtrace/contrib/dbapi/__init__.py, ddtrace/contrib/dbapi_async/__init__.py, tests/appsec/iast/test_taint_utils.py, tests/appsec/integrations/django_tests/conftest.py, tests/appsec/integrations/django_tests/test_django_appsec_iast.py
backport https://github.com/DataDog/dd-trace-py/pull/13075 to 2.21
Partial backport of #13046 to align the functions parameters.
(cherry picked from commit 9c8c6d0eb66c67ae261329c0f098dd32b6e67b21)
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backpor …
=> chore(iast): fix iast span metrics [backport 2.21]

tests/contrib/aws_lambda/test_aws_lambda.py
Backport 612d8023f01211303d36501e101760b2231c9e3b from #13039 to 3.2.
This PR addresses two flaky tests in `tests/contrib/aws_lambda/test_aws_lambda.py`. The issue that needed fixing was that env vars are checked during patch/unpatch. Since unpatch was being called after the env was reset, they were never being unpatched correctly. This PR ensures that the patching and unpatching occurs within the env override. …
=> chore(serverless): remove flaky mark from two serverless tests [backport 3.2]

.gitlab/benchmarks/microbenchmarks.yml
This is a stop gap to unblock releases which introduce known performance regressions. In the future we need to continue to block releases that introduce a performance regression. This PR is meant as a quick fix since we don't have any other ways to signal to the release process that we accept the regression. …
=> ci: don't fail with perf regressions on releases

.gitlab/benchmarks/microbenchmarks.yml
Fix for #13135 which incorrectly was looking at the branch name and not the tag name.  …
=> ci: update regression check rules for release tags

tests/profiling/test_accuracy.py
Increase the error margin and remove flaky marker.  …
=> chore(profiling): remove flaky marker on test_accuracy

ddtrace/_trace/trace_handlers.py, releasenotes/notes/fix-azure-functions-timer-trigger-span-kind-internal-a884095b43b2692b.yaml, tests/snapshots/tests.contrib.azure_functions.test_azure_functions_snapshot.test_timer.json
This PR adds a fix to set the span kind to `internal` for Azure Functions timer triggers instead of `server`.
Follows https://github.com/DataDog/dd-trace-py/pull/13055
- …
=> fix(azure_functions): use span kind internal for azure functions timer trigger

.github/CODEOWNERS
Adds codeowner entries that were accidentally omitted in #13081. …
=> chore(llmobs): add codeowner entries for oai_agents integration

ddtrace/appsec/_iast/_taint_tracking/aspects.py, releasenotes/notes/iast-fstring-exception-d460a37b6e44f972.yaml, tests/appsec/iast/aspects/test_str_py3.py
This fixes a bug with f-strings when IAST is enabled: when building an invalid string that should raise an "Unknown format code X" exception, the error wasn't being triggered in certain cases. like
```
f"{text:05d}"
```
Should raise a ValueError("Unknown format code 'd' for object of type 'str'")
- …
=> fix(iast): invalid f-string type conversions exception in format_value_aspect

ddtrace/propagation/http.py
Removing more static circular dependency in the tracer, this prevent a cycle between propagation.http and ddtrace.trace.
APPSEC-57233 …
=> chore(tracer): remove http dependency to trace

ddtrace/internal/utils/cache.py
With this you have a more ergonomic way of referring to the original inner function decorated with `@callonce` decorator. 
```Python
from ddtrace.internal.packages import _package_for_root_module_mapping
original_func = _package_for_root_module_mapping.__closure__[0].cell_contents
original_func = _package_for_root_module_mapping.__wrapped__
``` …
=> chore: use `functools.wraps` in `callonce` decorator

ddtrace/_trace/tracer.py, ddtrace/appsec/_iast/_ast/visitor.py, ddtrace/appsec/_iast/_taint_tracking/_taint_objects.py, ddtrace/appsec/_processor.py, ddtrace/internal/ci_visibility/git_client.py, ddtrace/internal/compat.py, ddtrace/internal/core/__init__.py, ddtrace/internal/gitmetadata.py, ddtrace/internal/periodic.py, ddtrace/internal/utils/time.py, ddtrace/profiling/collector/_lock.py, ddtrace/profiling/collector/pytorch.py, ddtrace/profiling/collector/threading.py, ddtrace/profiling/recorder.py, hatch.toml
Upgrade mypy from 0.991 (Nov 2022) to 1.15.0 (Feb 2025)
update type comments and code accordingly
What could be done next: enable more rules in the mypy rule book.
- All …
=> chore(tracer): upgrade mypy to last version

ddtrace/llmobs/_integrations/langchain.py
validated by running tests enabled in #13181 (we're moving test enablement to that PR, but want to land this fix separately to get in into the 3.5 release, as [we're enabling span linking by default](https://github.com/DataDog/dd-trace-py/pull/13077) in 3.5 for langchain. this is why the PR is a `chore` and not a `fix`, as the feature hasn't landed in a release yet)
before fix:
```
@no_type_check
def __setattr__(self, name, value):  # noqa: C901 (ignore complexity)
if name in self.__private_attributes__ or name in DUNDER_ATTRIBUTES:
return object_setattr(self, name, value)
if self.__config__.extra is not Extra.allow and name not in self.__fields__:
>           raise ValueError(f'"{self.__class__.__name__}" object has no field "{name}"')
E           ValueError: "RunnableSequence" object …
```
=> chore(llmobs): handle pydantic validation for adding datadog spans to langchain instances

ddtrace/_trace/filters.py, tests/tracer/test_filters.py
Addresses: https://github.com/DataDog/dd-trace-py/issues/13157. 
`FilterRequestsOnUrl` was deprecated in v2.21.0 and removed from the public API in v3.0. Since `FilterRequestsOnUrl` is not used within the ddtrace library we can just remove this class. 
This page provides documentation on how to ignore traces with unwanted resource names: https://docs.datadoghq.com/tracing/guide/ignoring_apm_resources/?tab=datadogyaml&code-lang=python …
=> chore(filters): remove unused code

releasenotes/notes/referrer-hostname-8aa6dc6edb9d53b1.yaml
As the title suggests, we need this release note to be formatted correctly so the release script can parse it without issues. Otherwise, the GitHub release notes and the notebook generated are blank.
Long term, we should figure out a job that lints the release notes as part of the CI. …
=> chore: fix malformed release note blocking release script

ddtrace/internal/processor/stats.py
We remove a static circular import on typing in the processor stats module. …
=> refactor: remove cycle in processor stats

ddtrace/contrib/internal/azure_functions/patch.py, releasenotes/notes/fix-azure-functions-timer-trigger-resource-name-5048d2e3bfea7a6c.yaml, tests/snapshots/tests.contrib.azure_functions.test_azure_functions_snapshot.test_timer.json
Add trigger type to resource name for azure functions timer trigger. This is consistent with the resource naming for Azure Functions in the [.NET tracer](https://github.com/DataDog/dd-trace-dotnet/blob/b2f1c6464cf6212d413eaf449efc7e6784412ade/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Azure/Functions/AzureFunctionsCommon.cs#L163). …
=> fix(azure_functions): add trigger type to resource name for azure functions timer trigger

setup.py
The memalloc C extension has debug assert statements. We want them off
by default in case they guard a costly call we wouldn't normally want to
happen. Depending on how the CPython interpreter running setup.py was
built, we may already get -DNDEBUG via the CFLAGS from sysconfig, which
disables asserts. See the [setuptools docs](https://setuptools.pypa.io/en/latest/userguide/ext_modules.html#compiler-and-linker-options).
But rather than rely on that, make sure that asserts
are explicitly disabled for normal builds and explicitly enabled for
debug builds.
- The PR description notes risks …
=> chore(profiling): explicitly set or clear NDEBUG for memalloc extension

ddtrace/llmobs/_llmobs.py, releasenotes/notes/fix-llmobs-session-id-via-tags-6f6b0f7fca47e516.yaml, tests/llmobs/test_llmobs_service.py
This PR makes a fix to how session ID is set on a LLM Obs span.
Session ID (for session tracking) can be explicitly set when starting a span via `LLMObs._start_span(session_id=...)`. We then set this both as the span's `session_id` field and as a tag on the span, `"session_id:..."`. 
However, currently session ID can also be set by using `LLMObs.annotate/annotation_context()` as a tag. This is meant for use cases where the session ID may not be immediately available. The issue here is that when setting as a tag, we don't actually set that value on the span's top level `session_id` field and only set it as a tag. This means that our backend and other event queries made by other products (like RUM/APM) can't 100% rely on that top level event field even if a user did indeed set it as a tag. …
=> fix(llmobs): set session ID on span if annotated as a tag

benchmarks/Dockerfile
Bumping the benchmark docker python version to the latest maintenance version of Python3.12.
In a subsequent PR I'm adding benchmarks for a new errortracking feature. The feature is enabled starting from Python3.10.
However starting from Python3.12 we are using a method which potentially adds some overhead. Therefore the errortracking benchmarks need to run on python3.12.
- …
=> chore: bump python version in benchmark dockerfile

ddtrace/internal/utils/inspection.py, tests/internal/symbol_db/test_symbols.py
We make sure to skip None line numbers when inspecting a code object for all the lines that it covers.
- …
=> chore: skip None line numbers in inspection

ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt, releasenotes/notes/profiling-update-echion-queue-ub-fix-b14e8c603f2e115f.yaml
The stack sampler could read off of an empty queue of frames after
failing to resolve specific frame information, triggering undefined
behavior. This commit updates echion to pick up https://github.com/P403n1x87/echion/commit/0876677add34925dbb5beaa7048226fabaddd0df,
which should fix the issue.
- Backport …
=> fix(profiling): update echion to pick up a potential undefined behavior fix

.gitlab-ci.yml, .gitlab/benchmarks/serverless.yml
This PR adds two variables which can be used to re-run a release process to allow failures from tests and benchmarks.
This mechanism is meant only as a "break glass" procedure if there is something in the CI pipeline preventing us from completing a release and we are willing to accept the risks of not having a green CI run.
Examples could be:
- The release introduces a known/expected performance overhead that we want to allow
- There is a new flaky test that showed up during this release
This mechanism is very broad, meaning it allows entire child pipelines to fail and is not targeted to specific jobs. So you cannot say "benchmark X or test Y are allowed to fail".
In an ideal world these don't need to exist. …
=> ci: add manual break glass options for tests and benchmarks

ddtrace/profiling/collector/_memalloc_tb.c
Right now there is a global scratch buffer used when collecting
tracebacks for memalloc. This is a resource usage optimization. We have
enough space set aside to record a maximum depth traceback. We collect
the traceback and put it in the scratch space. Then, once we know how
many frames there really are, we can allocate a new traceback that's
just the right size and store that for later reporting. This saves
wasted memory and extra work dynamically growing the traceback to the
right size.
However, there is only one scratch buffer. There is a hypothetical
logical race accessing the buffer. Before 2.18, when we added locks, it
was a _real_ logical  race. Essentially what happens is:
- Thread A is going to collect a traceback, and starts using the buffer
- Thread A sets the frame count to 0 …
=> refactor(profiling): pool memalloc traceback scratch buffers

.gitlab/benchmarks/microbenchmarks.yml
Microbenchmarks should be very quick to run. Lowering the default timeout from 1h to 30m will help encourage people to keep the duration low.
Ideally we could lower this even further to <20m. …
=> ci: lower benchmark job timeouts to 30m

docker-compose.yml
Avoid warnings:
```
❯ scripts/ddtest 
WARN[0000] /home/smola/dd/dd-trace-py/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Pulling 1/1
✔ testrunner Pulled                                                                                                    70.3s 
WARN[0000] /home/smola/dd/dd-trace-py/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Creating 1/1
[...]
```
- …
=> chore: remove obsolete version field in docker-compose.yml

ddtrace/appsec/_iast/_metrics.py, ddtrace/appsec/_metrics.py, ddtrace/internal/telemetry/logging.py
Avoid setting `lib_language` tag explicitly on telemetry. This tag is automatically added to all telemetry data based on the HTTP header `DD-Client-Library-Language`.
- …
=> chore(telemetry): remove redundant lib_language tag in telemetry

ddtrace/appsec/_iast/_taint_tracking/aspects.py
Related to: https://github.com/DataDog/dd-trace-py/pull/13239 / APPSEC-56947 …
=> chore(iast): normalize iast logs

ddtrace/appsec/_iast/_handlers.py, ddtrace/appsec/_iast/_iast_request_context_base.py, ddtrace/appsec/_iast/_metrics.py, ddtrace/appsec/_iast/_patch.py, ddtrace/appsec/_iast/_span_metrics.py, ddtrace/appsec/_iast/_taint_utils.py, ddtrace/appsec/_iast/_utils.py
This PR reorganizes functions in the IAST module to improve code organization and maintainability. The changes include:
- Restructuring functions for better logical grouping
- Improving code organization
- No functional changes, purely organizational improvements
The reorganization helps improve code readability and maintainability by grouping related functions together in a more logical way.
Since this is a reorganization change with no functional modifications, existing tests continue to validate the behavior remains unchanged.
Related to: https://github.com/DataDog/dd-trace-py/pull/13239 / APPSEC-56947
- The change includes tests OR the PR description describes a …
=> chore(iast): restructure functions

ddtrace/appsec/_iast/_ast/iastpatch.c
- Stopped hardcoding sizes of allow/denylists in `iastpatch.c`.
- Renamed one of the variables to have uniform naming across allow/denylists count variables.
- All …
=> chore(iast): avoid hardcoding array sizes

ddtrace/internal/telemetry/__init__.py, ddtrace/internal/telemetry/noop_writer.py, ddtrace/settings/_config.py, tests/internal/test_serverless.py
We explicitly disable telemetry when running the python tracer in aws lambda to save on its additional overhead. Despite this, we still import `ddtrace/internal/telemetry/writer.py`, which takes around 35ms to import.
This PR aims to avoid any import of `ddtrace/internal/telemetry/writer.py` when telemetry is disabled.
I packaged `ddtrace`, before and after this commit, into an AWS Lambda function. Without using `datadog-lambda-python`, I simply timed the import of `ddtrace` and sent this value as a metric. Here are the results of this testing.
Interestingly, according to our cold start tracing, the import of `ddtrace/internal/telemetry/writer.py` is around 6.5% of the total time of a cold start invocation. Why then are we not seeing a cold start time reduction of 6.5%? I do not have …
=> perf(serverless): create noop telemetry writer when telemetry disabled

.github/workflows/stale.yml
We have a GHA workflow to auto-close stale PRs, but it seems to not have been closing any.
Adding the missing config variable to let stale PRs (30 days old) get auto-closed after 1 day of no activity.
Successful run [here](https://github.com/DataDog/dd-trace-py/actions/runs/14451814062/job/40526057672).
Example PR with bot comment and close [here](https://github.com/DataDog/dd-trace-py/pull/10886) …
=> chore: fix stale PR closing workflow

ddtrace/internal/products.py, tests/internal/test_products.py
We fix the product manager to handle products that have failed to load. …
=> chore: handle products that fail to load

ddtrace/internal/debug.py, ddtrace/internal/packages.py, releasenotes/notes/perf-telemetry-d9881d20f22013f7.yaml, tests/internal/test_packages.py
TelemetryWriter periodically reports imported dependencies via calling `get_module_distribution_versions()` when new modules are imported. Typically when application is loaded up for the first time, the TelemetryWriter would notice new imports and then it calls with new module names. The function unnecessarily invoked `importlib.metadata`  and replaced the usage with cached distribution name to version mapping. 
See below for benchmark results.  …
=> perf(telemetry): remove call to `importlib.metadata` from `get_module_distribution_versions`

.github/workflows/build_python_3.yml
These new images are more similar to the default ones, including Docker. …
=> ci: update arm64 runners to arm-4core-linux-ubuntu24.04

.github/workflows/all-green.yml
=> chore(ci): do not run all-green job on pushes on main

ddtrace/contrib/internal/openai/_endpoint_hooks.py, releasenotes/notes/beta-chat-completions-f583f4722a831b04.yaml, tests/contrib/openai/test_openai_llmobs.py
ddtrace is throwing when users use `client.beta.chat.completions.stream`. This is because the beta client passes `NOT_GIVEN` explicitly as a keyword argument to an endpoint that we do support tracing for, and when we extract it out we attempt to call `get` on it.
We don't usually bump into this issue since `NOT_GIVEN` is never passed in as an explicit keyword argument by an actual library user
The fix accounts for the `NOT_GIVEN` cause and treats it the same as if `stream_options` was `None`.
We also add a regression test to make sure `client.beta.chat.completions.stream` does not throw
Previous error
```
packages/ddtrace/contrib/internal/openai/_endpoint_hooks.py, line 78, in handle_request
        self._record_request(pin, integration, instance, span, args, kwargs)
    File …
```
=> fix(llmobs): fix parsing for `NotGiven` in beta oai clients

ddtrace/debugging/_probe/model.py, releasenotes/notes/fix-debugger-hashable-probes-4a9ae0b7f1d40791.yaml, tests/debugging/probe/test_model.py, tests/debugging/test_debugger.py
Probes are mutable but have an identity that allows them to be hashed. We make sure that probe instances are hashable. This in turns makes code objects where probes are injected hashable and usable for lookups.
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing …
=> fix(debugging): make probe instances hashable

ddtrace/contrib/internal/trace_utils.py, tests/tracer/test_trace_utils.py
The function `activate_distributed_headers` unconditionally calls
`context = HTTPPropagator.extract(request_headers)`
and then immediately does` context.trace_id`, but under some circumstances (e.g. no distributed-trace headers present) `extract()` can return `None`. This leads to an uncaught
`AttributeError: 'NoneType' object has no attribute 'trace_id'`. 
Fixes issue: #13277
- The change follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html …
=> chore(tracer): handle None in activate_distributed_headers

.github/workflows/system-tests.yml
2.21 is not compatible with the latest changes in `system-tests`, this PR pins to the last know commit in `system-tests` which passes for this version of the code.
- All …
=> ci: pin system-tests commit hash

ddtrace/debugging/_probe/model.py, releasenotes/notes/fix-debugger-hashable-probes-4a9ae0b7f1d40791.yaml, tests/debugging/probe/test_model.py, tests/debugging/test_debugger.py
Backport 3c2015eacdd64496f510fdc37f4743f0c5537b65 from #13309 to 2.21.
Probes are mutable but have an identity that allows them to be hashed. We make sure that probe instances are hashable. This in turns makes code objects where probes are injected hashable and usable for lookups.
- Backport labels are …
=> fix(debugging): make probe instances hashable [backport #13309 to 2.21]

ddtrace/appsec/_iast/_stacktrace.c, tests/appsec/integrations/pygoat_tests/test_pygoat.py
Use more robust method to filter out frames from `ddtrace` module. The previous version would not work in some tests if the relevant frame was in site-packages within a virtual env named `ddtrace`, which happens in tests for #13256. This would generally not affect customers, but misbehaves in our test suite. …
=> chore(iast): improve detection of ddtrace frames

scripts/gen_gitlab_config.py
This is very noisy, you can always re-run the pipeline manually with `PIP_VERBOSE: 1` …
=> ci: reduce build_base_venvs verbosity

ddtrace/profiling/collector/_memalloc_heap_map.c
The cwisstable docs say conflicting things about what happens to an
iterator after an erase_at call. The map_api.h example from the repo
says the iterator is invalid. The internal CWISS_RawTable_erase_at
function, which is source of truth, says the iterator is invalid after
the call. Fix memalloc_heap_map_destructive_copy to just clear after
copying over the entries rather than erasing the iterator.
Note that this is currently dead code. We take the heap profiler lock
prior to freezing the heap profiler and emptying it out. So we can't add
an entry to the frozen array because we'll fail to acquire the lock
needed to do so. This means the map is empty and we won't see the
invalidated iterator. However, this code will run once we rework the
locking. I saw this code crash when pulling in the …
=> refactor(profiler): clear frozen map instead of using invalid iterator

.gitlab-ci.yml, .gitlab/tests.yml
Backport of #13222 to `2.21`
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#i …
=> ci: add manual break glass options for tests and benchmarks (#13222)

ddtrace/appsec/_iast/_stacktrace.c, ddtrace/appsec/_iast/reporter.py, tests/appsec/iast/taint_sinks/test_ssrf.py, tests/appsec/integrations/django_tests/test_django_appsec_iast.py
stackId should report inside vulnerability location, following this system test PR:
https://github.com/DataDog/system-tests/pull/4607
Tests confirmed locally:
- All …
=> chore(iast): stackId should report inside vulnerability location

tests/tracer/test_encoders.py
This PR ensures the `agent_config.trace_native_span_events` global configuration does not leak between test runs. 
Resolves the following ci failures: https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-py/-/jobs/928971572.
Introduced by: https://github.com/DataDog/dd-trace-py/commit/a754504fcd3756f75a54a9f8c95c5257c998d037 …
=> ci(tracing): fix flaky span event encoding test

ddtrace/bootstrap/sitecustomize.py, lib-injection/sources/sitecustomize.py
This change ensures all processes that were instrumented via ssi accurately report their instrumentation source.
When a python process is instrumented via ssi the instrumentation source will be reported as `ssi`. This is expected. However if this process forks the source of the child process will be reported as `cmd_line`. This is unexpected.  …
=> chore(ssi): track ssi source across subprocesses

ddtrace/contrib/internal/pytest/_plugin_v1.py, ddtrace/contrib/internal/pytest/_utils.py
Replaces any instances of os.environ with _get_config for the pytest integration.
Motivation: [APMAPI-1210](https://datadoghq.atlassian.net/browse/APMAPI-1210)
- All …
=> chore(configuration): replace instances of os.environ

ddtrace/debugging/_probe/registry.py, releasenotes/notes/fix-unresolved-pending-probe-removal-80fbf85a9c068122.yaml, tests/debugging/probe/test_registry.py
We prevent an exception from occurring when trying to remove a probe that did not resolve to a valid source code location. …
=> fix(di): prevent exception when removing unresolved probe

ddtrace/appsec/_iast/_handlers.py, ddtrace/appsec/_iast/_patch.py, ddtrace/contrib/internal/starlette/patch.py
Splitting this pull request https://github.com/DataDog/dd-trace-py/pull/13347 into smaller pieces. For IAST, we need to pass the route to the `_iast_instrument_starlette_scope` function.
- …
=> chore(iast): add route to starlette wrapper function

ddtrace/appsec/_iast/_patch_modules.py, ddtrace/appsec/_iast/secure_marks/sanitizers.py, static-analysis.datadog.yml, tests/appsec/app.py, tests/appsec/integrations/flask_tests/test_iast_flask_testagent.py
This PR fix https://github.com/DataDog/system-tests/pull/4602
Add a sanitizer to werkzeug to avoid false positives
APPSEC-57552 …
=> chore(iast): header injection sanitizers

tests/profiling/collector/test_stack.py
There are a couple of gevent-specific tests that seem to be flaky only on Python 3.8. They affect the legacy stack sampling mechanism, which together with support for 3.8, will be decomissioned soon. Therefore it is not worth investigating the cause at this point so we skip the tests instead.
- Backport …
=> test(profiling): skip flaky gevent tests on 3.8

ddtrace/profiling/collector/memalloc.py
While trying out refactors I've sometimes broken the memalloc import.
This happens completely silently. Add at least a debug log so we can
have some information in case failing to import memalloc turns out to be
relevant to a customer issue in the future ("why don't I have any memory
profiling data?")
- …
=> chore(profiling): log when importing memalloc fails

docs/basic_usage.rst
Improves and corrects documentation in the Error Tracking section of `basic_usage.rst`
While writing the Ruby documentation, I found that the python one was missing some precision on the `_INCLUDE` env variable. 
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributi …
=> chore(et): improve error_tracking documentation

ddtrace/contrib/internal/pytest/_atr_utils.py, ddtrace/contrib/internal/pytest/_attempt_to_fix.py, ddtrace/contrib/internal/pytest/_efd_utils.py, ddtrace/contrib/internal/pytest/_plugin_v2.py, ddtrace/contrib/internal/pytest/_retry_utils.py, ddtrace/contrib/internal/pytest/_utils.py, ddtrace/contrib/internal/pytest/plugin.py
This reverts commit 355694dfaef9c39089f9875a4b57dcadd514372a.
This change caused some errors with unittest (which did not run when the original PR was merged).
- All …
=> Revert "chore(ci_visibility): move retry logic to pytest_runtest_protocol (#13376)"

.github/workflows/all-green.yml
This action offers several advantages : 
* it checks status from gitlab (which is THE main advantage)
* it perform an initial check if the job is retried, saving some time
* it's not subject to API limitation (the API call used in `wechuli/allcheckspassed` is limited to 1000 runs)
- Backport labels are …
=> chore(ci): use datadog/ensure-ci-success instead of wechuli/allcheckspassed

tests/appsec/integrations/langchain_tests/test_iast_langchain.py
=> ci(appsec): add flaky decorator to failing langchain tests

ddtrace/appsec/_iast/_langchain.py, tests/appsec/integrations/langchain_tests/test_iast_langchain.py
* Langchain PR https://github.com/langchain-ai/langchain/pull/31238 released in langchain-core 0.3.60 changed the `text` field for generations, which uses to be a field and is now a property. We'll use `_text` when available.
* This reverts commit dba2b3e320a4a0995613fc80d47c7b45b04b133a (PR: https://github.com/DataDog/dd-trace-py/pull/13435)
* Not adding release notes since this only affects unreleased code in https://github.com/DataDog/dd-trace-py/pull/13256
- The change follows the …
=> chore(iast): fix taint tracking in langchain 0.3.60

ddtrace/llmobs/_evaluators/ragas/base.py, ddtrace/llmobs/_evaluators/runner.py, ddtrace/llmobs/_llmobs.py, ddtrace/llmobs/_writer.py
Some class initializers weren't typed which meant there were some attributes not being type-checked despite having type hints. This PR adds those and fixes some of the typing issues that fell through the cracks over time as a result. …
=> chore(llmobs): add additional typing

ddtrace/internal/ci_visibility/git_data.py, releasenotes/notes/ci_visibility-fix-use-git-tag-as-branch-971227009e6496a6.yaml, tests/ci_visibility/test_git_data.py
When called from a GitHub action triggered on a _tag_ push (not a branch push), we would have no branch name available and make some requests to the backend with a `null` branch, causing a 400 to be returned. This PR changes it so that the tag name is used as the branch name in such circumstances.
- …
=> fix(ci_visibility): use git tag as branch name if no branch name available

ddtrace/appsec/_iast/taint_sinks/code_injection.py, ddtrace/internal/writer/writer.py, tests/appsec/app.py, tests/appsec/appsec_utils.py, tests/appsec/integrations/django_tests/conftest.py, tests/appsec/integrations/django_tests/test_django_appsec_iast.py, tests/appsec/integrations/flask_tests/test_iast_flask_testagent.py
This PR addresses an issue in the Interactive Application Security Testing (IAST) module where metastruct data was not being sent if Application Security (AppSec) was disabled.
**Key Changes:**
* Updated the API version handling to ensure metastruct data is transmitted regardless of the AppSec enablement status.
* Refactored the metastruct data sending logic to decouple it from AppSec's state.
* Added tests to validate the correct behavior when AppSec is disabled.
These changes ensure that IAST continues to function correctly and send necessary data even when AppSec is turned off.
- The PR …
=> chore(iast): fix api version to send metastruct data if appsec is disabled

ddtrace/internal/datadog/profiling/dd_wrapper/include/static_sample_pool.hpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/static_sample_pool.cpp, ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp, scripts/cformat.sh
On main even if there's diff `scripts/cformat.sh` doesn't exit with code other than 0, and our CI `hatch run lint:fmt` doesn't block the rest of CI to be run. Modify `cformat.sh` to exit with 1 if there's diff, 0 otherwise. 
Format cpp files and add cwisstable.h to ignore list. 
prechecks doesn't stop CI even though there are diffs on main https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-py/-/jobs/950723647
prechecks fails on c3b072d27a666d9411bd80da232fee5283603d46 https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-py/-/jobs/951192540
- The PR description notes risks …
=> chore: format cpp files and block ci iff there's format diff

ddtrace/profiling/collector/__init__.py, ddtrace/profiling/collector/_lock.py, ddtrace/profiling/collector/memalloc.py, ddtrace/profiling/collector/stack.pyx, tests/profiling_v2/collector/test_asyncio.py, tests/profiling_v2/collector/test_memalloc.py, tests/profiling_v2/collector/test_stack.py, tests/profiling_v2/collector/test_threading.py
Main motivation to this PR is to reduce the diffs when removing recorder from the codebase as part of removing the legacy exporter.  …
=> chore(profiling): make recorder an optional parameter for collectors

ddtrace/appsec/_ddwaf/ddwaf_types.py, ddtrace/appsec/_ddwaf/waf.py
Remove unnecessary `ctypes.byref` in the waf interface. …
=> chore(asm): remove unnecessary byref in waf interface

ddtrace/internal/ci_visibility/git_data.py, releasenotes/notes/ci_visibility-fix-use-git-tag-as-branch-971227009e6496a6.yaml, tests/ci_visibility/test_git_data.py
Backport 88cbdc8e6e459c3cb427912813b2384cb04273fb from #13468 to 3.8.
When called from a GitHub action triggered on a _tag_ push (not a branch push), we would have no branch name available and make some requests to the backend with a `null` branch, causing a 400 to be returned. This PR changes it so that the tag name is used as the branch name in such circumstances.
- The …
=> fix(ci_visibility): use git tag as branch name if no branch name available [backport 3.8]

ddtrace/contrib/internal/pytest/_atr_utils.py, ddtrace/contrib/internal/pytest/_attempt_to_fix.py, ddtrace/contrib/internal/pytest/_efd_utils.py, ddtrace/contrib/internal/pytest/_plugin_v2.py, ddtrace/contrib/internal/pytest/_retry_utils.py, ddtrace/contrib/internal/pytest/_utils.py, tests/contrib/pytest/test_pytest_attempt_to_fix.py
Remove `RetryTestReport` for good, as part of the effort to support `pytest-xdist`. Attempt-to-Fix was the only retry mechanism that still used it; this PR brings it in line with the recent EFD and ATR refactors (#13448 and #13288).
As a bonus, this fixes the miscounting of active Attempt-to-Fix tests in the JUnit XML output. …
=> chore(ci_visibility): remove RetryTestReport, clean up Attempt-to-Fix

ddtrace/internal/packages.py, tests/debugging/origin/test_span.py, tests/internal/test_packages.py
While dogfooding, we noticed that code origins was still sending third-party code for bazel, e.g. this path:
```
/app/domains/dashboardsnotebooks_backend/sharing/apps/apis/shared_dd_query/shared_dd_query.runfiles/dd_source/external/pypi_linux_x86_64_ddtrace/site-packages/ddtrace/_trace/tracer.py
```
We have code specifically to handle the `*.runfiles` path, but we pass the string to a Path and call the resolve which removes the `*.runfiles` segment.
To fix this, we update the path resolution logic in `ddtrace/internal/packages.py` to improve handling of symlinks and add a new test to ensure correct behavior when symlinks are involved. 
* [`ddtrace/internal/packages.py`](diffhunk://#diff-362935abfa156805410cbcdbfa453d011dbc4c77ce21a20c68402ec130c2e76fL116-R117): Updated `_root_module` to …
=> feat(packages): symlinked .runfile pkgs should not be usercode

benchmarks/appsec_iast_aspects/scenario.py, benchmarks/appsec_iast_aspects_ospath/config.yaml, benchmarks/appsec_iast_aspects_ospath/scenario.py, benchmarks/appsec_iast_aspects_split/scenario.py
ospathdirname_aspect microbenchmark tests is very flaky now, we comment this test until we investigate the root of the problem
```
[STDERR] Regression Check  | FAIL! Metric MetricName.EXECUTION_TIME in scenario:iast_aspects-ospathdirname_aspect has regression +21.71%, larger than threshold 20.00%.
```
- …
=> ci(iast): microbenchmark flakiness

.github/workflows/system-tests.yml, scripts/update-system-tests-version.py
Adds a script to help manage updating the pinned system-tests version.
The goal is to introduce some stability into our CI pipeline, especially when managing backport PRs to older branches. …
=> ci: pin system-tests version

ddtrace/contrib/internal/pytest/_plugin_v2.py
As we switched from special retry statuses to plain pytest ones, we don't need to handle retry failures as a special case here; pytest can figure out the exit status on its own.
- Title is …
=> chore(ci_visibility): remove special handling of exit status for failed retries

.github/workflows/all-green.yml
This job can fail for external contributors. It is meant to be informative, it is not a big deal if it fails. …
=> ci: ignore Report codeowners failures from All Green check

tests/contrib/litellm/test_litellm_llmobs.py
The `test_completion_openai_enabled` test is flaky in CI due to some issues patching Open AI to be used within the LiteLLM library. This PR uses `@pytest.mark.skip` to avoid running these tests in CI.
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#back …
=> chore(litellm): skip flaky litellm tests

tests/internal/test_module.py
We refactor the internal module watchdog install-uninstall test to avoid referencing product-specific subclasses. …
=> test(internal): remove specific implementation from general module testing

benchmarks/bm/iast_fixtures/str_methods.py, benchmarks/bm/iast_fixtures/str_methods_py3.py, ddtrace/appsec/_iast/_taint_tracking/aspects.py, tests/appsec/iast/aspects/aspect_utils.py, tests/appsec/iast/aspects/test_format_map_aspect_fixtures.py, tests/appsec/iast/aspects/test_fstrings.py, tests/appsec/iast/aspects/test_modulo_aspect_fixtures.py, tests/appsec/iast/aspects/test_side_effects.py, tests/appsec/iast/conftest.py
Fix IAST validation in fstring aspect. We're considering as unexpected error, format errors like: `Unknown format code 'd' for object of type 'str'`
this PR fixes an error in https://github.com/DataDog/dd-trace-py/pull/13600/files#r2128401733
part of https://github.com/DataDog/dd-trace-py/pull/13600
APPSEC-57578 …
=> chore(iast): fix fstring log message

.gitlab/package.yml
Backport of #12627 to `2.21`
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#i …
=> ci: prevent git fatal warning in download artifacts job [backport 2.21]

ddtrace/contrib/internal/pytest/_plugin_v2.py, releasenotes/notes/ci_visibility-fix-ensure-test-finished-524a9bb93fd6b632.yaml
Currently, if the `pytest_runtest_protocol` hook is overridden in `conftest.py` and skips the Test Optimization hook, the corresponding test span will be left unfinished, which in turn will cause the suite and module to be unfinished until the end of the session. This PR ensures that the test will be finished by the `pytest_runtest_protocol` hook wrapper, so at least the other tests in the session are not affected. …
=> fix(ci_visibility): ensure test span is finished even if pytest_runtest_protocol is overridden

ddtrace/llmobs/_llmobs.py, releasenotes/notes/llmobs-fix-incorrect-exported-trace-id-d35aeea97a8419c4.yaml, tests/llmobs/test_llmobs_service.py
We recently changed how we record our LLMObs trace IDs - from APM trace IDs to new randomly generated ones. However, we missed updating `export_span`. This PR ensures we export the correct trace ID from `export_span`. …
=> fix(llmobs): make sure correct llmobs trace id is returned from `export_span`

ddtrace/debugging/_products/exception_replay.py, releasenotes/notes/feat-er-in-product-enablement-253418007f82a19b.yaml
We add in-product enablement support for Exception Replay. …
=> feat(er): add in-product enablement support

ddtrace/settings/_config.py, docs/configuration.rst, releasenotes/notes/add_DD_RUNTIME_METRICS_RUNTIME_ID_ENABLED-8e9d518dfd0028f2.yaml, releasenotes/notes/add_DD_TRACE_RUNTIME_ID_ENABLED-8e9d518dfd0028f2.yaml, tests/runtime/test_runtime_metrics_api.py
=> chore(config): use DD_RUNTIME_METRICS_RUNTIME_ID_ENABLED instead of DD_TRACE_RUNTIME_ID_ENABLED

.gitignore, setup.py
We add an option to cache download artifacts during the setup to allow for faster local builds. The feature is behind the ``DD_SETUP_CACHE_DOWNLOADS`` flag. Artifacts are downloaded in `.download_cache` within the working directory. To force the setup script to re-download all or some artifacts, one can simply delete the content of this folder. …
=> chore: cache setup downloads

ddtrace/data_streams.py, releasenotes/notes/add-dsm-manual-checkpoint-flag-8ec40cc433070ee6.yaml, tests/datastreams/test_public_api.py
Adds a manual_checkpoint parameter in the public dsm set_consume_checkpoint(), this allows one to turn off the manual_checkpoint:true tag if use of function is not for explicit purpose of manually instrumenting (default remains as manual instrumentation).  …
=> feat(dsm): add manual checkpoint parameter to consume API

.github/workflows/system-tests.yml, ddtrace/appsec/_processor.py
The new version of libddwaf can decide to keep a trace even without security events.
This PR allows to do so.
Also: update system tests version with last commit and remove the agent build step that is now deprecated.
This new internal feature is already checked by new system tests.
APPSEC-58012
- Backport …
=> chore(asm): keep trace without events if waf decides

.github/workflows/system-tests.yml
To enable the last trace tagging tests on our CI, this update the system tests version.
APPSEC-58012
- Avoids …
=> chore(ci): update system tests

ddtrace/appsec/_metrics.py
- Ensure the `waf.config_errors` metrics is generated when there is a waf failed initialisation or update.
- Improve typing in telemetry module for appsec
- This will also be tested in system tests https://github.com/DataDog/system-tests/pull/4788
APPSEC-58013 …
=> chore(aap): report config_errors for waf init failure

ddtrace/contrib/internal/botocore/services/bedrock.py, ddtrace/llmobs/_integrations/bedrock.py, releasenotes/notes/fix-bedrock-stream-0bd52763872967a5.yaml, tests/contrib/botocore/test_bedrock_llmobs.py
Fixes an issue where modifying chunks returned from a bedrock stream impacted our tracing of those chunks. Instead, our tracing should reflect the original response returned regardless of whether or not it was modified.
This is relevant when libraries like langchain delete data from the raw streamed response (e.g. [popping](https://github.com/langchain-ai/langchain-aws/blob/40abb584979a349019d89bbf1cba7d8c56d23664/libs/aws/langchain_aws/chat_models/bedrock_converse.py#L995) `usageMetadata`).
The fix uses an approach where we immediately process stream chunks as they are iterated over, instead of waiting until the entire stream has finished. 
The data flow is like this:
1. a streamed chunk is read from `TracedBotocoreConverseStream`
2. we send that chunk to `_output_stream_processor`, …
=> fix(llmobs): bedrock converse tracing is resistant to modifying the stream

ddtrace/appsec/_handlers.py
This is a followup on #13638, to add the forgotten waf address: `request_path_parameters`. …
=> chore(asm/lambda): add forgotten path parameters

ddtrace/appsec/trace_utils/__init__.py, tests/appsec/appsec/test_appsec_trace_utils.py
Add telemetry support for the legacy ATO SDK.
This will also be tested using system tests https://github.com/DataDog/system-tests/pull/4806
APPSEC-58051 …
=> chore(aap): telemetry wrapper for ato sdk v1

ddtrace/contrib/internal/litellm/utils.py, ddtrace/llmobs/_integrations/utils.py, releasenotes/notes/litellm-fix-out-of-bounds-error-8b4fa7f2f996dca7.yaml
This PR is a workaround for this [bug report](https://github.com/DataDog/dd-trace-py/issues/13700) where LiteLLM users are running into an unhandled exception caused by trying to append a chunk choice to the list of streamed chunks at that choice index.
The root of the issue comes down to where the user is setting the parameter for number of choices in the streamed response. If the `n` parameter was set as a kwarg, then there would be no issue. However, if the parameter was set elsewhere (e.g. in the user's proxy config file), then the `_streamed_chunks` list would incorrectly expect 1 choice which would lead to an indexing error.
I was able to reproduce the issue with the following config and client request:
Config File
```
model_list:
- model_name: gpt-3.5-turbo
litellm_params:
model: …
```
=> fix(litellm): be defensive when appending to streamed chunks

scripts/gen_ext_cache_scripts.py, setup.py
We include the rust extensions in the computation of the hash for native extensions. This allows us to cache the compilation result of rust builds and reuse them in CI.
- …
=> chore: include rust extensions in hash computation

setup.py
We add the dependency on the crashtracker executable to the crashtracker CMake extension to allow incremental builds to use it to decide when to recompile the extension. This also ensures that the executable is cached in our CI jobs and resored as appropriate. …
=> chore(setup): add dependency to crashtracker_exe

ddtrace/llmobs/_llmobs.py
Makes the (lack of) ML App error message more detailed, specifically to state the env var / config that needs to be set to avoid the error in the future.
- All changes …
=> chore(llmobs): make mlapp error message more helpful

ddtrace/llmobs/_llmobs.py, releasenotes/notes/fix-llmobs-ml-app-disabled-7879e1fcb2d1e0da.yaml, tests/llmobs/test_llmobs_service.py
Our `_start_span()` method does a bunch of llmobs-instrumentation/modifications under the hood, even if LLMObs is disabled. Specifically our llm/task/tool/agent/retrieval/workflow/embeddings() methods only log a warning if ML_APP is missing, but still route to our `_start_span()` method, which then continues on to do a ML_APP check (and raises if this is missing), even if LLMObs is disabled. This means if ML_APP is missing, any manual instrumentation will break customer apps if they disable LLMObs.
We need to make `_start_span()` a no-op wrapper around `tracer.trace(...)`. This fix ensures that if llmobs is disabled, we return the span immediately before we start doing llmobs-specific logic.
- The PR description articulates the …
=> fix(llmobs): avoid missing ml app error if llmobs is disabled

benchmarks/django_simple/app.py, benchmarks/django_simple/config.yaml, benchmarks/django_simple/scenario.py
- Add cache configuration and operations to simulate cache miss/hit patterns
- Add benchmark configurations to test performance with individual components disabled
- All …
=> ci(benchmarks): add cache operations and additional variants to Django benchmark

repository.datadog.yml
Add mergegate configuration to allow auto-generated PRs without commit signing …
=> chore(ci): add mergegate configuration

.gitlab/templates/build-base-venvs.yml, .gitlab/templates/cached-testrunner.yml, scripts/gen_gitlab_config.py
We make the dynamic configuration generation script leaner by taking out literal tempate strings into template files. …
=> ci(gitlab): use templates in dynamic configuration

.gitlab/benchmarks/microbenchmarks.yml
These jobs frequently timeout
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html# …
=> ci(benchmarks): skip django startup benchmarks

tests/appsec/suitespec.yml
Keeps timing out, or just barely passing the 20m timeout limit. …
=> ci: set appsec_iast_default job timeout to 30m

ddtrace/appsec/_constants.py, ddtrace/appsec/_processor.py, ddtrace/settings/asm.py, tests/appsec/appsec/test_processor.py, tests/appsec/utils.py
Avoid billing when Appsec is enabled for unsupported lambda events. To keep track of executions with unsupported events, we add a span metric.
- Selectively skip processing the span based on the event
To make the information available, I used the same pattern as the asm context initialization by storing temporary information inside the `ExecutionContext`.
The only difference is that in the case of lambda we only have a single global `ExecutionContext` so we have to clean it up.
This PR relies on: https://github.com/DataDog/datadog-lambda-python/pull/627
- The PR description notes risks …
=> feat(appsec): add metric for unsupported lambda event types

.gitlab/templates/build-base-venvs.yml, .gitlab/templates/debugging/exploration.yml, scripts/gen_gitlab_config.py
We include the stage name of each job so that the running jobs can be grouped-sorted together in many UI settings. …
=> ci: include stage in GitLab job name

ddtrace/debugging/_debugger.py, ddtrace/settings/dynamic_instrumentation.py, tests/debugging/test_debugger.py, tests/telemetry/test_writer.py
This pull request introduces support for loading probe definitions from a file in JSON format, enabling dynamic instrumentation via external configuration. The changes include updates to the `DynamicInstrumentationConfig` class, the debugger's initialization logic, and new tests to validate the functionality.
This can be configured via `DD_DYNAMIC_INSTRUMENTATION_PROBE_FILE` and used in combination with RC.
The JSON should be an array of probe objects in the same format as received via the RC config object, for example:
```
[
{
"id": "12e4866b-c2d0-4948-baf8-bd98027cd457",
"version": 0,
"type": "LOG_PROBE",
"language": "python",
"where": {
"sourceFile": "tests/submod/stuff.py",
"lines": [36],
},
"tags": [],
"template": "Hello new monitoring API",
"captureSnapshot": True,
"capture": …
```
=> feat(DI): add config to create probes through a file

tests/llmobs/conftest.py
Not shutting down the tracer resulted in a bunch of warnings logs about the tracer shutting down at exit.
- …
=> chore(llmobs): shutdown tracer after test case

ddtrace/llmobs/_integrations/langchain.py, releasenotes/notes/langchain-llmobs-token-value-error-e157dce357408791.yaml, tests/contrib/langchain/conftest.py, tests/contrib/langchain/test_langchain_llmobs.py
Fixes a `ValueError` in a bad return when checking for and grabbing token metrics when they aren't available as a top-level field on the langchain chat message response.
```
ValueError: too many values to unpack (expected 2)
```
Additionally, adds a regression test that asserts no tokens are added should both the top-level and sub-level token metrics are missing, and checks that it does not log (since we catch and log these exceptions).
MLOB-3231 …
=> fix(llmobs): resolve `ValueError` from token metrics through LLMs with `langchain`

ddtrace/contrib/internal/unittest/patch.py, ddtrace/internal/ci_visibility/recorder.py, releasenotes/notes/ci_visibility-upgrade-pytest-without-coverage-py-884beebdfd122661.yaml
Our pytest v2 plugin (which was officially released in ddtrace 3.0.0) does not use `coverage.py` for code coverage, but a ddtrace internal code coverage collection mechanism. However, unittest still uses `coverage.py`, and we've been requiring it to be installed for code coverage collection regardless of the test framework used.
This PR makes this dependency unittest-specific, and does not require `coverage.py` for pytest runs anymore.
I have tested this manually (pytest and unittest, with and without `coverage` installed). Writing tests for this is somewhat annoying because `coverage` is always present as a dependency in our pipeline. 
unittest will be switched to the new coverage mechanism once the plugin is rewritten to use the new testing API.
- The PR description includes an overview …
=> chore(ci_visibility): do not require coverage.py for Test Impact Analysis with pytest

.github/chainguard/gitlab.github-access.read.sts.yaml
LANGPLAT-661
The subject needs to match our gitlab project name …
=> ci: fix subject pattern for dd-octo-sts chainguard

.gitlab/benchmarks/bp-runner.microbenchmarks.fail-on-breach.yml
LANGPLAT-659
Reacting to the new SLO gate failures to narrow in on the right value for all tests.
- Avoids …
=> ci(benchmarks): increase otelspan-start-finish-telemetry slo threshold

ddtrace/llmobs/_experiment.py, ddtrace/llmobs/_llmobs.py, ddtrace/llmobs/_writer.py, tests/llmobs/conftest.py, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_projects_filter_name__test-project_get_068dd9a1.yaml, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_projects_post_954d8c3a.yaml, tests/llmobs/test_experiments.py
[MLOB-3265]
This PR does the following:
- Adds support for the DNE client to create and get project IDs based on a project name.
- Adds (undocumented) support for configuring a project name for experiments, via
1. `DD_LLMOBS_PROJECT_NAME` env var, and
2. `LLMObs.enable(..., project_name=...)`
- Makes `project_name` an arg for creating an experiment. If not provided either above or as an arg to the experiment constructor, then raise an error since project names are required.
Minor note: this change also makes LLMObs an instance that is stored on each experiment, not the class, and adds type hints for this.
- The change includes tests OR the PR description describes a …
=> chore(llmobs): add internal support for creating/getting projects

.github/workflows/system-tests.yml
=> ci: update system-tests GitHub Actions ref

ddtrace/llmobs/_constants.py, ddtrace/llmobs/_experiment.py, ddtrace/llmobs/_llmobs.py, ddtrace/llmobs/_writer.py, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_3bf4897d-e6aa-43a3-8d9c-5097b1f85177_batch_update_post_2d58a82a.yaml, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_67c7b6cc-ce98-481e-ab9b-e4925564826c_batch_update_post_a1f44751.yaml, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_264c9f32.yaml, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_d28fa230.yaml, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_35e295b1.yaml, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_3f098e52.yaml, tests/llmobs/test_experiments.py
[MLOB-3272]
Adds support for running experiment task functions concurrently, and tracing said experiment tasks.
Also does the following:
- Make `DatasetRecord.input_data` a more strict `Dict[str, NonNoneJSONType]`. There was a discrepancy between previous iterations of input_data from the DatasetRecord class and the required signature for `task` functions.
- Makes `config` a required input param (can be optional though) for task functions. Making it possibly optional is too clunky of an experience and users should be required to set it
- Private helper to create experiment spans to trace the experiment task run. Note that this is still submitted to the regular LLMObs span track, future PR will handle custom scoping and experiment custom I/O annotation on said span. …
=> chore(llmobs): support running experiment tasks

ddtrace/_monkey.py, ddtrace/contrib/internal/freezegun/patch.py, ddtrace/contrib/internal/pytest/_plugin_v2.py, releasenotes/notes/ci_visibility-deprecate-freezegun-integration-ff99aa77e3907204.yaml, tests/contrib/freezegun/test_freezegun.py
PR https://github.com/DataDog/dd-trace-py/pull/14036 made the tracer report correct span durations in the presence of ddtrace even without this integration, so it can be deprecated (and fully removed in the next major version). This fixes the issues with freezegun ignoring calls from functions wrapped by ddtrace, such as unittest wrappers. …
=> fix(ci_visibility): disable and deprecate freezegun integration

ddtrace/_trace/provider.py
Small performance improvement to avoid calling `Span.finished` which is a computed property more than is necessary in `DefaultContextProvider._update_active`
- All …
=> perf: avoid unncessary calls to Span.finished in _update_active

ddtrace/llmobs/_constants.py, ddtrace/llmobs/_experiment.py, ddtrace/llmobs/_llmobs.py, ddtrace/llmobs/_writer.py, tests/llmobs/test_experiments.py
[MLOB-3298]
This PR adds support for:
1. Annotating experiment  spans with `expected_output`
2. Submitting experiment spans/traces to the LLMObs experiment scope.
Notes:
- I/O for experiment spans currently are annotated the same way as regular LLMObs spans, i.e. `meta.input.value` and `meta.output.value`. It looks like experiments use just `meta.input/output`. This shouldn't be blocking for now but should be followed up on.
- We are currently using context baggage to determine when a span is considered an experiment span. We might want to follow the classic span store/request header pattern in the future.
- The change includes tests OR the PR description describes a …
=> chore(llmobs): submit experiment spans to experiment scope

docs/configuration.rst
We make the code origin configuration recursive to include all the configuration sub-item of the code origin product. …
=> docs: make code origin configuration recursive

releasenotes/notes/profiling-main-package-my-code-f650101b736c412e.yaml
Fixes an incorrectly-formatted release note that causes `reno` to fail …
=> docs: fix release note formatting

ddtrace/contrib/internal/pytest/_plugin_v2.py, tests/contrib/pytest/test_pytest.py
CI Visibility: Improve logging on unexpected coverage format with two different cases. …
=> chore(ci_visibility): change unexpected coverage format error logging

.github/workflows/system-tests.yml, pyproject.toml
Backport https://github.com/DataDog/dd-trace-py/pull/14063 to 3.10
Update the system-tests github action ref
- …
=> ci: update system-tests ref [backport 3.10]

.github/workflows/unit_tests.yml
These were disabled in the past, but the underlying issue appears to have been fixed, we should re-enable these. …
=> ci: re-enable mutli-os-tests for windows + Python 3.13

ddtrace/appsec/_handlers.py, ddtrace/appsec/_processor.py, ddtrace/settings/asm.py
Add a handler for lambda to send a response body to parse.
Additionally fix one typo
This is enabled in datadog_lambda by this PR: https://github.com/DataDog/datadog-lambda-python/pull/636
- …
=> feat(appsec): enable api security for lambda

ddtrace/llmobs/_experiment.py, tests/llmobs/test_experiments.py
Add a url property so users can easily hop into the product after an experiment is run. …
=> chore(llmobs): add experiment url

docs/conf.py
Looks like we accidentally removed a `not` from the check for whether or not we append the `ddtrace` path to syspath (see PR [here](https://github.com/DataDog/dd-trace-py/pull/14105/files)). This should have been for cases where `READTHEDOCS` is NOT TRUE. With this set to true, the builds have been failing due to:
```
autodoc: failed to import module 'contrib.internal.logging' from module 'ddtrace'; the following exception was raised:
--
  | No module named 'ddtrace.internal.native._native'
```
See passing build for this branch [here](https://app.readthedocs.org/projects/ddtrace/builds/29005040/). …
=> docs: fix failing doc builds

ddtrace/contrib/internal/ddtrace_api/patch.py, releasenotes/notes/ddtraceapi-clobber-809a4d88df9a29dc.yaml
Fixes a bug in the ddtrace_api integration in which `patch()` with no arguments, and thus `patch_all()`, breaks the integration. …
=> fix(ddtrace_api): avoid clobbering ddtrace_api's stored tracer instance

ddtrace/contrib/internal/ddtrace_api/patch.py, releasenotes/notes/ddtraceapi-clobber-809a4d88df9a29dc.yaml
Fixes a bug in the ddtrace_api integration in which `patch()` with no arguments, and thus `patch_all()`, breaks the integration. …
=> fix(ddtrace_api): avoid clobbering ddtrace_api's stored tracer instance [backport 3.11]

docker/Dockerfile, scripts/docs/install.sh
LANGPLAT-661
The new testrunner image runs as `bits` and not `root` so we cannot run `apt`/`apt-get` to install packages. …
=> ci: install libenchant in base image

ddtrace/llmobs/_constants.py, ddtrace/llmobs/_llmobs.py, tests/llmobs/_utils.py
This PR adds underlying support to tracking tool definitions, which will soon be added integrations.
Changes made include adding a TOOL_DEFINITIONS constant for span context, setting a meta field for tools (accounted for in dd-source go structs) and adding a tools field to _expected_llmobs_llm_span_event. …
=> chore(llmobs): add underlying support for tool definitions

ddtrace/opentelemetry/__init__.py
Update the outdated opentelemetry ddtrace docs, which (now incorrectly) stated that span events are not supported.  …
=> chore(docs): update opentelemetry doc for span events support

ddtrace/_trace/_span_link.py, ddtrace/_trace/_span_pointer.py, ddtrace/_trace/context.py, ddtrace/_trace/processor/__init__.py, ddtrace/_trace/sampling_rule.py, ddtrace/_trace/span.py, ddtrace/_trace/tracer.py, ddtrace/contrib/internal/celery/app.py, ddtrace/internal/glob_matching.py, ddtrace/internal/rate_limiter.py, tests/integration/test_debug.py, tests/tracer/test_encoders.py, tests/tracer/test_span.py
This PR removes all internal usages of `Span._pprint()`, which is deprecated and will be removed in ddtrace v4.0.0, while delivering significant performance improvements to span formatting.
API Migration
- Replace all internal calls to `Span._pprint()` with `Span.__repr__()` across:
- Span finish debug logs
- Celery integration
- Internal debugging utilities
- Performance Optimizations
- Rewrite `Span.__repr__()` to use f-strings instead of the slow pprint module (5-10x faster)
- Remove unnecessary sorting and formatting operations from span representation
- Eliminate redundant `__str__ = __repr__` assignments in classes that already define `__repr__()`
- Enhanced Debugging
- Add `__repr__` methods to SpanEvent, SpanPointer, and SpanLink objects for better span representations
- Add …
=> perf(span): deprecate Span._pprint, use repr and fstrings instead

ddtrace/llmobs/_constants.py, ddtrace/llmobs/_experiment.py, ddtrace/llmobs/_utils.py, tests/llmobs/test_experiments.py
previously it only printed us1 links, now it will support urls based on the configured dd_site
[tested with us3](https://us3.datadoghq.com/llm/datasets/9a23881a-71a8-45af-9259-aef0c9d5e4bf?page=1) 
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backpor …
=> chore(llmobs): support other sites when printing url

.gitlab/benchmarks/steps/build-baseline.sh
#13984 broke baseline:build job as 1) it upgraded in PyO3 version 2) changed how _taint_tracking is built
- …
=> chore(bench): fix build baseline for microbenchmarks

ddtrace/appsec/_iast/__init__.py, ddtrace/appsec/_iast/_patch_modules.py, ddtrace/appsec/_iast/_taint_tracking/aspects.py, ddtrace/appsec/_utils.py, ddtrace/settings/asm.py
mypy and ruff emits some warnings on aap code.
This PR fixes all those warnings. …
=> chore(aap): improvement to avoid warnings for typing and lint

ddtrace/llmobs/utils.py
Change type of result in ToolResult TypedDict to str, to match the same change for our backend structs in this PR: https://github.com/DataDog/dd-source/pull/250374
- All …
=> chore(llmobs): change result type to str

lib-injection/sources/sitecustomize.py, tests/lib_injection/conftest.py, tests/lib_injection/test_guardrails.py
The previous lib injection telemetry forwarder for tests was a python process, which `ddtrace` would try to trace on startup, causing the telemetry forwarder to time out and telemetry events to not get written. This PR changes the script to be a bash script, so that no test failures are hit due to timeouts. …
=> chore: ensure lib-injection telemetry forwarder uses bash process

.gitlab/benchmarks/bp-runner.microbenchmarks.fail-on-breach.yml, ddtrace/_trace/sampler.py, tests/tracer/test_sampler.py
Ensure an error log is always generated when sampling rules fail to apply.
Previously, failures to apply sampling rules were silent unless DD_TESTING_RAISE=True (which is disabled by default). This lack of visibility made debugging and observability difficult.
This PR guarantees that an error log is emitted whenever sampling rules are not applied, regardless of the DD_TESTING_RAISE setting. …
=> chore(sampling): log error when sampling rules are not applied

ddtrace/internal/wrapping/context.py
We make the check on whehter a function is wrapped with a universal wrapping context stricter. This will now check that we have actual bytecode wrapping, as the attribute check alone is not strict enough. There are examples of frameworks that might copy the state of wrapped functions over to closures, which would lead the current implementation to believe that a function is wrapped when in reality it is not. …
=> chore: stricter wrapping context wrap check

docker/Dockerfile
The error below arose while working on adding [azure-eventhub](https://pypi.org/project/azure-eventhub/) instrumentation. Upgrading to the latest version of [azure-functions-core-tools](https://github.com/Azure/azure-functions-core-tools) resolves this error.
```
A host error has occurred during startup operation '6093904c-5e5b-4c98-8a0f-8a3b1c0cfccc'.
[2025-08-07T18:02:19.062Z] Microsoft.Azure.WebJobs.Extensions.EventHubs: Could not load file or assembly 'System.Memory.Data, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
[2025-08-07T18:02:19.062Z] .
Value cannot be null. (Parameter 'provider')
```
- The …
=> ci: bump azure-functions-core-tools to 4.1.0

.github/workflows/system-tests.yml
backport of https://github.com/DataDog/dd-trace-py/pull/14233/files to unlock 3.11 CI
strategy
guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
[applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)) …
=> chore(ci): update system tests version on 3.11

ddtrace/profiling/collector/memalloc.py
In #14205 we removed the `_interval` parameter for the `MemoryCollector`.
This was a mistake. Now the memory profile collector thread basically
spins in a tight loop because the interval is 0. Add that parameter
back. …
=> chore(profiling): re-accept interval for memory profile collector

ddtrace/_trace/trace_handlers.py, ddtrace/contrib/internal/django/patch.py
We can remove the need for `with ctx.span` and calling an additional `django.process_exception` event by adding support for `should_set_traceback` to the `_finish_span` trace handler.
This will help to further remove span references/usage in the django integration. …
=> chore(django): remove django.process_exception event/handler

ddtrace/internal/wrapping/__init__.py, tests/internal/test_wrapping.py
Useful helpers to ensure we can check if something is already wrapped to avoid re-wrapping it, and we can check if it is already wrapped with a specific function. Useful both for testing and patching.
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#back …
=> chore(internal): add is_wrapped and is_wrapped_with helpers

ddtrace/contrib/internal/openai/patch.py, releasenotes/notes/fix-openai-catch-base-exception-a59c36fa8b0f40a0.yaml
Resolves an issue where our openai integration did not catch/propagate asyncio CancelledError cases.
In OpenAI Agents SDK, the OpenAI library is used internally to make LLM calls. However in a somewhat convoluted scenario, OpenAI Agents makes two LLM calls concurrently via `asyncio.gather(...)`, in which the first one can raise an error, which results in the second LLM call being cancelled sometime later. Our OpenAI integration did not catch this and continued executing and returning the underlying LLM call instead of raising, which caused an exception in the OpenAI Agents SDK which did not expect a None response (this should've cancelled and raised before it got to this point).
This fix addresses this by directly raising if we notice the asyncio task has been cancelled.
We're avoiding a …
=> fix(openai): catch and propagate asyncio.CancelledError

.github/workflows/system-tests.yml, .gitlab-ci.yml, scripts/update-system-tests-version.py
Also update `scripts/update-system-tsts-version.py` to also update `.gitlab-ci.yml` …
=> ci: pin system-tests ref in one-pipeline

.gitlab/benchmarks/steps/detect-baseline.sh, ddtrace/_trace/trace_handlers.py, ddtrace/contrib/internal/django/patch.py, ddtrace/contrib/internal/django/templates.py, tests/contrib/django/conftest.py, tests/contrib/django/test_django_patch.py
~Depends on #14295~
While working on #14273 I was running into some compatibility issues with middleware wrappers using WrappingContext + core api/ExecutionContext.
For now I feel it is safer to just use the regular bytecode wrappers instead until we can reproduce and debug the WrappingContext issues.
- …
=> chore(django): move template wrapping away from wrapping context

ddtrace/llmobs/_writer.py, releasenotes/notes/llmobs-url-override-5d791534021f66a9.yaml
Enable users to override the origin of the url to allow users to send the data to a different local endpoint than APM. …
=> chore(llmobs): add url origin env var

ddtrace/propagation/http.py, releasenotes/notes/single-span-sampling-tags-95f5f0723403ca75.yaml, tests/snapshots/tests.contrib.wsgi.test_wsgi.test_distributed_tracing_nested.json, tests/tracer/test_propagation.py
Fixes an issue where the trace sampling decision tag (_dd.p.dm) was being incorrectly set during header extraction even when a sampling priority was already propagated.
This issue was discovered when [new system-tests ](https://github.com/DataDog/system-tests/pull/5014) were introduced.  …
=> fix(sampling): skip _dd.p.dm tag when sampling priority is propagated

ddtrace/contrib/internal/starlette/patch.py
Minor refactor for performance improvement in starlette integration to reduce number of unnecessary function calls.
In the future, could be good to add starlette/ fastapi microbenchmarks / benchmarks.
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#back …
=> perf(starlette): avoid unnecessary version comparison

ddtrace/contrib/internal/pytest/_plugin_v2.py, releasenotes/notes/ci_visibility-fix-exception-memory-usage-46bffde9569ff4df.yaml
Backport 40d2bdb9306266b4080af50bdc01ada70266086f from #14328 to 3.12.
PR #13448 introduced a dictionary mapping test reports to their exception information. This dictionary prevents the exceptions from being garbage collected, which may lead to excessive memory usage. This PR removes the items from the dictionary after they are consumed. …
=> fix(ci_visibility): do not hold references to test exceptions [backport 3.12]

ddtrace/internal/writer/writer.py, tests/integration/test_integration.py
=> chore: add traceback info to the failed to send message [backport 3.10]

ddtrace/llmobs/_experiment.py, tests/llmobs/test_experiments.py
given a snippet like this
```
def divide(n1, n2):
return n1/n2
def print_divide(n1, n2):
print(divide(n1, n2))
def generate_capital_name_one_word(input_data: Dict[str, Any], config: Dict[str, Any]) -> str:
print_divide(1, 0)
output = oai_client.chat.completions.create(
model=config["model"],
messages=[
{"role": "system", "content": "You will respond only with the name of the capital of the country, nothing else."},
{"role": "user", "content": "What is the capital of France?"},
{"role": "assistant", "content": "Paris"},
{"role": "user", "content": input_data["question"]}],
temperature=config["temperature"]
)
return output.choices[0].message.content
def exact_match(input_data, output_data, expected_output):
raise ValueError("BBB")
return expected_output == output_data
def …
```
=> chore(llmobs): include stack trace and error type if possible when raising error

.gitlab/benchmarks/bp-runner.microbenchmarks.fail-on-breach.yml, ddtrace/internal/writer/writer.py, tests/integration/test_integration.py
=> chore: add traceback info to the failed to send message (#14299) [backport 3.11]

ddtrace/llmobs/_llmobs.py
Adds a debug-level log message to clarify when tracing is disabled because:
- An app key is present
- The DD_TRACE_ENABLED environment variable is not explicitly set to 'true'
- Title is …
=> chore: add debug log for when tracing is disabled due to app key and DD_TRACE_ENABLED

.gitlab/benchmarks/bp-runner.microbenchmarks.fail-on-breach.yml
They are still a bit flaky, and for the ones which are <0.20 ms they don't need that much more headroom.
e.g.
- telemetryaddmetric-1-distribution-metrics-100-times
- 🟥 `execution_time` seen in benchmark [211.852µs; 214.681µs]; SLO is < 210.000µs …
=> chore(benchmarks): give telemetry add metric slos more headroom

ddtrace/internal/core/__init__.py, tests/tracer/test_tracer.py
There did not appear to be any usage of `span=` for these functions, so we can remove the attribute and deprecation warnings now! …
=> chore(internal): remove span attributes from the core api

ddtrace/internal/writer/writer.py, tests/tracer/test_writer.py
This PR enables `NativeWriter` telemetry only on Linux platforms.
The `NativeWriter` will only call enable_telemetry if `DD_INSTRUMENTATION_TELEMETRY_ENABLED` is True and the platform is linux.
This PR will allow to monitor `NativeWriter` metrics during the dogfooding phase while APMSP-2204 is investigated.
Tests have been added to `NativeWriterTests` to check the telemetry is enabled based on the aforementioned conditions. …
=> chore: enable  telemetry only on Linux platforms

ddtrace/internal/remoteconfig/products/client.py, releasenotes/notes/fix-tracer-flare-default-url-fc1232a153f60b45.yaml
This PR fixes the tracer flare when `DD_TRACE_AGENT_URL` is not set. `ddtrace.config._trace_agent_url` is `None` when not set, which leads to `Failed to send tracer flare to Zendesk ticket XXXXXXXXX: Unsupported protocol 'b''' in intake URL 'None'. Must be one of: http, https, unix` when sending a flare. 
This PR makes sure to use the default.
Making tracer flares for Python work again
- Create a VM
- Install the agent
- Install the tracer with SSI
- Create a sample Flask app
- Start it with `DD_TRACE_DEBUG=true`
- Go to the Datadog UI & trigger a flare for your host (no need to force debug logs)
- After a few minutes a Zendesk ticket should be created and contain your tracer flare
- You should see a log starting with `Successfully sent the flare to Zendesk ticket`  …
=> fix: use default trace agent url for tracer flare

ddtrace/_trace/trace_handlers.py, ddtrace/contrib/internal/botocore/patch.py, ddtrace/internal/core/__init__.py
`core.get_item`/`ExecutionContext.get_item` will search through the hierarchy of parents until it finds the key (or cache miss on all parents and returns the default).
Most usage of context set_item/get_item are intended to be for the currently actively context only, and don't need to search for an item potentially on the parent.
When profiling `get_item` can be up to 5-6x slower than `get_local_item` especially for cache misses.
This change updates the `ddtrace/_trace/trace_handlers.py` usage to only use `get_local_item` instead.
- The PR description notes risks associated with the change, if …
=> perf(tracing): use get_local_item instead of get_item

hatch.toml
Gets rid of error:
> ModuleNotFoundError: No module named 'pbr' …
=> ci: upgrade bandit version

setup.cfg
Addresses following message from building wheels
```
With Python 2.7 end-of-life, support for building universal wheels
(i.e., wheels that support both Python 2 and Python 3)
is being obviated.
Please discontinue using this option, or if you still need it,
file an issue with pypa/setuptools describing your use case.
By 2025-Aug-30, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
``` …
=> chore(build): stop setting universal for bdist_wheel

ddtrace/internal/opentelemetry/logs.py, releasenotes/notes/disable-log-injection-on-otlp-logs-deefa7c4d68c08de.yaml, tests/opentelemetry/test_logs.py
- Set config._logs_injection = False in set_otel_logs_provider() to prevent duplicate log attributes
- Added test test_ddtrace_log_injection_otlp_enabled() to verify log injection is properly disabled
- Test covers both DD_LOGS_INJECTION=None and DD_LOGS_INJECTION=true scenarios
- Prevents duplicate log correlation attributes when both ddtrace and OpenTelemetry logs are active
- Ensures clean, non-redundant log data is sent to OpenTelemetry endpoints
- Maintains consistent behavior regardless of ddtrace log injection configuration
- Provides test coverage to verify the log injection disabling behavior works correctly
- The change includes tests OR the PR description …
=> fix(otel): disable log injection when otlp logs are used

benchmarks/core_api/scenario.py, ddtrace/_trace/trace_handlers.py, ddtrace/appsec/_asm_request_context.py, ddtrace/appsec/_handlers.py, ddtrace/appsec/_iast/_handlers.py, ddtrace/appsec/_iast/_iast_env.py, ddtrace/appsec/_processor.py, ddtrace/contrib/internal/botocore/services/bedrock.py, ddtrace/contrib/internal/botocore/services/stepfunctions.py, ddtrace/contrib/internal/celery/app.py, ddtrace/contrib/internal/subprocess/patch.py, ddtrace/contrib/internal/trace_utils.py, ddtrace/contrib/internal/wsgi/wsgi.py, ddtrace/internal/core/__init__.py, ddtrace/internal/datastreams/kafka.py, ddtrace/llmobs/_integrations/bedrock.py, ddtrace/settings/asm.py, tests/appsec/appsec/test_processor.py, tests/contrib/subprocess/test_subprocess.py, tests/internal/test_context_events_api.py
#14404 helped show that people should be clear/intentional over which core API is used for getting items off of an `ExecutionContext`.
This PR aims to rename and update doc strings to try and clarify further what will happen when the function is called.
- `get_item` -> `find_item`: since this API will traverse the context tree looking for the first value for the key. normally this adds the overhead of a loop instruction, but in general will return back quickly. The problem comes from cache misses where we traverse the whole tree just to return the default value.
- `get_local_item` -> `get_item`: make it so any new usage of `get_item` does the more correct thing by default
- `get_items` -> `find_items`: similar as `find_item`, making it more clear we iterate the whole context tree for each …
=> chore(core): rename and document core APIs for clarity

ddtrace/profiling/_traceback.py, tests/profiling/test_traceback.py
`_traceback.py` is unused code. This PR removes that file and the test for it.
Ticker: [LINK](https://datadoghq.atlassian.net/jira/software/c/projects/PROF/boards/11?selectedIssue=PROF-12238) …
=> chore(profiling): remove unused traceback file and test

ddtrace/contrib/internal/asyncpg/patch.py, releasenotes/notes/fix-asyncpg-pool-error-97a58b63370428bc.yaml, tests/contrib/asyncpg/test_asyncpg.py, tests/snapshots/tests.contrib.asyncpg.test_asyncpg.test_pool_custom_connect.json, tests/snapshots/tests.contrib.asyncpg.test_asyncpg.test_pool_without_custom_connect.json
Backports https://github.com/DataDog/dd-trace-py/pull/14436 to 3.12 …
=> fix(asyncpg): fix _TracedConnection error when using the connect option in create_pool [backport 3.12]

ddtrace/internal/_encoding.pyx
For some reason `from json import dumps as json_dumps` is listed twice. This PR removes that.
- Avoids …
=> chore: remove dupe `from json import dumps as json_dumps` from encoding file

.github/workflows/system-tests.yml, .gitlab-ci.yml
Optimizes the system tests CI workflow by building wheels once and reusing them across jobs instead of checking out and building from source multiple times.
The current system tests workflow checks out the dd-trace-py repository and builds from source in each job, leading to:
- Redundant build time across multiple jobs
- Increased CI resource usage
- Longer overall workflow execution time
- Build dependencies required in system-tests
This change centralizes wheel building in a dedicated job and distributes the pre-built wheels to consuming jobs, eliminating the need for build dependencies in system test runners.
- Created a new build-wheels job that calls the existing build_python_3.yml reusable workflow
- Replaced "Checkout dd-trace-py" steps with "Download wheels to binaries directory" …
=> ci: use prebuilt wheels in system-tests

.github/workflows/system-tests.yml, .gitlab-ci.yml
Ci was blocked by django errors due to unpinned dependencies version on weblogs.
This PR update system tests version with problem fixed. …
=> chore(ci): fixing ci by updating system tests version

ddtrace/contrib/internal/pytest/_utils.py
After changes from PRs #14328 and #14344, the dictionaries of test exceptions and reports are cleaned up manually, so they don't have to be `WeakKeyDictionary` anymore. The dictionaries being weak not only don't help, they also cause flakiness in one of the tests (`test_pytest_clears_excinfo_dict_after_use`) because the number of elements in the dicts is not reliable.
- The …
=> chore(ci_visibility): replace weak dicts with regular dicts

tests/llmobs/test_llmobs_eval_metric_agentless_writer.py, tests/llmobs/test_llmobs_evaluator_runner.py
some of our tests hit our real staging endpoint, which itself could sometimes be flaky. following up soon with a real fix to record a response one time and serve it back (since these tests are just checking logging behavior). …
=> ci(llmobs): skip flaky tests hitting faulty endpoint

ddtrace/llmobs/_experiment.py, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_0db64595-86bd-4c4d-aca7-00a13885b5a5_batch_update_post_6f95ccf3.yaml, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_0db64595-86bd-4c4d-aca7-00a13885b5a5_batch_update_post_e366d882.yaml, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_0db64595-86bd-4c4d-aca7-00a13885b5a5_records_get_8bb921e8.yaml, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_900b7824.yaml, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_filter_name__test-dataset-test_dataset_extend_test_dataset_records0__get_d3d212ba.yaml, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_8ba3f242.yaml, tests/llmobs/test_experiments.py
there should be a way to accept a list of records instead of only a single record …
=> chore(llmobs): add extend method to accept a list of records to dataset

ddtrace/llmobs/_experiment.py, ddtrace/llmobs/_llmobs.py, ddtrace/llmobs/_writer.py, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_7ebcf701-2bd3-42d4-9dbd-01bb1169e66f_records_upload_post_36936c02.yaml, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_0134f05d.yaml, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_e03e6dcc-1a71-49ed-82b0-0042d0f7e117_records_upload_post_1d3054f1.yaml, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_e03e6dcc-1a71-49ed-82b0-0042d0f7e117_records_upload_post_ca121309.yaml, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_ee7fe7e8-e947-4d0e-be54-be22314ca561_records_upload_post_6b357ece.yaml, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_fd975cd7.yaml, tests/llmobs/test_experiments.py
**case 1: create dataset from CSVs**
with big datasets / big CSVs, we will run into timeout errors 
```
File "/Users/gary.huang/go/src/github.com/DataDog/llm-observability/preview/experiments/notebooks/test.py", line 23, in <module>
dataset = LLMObs.create_dataset_from_csv(csv_path="/Users/gary.huang/Downloads/weatherAUS.csv", dataset_name="weatheraus-2", input_data_columns=["Date", "input", "Evaporation", "Sunshine"], expected_output_columns=["RainTomorrow"])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/gary.huang/go/src/github.com/DataDog/llm-observability/preview/ex …
```
=> chore(llmobs): use upload endpoint for CSV's and large pushes

ddtrace/contrib/internal/redis/asyncio_patch.py, releasenotes/notes/fix-redis-command-stack-2ef2be7f28c2e9ee.yaml, tests/contrib/redis/test_redis_cluster_asyncio.py, tests/snapshots/tests.contrib.redis.test_redis_cluster_asyncio.test_pipeline_command_stack_count_matches_metric.json
Github Issue: #13598
- Fix Redis asyncio cluster pipeline tracing for redis-py ≥ 6.2.0
- now supports both command_stack and _command_stack since _command_stack was removed
- Prevents AttributeError and ensures pipelines are traced correctly across versions …
=> fix(redis): add compatibility with redis version 6.2.0

ddtrace/_trace/_span_pointer.py, releasenotes/notes/fix-spanpointer-repr-565ebb8e6679ebde.yaml, tests/tracer/test_span.py
In the _SpanPointer.__repr__ method, it's trying to access self.direction and self.hash, but these attributes don't exist on the object. The _SpanPointer class:
1. It inherits from SpanLink
2. The direction and hash information are stored in the attributes dictionary as "ptr.dir" and "ptr.hash"
Therefore the fix. …
=> fix(tracing): span pointer __repr__

ddtrace/llmobs/_integrations/openai_agents.py, ddtrace/llmobs/_integrations/pydantic_ai.py, ddtrace/llmobs/_integrations/utils.py, releasenotes/notes/openai-agents-support-reasoning-a782615651107cc9.yaml, tests/contrib/openai_agents/test_openai_agents_llmobs.py
While QA-ing our agentic integrations, I noticed a bug in the current Open AI Agent's output message parsing. The content field on OpenAI's `ResponseReasoningItem` is optional ([ref](https://github.com/openai/openai-python/blob/2adf11112988e998fcf5adb805bae38501d22318/src/openai/types/responses/response_reasoning_item.py#L27-L51)) which we were not handling properly leading to potential `NoneType` errors like the one below:
```
File "/Users/nicole.cybul/go/src/github.com/DataDog/dd-trace-py/ddtrace/llmobs/_integrations/utils.py", line 1161, in llmobs_output_messages
for content in item.content:
^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```
While investigating this issue, I noticed that our OpenAI integration had a nearly identical implementation for parsing input and …
=> fix(llmobs): [MLOB-3863] openai agents support reasoning messages

ddtrace/internal/remoteconfig/_connectors.py, releasenotes/notes/rc_switch_to_typecode-9409c92e8a07a8be.yaml
This switches the shared data for the remote configuration PublisherSubscriberConnector to use a typecode instead of an explicit type to take advantage of an internal mapping. This should be more reliable across Python versions and fix an issue with Python3.13:
```
get_mp_context().Array(c_char, SHARED_MEMORY_SIZE, lock=False): TypeError: this type has no size
```
This change should be identical, and for more information, see the docs here:
- https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Array
- https://docs.python.org/3/library/array.html#module-array
- https://docs.python.org/3/library/ctypes.html
Refs: DEBUG-4453
Relevant stacktrace:
```
self.data = get_mp_context().Array(c_char, SHARED_MEMORY_SIZE, lock=False) …
```
=> fix(rc): switch from type to typecode for mp reliability

.github/workflows/system-tests.yml, .gitlab-ci.yml, ddtrace/debugging/_exception/replay.py, releasenotes/notes/fix-er-reverse-tracebacks-44a52d4f1601ca1f.yaml, tests/debugging/exception/test_replay.py
The introduction of the maximum number of frames to capture in Exception Replay has caused the capture to be truncated at the outermost exception end, close to the exception handler frame. This follows the natural ordering of traceback frames in traceback objects, which go in the opposite direction of stack traces. We reverse the order of the frames in an exception chain to ensure that we start capturing from the leaf frame of the innermost exception, thus starting from the end where the exception was actually thrown. We also ensure to keep the numbering consistent with the current implementation to allow for the correct matching on the UI side.
- The change includes …
=> fix(er): start capturing from the leaf frame

ddtrace/appsec/_metrics.py
Remove unnecessary waf.config_errors reportings:
- verbatim from the RFC: 
> appsec.waf.config_errors: this metric counts the configuration errors as reported by libddwaf. Note that this tag doesn’t count the number of times a configuration failed to load but rather the count of individual elements within the configuration which failed to load with an error (as opposed to a warning), currently this may need to be extracted from the *.errors key within diagnostics.
The reporting of individual errors extracted from the diagnostics is already performed in the `DDwaf._set_info` method. The one removed is called in `AppSecSpanProcessor._update_rule` and counts the number of times a configuration failed to load which should not be done as per the RFC.
- The PR description includes an overview …
=> chore(appsec): remove extra waf.config_errors reporting

tests/llmobs/test_llmobs_evaluator_runner.py
skips flaky test where a cassette (fixture) was removed. we'll be implementing a better CI solution in the testagent to later re-enable this test (plus the others that had cassettes generated but weren't unskipped (oops 😅)) …
=> ci(llmobs): skip flaky test again

ddtrace/appsec/_ddwaf/waf.py, ddtrace/appsec/_metrics.py
Add the `action` tag with value `init` or `update` on the `waf.config_errors` telemetry event to be in accordance with RFC-1051. …
=> chore(appsec): add action tag on waf.config_errors

.github/workflows/system-tests.yml, .gitlab-ci.yml
Add the scenario APPSEC_STANDALONE_RASP in the system-tests ci job. It was introduced in: https://github.com/DataDog/system-tests/pull/5284 …
=> test: add APPSEC_STANDALONE_RASP to the scenario list

.github/workflows/system-tests.yml, .gitlab-ci.yml, .gitlab/benchmarks/bp-runner.microbenchmarks.fail-on-breach.yml, ddtrace/appsec/_iast/_taint_tracking/context/taint_engine_context.cpp, ddtrace/appsec/_iast/_taint_tracking/context/taint_engine_context.h, ddtrace/appsec/_iast/_taint_tracking/native.cpp, riotfile.py
Following https://github.com/DataDog/dd-trace-py/pull/14513 that PR introduces a potencial conflict when a application shutdown exiting with a bad status code. the traceback suggests the vector’s internal state is invalid so the crash happens when constructing an iterator. I'm adding extra validations and a safe shutting down
```
#4  0x000077f0263304d7 in std::vector<std::shared_ptr<std::unordered_map<unsigned long, std::pair<long, std::shared_ptr<TaintedObject> >, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::pair<long, std::shared_ptr<TaintedObject> > > > > >, std::allocator<std::shared_ptr<std::unordered_map<unsigned long, std::pair<long, std::shared_ptr<TaintedObject> >, std::hash<unsigned long>, std::equal_to<unsigned …
```
=> chore(iast): ci_visibility interaction

.github/workflows/build_python_3.yml
This isn't ideal, but will help for now until we can address build duration.
Current duration is 20+m, with this it is under 15 minutes. …
=> ci: use larger wheel building runners

ddtrace/debugging/_uploader.py, tests/debugging/test_uploader.py
`set_track_endpoints` was recently introduced to protect against scenarios where the agent version can change over time (https://github.com/DataDog/dd-trace-py/pull/14568).
Unfortunately, this introduced a bug where the track queue would be reset such that the counter would look empty but the buffer would fill, leading to unrecoverable BufferFull errors.
This fixes that by preserving the queue metadata when the cache is reset.
refs: DEBUG-4516 …
=> chore(debugger): fix issue with re-initializing uploader tracks

ddtrace/llmobs/_experiment.py, ddtrace/llmobs/_llmobs.py, ddtrace/llmobs/_writer.py, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_experiments_9e046fc7-cf3f-4f01-b5ed-e5e7746fefa8_events_post_1edd9d51.yaml, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_experiments_9e046fc7-cf3f-4f01-b5ed-e5e7746fefa8_events_post_977047ce.yaml, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_experiments_9e046fc7-cf3f-4f01-b5ed-e5e7746fefa8_events_post_ac74921f.yaml, tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_experiments_9e046fc7-cf3f-4f01-b5ed-e5e7746fefa8_events_post_e476f464.yaml, tests/llmobs/test_experiments.py
- changes the ExperimentResult class to have summary eval results and the per experiment row results
- adds the ability to define and run summary evaluators
example:
given this script
```
#!/usr/bin/env python
import os
import math
import random
from dotenv import load_dotenv
load_dotenv(override=True)
from ddtrace.llmobs import LLMObs
LLMObs.enable(
api_key=os.getenv("DD_API_KEY"),
app_key=os.getenv("DD_APPLICATION_KEY"),
project_name="Onboarding",
ml_app="Onboarding-ML-App",
)
dataset = LLMObs.create_dataset_from_csv(
csv_path="./data/taskmaster.csv",
dataset_name="taskmaster-mini-314",
input_data_columns=["prompt", "topics"],
expected_output_columns=["labels"],
)
dataset.as_dataframe()
def return_hello(input_data, config):
return "hello"
def return_2(input_data, output_data, …
```
=> feat(llmobs): add summary evaluator functionality for datasets & experiments

ddtrace/debugging/_uploader.py
Small tweak to rate-limit the number of warning logs to at most once an hour. At some point we should also do this for:
```
[DEBUG] ddtrace.internal.remoteconfig.worker: Agent is down or Remote Config is not enabled in the Agent
Check your Agent version, you need an Agent running on 7.39.1 version or above.
Check Your Remote Config environment variables on your Agent:
DD_REMOTE_CONFIGURATION_ENABLED=true
```
Since it's quite noisy as well, but it's behind a DEBUG flag so less important.
=> chore(debugger): rate-limit agent warning logs to once an hour

tests/internal/crashtracker/test_crashtracker.py, tests/internal/crashtracker/utils.py, tests/utils.py
[Ticket](https://datadoghq.atlassian.net/jira/software/c/projects/PROF/boards/11?selectedIssue=PROF-12582)
This PR renames the function `wait_for_crash_reports` to `wait_for_crash_messages` and other uses of `reports` to `messages` where necessary. This is because the crashtracker emits two types of messages, crash reports and crash pings, so it is misleading to call both as crash reports. 
This PR also does a bit of updating of logic around how we set up our mock client to handle crash messages. Now, the crash tracker sends two messages, `crash_ping` and `crash_report`. The `wait_for_crash_reports` used to work by spinning for `N` cycles and each time, calling `TestAgentClient.crash_reports()`, which was a function that returned all the requests originated from crashtracker within that …
=> chore(crashtracking): fix flaky test around receiving crash messages

.github/workflows/requirements-locks.yml, .gitlab/templates/cached-testrunner.yml, .gitlab/testrunner.yml, setup.py
This change adds Python 3.14 to the list of runtime versions available in the shell for some gitlab and github workflows. It also skips building of the profiling extension under 3.14, since the profiling product currently doesn't work with this version.
Behavior under 3.14 isn't validated in tests - for now it's enough to know that this change doesn't break any existing tests.
This was pulled out of https://github.com/DataDog/dd-trace-py/pull/14264, which will include automated testing of this change under 3.14.
=> chore: avoid building profiling extension under 3.14

.github/workflows/system-tests.yml, .gitlab-ci.yml
The scenario APPSEC_REQUEST_BLOCKING has been merged into APPSEC_BLOCKING_FULL_DENYLIST in the system-tests project. This means tests that were previously run under APPSEC_REQUEST_BLOCKING will now execute using APPSEC_BLOCKING_FULL_DENYLIST (https://github.com/DataDog/system-tests/pull/5277)
This PR just cleans up the pipeline by removing the reference to the no-longer-existing scenario and updates ST version
=> chore(ci): removes APPSEC_BLOCKING from system-tests

ddtrace/contrib/internal/flask/patch.py, releasenotes/notes/flask_endpoint_discovery_fix-7f98200c2fa342c4.yaml, tests/appsec/contrib_appsec/flask_app/app.py, tests/appsec/contrib_appsec/utils.py
Some problems were found on dogweb with flask.
This fix ensures the `methods` value is properly iterable.
Also: use the default "GET" method as specified in the Flask documentation in case no methods have been defined.
Add a specific endpoint with methods=None to the flask application for appsec_threats test as a regression test, triggering the bug in previous versions of the tracer.
APPSEC-59242
=> fix(aap): fix flask patch for none methods

ddtrace/internal/datadog/profiling/stack_v2/__init__.pyi, ddtrace/profiling/collector/__init__.py, ddtrace/profiling/collector/_lock.py, ddtrace/profiling/collector/asyncio.py, ddtrace/profiling/collector/memalloc.py, ddtrace/profiling/collector/stack.pyi, ddtrace/profiling/collector/threading.py
This PR improves typing in the profiling codebase:
- It fixes it by replacing certain type annotations with the actual type where there were mismatches
- It makes it more specific in several places by replacing catch-all inferred types with the right ones 
- It makes it more modern by using actual type hints instead of typing comments
Note that due to how certain things work (namely, `envier`) and the many uses of untyped C extensions,  `getattr` and patching here and there, typing is still far from perfect. 
The rationale for this change is to make it easier to understand how the code works, as well as spot possible bugs early in the development cycle.
Notes
- This is not a functional change and as such, does not have a dedicated testing strategy 
- There are no known risks, as the code …
=> chore(profiling): small typing improvements

.github/CODEOWNERS
Team name changed from API to Capabilities a while ago - this change is required to reflect this in Github teams
=> chore(codeowners): update codeowners to rename apm-sdk-api to apm-sdk-capabilities

.gitlab-ci.yml, ddtrace/contrib/internal/django/database.py
We added ast-grep and a custom rule for checking `ddtrace.trace.Pin` usage and warning that it is deprecated.
We updated CI to run our ast-grep pattern test suite (tests that our rules work), but we never actually ran the "scan" which validates the repo for the rules.
There is 1 known violation in the codebase, I opened the draft PR first with adding the `hatch run lint:sg` to ensure it caught the issue first before fixing the violation.
=> ci: actually validate the ast-grep rules against the repo

.gitlab/benchmarks/bp-runner.microbenchmarks.fail-on-breach.yml, benchmarks/core_api/config.yaml, benchmarks/core_api/scenario.py, ddtrace/internal/core/event_hub.py, tests/internal/test_context_events_api.py
No one is actively using this feature, so let's remove to save on API footprint + overhead until we do actually need it.
=> chore: remove unused core.on_all function

ddtrace/internal/opentelemetry/logs.py
Removing useless metric. We can use telemetry configurations to track when/where opentelemetry logs are enabled.
This metric isnt tested 
No risk. This metric is already rejected by telemetry intake
Writing this PR description took longer than making this change.
=> chore(otel): remove useless metric

tests/internal/test_serverless.py
Customer reported that a class name changed in the most recent version of ddtrace which was then causing errors when attempting to import `datadog_lambda`. See https://github.com/DataDog/datadog-lambda-python/pull/661 and https://github.com/DataDog/dd-trace-py/pull/14653.
It's just some tests, so risk is low.
Added additional tests on the `datadog_lambda` side as well, including running our unit tests twice a day. See https://github.com/DataDog/datadog-lambda-python/pull/662.
=> chore(serverless): test to ensure that all imports in datadog-lambda-python still valid

ddtrace/debugging/_exception/replay.py, ddtrace/debugging/_origin/span.py, releasenotes/notes/fix-debugger-exception-replay-path-type-5180b5cf0d482e9e.yaml
Exception replay was failing when enabled via remote configuration due to using `pathlib.Path` instead of `ddtrace.internal.compat.Path`. The `is_user_code()` function uses `@singledispatch` and is only registered for the `compat.Path` type, causing `Unsupported type <class 'pathlib.PosixPath'>` errors that silently prevented snapshot capture.
This issue only manifested when enabled via RC (vs environment variable) due to module initialization timing differences.
Changes:
- Replace `pathlib.Path` import with `ddtrace.internal.compat.Path` in replay.py
- Replace `pathlib.Path` import with `ddtrace.internal.compat.Path` in origin/span.py
- Add exception logging in `_attach_tb_frame_snapshot_to_span` for debugging
Fixes exception replay not capturing snapshots when enabled through remote …
=> fix(er): use correct Path type in exception replay (and code origin)

ddtrace/constants.py, ddtrace/contrib/internal/ray/utils.py, tests/snapshots/tests.contrib.ray.test_ray.test_actor_and_task.json, tests/snapshots/tests.contrib.ray.test_ray.test_actor_interactions.json, tests/snapshots/tests.contrib.ray.test_ray.test_args_kwargs.json, tests/snapshots/tests.contrib.ray.test_ray.test_core_api_deactivated.json, tests/snapshots/tests.contrib.ray.test_ray.test_nested_tasks.json, tests/snapshots/tests.contrib.ray.test_ray.test_simple_actor.json, tests/snapshots/tests.contrib.ray.test_ray.test_simple_get.json, tests/snapshots/tests.contrib.ray.test_ray.test_simple_put.json, tests/snapshots/tests.contrib.ray.test_ray.test_simple_task.json, tests/snapshots/tests.contrib.ray.test_ray.test_simple_wait.json
This micro will enable our backend to differentiate AI Obs spans from other DJM spans, so that customers are not billed for AI Observability spans as part of their APM bill.
After installing ddtrace from local, run Ray locally, run a sample job and [make sure the new spans get tagged with the new _dd.ai_obs.enabled metric](https://dd.datad0g.com/apm/traces?query=%40component%3Aray&agg_m=count&agg_m_source=base&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=false&graphType=waterfall&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=desc&spanID=2509930093327428234&spanType=all&storage=hot&timeHint=1759854974570&trace=AwAAAZm_h9ZqCDBU7wAAABhBWm1faDktREFBQkJQSC0yTlhVeF8tcmsAAAAk …
=> chore(mlobs): set a special flag to distinguish AI Obs spans from DJM

ddtrace/internal/ffande/__init__.py, ddtrace/internal/ffande/_native.py, ddtrace/internal/ffande/product.py, ddtrace/internal/native/__init__.py, ddtrace/internal/native/_native.pyi, src/native/ffande.rs, src/native/lib.rs, tests/internal/ffande/test_ffande.py
Feature Flagging and Experimentation is being implemented in `libdatadog` and we need to send Remote Configuration updates to it.
This is a skeleton for discussion to be filled in properly when the FF&E code has landed in `libdatadog`.
All the tests are fake right now since there is no code on the native side.
=> feat: skeleton RC product for FF&E
